import {
  type TheoryBadgeClaimBoundaryV1,
  type TheoryBadgeEdgeV1,
  type TheoryBadgeV1,
} from "../contracts/theory-badge-graph.v1";

const PREBIOTIC_BRIDGE_BOUNDARY: TheoryBadgeClaimBoundaryV1 = {
  diagnosticOnly: true,
  doesValidateNHM2: false,
  validationClaimAllowed: false,
  physicalMechanismClaimAllowed: false,
  promotionAllowed: false,
};

const docRef = (path: string, id?: string, note?: string): TheoryBadgeV1["sourceRefs"][number] => ({
  kind: "doc",
  path,
  id: id ?? null,
  note: note ?? null,
});

const literatureRef = (id: string, note?: string): TheoryBadgeV1["sourceRefs"][number] => ({
  kind: "literature_ref",
  id,
  note: note ?? null,
});

const payload = (args: {
  id: string;
  expression: string;
  displayLatex: string;
  targetVariable: string;
}): TheoryBadgeV1["calculatorPayloads"][number] => ({
  id: args.id,
  expression: args.expression,
  displayLatex: args.displayLatex,
  preferredAction: "solve_with_steps",
  targetVariable: args.targetVariable,
  setupContext: null,
});

const prebioticBadge = (badge: Omit<TheoryBadgeV1, "claimBoundary">): TheoryBadgeV1 => ({
  ...badge,
  claimBoundary: PREBIOTIC_BRIDGE_BOUNDARY,
});

export const ASTROCHEMISTRY_PREBIOTIC_THEORY_BADGES: TheoryBadgeV1[] = [
  prebioticBadge({
    id: "astrochemistry.aromatic_carbon.interstellar_context",
    title: "Interstellar Aromatic Carbon Context",
    plainMeaning:
      "Represents aromatic carbon chemistry in circumstellar and interstellar environments as astrochemical context.",
    whyItMatters:
      "It anchors prebiotic-organic discussions in stellar carbon enrichment without implying biology, reward, consciousness, or collapse.",
    subjects: ["astrochemistry", "aromatic_carbon", "interstellar", "stellar_carbon"],
    level: "model",
    status: "diagnostic",
    simulationOwners: ["astrochemistry_prebiotic", "stellar_reference"],
    equationFamilies: ["astrochemistry_context", "aromatic_carbon_context"],
    tags: ["aromatic_carbon", "stellar_context", "diagnostic_context"],
    equations: [
      {
        id: "aromatic_carbon_context_reference",
        role: "noncomputable_reference",
        displayLatex: "\\mathrm{stellar\\ carbon}\\rightarrow\\mathrm{aromatic\\ carbon\\ chemistry}",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["stellar_carbon_synthesis"],
        outputSymbols: ["aromatic_carbon_context"],
      },
    ],
    units: [],
    assumptions: [
      "Aromatic-carbon evidence is astrochemical context.",
      "Aromatic carbon does not imply biology, dopamine inheritance, consciousness, or objective collapse.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      docRef(
        "docs/architecture/astrochemistry-prebiotic-neuro-consciousness-bridge-plan.md",
        "interstellar_aromatic_carbon_chemistry_definition",
      ),
      docRef("docs/knowledge/physics/interstellar-aromatic-carbon-chemistry.md"),
      literatureRef("ESA-ISO-benzene-in-space", "Aromatic ring molecule detection in carbon-rich stellar contexts."),
    ],
    hintKeys: {
      subjects: ["astrochemistry", "aromatic_carbon", "interstellar", "stellar_carbon"],
      symbols: ["aromatic_carbon_context", "stellar_carbon_synthesis"],
      unitSignatures: [],
      repoPaths: [
        "docs/architecture/astrochemistry-prebiotic-neuro-consciousness-bridge-plan.md",
        "docs/knowledge/physics/interstellar-aromatic-carbon-chemistry.md",
      ],
      equationFamilies: ["astrochemistry_context", "aromatic_carbon_context"],
      simulationOwners: ["astrochemistry_prebiotic", "stellar_reference"],
    },
  }),
  prebioticBadge({
    id: "astrochemistry.fullerene.c60_stellar_context",
    title: "C60 Stellar/Circumstellar Context",
    plainMeaning:
      "Represents fullerene C60 as a spectral carbon-chemistry context in circumstellar or interstellar environments.",
    whyItMatters:
      "It lets Helix discuss buckyballs observed in stellar or circumstellar light without turning that observation into a life, consciousness, or collapse claim.",
    subjects: ["astrochemistry", "fullerene", "c60", "spectroscopy", "stellar_carbon"],
    level: "model",
    status: "diagnostic",
    simulationOwners: ["stellar_reference", "astrochemistry_prebiotic"],
    equationFamilies: ["spectral_observable", "planck_relation", "astrochemistry_context"],
    tags: ["fullerene", "buckyball", "stellar_context", "calculator_loadable"],
    equations: [
      {
        id: "c60_feature_frequency",
        role: "calculator_demo",
        displayLatex: "f_{C60}=c/\\lambda_{C60}",
        computableExpression: "f_C60_Hz = c/lambda_C60_m",
        operatorKind: "scalar_expression",
        inputSymbols: ["c", "lambda_C60_m"],
        outputSymbols: ["f_C60_Hz"],
      },
      {
        id: "c60_feature_energy",
        role: "calculator_demo",
        displayLatex: "E_{C60}=h f_{C60}",
        computableExpression: "E_C60_J = h*f_C60_Hz",
        operatorKind: "scalar_expression",
        inputSymbols: ["h", "f_C60_Hz"],
        outputSymbols: ["E_C60_J"],
      },
    ],
    units: [
      { symbol: "lambda_C60_m", unit: "m", quantity: "wavelength", dimensionSignature: "L" },
      { symbol: "f_C60_Hz", unit: "Hz", quantity: "frequency", dimensionSignature: "T^-1" },
      { symbol: "E_C60_J", unit: "J", quantity: "energy", dimensionSignature: "M L^2 T^-2" },
    ],
    assumptions: [
      "C60 spectral features are astrochemical context.",
      "This badge does not assert that fullerenes caused life, consciousness, or objective collapse.",
    ],
    calculatorPayloads: [
      payload({
        id: "c60_feature_frequency_payload",
        expression: "f_C60_Hz = c/lambda_C60_m",
        displayLatex: "f_{C60}=c/\\lambda_{C60}",
        targetVariable: "f_C60_Hz",
      }),
      payload({
        id: "c60_feature_energy_payload",
        expression: "E_C60_J = h*f_C60_Hz",
        displayLatex: "E_{C60}=h f_{C60}",
        targetVariable: "E_C60_J",
      }),
    ],
    sourceRefs: [
      literatureRef("arXiv:1102.2985", "C60 spectral detections in proto-planetary nebula context."),
      docRef("docs/architecture/astrochemistry-prebiotic-neuro-consciousness-bridge-plan.md", "stellar-carbon-entry-point"),
    ],
    hintKeys: {
      subjects: ["astrochemistry", "fullerene", "c60", "spectroscopy", "stellar_carbon"],
      symbols: ["lambda_C60_m", "f_C60_Hz", "E_C60_J", "c", "h"],
      unitSignatures: ["L", "T^-1", "M L^2 T^-2"],
      repoPaths: ["docs/architecture/astrochemistry-prebiotic-neuro-consciousness-bridge-plan.md"],
      equationFamilies: ["spectral_observable", "planck_relation", "astrochemistry_context"],
      simulationOwners: ["stellar_reference", "astrochemistry_prebiotic"],
    },
  }),
  prebioticBadge({
    id: "astrochemistry.pah.spectral_family_context",
    title: "PAH Spectral-Family Context",
    plainMeaning:
      "Represents polycyclic aromatic hydrocarbons and PAH-like aromatic nitriles as spectral-family astrochemistry context.",
    whyItMatters:
      "It keeps PAH-family evidence retrievable as carbon chemistry without treating PAHs as direct biochemical or consciousness precursors.",
    subjects: ["astrochemistry", "pah", "aromatic_carbon", "spectroscopy", "interstellar"],
    level: "model",
    status: "diagnostic",
    simulationOwners: ["astrochemistry_prebiotic", "stellar_reference"],
    equationFamilies: ["spectral_observable", "planck_relation", "pah_spectral_family_context"],
    tags: ["pah", "aromatic_nitrile", "spectral_family", "calculator_loadable"],
    equations: [
      {
        id: "pah_feature_energy",
        role: "calculator_demo",
        displayLatex: "E_{PAH}=h c/\\lambda_{PAH}",
        computableExpression: "E_PAH_J = h*c/lambda_PAH_m",
        operatorKind: "scalar_expression",
        inputSymbols: ["h", "c", "lambda_PAH_m"],
        outputSymbols: ["E_PAH_J"],
      },
    ],
    units: [
      { symbol: "lambda_PAH_m", unit: "m", quantity: "wavelength", dimensionSignature: "L" },
      { symbol: "E_PAH_J", unit: "J", quantity: "energy", dimensionSignature: "M L^2 T^-2" },
    ],
    assumptions: [
      "PAH-family spectral evidence is astrochemical context.",
      "Individual PAH-like detections do not establish a direct path to dopamine, pleasure, consciousness, or objective collapse.",
    ],
    calculatorPayloads: [
      payload({
        id: "pah_feature_energy_payload",
        expression: "E_PAH_J = h*c/lambda_PAH_m",
        displayLatex: "E_{PAH}=h c/\\lambda_{PAH}",
        targetVariable: "E_PAH_J",
      }),
    ],
    sourceRefs: [
      literatureRef("arXiv:2103.09984", "Cyanonaphthalene detections in TMC-1 by spectral matched filtering."),
      literatureRef("arXiv:2410.00670", "Additional PAH-like aromatic nitrile detections in TMC-1."),
      docRef("docs/knowledge/physics/interstellar-pah-chemistry.md"),
    ],
    hintKeys: {
      subjects: ["astrochemistry", "pah", "aromatic_carbon", "spectroscopy", "interstellar"],
      symbols: ["lambda_PAH_m", "E_PAH_J", "h", "c"],
      unitSignatures: ["L", "M L^2 T^-2"],
      repoPaths: ["docs/knowledge/physics/interstellar-pah-chemistry.md"],
      equationFamilies: ["spectral_observable", "planck_relation", "pah_spectral_family_context"],
      simulationOwners: ["astrochemistry_prebiotic", "stellar_reference"],
    },
  }),
  prebioticBadge({
    id: "astrochemistry.lab_spectroscopy.molecular_fingerprint_foundation",
    title: "Laboratory Spectroscopy Molecular-Fingerprint Foundation",
    plainMeaning:
      "Represents laboratory microwave, millimeter, and molecular spectroscopy as the fingerprint basis for astronomical molecule identification.",
    whyItMatters:
      "It makes Ziurys's detection premise explicit: astronomical prebiotic-chemistry claims require laboratory spectra before line assignments become evidence.",
    subjects: ["astrochemistry", "laboratory_spectroscopy", "molecular_fingerprint", "radio_astronomy", "line_assignment"],
    level: "diagnostic_gate",
    status: "diagnostic",
    simulationOwners: ["astrochemistry_prebiotic", "stellar_reference"],
    equationFamilies: ["molecular_spectroscopy", "spectral_observable", "line_assignment"],
    tags: ["ziurys_2024", "laboratory_spectroscopy", "calculator_loadable"],
    equations: [
      {
        id: "spectroscopic_transition_energy",
        role: "calculator_demo",
        displayLatex: "E_{transition}=h\\nu",
        computableExpression: "E_transition_J = h*nu_Hz",
        operatorKind: "scalar_expression",
        inputSymbols: ["h", "nu_Hz"],
        outputSymbols: ["E_transition_J"],
      },
      {
        id: "laboratory_line_assignment_gate",
        role: "gate",
        displayLatex: "\\mathrm{assignment}\\Rightarrow\\mathrm{lab\\ spectrum}\\land\\mathrm{astro\\ line}",
        computableExpression: null,
        operatorKind: "gate_status",
        inputSymbols: ["laboratory_rest_frequency", "observed_line_frequency", "line_confusion_context"],
        outputSymbols: ["molecular_fingerprint_gate_status"],
      },
    ],
    units: [
      { symbol: "nu_Hz", unit: "Hz", quantity: "frequency", dimensionSignature: "T^-1" },
      { symbol: "E_transition_J", unit: "J", quantity: "energy", dimensionSignature: "M L^2 T^-2" },
    ],
    assumptions: [
      "Laboratory spectroscopy supplies molecular fingerprints for astronomical line assignments.",
      "A line assignment is identification evidence under spectral-model assumptions, not a complete formation pathway.",
      "Spectroscopic identification does not validate delivery, abiogenesis, biology, or consciousness.",
    ],
    calculatorPayloads: [
      payload({
        id: "spectroscopic_transition_energy_payload",
        expression: "E_transition_J = h*nu_Hz",
        displayLatex: "E_{transition}=h\\nu",
        targetVariable: "E_transition_J",
      }),
    ],
    sourceRefs: [
      literatureRef(
        "doi:10.1146/annurev-physchem-090722-010849",
        "Ziurys 2024 frames laboratory spectroscopy as the molecular fingerprint basis for astronomical identifications.",
      ),
      docRef("docs/knowledge/physics/interstellar-pah-chemistry.md"),
    ],
    hintKeys: {
      subjects: ["astrochemistry", "laboratory_spectroscopy", "molecular_fingerprint", "radio_astronomy", "line_assignment"],
      symbols: ["h", "nu_Hz", "E_transition_J", "laboratory_rest_frequency", "observed_line_frequency"],
      unitSignatures: ["T^-1", "M L^2 T^-2"],
      repoPaths: ["docs/knowledge/physics/interstellar-pah-chemistry.md"],
      equationFamilies: ["molecular_spectroscopy", "spectral_observable", "line_assignment"],
      simulationOwners: ["astrochemistry_prebiotic", "stellar_reference"],
    },
  }),
  prebioticBadge({
    id: "astrochemistry.prebiotic.small_organic_dense_cloud_inventory",
    title: "Small Organic Dense-Cloud Prebiotic Inventory",
    plainMeaning:
      "Represents dense-cloud small organic molecules as observational prebiotic-foundation inventory context.",
    whyItMatters:
      "It adds Ziurys's prebiotic framing to the existing complex-organics layer while keeping inventory rows separate from origin-of-life proof.",
    subjects: ["astrochemistry", "prebiotic_foundation", "dense_cloud", "small_organics", "molecular_inventory"],
    level: "model",
    status: "diagnostic",
    simulationOwners: ["astrochemistry_prebiotic", "stellar_reference"],
    equationFamilies: ["prebiotic_inventory_context", "fractional_abundance", "molecular_spectroscopy"],
    tags: ["ziurys_2024", "small_organics", "dense_cloud", "calculator_loadable"],
    equations: [
      {
        id: "small_organic_fractional_abundance",
        role: "calculator_demo",
        displayLatex: "X_{org}=N_{org}/N_{H2}",
        computableExpression: "X_org = N_org_cm2/N_H2_cm2",
        operatorKind: "scalar_expression",
        inputSymbols: ["N_org_cm2", "N_H2_cm2"],
        outputSymbols: ["X_org"],
      },
    ],
    units: [
      { symbol: "N_org_cm2", unit: "1/cm^2", quantity: "organic_column_density", dimensionSignature: "L^-2" },
      { symbol: "N_H2_cm2", unit: "1/cm^2", quantity: "hydrogen_column_density", dimensionSignature: "L^-2" },
      { symbol: "X_org", unit: null, quantity: "fractional_abundance", dimensionSignature: "1" },
    ],
    assumptions: [
      "Dense-cloud organic inventories are prebiotic foundation context.",
      "Inventory abundance requires line assignment, excitation, source, and column-density assumptions.",
      "A prebiotic inventory row does not prove protoplanetary survival, local concentration, reaction network closure, or life.",
    ],
    calculatorPayloads: [
      payload({
        id: "small_organic_fractional_abundance_payload",
        expression: "X_org = N_org_cm2/N_H2_cm2",
        displayLatex: "X_{org}=N_{org}/N_{H2}",
        targetVariable: "X_org",
      }),
    ],
    sourceRefs: [
      literatureRef(
        "doi:10.1146/annurev-physchem-090722-010849",
        "Ziurys 2024 reviews small organic molecules in dense clouds as prebiotic astrochemistry context.",
      ),
      docRef("docs/knowledge/physics/prebiotic-organic-inventory.md"),
    ],
    hintKeys: {
      subjects: ["astrochemistry", "prebiotic_foundation", "dense_cloud", "small_organics", "molecular_inventory"],
      symbols: ["N_org_cm2", "N_H2_cm2", "X_org"],
      unitSignatures: ["L^-2", "1"],
      repoPaths: ["docs/knowledge/physics/prebiotic-organic-inventory.md"],
      equationFamilies: ["prebiotic_inventory_context", "fractional_abundance", "molecular_spectroscopy"],
      simulationOwners: ["astrochemistry_prebiotic", "stellar_reference"],
    },
  }),
  prebioticBadge({
    id: "astrochemistry.fullerene.c60_c70_carbon_cage_context",
    title: "C60/C70 Carbon-Cage Prebiotic Context",
    plainMeaning:
      "Represents fullerene C60 and C70 as carbon-cage astrochemistry context that can preserve C-C bonding motifs across circumstellar/interstellar settings.",
    whyItMatters:
      "It extends the existing C60 row into Ziurys's fullerene-family framing without turning fullerene detections into life or origin claims.",
    subjects: ["astrochemistry", "fullerene", "c60", "c70", "carbon_cage", "prebiotic_foundation"],
    level: "model",
    status: "diagnostic",
    simulationOwners: ["astrochemistry_prebiotic", "stellar_reference"],
    equationFamilies: ["fullerene_context", "carbon_cage_context", "spectral_observable"],
    tags: ["ziurys_2024", "fullerene", "c60", "c70", "calculator_loadable"],
    equations: [
      {
        id: "fullerene_feature_energy",
        role: "calculator_demo",
        displayLatex: "E_{fullerene}=h c/\\lambda_{fullerene}",
        computableExpression: "E_fullerene_J = h*c/lambda_fullerene_m",
        operatorKind: "scalar_expression",
        inputSymbols: ["h", "c", "lambda_fullerene_m"],
        outputSymbols: ["E_fullerene_J"],
      },
    ],
    units: [
      { symbol: "lambda_fullerene_m", unit: "m", quantity: "wavelength", dimensionSignature: "L" },
      { symbol: "E_fullerene_J", unit: "J", quantity: "energy", dimensionSignature: "M L^2 T^-2" },
    ],
    assumptions: [
      "Fullerene C60/C70 context is carbon-cage astrochemistry evidence.",
      "C-C bond preservation context does not prove a specific prebiotic synthesis pathway.",
      "Fullerene detections do not validate biology, life, consciousness, or objective collapse.",
    ],
    calculatorPayloads: [
      payload({
        id: "fullerene_feature_energy_payload",
        expression: "E_fullerene_J = h*c/lambda_fullerene_m",
        displayLatex: "E_{fullerene}=h c/\\lambda_{fullerene}",
        targetVariable: "E_fullerene_J",
      }),
    ],
    sourceRefs: [
      literatureRef(
        "doi:10.1146/annurev-physchem-090722-010849",
        "Ziurys 2024 discusses C60 and C70 fullerene carbon carriers in prebiotic astrochemistry.",
      ),
      literatureRef("doi:10.1126/science.1192035", "Detection of C60 and C70 in a young planetary nebula."),
      docRef("docs/architecture/astrochemistry-prebiotic-neuro-consciousness-bridge-plan.md", "stellar-carbon-entry-point"),
    ],
    hintKeys: {
      subjects: ["astrochemistry", "fullerene", "c60", "c70", "carbon_cage", "prebiotic_foundation"],
      symbols: ["lambda_fullerene_m", "E_fullerene_J", "h", "c"],
      unitSignatures: ["L", "M L^2 T^-2"],
      repoPaths: ["docs/architecture/astrochemistry-prebiotic-neuro-consciousness-bridge-plan.md"],
      equationFamilies: ["fullerene_context", "carbon_cage_context", "spectral_observable"],
      simulationOwners: ["astrochemistry_prebiotic", "stellar_reference"],
    },
  }),
  prebioticBadge({
    id: "astrochemistry.phosphorus.po_pn_molecular_cloud_context",
    title: "PO/PN Molecular-Cloud Phosphorus Context",
    plainMeaning:
      "Represents PO and PN detections in molecular clouds as phosphorus-bearing astrochemical context for prebiotic-foundation discussions.",
    whyItMatters:
      "It adds the missing phosphorus lane from Ziurys: phosphorus chemistry can be observed in star-forming material but does not by itself establish bioavailable phosphate or RNA chemistry.",
    subjects: ["astrochemistry", "phosphorus", "po", "pn", "molecular_cloud", "prebiotic_foundation"],
    level: "model",
    status: "diagnostic",
    simulationOwners: ["astrochemistry_prebiotic", "stellar_reference"],
    equationFamilies: ["phosphorus_chemistry_context", "fractional_abundance", "molecular_inventory_context"],
    tags: ["ziurys_2024", "phosphorus", "po", "pn", "calculator_loadable"],
    equations: [
      {
        id: "po_pn_column_density_ratio",
        role: "calculator_demo",
        displayLatex: "R_{PO/PN}=N_{PO}/N_{PN}",
        computableExpression: "R_PO_PN = N_PO_cm2/N_PN_cm2",
        operatorKind: "scalar_expression",
        inputSymbols: ["N_PO_cm2", "N_PN_cm2"],
        outputSymbols: ["R_PO_PN"],
      },
      {
        id: "p_bearing_fractional_abundance",
        role: "calculator_demo",
        displayLatex: "X_{P-bearing}=(N_{PO}+N_{PN})/N_{H2}",
        computableExpression: "X_P_bearing = (N_PO_cm2 + N_PN_cm2)/N_H2_cm2",
        operatorKind: "scalar_expression",
        inputSymbols: ["N_PO_cm2", "N_PN_cm2", "N_H2_cm2"],
        outputSymbols: ["X_P_bearing"],
      },
    ],
    units: [
      { symbol: "N_PO_cm2", unit: "1/cm^2", quantity: "po_column_density", dimensionSignature: "L^-2" },
      { symbol: "N_PN_cm2", unit: "1/cm^2", quantity: "pn_column_density", dimensionSignature: "L^-2" },
      { symbol: "N_H2_cm2", unit: "1/cm^2", quantity: "hydrogen_column_density", dimensionSignature: "L^-2" },
      { symbol: "R_PO_PN", unit: null, quantity: "column_density_ratio", dimensionSignature: "1" },
      { symbol: "X_P_bearing", unit: null, quantity: "fractional_abundance", dimensionSignature: "1" },
    ],
    assumptions: [
      "PO and PN detections are phosphorus chemistry context in molecular clouds.",
      "Column-density ratios are line-assignment and model-conditioned evidence.",
      "PO/PN context does not prove bioavailable phosphate, RNA chemistry, metabolism, or life.",
    ],
    calculatorPayloads: [
      payload({
        id: "po_pn_column_density_ratio_payload",
        expression: "R_PO_PN = N_PO_cm2/N_PN_cm2",
        displayLatex: "R_{PO/PN}=N_{PO}/N_{PN}",
        targetVariable: "R_PO_PN",
      }),
      payload({
        id: "p_bearing_fractional_abundance_payload",
        expression: "X_P_bearing = (N_PO_cm2 + N_PN_cm2)/N_H2_cm2",
        displayLatex: "X_{P-bearing}=(N_{PO}+N_{PN})/N_{H2}",
        targetVariable: "X_P_bearing",
      }),
    ],
    sourceRefs: [
      literatureRef(
        "doi:10.1146/annurev-physchem-090722-010849",
        "Ziurys 2024 highlights PO and PN in molecular clouds as elusive phosphorus-bearing prebiotic context.",
      ),
      docRef("docs/knowledge/physics/prebiotic-organic-inventory.md"),
    ],
    hintKeys: {
      subjects: ["astrochemistry", "phosphorus", "po", "pn", "molecular_cloud", "prebiotic_foundation"],
      symbols: ["N_PO_cm2", "N_PN_cm2", "N_H2_cm2", "R_PO_PN", "X_P_bearing"],
      unitSignatures: ["L^-2", "1"],
      repoPaths: ["docs/knowledge/physics/prebiotic-organic-inventory.md"],
      equationFamilies: ["phosphorus_chemistry_context", "fractional_abundance", "molecular_inventory_context"],
      simulationOwners: ["astrochemistry_prebiotic", "stellar_reference"],
    },
  }),
  prebioticBadge({
    id: "astrochemistry.complex_organics.dense_source_inventory_context",
    title: "Complex Organic Dense-Source Inventory Context",
    plainMeaning:
      "Represents complex organic interstellar molecules as source-dependent dense-cloud and star-forming-region inventory evidence.",
    whyItMatters:
      "It adds the Herbst/van Dishoeck review layer that complex organics are observed astrochemical inventory probes, not direct prebiotic success or life evidence.",
    subjects: ["astrochemistry", "complex_organics", "dense_cloud", "star_formation", "molecular_inventory"],
    level: "model",
    status: "diagnostic",
    simulationOwners: ["astrochemistry_prebiotic", "stellar_reference"],
    equationFamilies: ["molecular_inventory_context", "fractional_abundance", "spectral_observable"],
    tags: ["complex_organic_molecules", "dense_source_context", "calculator_loadable"],
    equations: [
      {
        id: "complex_organic_fractional_abundance",
        role: "definition",
        displayLatex: "X_{mol}=N_{mol}/N_{H2}",
        computableExpression: "X_mol = N_mol_cm2/N_H2_cm2",
        operatorKind: "scalar_expression",
        inputSymbols: ["N_mol_cm2", "N_H2_cm2"],
        outputSymbols: ["X_mol"],
      },
    ],
    units: [
      { symbol: "N_mol_cm2", unit: "1/cm^2", quantity: "molecular_column_density", dimensionSignature: "L^-2" },
      { symbol: "N_H2_cm2", unit: "1/cm^2", quantity: "hydrogen_column_density", dimensionSignature: "L^-2" },
      { symbol: "X_mol", unit: null, quantity: "fractional_abundance", dimensionSignature: "1" },
    ],
    assumptions: [
      "Complex organic molecule inventory is an observational astrochemistry context.",
      "Fractional abundances depend on source class, excitation assumptions, and chemical history.",
      "Dense-source organic inventories do not certify protoplanetary delivery, abiogenesis, biology, or consciousness.",
    ],
    calculatorPayloads: [
      payload({
        id: "complex_organic_fractional_abundance_payload",
        expression: "X_mol = N_mol_cm2/N_H2_cm2",
        displayLatex: "X_{mol}=N_{mol}/N_{H2}",
        targetVariable: "X_mol",
      }),
    ],
    sourceRefs: [
      literatureRef(
        "doi:10.1146/annurev-astro-082708-101654",
        "Herbst and van Dishoeck review of complex organic interstellar molecules in dense and star-forming environments.",
      ),
      docRef("docs/knowledge/physics/prebiotic-organic-inventory.md"),
    ],
    hintKeys: {
      subjects: ["astrochemistry", "complex_organics", "dense_cloud", "star_formation", "molecular_inventory"],
      symbols: ["N_mol_cm2", "N_H2_cm2", "X_mol"],
      unitSignatures: ["L^-2", "1"],
      repoPaths: ["docs/knowledge/physics/prebiotic-organic-inventory.md"],
      equationFamilies: ["molecular_inventory_context", "fractional_abundance", "spectral_observable"],
      simulationOwners: ["astrochemistry_prebiotic", "stellar_reference"],
    },
  }),
  prebioticBadge({
    id: "astrochemistry.gas_grain.ice_mantle_formation_context",
    title: "Gas-Grain Ice-Mantle Formation Context",
    plainMeaning:
      "Represents ice mantles on interstellar grains as a formation and reservoir context for saturated complex organic molecules.",
    whyItMatters:
      "It captures the paper's strongest formation constraint: gas detections alone are incomplete without grain-surface chemistry, ice composition, and desorption context.",
    subjects: ["astrochemistry", "gas_grain_chemistry", "ice_mantle", "grain_surface", "methanol", "desorption"],
    level: "model",
    status: "diagnostic",
    simulationOwners: ["astrochemistry_prebiotic"],
    equationFamilies: ["gas_grain_context", "ice_mantle_inventory", "fractional_abundance"],
    tags: ["ice_mantle", "grain_surface", "calculator_loadable"],
    equations: [
      {
        id: "ice_mantle_methanol_water_ratio",
        role: "calculator_demo",
        displayLatex: "R_{CH3OH/H2O}=X_{CH3OH,ice}/X_{H2O,ice}",
        computableExpression: "R_CH3OH_H2O = X_CH3OH_ice/X_H2O_ice",
        operatorKind: "scalar_expression",
        inputSymbols: ["X_CH3OH_ice", "X_H2O_ice"],
        outputSymbols: ["R_CH3OH_H2O"],
      },
    ],
    units: [
      { symbol: "X_CH3OH_ice", unit: null, quantity: "ice_fractional_abundance", dimensionSignature: "1" },
      { symbol: "X_H2O_ice", unit: null, quantity: "ice_fractional_abundance", dimensionSignature: "1" },
      { symbol: "R_CH3OH_H2O", unit: null, quantity: "ice_abundance_ratio", dimensionSignature: "1" },
    ],
    assumptions: [
      "Ice-mantle chemistry is formation and reservoir context, not a complete origin pathway.",
      "Surface formation, heating, nonthermal desorption, and source evolution must be represented before gas-phase inventory is overinterpreted.",
      "Grain chemistry context does not promote an organic molecule inventory into life or consciousness evidence.",
    ],
    calculatorPayloads: [
      payload({
        id: "ice_mantle_methanol_water_ratio_payload",
        expression: "R_CH3OH_H2O = X_CH3OH_ice/X_H2O_ice",
        displayLatex: "R_{CH3OH/H2O}=X_{CH3OH,ice}/X_{H2O,ice}",
        targetVariable: "R_CH3OH_H2O",
      }),
    ],
    sourceRefs: [
      literatureRef(
        "doi:10.1146/annurev-astro-082708-101654",
        "Herbst and van Dishoeck review evidence for complex molecule formation in ice mantles on interstellar grains.",
      ),
      docRef("docs/knowledge/physics/physics-prebiotic-chemistry-tree.json", "physics-prebiotic-chemistry-molecular-selection"),
    ],
    hintKeys: {
      subjects: ["astrochemistry", "gas_grain_chemistry", "ice_mantle", "grain_surface", "methanol", "desorption"],
      symbols: ["X_CH3OH_ice", "X_H2O_ice", "R_CH3OH_H2O"],
      unitSignatures: ["1"],
      repoPaths: ["docs/knowledge/physics/physics-prebiotic-chemistry-tree.json"],
      equationFamilies: ["gas_grain_context", "ice_mantle_inventory", "fractional_abundance"],
      simulationOwners: ["astrochemistry_prebiotic"],
    },
  }),
  prebioticBadge({
    id: "astrochemistry.source_class.chemical_differentiation_context",
    title: "Astrochemical Source-Class Differentiation Context",
    plainMeaning:
      "Represents the constraint that cold cores, hot cores, hot corinos, outflows, and evolved-star envelopes can show different complex-organic inventories.",
    whyItMatters:
      "It prevents the graph from treating complex organic chemistry as one universal molecule list independent of physical environment and evolutionary history.",
    subjects: ["astrochemistry", "source_class", "hot_core", "hot_corino", "cold_core", "chemical_differentiation"],
    level: "diagnostic_gate",
    status: "diagnostic",
    simulationOwners: ["astrochemistry_prebiotic", "stellar_reference"],
    equationFamilies: ["source_class_context", "chemical_history_context", "claim_boundary"],
    tags: ["source_class", "chemical_differentiation", "noncomputable_reference"],
    equations: [
      {
        id: "source_class_conditioned_inventory_reference",
        role: "noncomputable_reference",
        displayLatex: "\\mathrm{inventory}=\\mathrm{context}(\\mathrm{source\\ class},T,n,t)",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["source_class", "temperature_K", "density_cm3", "chemical_age_s"],
        outputSymbols: ["source_conditioned_inventory_context"],
      },
    ],
    units: [
      { symbol: "temperature_K", unit: "K", quantity: "temperature", dimensionSignature: "Theta" },
      { symbol: "density_cm3", unit: "1/cm^3", quantity: "number_density", dimensionSignature: "L^-3" },
      { symbol: "chemical_age_s", unit: "s", quantity: "time", dimensionSignature: "T" },
    ],
    assumptions: [
      "Cold-core unsaturated chemistry and hot-core/corino saturated chemistry must be kept distinguishable.",
      "A detected molecule family is a probe of physical conditions and history, not a universal formation claim.",
      "Source-class context is required before comparing interstellar organics to prebiotic inventories.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      literatureRef(
        "doi:10.1146/annurev-astro-082708-101654",
        "Herbst and van Dishoeck describe source-dependent complex molecule inventories across cold cores and hot cores/corinos.",
      ),
      docRef("docs/knowledge/physics/physics-stellar-structure-nucleosynthesis-tree.json", "stellar-chemical-inheritance"),
    ],
    hintKeys: {
      subjects: ["astrochemistry", "source_class", "hot_core", "hot_corino", "cold_core", "chemical_differentiation"],
      symbols: ["source_class", "temperature_K", "density_cm3", "chemical_age_s", "source_conditioned_inventory_context"],
      unitSignatures: ["Theta", "L^-3", "T"],
      repoPaths: ["docs/knowledge/physics/physics-stellar-structure-nucleosynthesis-tree.json"],
      equationFamilies: ["source_class_context", "chemical_history_context", "claim_boundary"],
      simulationOwners: ["astrochemistry_prebiotic", "stellar_reference"],
    },
  }),
  prebioticBadge({
    id: "astrochemistry.claim_boundary.spectral_model_inference_only",
    title: "Spectral/Model Inference Boundary",
    plainMeaning:
      "Blocks spectral feature, abundance, and chemistry-model rows from being treated as direct proof of formation pathway, delivery, life, or consciousness.",
    whyItMatters:
      "It represents the review's inference boundary: spectra, column densities, chemical rates, and radiative transfer are powerful probes but remain model-conditioned evidence.",
    subjects: ["astrochemistry", "claim_boundary", "spectroscopy", "radiative_transfer", "chemical_model", "column_density"],
    level: "claim_boundary",
    status: "blocked",
    simulationOwners: ["astrochemistry_prebiotic", "stellar_reference"],
    equationFamilies: ["spectral_inference_boundary", "radiative_transfer_context", "claim_boundary"],
    tags: ["claim_boundary", "spectral_model_conditioned", "blocks_promotion"],
    equations: [
      {
        id: "spectral_model_residual_gate_reference",
        role: "gate",
        displayLatex: "\\Delta I_{line}=I_{obs}-I_{model}",
        computableExpression: null,
        operatorKind: "gate_status",
        inputSymbols: ["I_obs", "I_model", "line_assignment", "radiative_transfer_model"],
        outputSymbols: ["spectral_model_inference_gate_status"],
      },
    ],
    units: [],
    assumptions: [
      "Spectral assignments require line identification, excitation, column density, beam, and radiative-transfer assumptions.",
      "Chemical models are incomplete and can be time-dependent.",
      "Spectral or abundance agreement is model-conditioned evidence and does not prove a complete formation route, delivery route, life, or consciousness.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      literatureRef(
        "doi:10.1146/annurev-astro-082708-101654",
        "Herbst and van Dishoeck review model, spectra, abundance, and radiative-transfer caveats for complex organic molecules.",
      ),
      docRef("docs/knowledge/physics/interstellar-pah-chemistry.md"),
    ],
    hintKeys: {
      subjects: ["astrochemistry", "claim_boundary", "spectroscopy", "radiative_transfer", "chemical_model", "column_density"],
      symbols: ["I_obs", "I_model", "line_assignment", "radiative_transfer_model", "spectral_model_inference_gate_status"],
      unitSignatures: [],
      repoPaths: ["docs/knowledge/physics/interstellar-pah-chemistry.md"],
      equationFamilies: ["spectral_inference_boundary", "radiative_transfer_context", "claim_boundary"],
      simulationOwners: ["astrochemistry_prebiotic", "stellar_reference"],
    },
  }),
  prebioticBadge({
    id: "prebiotic.inventory.meteoritic_organics_context",
    title: "Meteoritic Organic Inventory Context",
    plainMeaning:
      "Represents returned-sample and meteoritic organic inventories as prebiotic ingredient context.",
    whyItMatters:
      "It lets Helix discuss amino acids, nucleobases, PAHs, salts, sugars, and related inventory rows without claiming life began in space.",
    subjects: ["prebiotic", "meteoritic_organics", "asteroid_sample", "amino_acid", "nucleobase", "pah", "salt"],
    level: "model",
    status: "diagnostic",
    simulationOwners: ["astrochemistry_prebiotic"],
    equationFamilies: ["prebiotic_inventory_context", "sample_provenance_context"],
    tags: ["bennu", "meteorite", "organic_inventory", "noncomputable_reference"],
    equations: [
      {
        id: "prebiotic_inventory_context_reference",
        role: "noncomputable_reference",
        displayLatex: "\\mathrm{inventory}=\\mathrm{context}(\\mathrm{organics},\\mathrm{salts},\\mathrm{curation})",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["organic_inventory", "sample_curation"],
        outputSymbols: ["prebiotic_inventory_context"],
      },
    ],
    units: [],
    assumptions: [
      "Returned-sample organic inventories are prebiotic ingredient context.",
      "Inventory rows do not assert DNA, RNA, cells, metabolism, life, consciousness, or objective collapse.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      literatureRef("NASA-Bennu-2025-organics", "Bennu amino-acid, nucleobase, and salt inventory context."),
      literatureRef("NatureAstronomy-Bennu-organics-2025", "Organic compounds in returned Bennu samples."),
      docRef("docs/knowledge/bridges/astrochemistry-prebiotic-neuro-consciousness-bridge-tree.json", "prebiotic-organic-inventory"),
    ],
    hintKeys: {
      subjects: ["prebiotic", "meteoritic_organics", "asteroid_sample", "amino_acid", "nucleobase", "pah", "salt"],
      symbols: ["organic_inventory", "sample_curation", "prebiotic_inventory_context"],
      unitSignatures: [],
      repoPaths: ["docs/knowledge/bridges/astrochemistry-prebiotic-neuro-consciousness-bridge-tree.json"],
      equationFamilies: ["prebiotic_inventory_context", "sample_provenance_context"],
      simulationOwners: ["astrochemistry_prebiotic"],
    },
  }),
  prebioticBadge({
    id: "astrochemistry.planetary_delivery.meteorite_comet_link_context",
    title: "Meteorite/Comet Planetary-Delivery Link Context",
    plainMeaning:
      "Represents meteorites and comets as possible links between molecule-rich interstellar starting material and planetary prebiotic inventories.",
    whyItMatters:
      "It preserves Ziurys's planetary-body bridge while blocking the shortcut from interstellar inventory to confirmed abiogenesis.",
    subjects: ["astrochemistry", "planetary_delivery", "meteorite", "comet", "prebiotic_inventory"],
    level: "model",
    status: "diagnostic",
    simulationOwners: ["astrochemistry_prebiotic"],
    equationFamilies: ["planetary_delivery_context", "prebiotic_inventory_context", "claim_boundary"],
    tags: ["ziurys_2024", "meteorite", "comet", "noncomputable_reference"],
    equations: [
      {
        id: "planetary_delivery_context_reference",
        role: "noncomputable_reference",
        displayLatex: "\\mathrm{delivery\\ context}=\\mathrm{context}(\\mathrm{meteorites},\\mathrm{comets},\\mathrm{processing})",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["meteorite_inventory", "comet_inventory", "disk_processing_context"],
        outputSymbols: ["planetary_delivery_context"],
      },
    ],
    units: [],
    assumptions: [
      "Meteorites and comets can provide link context between astrochemical inventories and planetary materials.",
      "Delivery context does not prove survival, concentration, aqueous availability, reaction closure, or abiogenesis.",
      "Planetary-body links require curation, alteration, and local environmental evidence before stronger prebiotic claims.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      literatureRef(
        "doi:10.1146/annurev-physchem-090722-010849",
        "Ziurys 2024 links molecule-rich interstellar starting material to planetary bodies such as meteorites and comets.",
      ),
      docRef("docs/knowledge/physics/meteoritic-prebiotic-organic-delivery.md"),
      docRef("docs/knowledge/physics/prebiotic-organic-inventory.md"),
    ],
    hintKeys: {
      subjects: ["astrochemistry", "planetary_delivery", "meteorite", "comet", "prebiotic_inventory"],
      symbols: ["meteorite_inventory", "comet_inventory", "disk_processing_context", "planetary_delivery_context"],
      unitSignatures: [],
      repoPaths: [
        "docs/knowledge/physics/meteoritic-prebiotic-organic-delivery.md",
        "docs/knowledge/physics/prebiotic-organic-inventory.md",
      ],
      equationFamilies: ["planetary_delivery_context", "prebiotic_inventory_context", "claim_boundary"],
      simulationOwners: ["astrochemistry_prebiotic"],
    },
  }),
  prebioticBadge({
    id: "astrochemistry.claim_boundary.protoplanetary_processing_uncertain",
    title: "Protoplanetary Processing Uncertainty Boundary",
    plainMeaning:
      "Blocks direct promotion from interstellar or planetary-delivery inventories into prebiotic pathway claims until disk, alteration, concentration, and local environment processing are represented.",
    whyItMatters:
      "It encodes Ziurys's uncertainty boundary: emerging planetary disks process inherited chemistry, so interstellar inventory is not automatically planetary prebiotic availability.",
    subjects: ["astrochemistry", "claim_boundary", "protoplanetary_disk", "processing_uncertainty", "prebiotic_inventory"],
    level: "claim_boundary",
    status: "blocked",
    simulationOwners: ["astrochemistry_prebiotic"],
    equationFamilies: ["protoplanetary_processing_boundary", "prebiotic_claim_boundary"],
    tags: ["ziurys_2024", "claim_boundary", "blocks_promotion"],
    equations: [
      {
        id: "protoplanetary_processing_boundary_reference",
        role: "gate",
        displayLatex: "\\mathrm{interstellar\\ inventory}\\nRightarrow\\mathrm{planetary\\ prebiotic\\ availability}",
        computableExpression: null,
        operatorKind: "gate_status",
        inputSymbols: ["interstellar_inventory", "disk_processing_context", "local_environment_context"],
        outputSymbols: ["protoplanetary_processing_boundary_status"],
      },
    ],
    units: [],
    assumptions: [
      "Chemical and physical processing in emerging planetary disks remains an uncertainty boundary.",
      "Interstellar inventories do not automatically survive, concentrate, or become locally available for prebiotic chemistry.",
      "This boundary blocks life, consciousness, and objective-collapse promotion from astrochemical foundation evidence.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      literatureRef(
        "doi:10.1146/annurev-physchem-090722-010849",
        "Ziurys 2024 notes uncertainty in chemical/physical processing of emerging planetary disks.",
      ),
      docRef("docs/architecture/astrochemistry-prebiotic-neuro-consciousness-bridge-plan.md", "prebiotic-chemistry-gates"),
    ],
    hintKeys: {
      subjects: ["astrochemistry", "claim_boundary", "protoplanetary_disk", "processing_uncertainty", "prebiotic_inventory"],
      symbols: [
        "interstellar_inventory",
        "disk_processing_context",
        "local_environment_context",
        "protoplanetary_processing_boundary_status",
      ],
      unitSignatures: [],
      repoPaths: ["docs/architecture/astrochemistry-prebiotic-neuro-consciousness-bridge-plan.md"],
      equationFamilies: ["protoplanetary_processing_boundary", "prebiotic_claim_boundary"],
      simulationOwners: ["astrochemistry_prebiotic"],
    },
  }),
  prebioticBadge({
    id: "prebiotic.photochemistry.radiation_processing_context",
    title: "Prebiotic Photochemical Processing Context",
    plainMeaning:
      "Represents UV or radiation processing as environmental chemistry context for prebiotic organic inventories.",
    whyItMatters:
      "It adds the missing energy-processing lane between astrochemical inventory and plausible chemical transformation without claiming a unique origin route.",
    subjects: ["prebiotic", "photochemistry", "radiation_processing", "uv", "organic_inventory"],
    level: "model",
    status: "diagnostic",
    simulationOwners: ["astrochemistry_prebiotic"],
    equationFamilies: ["photochemical_dose_context", "prebiotic_processing_context"],
    tags: ["photochemistry", "radiation_processing", "calculator_loadable"],
    equations: [
      {
        id: "photon_fluence_context",
        role: "calculator_demo",
        displayLatex: "\\mathcal{F}_{\\gamma}=F_{\\gamma}\\,t",
        computableExpression: "photon_fluence_m2 = photon_flux_m2_s*t_exposure_s",
        operatorKind: "scalar_expression",
        inputSymbols: ["photon_flux_m2_s", "t_exposure_s"],
        outputSymbols: ["photon_fluence_m2"],
      },
    ],
    units: [
      { symbol: "photon_flux_m2_s", unit: "1/(m^2*s)", quantity: "photon_flux", dimensionSignature: "L^-2 T^-1" },
      { symbol: "t_exposure_s", unit: "s", quantity: "time", dimensionSignature: "T" },
      { symbol: "photon_fluence_m2", unit: "1/m^2", quantity: "photon_fluence", dimensionSignature: "L^-2" },
    ],
    assumptions: [
      "Photochemical processing is environmental chemistry context.",
      "A photon fluence row does not establish a specific origin-of-life pathway.",
    ],
    calculatorPayloads: [
      payload({
        id: "photon_fluence_context_payload",
        expression: "photon_fluence_m2 = photon_flux_m2_s*t_exposure_s",
        displayLatex: "\\mathcal{F}_{\\gamma}=F_{\\gamma}\\,t",
        targetVariable: "photon_fluence_m2",
      }),
    ],
    sourceRefs: [
      literatureRef("NASA-Astrobiology-Strategy-2015", "Prebiotic chemistry and environmental processing context."),
      docRef("docs/architecture/astrochemistry-prebiotic-neuro-consciousness-bridge-plan.md", "prebiotic-chemistry-gates"),
    ],
    hintKeys: {
      subjects: ["prebiotic", "photochemistry", "radiation_processing", "uv", "organic_inventory"],
      symbols: ["photon_flux_m2_s", "t_exposure_s", "photon_fluence_m2"],
      unitSignatures: ["L^-2 T^-1", "T", "L^-2"],
      repoPaths: ["docs/architecture/astrochemistry-prebiotic-neuro-consciousness-bridge-plan.md"],
      equationFamilies: ["photochemical_dose_context", "prebiotic_processing_context"],
      simulationOwners: ["astrochemistry_prebiotic"],
    },
  }),
  prebioticBadge({
    id: "prebiotic.surface_catalysis.mineral_aqueous_context",
    title: "Mineral/Aqueous Surface Catalysis Context",
    plainMeaning:
      "Represents mineral surfaces, salts, and aqueous alteration as contextual constraints on prebiotic reaction networks.",
    whyItMatters:
      "It closes the gap between inventory lists and chemistry pathways by requiring local surface and solvent context before origin claims.",
    subjects: ["prebiotic", "surface_catalysis", "mineral", "aqueous_alteration", "salt", "reaction_network"],
    level: "model",
    status: "diagnostic",
    simulationOwners: ["astrochemistry_prebiotic"],
    equationFamilies: ["surface_catalysis_context", "aqueous_alteration_context"],
    tags: ["mineral_surface", "aqueous_context", "noncomputable_reference"],
    equations: [
      {
        id: "mineral_aqueous_context_reference",
        role: "noncomputable_reference",
        displayLatex: "\\mathrm{reaction\\ context}=\\mathrm{context}(\\mathrm{surface},\\mathrm{solvent},\\mathrm{salts})",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["mineral_surface_context", "aqueous_alteration_context", "salt_context"],
        outputSymbols: ["surface_catalysis_context"],
      },
    ],
    units: [],
    assumptions: [
      "Mineral and aqueous context can constrain plausible prebiotic chemistry.",
      "Surface catalysis context does not certify RNA-world, aromatic-ring origin, or consciousness claims.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      literatureRef("NASA-Bennu-2025-organics", "Bennu salts and organic inventory context."),
      literatureRef("Nature-Bennu-salts-2025", "Evaporite and salt minerals in returned Bennu samples."),
      docRef("docs/knowledge/bridges/astrochemistry-prebiotic-neuro-consciousness-bridge-tree.json", "prebiotic-organic-inventory"),
    ],
    hintKeys: {
      subjects: ["prebiotic", "surface_catalysis", "mineral", "aqueous_alteration", "salt", "reaction_network"],
      symbols: [
        "mineral_surface_context",
        "aqueous_alteration_context",
        "salt_context",
        "surface_catalysis_context",
      ],
      unitSignatures: [],
      repoPaths: ["docs/knowledge/bridges/astrochemistry-prebiotic-neuro-consciousness-bridge-tree.json"],
      equationFamilies: ["surface_catalysis_context", "aqueous_alteration_context"],
      simulationOwners: ["astrochemistry_prebiotic"],
    },
  }),
  prebioticBadge({
    id: "prebiotic.aromatic_ring.coupled_oscillator_context",
    title: "Coupled Aromatic-Ring Oscillator Context",
    plainMeaning:
      "Represents two or more aromatic rings as a speculative coupled-oscillator context for prebiotic molecular-coherence discussions.",
    whyItMatters:
      "It captures the Hameroff-adjacent claim in mathematically inspectable form while blocking collapse, pleasure, and consciousness promotion.",
    subjects: ["prebiotic", "aromatic_ring", "coupled_oscillator", "coherence"],
    level: "diagnostic_gate",
    status: "review",
    simulationOwners: ["astrochemistry_prebiotic"],
    equationFamilies: ["coupled_oscillator", "coherence_window", "claim_boundary"],
    tags: ["exploratory_bridge", "calculator_loadable", "hameroff_quote_context"],
    equations: [
      {
        id: "ring_frequency_detuning",
        role: "calculator_demo",
        displayLatex: "\\Delta\\omega=|\\omega_1-\\omega_2|",
        computableExpression: "delta_omega_rad_s = abs(omega_1_rad_s - omega_2_rad_s)",
        operatorKind: "scalar_expression",
        inputSymbols: ["omega_1_rad_s", "omega_2_rad_s"],
        outputSymbols: ["delta_omega_rad_s"],
      },
      {
        id: "ring_coupling_gate",
        role: "gate",
        displayLatex: "K_{12}>\\Delta\\omega \\;\\land\\; N_{rings}\\ge 2",
        computableExpression: null,
        operatorKind: "gate_status",
        inputSymbols: ["K_12_rad_s", "delta_omega_rad_s", "N_rings"],
        outputSymbols: ["ring_coupling_gate_status"],
      },
    ],
    units: [
      { symbol: "omega_1_rad_s", unit: "rad/s", quantity: "angular_frequency", dimensionSignature: "T^-1" },
      { symbol: "omega_2_rad_s", unit: "rad/s", quantity: "angular_frequency", dimensionSignature: "T^-1" },
      { symbol: "delta_omega_rad_s", unit: "rad/s", quantity: "detuning", dimensionSignature: "T^-1" },
      { symbol: "K_12_rad_s", unit: "rad/s", quantity: "coupling_rate", dimensionSignature: "T^-1" },
      { symbol: "N_rings", unit: null, quantity: "ring_count", dimensionSignature: "1" },
    ],
    assumptions: [
      "At least two oscillatory units are required for coupling language.",
      "Coupled aromatic oscillators are molecular-coherence context only.",
      "This does not validate OR, consciousness, pleasure optimization, or wavefunction-collapse biology.",
    ],
    calculatorPayloads: [
      payload({
        id: "ring_frequency_detuning_payload",
        expression: "delta_omega_rad_s = abs(omega_1_rad_s - omega_2_rad_s)",
        displayLatex: "\\Delta\\omega=|\\omega_1-\\omega_2|",
        targetVariable: "delta_omega_rad_s",
      }),
    ],
    sourceRefs: [
      docRef("docs/architecture/astrochemistry-prebiotic-neuro-consciousness-bridge-plan.md", "claim-context"),
      docRef("docs/knowledge/bridges/astrochemistry-prebiotic-neuro-consciousness-bridge-tree.json", "prebiotic-organic-inventory"),
    ],
    hintKeys: {
      subjects: ["prebiotic", "aromatic_ring", "coupled_oscillator", "coherence"],
      symbols: ["omega_1_rad_s", "omega_2_rad_s", "delta_omega_rad_s", "K_12_rad_s", "N_rings"],
      unitSignatures: ["T^-1", "1"],
      repoPaths: [
        "docs/architecture/astrochemistry-prebiotic-neuro-consciousness-bridge-plan.md",
        "docs/knowledge/bridges/astrochemistry-prebiotic-neuro-consciousness-bridge-tree.json",
      ],
      equationFamilies: ["coupled_oscillator", "coherence_window", "claim_boundary"],
      simulationOwners: ["astrochemistry_prebiotic"],
    },
  }),
  prebioticBadge({
    id: "prebiotic.coherence.decoherence_lifetime_gate",
    title: "Prebiotic Decoherence Lifetime Gate",
    plainMeaning:
      "Requires any molecular-coherence claim to expose a candidate lifetime, decoherence time, and explicit surplus or deficit.",
    whyItMatters:
      "It prevents aromatic-ring oscillator language from skipping directly to OR or consciousness claims without a testable coherence window.",
    subjects: ["prebiotic", "coherence", "decoherence", "lifetime_gate", "molecular_oscillator"],
    level: "diagnostic_gate",
    status: "review",
    simulationOwners: ["astrochemistry_prebiotic"],
    equationFamilies: ["coherence_lifetime_gate", "decoherence_window", "claim_boundary"],
    tags: ["coherence_gate", "decoherence", "calculator_loadable"],
    equations: [
      {
        id: "coherence_lifetime_surplus",
        role: "calculator_demo",
        displayLatex: "\\Delta t_{coh}=\\tau_{coherence}-\\tau_{candidate}",
        computableExpression: "coherence_surplus_s = tau_coherence_s - tau_candidate_s",
        operatorKind: "scalar_expression",
        inputSymbols: ["tau_coherence_s", "tau_candidate_s"],
        outputSymbols: ["coherence_surplus_s"],
      },
      {
        id: "decoherence_lifetime_gate",
        role: "gate",
        displayLatex: "\\tau_{coherence}>\\tau_{candidate}",
        computableExpression: null,
        operatorKind: "gate_status",
        inputSymbols: ["tau_coherence_s", "tau_candidate_s"],
        outputSymbols: ["coherence_lifetime_gate_status"],
      },
    ],
    units: [
      { symbol: "tau_coherence_s", unit: "s", quantity: "coherence_time", dimensionSignature: "T" },
      { symbol: "tau_candidate_s", unit: "s", quantity: "candidate_timescale", dimensionSignature: "T" },
      { symbol: "coherence_surplus_s", unit: "s", quantity: "time_margin", dimensionSignature: "T" },
    ],
    assumptions: [
      "Molecular coherence claims require an explicit coherence lifetime and candidate timescale.",
      "Passing this gate would still not validate OR, consciousness, or wavefunction-collapse biology.",
    ],
    calculatorPayloads: [
      payload({
        id: "coherence_lifetime_surplus_payload",
        expression: "coherence_surplus_s = tau_coherence_s - tau_candidate_s",
        displayLatex: "\\Delta t_{coh}=\\tau_{coherence}-\\tau_{candidate}",
        targetVariable: "coherence_surplus_s",
      }),
    ],
    sourceRefs: [
      docRef("docs/architecture/astrochemistry-prebiotic-neuro-consciousness-bridge-plan.md", "orch-or-requires-direct-measurement-contract"),
      docRef("docs/knowledge/bridges/astrochemistry-prebiotic-neuro-consciousness-bridge-tree.json", "orch_or_requires_direct_measurement_contract"),
    ],
    hintKeys: {
      subjects: ["prebiotic", "coherence", "decoherence", "lifetime_gate", "molecular_oscillator"],
      symbols: ["tau_coherence_s", "tau_candidate_s", "coherence_surplus_s"],
      unitSignatures: ["T"],
      repoPaths: [
        "docs/architecture/astrochemistry-prebiotic-neuro-consciousness-bridge-plan.md",
        "docs/knowledge/bridges/astrochemistry-prebiotic-neuro-consciousness-bridge-tree.json",
      ],
      equationFamilies: ["coherence_lifetime_gate", "decoherence_window", "claim_boundary"],
      simulationOwners: ["astrochemistry_prebiotic"],
    },
  }),
  prebioticBadge({
    id: "prebiotic.rna_world.ribozyme_context",
    title: "RNA-World Ribozyme Context",
    plainMeaning:
      "Represents RNA catalytic function as origin-of-life context separate from aromatic-ring origin hypotheses.",
    whyItMatters:
      "It keeps RNA-world support retrievable without using RNA catalysis as validation of Hameroff-style aromatic-ring or Orch-OR claims.",
    subjects: ["prebiotic", "rna_world", "ribozyme", "origin_of_life"],
    level: "model",
    status: "diagnostic",
    simulationOwners: ["astrochemistry_prebiotic"],
    equationFamilies: ["rna_world_context", "origin_of_life_context"],
    tags: ["rna_world", "ribozyme", "noncomputable_reference"],
    equations: [
      {
        id: "rna_catalytic_context_reference",
        role: "noncomputable_reference",
        displayLatex: "\\mathrm{RNA\\ catalysis}\\neq\\mathrm{Orch\\text{-}OR\\ validation}",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["rna_catalysis_evidence"],
        outputSymbols: ["rna_world_context"],
      },
    ],
    units: [],
    assumptions: [
      "RNA-world context is represented as origin-of-life chemistry context.",
      "RNA catalysis does not validate aromatic-ring OR claims or Orch-OR.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      literatureRef("NobelPrize-1989-RNA-catalysis", "Catalytic properties of RNA reference."),
      docRef("docs/architecture/astrochemistry-prebiotic-neuro-consciousness-bridge-plan.md", "recommended-tree-split"),
    ],
    hintKeys: {
      subjects: ["prebiotic", "rna_world", "ribozyme", "origin_of_life"],
      symbols: ["rna_world_context", "rna_catalysis_evidence"],
      unitSignatures: [],
      repoPaths: ["docs/architecture/astrochemistry-prebiotic-neuro-consciousness-bridge-plan.md"],
      equationFamilies: ["rna_world_context", "origin_of_life_context"],
      simulationOwners: ["astrochemistry_prebiotic"],
    },
  }),
  prebioticBadge({
    id: "prebiotic.claim_boundary.dopamine_not_pah_shortcut",
    title: "Dopamine Not-PAH Shortcut Boundary",
    plainMeaning:
      "Blocks shortcuts that treat interstellar PAH chemistry as direct dopamine inheritance or a pleasure-optimization law.",
    whyItMatters:
      "It keeps aromatic carbon chemistry separate from terrestrial catecholamine biosynthesis and reward-system interpretation.",
    subjects: ["prebiotic", "claim_boundary", "dopamine", "pah", "reward_signaling", "shortcut_block"],
    level: "claim_boundary",
    status: "blocked",
    simulationOwners: ["astrochemistry_prebiotic"],
    equationFamilies: ["dopamine_shortcut_boundary", "prebiotic_claim_boundary"],
    tags: ["claim_boundary", "dopamine_not_pah", "blocks_promotion"],
    equations: [
      {
        id: "dopamine_not_pah_boundary_reference",
        role: "noncomputable_reference",
        displayLatex: "\\mathrm{PAH\\ chemistry}\\nRightarrow\\mathrm{dopamine\\ reward\\ law}",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: [],
        outputSymbols: ["dopamine_not_pah_shortcut_boundary"],
      },
    ],
    units: [],
    assumptions: [
      "Dopamine is not a PAH.",
      "Interstellar aromatic chemistry does not establish terrestrial dopamine biosynthesis.",
      "No pleasure-optimization law is encoded by this bridge.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      docRef("docs/architecture/astrochemistry-prebiotic-neuro-consciousness-bridge-plan.md", "forbidden-shortcut"),
      docRef("docs/knowledge/bridges/astrochemistry-prebiotic-neuro-consciousness-bridge-tree.json", "dopamine_is_not_pah"),
      docRef("docs/knowledge/physics/terrestrial-catecholamine-biosynthesis.md"),
      docRef("docs/knowledge/physics/dopamine-reward-signaling.md"),
    ],
    hintKeys: {
      subjects: ["prebiotic", "claim_boundary", "dopamine", "pah", "reward_signaling", "shortcut_block"],
      symbols: ["dopamine_not_pah_shortcut_boundary"],
      unitSignatures: [],
      repoPaths: [
        "docs/architecture/astrochemistry-prebiotic-neuro-consciousness-bridge-plan.md",
        "docs/knowledge/bridges/astrochemistry-prebiotic-neuro-consciousness-bridge-tree.json",
        "docs/knowledge/physics/terrestrial-catecholamine-biosynthesis.md",
        "docs/knowledge/physics/dopamine-reward-signaling.md",
      ],
      equationFamilies: ["dopamine_shortcut_boundary", "prebiotic_claim_boundary"],
      simulationOwners: ["astrochemistry_prebiotic"],
    },
  }),
  prebioticBadge({
    id: "biophysics.membrane.open_system_entropy_flow",
    title: "Membrane Open-System Entropy Flow",
    plainMeaning:
      "Represents membrane-bounded chemistry as open-system entropy production and entropy-flow context.",
    whyItMatters:
      "It gives synchrony and membrane language a thermodynamic footing without encoding will, pleasure, or teleology as a law.",
    subjects: ["biophysics", "membrane", "open_system", "entropy", "non_equilibrium"],
    level: "derived_relation",
    status: "diagnostic",
    simulationOwners: ["astrochemistry_prebiotic"],
    equationFamilies: ["open_system_entropy", "membrane_transport_context"],
    tags: ["entropy", "membrane", "open_system", "calculator_loadable"],
    equations: [
      {
        id: "open_system_entropy_balance",
        role: "law",
        displayLatex: "\\frac{dS_{sys}}{dt}=\\sigma+\\Phi",
        computableExpression: "dS_system_dt = sigma_entropy_production + Phi_entropy_flow",
        operatorKind: "scalar_expression",
        inputSymbols: ["sigma_entropy_production", "Phi_entropy_flow"],
        outputSymbols: ["dS_system_dt"],
      },
      {
        id: "entropy_production_nonnegative",
        role: "constraint",
        displayLatex: "\\sigma\\ge 0",
        computableExpression: null,
        operatorKind: "gate_status",
        inputSymbols: ["sigma_entropy_production"],
        outputSymbols: ["entropy_production_gate_status"],
      },
    ],
    units: [
      { symbol: "dS_system_dt", unit: "J/K/s", quantity: "entropy_rate", dimensionSignature: "M L^2 T^-3 Theta^-1" },
      {
        symbol: "sigma_entropy_production",
        unit: "J/K/s",
        quantity: "entropy_production_rate",
        dimensionSignature: "M L^2 T^-3 Theta^-1",
      },
      {
        symbol: "Phi_entropy_flow",
        unit: "J/K/s",
        quantity: "entropy_flow_rate",
        dimensionSignature: "M L^2 T^-3 Theta^-1",
      },
    ],
    assumptions: [
      "Membranes regulate matter, energy, charge, and chemical-potential gradients.",
      "Local order may be maintained by exporting entropy.",
      "This row does not encode will, pleasure optimization, or consciousness.",
    ],
    calculatorPayloads: [
      payload({
        id: "open_system_entropy_balance_payload",
        expression: "dS_system_dt = sigma_entropy_production + Phi_entropy_flow",
        displayLatex: "\\frac{dS_{sys}}{dt}=\\sigma+\\Phi",
        targetVariable: "dS_system_dt",
      }),
    ],
    sourceRefs: [
      docRef("docs/knowledge/physics/physics-thermodynamics-entropy-tree.json", "open-system entropy context"),
      docRef("docs/architecture/astrochemistry-prebiotic-neuro-consciousness-bridge-plan.md", "maturity-policy"),
    ],
    hintKeys: {
      subjects: ["biophysics", "membrane", "open_system", "entropy", "non_equilibrium"],
      symbols: ["dS_system_dt", "sigma_entropy_production", "Phi_entropy_flow"],
      unitSignatures: ["M L^2 T^-3 Theta^-1"],
      repoPaths: [
        "docs/knowledge/physics/physics-thermodynamics-entropy-tree.json",
        "docs/architecture/astrochemistry-prebiotic-neuro-consciousness-bridge-plan.md",
      ],
      equationFamilies: ["open_system_entropy", "membrane_transport_context"],
      simulationOwners: ["astrochemistry_prebiotic"],
    },
  }),
  prebioticBadge({
    id: "orch_or.claim_boundary.prebiotic_consciousness_exploratory_only",
    title: "Prebiotic Consciousness Bridge Boundary",
    plainMeaning:
      "Blocks prebiotic chemistry, molecular oscillator, RNA, membrane, and stellar-carbon rows from promoting into consciousness or objective-collapse claims.",
    whyItMatters:
      "It keeps the astrochemistry bridge adjacent to Orch-OR without treating adjacency as evidence.",
    subjects: ["astrochemistry_prebiotic", "claim_boundary", "orch_or", "consciousness", "objective_collapse"],
    level: "claim_boundary",
    status: "blocked",
    simulationOwners: ["astrochemistry_prebiotic", "orch_or_coherence"],
    equationFamilies: ["prebiotic_claim_boundary", "orch_or_claim_boundary"],
    tags: ["claim_boundary", "exploratory_only", "blocks_promotion"],
    equations: [
      {
        id: "prebiotic_bridge_boundary_reference",
        role: "noncomputable_reference",
        displayLatex: "\\mathrm{prebiotic\\ coherence\\ context}\\nRightarrow\\mathrm{consciousness\\ validation}",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: [],
        outputSymbols: ["prebiotic_consciousness_claim_boundary"],
      },
    ],
    units: [],
    assumptions: [
      "Coupled aromatic oscillators may be represented as exploratory open-system molecular-coherence context.",
      "This does not validate OR, consciousness, pleasure optimization, or wavefunction-collapse biology.",
      "No row in this lane validates NHM2, objective collapse, Orch-OR, or a physical consciousness mechanism.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      docRef("docs/architecture/astrochemistry-prebiotic-neuro-consciousness-bridge-plan.md", "falsifier-requirements"),
      docRef("docs/knowledge/bridges/astrochemistry-prebiotic-neuro-consciousness-bridge-tree.json", "orch_or_requires_direct_measurement_contract"),
    ],
    hintKeys: {
      subjects: ["astrochemistry_prebiotic", "claim_boundary", "orch_or", "consciousness", "objective_collapse"],
      symbols: ["prebiotic_consciousness_claim_boundary"],
      unitSignatures: [],
      repoPaths: [
        "docs/architecture/astrochemistry-prebiotic-neuro-consciousness-bridge-plan.md",
        "docs/knowledge/bridges/astrochemistry-prebiotic-neuro-consciousness-bridge-tree.json",
      ],
      equationFamilies: ["prebiotic_claim_boundary", "orch_or_claim_boundary"],
      simulationOwners: ["astrochemistry_prebiotic", "orch_or_coherence"],
    },
  }),
];

export const ASTROCHEMISTRY_PREBIOTIC_THEORY_EDGES: TheoryBadgeEdgeV1[] = [
  {
    id: "stellar_nucleosynthesis_documents_aromatic_carbon",
    from: "stellar.nucleosynthesis.reaction_network_context",
    to: "astrochemistry.aromatic_carbon.interstellar_context",
    relation: "documents",
    label: "Stellar nucleosynthesis provides the carbon-enrichment context for aromatic astrochemistry.",
    claimBoundaryNote: "Stellar carbon context does not imply prebiotic success or consciousness.",
  },
  {
    id: "aromatic_carbon_documents_c60_fullerene",
    from: "astrochemistry.aromatic_carbon.interstellar_context",
    to: "astrochemistry.fullerene.c60_stellar_context",
    relation: "documents",
    label: "Aromatic carbon context documents fullerene C60 spectral chemistry.",
    claimBoundaryNote: "C60 spectral context is not evidence for life, consciousness, or objective collapse.",
  },
  {
    id: "aromatic_carbon_requires_lab_spectroscopy_fingerprint",
    from: "astrochemistry.aromatic_carbon.interstellar_context",
    to: "astrochemistry.lab_spectroscopy.molecular_fingerprint_foundation",
    relation: "requires",
    label: "Aromatic carbon detections require laboratory spectroscopy as the molecular-fingerprint basis.",
    claimBoundaryNote: "Laboratory line assignments are identification evidence, not pathway or life validation.",
  },
  {
    id: "lab_spectroscopy_documents_small_organic_inventory",
    from: "astrochemistry.lab_spectroscopy.molecular_fingerprint_foundation",
    to: "astrochemistry.prebiotic.small_organic_dense_cloud_inventory",
    relation: "documents",
    label: "Laboratory molecular fingerprints document small-organic dense-cloud inventory rows.",
    claimBoundaryNote: "Identified small organics remain model-conditioned inventory evidence.",
  },
  {
    id: "small_organic_inventory_requires_spectral_model_boundary",
    from: "astrochemistry.prebiotic.small_organic_dense_cloud_inventory",
    to: "astrochemistry.claim_boundary.spectral_model_inference_only",
    relation: "requires",
    label: "Small-organic inventory claims require the spectral/model inference boundary.",
    claimBoundaryNote: "Dense-cloud organic inventory does not prove formation pathway, delivery, life, or consciousness.",
  },
  {
    id: "small_organic_inventory_documents_phosphorus_context",
    from: "astrochemistry.prebiotic.small_organic_dense_cloud_inventory",
    to: "astrochemistry.phosphorus.po_pn_molecular_cloud_context",
    relation: "documents",
    label: "Small-organic prebiotic inventory context documents the adjacent PO/PN phosphorus lane.",
    claimBoundaryNote: "Observed phosphorus-bearing molecules do not prove bioavailable phosphate or RNA chemistry.",
  },
  {
    id: "aromatic_carbon_documents_c60_c70_fullerene_family",
    from: "astrochemistry.aromatic_carbon.interstellar_context",
    to: "astrochemistry.fullerene.c60_c70_carbon_cage_context",
    relation: "documents",
    label: "Aromatic carbon context documents the broader C60/C70 carbon-cage fullerene family.",
    claimBoundaryNote: "Fullerene-family chemistry is carbon-carrier context, not life evidence.",
  },
  {
    id: "c60_context_documents_c60_c70_family_context",
    from: "astrochemistry.fullerene.c60_stellar_context",
    to: "astrochemistry.fullerene.c60_c70_carbon_cage_context",
    relation: "documents",
    label: "The existing C60 row documents the broader C60/C70 fullerene-family context.",
    claimBoundaryNote: "Extending C60 to fullerene-family context does not promote the claim beyond spectroscopy.",
  },
  {
    id: "fullerene_family_blocks_life_overclaim",
    from: "astrochemistry.fullerene.c60_c70_carbon_cage_context",
    to: "astrochemistry.claim_boundary.spectral_model_inference_only",
    relation: "blocks",
    label: "Fullerene-family detections are blocked from promotion into life or abiogenesis claims.",
    claimBoundaryNote: "Carbon cages are not direct evidence of biology, consciousness, or objective collapse.",
  },
  {
    id: "aromatic_carbon_documents_pah_spectral_family",
    from: "astrochemistry.aromatic_carbon.interstellar_context",
    to: "astrochemistry.pah.spectral_family_context",
    relation: "documents",
    label: "Aromatic carbon context documents PAH-family spectral chemistry.",
    claimBoundaryNote: "PAH-family spectral context is not a dopamine, life, consciousness, or collapse claim.",
  },
  {
    id: "aromatic_carbon_documents_complex_organic_inventory",
    from: "astrochemistry.aromatic_carbon.interstellar_context",
    to: "astrochemistry.complex_organics.dense_source_inventory_context",
    relation: "documents",
    label: "Aromatic carbon context documents complex organic molecule inventory evidence in dense sources.",
    claimBoundaryNote: "Complex organic inventory is not prebiotic success, biology, or consciousness evidence.",
  },
  {
    id: "complex_organic_inventory_requires_source_class_context",
    from: "astrochemistry.complex_organics.dense_source_inventory_context",
    to: "astrochemistry.source_class.chemical_differentiation_context",
    relation: "requires",
    label: "Complex organic inventories require source-class and chemical-history context.",
    claimBoundaryNote: "A molecule list cannot be compared across environments without source conditioning.",
  },
  {
    id: "complex_organic_inventory_requires_spectral_model_boundary",
    from: "astrochemistry.complex_organics.dense_source_inventory_context",
    to: "astrochemistry.claim_boundary.spectral_model_inference_only",
    relation: "requires",
    label: "Complex organic inventory claims require spectral and chemistry-model inference boundaries.",
    claimBoundaryNote: "Spectral assignment and abundance estimates remain model-conditioned evidence.",
  },
  {
    id: "complex_organic_inventory_documents_gas_grain_ice_context",
    from: "astrochemistry.complex_organics.dense_source_inventory_context",
    to: "astrochemistry.gas_grain.ice_mantle_formation_context",
    relation: "documents",
    label: "Complex organic inventories document gas-grain and ice-mantle formation context.",
    claimBoundaryNote: "Ice-mantle context does not prove a complete formation pathway or delivery route.",
  },
  {
    id: "gas_grain_ice_context_bounds_meteoritic_inventory",
    from: "astrochemistry.gas_grain.ice_mantle_formation_context",
    to: "prebiotic.inventory.meteoritic_organics_context",
    relation: "bounds",
    label: "Gas-grain and ice-mantle chemistry bounds comparisons to meteoritic organic inventories.",
    claimBoundaryNote: "Astrochemical formation context is not equivalent to returned-sample prebiotic availability.",
  },
  {
    id: "source_class_context_blocks_universal_organic_inventory",
    from: "astrochemistry.source_class.chemical_differentiation_context",
    to: "astrochemistry.claim_boundary.spectral_model_inference_only",
    relation: "blocks",
    label: "Source-class differentiation blocks universalized complex-organic inventory claims.",
    claimBoundaryNote: "Source-conditioned chemistry cannot be promoted to a universal route without additional evidence.",
  },
  {
    id: "pah_spectral_family_documents_meteoritic_inventory",
    from: "astrochemistry.pah.spectral_family_context",
    to: "prebiotic.inventory.meteoritic_organics_context",
    relation: "documents",
    label: "PAH-family astrochemistry can be compared with returned-sample organic inventory rows.",
    claimBoundaryNote: "Organic inventory context does not imply successful abiogenesis.",
  },
  {
    id: "phosphorus_context_bounds_planetary_delivery",
    from: "astrochemistry.phosphorus.po_pn_molecular_cloud_context",
    to: "astrochemistry.planetary_delivery.meteorite_comet_link_context",
    relation: "bounds",
    label: "PO/PN molecular-cloud phosphorus context bounds planetary-delivery interpretation.",
    claimBoundaryNote: "Phosphorus-bearing astrochemistry is not the same as delivered bioavailable phosphate.",
  },
  {
    id: "meteoritic_inventory_documents_planetary_delivery_link",
    from: "prebiotic.inventory.meteoritic_organics_context",
    to: "astrochemistry.planetary_delivery.meteorite_comet_link_context",
    relation: "documents",
    label: "Meteoritic inventory context documents the meteorite/comet delivery link.",
    claimBoundaryNote: "Inventory-plus-delivery context still does not prove abiogenesis.",
  },
  {
    id: "planetary_delivery_requires_protoplanetary_processing_boundary",
    from: "astrochemistry.planetary_delivery.meteorite_comet_link_context",
    to: "astrochemistry.claim_boundary.protoplanetary_processing_uncertain",
    relation: "requires",
    label: "Planetary-delivery interpretation requires the protoplanetary processing uncertainty boundary.",
    claimBoundaryNote: "Disk processing, alteration, concentration, and local availability remain unresolved gates.",
  },
  {
    id: "protoplanetary_processing_boundary_blocks_consciousness_promotion",
    from: "astrochemistry.claim_boundary.protoplanetary_processing_uncertain",
    to: "orch_or.claim_boundary.prebiotic_consciousness_exploratory_only",
    relation: "blocks",
    label: "Protoplanetary processing uncertainty blocks promotion into prebiotic consciousness claims.",
    claimBoundaryNote: "Astrochemical inheritance cannot validate consciousness or objective-collapse biology.",
  },
  {
    id: "protoplanetary_processing_boundary_bounds_surface_catalysis",
    from: "astrochemistry.claim_boundary.protoplanetary_processing_uncertain",
    to: "prebiotic.surface_catalysis.mineral_aqueous_context",
    relation: "bounds",
    label: "Protoplanetary processing uncertainty bounds later surface-catalysis interpretation.",
    claimBoundaryNote: "Local mineral and aqueous chemistry must be represented separately from inherited inventory.",
  },
  {
    id: "meteoritic_inventory_documents_photochemical_processing",
    from: "prebiotic.inventory.meteoritic_organics_context",
    to: "prebiotic.photochemistry.radiation_processing_context",
    relation: "documents",
    label: "Prebiotic inventories need environmental processing context such as photon fluence.",
    claimBoundaryNote: "Photochemical processing context does not certify an origin pathway.",
  },
  {
    id: "meteoritic_inventory_documents_surface_catalysis",
    from: "prebiotic.inventory.meteoritic_organics_context",
    to: "prebiotic.surface_catalysis.mineral_aqueous_context",
    relation: "documents",
    label: "Organic inventories need mineral, salt, and aqueous alteration context before reaction-path interpretation.",
    claimBoundaryNote: "Surface and aqueous context remain diagnostic constraints.",
  },
  {
    id: "aromatic_carbon_documents_coupled_ring_context",
    from: "astrochemistry.aromatic_carbon.interstellar_context",
    to: "prebiotic.aromatic_ring.coupled_oscillator_context",
    relation: "documents",
    label: "Aromatic carbon chemistry can document speculative coupled-ring oscillator context.",
    claimBoundaryNote: "Molecular coupling is not OR evidence.",
  },
  {
    id: "coupled_ring_requires_decoherence_lifetime_gate",
    from: "prebiotic.aromatic_ring.coupled_oscillator_context",
    to: "prebiotic.coherence.decoherence_lifetime_gate",
    relation: "requires",
    label: "Coupled-ring coherence discussion requires an explicit lifetime and candidate-timescale gate.",
    claimBoundaryNote: "A lifetime gate is necessary context, not OR validation.",
  },
  {
    id: "decoherence_lifetime_gate_blocks_prebiotic_consciousness_promotion",
    from: "prebiotic.coherence.decoherence_lifetime_gate",
    to: "orch_or.claim_boundary.prebiotic_consciousness_exploratory_only",
    relation: "blocks",
    label: "A molecular coherence lifetime gate cannot promote into consciousness or objective-collapse validation.",
    claimBoundaryNote: "Even a positive coherence margin would remain exploratory and non-validating.",
  },
  {
    id: "coupled_ring_documents_membrane_entropy_context",
    from: "prebiotic.aromatic_ring.coupled_oscillator_context",
    to: "biophysics.membrane.open_system_entropy_flow",
    relation: "documents",
    label: "Coupled molecular context can be discussed alongside membrane-bounded open-system entropy flow.",
    claimBoundaryNote: "Open-system entropy flow is not a pleasure or consciousness law.",
  },
  {
    id: "membrane_entropy_bounds_rna_world_context",
    from: "biophysics.membrane.open_system_entropy_flow",
    to: "prebiotic.rna_world.ribozyme_context",
    relation: "bounds",
    label: "Open-system thermodynamic boundaries constrain origin-of-life chemistry context.",
    claimBoundaryNote: "RNA-world context is separate from Hameroff-style aromatic-ring claims.",
  },
  {
    id: "surface_catalysis_bounds_rna_world_context",
    from: "prebiotic.surface_catalysis.mineral_aqueous_context",
    to: "prebiotic.rna_world.ribozyme_context",
    relation: "bounds",
    label: "Mineral and aqueous chemistry context bounds RNA-world reaction interpretations.",
    claimBoundaryNote: "Surface context does not validate RNA-world as a solved origin pathway.",
  },
  {
    id: "pah_spectral_family_blocks_dopamine_shortcut",
    from: "astrochemistry.pah.spectral_family_context",
    to: "prebiotic.claim_boundary.dopamine_not_pah_shortcut",
    relation: "blocks",
    label: "PAH-family astrochemistry cannot shortcut into dopamine or pleasure-law claims.",
    claimBoundaryNote: "Dopamine biosynthesis and reward signaling require separate terrestrial biology evidence.",
  },
  {
    id: "meteoritic_inventory_blocks_dopamine_shortcut",
    from: "prebiotic.inventory.meteoritic_organics_context",
    to: "prebiotic.claim_boundary.dopamine_not_pah_shortcut",
    relation: "blocks",
    label: "Prebiotic organic inventories cannot shortcut into dopamine inheritance claims.",
    claimBoundaryNote: "Ingredient context is not neurotransmitter lineage evidence.",
  },
  {
    id: "dopamine_shortcut_boundary_documents_prebiotic_boundary",
    from: "prebiotic.claim_boundary.dopamine_not_pah_shortcut",
    to: "orch_or.claim_boundary.prebiotic_consciousness_exploratory_only",
    relation: "documents",
    label: "The dopamine shortcut boundary points to the broader prebiotic consciousness boundary.",
    claimBoundaryNote: "Reward-system adjacency is boundary context, not consciousness evidence.",
  },
  {
    id: "coupled_ring_blocks_prebiotic_consciousness_promotion",
    from: "prebiotic.aromatic_ring.coupled_oscillator_context",
    to: "orch_or.claim_boundary.prebiotic_consciousness_exploratory_only",
    relation: "blocks",
    label: "Coupled aromatic oscillators cannot promote into consciousness or objective-collapse validation.",
    claimBoundaryNote: "Requires direct OR-specific evidence and remains exploratory.",
  },
  {
    id: "rna_world_blocks_prebiotic_consciousness_promotion",
    from: "prebiotic.rna_world.ribozyme_context",
    to: "orch_or.claim_boundary.prebiotic_consciousness_exploratory_only",
    relation: "blocks",
    label: "RNA catalytic context cannot promote into Orch-OR or consciousness validation.",
    claimBoundaryNote: "RNA-world evidence is origin-of-life context, not consciousness evidence.",
  },
  {
    id: "prebiotic_boundary_documents_orch_or_boundary",
    from: "orch_or.claim_boundary.prebiotic_consciousness_exploratory_only",
    to: "orch_or.claim_boundary.exploratory_only",
    relation: "documents",
    label: "The prebiotic bridge boundary points to the broader Orch-OR exploratory boundary.",
    claimBoundaryNote: "Adjacency to Orch-OR is boundary context, not proof.",
  },
];

export function buildAstrochemistryPrebioticTheoryBadgesV1(): {
  badges: TheoryBadgeV1[];
  edges: TheoryBadgeEdgeV1[];
} {
  return {
    badges: ASTROCHEMISTRY_PREBIOTIC_THEORY_BADGES.map((badge: TheoryBadgeV1) => ({ ...badge })),
    edges: ASTROCHEMISTRY_PREBIOTIC_THEORY_EDGES.map((edge: TheoryBadgeEdgeV1) => ({ ...edge })),
  };
}
