import {
  type TheoryBadgeClaimBoundaryV1,
  type TheoryBadgeEdgeV1,
  type TheoryBadgeV1,
} from "../contracts/theory-badge-graph.v1";

const STUDY_BOUNDARY: TheoryBadgeClaimBoundaryV1 = {
  diagnosticOnly: true,
  doesValidateNHM2: false,
  validationClaimAllowed: false,
  physicalMechanismClaimAllowed: false,
  promotionAllowed: false,
};

const sourceRef = (
  kind: TheoryBadgeV1["sourceRefs"][number]["kind"],
  path: string,
  id?: string,
  note?: string,
): TheoryBadgeV1["sourceRefs"][number] => ({
  kind,
  path,
  id: id ?? null,
  note: note ?? null,
});

const studyBadge = (badge: Omit<TheoryBadgeV1, "claimBoundary">): TheoryBadgeV1 => ({
  ...badge,
  claimBoundary: STUDY_BOUNDARY,
});

export const CASIMIR_DP_STUDY_THEORY_BADGES: TheoryBadgeV1[] = [
  studyBadge({
    id: "study.casimir_dp.protocol",
    title: "Casimir / DP Separated-Lane Study Protocol",
    plainMeaning:
      "Runs Casimir reference, material/metrology, DP branch, bounds, bridge, sensitivity, reproduction, and paper-update stages in dependency order.",
    whyItMatters:
      "It transfers the reproducibility discipline of the NHM2 full solve without importing NHM2 force, source, transport, or viability assumptions.",
    subjects: [
      "casimir_dp_study",
      "casimir_effect",
      "diosi_penrose",
      "quantum_foam",
      "study_protocol",
      "run_order",
      "reproducibility",
    ],
    level: "simulation_specific",
    status: "diagnostic",
    simulationOwners: ["casimir_dp_study", "casimir", "curvature_collapse"],
    equationFamilies: ["study_protocol", "casimir_energy", "dp_collapse"],
    tags: ["whitepaper", "runtime_reference", "ordered_protocol", "diagnostic_only"],
    equations: [
      {
        id: "casimir_dp_canonical_run_order",
        role: "noncomputable_reference",
        displayLatex:
          "P_{study}=P_{freeze}\\prec P_{Casimir}\\prec P_{material}\\prec P_{DP}\\prec P_{bounds}\\prec P_{bridge}\\prec P_{sensitivity}\\prec P_{reproduce}\\prec P_{paper}",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["study_config", "runtime_receipts", "evidence_receipts"],
        outputSymbols: ["study_run_receipt"],
      },
    ],
    units: [],
    assumptions: [
      "Stage authority follows dependency order even when a stage uses internal parallelism.",
      "A completed process receipt does not turn blocked or not-ready scientific gates into pass.",
      "The protocol is independent of NHM2 source closure, transport, viability, and certificate semantics.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      sourceRef("doc", "docs/research/casimir-dp-quantum-foam-study.md", "CDP-QF-1", "Maintained study paper."),
      sourceRef("doc", "docs/research/study-full-solve-template.md", "full-solve-study-template", "Reusable study protocol."),
      sourceRef("repo_module", "scripts/research/run-casimir-dp-quantum-foam-study.ts", "runCasimirDpStudy", "Deterministic diagnostic runner."),
      sourceRef("artifact", "configs/research/casimir-dp-quantum-foam-study.v1.json", "diagnostic-smoke-v1", "Machine-readable stage order and smoke inputs."),
    ],
    hintKeys: {
      subjects: ["casimir dp study", "casimir effect", "diosi penrose", "quantum foam", "full solve", "study protocol"],
      symbols: ["P_study", "study_run_receipt"],
      unitSignatures: [],
      repoPaths: [
        "docs/research/casimir-dp-quantum-foam-study.md",
        "docs/research/study-full-solve-template.md",
        "configs/research/casimir-dp-quantum-foam-study.v1.json",
        "scripts/research/run-casimir-dp-quantum-foam-study.ts",
      ],
      equationFamilies: ["study_protocol", "casimir_energy", "dp_collapse"],
      simulationOwners: ["casimir_dp_study", "casimir", "curvature_collapse"],
    },
  }),
  studyBadge({
    id: "study.casimir_dp.manifold_response_hypothesis",
    title: "Boundary-Conditioned Manifold-Response Hypothesis",
    plainMeaning:
      "Tests whether a controlled Casimir boundary change leaves a coherence-rate residual after ordinary electromagnetic, thermal, mechanical, and readout decoherence are accounted for.",
    whyItMatters:
      "It turns the proposed vacuum/manifold connection into a differential observable while keeping semiclassical mean stress, stochastic metric fluctuations, DP collapse, and quantum foam as distinct model classes.",
    subjects: [
      "casimir_dp_study",
      "semiclassical_gravity",
      "stochastic_gravity",
      "boundary_conditioned_coherence",
      "manifold_response",
    ],
    level: "model",
    status: "blocked",
    simulationOwners: ["casimir_dp_study", "casimir", "curvature_collapse"],
    equationFamilies: ["semiclassical_einstein", "stress_tensor_noise", "coherence_residual"],
    tags: ["stage_0", "hypothesis", "noncomputable", "decoherence_budget_required"],
    equations: [
      {
        id: "semiclassical_curvature_baseline",
        role: "noncomputable_reference",
        displayLatex:
          "G_{\\mu\\nu}+\\Lambda g_{\\mu\\nu}=\\frac{8\\pi G}{c^4}\\langle\\hat T_{\\mu\\nu}\\rangle_{\\rm ren}",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["T_munu_ren", "Lambda", "metric", "renormalization_contract"],
        outputSymbols: ["metric_response"],
      },
      {
        id: "boundary_conditioned_coherence_residual",
        role: "noncomputable_reference",
        displayLatex:
          "\\Delta\\Gamma_{res}=\\Delta_b\\Gamma_{obs}-\\Delta\\Gamma_{EM}-\\Delta\\Gamma_{thermal}-\\Delta\\Gamma_{mech}-\\Delta\\Gamma_{readout}",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["Gamma_b1", "Gamma_b0", "standard_decoherence_budget"],
        outputSymbols: ["delta_Gamma_res"],
      },
      {
        id: "manifold_response_slot",
        role: "noncomputable_reference",
        displayLatex:
          "\\Delta\\Gamma_{MR}=\\mathcal{F}_{MR}[\\Delta_b\\langle\\hat T_{\\mu\\nu}\\rangle_{ren},N_{\\mu\\nu\\rho\\sigma},\\Delta\\rho;\\theta_{MR}]",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["delta_b_T_munu_ren", "noise_kernel", "delta_rho", "theta_MR"],
        outputSymbols: ["delta_Gamma_MR"],
      },
    ],
    units: [
      { symbol: "delta_Gamma_res", unit: "s^-1", quantity: "coherence_decay_rate_residual", dimensionSignature: "T^-1" },
      { symbol: "delta_Gamma_MR", unit: "s^-1", quantity: "candidate_manifold_response_rate", dimensionSignature: "T^-1" },
      { symbol: "T_munu_ren", unit: "J m^-3", quantity: "renormalized_stress_energy_component", dimensionSignature: "M L^-1 T^-2" },
    ],
    assumptions: [
      "Math maturity is Stage 0 exploratory and no tensor-to-metric-to-coherence functional is registered.",
      "A cavity boundary setting is not a DP material branch.",
      "A negative renormalized energy-density component does not uniquely determine curvature sign or geometry.",
      "Virtual particles are not treated as literal prepared branches with annihilation lifetimes.",
      "The material branch distribution and standard decoherence budget must be fixed before the target comparison.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      sourceRef("doc", "docs/research/casimir-dp-quantum-foam-study.md", "manifold-response-hypothesis", "Stage-0 hypothesis, direct-manipulation protocol, and non-claims."),
      sourceRef("literature_ref", "https://doi.org/10.12942/lrr-2008-3", "Hu-Verdaguer-2008", "Semiclassical mean stress and stochastic-gravity noise-kernel framework."),
      sourceRef("literature_ref", "https://doi.org/10.1007/BF02105068", "Penrose-1996", "Objective-reduction motivation; not a derivation of the proposed Casimir bridge."),
    ],
    hintKeys: {
      subjects: ["manifold response", "boundary conditioned coherence", "semiclassical gravity", "stochastic gravity", "vacuum collapse"],
      symbols: ["T_munu_ren", "delta_Gamma_res", "delta_Gamma_MR", "noise_kernel"],
      unitSignatures: ["T^-1", "M L^-1 T^-2"],
      repoPaths: ["docs/research/casimir-dp-quantum-foam-study.md"],
      equationFamilies: ["semiclassical_einstein", "stress_tensor_noise", "coherence_residual"],
      simulationOwners: ["casimir_dp_study", "casimir", "curvature_collapse"],
    },
  }),
  studyBadge({
    id: "study.casimir_dp.decoherence_collapse_gate",
    title: "Decoherence / Objective-Collapse Separation Gate",
    plainMeaning:
      "Blocks identification of boundary-conditioned visibility loss with objective collapse while ordinary open-system explanations remain viable.",
    whyItMatters:
      "Decoherence and objective collapse can both reduce interference, but they assert different dynamics and require discriminating evidence.",
    subjects: ["casimir_dp_study", "decoherence", "objective_collapse", "coherence_rate", "model_selection"],
    level: "diagnostic_gate",
    status: "blocked",
    simulationOwners: ["casimir_dp_study", "curvature_collapse"],
    equationFamilies: ["coherence_residual", "collapse_model_selection"],
    tags: ["hard_gate", "fail_closed", "ordinary_decoherence_not_closed"],
    equations: [
      {
        id: "decoherence_collapse_identification_gate",
        role: "gate",
        displayLatex:
          "\\mathrm{Identify}(\\Delta\\Gamma_{res},\\Gamma_{collapse})=\\mathrm{BLOCKED}:\\mathrm{ordinary\\ decoherence\\ alternatives\\ remain}",
        computableExpression: null,
        operatorKind: "gate_status",
        inputSymbols: ["delta_Gamma_res", "standard_decoherence_receipts", "dynamics_discriminator"],
        outputSymbols: ["decoherence_collapse_gate_status"],
      },
    ],
    units: [
      { symbol: "delta_Gamma_res", unit: "s^-1", quantity: "coherence_decay_rate_residual", dimensionSignature: "T^-1" },
      { symbol: "Gamma_collapse", unit: "s^-1", quantity: "objective_collapse_rate", dimensionSignature: "T^-1" },
    ],
    observables: [
      {
        id: "study_boundary_conditioned_coherence_residual",
        canonicalObservableId: "observable.coherence.boundary_conditioned_decay_residual",
        symbol: "delta_Gamma_res",
        quantity: "boundary_conditioned_coherence_decay_rate_after_standard_budget",
        mathematicalType: "scalar",
        unit: "s^-1",
        dimensionSignature: "T^-1",
        coordinateFrame: "apparatus_clock",
        operationalDefinitionRef: "manifold-response-hypothesis",
        responseModelRef: "manifold-response-hypothesis",
      },
      {
        id: "study_objective_collapse_rate",
        canonicalObservableId: "observable.collapse.objective_rate",
        symbol: "Gamma_collapse",
        quantity: "registered_objective_collapse_model_rate",
        mathematicalType: "scalar",
        unit: "s^-1",
        dimensionSignature: "T^-1",
        coordinateFrame: "collapse_model_time",
        operationalDefinitionRef: "computeDpCollapse",
        responseModelRef: "computeDpCollapse",
      },
    ],
    assumptions: [
      "Reduced visibility alone does not identify nonunitary dynamics.",
      "All ordinary decoherence contributions and uncertainties must be pre-registered and receipt-backed.",
      "Correlation with a cavity boundary setting does not establish a gravitational cause.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      sourceRef("doc", "docs/research/casimir-dp-quantum-foam-study.md", "manifold-response-hypothesis", "Coherence residual and direct-manipulation protocol."),
      sourceRef("repo_module", "shared/dp-collapse.ts", "computeDpCollapse", "Current DP model-rate authority."),
      sourceRef("literature_ref", "https://doi.org/10.1038/s41567-020-1008-4", "Donadi-et-al-2021", "Independent collapse-model constraint context."),
    ],
    hintKeys: {
      subjects: ["decoherence versus collapse", "visibility loss", "objective collapse", "coherence residual"],
      symbols: ["delta_Gamma_res", "Gamma_collapse"],
      unitSignatures: ["T^-1"],
      repoPaths: ["docs/research/casimir-dp-quantum-foam-study.md", "shared/dp-collapse.ts"],
      equationFamilies: ["coherence_residual", "collapse_model_selection"],
      simulationOwners: ["casimir_dp_study", "curvature_collapse"],
    },
  }),
  studyBadge({
    id: "study.casimir_dp.quantum_foam_hypothesis",
    title: "Quantum-Foam Casimir Residual Hypothesis",
    plainMeaning:
      "Reserves a bounded model slot for a future quantum-spacetime response function that predicts a Casimir observable residual.",
    whyItMatters:
      "It makes the speculative mechanism explicit and falsifiable instead of embedding quantum-foam language in the accepted Casimir baseline.",
    subjects: ["casimir_dp_study", "quantum_foam", "casimir_residual", "coherence_residual", "candidate_mechanism"],
    level: "model",
    status: "blocked",
    simulationOwners: ["casimir_dp_study"],
    equationFamilies: ["quantum_foam_response", "casimir_residual"],
    tags: ["hypothesis", "unregistered_response", "noncomputable", "falsifier_required"],
    equations: [
      {
        id: "quantum_foam_response_slot",
        role: "noncomputable_reference",
        displayLatex:
          "R_F^{foam}=\\mathcal{R}_{foam}(a,T,\\mathcal{G},\\mathcal{M};\\theta_{foam})",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["a", "T", "geometry", "material", "theta_foam"],
        outputSymbols: ["R_F_foam"],
      },
    ],
    units: [
      { symbol: "R_F_foam", unit: "N", quantity: "candidate_force_residual", dimensionSignature: "M L T^-2" },
      { symbol: "a", unit: "m", quantity: "gap", dimensionSignature: "L" },
    ],
    assumptions: [
      "No quantitative response function is currently registered.",
      "The model must recover the standard Casimir baseline in a declared limiting domain.",
      "A nuisance model, error contract, and independent falsifier are required before fitting target residuals.",
      "Quantum foam is not treated as the accepted explanation of the Casimir effect.",
      "Vacuum-induced ordinary decoherence is not identified with objective collapse.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      sourceRef("doc", "docs/research/casimir-dp-quantum-foam-study.md", "lane-c", "Candidate-model requirements and non-claims."),
      sourceRef("literature_ref", "https://doi.org/10.1103/PhysRevD.72.021301", "Jaffe-2005", "Casimir force does not uniquely fix a vacuum ontology."),
      sourceRef("literature_ref", "https://arxiv.org/abs/0912.0535", "Christiansen-et-al-2009", "Example of separately testable spacetime-foam phenomenology and constraints."),
    ],
    hintKeys: {
      subjects: ["quantum foam", "spacetime foam", "casimir residual", "candidate mechanism"],
      symbols: ["R_F_foam", "theta_foam", "a", "T"],
      unitSignatures: ["M L T^-2", "L"],
      repoPaths: ["docs/research/casimir-dp-quantum-foam-study.md"],
      equationFamilies: ["quantum_foam_response", "casimir_residual"],
      simulationOwners: ["casimir_dp_study"],
    },
  }),
  studyBadge({
    id: "study.casimir_dp.observable_separation_gate",
    title: "Casimir-to-DP Observable Separation Gate",
    plainMeaning:
      "Keeps a Casimir force residual distinct from the DP gravitational self-energy built from mass-density branch differences.",
    whyItMatters:
      "It blocks the central category error: treating an overall Casimir force or energy as if it were the DP branch self-energy input.",
    subjects: [
      "casimir_dp_study",
      "observable_identity",
      "casimir_force_residual",
      "dp_self_energy",
      "missing_bridge",
    ],
    level: "diagnostic_gate",
    status: "blocked",
    simulationOwners: ["casimir_dp_study", "casimir", "curvature_collapse"],
    equationFamilies: ["observable_identity", "casimir_residual", "dp_collapse"],
    tags: ["hard_gate", "missing_registered_observable_bridge", "fail_closed"],
    equations: [
      {
        id: "casimir_dp_bridge_gate",
        role: "gate",
        displayLatex:
          "\\mathrm{Bridge}(R_F,\\Delta E_G)=\\mathrm{BLOCKED}:\\mathrm{missing\\ registered\\ observable\\ bridge}",
        computableExpression: null,
        operatorKind: "gate_status",
        inputSymbols: ["R_F", "deltaE_G_J", "observable_bridge_receipt"],
        outputSymbols: ["observable_bridge_status"],
      },
    ],
    units: [
      { symbol: "R_F", unit: "N", quantity: "force_residual", dimensionSignature: "M L T^-2" },
      { symbol: "deltaE_G_J", unit: "J", quantity: "gravitational_self_energy_difference", dimensionSignature: "M L^2 T^-2" },
    ],
    observables: [
      {
        id: "study_casimir_force_residual",
        canonicalObservableId: "observable.casimir.force_residual",
        symbol: "R_F",
        quantity: "observed_minus_standard_casimir_force",
        mathematicalType: "scalar",
        unit: "N",
        dimensionSignature: "M L T^-2",
        coordinateFrame: "apparatus_force_axis",
        operationalDefinitionRef: "observable-separation-gate",
        responseModelRef: "casimir.cavity.parallel_plate_pressure",
      },
      {
        id: "study_dp_gravitational_self_energy",
        canonicalObservableId: "observable.dp.gravitational_self_energy_difference",
        symbol: "deltaE_G_J",
        quantity: "dp_gravitational_self_energy_from_mass_density_branch_difference",
        mathematicalType: "scalar",
        unit: "J",
        dimensionSignature: "M L^2 T^-2",
        coordinateFrame: "dp_branch_density_grid",
        operationalDefinitionRef: "computeDpCollapse",
        responseModelRef: "computeDpCollapse",
      },
    ],
    assumptions: [
      "The two observables have different canonical identities, dimensions, operational definitions, and response models.",
      "No registered transformation currently maps the Casimir residual to DP self-energy.",
      "Shared vocabulary, sign, or energy units elsewhere in the pipeline cannot satisfy this gate.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      sourceRef("doc", "docs/research/casimir-dp-quantum-foam-study.md", "observable-separation-gate", "Study gate and repair conditions."),
      sourceRef("repo_module", "shared/dp-collapse.ts", "computeDpCollapse", "DP input and solver authority."),
      sourceRef("repo_module", "shared/theory/casimir-cavity-theory-badges.ts", "casimir.cavity.parallel_plate_pressure", "Casimir scalar and receipt boundaries."),
      sourceRef("doc", "docs/architecture/theory-badge-graph-contract.md", "observable-identity", "Observable identity and bridge contract."),
    ],
    hintKeys: {
      subjects: ["casimir dp bridge", "observable separation", "casimir force residual", "dp self energy", "missing bridge"],
      symbols: ["R_F", "deltaE_G_J", "observable_bridge_status"],
      unitSignatures: ["M L T^-2", "M L^2 T^-2"],
      repoPaths: [
        "docs/research/casimir-dp-quantum-foam-study.md",
        "shared/dp-collapse.ts",
        "docs/architecture/theory-badge-graph-contract.md",
      ],
      equationFamilies: ["observable_identity", "casimir_residual", "dp_collapse"],
      simulationOwners: ["casimir_dp_study", "casimir", "curvature_collapse"],
    },
  }),
  studyBadge({
    id: "study.casimir_dp.frequency_bridge_gate",
    title: "Compton / DP / Cavity Frequency Separation Gate",
    plainMeaning:
      "Separates the Compton rest-energy frequency, the DP inverse-timescale frequency, and a physical cavity mode until a sourced transfer kernel connects them to one apparatus observable.",
    whyItMatters:
      "It prevents E=mc^2=h nu and matching frequency units from being promoted into an unsupported collapse beat, manifold resonance, or quantum-foam spectral prediction.",
    subjects: [
      "casimir_dp_study",
      "compton_frequency",
      "dp_timescale",
      "cavity_frequency",
      "observable_transfer",
      "claim_boundary",
    ],
    level: "diagnostic_gate",
    status: "blocked",
    simulationOwners: ["casimir_dp_study", "casimir", "curvature_collapse"],
    equationFamilies: ["compton_frequency", "dp_timescale", "frequency_bridge"],
    tags: ["hard_gate", "fail_closed", "missing_transfer_kernel", "no_resonance_claim"],
    equations: [
      {
        id: "compton_dp_frequency_identities",
        role: "noncomputable_reference",
        displayLatex:
          "\\nu_C=mc^2/h,\\quad\\nu_{DP}=\\Delta E_G/h=(2\\pi\\tau_{DP})^{-1},\\quad\\omega_{DP}=\\Delta E_G/\\hbar=\\tau_{DP}^{-1}",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["mass", "deltaE_G_J", "tau_DP"],
        outputSymbols: ["nu_C", "nu_DP", "omega_DP"],
      },
      {
        id: "compton_dp_cavity_bridge_gate",
        role: "gate",
        displayLatex:
          "\\mathrm{Bridge}(\\nu_C,\\nu_{DP},\\omega_{cavity})=\\mathrm{BLOCKED}:\\mathcal K_{cavity\\rightarrow branch/coherence}\\ \\mathrm{not\\ registered}",
        computableExpression: null,
        operatorKind: "gate_status",
        inputSymbols: ["nu_C", "nu_DP", "omega_cavity", "transfer_kernel_receipt"],
        outputSymbols: ["frequency_bridge_status"],
      },
    ],
    units: [
      { symbol: "nu_C", unit: "Hz", quantity: "compton_rest_energy_frequency", dimensionSignature: "T^-1" },
      { symbol: "nu_DP", unit: "Hz", quantity: "dp_cyclic_inverse_timescale", dimensionSignature: "T^-1" },
      { symbol: "omega_DP", unit: "s^-1", quantity: "dp_angular_inverse_timescale", dimensionSignature: "T^-1" },
      { symbol: "omega_cavity", unit: "s^-1", quantity: "declared_cavity_angular_frequency", dimensionSignature: "T^-1" },
    ],
    assumptions: [
      "The Compton frequency is associated with total rest energy and is not a body-vibration observable by identity alone.",
      "The DP frequencies are derived from branch-dependent gravitational self-energy and do not imply a DP spectral line.",
      "Equal dimensions or numerical proximity cannot supply a dynamical coupling.",
      "A bridge requires a sourced kernel with declared field input, branch or coherence dynamics, differential output, validity limits, uncertainty model, and falsifier.",
      "The current transfer kernel is absent, so beat-frequency, manifold-ringing, and quantum-foam-resonance claims remain blocked.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      sourceRef("doc", "docs/research/casimir-dp-quantum-foam-study.md", "compton-frequency-non-bridge", "Canonical frequency identities, transfer-kernel requirements, and claim-audit baseline."),
      sourceRef("repo_module", "shared/dp-collapse.ts", "computeDpCollapse", "Branch-dependent DP self-energy and timescale authority."),
      sourceRef("literature_ref", "https://doi.org/10.1007/BF02105068", "Penrose-1996", "Objective-reduction motivation; not a cavity-resonance derivation."),
      sourceRef("literature_ref", "https://doi.org/10.1088/0264-9381/28/14/145017", "Wolf-et-al-2011", "Operational context for why a Compton-frequency interpretation requires a defined phase observable and readout."),
    ],
    hintKeys: {
      subjects: ["compton frequency", "DP frequency", "collapse beat frequency", "cavity resonance", "manifold ringing"],
      symbols: ["nu_C", "nu_DP", "omega_DP", "omega_cavity", "transfer_kernel_receipt"],
      unitSignatures: ["T^-1"],
      repoPaths: ["docs/research/casimir-dp-quantum-foam-study.md", "shared/dp-collapse.ts"],
      equationFamilies: ["compton_frequency", "dp_timescale", "frequency_bridge"],
      simulationOwners: ["casimir_dp_study", "casimir", "curvature_collapse"],
    },
  }),
  studyBadge({
    id: "study.casimir_dp.experiment_design_campaign",
    title: "Boundary-Conditioned Coherence Experiment Design Campaign",
    plainMeaning:
      "Compares a Casimir calibration platform, an integrated levitated coherence platform, and a free-flight spatial-superposition benchmark under one ordered gate ledger.",
    whyItMatters:
      "It turns the proposed experiment into runnable signal, force-symmetry, decoherence, DP-proxy, and identifiability budgets without mistaking engineering readiness for physical evidence.",
    subjects: [
      "casimir_dp_study",
      "experiment_design",
      "boundary_conditioned_coherence",
      "levitated_nanoparticle",
      "nanomechanical_resonator",
      "matter_wave",
      "rate_budget",
    ],
    level: "simulation_specific",
    status: "diagnostic",
    simulationOwners: ["casimir_dp_study", "casimir", "curvature_collapse"],
    equationFamilies: ["coherence_rate_budget", "dp_collapse", "experiment_design_screen"],
    tags: ["design_only", "role_separated", "hashed_receipt", "no_physics_winner"],
    equations: [
      {
        id: "casimir_dp_accessible_rate_ratio",
        role: "residual",
        displayLatex: "\\mathcal R_{access}=\\Gamma_{DP}/\\Gamma_{env}",
        computableExpression: "R_access = Gamma_DP/Gamma_env",
        operatorKind: "scalar_expression",
        inputSymbols: ["Gamma_DP", "Gamma_env"],
        outputSymbols: ["R_access"],
      },
    ],
    units: [
      { symbol: "Gamma_DP", unit: "s^-1", quantity: "dp_proxy_rate", dimensionSignature: "T^-1" },
      { symbol: "Gamma_env", unit: "s^-1", quantity: "ordinary_decoherence_rate", dimensionSignature: "T^-1" },
      { symbol: "R_access", unit: "1", quantity: "dp_to_environment_rate_ratio", dimensionSignature: "1" },
    ],
    assumptions: [
      "The engineering screening index is not a physics-evidence score or platform selection.",
      "Ideal parallel-plate Casimir values are reference rows, not finite-geometry apparatus predictions.",
      "Gaussian DP branches are diagnostic proxies, not measured material-density receipts.",
      "The integrated levitated row uses design-assumption decoherence rates and cannot support a collapse claim.",
      "No manifold-response rate is registered or computed.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      sourceRef("doc", "docs/research/casimir-dp-experiment-design-report.md", "boundary-coherence-platform-screen-v1", "Maintained role-separated diagnostic report."),
      sourceRef("artifact", "configs/research/casimir-dp-experiment-design.v1.json", "boundary-coherence-platform-screen-v1", "Frozen candidate inputs, evidence classes, thresholds, and run order."),
      sourceRef("repo_module", "scripts/research/run-casimir-dp-experiment-design.ts", "runCasimirDpExperimentDesign", "Deterministic signal, disturbance, coherence, and DP-proxy runner."),
      sourceRef("repo_module", "shared/contracts/casimir-dp-experiment-design.v1.ts", "casimir_dp_experiment_design/1", "Validated input and report contract."),
    ],
    hintKeys: {
      subjects: ["casimir dp experiment", "coherence platform", "levitated nanoparticle", "matter wave", "superconducting casimir"],
      symbols: ["Gamma_DP", "Gamma_env", "R_access"],
      unitSignatures: ["T^-1", "1"],
      repoPaths: [
        "docs/research/casimir-dp-experiment-design-report.md",
        "configs/research/casimir-dp-experiment-design.v1.json",
        "scripts/research/run-casimir-dp-experiment-design.ts",
        "shared/contracts/casimir-dp-experiment-design.v1.ts",
      ],
      equationFamilies: ["coherence_rate_budget", "dp_collapse", "experiment_design_screen"],
      simulationOwners: ["casimir_dp_study", "casimir", "curvature_collapse"],
    },
  }),
  studyBadge({
    id: "study.casimir_dp.gated_computations_stage1",
    title: "Casimir-DP Gated Computations Stage 1",
    plainMeaning:
      "Runs a real Matsubara/reflection-coefficient calculation, evidence-bearing sidecar budgets, exact-grid rigid-sphere DP convergence, rate-only power analysis, a dynamics-signature gate, and a fail-closed manifold registration audit.",
    whyItMatters:
      "It replaces heuristic screening in the lanes where a reduced-order computation is defensible and quantifies why visibility-rate data alone are not an accessible or identifiable collapse test.",
    subjects: [
      "casimir_dp_study",
      "lifshitz_matsubara",
      "material_receipts",
      "decoherence_sidecars",
      "dp_grid_convergence",
      "statistical_power",
      "dynamics_identifiability",
      "manifold_registration",
    ],
    level: "simulation_specific",
    status: "diagnostic",
    simulationOwners: ["casimir_dp_study", "casimir", "curvature_collapse"],
    equationFamilies: [
      "lifshitz_matsubara",
      "dp_collapse",
      "grid_convergence",
      "visibility_power",
      "dynamics_signature",
    ],
    tags: ["stage_1", "reduced_order", "exact_grid", "rate_only_inaccessible", "promotion_blocked"],
    equations: [
      {
        id: "casimir_dp_stage1_lifshitz_free_energy",
        role: "noncomputable_reference",
        displayLatex:
          "\\mathcal F/A=(k_BT/2\\pi)\\sum_n{}'\\int k_\\perp dk_\\perp\\sum_p\\ln(1-r_p^{(1)}r_p^{(2)}e^{-2q_na})",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["a", "T", "epsilon_1_i_xi", "epsilon_2_i_xi", "geometry"],
        outputSymbols: ["F_free_per_area", "P_lifshitz"],
      },
      {
        id: "casimir_dp_stage1_rate_power",
        role: "noncomputable_reference",
        displayLatex:
          "N_{setting}\\approx(z_{1-\\alpha/2}+z_{power})^2[(1-V_0^2)+(1-V_1^2)]/(V_0-V_1)^2",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["alpha", "power", "V_0", "V_1", "variance_inflation"],
        outputSymbols: ["N_setting"],
      },
      {
        id: "casimir_dp_stage1_manifold_registration_gate",
        role: "gate",
        displayLatex:
          "Register(\\Delta\\langle T_{\\mu\\nu}\\rangle,N_{\\mu\\nu\\rho\\sigma},G_{ret},\\mathcal L_{coh})=BLOCKED",
        computableExpression: null,
        operatorKind: "gate_status",
        inputSymbols: ["renormalization", "noise_kernel", "causal_response", "coherence_dynamics"],
        outputSymbols: ["manifold_registration_status"],
      },
    ],
    units: [
      { symbol: "F_free_per_area", unit: "J m^-2", quantity: "lifshitz_free_energy_per_area", dimensionSignature: "M T^-2" },
      { symbol: "P_lifshitz", unit: "Pa", quantity: "lifshitz_pressure", dimensionSignature: "M L^-1 T^-2" },
      { symbol: "N_setting", unit: "1", quantity: "shots_per_boundary_setting", dimensionSignature: "1" },
    ],
    assumptions: [
      "The Lifshitz solver is equilibrium, local, isotropic, nonmagnetic, and planar; PFA remains reference-only.",
      "The ideal validation and coarse DP convergence gates are numerical checks, not measured-material or branch-provenance gates.",
      "Current switching and decoherence sidecars are design assumptions with no raw measurement hashes.",
      "The visibility power calculation uses independent binomial samples and an exponential rate-only alternative.",
      "No collapse secondary-observable signature or manifold-response dynamics are registered.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      sourceRef("doc", "docs/research/casimir-dp-next-computations-report.md", "casimir-dp-gated-computations-stage1-v1", "Maintained Stage-1 gate report."),
      sourceRef("artifact", "configs/research/casimir-dp-next-computations.v1.json", "casimir-dp-gated-computations-stage1-v1", "Frozen numerical, sidecar, power, dynamics, and manifold inputs."),
      sourceRef("repo_module", "shared/casimir-lifshitz.ts", "computeLifshitzEquilibrium", "Reduced-order Matsubara/reflection-coefficient solver."),
      sourceRef("repo_module", "shared/casimir-dp-inference.ts", "estimateVisibilityRatePower", "Rate-only power and dynamics-signature diagnostics."),
      sourceRef("repo_module", "scripts/research/run-casimir-dp-next-computations.ts", "runCasimirDpNextComputations", "Ordered campaign runner and hashed receipt writer."),
      sourceRef("literature_ref", "https://doi.org/10.1103/RevModPhys.81.1827", "Klimchitskaya-et-al-2009", "Planar finite-temperature real-material Lifshitz formalism."),
      sourceRef("literature_ref", "https://doi.org/10.1103/PhysRevLett.134.061501", "Kryhin-Sudhir-2025", "Phase/correlation observables as dynamics discriminators."),
    ],
    hintKeys: {
      subjects: ["lifshitz solver", "dp convergence", "collapse power", "dynamics discriminator", "manifold registration"],
      symbols: ["F_free_per_area", "P_lifshitz", "N_setting", "manifold_registration_status"],
      unitSignatures: ["M T^-2", "M L^-1 T^-2", "1"],
      repoPaths: [
        "docs/research/casimir-dp-next-computations-report.md",
        "configs/research/casimir-dp-next-computations.v1.json",
        "shared/casimir-lifshitz.ts",
        "shared/casimir-dp-inference.ts",
        "scripts/research/run-casimir-dp-next-computations.ts",
      ],
      equationFamilies: ["lifshitz_matsubara", "dp_collapse", "grid_convergence", "visibility_power", "dynamics_signature"],
      simulationOwners: ["casimir_dp_study", "casimir", "curvature_collapse"],
    },
  }),
  studyBadge({
    id: "study.casimir_dp.data_readiness_stage1",
    title: "Casimir-DP Data Readiness Stage 1",
    plainMeaning:
      "Validates the real-to-imaginary optical-response transform, artifact hashes, calibration and covariance gates, source-data access ledger, and a blinded secondary-observable power protocol without promoting synthetic fixtures to measurements.",
    whyItMatters:
      "It makes the next experimental acquisition reproducible while preserving the distinction between a runnable data path, authentic measured evidence, contamination discrimination, and objective-collapse identification.",
    subjects: [
      "casimir_dp_study",
      "kramers_kronig",
      "optical_response_receipts",
      "sidecar_integrity",
      "covariance",
      "blinded_protocol",
      "correlation_power",
      "data_access_ledger",
    ],
    level: "simulation_specific",
    status: "diagnostic",
    simulationOwners: ["casimir_dp_study", "casimir", "curvature_collapse"],
    equationFamilies: ["kramers_kronig", "sidecar_covariance", "fisher_correlation_power"],
    tags: ["stage_1", "data_readiness", "synthetic_validation", "measured_evidence_open", "promotion_blocked"],
    equations: [
      {
        id: "casimir_dp_data_readiness_kramers_kronig",
        role: "noncomputable_reference",
        displayLatex:
          "\\epsilon(i\\xi)=1+(2/\\pi)\\int_0^\\infty \\omega\\epsilon''(\\omega)/(\\omega^2+\\xi^2)\\,d\\omega",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["omega", "epsilon_imag", "optical_covariance", "tail_models"],
        outputSymbols: ["epsilon_i_xi"],
      },
      {
        id: "casimir_dp_data_readiness_correlation_power",
        role: "noncomputable_reference",
        displayLatex:
          "N_{pair}=\\lceil3+[(z_{1-\\alpha/(2m)}+z_{power})/(atanh\\rho_1-atanh\\rho_0)]^2\\rceil",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["alpha", "multiplicity", "power", "rho_0", "rho_1"],
        outputSymbols: ["N_pair"],
      },
      {
        id: "casimir_dp_data_readiness_measured_gate",
        role: "gate",
        displayLatex:
          "G_{measured}=G_{hash}\\land G_{cal}\\land G_{cov}\\land G_{coverage}\\land G_{blinding}=NOT\\ READY",
        computableExpression: null,
        operatorKind: "gate_status",
        inputSymbols: ["raw_hashes", "calibrations", "covariance", "spectral_coverage", "blind_state"],
        outputSymbols: ["measured_evidence_status"],
      },
    ],
    units: [
      { symbol: "omega", unit: "rad s^-1", quantity: "real_axis_angular_frequency", dimensionSignature: "T^-1" },
      { symbol: "epsilon_i_xi", unit: "1", quantity: "imaginary_axis_relative_permittivity", dimensionSignature: "1" },
      { symbol: "N_pair", unit: "1", quantity: "paired_acquisition_windows", dimensionSignature: "1" },
    ],
    assumptions: [
      "The Kramers-Kronig quadrature uses the supplied passive loss table; registered tails are audited but not silently extrapolated.",
      "The current Lorentz, switching, and decoherence artifacts are synthetic validation fixtures.",
      "Diagonal optical uncertainty propagation assumes independent loss samples unless a fuller covariance model is supplied.",
      "Fisher-z power assumes independent approximately bivariate-normal paired acquisition windows.",
      "Switch cross-correlation can diagnose contamination but cannot identify objective collapse by itself.",
      "No source-backed DP/Penrose secondary-observable signature or manifold-response dynamics is registered.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      sourceRef("doc", "docs/research/casimir-dp-data-readiness-report.md", "casimir-dp-data-readiness-stage1-v1", "Maintained data-readiness report."),
      sourceRef("artifact", "configs/research/casimir-dp-data-readiness.v1.json", "casimir-dp-data-readiness-stage1-v1", "Frozen artifacts, source ledger, blind protocol, and power cases."),
      sourceRef("repo_module", "shared/casimir-optical-response.ts", "convertLossTableToImaginaryAxis", "Kramers-Kronig transform and measured-material gates."),
      sourceRef("repo_module", "shared/casimir-dp-data-readiness.ts", "validateAcquisitionSidecar", "Hash, calibration, covariance, and correlation-power diagnostics."),
      sourceRef("repo_module", "scripts/research/run-casimir-dp-data-readiness.ts", "runCasimirDpDataReadiness", "Ordered runner and hashed report receipt."),
      sourceRef("artifact", "https://doi.org/10.5281/zenodo.17502163", "Pedalino-et-al-data", "Open external matter-wave data/code benchmark; not this apparatus's measurement."),
      sourceRef("literature_ref", "https://doi.org/10.1038/s41567-020-1008-4", "Donadi-et-al-2021", "DP exclusion context and source-data route."),
    ],
    hintKeys: {
      subjects: ["casimir dp data readiness", "kramers kronig", "sidecar covariance", "blinded coherence", "correlation power"],
      symbols: ["epsilon_i_xi", "N_pair", "measured_evidence_status"],
      unitSignatures: ["T^-1", "1"],
      repoPaths: [
        "docs/research/casimir-dp-data-readiness-report.md",
        "configs/research/casimir-dp-data-readiness.v1.json",
        "shared/casimir-optical-response.ts",
        "shared/casimir-dp-data-readiness.ts",
        "scripts/research/run-casimir-dp-data-readiness.ts",
      ],
      equationFamilies: ["kramers_kronig", "sidecar_covariance", "fisher_correlation_power"],
      simulationOwners: ["casimir_dp_study", "casimir", "curvature_collapse"],
    },
  }),
  studyBadge({
    id: "study.casimir_dp.proposal_closure",
    title: "Casimir-DP Proposal Closure",
    plainMeaning:
      "Freezes the transverse-branch sample-and-hold apparatus, systematic-transfer matrix, commissioning dependency ladder, blinded power plan, and decision language needed to enter experimental commissioning without calling the apparatus or mechanism validated.",
    whyItMatters:
      "It converts open validation labels into explicit artifact-producing acceptance tests and corrects the earlier dependence on implausibly exact cancellation of normal surface forces.",
    subjects: [
      "casimir_dp_study",
      "experiment_proposal",
      "transverse_superposition",
      "sample_and_hold_boundary",
      "casimir_polder",
      "systematics_matrix",
      "commissioning",
      "blinding",
      "decision_table",
    ],
    level: "simulation_specific",
    status: "diagnostic",
    simulationOwners: ["casimir_dp_study", "casimir", "curvature_collapse"],
    equationFamilies: ["phase_force_bound", "casimir_polder_reference", "proposal_gate_ledger"],
    tags: ["proposal_complete", "commissioning_conditional", "architecture_frozen", "hardware_not_validated", "promotion_blocked"],
    equations: [
      {
        id: "casimir_dp_proposal_phase_force_bound",
        role: "noncomputable_reference",
        displayLatex: "\\delta F_{max}=\\hbar\\delta\\phi_{max}/(\\Delta x\\,t)",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["delta_phi_max", "branch_separation", "observation_time"],
        outputSymbols: ["delta_F_max"],
      },
      {
        id: "casimir_dp_proposal_cp_reference",
        role: "noncomputable_reference",
        displayLatex: "U_{CP}=-C_4/z^4,\\quad F_{CP}=-4C_4/z^5",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["C_4", "surface_distance"],
        outputSymbols: ["U_CP", "F_CP"],
      },
      {
        id: "casimir_dp_proposal_gate_ledger",
        role: "gate",
        displayLatex: "G_{proposal}=PASS,\\quad G_{commission}=CONDITIONAL,\\quad G_{measured}=NOT\\ READY",
        computableExpression: null,
        operatorKind: "gate_status",
        inputSymbols: ["architecture", "systematics", "commissioning", "blinding", "decision_table"],
        outputSymbols: ["proposal_status", "commissioning_status", "measured_status"],
      },
    ],
    units: [
      { symbol: "delta_F_max", unit: "N", quantity: "maximum_differential_force_noise", dimensionSignature: "M L T^-2" },
      { symbol: "C_4", unit: "J m^4", quantity: "retarded_casimir_polder_coefficient", dimensionSignature: "M L^6 T^-2" },
      { symbol: "surface_distance", unit: "m", quantity: "particle_surface_distance", dimensionSignature: "L" },
      { symbol: "F_CP", unit: "N", quantity: "casimir_polder_force", dimensionSignature: "M L T^-2" },
    ],
    assumptions: [
      "The silica/silicon C4 value is a literature reference and not the gate-dependent 2D boundary contrast.",
      "The superposition separation is transverse to the surface normal so the normal force is common-mode only to first order.",
      "Boundary switching occurs between shots and is followed by a registered settling interval.",
      "Every systematic threshold is a commissioning target until a measured transfer-function receipt exists.",
      "Proposal completeness and software verification do not validate integrated hardware, collapse, or manifold dynamics.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      sourceRef("doc", "docs/research/casimir-dp-experiment-proposal.md", "casimir-dp-transverse-branch-pilot-v1", "Submission-ready bounded experiment proposal."),
      sourceRef("doc", "docs/research/casimir-dp-proposal-closure-report.md", "casimir-dp-transverse-branch-pilot-v1", "Runnable proposal-closure report."),
      sourceRef("artifact", "configs/research/casimir-dp-proposal-closure.v1.json", "casimir-dp-transverse-branch-pilot-v1", "Frozen apparatus, systematics, commissioning, model, and decision contracts."),
      sourceRef("repo_module", "shared/casimir-dp-proposal-readiness.ts", "evaluateCasimirDpProposalReadiness", "Proposal readiness, reference-scale, and gate evaluation."),
      sourceRef("repo_module", "scripts/research/run-casimir-dp-proposal-closure.ts", "runCasimirDpProposalClosure", "Ordered proposal runner and hashed receipt."),
      sourceRef("literature_ref", "https://doi.org/10.1038/s41565-024-01677-3", "Melo-et-al-2024", "On-chip high-vacuum levitation subsystem evidence."),
      sourceRef("literature_ref", "https://doi.org/10.1103/PhysRevA.98.053831", "Winstone-et-al-2018", "Near-surface electrostatic and Casimir-Polder reference evidence."),
      sourceRef("literature_ref", "https://doi.org/10.1103/y1q9-pnlc", "Seta-et-al-2026", "State-expansion displacement-noise evidence."),
    ],
    hintKeys: {
      subjects: ["casimir dp proposal", "transverse branch", "sample hold boundary", "commissioning", "phase force bound"],
      symbols: ["delta_F_max", "C_4", "F_CP", "proposal_status"],
      unitSignatures: ["M L T^-2", "M L^6 T^-2", "L"],
      repoPaths: [
        "docs/research/casimir-dp-experiment-proposal.md",
        "docs/research/casimir-dp-proposal-closure-report.md",
        "configs/research/casimir-dp-proposal-closure.v1.json",
        "shared/casimir-dp-proposal-readiness.ts",
        "scripts/research/run-casimir-dp-proposal-closure.ts",
      ],
      equationFamilies: ["phase_force_bound", "casimir_polder_reference", "proposal_gate_ledger"],
      simulationOwners: ["casimir_dp_study", "casimir", "curvature_collapse"],
    },
  }),
  studyBadge({
    id: "study.casimir_dp.claim_boundary",
    title: "Casimir / DP Quantum-Foam Study Claim Boundary",
    plainMeaning:
      "Keeps the study diagnostic until the material, branch-provenance, bounds, observable-bridge, sensitivity, and reproduction gates close.",
    whyItMatters:
      "It prevents a runnable smoke receipt or scalar agreement from being described as quantum-foam, objective-collapse, NHM2, or viability validation.",
    subjects: ["casimir_dp_study", "claim_boundary", "quantum_foam", "objective_collapse"],
    level: "claim_boundary",
    status: "blocked",
    simulationOwners: ["casimir_dp_study"],
    equationFamilies: ["study_claim_boundary"],
    tags: ["diagnostic_only", "promotion_blocked", "non_claims"],
    equations: [
      {
        id: "casimir_dp_claim_boundary",
        role: "noncomputable_reference",
        displayLatex:
          "claim_{CDP-QF-1}=diagnostic\\ only\\;\\ promotion=blocked",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["study_gate_ledger"],
        outputSymbols: ["claim_boundary"],
      },
    ],
    units: [],
    assumptions: [
      "Casimir calculations do not prove a unique quantum-vacuum or quantum-foam ontology.",
      "DP calculations do not prove observed objective collapse.",
      "Compton and DP frequency identities do not supply a cavity resonance or collapse beat without a registered transfer kernel.",
      "Negative renormalized energy density does not by itself identify negative curvature.",
      "Visibility loss does not establish objective collapse without a dynamics-level discriminator.",
      "The study does not validate NHM2, propulsion, gravity control, negative-energy engineering, or physical viability.",
      "Promotion remains disallowed in this badge graph version.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      sourceRef("doc", "docs/research/casimir-dp-quantum-foam-study.md", "claim-boundaries", "Canonical study non-claims."),
      sourceRef("literature_ref", "https://doi.org/10.1038/s41567-020-1008-4", "Donadi-et-al-2021", "Experimental exclusion context for the natural parameter-free DP version."),
      sourceRef("literature_ref", "https://doi.org/10.1103/2jm3-4976", "XENONnT-2026", "Current independent DP parameter constraints."),
    ],
    hintKeys: {
      subjects: ["casimir dp claim boundary", "quantum foam non claim", "objective collapse bounds"],
      symbols: ["claim_CDP_QF_1", "claim_boundary"],
      unitSignatures: [],
      repoPaths: ["docs/research/casimir-dp-quantum-foam-study.md"],
      equationFamilies: ["study_claim_boundary"],
      simulationOwners: ["casimir_dp_study"],
    },
  }),
];

export const CASIMIR_DP_STUDY_THEORY_EDGES: TheoryBadgeEdgeV1[] = [
  {
    id: "casimir_dp_protocol_requires_casimir_baseline",
    from: "casimir.cavity.parallel_plate_pressure",
    to: "study.casimir_dp.protocol",
    relation: "requires",
    label: "The study protocol starts from the established Casimir reference lane.",
    claimBoundaryNote: "The ideal scalar is a baseline, not a complete apparatus prediction.",
  },
  {
    id: "casimir_dp_protocol_requires_material_receipts",
    from: "casimir.material_receipts",
    to: "study.casimir_dp.protocol",
    relation: "requires",
    label: "Measurement comparison requires the Casimir material and metrology receipt chain.",
    claimBoundaryNote: "Missing receipts keep residual interpretation not ready.",
  },
  {
    id: "casimir_dp_protocol_requires_dp_branches",
    from: "collapse.objective.mass_density_branch_difference",
    to: "study.casimir_dp.protocol",
    relation: "requires",
    label: "The DP lane requires explicit mass-density branch evidence.",
    claimBoundaryNote: "Casimir force cannot replace branch distributions.",
  },
  {
    id: "casimir_dp_protocol_requires_dp_bounds",
    from: "collapse.objective.experimental_bounds",
    to: "study.casimir_dp.protocol",
    relation: "requires",
    label: "The DP diagnostic must be interpreted against independent experimental bounds.",
    claimBoundaryNote: "Bounds constrain parameter space and do not validate collapse.",
  },
  {
    id: "casimir_dp_manifold_response_requires_observable_gate",
    from: "study.casimir_dp.observable_separation_gate",
    to: "study.casimir_dp.manifold_response_hypothesis",
    relation: "requires",
    label: "The manifold-response hypothesis requires distinct boundary-stress, coherence, and DP observables.",
    claimBoundaryNote: "Shared vacuum or gravity vocabulary cannot supply the transformation.",
  },
  {
    id: "casimir_dp_manifold_response_requires_decoherence_gate",
    from: "study.casimir_dp.decoherence_collapse_gate",
    to: "study.casimir_dp.manifold_response_hypothesis",
    relation: "requires",
    label: "A candidate manifold term must survive the ordinary decoherence budget and dynamics discriminator.",
    claimBoundaryNote: "A coherence residual is not automatically an objective-collapse rate.",
  },
  {
    id: "casimir_dp_manifold_response_requires_frequency_bridge_gate",
    from: "study.casimir_dp.frequency_bridge_gate",
    to: "study.casimir_dp.manifold_response_hypothesis",
    relation: "requires",
    label: "A frequency-based manifold-response model requires a sourced transfer kernel from cavity input to branch or coherence dynamics.",
    claimBoundaryNote: "Frequency identities and matching units cannot supply the missing dynamics.",
  },
  {
    id: "casimir_dp_manifold_response_specializes_quantum_foam_slot",
    from: "study.casimir_dp.manifold_response_hypothesis",
    to: "study.casimir_dp.quantum_foam_hypothesis",
    relation: "specializes",
    label: "The direct-manipulation manifold hypothesis provides a narrower test target inside the quantum-foam model family.",
    claimBoundaryNote: "Both model slots remain noncomputable and Stage 0 until dynamics are registered.",
  },
  {
    id: "casimir_dp_quantum_foam_requires_observable_gate",
    from: "study.casimir_dp.observable_separation_gate",
    to: "study.casimir_dp.quantum_foam_hypothesis",
    relation: "requires",
    label: "Any quantum-foam residual model must identify its Casimir observable and any proposed DP bridge.",
    claimBoundaryNote: "The missing bridge currently blocks cross-lane inference.",
  },
  {
    id: "casimir_dp_protocol_documents_observable_gate",
    from: "study.casimir_dp.protocol",
    to: "study.casimir_dp.observable_separation_gate",
    relation: "diagnostic_checks",
    label: "The ordered protocol evaluates observable identity before synthesis.",
    claimBoundaryNote: "Process completion cannot override a blocked identity gate.",
  },
  {
    id: "casimir_dp_protocol_runs_experiment_design_campaign",
    from: "study.casimir_dp.protocol",
    to: "study.casimir_dp.experiment_design_campaign",
    relation: "diagnostic_checks",
    label: "The ordered study protocol runs the role-separated experiment-design screen before apparatus selection.",
    claimBoundaryNote: "The screen compares open budgets and cannot promote a candidate.",
  },
  {
    id: "casimir_dp_experiment_design_requires_decoherence_gate",
    from: "study.casimir_dp.decoherence_collapse_gate",
    to: "study.casimir_dp.experiment_design_campaign",
    relation: "requires",
    label: "The design campaign inherits the ordinary-decoherence and collapse-identifiability gate.",
    claimBoundaryNote: "A DP-to-environment rate ratio is a design diagnostic, not observed collapse.",
  },
  {
    id: "casimir_dp_experiment_design_runs_stage1_gated_computations",
    from: "study.casimir_dp.experiment_design_campaign",
    to: "study.casimir_dp.gated_computations_stage1",
    relation: "diagnostic_checks",
    label: "The role-separated design campaign feeds the Stage-1 numerical and inference gates.",
    claimBoundaryNote: "Numerical progress cannot replace material, sidecar, or branch evidence.",
  },
  {
    id: "casimir_dp_stage1_requires_material_receipts",
    from: "casimir.material_receipts",
    to: "study.casimir_dp.gated_computations_stage1",
    relation: "requires",
    label: "Publication comparison requires measured material and metrology receipts beyond literature Drude parameters.",
    claimBoundaryNote: "The current material gate remains not ready.",
  },
  {
    id: "casimir_dp_stage1_blocks_claims",
    from: "study.casimir_dp.gated_computations_stage1",
    to: "study.casimir_dp.claim_boundary",
    relation: "blocks",
    label: "Open finite-geometry, sidecar, branch-provenance, identifiability, and manifold gates block promotion.",
    claimBoundaryNote: "Stage-1 numerical passes do not establish objective collapse or a manifold mechanism.",
  },
  {
    id: "casimir_dp_stage1_runs_data_readiness",
    from: "study.casimir_dp.gated_computations_stage1",
    to: "study.casimir_dp.data_readiness_stage1",
    relation: "diagnostic_checks",
    label: "Stage-1 numerical gaps feed the authenticated material, sidecar, source-ledger, and blinded discriminator campaign.",
    claimBoundaryNote: "Synthetic validation makes the acquisition path runnable but does not supply measurements.",
  },
  {
    id: "casimir_dp_data_readiness_requires_material_receipts",
    from: "casimir.material_receipts",
    to: "study.casimir_dp.data_readiness_stage1",
    relation: "requires",
    label: "Measured optical continuation requires apparatus-specific material and calibration receipts.",
    claimBoundaryNote: "External or synthetic optical response cannot close the measured-material gate.",
  },
  {
    id: "casimir_dp_data_readiness_blocks_claims",
    from: "study.casimir_dp.data_readiness_stage1",
    to: "study.casimir_dp.claim_boundary",
    relation: "blocks",
    label: "Open measured-evidence, collapse-signature, and manifold-dynamics gates block promotion.",
    claimBoundaryNote: "A passing pipeline receipt is not evidence for objective collapse or manifold manipulation.",
  },
  {
    id: "casimir_dp_data_readiness_runs_proposal_closure",
    from: "study.casimir_dp.data_readiness_stage1",
    to: "study.casimir_dp.proposal_closure",
    relation: "diagnostic_checks",
    label: "The authenticated data path feeds the frozen apparatus, systematics, commissioning, and decision contracts.",
    claimBoundaryNote: "Protocol closure does not supply the missing measured artifacts.",
  },
  {
    id: "casimir_dp_proposal_requires_decoherence_gate",
    from: "study.casimir_dp.decoherence_collapse_gate",
    to: "study.casimir_dp.proposal_closure",
    relation: "requires",
    label: "The proposal inherits the ordinary-decoherence and collapse-identification separation gate.",
    claimBoundaryNote: "An unexplained coherence residual remains non-identifying.",
  },
  {
    id: "casimir_dp_proposal_closure_blocks_claims",
    from: "study.casimir_dp.proposal_closure",
    to: "study.casimir_dp.claim_boundary",
    relation: "blocks",
    label: "Conditional commissioning and open measured/model gates block physical promotion.",
    claimBoundaryNote: "Proposal readiness is not experimental or mechanism validation.",
  },
  {
    id: "casimir_dp_experiment_design_blocks_claims",
    from: "study.casimir_dp.experiment_design_campaign",
    to: "study.casimir_dp.claim_boundary",
    relation: "blocks",
    label: "Open material, geometry, decoherence, DP-branch, manifold, and identifiability gates block promotion.",
    claimBoundaryNote: "No engineering rank is physical evidence.",
  },
  {
    id: "casimir_dp_decoherence_gate_blocks_claims",
    from: "study.casimir_dp.decoherence_collapse_gate",
    to: "study.casimir_dp.claim_boundary",
    relation: "blocks",
    label: "Unclosed ordinary decoherence alternatives block objective-collapse interpretation.",
    claimBoundaryNote: "Visibility loss or a cavity correlation alone cannot establish collapse.",
  },
  {
    id: "casimir_dp_manifold_response_blocks_claims",
    from: "study.casimir_dp.manifold_response_hypothesis",
    to: "study.casimir_dp.claim_boundary",
    relation: "blocks",
    label: "The unregistered tensor-to-metric-to-coherence functional blocks manifold-mechanism claims.",
    claimBoundaryNote: "The current math maturity is Stage 0 exploratory.",
  },
  {
    id: "casimir_dp_observable_gate_blocks_claims",
    from: "study.casimir_dp.observable_separation_gate",
    to: "study.casimir_dp.claim_boundary",
    relation: "blocks",
    label: "The missing Casimir-to-DP bridge blocks mechanism and promotion claims.",
    claimBoundaryNote: "No quantum-foam or DP mechanism claim is allowed while blocked.",
  },
  {
    id: "casimir_dp_frequency_bridge_gate_blocks_claims",
    from: "study.casimir_dp.frequency_bridge_gate",
    to: "study.casimir_dp.claim_boundary",
    relation: "blocks",
    label: "The missing Compton/DP-to-cavity transfer kernel blocks beat-frequency and resonance claims.",
    claimBoundaryNote: "The gate can open only with sourced dynamics, an operational observable, uncertainties, and a falsifier.",
  },
  {
    id: "casimir_dp_quantum_foam_blocks_claims",
    from: "study.casimir_dp.quantum_foam_hypothesis",
    to: "study.casimir_dp.claim_boundary",
    relation: "blocks",
    label: "An unregistered quantum-foam response remains a bounded hypothesis slot.",
    claimBoundaryNote: "Noncomputable hypothesis language is not evidence.",
  },
  {
    id: "casimir_dp_protocol_documents_claim_boundary",
    from: "study.casimir_dp.protocol",
    to: "study.casimir_dp.claim_boundary",
    relation: "documents",
    label: "Every run receipt carries the study claim boundary.",
    claimBoundaryNote: "The maximum claim tier remains diagnostic.",
  },
];

export function buildCasimirDpStudyTheoryBadgesV1(): {
  badges: TheoryBadgeV1[];
  edges: TheoryBadgeEdgeV1[];
} {
  return {
    badges: CASIMIR_DP_STUDY_THEORY_BADGES.map((badge) => ({ ...badge })),
    edges: CASIMIR_DP_STUDY_THEORY_EDGES.map((edge) => ({ ...edge })),
  };
}
