import {
  type TheoryBadgeClaimBoundaryV1,
  type TheoryBadgeEdgeV1,
  type TheoryBadgeV1,
} from "../contracts/theory-badge-graph.v1";

const CASIMIR_BOUNDARY: TheoryBadgeClaimBoundaryV1 = {
  diagnosticOnly: true,
  doesValidateNHM2: false,
  validationClaimAllowed: false,
  physicalMechanismClaimAllowed: false,
  promotionAllowed: false,
};

const repoRef = (path: string, id?: string, note?: string): TheoryBadgeV1["sourceRefs"][number] => ({
  kind: "repo_module",
  path,
  id: id ?? null,
  note: note ?? null,
});

const docRef = (path: string, id?: string, note?: string): TheoryBadgeV1["sourceRefs"][number] => ({
  kind: "doc",
  path,
  id: id ?? null,
  note: note ?? null,
});

const literatureRef = (path: string, id: string, note?: string): TheoryBadgeV1["sourceRefs"][number] => ({
  kind: "literature_ref",
  path,
  id,
  note: note ?? null,
});

const payload = (args: {
  id: string;
  expression: string;
  displayLatex: string;
  targetVariable: string;
}): TheoryBadgeV1["calculatorPayloads"][number] => ({
  id: args.id,
  expression: args.expression,
  displayLatex: args.displayLatex,
  preferredAction: "solve_with_steps",
  targetVariable: args.targetVariable,
  setupContext: null,
});

const casimirBadge = (badge: Omit<TheoryBadgeV1, "claimBoundary">): TheoryBadgeV1 => ({
  ...badge,
  claimBoundary: CASIMIR_BOUNDARY,
});

export const CASIMIR_CAVITY_THEORY_BADGES: TheoryBadgeV1[] = [
  casimirBadge({
    id: "casimir.cavity.parallel_plate_energy_density",
    title: "Casimir Parallel-Plate Energy Density",
    plainMeaning: "Computes the idealized static Casimir energy per plate area from gap distance.",
    whyItMatters: "It is the scalar root for the repo's static Casimir tile budget.",
    subjects: ["casimir", "cavity", "parallel_plate", "vacuum_energy", "static"],
    level: "law",
    status: "canonical_reference",
    simulationOwners: ["casimir", "NHM2"],
    equationFamilies: ["casimir_energy", "parallel_plate_static"],
    tags: ["gap", "static", "calculator_loadable"],
    equations: [
      {
        id: "casimir_energy_per_area",
        role: "calculator_demo",
        displayLatex: "E_A=-\\frac{\\pi^2\\hbar c}{720a^3}",
        computableExpression: "E_area = -(pi^2*hbar_c)/(720*a^3)",
        operatorKind: "scalar_expression",
        inputSymbols: ["pi", "hbar_c", "a"],
        outputSymbols: ["E_area"],
      },
    ],
    units: [
      { symbol: "E_area", unit: "J/m^2", quantity: "energy_per_area", dimensionSignature: "M T^-2" },
      { symbol: "a", unit: "m", quantity: "gap", dimensionSignature: "L" },
      { symbol: "hbar_c", unit: "J*m", quantity: "reduced_planck_speed_product", dimensionSignature: "M L^3 T^-2" },
    ],
    assumptions: [
      "Idealized perfect-conductor, zero-temperature parallel-plate scalar row.",
      "Material and finite-temperature corrections require a separate runtime/receipt context.",
      "Material receipts are required before this scalar row can be used as material source evidence.",
    ],
    calculatorPayloads: [
      payload({
        id: "casimir_energy_per_area_payload",
        expression: "E_area = -(pi^2*hbar_c)/(720*a^3)",
        displayLatex: "E_A=-\\frac{\\pi^2\\hbar c}{720a^3}",
        targetVariable: "E_area",
      }),
    ],
    sourceRefs: [
      repoRef("modules/core/physics-constants.ts", "PHYSICS_CONSTANTS.HBAR_C", "Constants used by the static Casimir module."),
      repoRef("modules/sim_core/static-casimir.ts", "calculateCasimirEnergy", "Static Casimir calculation module."),
      repoRef("shared/contracts/casimir-material-receipt.v1.ts", "CasimirMaterialReceiptV1", "Receipt contract that gates material-source interpretation."),
      docRef("docs/casimir-tile-mechanism.md", "per-tile-casimir-energy", "Mechanism note mapping the formula to pipeline fields."),
    ],
    hintKeys: {
      subjects: ["casimir", "cavity", "parallel_plate", "vacuum_energy"],
      symbols: ["E_area", "hbar_c", "a", "gap"],
      unitSignatures: ["M T^-2", "M L^3 T^-2", "L"],
      repoPaths: [
        "modules/sim_core/static-casimir.ts",
        "modules/core/physics-constants.ts",
        "shared/contracts/casimir-material-receipt.v1.ts",
        "docs/casimir-tile-mechanism.md",
      ],
      equationFamilies: ["casimir_energy", "parallel_plate_static"],
      simulationOwners: ["casimir", "NHM2"],
    },
  }),
  casimirBadge({
    id: "casimir.cavity.parallel_plate_pressure",
    title: "Casimir Parallel-Plate Pressure",
    plainMeaning: "Computes the idealized pressure magnitude/sign proxy for a plate gap.",
    whyItMatters: "It gives force/load prompts a scalar pressure row linked to the same gap dependence.",
    subjects: ["casimir", "cavity", "pressure", "parallel_plate"],
    level: "derived_relation",
    status: "canonical_reference",
    simulationOwners: ["casimir"],
    equationFamilies: ["casimir_pressure", "parallel_plate_static"],
    tags: ["pressure", "gap", "calculator_loadable"],
    equations: [
      {
        id: "casimir_pressure",
        role: "calculator_demo",
        displayLatex: "P=-\\frac{\\pi^2\\hbar c}{240a^4}",
        computableExpression: "P_casimir = -(pi^2*hbar_c)/(240*a^4)",
        operatorKind: "scalar_expression",
        inputSymbols: ["pi", "hbar_c", "a"],
        outputSymbols: ["P_casimir"],
      },
    ],
    units: [
      { symbol: "P_casimir", unit: "Pa", quantity: "pressure", dimensionSignature: "M L^-1 T^-2" },
      { symbol: "a", unit: "m", quantity: "gap", dimensionSignature: "L" },
    ],
    assumptions: ["Idealized scalar pressure row.", "Does not include material, roughness, or finite-temperature corrections."],
    calculatorPayloads: [
      payload({
        id: "casimir_pressure_payload",
        expression: "P_casimir = -(pi^2*hbar_c)/(240*a^4)",
        displayLatex: "P=-\\frac{\\pi^2\\hbar c}{240a^4}",
        targetVariable: "P_casimir",
      }),
    ],
    sourceRefs: [
      repoRef("modules/sim_core/static-casimir.ts", "calculateCasimirEnergy", "Force magnitude is derived from static energy and gap."),
      docRef("docs/knowledge/physics/casimir-force-energy.md", "casimir-force-energy", "Knowledge-tree source for force/energy context."),
    ],
    hintKeys: {
      subjects: ["casimir", "pressure", "force", "gap"],
      symbols: ["P_casimir", "hbar_c", "a", "gap"],
      unitSignatures: ["M L^-1 T^-2", "L"],
      repoPaths: ["modules/sim_core/static-casimir.ts", "docs/knowledge/physics/casimir-force-energy.md"],
      equationFamilies: ["casimir_pressure", "parallel_plate_static"],
      simulationOwners: ["casimir"],
    },
  }),
  casimirBadge({
    id: "casimir.cavity.per_tile_energy",
    title: "Casimir Per-Tile Energy",
    plainMeaning: "Converts energy per area into a tile energy using the tile footprint.",
    whyItMatters: "It is the first project-specific row after the universal parallel-plate formula.",
    subjects: ["casimir", "tile", "energy", "cavity"],
    level: "simulation_specific",
    status: "project_derived",
    simulationOwners: ["casimir", "NHM2"],
    equationFamilies: ["casimir_tile_budget"],
    tags: ["tile", "area", "calculator_loadable"],
    equations: [
      {
        id: "per_tile_energy",
        role: "calculator_demo",
        displayLatex: "E_{tile}=E_A A_{tile}",
        computableExpression: "E_tile = E_area*A_tile",
        operatorKind: "scalar_expression",
        inputSymbols: ["E_area", "A_tile"],
        outputSymbols: ["E_tile"],
      },
    ],
    units: [
      { symbol: "E_tile", unit: "J", quantity: "energy", dimensionSignature: "M L^2 T^-2" },
      { symbol: "A_tile", unit: "m^2", quantity: "area", dimensionSignature: "L^2" },
    ],
    assumptions: ["Tile footprint is supplied by the object binding or pipeline receipt."],
    calculatorPayloads: [
      payload({
        id: "casimir_per_tile_energy_payload",
        expression: "E_tile = E_area*A_tile",
        displayLatex: "E_{tile}=E_A A_{tile}",
        targetVariable: "E_tile",
      }),
    ],
    sourceRefs: [
      repoRef("server/energy-pipeline.ts", "calculateStaticCasimir", "Pipeline owner for per-tile and static budget values."),
      docRef("docs/casimir-tile-mechanism.md", "numbers-step-by-step", "Mechanism note with tile footprint defaults."),
    ],
    hintKeys: {
      subjects: ["casimir", "tile", "energy"],
      symbols: ["E_tile", "E_area", "A_tile"],
      unitSignatures: ["M L^2 T^-2", "L^2"],
      repoPaths: ["server/energy-pipeline.ts", "docs/casimir-tile-mechanism.md"],
      equationFamilies: ["casimir_tile_budget"],
      simulationOwners: ["casimir", "NHM2"],
    },
  }),
  casimirBadge({
    id: "casimir.cavity.static_tile_budget",
    title: "Casimir Static Tile Budget",
    plainMeaning: "Aggregates per-tile energy over a tile census.",
    whyItMatters: "It connects a single cavity row to the array-level static energy budget.",
    subjects: ["casimir", "tile", "budget", "array"],
    level: "simulation_specific",
    status: "project_derived",
    simulationOwners: ["casimir", "NHM2"],
    equationFamilies: ["casimir_tile_budget"],
    tags: ["static_budget", "calculator_loadable"],
    equations: [
      {
        id: "static_tile_budget",
        role: "calculator_demo",
        displayLatex: "U_{static}=N_{tiles}E_{tile}",
        computableExpression: "U_static = N_tiles*E_tile",
        operatorKind: "scalar_expression",
        inputSymbols: ["N_tiles", "E_tile"],
        outputSymbols: ["U_static"],
      },
    ],
    units: [
      { symbol: "U_static", unit: "J", quantity: "energy", dimensionSignature: "M L^2 T^-2" },
      { symbol: "N_tiles", unit: null, quantity: "count", dimensionSignature: "1" },
    ],
    assumptions: ["Tile census must come from a layout, pipeline, or explicit object binding."],
    calculatorPayloads: [
      payload({
        id: "casimir_static_budget_payload",
        expression: "U_static = N_tiles*E_tile",
        displayLatex: "U_{static}=N_{tiles}E_{tile}",
        targetVariable: "U_static",
      }),
    ],
    sourceRefs: [
      repoRef("server/energy-pipeline.ts", "state.U_static", "Pipeline field for static tile budget."),
      repoRef("client/src/components/HelixCasimirAmplifier.tsx", "U_static", "UI surface for Casimir amplifier values."),
    ],
    hintKeys: {
      subjects: ["casimir", "tile", "budget", "array"],
      symbols: ["U_static", "N_tiles", "E_tile"],
      unitSignatures: ["M L^2 T^-2", "1"],
      repoPaths: ["server/energy-pipeline.ts", "client/src/components/HelixCasimirAmplifier.tsx"],
      equationFamilies: ["casimir_tile_budget"],
      simulationOwners: ["casimir", "NHM2"],
    },
  }),
  casimirBadge({
    id: "casimir.tile.duty_budget",
    title: "Casimir Tile Duty Budget",
    plainMeaning:
      "Computes the sector-averaged duty term for a strobing tile budget from burst duty, cycle duty, and concurrent sector count.",
    whyItMatters:
      "It keeps strobing language tied to a cycle-averaged source proxy instead of actuator or steering claims.",
    subjects: ["casimir", "tile", "duty_budget", "sector_schedule", "source_proxy"],
    level: "simulation_specific",
    status: "diagnostic",
    simulationOwners: ["casimir", "NHM2"],
    equationFamilies: ["casimir_tile_duty_budget", "sector_schedule"],
    tags: ["d_eff", "sector_count", "concurrent_sectors", "calculator_loadable", "diagnostic_only"],
    equations: [
      {
        id: "effective_sector_duty",
        role: "calculator_demo",
        displayLatex: "d_{eff}=d_{burst}d_{cycle}\\frac{N_{concurrent}}{N_{sector}}",
        computableExpression: "d_eff = d_burst*d_cycle*(N_concurrent/N_sector)",
        operatorKind: "scalar_expression",
        inputSymbols: ["d_burst", "d_cycle", "N_concurrent", "N_sector"],
        outputSymbols: ["d_eff"],
      },
      {
        id: "time_averaged_amplification",
        role: "calculator_demo",
        displayLatex: "A_{avg}=A_{pulse}d_{eff}",
        computableExpression: "A_avg = A_pulse*d_eff",
        operatorKind: "scalar_expression",
        inputSymbols: ["A_pulse", "d_eff"],
        outputSymbols: ["A_avg"],
      },
    ],
    units: [
      { symbol: "d_eff", unit: null, quantity: "effective_duty", dimensionSignature: "1" },
      { symbol: "N_concurrent", unit: null, quantity: "concurrent_sector_count", dimensionSignature: "1" },
      { symbol: "N_sector", unit: null, quantity: "sector_count", dimensionSignature: "1" },
      { symbol: "A_avg", unit: null, quantity: "time_averaged_amplification", dimensionSignature: "1" },
    ],
    assumptions: [
      "Sector strobing controls a cycle-averaged source proxy only.",
      "Duty budgeting does not prove directional stress-energy steering or macroscopic actuation.",
    ],
    calculatorPayloads: [
      payload({
        id: "casimir_effective_sector_duty_payload",
        expression: "d_eff = d_burst*d_cycle*(N_concurrent/N_sector)",
        displayLatex: "d_{eff}=d_{burst}d_{cycle}\\frac{N_{concurrent}}{N_{sector}}",
        targetVariable: "d_eff",
      }),
      payload({
        id: "casimir_time_averaged_amplification_payload",
        expression: "A_avg = A_pulse*d_eff",
        displayLatex: "A_{avg}=A_{pulse}d_{eff}",
        targetVariable: "A_avg",
      }),
    ],
    sourceRefs: [
      repoRef("configs/needle-hull-mark2-cavity-contract.v1.json", "geometry", "Frozen sectorCount and concurrentSectors."),
      repoRef("configs/needle-hull-mark2-cavity-contract.v1.json", "loss", "Frozen duty and Q-spoiling terms."),
      docRef("docs/casimir-tile-mechanism.md", "duty-cycle", "Mechanism note for duty-cycle ladder terms."),
    ],
    hintKeys: {
      subjects: ["casimir", "tile", "duty_budget", "sector_schedule", "source_proxy"],
      symbols: ["d_eff", "d_burst", "d_cycle", "N_concurrent", "N_sector", "A_avg", "A_pulse"],
      unitSignatures: ["1"],
      repoPaths: ["configs/needle-hull-mark2-cavity-contract.v1.json", "docs/casimir-tile-mechanism.md"],
      equationFamilies: ["casimir_tile_duty_budget", "sector_schedule"],
      simulationOwners: ["casimir", "NHM2"],
    },
  }),
  casimirBadge({
    id: "casimir.cavity.geometry_gain",
    title: "Casimir Geometry Gain",
    plainMeaning: "Applies the geometry gain cube to the static tile budget.",
    whyItMatters: "It exposes one step of the project-specific amplification ladder as scalar math.",
    subjects: ["casimir", "geometry_gain", "amplification", "budget"],
    level: "simulation_specific",
    status: "project_derived",
    simulationOwners: ["casimir", "NHM2"],
    equationFamilies: ["casimir_gain_ladder"],
    tags: ["gammaGeo", "calculator_loadable"],
    equations: [
      {
        id: "geometry_gain",
        role: "calculator_demo",
        displayLatex: "U_{geo}=U_{static}\\gamma_{geo}^3",
        computableExpression: "U_geo = U_static*gammaGeo^3",
        operatorKind: "scalar_expression",
        inputSymbols: ["U_static", "gammaGeo"],
        outputSymbols: ["U_geo"],
      },
    ],
    units: [{ symbol: "U_geo", unit: "J", quantity: "energy", dimensionSignature: "M L^2 T^-2" }],
    assumptions: ["Geometry gain is a diagnostic/proxy knob in the current theory map."],
    calculatorPayloads: [
      payload({
        id: "casimir_geometry_gain_payload",
        expression: "U_geo = U_static*gammaGeo^3",
        displayLatex: "U_{geo}=U_{static}\\gamma_{geo}^3",
        targetVariable: "U_geo",
      }),
    ],
    sourceRefs: [
      repoRef("server/energy-pipeline.ts", "gammaGeo", "Pipeline field for geometry gain."),
      docRef("docs/casimir-tile-mechanism.md", "geometry-gain", "Mechanism note for gain ladder."),
    ],
    hintKeys: {
      subjects: ["casimir", "geometry_gain", "amplification"],
      symbols: ["U_geo", "U_static", "gammaGeo"],
      unitSignatures: ["M L^2 T^-2"],
      repoPaths: ["server/energy-pipeline.ts", "docs/casimir-tile-mechanism.md"],
      equationFamilies: ["casimir_gain_ladder"],
      simulationOwners: ["casimir", "NHM2"],
    },
  }),
  casimirBadge({
    id: "casimir.cavity.output_energy_proxy",
    title: "Casimir Output Energy Proxy",
    plainMeaning: "Applies quality, geometry, compression, and duty factors to a static energy magnitude.",
    whyItMatters: "It keeps the ladder calculation visible while retaining claim-boundary context.",
    subjects: ["casimir", "gain_ladder", "energy", "duty_cycle"],
    level: "simulation_specific",
    status: "diagnostic",
    simulationOwners: ["casimir", "NHM2"],
    equationFamilies: ["casimir_gain_ladder"],
    tags: ["Q_L", "d_eff", "gamma_VdB", "calculator_loadable"],
    equations: [
      {
        id: "output_energy_proxy",
        role: "calculator_demo",
        displayLatex: "E_{out}=|U_{static}|\\gamma_{geo}^3Q_L\\gamma_{VdB}d_{eff}",
        computableExpression: "E_out = absU_static*gammaGeo^3*Q_L*gamma_VdB*d_eff",
        operatorKind: "scalar_expression",
        inputSymbols: ["absU_static", "gammaGeo", "Q_L", "gamma_VdB", "d_eff"],
        outputSymbols: ["E_out"],
      },
    ],
    units: [{ symbol: "E_out", unit: "J", quantity: "energy", dimensionSignature: "M L^2 T^-2" }],
    assumptions: [
      "Diagnostic energy proxy only.",
      "Quality, duty, and compression factors require separate provenance before interpretation.",
    ],
    calculatorPayloads: [
      payload({
        id: "casimir_output_energy_proxy_payload",
        expression: "E_out = absU_static*gammaGeo^3*Q_L*gamma_VdB*d_eff",
        displayLatex: "E_{out}=|U_{static}|\\gamma_{geo}^3Q_L\\gamma_{VdB}d_{eff}",
        targetVariable: "E_out",
      }),
    ],
    sourceRefs: [
      repoRef("server/energy-pipeline.ts", "mass.realisticBandKg", "Pipeline ladder source for energy/mass proxy fields."),
      docRef("docs/casimir-tile-mechanism.md", "amplification-ladder-and-mass-chain", "Mechanism note for ladder terms."),
    ],
    hintKeys: {
      subjects: ["casimir", "gain_ladder", "energy", "duty_cycle"],
      symbols: ["E_out", "absU_static", "gammaGeo", "Q_L", "gamma_VdB", "d_eff"],
      unitSignatures: ["M L^2 T^-2", "1"],
      repoPaths: ["server/energy-pipeline.ts", "docs/casimir-tile-mechanism.md"],
      equationFamilies: ["casimir_gain_ladder"],
      simulationOwners: ["casimir", "NHM2"],
    },
  }),
  casimirBadge({
    id: "casimir.cavity.mass_equivalent_proxy",
    title: "Casimir Mass-Equivalent Proxy",
    plainMeaning: "Converts an energy proxy into a mass-equivalent scalar using c squared.",
    whyItMatters: "It shows the calculator-visible final row of the energy-to-mass proxy chain.",
    subjects: ["casimir", "mass_proxy", "energy", "relativity"],
    level: "simulation_specific",
    status: "diagnostic",
    simulationOwners: ["casimir", "NHM2"],
    equationFamilies: ["mass_equivalent_proxy"],
    tags: ["E_over_c2", "calculator_loadable"],
    equations: [
      {
        id: "mass_equivalent_proxy",
        role: "calculator_demo",
        displayLatex: "M_{proxy}=\\frac{E_{out}}{c^2}",
        computableExpression: "M_proxy = E_out/c^2",
        operatorKind: "scalar_expression",
        inputSymbols: ["E_out", "c"],
        outputSymbols: ["M_proxy"],
      },
    ],
    units: [{ symbol: "M_proxy", unit: "kg", quantity: "mass", dimensionSignature: "M" }],
    assumptions: ["Mass-equivalent proxy only; not a mechanism confirmation."],
    calculatorPayloads: [
      payload({
        id: "casimir_mass_equivalent_proxy_payload",
        expression: "M_proxy = E_out/c^2",
        displayLatex: "M_{proxy}=\\frac{E_{out}}{c^2}",
        targetVariable: "M_proxy",
      }),
    ],
    sourceRefs: [
      repoRef("server/energy-pipeline.ts", "mass", "Pipeline mass-proxy fields."),
      docRef("docs/mass-semantics.md", "mass-mode", "Mass-mode policy and provenance context."),
    ],
    hintKeys: {
      subjects: ["casimir", "mass_proxy", "energy", "relativity"],
      symbols: ["M_proxy", "E_out", "c"],
      unitSignatures: ["M", "M L^2 T^-2", "L T^-1"],
      repoPaths: ["server/energy-pipeline.ts", "docs/mass-semantics.md"],
      equationFamilies: ["mass_equivalent_proxy"],
      simulationOwners: ["casimir", "NHM2"],
    },
  }),
  casimirBadge({
    id: "casimir.cavity.mode_frequency",
    title: "Casimir Cavity Mode Frequency",
    plainMeaning: "Computes a simple standing-wave frequency for a cavity length and mode index.",
    whyItMatters: "It connects cavity geometry to photon/mode energy rows without running a full resonator model.",
    subjects: ["casimir", "cavity", "mode_frequency", "resonator"],
    level: "derived_relation",
    status: "canonical_reference",
    simulationOwners: ["casimir"],
    equationFamilies: ["cavity_mode"],
    tags: ["frequency", "standing_wave", "calculator_loadable"],
    equations: [
      {
        id: "cavity_mode_frequency",
        role: "calculator_demo",
        displayLatex: "f_n=\\frac{nc}{2L}",
        computableExpression: "f_n = n*c/(2*L)",
        operatorKind: "scalar_expression",
        inputSymbols: ["n", "c", "L"],
        outputSymbols: ["f_n"],
      },
    ],
    units: [
      { symbol: "f_n", unit: "Hz", quantity: "frequency", dimensionSignature: "T^-1" },
      { symbol: "L", unit: "m", quantity: "length", dimensionSignature: "L" },
    ],
    assumptions: ["Simple standing-wave proxy; boundary conditions and materials are context rows."],
    calculatorPayloads: [
      payload({
        id: "cavity_mode_frequency_payload",
        expression: "f_n = n*c/(2*L)",
        displayLatex: "f_n=\\frac{nc}{2L}",
        targetVariable: "f_n",
      }),
    ],
    sourceRefs: [
      repoRef("modules/dynamic/dynamic-casimir.ts", "storedEnergyJ", "Dynamic module receives mode/frequency context."),
      docRef("docs/knowledge/cavity-mechanism.md", "cavity-mechanism", "Cavity mechanism knowledge note."),
    ],
    hintKeys: {
      subjects: ["casimir", "cavity", "mode_frequency", "resonator"],
      symbols: ["f_n", "n", "c", "L"],
      unitSignatures: ["T^-1", "L", "L T^-1"],
      repoPaths: ["modules/dynamic/dynamic-casimir.ts", "docs/knowledge/cavity-mechanism.md"],
      equationFamilies: ["cavity_mode"],
      simulationOwners: ["casimir"],
    },
  }),
  casimirBadge({
    id: "casimir.cavity.mode_photon_energy",
    title: "Casimir Mode Photon Energy",
    plainMeaning: "Maps a cavity mode frequency into photon energy using Planck's relation.",
    whyItMatters: "It lets cavity prompts cross into the shared quantum energy-frequency root.",
    subjects: ["casimir", "cavity", "mode_energy", "quantum"],
    level: "derived_relation",
    status: "canonical_reference",
    simulationOwners: ["casimir"],
    equationFamilies: ["cavity_mode", "planck_relation"],
    tags: ["frequency", "energy", "calculator_loadable"],
    equations: [
      {
        id: "cavity_mode_photon_energy",
        role: "calculator_demo",
        displayLatex: "E_n=hf_n",
        computableExpression: "E_n = h*f_n",
        operatorKind: "scalar_expression",
        inputSymbols: ["h", "f_n"],
        outputSymbols: ["E_n"],
      },
    ],
    units: [{ symbol: "E_n", unit: "J", quantity: "energy", dimensionSignature: "M L^2 T^-2" }],
    assumptions: ["Single-mode scalar row only."],
    calculatorPayloads: [
      payload({
        id: "cavity_mode_photon_energy_payload",
        expression: "E_n = h*f_n",
        displayLatex: "E_n=hf_n",
        targetVariable: "E_n",
      }),
    ],
    sourceRefs: [
      repoRef("modules/dynamic/dynamic-casimir.ts", "energyDeltaPerPumpCycleJ", "Dynamic module energy context."),
      docRef("docs/knowledge/physics/dynamic-casimir-effect.md", "dynamic-casimir-effect", "Dynamic Casimir knowledge note."),
    ],
    hintKeys: {
      subjects: ["casimir", "cavity", "mode_energy", "quantum"],
      symbols: ["E_n", "h", "f_n"],
      unitSignatures: ["M L^2 T^-2", "T^-1"],
      repoPaths: ["modules/dynamic/dynamic-casimir.ts", "docs/knowledge/physics/dynamic-casimir-effect.md"],
      equationFamilies: ["cavity_mode", "planck_relation"],
      simulationOwners: ["casimir"],
    },
  }),
  casimirBadge({
    id: "casimir.runtime.static_casimir_module",
    title: "Static Casimir Module Runtime",
    plainMeaning: "References the runtime module that evaluates static Casimir configurations.",
    whyItMatters: "It gives Helix a real code anchor for static Casimir calculations without treating runtime output as a scalar solve.",
    subjects: ["casimir", "runtime", "static_module", "material_model"],
    level: "simulation_specific",
    status: "project_derived",
    simulationOwners: ["casimir"],
    equationFamilies: ["static_casimir_runtime", "material_band"],
    tags: ["runtime", "source_ref"],
    equations: [
      {
        id: "static_casimir_runtime",
        role: "noncomputable_reference",
        displayLatex: "calculateCasimirEnergy(params)\\rightarrow static\\ receipt",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["geometry", "gap", "radius", "materialModel"],
        outputSymbols: ["casimirEnergy", "casimirForce"],
      },
    ],
    units: [],
    assumptions: ["Runtime/source reference only; use a future runtime receipt for material-band interpretation."],
    calculatorPayloads: [],
    sourceRefs: [
      repoRef("modules/sim_core/static-casimir.ts", "calculateCasimirEnergy", "Static Casimir module."),
      repoRef("modules/sim_core/casimir-inference.ts", "inferCasimirForceScale", "Measured-force scale inference path."),
      repoRef("server/services/casimir/telemetry.ts", "telemetry", "Casimir telemetry service."),
    ],
    hintKeys: {
      subjects: ["casimir", "runtime", "static_module", "material_model"],
      symbols: ["casimirEnergy", "casimirForce", "materialModel"],
      unitSignatures: ["M L^2 T^-2", "M L T^-2"],
      repoPaths: ["modules/sim_core/static-casimir.ts", "modules/sim_core/casimir-inference.ts", "server/services/casimir/telemetry.ts"],
      equationFamilies: ["static_casimir_runtime", "material_band"],
      simulationOwners: ["casimir"],
    },
  }),
  casimirBadge({
    id: "casimir.material_receipts",
    title: "Casimir Material Receipts",
    plainMeaning:
      "Requires material response, finite conductivity, roughness, finite temperature, gap metrology, seal/vacuum, and geometry-validity receipts.",
    whyItMatters:
      "It blocks ideal parallel-plate or frozen-geometry rows from being read as fabrication readiness or actuator evidence.",
    subjects: ["casimir", "materials", "metrology", "lifshitz", "geometry_validity"],
    level: "diagnostic_gate",
    status: "blocked",
    simulationOwners: ["casimir", "NHM2"],
    equationFamilies: ["casimir_material_receipts", "geometry_validity"],
    tags: ["lifshitz", "finite_conductivity", "roughness", "finite_temperature", "gap_metrology", "blocked"],
    equations: [
      {
        id: "casimir_material_receipts_gate",
        role: "gate",
        displayLatex:
          "\\mathrm{receipts}=\\epsilon(\\omega)\\land conductivity\\land roughness\\land T\\land gap\\land geometry",
        computableExpression: null,
        operatorKind: "gate_status",
        inputSymbols: ["epsilon_omega", "conductivity", "roughness", "temperature", "gap_metrology", "geometry_validity"],
        outputSymbols: ["material_receipt_status"],
      },
    ],
    units: [],
    assumptions: [
      "Material receipts are required before ideal scalar rows can be interpreted beyond diagnostic source context.",
      "Frozen geometry is review-only and does not certify fabrication readiness.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      repoRef("shared/contracts/casimir-material-receipt.v1.ts", "CasimirMaterialReceiptV1", "Runtime receipt contract for material and geometry evidence."),
      repoRef("configs/needle-hull-mark2-cavity-contract.v1.json", "boundary", "Geometry-freeze boundary statement."),
      repoRef("configs/needle-hull-mark2-cavity-contract.v1.json", "layout.witnessCoupons", "Nanogap and sign-control witness coupon layout."),
      repoRef("modules/sim_core/static-casimir.ts", "calculateCasimirEnergy", "Static idealized calculation that receipts must qualify."),
      docRef("docs/casimir-tile-mechanism.md", "caveats", "Mechanism caveats and verification checklist."),
    ],
    hintKeys: {
      subjects: ["casimir", "materials", "metrology", "lifshitz", "geometry_validity"],
      symbols: ["epsilon_omega", "conductivity", "roughness", "temperature", "gap_metrology", "geometry_validity"],
      unitSignatures: [],
      repoPaths: [
        "configs/needle-hull-mark2-cavity-contract.v1.json",
        "shared/contracts/casimir-material-receipt.v1.ts",
        "modules/sim_core/static-casimir.ts",
        "docs/casimir-tile-mechanism.md",
      ],
      equationFamilies: ["casimir_material_receipts", "geometry_validity"],
      simulationOwners: ["casimir", "NHM2"],
    },
  }),
  casimirBadge({
    id: "casimir.material.lifshitz_receipt",
    title: "Casimir Lifshitz Material Receipt",
    plainMeaning:
      "Checks whether the runtime has a material receipt with dielectric response, finite conductivity, finite temperature, and roughness corrections.",
    whyItMatters:
      "It separates real-material Lifshitz context from the perfect-conductor scalar formula.",
    subjects: ["casimir", "materials", "lifshitz", "dielectric_response", "receipt"],
    level: "diagnostic_gate",
    status: "blocked",
    simulationOwners: ["casimir", "NHM2"],
    equationFamilies: ["casimir_material_receipts", "lifshitz_material_model"],
    tags: ["lifshitz", "material_receipt", "finite_conductivity", "finite_temperature", "roughness"],
    equations: [
      {
        id: "casimir_lifshitz_receipt_gate",
        role: "gate",
        displayLatex:
          "receipt_{Lifshitz}=\\epsilon(\\omega)\\land \\sigma_{finite}\\land T_{finite}\\land roughness",
        computableExpression: null,
        operatorKind: "gate_status",
        inputSymbols: ["epsilon_omega", "finite_conductivity", "finite_temperature", "roughness"],
        outputSymbols: ["material_receipt_status"],
      },
    ],
    units: [],
    assumptions: [
      "A Lifshitz label without dielectric-response provenance is blocked, not material-receipted.",
      "Perfect-conductor rows remain diagnostic scalar rows until this receipt is present.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      repoRef("shared/contracts/casimir-material-receipt.v1.ts", "CasimirMaterialReceiptV1", "Lifshitz/material receipt contract."),
      repoRef("modules/sim_core/static-casimir.ts", "calculateCasimirEnergy", "Static module whose material model is receipt-gated."),
      docRef("docs/casimir-tile-mechanism.md", "caveats", "Mechanism caveats and verification checklist."),
    ],
    hintKeys: {
      subjects: ["casimir", "materials", "lifshitz", "dielectric_response", "receipt"],
      symbols: ["epsilon_omega", "material_receipt_status"],
      unitSignatures: [],
      repoPaths: [
        "shared/contracts/casimir-material-receipt.v1.ts",
        "modules/sim_core/static-casimir.ts",
        "docs/casimir-tile-mechanism.md",
      ],
      equationFamilies: ["casimir_material_receipts", "lifshitz_material_model"],
      simulationOwners: ["casimir", "NHM2"],
    },
  }),
  casimirBadge({
    id: "casimir.geometry.beyond_pfa_validity",
    title: "Casimir Beyond-PFA Geometry Validity",
    plainMeaning:
      "Checks whether the tile geometry is valid beyond the simple proximity-force/parallel-plate approximation.",
    whyItMatters:
      "It prevents curved or rough nanogap geometry from inheriting the ideal plate scalar without geometry evidence.",
    subjects: ["casimir", "geometry", "pfa", "roughness", "metrology"],
    level: "diagnostic_gate",
    status: "blocked",
    simulationOwners: ["casimir", "NHM2"],
    equationFamilies: ["casimir_material_receipts", "geometry_validity"],
    tags: ["geometry", "beyond_pfa", "gap_metrology", "roughness", "blocked"],
    equations: [
      {
        id: "casimir_beyond_pfa_validity_gate",
        role: "gate",
        displayLatex:
          "geometry_{valid}=gap_{measured}\\land roughness\\land beyond\\ PFA",
        computableExpression: null,
        operatorKind: "gate_status",
        inputSymbols: ["gap_metrology", "roughness", "beyond_pfa_validity"],
        outputSymbols: ["geometry_receipt_status"],
      },
    ],
    units: [],
    assumptions: [
      "Parallel-plate and PFA-like geometry rows are not geometry receipts.",
      "Beyond-PFA validity must be explicit before using geometry-corrected Casimir rows as source evidence.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      repoRef("shared/contracts/casimir-material-receipt.v1.ts", "geometry.beyondPfaValidity", "Geometry validity field in the material receipt."),
      repoRef("configs/needle-hull-mark2-cavity-contract.v1.json", "layout.witnessCoupons", "Witness coupon context for nanogap and geometry checks."),
      docRef("docs/casimir-tile-mechanism.md", "caveats", "Mechanism caveats and verification checklist."),
    ],
    hintKeys: {
      subjects: ["casimir", "geometry", "pfa", "roughness", "metrology"],
      symbols: ["gap_metrology", "roughness", "beyond_pfa_validity"],
      unitSignatures: [],
      repoPaths: [
        "shared/contracts/casimir-material-receipt.v1.ts",
        "configs/needle-hull-mark2-cavity-contract.v1.json",
        "docs/casimir-tile-mechanism.md",
      ],
      equationFamilies: ["casimir_material_receipts", "geometry_validity"],
      simulationOwners: ["casimir", "NHM2"],
    },
  }),
  casimirBadge({
    id: "casimir.geometry.finite_temperature_maxwell_stress",
    title: "Finite-Temperature Maxwell-Stress Receipt",
    plainMeaning:
      "Requires a converged, artifact-backed Maxwell-stress calculation for the declared finite geometry, material response, and temperature before that geometry is used as Casimir source context.",
    whyItMatters:
      "It creates an evidence gate for moving beyond ideal parallel plates around tile pockets, rims, anchors, and support structures without treating a numerical force calculation as an NHM2 mechanism.",
    subjects: [
      "casimir",
      "geometry",
      "finite_temperature",
      "maxwell_stress",
      "lifshitz",
      "receipt",
    ],
    level: "diagnostic_gate",
    status: "blocked",
    simulationOwners: ["casimir", "NHM2"],
    equationFamilies: [
      "finite_temperature_maxwell_stress",
      "casimir_material_receipts",
      "geometry_validity",
    ],
    tags: [
      "finite_temperature",
      "maxwell_stress",
      "finite_geometry",
      "material_response",
      "receipt_required",
      "blocked",
    ],
    equations: [
      {
        id: "finite_temperature_maxwell_stress_receipt_gate",
        role: "gate",
        displayLatex:
          "receipt_{MST}=\\epsilon(\\omega)\\land T\\land geometry_{finite}\\land convergence\\land hashes",
        computableExpression: null,
        operatorKind: "gate_status",
        inputSymbols: [
          "epsilon_omega",
          "finite_temperature",
          "finite_geometry",
          "maxwell_stress_convergence",
          "artifact_hashes",
        ],
        outputSymbols: ["maxwell_stress_receipt_status"],
      },
    ],
    units: [],
    assumptions: [
      "The gate requires a run-specific receipt with material model, temperature, geometry/mesh, convergence, and artifact provenance.",
      "The discontinuous-Galerkin time-domain method is a candidate numerical formalism, not an already integrated NHM2 tile solver.",
      "A passed Casimir force receipt would remain diagnostic source context and cannot establish NHM2, propulsion, transport, route ETA, or certified-speed claims.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      repoRef(
        "shared/contracts/casimir-material-receipt.v1.ts",
        "CasimirMaterialReceiptV1",
        "Material and finite-temperature receipt contract that a Maxwell-stress artifact must satisfy.",
      ),
      repoRef(
        "configs/needle-hull-mark2-cavity-contract.v1.json",
        "layout",
        "Declared finite tile-pocket, rim, anchor, and support geometry context.",
      ),
      literatureRef(
        "https://arxiv.org/abs/2603.03888",
        "arxiv_2603_03888_finite_temperature_maxwell_stress",
        "Primary method source for finite-temperature Casimir-Lifshitz evaluation with the Maxwell stress tensor in realistic materials and finite geometries.",
      ),
    ],
    hintKeys: {
      subjects: [
        "casimir",
        "geometry",
        "finite_temperature",
        "maxwell_stress",
        "lifshitz",
        "receipt",
      ],
      symbols: [
        "epsilon_omega",
        "finite_temperature",
        "finite_geometry",
        "maxwell_stress_convergence",
        "maxwell_stress_receipt_status",
      ],
      unitSignatures: [],
      repoPaths: [
        "shared/contracts/casimir-material-receipt.v1.ts",
        "configs/needle-hull-mark2-cavity-contract.v1.json",
        "https://arxiv.org/abs/2603.03888",
      ],
      equationFamilies: [
        "finite_temperature_maxwell_stress",
        "casimir_material_receipts",
        "geometry_validity",
      ],
      simulationOwners: ["casimir", "NHM2"],
    },
  }),
  casimirBadge({
    id: "casimir.claim_boundary.diagnostic_source_context",
    title: "Casimir Diagnostic Source Boundary",
    plainMeaning: "Marks Casimir cavity rows as diagnostic/source-context rows, not physical confirmation.",
    whyItMatters: "It keeps the theory atlas from overstating Casimir tile calculations when they overlap NHM2 or QEI paths.",
    subjects: ["casimir", "claim_boundary", "safety"],
    level: "claim_boundary",
    status: "blocked",
    simulationOwners: ["casimir", "NHM2"],
    equationFamilies: ["claim_boundary"],
    tags: ["boundary", "diagnostic_only"],
    equations: [
      {
        id: "casimir_source_boundary",
        role: "noncomputable_reference",
        displayLatex: "claim_{Casimir}=diagnostic\\ source\\ context",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["casimir_badge_trace", "source_refs"],
        outputSymbols: ["claim_boundary"],
      },
    ],
    units: [],
    assumptions: [
      "Casimir rows in this graph are diagnostic/source-context artifacts.",
      "Promotion requires separate evidence gates outside this map.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      repoRef("shared/contracts/nhm2-observable-equation-map.v1.ts", "forbidden_claims", "Existing claim-boundary guardrails."),
      docRef("docs/casimir-tile-mechanism.md", "caveats", "Mechanism caveats and verification checklist."),
    ],
    hintKeys: {
      subjects: ["casimir", "claim_boundary", "safety"],
      symbols: ["claim_Casimir", "claim_boundary"],
      unitSignatures: [],
      repoPaths: ["shared/contracts/nhm2-observable-equation-map.v1.ts", "docs/casimir-tile-mechanism.md"],
      equationFamilies: ["claim_boundary"],
      simulationOwners: ["casimir", "NHM2"],
    },
  }),
];

export const CASIMIR_CAVITY_THEORY_EDGES: TheoryBadgeEdgeV1[] = [
  {
    id: "quantum_energy_supports_cavity_mode_energy",
    from: "physics.quantum.energy_frequency",
    to: "casimir.cavity.mode_photon_energy",
    relation: "requires",
    label: "Mode photon energy reuses the shared energy-frequency relation.",
    claimBoundaryNote: "Scalar quantum relation only.",
  },
  {
    id: "speed_of_light_supports_cavity_mode",
    from: "physics.constants.speed_of_light",
    to: "casimir.cavity.mode_frequency",
    relation: "uses_constant",
    label: "Mode frequency uses the shared speed-of-light constant.",
    claimBoundaryNote: "Cavity mode proxy only.",
  },
  {
    id: "cavity_mode_feeds_mode_energy",
    from: "casimir.cavity.mode_frequency",
    to: "casimir.cavity.mode_photon_energy",
    relation: "derives",
    label: "Mode frequency feeds the single-mode energy row.",
    claimBoundaryNote: "Single-mode scalar proxy only.",
  },
  {
    id: "energy_density_supports_casimir_energy_area",
    from: "physics.energy.energy_density",
    to: "casimir.cavity.parallel_plate_energy_density",
    relation: "requires",
    label: "Casimir energy-per-area shares the energy-density foundation.",
    claimBoundaryNote: "Shared dimensional context only.",
  },
  {
    id: "casimir_energy_area_feeds_pressure",
    from: "casimir.cavity.parallel_plate_energy_density",
    to: "casimir.cavity.parallel_plate_pressure",
    relation: "derives",
    label: "Pressure follows the same gap-dependent static Casimir family.",
    claimBoundaryNote: "Idealized static scalar row.",
  },
  {
    id: "casimir_energy_area_feeds_tile_energy",
    from: "casimir.cavity.parallel_plate_energy_density",
    to: "casimir.cavity.per_tile_energy",
    relation: "derives",
    label: "Per-area static energy becomes per-tile energy through tile area.",
    claimBoundaryNote: "Tile area must be explicitly supplied.",
  },
  {
    id: "casimir_tile_energy_feeds_static_budget",
    from: "casimir.cavity.per_tile_energy",
    to: "casimir.cavity.static_tile_budget",
    relation: "derives",
    label: "Tile energy aggregates over a tile census.",
    claimBoundaryNote: "Tile count must come from layout/pipeline context.",
  },
  {
    id: "casimir_static_budget_feeds_duty_budget",
    from: "casimir.cavity.static_tile_budget",
    to: "casimir.tile.duty_budget",
    relation: "requires",
    label: "Static tile budget requires sector-duty context before cycle-averaged source proxy language.",
    claimBoundaryNote: "Duty averaging remains diagnostic source context only.",
  },
  {
    id: "casimir_static_budget_feeds_geometry_gain",
    from: "casimir.cavity.static_tile_budget",
    to: "casimir.cavity.geometry_gain",
    relation: "derives",
    label: "Static budget feeds the geometry-gain row.",
    claimBoundaryNote: "Geometry gain remains a diagnostic/proxy knob.",
  },
  {
    id: "casimir_geometry_gain_feeds_output_proxy",
    from: "casimir.cavity.geometry_gain",
    to: "casimir.cavity.output_energy_proxy",
    relation: "derives",
    label: "Gain ladder terms combine into an output-energy proxy.",
    claimBoundaryNote: "Output energy is a proxy row in this map.",
  },
  {
    id: "casimir_duty_budget_feeds_output_proxy",
    from: "casimir.tile.duty_budget",
    to: "casimir.cavity.output_energy_proxy",
    relation: "requires",
    label: "Output-energy proxy rows require the effective duty term used in the sector schedule.",
    claimBoundaryNote: "Duty terms do not prove directional steering or actuation.",
  },
  {
    id: "casimir_output_proxy_feeds_mass_proxy",
    from: "casimir.cavity.output_energy_proxy",
    to: "casimir.cavity.mass_equivalent_proxy",
    relation: "derives",
    label: "Energy proxy can be converted to mass-equivalent units.",
    claimBoundaryNote: "Mass-equivalent row is not physical confirmation.",
  },
  {
    id: "casimir_static_runtime_documents_boundary",
    from: "casimir.runtime.static_casimir_module",
    to: "casimir.claim_boundary.diagnostic_source_context",
    relation: "documents",
    label: "Runtime references must carry the diagnostic source boundary.",
    claimBoundaryNote: "Runtime output requires receipt/provenance before interpretation.",
  },
  {
    id: "casimir_material_receipts_document_boundary",
    from: "casimir.material_receipts",
    to: "casimir.claim_boundary.diagnostic_source_context",
    relation: "requires",
    label: "Material receipts must be present before Casimir source rows can be interpreted beyond diagnostics.",
    claimBoundaryNote: "Missing material and metrology receipts block physical mechanism language.",
  },
  {
    id: "casimir_lifshitz_receipt_feeds_material_receipts",
    from: "casimir.material.lifshitz_receipt",
    to: "casimir.material_receipts",
    relation: "requires",
    label: "The material-receipt gate includes Lifshitz/dielectric-response provenance.",
    claimBoundaryNote: "A material model label alone is not a material receipt.",
  },
  {
    id: "casimir_beyond_pfa_feeds_material_receipts",
    from: "casimir.geometry.beyond_pfa_validity",
    to: "casimir.material_receipts",
    relation: "requires",
    label: "The material-receipt gate includes gap metrology and beyond-PFA geometry validity.",
    claimBoundaryNote: "Ideal plate geometry does not certify shaped tile geometry.",
  },
  {
    id: "casimir_beyond_pfa_validity_feeds_lifshitz_receipt",
    from: "casimir.geometry.beyond_pfa_validity",
    to: "casimir.material.lifshitz_receipt",
    relation: "requires",
    label: "Lifshitz material receipts require geometry/metrology context before shaped-tile source interpretation.",
    claimBoundaryNote: "A dielectric-response receipt without geometry validity remains diagnostic only.",
  },
  {
    id: "casimir_lifshitz_receipt_feeds_finite_temperature_maxwell_stress",
    from: "casimir.material.lifshitz_receipt",
    to: "casimir.geometry.finite_temperature_maxwell_stress",
    relation: "requires",
    label: "Finite-temperature Maxwell-stress evaluation requires dielectric-response and material-model provenance.",
    claimBoundaryNote: "A material model without a run-specific Maxwell-stress receipt remains diagnostic only.",
  },
  {
    id: "casimir_beyond_pfa_feeds_finite_temperature_maxwell_stress",
    from: "casimir.geometry.beyond_pfa_validity",
    to: "casimir.geometry.finite_temperature_maxwell_stress",
    relation: "requires",
    label: "Finite-geometry Maxwell-stress evaluation requires explicit geometry and metrology validity.",
    claimBoundaryNote: "A finite-geometry mesh cannot certify the fabricated tile geometry by itself.",
  },
  {
    id: "casimir_finite_temperature_maxwell_stress_feeds_material_receipts",
    from: "casimir.geometry.finite_temperature_maxwell_stress",
    to: "casimir.material_receipts",
    relation: "requires",
    label: "The material-receipt gate requires an artifact-backed finite-temperature Maxwell-stress result when shaped finite geometry is invoked.",
    claimBoundaryNote: "The receipt remains source context and cannot establish a physical NHM2 mechanism.",
  },
  {
    id: "casimir_finite_temperature_maxwell_stress_checks_wall_t00_residual",
    from: "casimir.geometry.finite_temperature_maxwell_stress",
    to: "nhm2.closure.wall_t00_source_residual",
    relation: "diagnostic_checks",
    label: "A receipt-backed finite-geometry Casimir result may supply source-context evidence to the wall T00 residual gate.",
    claimBoundaryNote: "A Casimir force receipt cannot repair a semantic or same-basis tensor mismatch.",
  },
  {
    id: "casimir_lifshitz_receipt_feeds_wall_t00_source_residual",
    from: "casimir.material.lifshitz_receipt",
    to: "nhm2.closure.wall_t00_source_residual",
    relation: "diagnostic_checks",
    label: "Material receipts provide source-context evidence for the wall-region T00 residual gate.",
    claimBoundaryNote: "Receipt-backed Casimir rows still do not override wall closure failure.",
  },
  {
    id: "casimir_ideal_scalar_requires_receipt_for_source_evidence",
    from: "casimir.cavity.parallel_plate_energy_density",
    to: "casimir.material.lifshitz_receipt",
    relation: "requires",
    label: "The ideal scalar row requires a material receipt before source-evidence interpretation.",
    claimBoundaryNote: "The calculator payload remains available as a diagnostic scalar.",
  },
  {
    id: "casimir_ideal_geometry_requires_beyond_pfa_for_source_evidence",
    from: "casimir.cavity.parallel_plate_energy_density",
    to: "casimir.geometry.beyond_pfa_validity",
    relation: "blocks",
    label: "The ideal plate row requires geometry validity before shaped tile source-evidence interpretation.",
    claimBoundaryNote: "Parallel-plate validity is not a shaped-geometry receipt.",
  },
  {
    id: "casimir_mass_proxy_blocks_claim_promotion",
    from: "casimir.cavity.mass_equivalent_proxy",
    to: "casimir.claim_boundary.diagnostic_source_context",
    relation: "blocks",
    label: "Mass-equivalent proxy rows cannot promote themselves into physical confirmation.",
    claimBoundaryNote: "Promotion is intentionally disallowed in v1.",
  },
  {
    id: "casimir_budget_shares_units_with_nhm2_source",
    from: "casimir.cavity.static_tile_budget",
    to: "nhm2.source.energy_density_proxy",
    relation: "shares_units",
    label: "Casimir budget rows overlap NHM2 source-energy unit families.",
    claimBoundaryNote: "Shared units are a hint relation, not validation.",
  },
];

export function buildCasimirCavityTheoryBadgesV1(): {
  badges: TheoryBadgeV1[];
  edges: TheoryBadgeEdgeV1[];
} {
  return {
    badges: CASIMIR_CAVITY_THEORY_BADGES,
    edges: CASIMIR_CAVITY_THEORY_EDGES,
  };
}
