import {
  type TheoryBadgeClaimBoundaryV1,
  type TheoryBadgeEdgeV1,
  type TheoryBadgeV1,
} from "../contracts/theory-badge-graph.v1";

const CROSS_SCALE_BOUNDARY: TheoryBadgeClaimBoundaryV1 = {
  diagnosticOnly: true,
  doesValidateNHM2: false,
  validationClaimAllowed: false,
  physicalMechanismClaimAllowed: false,
  promotionAllowed: false,
};

const literatureRef = (id: string, note?: string): TheoryBadgeV1["sourceRefs"][number] => ({
  kind: "literature_ref",
  id,
  note: note ?? null,
});

const crossScaleBadge = (badge: Omit<TheoryBadgeV1, "claimBoundary">): TheoryBadgeV1 => ({
  ...badge,
  claimBoundary: CROSS_SCALE_BOUNDARY,
});

const calculatorPayload = (args: {
  id: string;
  expression: string;
  displayLatex: string;
  targetVariable: string;
}): TheoryBadgeV1["calculatorPayloads"][number] => ({
  id: args.id,
  expression: args.expression,
  displayLatex: args.displayLatex,
  preferredAction: "solve_with_steps",
  targetVariable: args.targetVariable,
  setupContext: null,
});

const commonAssumptions = [
  "Cross-scale rows are diagnostic connective tissue between established theory badges.",
  "They do not validate NHM2, propulsion, consciousness, biology, or prebiotic-success claims.",
  "Scalar payloads are proxy demonstrations unless a runtime receipt, table, or platform-specific model is attached.",
];

export const CROSS_SCALE_CONNECTIVE_TISSUE_THEORY_BADGES: TheoryBadgeV1[] = [
  crossScaleBadge({
    id: "physics.nuclear.reaction.astrophysical_s_factor_context",
    title: "Astrophysical S-Factor Context",
    plainMeaning:
      "Represents the S-factor as a low-energy charged-particle fusion cross-section factor after the Coulomb tunneling term is separated.",
    whyItMatters:
      "It bridges Coulomb barrier and tunneling badges into reaction-rate language without letting a tunneling proxy become a full stellar yield model.",
    subjects: ["nuclear_physics", "fusion", "s_factor", "coulomb_barrier", "reaction_rate"],
    level: "model",
    status: "canonical_reference",
    simulationOwners: ["general_physics", "stellar_reference"],
    equationFamilies: ["astrophysical_s_factor", "fusion_cross_section", "gamow_proxy"],
    tags: ["s_factor", "fusion_proxy", "calculator_loadable", "claim_boundary"],
    equations: [
      {
        id: "s_factor_cross_section_proxy",
        role: "calculator_demo",
        displayLatex: "\\sigma(E)_{proxy}=\\frac{S(E)}{E}e^{-2\\pi\\eta}",
        computableExpression: "sigma_proxy_m2 = (S_E_J_m2 / E_J) * exp(-2 * pi * eta)",
        operatorKind: "scalar_expression",
        inputSymbols: ["S_E_J_m2", "E_J", "eta"],
        outputSymbols: ["sigma_proxy_m2"],
      },
    ],
    units: [
      { symbol: "S_E_J_m2", unit: "J m^2", quantity: "s_factor_proxy", dimensionSignature: "M L^4 T^-2" },
      { symbol: "E_J", unit: "J", quantity: "center_of_mass_energy", dimensionSignature: "M L^2 T^-2" },
      { symbol: "sigma_proxy_m2", unit: "m^2", quantity: "cross_section_proxy", dimensionSignature: "L^2" },
      { symbol: "eta", unit: null, quantity: "sommerfeld_parameter", dimensionSignature: "1" },
    ],
    assumptions: [
      ...commonAssumptions,
      "The payload is a shape proxy and requires measured or evaluated S(E), screening, and channel data for astrophysical use.",
    ],
    calculatorPayloads: [
      calculatorPayload({
        id: "s_factor_cross_section_proxy_payload",
        expression: "sigma_proxy_m2 = (S_E_J_m2 / E_J) * exp(-2 * pi * eta)",
        displayLatex: "\\sigma(E)_{proxy}=\\frac{S(E)}{E}e^{-2\\pi\\eta}",
        targetVariable: "sigma_proxy_m2",
      }),
    ],
    sourceRefs: [
      literatureRef("doi:10.1146/annurev.aa.05.090167.002521", "Fowler, Caughlan, and Zimmerman thermonuclear reaction-rate reference."),
      literatureRef("doi:10.1103/RevModPhys.83.195", "Adelberger et al. solar fusion cross-section review."),
    ],
    hintKeys: {
      subjects: ["nuclear_physics", "fusion", "s_factor", "coulomb_barrier", "reaction_rate"],
      symbols: ["S_E_J_m2", "E_J", "eta", "sigma_proxy_m2"],
      unitSignatures: ["M L^4 T^-2", "M L^2 T^-2", "L^2", "1"],
      repoPaths: [],
      equationFamilies: ["astrophysical_s_factor", "fusion_cross_section", "gamow_proxy"],
      simulationOwners: ["general_physics", "stellar_reference"],
    },
  }),
  crossScaleBadge({
    id: "physics.nuclear.reaction.thermonuclear_rate_context",
    title: "Thermonuclear Reaction-Rate Context",
    plainMeaning:
      "Represents a reduced two-body reaction-rate density from number densities, relative velocity, and cross section.",
    whyItMatters:
      "It gives fusion prompts the missing density-and-rate bridge between microscopic cross sections and stellar nucleosynthesis context.",
    subjects: ["nuclear_physics", "fusion", "reaction_rate", "stellar_nucleosynthesis"],
    level: "derived_relation",
    status: "canonical_reference",
    simulationOwners: ["stellar_reference", "general_physics"],
    equationFamilies: ["thermonuclear_reaction_rate", "rate_density", "reaction_network"],
    tags: ["reaction_rate", "density", "calculator_loadable", "proxy"],
    equations: [
      {
        id: "two_body_rate_density_proxy",
        role: "calculator_demo",
        displayLatex: "r_{12,proxy}=n_1 n_2 \\sigma v",
        computableExpression: "rate_proxy_m3_s = n1_m3 * n2_m3 * sigma_m2 * v_m_s",
        operatorKind: "scalar_expression",
        inputSymbols: ["n1_m3", "n2_m3", "sigma_m2", "v_m_s"],
        outputSymbols: ["rate_proxy_m3_s"],
      },
    ],
    units: [
      { symbol: "n1_m3", unit: "1/m^3", quantity: "number_density_1", dimensionSignature: "L^-3" },
      { symbol: "n2_m3", unit: "1/m^3", quantity: "number_density_2", dimensionSignature: "L^-3" },
      { symbol: "sigma_m2", unit: "m^2", quantity: "cross_section", dimensionSignature: "L^2" },
      { symbol: "v_m_s", unit: "m/s", quantity: "relative_speed", dimensionSignature: "L T^-1" },
      { symbol: "rate_proxy_m3_s", unit: "1/(m^3 s)", quantity: "reaction_rate_density_proxy", dimensionSignature: "L^-3 T^-1" },
    ],
    assumptions: [
      ...commonAssumptions,
      "A serious thermonuclear rate requires a thermal average, channel factors, screening, and evaluated reaction data.",
    ],
    calculatorPayloads: [
      calculatorPayload({
        id: "two_body_rate_density_proxy_payload",
        expression: "rate_proxy_m3_s = n1_m3 * n2_m3 * sigma_m2 * v_m_s",
        displayLatex: "r_{12,proxy}=n_1 n_2 \\sigma v",
        targetVariable: "rate_proxy_m3_s",
      }),
    ],
    sourceRefs: [
      literatureRef("doi:10.1146/annurev.aa.05.090167.002521", "Thermonuclear reaction rates for stellar contexts."),
      literatureRef("doi:10.1103/RevModPhys.83.195", "Solar fusion reaction-rate and cross-section review."),
    ],
    hintKeys: {
      subjects: ["nuclear_physics", "fusion", "reaction_rate", "stellar_nucleosynthesis"],
      symbols: ["n1_m3", "n2_m3", "sigma_m2", "v_m_s", "rate_proxy_m3_s"],
      unitSignatures: ["L^-3", "L^2", "L T^-1", "L^-3 T^-1"],
      repoPaths: [],
      equationFamilies: ["thermonuclear_reaction_rate", "rate_density", "reaction_network"],
      simulationOwners: ["stellar_reference", "general_physics"],
    },
  }),
  crossScaleBadge({
    id: "physics.nuclear.reaction.plasma_screening_context",
    title: "Plasma Screening Context",
    plainMeaning:
      "Represents plasma screening as environmental modification of charged-particle reaction entrance conditions.",
    whyItMatters:
      "It prevents bare Coulomb-barrier intuition from being treated as the whole stellar-plasma fusion story.",
    subjects: ["nuclear_physics", "plasma", "screening", "fusion", "stellar_core"],
    level: "model",
    status: "canonical_reference",
    simulationOwners: ["stellar_reference", "general_physics"],
    equationFamilies: ["plasma_screening", "fusion_rate_correction", "stellar_plasma_context"],
    tags: ["screening", "plasma", "noncomputable_reference", "claim_boundary"],
    equations: [
      {
        id: "screening_factor_context",
        role: "noncomputable_reference",
        displayLatex: "r_{screened}=f_{screen}(T,\\rho,Z_i,\\mathrm{plasma})r_{bare}",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["T_K", "rho_kg_m3", "Z_i", "r_bare"],
        outputSymbols: ["r_screened"],
      },
    ],
    units: [
      { symbol: "T_K", unit: "K", quantity: "temperature", dimensionSignature: "Theta" },
      { symbol: "rho_kg_m3", unit: "kg/m^3", quantity: "mass_density", dimensionSignature: "M L^-3" },
      { symbol: "r_screened", unit: null, quantity: "screened_rate_context", dimensionSignature: "mixed" },
    ],
    assumptions: [
      ...commonAssumptions,
      "Screening is model- and regime-dependent and is not solved by the scalar Coulomb barrier badge.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      literatureRef("doi:10.1071/PH540373", "Salpeter weak-screening reference for nuclear reactions in stars."),
      literatureRef("doi:10.1103/RevModPhys.83.195", "Solar fusion review with screening and low-energy reaction context."),
    ],
    hintKeys: {
      subjects: ["nuclear_physics", "plasma", "screening", "fusion", "stellar_core"],
      symbols: ["T_K", "rho_kg_m3", "Z_i", "r_bare", "r_screened"],
      unitSignatures: ["Theta", "M L^-3", "mixed"],
      repoPaths: [],
      equationFamilies: ["plasma_screening", "fusion_rate_correction", "stellar_plasma_context"],
      simulationOwners: ["stellar_reference", "general_physics"],
    },
  }),
  crossScaleBadge({
    id: "physics.nuclear.structure.semi_empirical_mass_formula_context",
    title: "Semi-Empirical Mass-Formula Context",
    plainMeaning:
      "Represents nuclear binding systematics through volume, surface, Coulomb, asymmetry, and pairing terms.",
    whyItMatters:
      "It gives the element-origin branch a bounded nuclear-structure bridge beyond a single mass-defect scalar.",
    subjects: ["nuclear_structure", "binding_energy", "mass_formula", "element_origin"],
    level: "model",
    status: "canonical_reference",
    simulationOwners: ["general_physics", "stellar_reference"],
    equationFamilies: ["semi_empirical_mass_formula", "nuclear_binding_systematics"],
    tags: ["binding_energy", "mass_formula", "nuclear_structure", "claim_boundary"],
    equations: [
      {
        id: "semf_context",
        role: "noncomputable_reference",
        displayLatex: "B(A,Z)=a_vA-a_sA^{2/3}-a_c\\frac{Z(Z-1)}{A^{1/3}}-a_a\\frac{(A-2Z)^2}{A}+\\delta",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["A", "Z", "a_v", "a_s", "a_c", "a_a", "delta_pairing"],
        outputSymbols: ["B_A_Z"],
      },
    ],
    units: [
      { symbol: "A", unit: null, quantity: "mass_number", dimensionSignature: "1" },
      { symbol: "Z", unit: null, quantity: "atomic_number", dimensionSignature: "1" },
      { symbol: "B_A_Z", unit: "J", quantity: "binding_energy_context", dimensionSignature: "M L^2 T^-2" },
    ],
    assumptions: [
      ...commonAssumptions,
      "The formula is a nuclear-systematics context and does not replace measured nuclear masses or reaction network yields.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      literatureRef("doi:10.1007/BF01337700", "Weizsacker semi-empirical mass formula reference."),
    ],
    hintKeys: {
      subjects: ["nuclear_structure", "binding_energy", "mass_formula", "element_origin"],
      symbols: ["A", "Z", "B_A_Z", "a_v", "a_s", "a_c", "a_a", "delta_pairing"],
      unitSignatures: ["1", "M L^2 T^-2"],
      repoPaths: [],
      equationFamilies: ["semi_empirical_mass_formula", "nuclear_binding_systematics"],
      simulationOwners: ["general_physics", "stellar_reference"],
    },
  }),
  crossScaleBadge({
    id: "physics.nuclear.structure.shell_magic_number_context",
    title: "Nuclear Shell Magic-Number Context",
    plainMeaning:
      "Represents nuclear shell closures and magic numbers as stability context for isotope and element-origin interpretation.",
    whyItMatters:
      "It separates nuclear shell stability from electron shell chemistry while still letting both branches meet at element identity.",
    subjects: ["nuclear_structure", "shell_model", "magic_numbers", "isotope_stability"],
    level: "model",
    status: "canonical_reference",
    simulationOwners: ["general_physics", "stellar_reference"],
    equationFamilies: ["nuclear_shell_model", "magic_number_context", "isotope_stability"],
    tags: ["shell_model", "magic_numbers", "nuclear_structure", "claim_boundary"],
    equations: [
      {
        id: "magic_number_context",
        role: "noncomputable_reference",
        displayLatex: "N,Z\\in\\{2,8,20,28,50,82,126\\}\\Rightarrow\\mathrm{shell\\ closure\\ context}",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["N", "Z"],
        outputSymbols: ["shell_closure_context"],
      },
    ],
    units: [
      { symbol: "N", unit: null, quantity: "neutron_number", dimensionSignature: "1" },
      { symbol: "Z", unit: null, quantity: "atomic_number", dimensionSignature: "1" },
    ],
    assumptions: [
      ...commonAssumptions,
      "Nuclear shell closures provide stability context and do not determine chemical phase or molecular binding by themselves.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      literatureRef("doi:10.1103/PhysRev.74.235", "Mayer nuclear shell model and magic-number reference."),
      literatureRef("doi:10.1103/PhysRev.75.1766.2", "Haxel, Jensen, and Suess shell-model reference."),
    ],
    hintKeys: {
      subjects: ["nuclear_structure", "shell_model", "magic_numbers", "isotope_stability"],
      symbols: ["N", "Z", "shell_closure_context"],
      unitSignatures: ["1"],
      repoPaths: [],
      equationFamilies: ["nuclear_shell_model", "magic_number_context", "isotope_stability"],
      simulationOwners: ["general_physics", "stellar_reference"],
    },
  }),
  crossScaleBadge({
    id: "physics.atomic.spectra.transition_probability_context",
    title: "Atomic Transition-Probability Context",
    plainMeaning:
      "Represents transition probabilities and oscillator strengths as the atomic-data layer behind spectral line interpretation.",
    whyItMatters:
      "It prevents line wavelengths alone from carrying abundance or origin claims without atomic transition data and calibration.",
    subjects: ["atomic_physics", "spectroscopy", "transition_probability", "oscillator_strength"],
    level: "model",
    status: "canonical_reference",
    simulationOwners: ["general_physics", "stellar_reference"],
    equationFamilies: ["transition_probability", "oscillator_strength", "spectral_line_strength"],
    tags: ["spectroscopy", "atomic_data", "oscillator_strength", "claim_boundary"],
    equations: [
      {
        id: "transition_probability_context",
        role: "noncomputable_reference",
        displayLatex: "I_{line}=\\mathrm{context}(A_{ul},f_{lu},N_l,T,\\mathrm{radiative\\ transfer})",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["A_ul_s_inv", "f_lu", "N_l", "T_K"],
        outputSymbols: ["line_intensity_context"],
      },
    ],
    units: [
      { symbol: "A_ul_s_inv", unit: "1/s", quantity: "einstein_a_coefficient", dimensionSignature: "T^-1" },
      { symbol: "f_lu", unit: null, quantity: "oscillator_strength", dimensionSignature: "1" },
      { symbol: "N_l", unit: null, quantity: "lower_level_population", dimensionSignature: "mixed" },
    ],
    assumptions: [
      ...commonAssumptions,
      "Transition probabilities constrain line strengths but do not by themselves prove element origin or abundance.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      literatureRef("doi:10.1063/1.3077727", "Wiese and Fuhr atomic transition probabilities reference."),
      literatureRef("NIST-Atomic-Spectra-Database", "Evaluated atomic wavelengths, energy levels, and transition data."),
    ],
    hintKeys: {
      subjects: ["atomic_physics", "spectroscopy", "transition_probability", "oscillator_strength"],
      symbols: ["A_ul_s_inv", "f_lu", "N_l", "T_K", "line_intensity_context"],
      unitSignatures: ["T^-1", "1", "mixed"],
      repoPaths: [],
      equationFamilies: ["transition_probability", "oscillator_strength", "spectral_line_strength"],
      simulationOwners: ["general_physics", "stellar_reference"],
    },
  }),
  crossScaleBadge({
    id: "physics.atomic.spectra.line_broadening_context",
    title: "Spectral Line-Broadening Context",
    plainMeaning:
      "Represents thermal, pressure, natural, Zeeman, rotational, and instrumental broadening as context for spectral feature interpretation.",
    whyItMatters:
      "It keeps spectral detections from becoming overconfident line IDs or abundance claims without width and calibration context.",
    subjects: ["spectroscopy", "line_broadening", "radiative_transfer", "observational_inference"],
    level: "model",
    status: "canonical_reference",
    simulationOwners: ["stellar_reference", "general_physics"],
    equationFamilies: ["line_broadening", "radiative_transfer", "instrument_response"],
    tags: ["spectroscopy", "line_width", "instrument", "claim_boundary"],
    equations: [
      {
        id: "line_width_context",
        role: "noncomputable_reference",
        displayLatex: "\\Delta\\lambda=\\mathrm{context}(T,P,B,v_{rot},\\Gamma,\\mathrm{instrument})",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["T_K", "P_Pa", "B_T", "v_rot_m_s", "instrument_response"],
        outputSymbols: ["delta_lambda_context"],
      },
    ],
    units: [
      { symbol: "T_K", unit: "K", quantity: "temperature", dimensionSignature: "Theta" },
      { symbol: "P_Pa", unit: "Pa", quantity: "pressure", dimensionSignature: "M L^-1 T^-2" },
      { symbol: "B_T", unit: "T", quantity: "magnetic_field", dimensionSignature: "M T^-2 I^-1" },
    ],
    assumptions: [
      ...commonAssumptions,
      "Line broadening is a model context for physical conditions and instrument response; it is not a formation-pathway proof.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      literatureRef("Rybicki-Lightman-Radiative-Processes-in-Astrophysics", "Radiative-processes reference for line formation and broadening contexts."),
      literatureRef("NIST-Atomic-Spectra-Database", "Atomic spectral-line reference data."),
    ],
    hintKeys: {
      subjects: ["spectroscopy", "line_broadening", "radiative_transfer", "observational_inference"],
      symbols: ["T_K", "P_Pa", "B_T", "v_rot_m_s", "delta_lambda_context", "instrument_response"],
      unitSignatures: ["Theta", "M L^-1 T^-2", "M T^-2 I^-1"],
      repoPaths: [],
      equationFamilies: ["line_broadening", "radiative_transfer", "instrument_response"],
      simulationOwners: ["stellar_reference", "general_physics"],
    },
  }),
  crossScaleBadge({
    id: "astrochemistry.reaction_network.rate_equation_context",
    title: "Astrochemical Rate-Equation Context",
    plainMeaning:
      "Represents molecular abundances as formation and destruction terms in an astrochemical reaction network.",
    whyItMatters:
      "It gives water and molecular-cloud prompts a rate-network bridge rather than treating element availability as molecule formation.",
    subjects: ["astrochemistry", "reaction_network", "water", "molecular_cloud", "rate_equation"],
    level: "model",
    status: "canonical_reference",
    simulationOwners: ["astrochemistry_prebiotic", "stellar_reference"],
    equationFamilies: ["astrochemical_reaction_network", "rate_equation", "water_chemistry_context"],
    tags: ["reaction_network", "water_context", "formation_destruction", "claim_boundary"],
    equations: [
      {
        id: "astrochemical_rate_equation_context",
        role: "noncomputable_reference",
        displayLatex: "\\frac{dn_i}{dt}=\\sum_j k_j\\prod_m n_m-\\sum_l k_l n_i\\prod_q n_q",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["n_i", "k_j", "n_m", "k_l", "n_q"],
        outputSymbols: ["dn_i_dt"],
      },
    ],
    units: [
      { symbol: "n_i", unit: "1/m^3", quantity: "species_number_density", dimensionSignature: "L^-3" },
      { symbol: "dn_i_dt", unit: "1/(m^3 s)", quantity: "abundance_rate", dimensionSignature: "L^-3 T^-1" },
    ],
    assumptions: [
      ...commonAssumptions,
      "Reaction networks require admitted rate coefficients, physical conditions, shielding, and initial abundances.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      literatureRef("doi:10.1146/annurev-astro-082708-101654", "Herbst and van Dishoeck astrochemical reaction-network review."),
      literatureRef("doi:10.1021/cr4003177", "van Dishoeck, Herbst, and Neufeld interstellar water chemistry review."),
    ],
    hintKeys: {
      subjects: ["astrochemistry", "reaction_network", "water", "molecular_cloud", "rate_equation"],
      symbols: ["n_i", "k_j", "n_m", "k_l", "n_q", "dn_i_dt"],
      unitSignatures: ["L^-3", "L^-3 T^-1"],
      repoPaths: [],
      equationFamilies: ["astrochemical_reaction_network", "rate_equation", "water_chemistry_context"],
      simulationOwners: ["astrochemistry_prebiotic", "stellar_reference"],
    },
  }),
  crossScaleBadge({
    id: "astrochemistry.reaction_network.photodissociation_context",
    title: "Photodissociation And Shielding Context",
    plainMeaning:
      "Represents UV photodissociation, dust shielding, and self-shielding as molecular survival context.",
    whyItMatters:
      "It keeps water or molecular-band claims conditioned on the environment that can destroy as well as form molecules.",
    subjects: ["astrochemistry", "photodissociation", "shielding", "molecular_cloud", "water"],
    level: "model",
    status: "canonical_reference",
    simulationOwners: ["astrochemistry_prebiotic", "stellar_reference"],
    equationFamilies: ["photodissociation", "shielding", "molecular_survival"],
    tags: ["photodissociation", "shielding", "water_context", "claim_boundary"],
    equations: [
      {
        id: "photodissociation_shielding_context",
        role: "noncomputable_reference",
        displayLatex: "k_{pd}=k_0\\,G_0\\,e^{-\\gamma A_V}\\,f_{shield}",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["k0_s_inv", "G0", "A_V", "gamma", "f_shield"],
        outputSymbols: ["k_pd_s_inv"],
      },
    ],
    units: [
      { symbol: "k0_s_inv", unit: "1/s", quantity: "unshielded_photodissociation_rate", dimensionSignature: "T^-1" },
      { symbol: "k_pd_s_inv", unit: "1/s", quantity: "shielded_photodissociation_rate", dimensionSignature: "T^-1" },
      { symbol: "A_V", unit: "mag", quantity: "visual_extinction", dimensionSignature: "1" },
    ],
    assumptions: [
      ...commonAssumptions,
      "Molecular survival depends on radiation field, shielding, density, temperature, and reaction partners.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      literatureRef("doi:10.1103/RevModPhys.71.173", "Hollenbach and Tielens photodissociation-region review."),
      literatureRef("doi:10.1021/cr4003177", "Interstellar water chemistry and destruction/survival context."),
    ],
    hintKeys: {
      subjects: ["astrochemistry", "photodissociation", "shielding", "molecular_cloud", "water"],
      symbols: ["k0_s_inv", "G0", "A_V", "gamma", "f_shield", "k_pd_s_inv"],
      unitSignatures: ["T^-1", "1"],
      repoPaths: [],
      equationFamilies: ["photodissociation", "shielding", "molecular_survival"],
      simulationOwners: ["astrochemistry_prebiotic", "stellar_reference"],
    },
  }),
  crossScaleBadge({
    id: "thermodynamics.phase.free_energy_minimization_context",
    title: "Free-Energy Phase-Selection Context",
    plainMeaning:
      "Represents phase selection as minimization of the appropriate thermodynamic potential under declared constraints.",
    whyItMatters:
      "It gives phase badges a first-principles thermodynamic decision rule without pretending scalar temperature and pressure alone determine structure.",
    subjects: ["thermodynamics", "phase", "free_energy", "equilibrium", "state_selection"],
    level: "law",
    status: "canonical_reference",
    simulationOwners: ["general_physics"],
    equationFamilies: ["free_energy_minimization", "phase_equilibrium", "thermodynamic_potential"],
    tags: ["free_energy", "phase_selection", "equilibrium", "claim_boundary"],
    equations: [
      {
        id: "phase_free_energy_selection_context",
        role: "constraint",
        displayLatex: "\\alpha_{eq}=\\arg\\min_{\\alpha}G(T,P,N_i,\\alpha)",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["T_K", "P_Pa", "N_i", "phase_alpha"],
        outputSymbols: ["alpha_eq"],
      },
    ],
    units: [
      { symbol: "G", unit: "J", quantity: "gibbs_free_energy", dimensionSignature: "M L^2 T^-2" },
      { symbol: "T_K", unit: "K", quantity: "temperature", dimensionSignature: "Theta" },
      { symbol: "P_Pa", unit: "Pa", quantity: "pressure", dimensionSignature: "M L^-1 T^-2" },
    ],
    assumptions: [
      ...commonAssumptions,
      "Equilibrium phase selection requires the correct potential, constraints, composition, and validity range.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      literatureRef("doi:10.1103/PhysRev.37.405", "Onsager reciprocal-relations foundation for irreversible thermodynamics context."),
      literatureRef("doi:10.1103/PhysRev.38.2265", "Onsager second paper on reciprocal relations."),
      literatureRef("Gibbs-Phase-Rule-DoITPoMS", "Gibbs phase rule educational reference for phase degrees of freedom."),
    ],
    hintKeys: {
      subjects: ["thermodynamics", "phase", "free_energy", "equilibrium", "state_selection"],
      symbols: ["G", "T_K", "P_Pa", "N_i", "phase_alpha", "alpha_eq"],
      unitSignatures: ["M L^2 T^-2", "Theta", "M L^-1 T^-2"],
      repoPaths: [],
      equationFamilies: ["free_energy_minimization", "phase_equilibrium", "thermodynamic_potential"],
      simulationOwners: ["general_physics"],
    },
  }),
  crossScaleBadge({
    id: "thermodynamics.phase.equation_of_state_context",
    title: "Equation-Of-State Validity Context",
    plainMeaning:
      "Represents an equation of state as a validity-bounded map from thermodynamic variables to density or related material properties.",
    whyItMatters:
      "It adds a guardrail between density, phase, and calculator traces so EOS use stays inside model boundaries.",
    subjects: ["thermodynamics", "phase", "equation_of_state", "density", "validity_range"],
    level: "model",
    status: "canonical_reference",
    simulationOwners: ["general_physics", "astrochemistry_prebiotic"],
    equationFamilies: ["equation_of_state", "density_context", "validity_boundary"],
    tags: ["equation_of_state", "density", "validity_range", "claim_boundary"],
    equations: [
      {
        id: "eos_validity_context",
        role: "noncomputable_reference",
        displayLatex: "\\rho=\\rho(T,P,x_i;\\mathrm{EOS})\\quad \\mathrm{inside\\ validity\\ range}",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["T_K", "P_Pa", "x_i", "eos_model"],
        outputSymbols: ["rho_m_kg_m3"],
      },
    ],
    units: [
      { symbol: "rho_m_kg_m3", unit: "kg/m^3", quantity: "mass_density", dimensionSignature: "M L^-3" },
      { symbol: "T_K", unit: "K", quantity: "temperature", dimensionSignature: "Theta" },
      { symbol: "P_Pa", unit: "Pa", quantity: "pressure", dimensionSignature: "M L^-1 T^-2" },
    ],
    assumptions: [
      ...commonAssumptions,
      "EOS context requires named material, composition, phase region, and declared validity limits.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      literatureRef("Gibbs-Phase-Rule-DoITPoMS", "Phase degrees-of-freedom context for EOS use."),
      literatureRef("doi:10.1063/1.1461829", "IAPWS-95 water EOS precedent already used by phase badges."),
    ],
    hintKeys: {
      subjects: ["thermodynamics", "phase", "equation_of_state", "density", "validity_range"],
      symbols: ["rho_m_kg_m3", "T_K", "P_Pa", "x_i", "eos_model"],
      unitSignatures: ["M L^-3", "Theta", "M L^-1 T^-2"],
      repoPaths: [],
      equationFamilies: ["equation_of_state", "density_context", "validity_boundary"],
      simulationOwners: ["general_physics", "astrochemistry_prebiotic"],
    },
  }),
  crossScaleBadge({
    id: "quantum.open_system.lindblad_master_equation_context",
    title: "Lindblad Open-System Context",
    plainMeaning:
      "Represents Markovian open quantum dynamics through a density-matrix master-equation form.",
    whyItMatters:
      "It gives time-crystal, polariton, and decoherence prompts a formal bridge for drive, dissipation, loss, and noise.",
    subjects: ["quantum", "open_system", "lindblad", "decoherence", "time_crystal"],
    level: "law",
    status: "canonical_reference",
    simulationOwners: ["general_physics"],
    equationFamilies: ["lindblad_master_equation", "open_quantum_system", "decoherence"],
    tags: ["lindblad", "open_system", "decoherence", "noncomputable_reference"],
    equations: [
      {
        id: "lindblad_master_equation_context",
        role: "law",
        displayLatex: "\\dot{\\rho}=-\\frac{i}{\\hbar}[H,\\rho]+\\sum_k\\left(L_k\\rho L_k^\\dagger-\\frac{1}{2}\\{L_k^\\dagger L_k,\\rho\\}\\right)",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["rho_density_matrix", "H", "L_k"],
        outputSymbols: ["rho_dot"],
      },
    ],
    units: [
      { symbol: "rho_density_matrix", unit: null, quantity: "density_matrix", dimensionSignature: "1" },
      { symbol: "H", unit: "J", quantity: "hamiltonian", dimensionSignature: "M L^2 T^-2" },
      { symbol: "L_k", unit: "mixed", quantity: "jump_operator", dimensionSignature: "mixed" },
    ],
    assumptions: [
      ...commonAssumptions,
      "The Lindblad form assumes a Markovian completely positive trace-preserving open-system model.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      literatureRef("doi:10.1007/BF01608499", "Lindblad generator of quantum dynamical semigroups."),
      literatureRef("doi:10.1063/1.522979", "Gorini, Kossakowski, and Sudarshan completely positive semigroup reference."),
    ],
    hintKeys: {
      subjects: ["quantum", "open_system", "lindblad", "decoherence", "time_crystal"],
      symbols: ["rho_density_matrix", "H", "L_k", "rho_dot"],
      unitSignatures: ["1", "M L^2 T^-2", "mixed"],
      repoPaths: [],
      equationFamilies: ["lindblad_master_equation", "open_quantum_system", "decoherence"],
      simulationOwners: ["general_physics"],
    },
  }),
  crossScaleBadge({
    id: "quantum.decoherence.einselection_context",
    title: "Environment-Induced Superselection Context",
    plainMeaning:
      "Represents decoherence and einselection as environment-conditioned emergence of stable pointer-state descriptions.",
    whyItMatters:
      "It gives quantum-to-classical bridge prompts a grounded boundary without saying decoherence proves classical truth or consciousness.",
    subjects: ["quantum", "decoherence", "einselection", "quantum_classical_bridge", "environment"],
    level: "model",
    status: "canonical_reference",
    simulationOwners: ["general_physics"],
    equationFamilies: ["decoherence", "einselection", "quantum_classical_bridge"],
    tags: ["decoherence", "pointer_states", "environment", "claim_boundary"],
    equations: [
      {
        id: "einselection_context",
        role: "noncomputable_reference",
        displayLatex: "\\mathrm{pointer\\ states}=\\mathrm{stable\\ states}(H_{system-env},\\mathrm{monitoring})",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["H_system_env", "environment_monitoring", "pointer_basis"],
        outputSymbols: ["einselection_context"],
      },
    ],
    units: [{ symbol: "einselection_context", unit: null, quantity: "decoherence_context", dimensionSignature: "1" }],
    assumptions: [
      ...commonAssumptions,
      "Decoherence explains loss of local interference under environmental monitoring but is not a universal claim of final classical ontology.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      literatureRef("doi:10.1103/RevModPhys.75.715", "Zurek decoherence, einselection, and quantum origins of classicality review."),
    ],
    hintKeys: {
      subjects: ["quantum", "decoherence", "einselection", "quantum_classical_bridge", "environment"],
      symbols: ["H_system_env", "environment_monitoring", "pointer_basis", "einselection_context"],
      unitSignatures: ["1"],
      repoPaths: [],
      equationFamilies: ["decoherence", "einselection", "quantum_classical_bridge"],
      simulationOwners: ["general_physics"],
    },
  }),
  crossScaleBadge({
    id: "matter.order_parameter.landau_context",
    title: "Landau Order-Parameter Context",
    plainMeaning:
      "Represents an order parameter as a symmetry-distinguishing collective variable for phases and transitions.",
    whyItMatters:
      "It gives phase, time-crystal, and synchrony prompts a bridge from microscopic dynamics to macroscopic state classification.",
    subjects: ["matter", "order_parameter", "phase_transition", "symmetry", "landau"],
    level: "model",
    status: "canonical_reference",
    simulationOwners: ["general_physics"],
    equationFamilies: ["order_parameter", "landau_theory", "phase_transition"],
    tags: ["order_parameter", "symmetry", "phase_transition", "claim_boundary"],
    equations: [
      {
        id: "landau_free_energy_context",
        role: "noncomputable_reference",
        displayLatex: "F[\\phi]=F_0+a\\phi^2+b\\phi^4+\\cdots",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["phi_order", "a", "b"],
        outputSymbols: ["F_phi_context"],
      },
    ],
    units: [{ symbol: "phi_order", unit: null, quantity: "order_parameter", dimensionSignature: "mixed" }],
    assumptions: [
      ...commonAssumptions,
      "Order parameters classify collective state changes and do not prove a specific microscopic mechanism by themselves.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      literatureRef("doi:10.1016/j.physrep.2015.01.001", "Hohenberg and Krekhov pattern-formation and non-equilibrium order review context."),
      literatureRef("doi:10.1126/science.177.4047.393", "Anderson more-is-different emergence reference."),
    ],
    hintKeys: {
      subjects: ["matter", "order_parameter", "phase_transition", "symmetry", "landau"],
      symbols: ["phi_order", "a", "b", "F_phi_context"],
      unitSignatures: ["mixed"],
      repoPaths: [],
      equationFamilies: ["order_parameter", "landau_theory", "phase_transition"],
      simulationOwners: ["general_physics"],
    },
  }),
  crossScaleBadge({
    id: "matter.symmetry_breaking.goldstone_context",
    title: "Goldstone Symmetry-Breaking Context",
    plainMeaning:
      "Represents continuous symmetry breaking as a context that can produce low-energy collective modes.",
    whyItMatters:
      "It lets the graph connect symmetry, order, and collective modes while keeping platform-specific evidence separate.",
    subjects: ["matter", "symmetry_breaking", "goldstone", "collective_mode", "order_parameter"],
    level: "law",
    status: "canonical_reference",
    simulationOwners: ["general_physics"],
    equationFamilies: ["spontaneous_symmetry_breaking", "goldstone_mode", "collective_modes"],
    tags: ["symmetry_breaking", "goldstone", "collective_modes", "claim_boundary"],
    equations: [
      {
        id: "goldstone_context",
        role: "noncomputable_reference",
        displayLatex: "\\mathrm{continuous\\ SSB}\\Rightarrow\\mathrm{gapless\\ collective\\ mode\\ context}",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["continuous_symmetry", "broken_generator", "order_parameter"],
        outputSymbols: ["goldstone_mode_context"],
      },
    ],
    units: [{ symbol: "goldstone_mode_context", unit: null, quantity: "collective_mode_context", dimensionSignature: "1" }],
    assumptions: [
      ...commonAssumptions,
      "Goldstone context requires the relevant symmetry, dimensionality, interactions, and platform assumptions.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      literatureRef("doi:10.1007/BF02812722", "Goldstone field-theory symmetry-breaking reference."),
      literatureRef("doi:10.1126/science.177.4047.393", "Anderson emergence and broken-symmetry context."),
    ],
    hintKeys: {
      subjects: ["matter", "symmetry_breaking", "goldstone", "collective_mode", "order_parameter"],
      symbols: ["continuous_symmetry", "broken_generator", "order_parameter", "goldstone_mode_context"],
      unitSignatures: ["1"],
      repoPaths: [],
      equationFamilies: ["spontaneous_symmetry_breaking", "goldstone_mode", "collective_modes"],
      simulationOwners: ["general_physics"],
    },
  }),
  crossScaleBadge({
    id: "scale.eft.rg_relevance_context",
    title: "Renormalization-Group Relevance Context",
    plainMeaning:
      "Represents scale flow and relevance as a way to classify which variables matter at a chosen resolution.",
    whyItMatters:
      "It gives the badge graph a disciplined way to carry analogies across scales without treating shared words as shared mechanisms.",
    subjects: [
      "scale",
      "renormalization_group",
      "effective_theory",
      "resolution",
      "relevance",
      "coarse_graining",
      "emergence",
    ],
    level: "model",
    status: "canonical_reference",
    simulationOwners: ["general_physics"],
    equationFamilies: ["renormalization_group", "scale_relevance", "effective_field_theory"],
    tags: [
      "renormalization_group",
      "scale_separation",
      "resolution",
      "coarse_graining",
      "emergence",
      "claim_boundary",
    ],
    equations: [
      {
        id: "rg_flow_context",
        role: "noncomputable_reference",
        displayLatex: "\\frac{dg_i}{d\\ln\\mu}=\\beta_i(g)",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["g_i", "mu_scale", "beta_i"],
        outputSymbols: ["rg_flow_context"],
      },
    ],
    units: [
      { symbol: "mu_scale", unit: "mixed", quantity: "renormalization_scale", dimensionSignature: "mixed" },
      { symbol: "g_i", unit: null, quantity: "coupling", dimensionSignature: "mixed" },
    ],
    assumptions: [
      ...commonAssumptions,
      "RG relevance is a resolution rule for models and analogies; it does not transport validation across unrelated scales.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      literatureRef("doi:10.1103/RevModPhys.47.773", "Wilson renormalization-group critical-phenomena review."),
      literatureRef("Wilson-Kogut-1974-Physics-Reports", "Wilson and Kogut renormalization-group review."),
    ],
    hintKeys: {
      subjects: [
        "scale",
        "renormalization_group",
        "effective_theory",
        "resolution",
        "relevance",
        "coarse_graining",
        "emergence",
      ],
      symbols: ["g_i", "mu_scale", "beta_i", "rg_flow_context"],
      unitSignatures: ["mixed"],
      repoPaths: [],
      equationFamilies: ["renormalization_group", "scale_relevance", "effective_field_theory"],
      simulationOwners: ["general_physics"],
    },
  }),
  crossScaleBadge({
    id: "scale.eft.effective_degrees_of_freedom_context",
    title: "Effective Degrees-Of-Freedom Context",
    plainMeaning:
      "Represents effective theory as choosing variables appropriate to a domain, energy, length, and observation scale.",
    whyItMatters:
      "It keeps the graph versatile while stopping first-principles language from flattening nuclear, atomic, molecular, phase, and cosmic scales.",
    subjects: [
      "scale",
      "effective_field_theory",
      "degrees_of_freedom",
      "model_boundary",
      "coarse_graining",
      "microscopic",
      "macroscopic",
      "effective_description",
      "emergence",
    ],
    level: "model",
    status: "canonical_reference",
    simulationOwners: ["general_physics"],
    equationFamilies: ["effective_degrees_of_freedom", "scale_separation", "model_boundary"],
    tags: [
      "effective_theory",
      "scale_separation",
      "degrees_of_freedom",
      "coarse_graining",
      "microscopic",
      "macroscopic",
      "effective_description",
      "emergence",
      "claim_boundary",
    ],
    equations: [
      {
        id: "effective_degrees_of_freedom_context",
        role: "noncomputable_reference",
        displayLatex: "\\mathrm{model}=\\mathrm{DOF}(E,L,t,\\epsilon_{target},\\mathrm{domain})",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["E_scale", "L_scale", "t_scale", "epsilon_target", "domain_context"],
        outputSymbols: ["effective_dof_context"],
      },
    ],
    units: [
      { symbol: "E_scale", unit: "J", quantity: "energy_scale", dimensionSignature: "M L^2 T^-2" },
      { symbol: "L_scale", unit: "m", quantity: "length_scale", dimensionSignature: "L" },
      { symbol: "t_scale", unit: "s", quantity: "time_scale", dimensionSignature: "T" },
    ],
    assumptions: [
      ...commonAssumptions,
      "Effective variables are model choices and must be tied to resolution, error tolerance, and admitted observables.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      literatureRef("doi:10.1016/0378-4371(79)90223-1", "Weinberg phenomenological Lagrangians and effective theory reference."),
      literatureRef("arXiv:hep-ph/0506330", "Lepage effective field theory lecture notes."),
    ],
    hintKeys: {
      subjects: [
        "scale",
        "effective_field_theory",
        "degrees_of_freedom",
        "model_boundary",
        "coarse_graining",
        "microscopic",
        "macroscopic",
        "effective_description",
        "emergence",
      ],
      symbols: ["E_scale", "L_scale", "t_scale", "epsilon_target", "domain_context", "effective_dof_context"],
      unitSignatures: ["M L^2 T^-2", "L", "T"],
      repoPaths: [],
      equationFamilies: ["effective_degrees_of_freedom", "scale_separation", "model_boundary"],
      simulationOwners: ["general_physics"],
    },
  }),
  crossScaleBadge({
    id: "evidence.uncertainty.measurement_model_context",
    title: "Measurement-Model Uncertainty Context",
    plainMeaning:
      "Represents uncertainty propagation as a measurement-model problem with inputs, covariance, calibration, and output quantities.",
    whyItMatters:
      "It gives reflection and calculator paths a way to discuss resolution and confidence without using deterministic turns as evidence.",
    subjects: ["evidence", "uncertainty", "measurement_model", "calibration", "resolution"],
    level: "model",
    status: "canonical_reference",
    simulationOwners: ["general_physics"],
    equationFamilies: ["measurement_uncertainty", "error_propagation", "evidence_resolution"],
    tags: ["uncertainty", "measurement_model", "calibration", "claim_boundary"],
    equations: [
      {
        id: "measurement_uncertainty_context",
        role: "noncomputable_reference",
        displayLatex: "u_y^2\\approx J\\Sigma_xJ^T",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["J", "Sigma_x", "measurement_model"],
        outputSymbols: ["u_y2_context"],
      },
    ],
    units: [{ symbol: "u_y2_context", unit: "mixed", quantity: "output_uncertainty_context", dimensionSignature: "mixed" }],
    assumptions: [
      ...commonAssumptions,
      "The matrix expression is kept non-computable until a matrix-capable calculator path is admitted.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      literatureRef("doi:10.59161/JCGM100-2008E", "JCGM GUM uncertainty-evaluation guide."),
    ],
    hintKeys: {
      subjects: ["evidence", "uncertainty", "measurement_model", "calibration", "resolution"],
      symbols: ["J", "Sigma_x", "measurement_model", "u_y2_context"],
      unitSignatures: ["mixed"],
      repoPaths: [],
      equationFamilies: ["measurement_uncertainty", "error_propagation", "evidence_resolution"],
      simulationOwners: ["general_physics"],
    },
  }),
  crossScaleBadge({
    id: "evidence.uncertainty.proxy_model_boundary_context",
    title: "Proxy-Model Boundary Context",
    plainMeaning:
      "Represents the boundary between a scalar proxy, a calibrated model, and an observationally supported claim.",
    whyItMatters:
      "It gives the graph a reusable guardrail for calculator payloads, sweeps, and reflection outputs.",
    subjects: ["evidence", "proxy_model", "claim_boundary", "calculator", "reflection"],
    level: "claim_boundary",
    status: "canonical_reference",
    simulationOwners: ["general_physics", "helix"],
    equationFamilies: ["proxy_model_boundary", "claim_boundary", "calculator_trace_boundary"],
    tags: ["proxy", "calculator", "uncertainty", "claim_boundary"],
    equations: [
      {
        id: "proxy_model_boundary_context",
        role: "gate",
        displayLatex: "\\mathrm{proxy}\\neq\\mathrm{calibrated\\ model}\\neq\\mathrm{validated\\ claim}",
        computableExpression: null,
        operatorKind: "gate_status",
        inputSymbols: ["proxy_value", "calibration_context", "observational_evidence"],
        outputSymbols: ["proxy_boundary_context"],
      },
    ],
    units: [{ symbol: "proxy_boundary_context", unit: null, quantity: "claim_boundary", dimensionSignature: "1" }],
    assumptions: [
      ...commonAssumptions,
      "Calculator traces may organize evidence but do not become answer authority or proof without the surrounding solver path and provenance.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      literatureRef("doi:10.59161/JCGM100-2008E", "Measurement-model and uncertainty-boundary reference."),
      literatureRef("arXiv:1809.02293", "Bayesian inference in astronomy review context."),
    ],
    hintKeys: {
      subjects: ["evidence", "proxy_model", "claim_boundary", "calculator", "reflection"],
      symbols: ["proxy_value", "calibration_context", "observational_evidence", "proxy_boundary_context"],
      unitSignatures: ["1"],
      repoPaths: [],
      equationFamilies: ["proxy_model_boundary", "claim_boundary", "calculator_trace_boundary"],
      simulationOwners: ["general_physics", "helix"],
    },
  }),
  crossScaleBadge({
    id: "astronomy.observational_inference.spectral_pipeline_context",
    title: "Spectral Observational-Inference Pipeline Context",
    plainMeaning:
      "Represents the path from calibrated spectra through line identification, modeling, uncertainty, and posterior abundance or origin hypotheses.",
    whyItMatters:
      "It gives astronomy prompts an observable-to-theory bridge while preventing a spectral match from proving an origin story.",
    subjects: ["astronomy", "observational_inference", "spectroscopy", "abundance", "posterior"],
    level: "model",
    status: "canonical_reference",
    simulationOwners: ["stellar_reference", "astrochemistry_prebiotic"],
    equationFamilies: ["observational_inference", "spectral_pipeline", "abundance_posterior"],
    tags: ["spectroscopy", "bayesian_inference", "pipeline", "claim_boundary"],
    equations: [
      {
        id: "spectral_inference_pipeline_context",
        role: "noncomputable_reference",
        displayLatex: "p(\\theta|D)\\propto p(D|\\theta,\\mathrm{model})p(\\theta)",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["D_spectrum", "theta_model", "likelihood", "prior"],
        outputSymbols: ["posterior_context"],
      },
    ],
    units: [{ symbol: "posterior_context", unit: null, quantity: "inference_context", dimensionSignature: "1" }],
    assumptions: [
      ...commonAssumptions,
      "Spectral inference needs calibration, model choice, uncertainty, degeneracy checks, and claim boundaries.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      literatureRef("doi:10.1007/s41115-025-00022-2", "Spectral synthesis and inference review context."),
      literatureRef("arXiv:1809.02293", "Bayesian inference in astronomy review."),
    ],
    hintKeys: {
      subjects: ["astronomy", "observational_inference", "spectroscopy", "abundance", "posterior"],
      symbols: ["D_spectrum", "theta_model", "likelihood", "prior", "posterior_context"],
      unitSignatures: ["1"],
      repoPaths: [],
      equationFamilies: ["observational_inference", "spectral_pipeline", "abundance_posterior"],
      simulationOwners: ["stellar_reference", "astrochemistry_prebiotic"],
    },
  }),
];

export const CROSS_SCALE_CONNECTIVE_TISSUE_THEORY_EDGES: TheoryBadgeEdgeV1[] = [
  {
    id: "tunneling_entrance_requires_s_factor_context",
    from: "physics.quantum.tunneling_fusion_entrance",
    to: "physics.nuclear.reaction.astrophysical_s_factor_context",
    relation: "requires",
    label: "Charged-particle tunneling context requires S-factor context before rate interpretation.",
    claimBoundaryNote: "A tunneling proxy is not a measured or evaluated fusion cross section.",
  },
  {
    id: "s_factor_context_requires_thermonuclear_rate_context",
    from: "physics.nuclear.reaction.astrophysical_s_factor_context",
    to: "physics.nuclear.reaction.thermonuclear_rate_context",
    relation: "requires",
    label: "Cross-section context feeds the density and velocity side of thermonuclear rate interpretation.",
    claimBoundaryNote: "The rate payload remains a reduced two-body proxy.",
  },
  {
    id: "plasma_screening_documents_thermonuclear_rate_context",
    from: "physics.nuclear.reaction.plasma_screening_context",
    to: "physics.nuclear.reaction.thermonuclear_rate_context",
    relation: "documents",
    label: "Plasma screening documents environmental corrections for stellar reaction rates.",
    claimBoundaryNote: "Screening corrections are regime-dependent and not solved by the scalar rate proxy.",
  },
  {
    id: "thermonuclear_rate_context_documents_nucleosynthesis_network",
    from: "physics.nuclear.reaction.thermonuclear_rate_context",
    to: "stellar.nucleosynthesis.reaction_network_context",
    relation: "documents",
    label: "Thermonuclear rate context documents how reaction networks receive rate inputs.",
    claimBoundaryNote: "Rate context is not an abundance-yield solution.",
  },
  {
    id: "thermonuclear_rate_context_documents_hydrogen_burning",
    from: "physics.nuclear.reaction.thermonuclear_rate_context",
    to: "nucleosynthesis.hydrogen_burning.helium_production",
    relation: "documents",
    label: "Thermonuclear rate context documents hydrogen-burning fusion conditions.",
    claimBoundaryNote: "Hydrogen burning context does not directly produce oxygen or water.",
  },
  {
    id: "nuclear_binding_energy_documents_semf_context",
    from: "physics.mass_energy.nuclear_binding_energy",
    to: "physics.nuclear.structure.semi_empirical_mass_formula_context",
    relation: "documents",
    label: "Mass-defect binding energy documents the energy-accounting side of nuclear binding systematics.",
    claimBoundaryNote: "SEMF context does not replace measured masses or isotope-specific yields.",
  },
  {
    id: "semf_context_documents_shell_magic_number_context",
    from: "physics.nuclear.structure.semi_empirical_mass_formula_context",
    to: "physics.nuclear.structure.shell_magic_number_context",
    relation: "documents",
    label: "Nuclear binding systematics document why shell closures need separate isotope-stability context.",
    claimBoundaryNote: "Nuclear shell context is not electron shell chemistry.",
  },
  {
    id: "nuclear_shell_context_documents_periodic_element_origin_h",
    from: "physics.nuclear.structure.shell_magic_number_context",
    to: "element.h.origin",
    relation: "documents",
    label: "Nuclear shell context documents bounded isotope-stability context for hydrogen.",
    claimBoundaryNote: "Shell context does not prove a specific origin path.",
  },
  {
    id: "nuclear_shell_context_documents_periodic_element_origin_o",
    from: "physics.nuclear.structure.shell_magic_number_context",
    to: "element.o.origin",
    relation: "documents",
    label: "Nuclear shell context documents bounded isotope-stability context for oxygen.",
    claimBoundaryNote: "Shell context does not prove a specific oxygen yield pathway.",
  },
  {
    id: "atomic_shell_documents_transition_probability_context",
    from: "physics.atomic.pauli_shell_structure",
    to: "physics.atomic.spectra.transition_probability_context",
    relation: "documents",
    label: "Electron shell structure documents the atomic-state side of transition probabilities.",
    claimBoundaryNote: "Shell context alone is not a spectral abundance claim.",
  },
  {
    id: "transition_probability_context_requires_line_broadening_context",
    from: "physics.atomic.spectra.transition_probability_context",
    to: "physics.atomic.spectra.line_broadening_context",
    relation: "requires",
    label: "Line-strength interpretation requires broadening and physical-condition context.",
    claimBoundaryNote: "Transition data without line-shape context is incomplete observational evidence.",
  },
  {
    id: "line_broadening_context_documents_spectral_pipeline_context",
    from: "physics.atomic.spectra.line_broadening_context",
    to: "astronomy.observational_inference.spectral_pipeline_context",
    relation: "documents",
    label: "Line broadening documents model and instrument context for spectral inference.",
    claimBoundaryNote: "A spectral match is not an origin proof.",
  },
  {
    id: "atomic_line_context_documents_spectral_pipeline_context",
    from: "stellar.spectroscopy.atomic_line_identification_context",
    to: "astronomy.observational_inference.spectral_pipeline_context",
    relation: "documents",
    label: "Atomic line identification documents the feature-matching step in spectral inference.",
    claimBoundaryNote: "Feature matching remains candidate context until modeled with uncertainty.",
  },
  {
    id: "molecular_cloud_inheritance_requires_astrochemical_rate_equations",
    from: "astrochemistry.molecular_cloud.elemental_inheritance_context",
    to: "astrochemistry.reaction_network.rate_equation_context",
    relation: "requires",
    label: "Elemental inheritance requires astrochemical rate context before molecule-abundance interpretation.",
    claimBoundaryNote: "Element inventory does not guarantee molecule formation.",
  },
  {
    id: "astrochemical_rate_equations_require_photodissociation_context",
    from: "astrochemistry.reaction_network.rate_equation_context",
    to: "astrochemistry.reaction_network.photodissociation_context",
    relation: "requires",
    label: "Molecular abundance networks require destruction and shielding context.",
    claimBoundaryNote: "Formation terms alone are not a survival or abundance claim.",
  },
  {
    id: "astrochemical_rate_equations_document_water_binding_context",
    from: "astrochemistry.reaction_network.rate_equation_context",
    to: "astrochemistry.water.h_o_binding_context",
    relation: "documents",
    label: "Astrochemical rate equations document formation and destruction routes for water context.",
    claimBoundaryNote: "Hydrogen and oxygen availability still does not guarantee water.",
  },
  {
    id: "thermodynamic_state_requires_free_energy_minimization_context",
    from: "matter.phase.thermodynamic_state_context",
    to: "thermodynamics.phase.free_energy_minimization_context",
    relation: "requires",
    label: "Thermodynamic phase state requires a potential or phase-equilibrium rule when equilibrium is claimed.",
    claimBoundaryNote: "Free-energy context is not a universal microscopic-structure solve.",
  },
  {
    id: "free_energy_minimization_requires_eos_validity_context",
    from: "thermodynamics.phase.free_energy_minimization_context",
    to: "thermodynamics.phase.equation_of_state_context",
    relation: "requires",
    label: "Phase selection and density interpretation require EOS validity context.",
    claimBoundaryNote: "EOS rows are material- and regime-bounded.",
  },
  {
    id: "eos_validity_documents_phase_density_context",
    from: "thermodynamics.phase.equation_of_state_context",
    to: "matter.phase.equation_of_state_density_context",
    relation: "documents",
    label: "EOS validity context documents density lookups and phase-density claims.",
    claimBoundaryNote: "Density context remains conditioned on composition and validity range.",
  },
  {
    id: "open_system_drive_requires_lindblad_context",
    from: "matter.phase.open_system_drive_dissipation_context",
    to: "quantum.open_system.lindblad_master_equation_context",
    relation: "requires",
    label: "Open quantum drive and dissipation claims require a formal open-system dynamics context.",
    claimBoundaryNote: "Lindblad context is formal structure, not platform validation.",
  },
  {
    id: "lindblad_context_documents_einselection_context",
    from: "quantum.open_system.lindblad_master_equation_context",
    to: "quantum.decoherence.einselection_context",
    relation: "documents",
    label: "Open-system dynamics documents the decoherence and environment-selection bridge.",
    claimBoundaryNote: "Decoherence context does not prove a final classical or consciousness claim.",
  },
  {
    id: "lindblad_context_documents_time_crystal_synchrony_margin",
    from: "quantum.open_system.lindblad_master_equation_context",
    to: "matter.time_crystal.noisy_synchrony_margin_context",
    relation: "documents",
    label: "Open-system formalism documents drive, loss, and noise terms in synchrony-margin comparisons.",
    claimBoundaryNote: "Synchrony margin remains a diagnostic proxy.",
  },
  {
    id: "structural_order_requires_landau_order_parameter_context",
    from: "matter.phase.structural_order_context",
    to: "matter.order_parameter.landau_context",
    relation: "requires",
    label: "Structural-order interpretation requires an order-parameter context when phase classification is discussed.",
    claimBoundaryNote: "An order parameter classifies state structure and does not certify mechanism.",
  },
  {
    id: "landau_order_parameter_documents_goldstone_context",
    from: "matter.order_parameter.landau_context",
    to: "matter.symmetry_breaking.goldstone_context",
    relation: "documents",
    label: "Order-parameter context documents symmetry-breaking and collective-mode interpretation.",
    claimBoundaryNote: "Goldstone context is symmetry-specific and platform-bounded.",
  },
  {
    id: "landau_order_parameter_documents_time_crystal_signature",
    from: "matter.order_parameter.landau_context",
    to: "matter.phase.time_crystal_observable_signature_context",
    relation: "documents",
    label: "Time-crystal observable signatures need an order-parameter or correlation-function interpretation.",
    claimBoundaryNote: "Observable rhythm without order-parameter evidence is not enough.",
  },
  {
    id: "rg_relevance_bounds_effective_degrees_of_freedom",
    from: "scale.eft.rg_relevance_context",
    to: "scale.eft.effective_degrees_of_freedom_context",
    relation: "bounds",
    label: "RG relevance bounds which variables belong in an effective model at a selected resolution.",
    claimBoundaryNote: "Scale relevance does not transport validation across scales.",
  },
  {
    id: "effective_dof_bounds_polariton_stc_bridge",
    from: "scale.eft.effective_degrees_of_freedom_context",
    to: "matter.time_crystal.polariton_stc_bridge_boundary",
    relation: "bounds",
    label: "Effective degrees of freedom bound analogies between polariton reservoirs, time crystals, and magnon lattices.",
    claimBoundaryNote: "Shared collective-mode language is not mechanism equivalence.",
  },
  {
    id: "effective_dof_bounds_spectral_pipeline_context",
    from: "scale.eft.effective_degrees_of_freedom_context",
    to: "astronomy.observational_inference.spectral_pipeline_context",
    relation: "bounds",
    label: "Effective-model boundaries document which observables are meaningful in a spectral inference pipeline.",
    claimBoundaryNote: "Inference pipelines remain model-dependent.",
  },
  {
    id: "measurement_model_context_documents_proxy_model_boundary",
    from: "evidence.uncertainty.measurement_model_context",
    to: "evidence.uncertainty.proxy_model_boundary_context",
    relation: "documents",
    label: "Measurement-model uncertainty documents when scalar payloads remain proxies.",
    claimBoundaryNote: "Uncertainty context prevents calculator traces from becoming proof.",
  },
  {
    id: "proxy_model_boundary_bounds_s_factor_context",
    from: "evidence.uncertainty.proxy_model_boundary_context",
    to: "physics.nuclear.reaction.astrophysical_s_factor_context",
    relation: "bounds",
    label: "Proxy boundaries constrain S-factor cross-section payload interpretation.",
    claimBoundaryNote: "The S-factor payload is not an evaluated reaction-rate table.",
  },
  {
    id: "proxy_model_boundary_bounds_time_crystal_sweep_context",
    from: "evidence.uncertainty.proxy_model_boundary_context",
    to: "matter.time_crystal.stabilized_vs_noisy_trace_context",
    relation: "bounds",
    label: "Proxy boundaries constrain stabilized-versus-noisy time-crystal trace comparisons.",
    claimBoundaryNote: "Sweep traces organize evidence and do not prove a phase by themselves.",
  },
  {
    id: "spectral_pipeline_requires_measurement_model_context",
    from: "astronomy.observational_inference.spectral_pipeline_context",
    to: "evidence.uncertainty.measurement_model_context",
    relation: "requires",
    label: "Spectral inference requires measurement-model and uncertainty context.",
    claimBoundaryNote: "Posterior abundance or origin hypotheses remain model- and data-conditioned.",
  },
  {
    id: "spectral_pipeline_documents_abundance_proxy_boundary",
    from: "astronomy.observational_inference.spectral_pipeline_context",
    to: "stellar.spectroscopy.abundance_proxy_equivalent_width",
    relation: "documents",
    label: "Spectral inference documents why equivalent width is only an abundance proxy without full modeling.",
    claimBoundaryNote: "Equivalent-width rows do not prove origin or abundance alone.",
  },
];

export function buildCrossScaleConnectiveTissueTheoryBadgesV1(): {
  badges: TheoryBadgeV1[];
  edges: TheoryBadgeEdgeV1[];
} {
  return {
    badges: CROSS_SCALE_CONNECTIVE_TISSUE_THEORY_BADGES.map((badge) => ({ ...badge })),
    edges: CROSS_SCALE_CONNECTIVE_TISSUE_THEORY_EDGES.map((edge) => ({ ...edge })),
  };
}
