import {
  type TheoryBadgeClaimBoundaryV1,
  type TheoryBadgeEdgeV1,
  type TheoryBadgeV1,
} from "../contracts/theory-badge-graph.v1";

const CURVATURE_BOUNDARY: TheoryBadgeClaimBoundaryV1 = {
  diagnosticOnly: true,
  doesValidateNHM2: false,
  validationClaimAllowed: false,
  physicalMechanismClaimAllowed: false,
  promotionAllowed: false,
};

const repoRef = (path: string, id?: string, note?: string): TheoryBadgeV1["sourceRefs"][number] => ({
  kind: "repo_module",
  path,
  id: id ?? null,
  note: note ?? null,
});

const docRef = (path: string, id?: string, note?: string): TheoryBadgeV1["sourceRefs"][number] => ({
  kind: "doc",
  path,
  id: id ?? null,
  note: note ?? null,
});

const payload = (args: {
  id: string;
  expression: string;
  displayLatex: string;
  targetVariable: string;
}): TheoryBadgeV1["calculatorPayloads"][number] => ({
  id: args.id,
  expression: args.expression,
  displayLatex: args.displayLatex,
  preferredAction: "solve_with_steps",
  targetVariable: args.targetVariable,
  setupContext: null,
});

const curvatureBadge = (badge: Omit<TheoryBadgeV1, "claimBoundary">): TheoryBadgeV1 => ({
  ...badge,
  claimBoundary: CURVATURE_BOUNDARY,
});

export const CURVATURE_COLLAPSE_THEORY_BADGES: TheoryBadgeV1[] = [
  curvatureBadge({
    id: "curvature.proxy.body_density",
    title: "Body Curvature Proxy",
    plainMeaning: "Maps mass density into a scalar curvature-unit proxy.",
    whyItMatters: "It gives curvature prompts a shared m^-2 diagnostic scale without claiming a geometry certificate.",
    subjects: ["curvature", "density", "proxy"],
    level: "derived_relation",
    status: "project_derived",
    simulationOwners: ["curvature_collapse", "warp_gr_nhm2"],
    equationFamilies: ["curvature_proxy"],
    tags: ["calculator_loadable", "kappa_body"],
    equations: [
      {
        id: "kappa_body_density",
        role: "calculator_demo",
        displayLatex: "\\kappa_{body}=\\frac{8\\pi G}{3c^2}\\rho",
        computableExpression: "kappa_body = 6.217e-27*rho_kg_m3",
        operatorKind: "scalar_expression",
        inputSymbols: ["rho_kg_m3"],
        outputSymbols: ["kappa_body"],
      },
    ],
    units: [
      { symbol: "kappa_body", unit: "m^-2", quantity: "curvature_proxy", dimensionSignature: "L^-2" },
      { symbol: "rho_kg_m3", unit: "kg/m^3", quantity: "mass_density", dimensionSignature: "M L^-3" },
    ],
    assumptions: ["Diagnostic curvature-unit proxy.", "Not a curvature-gravity certificate."],
    calculatorPayloads: [
      payload({
        id: "curvature_kappa_body_payload",
        expression: "kappa_body = 6.217e-27*rho_kg_m3",
        displayLatex: "\\kappa_{body}=\\frac{8\\pi G}{3c^2}\\rho",
        targetVariable: "kappa_body",
      }),
    ],
    sourceRefs: [
      repoRef("shared/curvature-proxy.ts", "kappa_body"),
      repoRef("client/src/physics/curvature.ts", "kappaBody"),
    ],
    hintKeys: {
      subjects: ["curvature", "density", "proxy"],
      symbols: ["kappa_body", "rho_kg_m3"],
      unitSignatures: ["L^-2", "M L^-3"],
      repoPaths: ["shared/curvature-proxy.ts", "client/src/physics/curvature.ts"],
      equationFamilies: ["curvature_proxy"],
      simulationOwners: ["curvature_collapse", "warp_gr_nhm2"],
    },
  }),
  curvatureBadge({
    id: "curvature.proxy.drive_power_flux",
    title: "Drive Curvature Proxy",
    plainMeaning: "Maps drive power over area into a reduced curvature-unit proxy.",
    whyItMatters: "It gives drive prompts a scalar comparison row before runtime/certificate interpretation.",
    subjects: ["curvature", "drive", "power_flux", "proxy"],
    level: "derived_relation",
    status: "project_derived",
    simulationOwners: ["curvature_collapse", "warp_gr_nhm2"],
    equationFamilies: ["curvature_proxy"],
    tags: ["calculator_loadable", "kappa_drive"],
    equations: [
      {
        id: "kappa_drive_power",
        role: "calculator_demo",
        displayLatex: "\\kappa_{drive}=C_{drive}\\frac{P}{A}d_{eff}g",
        computableExpression: "kappa_drive = 6.925e-52*(power_W/area_m2)*d_eff*gain",
        operatorKind: "scalar_expression",
        inputSymbols: ["power_W", "area_m2", "d_eff", "gain"],
        outputSymbols: ["kappa_drive"],
      },
    ],
    units: [
      { symbol: "kappa_drive", unit: "m^-2", quantity: "curvature_proxy", dimensionSignature: "L^-2" },
      { symbol: "power_W", unit: "W", quantity: "power", dimensionSignature: "M L^2 T^-3" },
      { symbol: "area_m2", unit: "m^2", quantity: "area", dimensionSignature: "L^2" },
    ],
    assumptions: ["Reduced drive proxy.", "Requires runtime provenance before interpretation."],
    calculatorPayloads: [
      payload({
        id: "curvature_kappa_drive_payload",
        expression: "kappa_drive = 6.925e-52*(power_W/area_m2)*d_eff*gain",
        displayLatex: "\\kappa_{drive}=C_{drive}\\frac{P}{A}d_{eff}g",
        targetVariable: "kappa_drive",
      }),
    ],
    sourceRefs: [
      repoRef("shared/curvature-proxy.ts", "kappa_drive_from_power"),
      repoRef("client/src/physics/curvature.ts", "kappaDriveFromPower"),
    ],
    hintKeys: {
      subjects: ["curvature", "drive", "power_flux", "proxy"],
      symbols: ["kappa_drive", "power_W", "area_m2", "d_eff", "gain"],
      unitSignatures: ["L^-2", "M T^-3"],
      repoPaths: ["shared/curvature-proxy.ts", "client/src/physics/curvature.ts"],
      equationFamilies: ["curvature_proxy"],
      simulationOwners: ["curvature_collapse", "warp_gr_nhm2"],
    },
  }),
  curvatureBadge({
    id: "curvature.proxy.drive_body_ratio",
    title: "Drive / Body Curvature Ratio",
    plainMeaning: "Compares drive and body curvature proxy magnitudes.",
    whyItMatters: "It gives a compact scalar diagnostic for relative proxy scale.",
    subjects: ["curvature", "ratio", "proxy"],
    level: "diagnostic_gate",
    status: "diagnostic",
    simulationOwners: ["curvature_collapse", "warp_gr_nhm2"],
    equationFamilies: ["curvature_proxy"],
    tags: ["calculator_loadable"],
    equations: [
      {
        id: "drive_body_ratio",
        role: "calculator_demo",
        displayLatex: "\\eta_\\kappa=\\kappa_{drive}/\\kappa_{body}",
        computableExpression: "eta_kappa = kappa_drive/kappa_body",
        operatorKind: "scalar_expression",
        inputSymbols: ["kappa_drive", "kappa_body"],
        outputSymbols: ["eta_kappa"],
      },
    ],
    units: [{ symbol: "eta_kappa", unit: null, quantity: "ratio", dimensionSignature: "1" }],
    assumptions: ["Proxy ratio only.", "Does not certify geometric curvature."],
    calculatorPayloads: [
      payload({
        id: "curvature_drive_body_ratio_payload",
        expression: "eta_kappa = kappa_drive/kappa_body",
        displayLatex: "\\eta_\\kappa=\\kappa_{drive}/\\kappa_{body}",
        targetVariable: "eta_kappa",
      }),
    ],
    sourceRefs: [repoRef("client/src/physics/curvature.ts", "potatoEfficiency")],
    hintKeys: {
      subjects: ["curvature", "ratio", "proxy"],
      symbols: ["eta_kappa", "kappa_drive", "kappa_body"],
      unitSignatures: ["1", "L^-2"],
      repoPaths: ["client/src/physics/curvature.ts"],
      equationFamilies: ["curvature_proxy"],
      simulationOwners: ["curvature_collapse", "warp_gr_nhm2"],
    },
  }),
  curvatureBadge({
    id: "collapse.benchmark.hazard_probability",
    title: "Collapse Benchmark Hazard",
    plainMeaning: "Computes benchmark trigger probability from timestep and timescale.",
    whyItMatters: "It exposes the deterministic collapse-benchmark cadence as scalar math.",
    subjects: ["collapse", "benchmark", "hazard"],
    level: "derived_relation",
    status: "project_derived",
    simulationOwners: ["curvature_collapse"],
    equationFamilies: ["collapse_benchmark"],
    tags: ["calculator_loadable"],
    equations: [
      {
        id: "hazard_probability",
        role: "calculator_demo",
        displayLatex: "p=1-e^{-dt/\\tau}",
        computableExpression: "p_trigger = 1 - exp(-dt_ms/tau_ms)",
        operatorKind: "scalar_expression",
        inputSymbols: ["dt_ms", "tau_ms"],
        outputSymbols: ["p_trigger"],
      },
    ],
    units: [{ symbol: "p_trigger", unit: null, quantity: "probability", dimensionSignature: "1" }],
    assumptions: ["Benchmark cadence helper.", "Not a quantum signaling model."],
    calculatorPayloads: [
      payload({
        id: "collapse_hazard_probability_payload",
        expression: "p_trigger = 1 - exp(-dt_ms/tau_ms)",
        displayLatex: "p=1-e^{-dt/\\tau}",
        targetVariable: "p_trigger",
      }),
    ],
    sourceRefs: [
      repoRef("shared/collapse-benchmark.ts", "hazardProbability"),
      docRef("docs/collapse-benchmark-backend-roadmap.md", "core-benchmark-math"),
    ],
    hintKeys: {
      subjects: ["collapse", "benchmark", "hazard"],
      symbols: ["p_trigger", "dt_ms", "tau_ms"],
      unitSignatures: ["1", "T"],
      repoPaths: ["shared/collapse-benchmark.ts", "docs/collapse-benchmark-backend-roadmap.md"],
      equationFamilies: ["collapse_benchmark"],
      simulationOwners: ["curvature_collapse"],
    },
  }),
  curvatureBadge({
    id: "collapse.benchmark.present_length",
    title: "Collapse Benchmark Present Length",
    plainMeaning: "Bounds benchmark footprint by correlation length and light-travel distance.",
    whyItMatters: "It keeps benchmark interpretation explicitly relativity bounded.",
    subjects: ["collapse", "benchmark", "causal_footprint"],
    level: "derived_relation",
    status: "project_derived",
    simulationOwners: ["curvature_collapse"],
    equationFamilies: ["collapse_benchmark"],
    tags: ["calculator_loadable"],
    equations: [
      {
        id: "present_length",
        role: "calculator_demo",
        displayLatex: "L_{present}=\\min(r_c,c\\tau)",
        computableExpression: "L_present = min(r_c_m, c*tau_ms/1000)",
        operatorKind: "scalar_expression",
        inputSymbols: ["r_c_m", "c", "tau_ms"],
        outputSymbols: ["L_present"],
      },
    ],
    units: [{ symbol: "L_present", unit: "m", quantity: "length", dimensionSignature: "L" }],
    assumptions: ["Relativity-bounded benchmark footprint.", "Requires runtime receipt for record-of-run values."],
    calculatorPayloads: [
      payload({
        id: "collapse_present_length_payload",
        expression: "L_present = min(r_c_m, c*tau_ms/1000)",
        displayLatex: "L_{present}=\\min(r_c,c\\tau)",
        targetVariable: "L_present",
      }),
    ],
    sourceRefs: [repoRef("shared/collapse-benchmark.ts", "presentLengthMeters")],
    hintKeys: {
      subjects: ["collapse", "benchmark", "causal_footprint"],
      symbols: ["L_present", "r_c_m", "c", "tau_ms"],
      unitSignatures: ["L", "T"],
      repoPaths: ["shared/collapse-benchmark.ts"],
      equationFamilies: ["collapse_benchmark"],
      simulationOwners: ["curvature_collapse"],
    },
  }),
  curvatureBadge({
    id: "collapse.benchmark.kappa_present",
    title: "Collapse Benchmark Kappa Present",
    plainMeaning: "Converts benchmark present length into a curvature-unit diagnostic.",
    whyItMatters: "It lets collapse benchmark outputs share the same m^-2 display scale as curvature proxies.",
    subjects: ["collapse", "benchmark", "curvature"],
    level: "derived_relation",
    status: "project_derived",
    simulationOwners: ["curvature_collapse"],
    equationFamilies: ["collapse_benchmark", "curvature_proxy"],
    tags: ["calculator_loadable"],
    equations: [
      {
        id: "kappa_present",
        role: "calculator_demo",
        displayLatex: "\\kappa_{present}=1/L_{present}^2",
        computableExpression: "kappa_present = 1/(L_present^2)",
        operatorKind: "scalar_expression",
        inputSymbols: ["L_present"],
        outputSymbols: ["kappa_present"],
      },
    ],
    units: [{ symbol: "kappa_present", unit: "m^-2", quantity: "curvature_diagnostic", dimensionSignature: "L^-2" }],
    assumptions: ["Curvature-unit diagnostic only.", "Not a curvature-gravity certificate."],
    calculatorPayloads: [
      payload({
        id: "collapse_kappa_present_payload",
        expression: "kappa_present = 1/(L_present^2)",
        displayLatex: "\\kappa_{present}=1/L_{present}^2",
        targetVariable: "kappa_present",
      }),
    ],
    sourceRefs: [repoRef("shared/collapse-benchmark.ts", "kappaPresentFromLength")],
    hintKeys: {
      subjects: ["collapse", "benchmark", "curvature"],
      symbols: ["kappa_present", "L_present"],
      unitSignatures: ["L^-2", "L"],
      repoPaths: ["shared/collapse-benchmark.ts"],
      equationFamilies: ["collapse_benchmark", "curvature_proxy"],
      simulationOwners: ["curvature_collapse"],
    },
  }),
  curvatureBadge({
    id: "curvature.uncertainty.margin",
    title: "Curvature Uncertainty Margin",
    plainMeaning: "Computes observed-minus-bound margin for benchmark decisions.",
    whyItMatters: "It provides a simple scalar row for uncertainty-aware gate explanations.",
    subjects: ["curvature", "uncertainty", "margin"],
    level: "diagnostic_gate",
    status: "diagnostic",
    simulationOwners: ["curvature_collapse"],
    equationFamilies: ["uncertainty_propagation"],
    tags: ["calculator_loadable"],
    equations: [
      {
        id: "uncertainty_margin",
        role: "calculator_demo",
        displayLatex: "margin=observed-bound",
        computableExpression: "margin = observed - bound",
        operatorKind: "scalar_expression",
        inputSymbols: ["observed", "bound"],
        outputSymbols: ["margin"],
      },
    ],
    units: [{ symbol: "margin", unit: null, quantity: "margin", dimensionSignature: "1" }],
    assumptions: ["Scalar gate helper.", "Unit meaning follows the bound being compared."],
    calculatorPayloads: [
      payload({
        id: "curvature_uncertainty_margin_payload",
        expression: "margin = observed - bound",
        displayLatex: "margin=observed-bound",
        targetVariable: "margin",
      }),
    ],
    sourceRefs: [repoRef("server/energy-pipeline.ts", "uncertaintyBoundPass")],
    hintKeys: {
      subjects: ["curvature", "uncertainty", "margin"],
      symbols: ["margin", "observed", "bound"],
      unitSignatures: ["1"],
      repoPaths: ["server/energy-pipeline.ts"],
      equationFamilies: ["uncertainty_propagation"],
      simulationOwners: ["curvature_collapse"],
    },
  }),
  curvatureBadge({
    id: "curvature.uncertainty.z_score",
    title: "Curvature Uncertainty Z Score",
    plainMeaning: "Normalizes an observed-bound margin by an uncertainty scale.",
    whyItMatters: "It gives Helix Ask a scalar way to explain how far a diagnostic is from a bound.",
    subjects: ["curvature", "uncertainty", "z_score"],
    level: "diagnostic_gate",
    status: "diagnostic",
    simulationOwners: ["curvature_collapse"],
    equationFamilies: ["uncertainty_propagation"],
    tags: ["calculator_loadable"],
    equations: [
      {
        id: "uncertainty_z_score",
        role: "calculator_demo",
        displayLatex: "z=\\frac{|observed-bound|}{\\sigma}",
        computableExpression: "z_score = abs(observed - bound)/sigma",
        operatorKind: "scalar_expression",
        inputSymbols: ["observed", "bound", "sigma"],
        outputSymbols: ["z_score"],
      },
    ],
    units: [{ symbol: "z_score", unit: null, quantity: "normalized_margin", dimensionSignature: "1" }],
    assumptions: ["Assumes sigma is commensurate with observed and bound.", "Diagnostic only."],
    calculatorPayloads: [
      payload({
        id: "curvature_uncertainty_z_score_payload",
        expression: "z_score = abs(observed - bound)/sigma",
        displayLatex: "z=\\frac{|observed-bound|}{\\sigma}",
        targetVariable: "z_score",
      }),
    ],
    sourceRefs: [repoRef("server/energy-pipeline.ts", "uncertaintyRelativeBound")],
    hintKeys: {
      subjects: ["curvature", "uncertainty", "z_score"],
      symbols: ["z_score", "observed", "bound", "sigma"],
      unitSignatures: ["1"],
      repoPaths: ["server/energy-pipeline.ts"],
      equationFamilies: ["uncertainty_propagation"],
      simulationOwners: ["curvature_collapse"],
    },
  }),
  curvatureBadge({
    id: "collapse.runtime.benchmark_route",
    title: "Collapse Benchmark Runtime",
    plainMeaning: "Reference node for the backend collapse benchmark route and deterministic report flow.",
    whyItMatters: "It keeps full benchmark execution in backend receipt space rather than scalar calculator rows.",
    subjects: ["collapse", "runtime", "benchmark"],
    level: "diagnostic_gate",
    status: "diagnostic",
    simulationOwners: ["curvature_collapse"],
    equationFamilies: ["collapse_benchmark"],
    tags: ["runtime_reference"],
    equations: [
      {
        id: "collapse_runtime_reference",
        role: "noncomputable_reference",
        displayLatex: "collapse\\_benchmark=runtime(dt,\\tau,r_c,lattice)",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["dt_ms", "tau_ms", "r_c_m", "lattice"],
        outputSymbols: ["collapse_benchmark_receipt"],
      },
    ],
    units: [],
    assumptions: ["Runtime receipt required.", "Benchmark route is diagnostic and deterministic under fixed inputs."],
    calculatorPayloads: [],
    sourceRefs: [
      repoRef("server/routes/benchmarks.collapse.ts", "POST /api/benchmarks/collapse"),
      repoRef("server/services/collapse-benchmark.ts", "runCollapseBenchmark"),
    ],
    hintKeys: {
      subjects: ["collapse", "runtime", "benchmark"],
      symbols: ["collapse_benchmark_receipt", "dt_ms", "tau_ms", "r_c_m"],
      unitSignatures: ["T", "L"],
      repoPaths: ["server/routes/benchmarks.collapse.ts", "server/services/collapse-benchmark.ts"],
      equationFamilies: ["collapse_benchmark"],
      simulationOwners: ["curvature_collapse"],
    },
  }),
  curvatureBadge({
    id: "curvature.runtime.leverage_benchmark",
    title: "Curvature Leverage Benchmark Runtime",
    plainMeaning: "Reference node for curvature leverage benchmark scripts and reports.",
    whyItMatters: "It points prompts to repeatable benchmark receipts without treating calculator rows as records of execution.",
    subjects: ["curvature", "runtime", "benchmark"],
    level: "diagnostic_gate",
    status: "diagnostic",
    simulationOwners: ["curvature_collapse"],
    equationFamilies: ["curvature_benchmark"],
    tags: ["runtime_reference"],
    equations: [
      {
        id: "curvature_leverage_reference",
        role: "noncomputable_reference",
        displayLatex: "curvature\\_leverage=benchmark\\_receipt",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["benchmark_manifest"],
        outputSymbols: ["curvature_report"],
      },
    ],
    units: [],
    assumptions: ["Runtime/script receipt required.", "Benchmark summaries are diagnostics."],
    calculatorPayloads: [],
    sourceRefs: [repoRef("scripts/curvature-leverage-benchmark-ladder.ts", "benchmark ladder")],
    hintKeys: {
      subjects: ["curvature", "runtime", "benchmark"],
      symbols: ["curvature_report", "benchmark_manifest"],
      unitSignatures: ["L^-2"],
      repoPaths: ["scripts/curvature-leverage-benchmark-ladder.ts"],
      equationFamilies: ["curvature_benchmark"],
      simulationOwners: ["curvature_collapse"],
    },
  }),
  curvatureBadge({
    id: "curvature.claim_boundary.benchmark_only",
    title: "Curvature / Collapse Benchmark Boundary",
    plainMeaning: "Keeps curvature proxy and collapse benchmark rows in diagnostic scope.",
    whyItMatters: "It blocks UI and agent language from treating scalar rows as physics validation or mechanism confirmation.",
    subjects: ["curvature", "collapse", "claim_boundary"],
    level: "claim_boundary",
    status: "blocked",
    simulationOwners: ["curvature_collapse"],
    equationFamilies: ["curvature_claim_boundary"],
    tags: ["claim_boundary"],
    equations: [
      {
        id: "curvature_boundary_reference",
        role: "noncomputable_reference",
        displayLatex: "\\mathrm{benchmark\\ diagnostics\\ only}",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: [],
        outputSymbols: ["claim_boundary"],
      },
    ],
    units: [],
    assumptions: [
      "Calculator rows are proxy diagnostics.",
      "Collapse benchmark rows are commit/selection benchmark helpers.",
      "Runtime receipts and verification gates are required before stronger interpretation.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      docRef("docs/collapse-benchmark-backend-roadmap.md", "relativity-safe-boundary"),
      repoRef("shared/collapse-benchmark.ts", "Collapse benchmark terminology"),
    ],
    hintKeys: {
      subjects: ["curvature", "collapse", "claim_boundary"],
      symbols: ["claim_boundary"],
      unitSignatures: [],
      repoPaths: ["docs/collapse-benchmark-backend-roadmap.md", "shared/collapse-benchmark.ts"],
      equationFamilies: ["curvature_claim_boundary"],
      simulationOwners: ["curvature_collapse"],
    },
  }),
];

export const CURVATURE_COLLAPSE_THEORY_EDGES: TheoryBadgeEdgeV1[] = [
  {
    id: "curvature_body_ratio_input",
    from: "curvature.proxy.body_density",
    to: "curvature.proxy.drive_body_ratio",
    relation: "requires",
    label: "Drive/body ratio requires body curvature proxy.",
    claimBoundaryNote: "Ratio is diagnostic only.",
  },
  {
    id: "curvature_drive_ratio_input",
    from: "curvature.proxy.drive_power_flux",
    to: "curvature.proxy.drive_body_ratio",
    relation: "requires",
    label: "Drive/body ratio requires drive curvature proxy.",
    claimBoundaryNote: "Ratio is diagnostic only.",
  },
  {
    id: "collapse_hazard_to_runtime",
    from: "collapse.benchmark.hazard_probability",
    to: "collapse.runtime.benchmark_route",
    relation: "documents",
    label: "Hazard probability documents benchmark cadence.",
    claimBoundaryNote: "Runtime receipt required for record-of-run.",
  },
  {
    id: "collapse_present_length_to_kappa",
    from: "collapse.benchmark.present_length",
    to: "collapse.benchmark.kappa_present",
    relation: "derives",
    label: "Present length feeds curvature-unit diagnostic.",
    claimBoundaryNote: "Curvature-unit diagnostic only.",
  },
  {
    id: "collapse_kappa_to_runtime",
    from: "collapse.benchmark.kappa_present",
    to: "collapse.runtime.benchmark_route",
    relation: "documents",
    label: "Kappa present is emitted by benchmark diagnostics.",
    claimBoundaryNote: "Runtime receipt required for record-of-run.",
  },
  {
    id: "curvature_margin_to_z_score",
    from: "curvature.uncertainty.margin",
    to: "curvature.uncertainty.z_score",
    relation: "requires",
    label: "Normalized uncertainty uses observed-bound margin context.",
    claimBoundaryNote: "Uncertainty row is diagnostic.",
  },
  {
    id: "curvature_proxy_documents_benchmark",
    from: "curvature.proxy.drive_body_ratio",
    to: "curvature.runtime.leverage_benchmark",
    relation: "documents",
    label: "Curvature proxy ratios document leverage benchmark context.",
    claimBoundaryNote: "Benchmark receipts are required for records.",
  },
  {
    id: "collapse_runtime_blocks_claims",
    from: "collapse.runtime.benchmark_route",
    to: "curvature.claim_boundary.benchmark_only",
    relation: "blocks",
    label: "Benchmark runtime remains diagnostic.",
    claimBoundaryNote: "No physics mechanism claim is allowed from this row.",
  },
  {
    id: "curvature_runtime_blocks_claims",
    from: "curvature.runtime.leverage_benchmark",
    to: "curvature.claim_boundary.benchmark_only",
    relation: "blocks",
    label: "Curvature benchmark remains diagnostic.",
    claimBoundaryNote: "No certificate is implied.",
  },
  {
    id: "efe_documents_curvature_proxy",
    from: "physics.gr.einstein_field_equation",
    to: "curvature.proxy.body_density",
    relation: "documents",
    label: "GR field equations provide canonical curvature context.",
    claimBoundaryNote: "Scalar proxy is not a tensor solve.",
  },
];

export function buildCurvatureCollapseTheoryBadgesV1(): {
  badges: TheoryBadgeV1[];
  edges: TheoryBadgeEdgeV1[];
} {
  return {
    badges: CURVATURE_COLLAPSE_THEORY_BADGES.map((badge) => ({ ...badge })),
    edges: CURVATURE_COLLAPSE_THEORY_EDGES.map((edge) => ({ ...edge })),
  };
}
