import {
  type TheoryBadgeClaimBoundaryV1,
  type TheoryBadgeEdgeV1,
  type TheoryBadgeV1,
} from "../contracts/theory-badge-graph.v1";

const CURVATURE_BOUNDARY: TheoryBadgeClaimBoundaryV1 = {
  diagnosticOnly: true,
  doesValidateNHM2: false,
  validationClaimAllowed: false,
  physicalMechanismClaimAllowed: false,
  promotionAllowed: false,
};

const repoRef = (path: string, id?: string, note?: string): TheoryBadgeV1["sourceRefs"][number] => ({
  kind: "repo_module",
  path,
  id: id ?? null,
  note: note ?? null,
});

const docRef = (path: string, id?: string, note?: string): TheoryBadgeV1["sourceRefs"][number] => ({
  kind: "doc",
  path,
  id: id ?? null,
  note: note ?? null,
});

const payload = (args: {
  id: string;
  expression: string;
  displayLatex: string;
  targetVariable: string;
}): TheoryBadgeV1["calculatorPayloads"][number] => ({
  id: args.id,
  expression: args.expression,
  displayLatex: args.displayLatex,
  preferredAction: "solve_with_steps",
  targetVariable: args.targetVariable,
  setupContext: null,
});

const curvatureBadge = (badge: Omit<TheoryBadgeV1, "claimBoundary">): TheoryBadgeV1 => ({
  ...badge,
  claimBoundary: CURVATURE_BOUNDARY,
});

export const CURVATURE_COLLAPSE_THEORY_BADGES: TheoryBadgeV1[] = [
  curvatureBadge({
    id: "curvature.proxy.body_density",
    title: "Body Curvature Proxy",
    plainMeaning: "Maps mass density into a scalar curvature-unit proxy.",
    whyItMatters: "It gives curvature prompts a shared m^-2 diagnostic scale without claiming a geometry certificate.",
    subjects: ["curvature", "density", "proxy"],
    level: "derived_relation",
    status: "project_derived",
    simulationOwners: ["curvature_collapse", "warp_gr_nhm2"],
    equationFamilies: ["curvature_proxy"],
    tags: ["calculator_loadable", "kappa_body"],
    equations: [
      {
        id: "kappa_body_density",
        role: "calculator_demo",
        displayLatex: "\\kappa_{body}=\\frac{8\\pi G}{3c^2}\\rho",
        computableExpression: "kappa_body = 6.217e-27*rho_kg_m3",
        operatorKind: "scalar_expression",
        inputSymbols: ["rho_kg_m3"],
        outputSymbols: ["kappa_body"],
      },
    ],
    units: [
      { symbol: "kappa_body", unit: "m^-2", quantity: "curvature_proxy", dimensionSignature: "L^-2" },
      { symbol: "rho_kg_m3", unit: "kg/m^3", quantity: "mass_density", dimensionSignature: "M L^-3" },
    ],
    assumptions: ["Diagnostic curvature-unit proxy.", "Not a curvature-gravity certificate."],
    calculatorPayloads: [
      payload({
        id: "curvature_kappa_body_payload",
        expression: "kappa_body = 6.217e-27*rho_kg_m3",
        displayLatex: "\\kappa_{body}=\\frac{8\\pi G}{3c^2}\\rho",
        targetVariable: "kappa_body",
      }),
    ],
    sourceRefs: [
      repoRef("shared/curvature-proxy.ts", "kappa_body"),
      repoRef("client/src/physics/curvature.ts", "kappaBody"),
    ],
    hintKeys: {
      subjects: ["curvature", "density", "proxy"],
      symbols: ["kappa_body", "rho_kg_m3"],
      unitSignatures: ["L^-2", "M L^-3"],
      repoPaths: ["shared/curvature-proxy.ts", "client/src/physics/curvature.ts"],
      equationFamilies: ["curvature_proxy"],
      simulationOwners: ["curvature_collapse", "warp_gr_nhm2"],
    },
  }),
  curvatureBadge({
    id: "curvature.proxy.drive_power_flux",
    title: "Drive Curvature Proxy",
    plainMeaning: "Maps drive power over area into a reduced curvature-unit proxy.",
    whyItMatters: "It gives drive prompts a scalar comparison row before runtime/certificate interpretation.",
    subjects: ["curvature", "drive", "power_flux", "proxy"],
    level: "derived_relation",
    status: "project_derived",
    simulationOwners: ["curvature_collapse", "warp_gr_nhm2"],
    equationFamilies: ["curvature_proxy"],
    tags: ["calculator_loadable", "kappa_drive"],
    equations: [
      {
        id: "kappa_drive_power",
        role: "calculator_demo",
        displayLatex: "\\kappa_{drive}=C_{drive}\\frac{P}{A}d_{eff}g",
        computableExpression: "kappa_drive = 6.925e-52*(power_W/area_m2)*d_eff*gain",
        operatorKind: "scalar_expression",
        inputSymbols: ["power_W", "area_m2", "d_eff", "gain"],
        outputSymbols: ["kappa_drive"],
      },
    ],
    units: [
      { symbol: "kappa_drive", unit: "m^-2", quantity: "curvature_proxy", dimensionSignature: "L^-2" },
      { symbol: "power_W", unit: "W", quantity: "power", dimensionSignature: "M L^2 T^-3" },
      { symbol: "area_m2", unit: "m^2", quantity: "area", dimensionSignature: "L^2" },
    ],
    assumptions: ["Reduced drive proxy.", "Requires runtime provenance before interpretation."],
    calculatorPayloads: [
      payload({
        id: "curvature_kappa_drive_payload",
        expression: "kappa_drive = 6.925e-52*(power_W/area_m2)*d_eff*gain",
        displayLatex: "\\kappa_{drive}=C_{drive}\\frac{P}{A}d_{eff}g",
        targetVariable: "kappa_drive",
      }),
    ],
    sourceRefs: [
      repoRef("shared/curvature-proxy.ts", "kappa_drive_from_power"),
      repoRef("client/src/physics/curvature.ts", "kappaDriveFromPower"),
    ],
    hintKeys: {
      subjects: ["curvature", "drive", "power_flux", "proxy"],
      symbols: ["kappa_drive", "power_W", "area_m2", "d_eff", "gain"],
      unitSignatures: ["L^-2", "M T^-3"],
      repoPaths: ["shared/curvature-proxy.ts", "client/src/physics/curvature.ts"],
      equationFamilies: ["curvature_proxy"],
      simulationOwners: ["curvature_collapse", "warp_gr_nhm2"],
    },
  }),
  curvatureBadge({
    id: "curvature.proxy.drive_body_ratio",
    title: "Drive / Body Curvature Ratio",
    plainMeaning: "Compares drive and body curvature proxy magnitudes.",
    whyItMatters: "It gives a compact scalar diagnostic for relative proxy scale.",
    subjects: ["curvature", "ratio", "proxy"],
    level: "diagnostic_gate",
    status: "diagnostic",
    simulationOwners: ["curvature_collapse", "warp_gr_nhm2"],
    equationFamilies: ["curvature_proxy"],
    tags: ["calculator_loadable"],
    equations: [
      {
        id: "drive_body_ratio",
        role: "calculator_demo",
        displayLatex: "\\eta_\\kappa=\\kappa_{drive}/\\kappa_{body}",
        computableExpression: "eta_kappa = kappa_drive/kappa_body",
        operatorKind: "scalar_expression",
        inputSymbols: ["kappa_drive", "kappa_body"],
        outputSymbols: ["eta_kappa"],
      },
    ],
    units: [{ symbol: "eta_kappa", unit: null, quantity: "ratio", dimensionSignature: "1" }],
    assumptions: ["Proxy ratio only.", "Does not certify geometric curvature."],
    calculatorPayloads: [
      payload({
        id: "curvature_drive_body_ratio_payload",
        expression: "eta_kappa = kappa_drive/kappa_body",
        displayLatex: "\\eta_\\kappa=\\kappa_{drive}/\\kappa_{body}",
        targetVariable: "eta_kappa",
      }),
    ],
    sourceRefs: [repoRef("client/src/physics/curvature.ts", "potatoEfficiency")],
    hintKeys: {
      subjects: ["curvature", "ratio", "proxy"],
      symbols: ["eta_kappa", "kappa_drive", "kappa_body"],
      unitSignatures: ["1", "L^-2"],
      repoPaths: ["client/src/physics/curvature.ts"],
      equationFamilies: ["curvature_proxy"],
      simulationOwners: ["curvature_collapse", "warp_gr_nhm2"],
    },
  }),
  curvatureBadge({
    id: "collapse.benchmark.hazard_probability",
    title: "Collapse Benchmark Hazard",
    plainMeaning: "Computes benchmark trigger probability from timestep and timescale.",
    whyItMatters: "It exposes the deterministic collapse-benchmark cadence as scalar math.",
    subjects: ["collapse", "benchmark", "hazard"],
    level: "derived_relation",
    status: "project_derived",
    simulationOwners: ["curvature_collapse"],
    equationFamilies: ["collapse_benchmark"],
    tags: ["calculator_loadable"],
    equations: [
      {
        id: "hazard_probability",
        role: "calculator_demo",
        displayLatex: "p=1-e^{-dt/\\tau}",
        computableExpression: "p_trigger = 1 - exp(-dt_ms/tau_ms)",
        operatorKind: "scalar_expression",
        inputSymbols: ["dt_ms", "tau_ms"],
        outputSymbols: ["p_trigger"],
      },
    ],
    units: [{ symbol: "p_trigger", unit: null, quantity: "probability", dimensionSignature: "1" }],
    assumptions: ["Benchmark cadence helper.", "Not a quantum signaling model."],
    calculatorPayloads: [
      payload({
        id: "collapse_hazard_probability_payload",
        expression: "p_trigger = 1 - exp(-dt_ms/tau_ms)",
        displayLatex: "p=1-e^{-dt/\\tau}",
        targetVariable: "p_trigger",
      }),
    ],
    sourceRefs: [
      repoRef("shared/collapse-benchmark.ts", "hazardProbability"),
      docRef("docs/collapse-benchmark-backend-roadmap.md", "core-benchmark-math"),
    ],
    hintKeys: {
      subjects: ["collapse", "benchmark", "hazard"],
      symbols: ["p_trigger", "dt_ms", "tau_ms"],
      unitSignatures: ["1", "T"],
      repoPaths: ["shared/collapse-benchmark.ts", "docs/collapse-benchmark-backend-roadmap.md"],
      equationFamilies: ["collapse_benchmark"],
      simulationOwners: ["curvature_collapse"],
    },
  }),
  curvatureBadge({
    id: "collapse.benchmark.present_length",
    title: "Collapse Benchmark Present Length",
    plainMeaning: "Bounds benchmark footprint by correlation length and light-travel distance.",
    whyItMatters: "It keeps benchmark interpretation explicitly relativity bounded.",
    subjects: ["collapse", "benchmark", "causal_footprint"],
    level: "derived_relation",
    status: "project_derived",
    simulationOwners: ["curvature_collapse"],
    equationFamilies: ["collapse_benchmark"],
    tags: ["calculator_loadable"],
    equations: [
      {
        id: "present_length",
        role: "calculator_demo",
        displayLatex: "L_{present}=\\min(r_c,c\\tau)",
        computableExpression: "L_present = min(r_c_m, c*tau_ms/1000)",
        operatorKind: "scalar_expression",
        inputSymbols: ["r_c_m", "c", "tau_ms"],
        outputSymbols: ["L_present"],
      },
    ],
    units: [{ symbol: "L_present", unit: "m", quantity: "length", dimensionSignature: "L" }],
    assumptions: ["Relativity-bounded benchmark footprint.", "Requires runtime receipt for record-of-run values."],
    calculatorPayloads: [
      payload({
        id: "collapse_present_length_payload",
        expression: "L_present = min(r_c_m, c*tau_ms/1000)",
        displayLatex: "L_{present}=\\min(r_c,c\\tau)",
        targetVariable: "L_present",
      }),
    ],
    sourceRefs: [repoRef("shared/collapse-benchmark.ts", "presentLengthMeters")],
    hintKeys: {
      subjects: ["collapse", "benchmark", "causal_footprint"],
      symbols: ["L_present", "r_c_m", "c", "tau_ms"],
      unitSignatures: ["L", "T"],
      repoPaths: ["shared/collapse-benchmark.ts"],
      equationFamilies: ["collapse_benchmark"],
      simulationOwners: ["curvature_collapse"],
    },
  }),
  curvatureBadge({
    id: "collapse.benchmark.kappa_present",
    title: "Collapse Benchmark Kappa Present",
    plainMeaning: "Converts benchmark present length into a curvature-unit diagnostic.",
    whyItMatters: "It lets collapse benchmark outputs share the same m^-2 display scale as curvature proxies.",
    subjects: ["collapse", "benchmark", "curvature"],
    level: "derived_relation",
    status: "project_derived",
    simulationOwners: ["curvature_collapse"],
    equationFamilies: ["collapse_benchmark", "curvature_proxy"],
    tags: ["calculator_loadable"],
    equations: [
      {
        id: "kappa_present",
        role: "calculator_demo",
        displayLatex: "\\kappa_{present}=1/L_{present}^2",
        computableExpression: "kappa_present = 1/(L_present^2)",
        operatorKind: "scalar_expression",
        inputSymbols: ["L_present"],
        outputSymbols: ["kappa_present"],
      },
    ],
    units: [{ symbol: "kappa_present", unit: "m^-2", quantity: "curvature_diagnostic", dimensionSignature: "L^-2" }],
    assumptions: ["Curvature-unit diagnostic only.", "Not a curvature-gravity certificate."],
    calculatorPayloads: [
      payload({
        id: "collapse_kappa_present_payload",
        expression: "kappa_present = 1/(L_present^2)",
        displayLatex: "\\kappa_{present}=1/L_{present}^2",
        targetVariable: "kappa_present",
      }),
    ],
    sourceRefs: [repoRef("shared/collapse-benchmark.ts", "kappaPresentFromLength")],
    hintKeys: {
      subjects: ["collapse", "benchmark", "curvature"],
      symbols: ["kappa_present", "L_present"],
      unitSignatures: ["L^-2", "L"],
      repoPaths: ["shared/collapse-benchmark.ts"],
      equationFamilies: ["collapse_benchmark", "curvature_proxy"],
      simulationOwners: ["curvature_collapse"],
    },
  }),
  curvatureBadge({
    id: "curvature.uncertainty.margin",
    title: "Curvature Uncertainty Margin",
    plainMeaning: "Computes observed-minus-bound margin for benchmark decisions.",
    whyItMatters: "It provides a simple scalar row for uncertainty-aware gate explanations.",
    subjects: ["curvature", "uncertainty", "margin"],
    level: "diagnostic_gate",
    status: "diagnostic",
    simulationOwners: ["curvature_collapse"],
    equationFamilies: ["uncertainty_propagation"],
    tags: ["calculator_loadable"],
    equations: [
      {
        id: "uncertainty_margin",
        role: "calculator_demo",
        displayLatex: "margin=observed-bound",
        computableExpression: "margin = observed - bound",
        operatorKind: "scalar_expression",
        inputSymbols: ["observed", "bound"],
        outputSymbols: ["margin"],
      },
    ],
    units: [{ symbol: "margin", unit: null, quantity: "margin", dimensionSignature: "1" }],
    assumptions: ["Scalar gate helper.", "Unit meaning follows the bound being compared."],
    calculatorPayloads: [
      payload({
        id: "curvature_uncertainty_margin_payload",
        expression: "margin = observed - bound",
        displayLatex: "margin=observed-bound",
        targetVariable: "margin",
      }),
    ],
    sourceRefs: [repoRef("server/energy-pipeline.ts", "uncertaintyBoundPass")],
    hintKeys: {
      subjects: ["curvature", "uncertainty", "margin"],
      symbols: ["margin", "observed", "bound"],
      unitSignatures: ["1"],
      repoPaths: ["server/energy-pipeline.ts"],
      equationFamilies: ["uncertainty_propagation"],
      simulationOwners: ["curvature_collapse"],
    },
  }),
  curvatureBadge({
    id: "curvature.uncertainty.z_score",
    title: "Curvature Uncertainty Z Score",
    plainMeaning: "Normalizes an observed-bound margin by an uncertainty scale.",
    whyItMatters: "It gives Helix Ask a scalar way to explain how far a diagnostic is from a bound.",
    subjects: ["curvature", "uncertainty", "z_score"],
    level: "diagnostic_gate",
    status: "diagnostic",
    simulationOwners: ["curvature_collapse"],
    equationFamilies: ["uncertainty_propagation"],
    tags: ["calculator_loadable"],
    equations: [
      {
        id: "uncertainty_z_score",
        role: "calculator_demo",
        displayLatex: "z=\\frac{|observed-bound|}{\\sigma}",
        computableExpression: "z_score = abs(observed - bound)/sigma",
        operatorKind: "scalar_expression",
        inputSymbols: ["observed", "bound", "sigma"],
        outputSymbols: ["z_score"],
      },
    ],
    units: [{ symbol: "z_score", unit: null, quantity: "normalized_margin", dimensionSignature: "1" }],
    assumptions: ["Assumes sigma is commensurate with observed and bound.", "Diagnostic only."],
    calculatorPayloads: [
      payload({
        id: "curvature_uncertainty_z_score_payload",
        expression: "z_score = abs(observed - bound)/sigma",
        displayLatex: "z=\\frac{|observed-bound|}{\\sigma}",
        targetVariable: "z_score",
      }),
    ],
    sourceRefs: [repoRef("server/energy-pipeline.ts", "uncertaintyRelativeBound")],
    hintKeys: {
      subjects: ["curvature", "uncertainty", "z_score"],
      symbols: ["z_score", "observed", "bound", "sigma"],
      unitSignatures: ["1"],
      repoPaths: ["server/energy-pipeline.ts"],
      equationFamilies: ["uncertainty_propagation"],
      simulationOwners: ["curvature_collapse"],
    },
  }),
  curvatureBadge({
    id: "collapse.objective.energy_frequency_period",
    title: "Objective Collapse Energy Period",
    plainMeaning: "Frames an energy scale as a frequency and period before any collapse-model interpretation.",
    whyItMatters: "It anchors objective-collapse prompts to E=hf and T=h/E before moving into model-specific timescales.",
    subjects: ["collapse", "objective_collapse", "energy", "frequency", "period"],
    level: "derived_relation",
    status: "review",
    simulationOwners: ["curvature_collapse"],
    equationFamilies: ["energy_frequency", "objective_collapse"],
    tags: ["calculator_loadable", "objective_collapse_seed"],
    equations: [
      {
        id: "energy_frequency_period",
        role: "calculator_demo",
        displayLatex: "f=E/h,\\quad T=h/E",
        computableExpression: "f_Hz = E_J/h; T_s = h/E_J",
        operatorKind: "scalar_expression",
        inputSymbols: ["E_J", "h"],
        outputSymbols: ["f_Hz", "T_s"],
      },
    ],
    units: [
      { symbol: "E_J", unit: "J", quantity: "energy", dimensionSignature: "M L^2 T^-2" },
      { symbol: "f_Hz", unit: "Hz", quantity: "frequency", dimensionSignature: "T^-1" },
      { symbol: "T_s", unit: "s", quantity: "period", dimensionSignature: "T" },
      { symbol: "h", unit: "J s", quantity: "planck_constant", dimensionSignature: "M L^2 T^-1" },
    ],
    assumptions: [
      "Energy-frequency identity only.",
      "This does not by itself identify a physical wavefunction-collapse event.",
    ],
    calculatorPayloads: [
      payload({
        id: "objective_energy_frequency_payload",
        expression: "f_Hz = E_J/h",
        displayLatex: "f=E/h",
        targetVariable: "f_Hz",
      }),
      payload({
        id: "objective_energy_period_payload",
        expression: "T_s = h/E_J",
        displayLatex: "T=h/E",
        targetVariable: "T_s",
      }),
    ],
    sourceRefs: [
      docRef("docs/architecture/orch-or-time-crystal-research-packet.md", "gravity-related-collapse-definition"),
      repoRef("shared/physics-const.ts", "Planck constants"),
    ],
    hintKeys: {
      subjects: ["collapse", "objective_collapse", "energy", "frequency", "period"],
      symbols: ["E_J", "h", "f_Hz", "T_s"],
      unitSignatures: ["M L^2 T^-2", "T^-1", "T"],
      repoPaths: ["shared/physics-const.ts", "docs/architecture/orch-or-time-crystal-research-packet.md"],
      equationFamilies: ["energy_frequency", "objective_collapse"],
      simulationOwners: ["curvature_collapse"],
    },
  }),
  curvatureBadge({
    id: "collapse.objective.mass_energy_density",
    title: "Objective Collapse Mass-Energy Density",
    plainMeaning: "Connects mass density to energy density for collapse-model branch comparisons.",
    whyItMatters: "Diosi-Penrose-style diagnostics depend on mass-density differences, so this keeps the mass-energy bridge explicit.",
    subjects: ["collapse", "objective_collapse", "mass_energy", "density"],
    level: "derived_relation",
    status: "review",
    simulationOwners: ["curvature_collapse"],
    equationFamilies: ["mass_energy", "objective_collapse"],
    tags: ["calculator_loadable", "objective_collapse_seed"],
    equations: [
      {
        id: "mass_energy_density",
        role: "calculator_demo",
        displayLatex: "u=\\rho_m c^2",
        computableExpression: "u_J_m3 = rho_kg_m3*c^2",
        operatorKind: "scalar_expression",
        inputSymbols: ["rho_kg_m3", "c"],
        outputSymbols: ["u_J_m3"],
      },
    ],
    units: [
      { symbol: "rho_kg_m3", unit: "kg/m^3", quantity: "mass_density", dimensionSignature: "M L^-3" },
      { symbol: "u_J_m3", unit: "J/m^3", quantity: "energy_density", dimensionSignature: "M L^-1 T^-2" },
    ],
    assumptions: ["Mass-energy density bridge.", "Not a collapse trigger by itself."],
    calculatorPayloads: [
      payload({
        id: "objective_mass_energy_density_payload",
        expression: "u_J_m3 = rho_kg_m3*c^2",
        displayLatex: "u=\\rho_m c^2",
        targetVariable: "u_J_m3",
      }),
    ],
    sourceRefs: [
      repoRef("shared/dp-collapse.ts", "DpMassDistribution"),
      repoRef("shared/collapse-benchmark.ts", "DpAdapterInput"),
    ],
    hintKeys: {
      subjects: ["collapse", "objective_collapse", "mass_energy", "density"],
      symbols: ["rho_kg_m3", "u_J_m3", "c"],
      unitSignatures: ["M L^-3", "M L^-1 T^-2"],
      repoPaths: ["shared/dp-collapse.ts", "shared/collapse-benchmark.ts"],
      equationFamilies: ["mass_energy", "objective_collapse"],
      simulationOwners: ["curvature_collapse"],
    },
  }),
  curvatureBadge({
    id: "collapse.objective.mass_density_branch_difference",
    title: "Objective Collapse Branch Difference",
    plainMeaning: "Represents the mass-density difference between two superposed branches.",
    whyItMatters: "The DP self-energy comparison is about branch differences, not a universal local density alone.",
    subjects: ["collapse", "objective_collapse", "mass_density", "superposition"],
    level: "model",
    status: "review",
    simulationOwners: ["curvature_collapse"],
    equationFamilies: ["dp_collapse", "objective_collapse"],
    tags: ["runtime_reference", "branch_difference"],
    equations: [
      {
        id: "mass_density_branch_difference",
        role: "noncomputable_reference",
        displayLatex: "\\Delta\\rho(\\mathbf{x})=\\rho_A(\\mathbf{x})-\\rho_B(\\mathbf{x})",
        computableExpression: null,
        operatorKind: "field_sample",
        inputSymbols: ["rho_A", "rho_B", "grid"],
        outputSymbols: ["delta_rho"],
      },
    ],
    units: [{ symbol: "delta_rho", unit: "kg/m^3", quantity: "mass_density_difference", dimensionSignature: "M L^-3" }],
    assumptions: [
      "Requires explicit branch distributions or gridded density fields.",
      "A scalar calculator row cannot replace the mass-density branch evidence.",
    ],
    calculatorPayloads: [],
    sourceRefs: [repoRef("shared/dp-collapse.ts", "DpMassDistribution")],
    hintKeys: {
      subjects: ["collapse", "objective_collapse", "mass_density", "superposition"],
      symbols: ["rho_A", "rho_B", "delta_rho", "grid"],
      unitSignatures: ["M L^-3"],
      repoPaths: ["shared/dp-collapse.ts"],
      equationFamilies: ["dp_collapse", "objective_collapse"],
      simulationOwners: ["curvature_collapse"],
    },
  }),
  curvatureBadge({
    id: "collapse.objective.dp_gravitational_self_energy",
    title: "DP Gravitational Self-Energy",
    plainMeaning: "Reference node for the gravitational self-energy difference used by Diosi-Penrose collapse diagnostics.",
    whyItMatters: "It marks the runtime-owned step between branch mass distributions and a collapse timescale.",
    subjects: ["collapse", "objective_collapse", "dp", "gravitational_self_energy"],
    level: "simulation_specific",
    status: "review",
    simulationOwners: ["curvature_collapse"],
    equationFamilies: ["dp_collapse", "objective_collapse"],
    tags: ["runtime_reference", "non_scalar"],
    equations: [
      {
        id: "dp_self_energy_reference",
        role: "noncomputable_reference",
        displayLatex: "\\Delta E_G\\sim G\\iint \\frac{\\Delta\\rho(\\mathbf{x})\\Delta\\rho(\\mathbf{y})}{|\\mathbf{x}-\\mathbf{y}|}\\,d^3x\\,d^3y",
        computableExpression: null,
        operatorKind: "region_aggregate",
        inputSymbols: ["delta_rho", "G", "r_c_m", "grid"],
        outputSymbols: ["deltaE_G_J"],
      },
    ],
    units: [{ symbol: "deltaE_G_J", unit: "J", quantity: "gravitational_self_energy_difference", dimensionSignature: "M L^2 T^-2" }],
    assumptions: [
      "Runtime or artifact receipt required.",
      "Cutoff, grid, branch provenance, and experimental-bound context must be explicit.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      repoRef("shared/dp-collapse.ts", "DpCollapseResult.deltaE_J"),
      docRef("docs/DP_COLLAPSE_DERIVATION.md", "dp_deltaE"),
      docRef("docs/architecture/orch-or-time-crystal-research-packet.md", "diosi-penrose-timescale-definition"),
    ],
    hintKeys: {
      subjects: ["collapse", "objective_collapse", "dp", "gravitational_self_energy"],
      symbols: ["deltaE_G_J", "delta_rho", "r_c_m", "G"],
      unitSignatures: ["M L^2 T^-2", "M L^-3", "L"],
      repoPaths: ["shared/dp-collapse.ts", "docs/DP_COLLAPSE_DERIVATION.md"],
      equationFamilies: ["dp_collapse", "objective_collapse"],
      simulationOwners: ["curvature_collapse"],
    },
  }),
  curvatureBadge({
    id: "collapse.objective.dp_timescale",
    title: "DP Collapse Timescale",
    plainMeaning: "Computes the exploratory DP timescale from gravitational self-energy difference.",
    whyItMatters: "It is the clean scalar bridge from a runtime self-energy receipt into a collapse-model timescale.",
    subjects: ["collapse", "objective_collapse", "dp", "timescale"],
    level: "derived_relation",
    status: "review",
    simulationOwners: ["curvature_collapse"],
    equationFamilies: ["dp_collapse", "objective_collapse"],
    tags: ["calculator_loadable", "dp_timescale"],
    equations: [
      {
        id: "dp_timescale",
        role: "calculator_demo",
        displayLatex: "\\tau_{DP}=\\hbar/\\Delta E_G",
        computableExpression: "tau_DP_s = hbar/deltaE_G_J",
        operatorKind: "scalar_expression",
        inputSymbols: ["hbar", "deltaE_G_J"],
        outputSymbols: ["tau_DP_s"],
      },
    ],
    units: [
      { symbol: "tau_DP_s", unit: "s", quantity: "collapse_timescale", dimensionSignature: "T" },
      { symbol: "deltaE_G_J", unit: "J", quantity: "gravitational_self_energy_difference", dimensionSignature: "M L^2 T^-2" },
      { symbol: "hbar", unit: "J s", quantity: "reduced_planck_constant", dimensionSignature: "M L^2 T^-1" },
    ],
    assumptions: [
      "Exploratory DP model-comparison scalar.",
      "Only meaningful when deltaE_G_J comes from a documented mass-density branch calculation.",
    ],
    calculatorPayloads: [
      payload({
        id: "objective_dp_timescale_payload",
        expression: "tau_DP_s = hbar/deltaE_G_J",
        displayLatex: "\\tau_{DP}=\\hbar/\\Delta E_G",
        targetVariable: "tau_DP_s",
      }),
      payload({
        id: "objective_dp_timescale_ms_payload",
        expression: "tau_DP_ms = 1000*hbar/deltaE_G_J",
        displayLatex: "\\tau_{DP,ms}=1000\\hbar/\\Delta E_G",
        targetVariable: "tau_DP_ms",
      }),
    ],
    sourceRefs: [
      repoRef("shared/dp-collapse.ts", "DpCollapseResult.tau_s"),
      docRef("docs/DP_COLLAPSE_DERIVATION.md", "tau_via_dp_deltaE"),
    ],
    hintKeys: {
      subjects: ["collapse", "objective_collapse", "dp", "timescale"],
      symbols: ["tau_DP_s", "tau_DP_ms", "hbar", "deltaE_G_J"],
      unitSignatures: ["T", "M L^2 T^-2"],
      repoPaths: ["shared/dp-collapse.ts", "docs/DP_COLLAPSE_DERIVATION.md"],
      equationFamilies: ["dp_collapse", "objective_collapse"],
      simulationOwners: ["curvature_collapse"],
    },
  }),
  curvatureBadge({
    id: "collapse.objective.dp_rate",
    title: "DP Collapse Rate",
    plainMeaning: "Converts the exploratory DP timescale into a rate.",
    whyItMatters: "It lets the graph represent collapse as a rate only after the model-specific timescale has been derived.",
    subjects: ["collapse", "objective_collapse", "dp", "rate"],
    level: "derived_relation",
    status: "review",
    simulationOwners: ["curvature_collapse"],
    equationFamilies: ["dp_collapse", "objective_collapse"],
    tags: ["calculator_loadable", "dp_rate"],
    equations: [
      {
        id: "dp_rate",
        role: "calculator_demo",
        displayLatex: "\\Gamma_{DP}=1/\\tau_{DP}=\\Delta E_G/\\hbar",
        computableExpression: "Gamma_DP_Hz = deltaE_G_J/hbar",
        operatorKind: "scalar_expression",
        inputSymbols: ["deltaE_G_J", "hbar"],
        outputSymbols: ["Gamma_DP_Hz"],
      },
    ],
    units: [{ symbol: "Gamma_DP_Hz", unit: "Hz", quantity: "collapse_rate", dimensionSignature: "T^-1" }],
    assumptions: ["Exploratory model rate.", "Not a measured present-moment rate without receipt evidence."],
    calculatorPayloads: [
      payload({
        id: "objective_dp_rate_payload",
        expression: "Gamma_DP_Hz = deltaE_G_J/hbar",
        displayLatex: "\\Gamma_{DP}=\\Delta E_G/\\hbar",
        targetVariable: "Gamma_DP_Hz",
      }),
    ],
    sourceRefs: [repoRef("shared/dp-collapse.ts", "DpCollapseResult")],
    hintKeys: {
      subjects: ["collapse", "objective_collapse", "dp", "rate"],
      symbols: ["Gamma_DP_Hz", "deltaE_G_J", "hbar"],
      unitSignatures: ["T^-1", "M L^2 T^-2"],
      repoPaths: ["shared/dp-collapse.ts"],
      equationFamilies: ["dp_collapse", "objective_collapse"],
      simulationOwners: ["curvature_collapse"],
    },
  }),
  curvatureBadge({
    id: "collapse.objective.experimental_bounds",
    title: "Objective Collapse Experimental Bounds",
    plainMeaning: "Reference node for experimental constraints on gravity-related and spontaneous-collapse models.",
    whyItMatters: "It prevents the graph from treating collapse-model timescales as validation when experiments only bound parameter space.",
    subjects: ["collapse", "objective_collapse", "experimental_bounds", "claim_boundary"],
    level: "diagnostic_gate",
    status: "blocked",
    simulationOwners: ["curvature_collapse"],
    equationFamilies: ["objective_collapse_bounds", "dp_collapse"],
    tags: ["claim_boundary", "experimental_bound"],
    equations: [
      {
        id: "objective_collapse_bounds_reference",
        role: "noncomputable_reference",
        displayLatex: "\\mathrm{bounds}(R_0,\\lambda,\\Delta E_G)\\neq\\mathrm{validation}",
        computableExpression: null,
        operatorKind: "gate_status",
        inputSymbols: ["experimental_bounds", "model_parameters"],
        outputSymbols: ["bound_status"],
      },
    ],
    units: [],
    assumptions: [
      "Experimental bounds constrain model parameters.",
      "Bounds do not validate physical objective collapse.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      docRef("docs/architecture/orch-or-time-crystal-research-packet.md", "collapse-bound-comparison"),
      docRef("docs/DP_COLLAPSE_DERIVATION.md", "diagnostic_not_evidence_of_physical_collapse"),
    ],
    hintKeys: {
      subjects: ["collapse", "objective_collapse", "experimental_bounds", "claim_boundary"],
      symbols: ["R0", "lambda", "bound_status", "model_parameters"],
      unitSignatures: [],
      repoPaths: ["docs/architecture/orch-or-time-crystal-research-packet.md", "docs/DP_COLLAPSE_DERIVATION.md"],
      equationFamilies: ["objective_collapse_bounds", "dp_collapse"],
      simulationOwners: ["curvature_collapse"],
    },
  }),
  curvatureBadge({
    id: "collapse.runtime.benchmark_route",
    title: "Collapse Benchmark Runtime",
    plainMeaning: "Reference node for the backend collapse benchmark route and deterministic report flow.",
    whyItMatters: "It keeps full benchmark execution in backend receipt space rather than scalar calculator rows.",
    subjects: ["collapse", "runtime", "benchmark"],
    level: "diagnostic_gate",
    status: "diagnostic",
    simulationOwners: ["curvature_collapse"],
    equationFamilies: ["collapse_benchmark"],
    tags: ["runtime_reference"],
    equations: [
      {
        id: "collapse_runtime_reference",
        role: "noncomputable_reference",
        displayLatex: "collapse\\_benchmark=runtime(dt,\\tau,r_c,lattice)",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["dt_ms", "tau_ms", "r_c_m", "lattice"],
        outputSymbols: ["collapse_benchmark_receipt"],
      },
    ],
    units: [],
    assumptions: ["Runtime receipt required.", "Benchmark route is diagnostic and deterministic under fixed inputs."],
    calculatorPayloads: [],
    sourceRefs: [
      repoRef("server/routes/benchmarks.collapse.ts", "POST /api/benchmarks/collapse"),
      repoRef("server/services/collapse-benchmark.ts", "runCollapseBenchmark"),
    ],
    hintKeys: {
      subjects: ["collapse", "runtime", "benchmark"],
      symbols: ["collapse_benchmark_receipt", "dt_ms", "tau_ms", "r_c_m"],
      unitSignatures: ["T", "L"],
      repoPaths: ["server/routes/benchmarks.collapse.ts", "server/services/collapse-benchmark.ts"],
      equationFamilies: ["collapse_benchmark"],
      simulationOwners: ["curvature_collapse"],
    },
  }),
  curvatureBadge({
    id: "curvature.runtime.leverage_benchmark",
    title: "Curvature Leverage Benchmark Runtime",
    plainMeaning: "Reference node for curvature leverage benchmark scripts and reports.",
    whyItMatters: "It points prompts to repeatable benchmark receipts without treating calculator rows as records of execution.",
    subjects: ["curvature", "runtime", "benchmark"],
    level: "diagnostic_gate",
    status: "diagnostic",
    simulationOwners: ["curvature_collapse"],
    equationFamilies: ["curvature_benchmark"],
    tags: ["runtime_reference"],
    equations: [
      {
        id: "curvature_leverage_reference",
        role: "noncomputable_reference",
        displayLatex: "curvature\\_leverage=benchmark\\_receipt",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["benchmark_manifest"],
        outputSymbols: ["curvature_report"],
      },
    ],
    units: [],
    assumptions: ["Runtime/script receipt required.", "Benchmark summaries are diagnostics."],
    calculatorPayloads: [],
    sourceRefs: [repoRef("scripts/curvature-leverage-benchmark-ladder.ts", "benchmark ladder")],
    hintKeys: {
      subjects: ["curvature", "runtime", "benchmark"],
      symbols: ["curvature_report", "benchmark_manifest"],
      unitSignatures: ["L^-2"],
      repoPaths: ["scripts/curvature-leverage-benchmark-ladder.ts"],
      equationFamilies: ["curvature_benchmark"],
      simulationOwners: ["curvature_collapse"],
    },
  }),
  curvatureBadge({
    id: "curvature.claim_boundary.benchmark_only",
    title: "Curvature / Collapse Benchmark Boundary",
    plainMeaning: "Keeps curvature proxy and collapse benchmark rows in diagnostic scope.",
    whyItMatters: "It blocks UI and agent language from treating scalar rows as physics validation or mechanism confirmation.",
    subjects: ["curvature", "collapse", "claim_boundary"],
    level: "claim_boundary",
    status: "blocked",
    simulationOwners: ["curvature_collapse"],
    equationFamilies: ["curvature_claim_boundary"],
    tags: ["claim_boundary"],
    equations: [
      {
        id: "curvature_boundary_reference",
        role: "noncomputable_reference",
        displayLatex: "\\mathrm{benchmark\\ diagnostics\\ only}",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: [],
        outputSymbols: ["claim_boundary"],
      },
    ],
    units: [],
    assumptions: [
      "Calculator rows are proxy diagnostics.",
      "Collapse benchmark rows are commit/selection benchmark helpers.",
      "Runtime receipts and verification gates are required before stronger interpretation.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      docRef("docs/collapse-benchmark-backend-roadmap.md", "relativity-safe-boundary"),
      repoRef("shared/collapse-benchmark.ts", "Collapse benchmark terminology"),
    ],
    hintKeys: {
      subjects: ["curvature", "collapse", "claim_boundary"],
      symbols: ["claim_boundary"],
      unitSignatures: [],
      repoPaths: ["docs/collapse-benchmark-backend-roadmap.md", "shared/collapse-benchmark.ts"],
      equationFamilies: ["curvature_claim_boundary"],
      simulationOwners: ["curvature_collapse"],
    },
  }),
];

export const CURVATURE_COLLAPSE_THEORY_EDGES: TheoryBadgeEdgeV1[] = [
  {
    id: "curvature_body_ratio_input",
    from: "curvature.proxy.body_density",
    to: "curvature.proxy.drive_body_ratio",
    relation: "requires",
    label: "Drive/body ratio requires body curvature proxy.",
    claimBoundaryNote: "Ratio is diagnostic only.",
  },
  {
    id: "curvature_drive_ratio_input",
    from: "curvature.proxy.drive_power_flux",
    to: "curvature.proxy.drive_body_ratio",
    relation: "requires",
    label: "Drive/body ratio requires drive curvature proxy.",
    claimBoundaryNote: "Ratio is diagnostic only.",
  },
  {
    id: "collapse_hazard_to_runtime",
    from: "collapse.benchmark.hazard_probability",
    to: "collapse.runtime.benchmark_route",
    relation: "documents",
    label: "Hazard probability documents benchmark cadence.",
    claimBoundaryNote: "Runtime receipt required for record-of-run.",
  },
  {
    id: "collapse_present_length_to_kappa",
    from: "collapse.benchmark.present_length",
    to: "collapse.benchmark.kappa_present",
    relation: "derives",
    label: "Present length feeds curvature-unit diagnostic.",
    claimBoundaryNote: "Curvature-unit diagnostic only.",
  },
  {
    id: "collapse_kappa_to_runtime",
    from: "collapse.benchmark.kappa_present",
    to: "collapse.runtime.benchmark_route",
    relation: "documents",
    label: "Kappa present is emitted by benchmark diagnostics.",
    claimBoundaryNote: "Runtime receipt required for record-of-run.",
  },
  {
    id: "curvature_margin_to_z_score",
    from: "curvature.uncertainty.margin",
    to: "curvature.uncertainty.z_score",
    relation: "requires",
    label: "Normalized uncertainty uses observed-bound margin context.",
    claimBoundaryNote: "Uncertainty row is diagnostic.",
  },
  {
    id: "quantum_energy_to_objective_period",
    from: "physics.quantum.energy_frequency",
    to: "collapse.objective.energy_frequency_period",
    relation: "derives",
    label: "Energy-frequency identity anchors objective-collapse period rows.",
    claimBoundaryNote: "Energy-frequency identity is not a collapse mechanism.",
  },
  {
    id: "mass_energy_to_objective_density",
    from: "physics.energy.energy_density",
    to: "collapse.objective.mass_energy_density",
    relation: "derives",
    label: "Mass-energy density frames branch mass distributions.",
    claimBoundaryNote: "Mass-energy density alone does not trigger collapse.",
  },
  {
    id: "objective_density_to_branch_difference",
    from: "collapse.objective.mass_energy_density",
    to: "collapse.objective.mass_density_branch_difference",
    relation: "documents",
    label: "Objective-collapse comparison requires branch density differences.",
    claimBoundaryNote: "Branch evidence must be explicit.",
  },
  {
    id: "objective_branch_to_dp_self_energy",
    from: "collapse.objective.mass_density_branch_difference",
    to: "collapse.objective.dp_gravitational_self_energy",
    relation: "requires",
    label: "DP self-energy is computed from branch mass-density differences.",
    claimBoundaryNote: "Runtime or artifact receipt required.",
  },
  {
    id: "objective_self_energy_to_timescale",
    from: "collapse.objective.dp_gravitational_self_energy",
    to: "collapse.objective.dp_timescale",
    relation: "derives",
    label: "DP timescale follows from gravitational self-energy difference.",
    claimBoundaryNote: "Timescale is exploratory model-comparison context.",
  },
  {
    id: "objective_timescale_to_rate",
    from: "collapse.objective.dp_timescale",
    to: "collapse.objective.dp_rate",
    relation: "derives",
    label: "DP rate is the inverse collapse timescale.",
    claimBoundaryNote: "Rate is not a measured present without evidence.",
  },
  {
    id: "objective_timescale_to_hazard",
    from: "collapse.objective.dp_timescale",
    to: "collapse.benchmark.hazard_probability",
    relation: "documents",
    label: "DP timescale can feed the existing benchmark hazard row.",
    claimBoundaryNote: "Benchmark hazard remains diagnostic.",
  },
  {
    id: "objective_rate_to_bounds",
    from: "collapse.objective.dp_rate",
    to: "collapse.objective.experimental_bounds",
    relation: "bounds",
    label: "Objective-collapse rates must be interpreted against experimental bounds.",
    claimBoundaryNote: "Bounds constrain; they do not validate collapse.",
  },
  {
    id: "objective_bounds_blocks_claims",
    from: "collapse.objective.experimental_bounds",
    to: "curvature.claim_boundary.benchmark_only",
    relation: "blocks",
    label: "Objective-collapse rows remain exploratory diagnostics.",
    claimBoundaryNote: "No objective-collapse proof or mechanism confirmation is allowed.",
  },
  {
    id: "curvature_proxy_documents_benchmark",
    from: "curvature.proxy.drive_body_ratio",
    to: "curvature.runtime.leverage_benchmark",
    relation: "documents",
    label: "Curvature proxy ratios document leverage benchmark context.",
    claimBoundaryNote: "Benchmark receipts are required for records.",
  },
  {
    id: "collapse_runtime_blocks_claims",
    from: "collapse.runtime.benchmark_route",
    to: "curvature.claim_boundary.benchmark_only",
    relation: "blocks",
    label: "Benchmark runtime remains diagnostic.",
    claimBoundaryNote: "No physics mechanism claim is allowed from this row.",
  },
  {
    id: "curvature_runtime_blocks_claims",
    from: "curvature.runtime.leverage_benchmark",
    to: "curvature.claim_boundary.benchmark_only",
    relation: "blocks",
    label: "Curvature benchmark remains diagnostic.",
    claimBoundaryNote: "No certificate is implied.",
  },
  {
    id: "efe_documents_curvature_proxy",
    from: "physics.gr.einstein_field_equation",
    to: "curvature.proxy.body_density",
    relation: "documents",
    label: "GR field equations provide canonical curvature context.",
    claimBoundaryNote: "Scalar proxy is not a tensor solve.",
  },
];

export function buildCurvatureCollapseTheoryBadgesV1(): {
  badges: TheoryBadgeV1[];
  edges: TheoryBadgeEdgeV1[];
} {
  return {
    badges: CURVATURE_COLLAPSE_THEORY_BADGES.map((badge) => ({ ...badge })),
    edges: CURVATURE_COLLAPSE_THEORY_EDGES.map((edge) => ({ ...edge })),
  };
}
