import {
  type TheoryBadgeClaimBoundaryV1,
  type TheoryBadgeEdgeV1,
  type TheoryBadgeV1,
} from "../contracts/theory-badge-graph.v1";

const REFERENCE_BOUNDARY: TheoryBadgeClaimBoundaryV1 = {
  diagnosticOnly: false,
  doesValidateNHM2: false,
  validationClaimAllowed: false,
  physicalMechanismClaimAllowed: false,
  promotionAllowed: false,
};

const literatureRef = (id: string, note?: string): TheoryBadgeV1["sourceRefs"][number] => ({
  kind: "literature_ref",
  id,
  note: note ?? null,
});

const calculatorPayload = (args: {
  id: string;
  expression: string;
  displayLatex: string;
  targetVariable?: string;
}): TheoryBadgeV1["calculatorPayloads"][number] => ({
  id: args.id,
  expression: args.expression,
  displayLatex: args.displayLatex,
  preferredAction: "solve_with_steps",
  targetVariable: args.targetVariable ?? null,
  setupContext: null,
});

const firstPrincipleBadge = (badge: Omit<TheoryBadgeV1, "claimBoundary">): TheoryBadgeV1 => ({
  ...badge,
  claimBoundary: REFERENCE_BOUNDARY,
});

export const FIRST_PRINCIPLES_THEORY_BADGES: TheoryBadgeV1[] = [
  firstPrincipleBadge({
    id: "physics.units.dimension_consistency",
    title: "Dimension Consistency",
    plainMeaning: "Checks that equations preserve compatible physical dimensions from input to output.",
    whyItMatters: "It is the root guardrail that keeps calculator payloads from connecting unrelated quantities.",
    subjects: ["units", "dimensions", "first_principles"],
    level: "first_principle",
    status: "canonical_reference",
    simulationOwners: ["general_physics"],
    equationFamilies: ["dimensional_analysis"],
    tags: ["units", "dimension_signature", "root"],
    equations: [
      {
        id: "dimension_input_output_match",
        role: "constraint",
        displayLatex: "[lhs]=[rhs]",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["lhs", "rhs"],
        outputSymbols: ["dimension_ok"],
      },
    ],
    units: [{ symbol: "[x]", quantity: "dimension_signature", dimensionSignature: "dimension_signature" }],
    assumptions: ["Reference rule only.", "Scalar calculator payloads still need explicit unit context."],
    calculatorPayloads: [],
    sourceRefs: [literatureRef("Dimensional analysis", "Canonical equation consistency rule.")],
    hintKeys: {
      subjects: ["units", "dimensions"],
      symbols: ["lhs", "rhs", "dimension_ok"],
      unitSignatures: ["dimension_signature"],
      repoPaths: [],
      equationFamilies: ["dimensional_analysis"],
      simulationOwners: ["general_physics"],
    },
  }),
  firstPrincipleBadge({
    id: "physics.constants.speed_of_light",
    title: "Speed of Light Constant",
    plainMeaning: "Represents c as the invariant light-speed constant used by relativity relations.",
    whyItMatters: "It is a common bridge between relativity expressions and GR source equations.",
    subjects: ["constants", "relativity", "first_principles"],
    level: "first_principle",
    status: "canonical_reference",
    simulationOwners: ["general_physics"],
    equationFamilies: ["physical_constants"],
    tags: ["c", "constant", "light_speed"],
    equations: [
      {
        id: "c_constant",
        role: "definition",
        displayLatex: "c=299792458\\,m/s",
        computableExpression: "c = 299792458",
        operatorKind: "scalar_expression",
        inputSymbols: [],
        outputSymbols: ["c"],
      },
    ],
    units: [{ symbol: "c", unit: "m/s", quantity: "speed", dimensionSignature: "L T^-1" }],
    assumptions: ["Uses the SI exact defined value of c."],
    calculatorPayloads: [
      calculatorPayload({
        id: "speed_of_light_constant_payload",
        expression: "c = 299792458",
        displayLatex: "c=299792458\\,m/s",
        targetVariable: "c",
      }),
    ],
    sourceRefs: [literatureRef("SI speed of light definition", "Exact SI constant.")],
    hintKeys: {
      subjects: ["constants", "relativity"],
      symbols: ["c"],
      unitSignatures: ["L T^-1"],
      repoPaths: [],
      equationFamilies: ["physical_constants"],
      simulationOwners: ["general_physics"],
    },
  }),
  firstPrincipleBadge({
    id: "physics.quantum.energy_frequency",
    title: "Quantum Energy-Frequency Relation",
    plainMeaning: "Relates photon-like energy to frequency through Planck's constant.",
    whyItMatters: "It gives energy-bearing quantum expressions a calculator-loadable root relation.",
    subjects: ["quantum", "energy", "first_principles"],
    level: "law",
    status: "canonical_reference",
    simulationOwners: ["general_physics"],
    equationFamilies: ["planck_relation"],
    tags: ["energy", "frequency", "planck"],
    equations: [
      {
        id: "energy_frequency",
        role: "law",
        displayLatex: "E=h f",
        computableExpression: "E = h * f",
        operatorKind: "scalar_expression",
        inputSymbols: ["h", "f"],
        outputSymbols: ["E"],
      },
    ],
    units: [
      { symbol: "E", unit: "J", quantity: "energy", dimensionSignature: "M L^2 T^-2" },
      { symbol: "f", unit: "Hz", quantity: "frequency", dimensionSignature: "T^-1" },
    ],
    assumptions: ["Scalar relation only.", "h is treated as a supplied constant in calculator runs."],
    calculatorPayloads: [
      calculatorPayload({
        id: "energy_frequency_payload",
        expression: "E = h * f",
        displayLatex: "E=h f",
        targetVariable: "E",
      }),
    ],
    sourceRefs: [literatureRef("Planck relation", "Canonical quantum reference.")],
    hintKeys: {
      subjects: ["quantum", "energy"],
      symbols: ["E", "h", "f"],
      unitSignatures: ["M L^2 T^-2", "T^-1"],
      repoPaths: [],
      equationFamilies: ["planck_relation"],
      simulationOwners: ["general_physics"],
    },
  }),
  firstPrincipleBadge({
    id: "physics.quantum.momentum_wavelength",
    title: "Momentum-Wavelength Relation",
    plainMeaning: "Relates de Broglie momentum to wavelength through Planck's constant.",
    whyItMatters: "It provides a momentum root for energy-momentum relations.",
    subjects: ["quantum", "momentum", "first_principles"],
    level: "law",
    status: "canonical_reference",
    simulationOwners: ["general_physics"],
    equationFamilies: ["de_broglie_relation"],
    tags: ["momentum", "wavelength", "planck"],
    equations: [
      {
        id: "momentum_wavelength",
        role: "law",
        displayLatex: "p=\\frac{h}{\\lambda}",
        computableExpression: "p = h / lambda",
        operatorKind: "scalar_expression",
        inputSymbols: ["h", "lambda"],
        outputSymbols: ["p"],
      },
    ],
    units: [{ symbol: "p", unit: "kg m/s", quantity: "momentum", dimensionSignature: "M L T^-1" }],
    assumptions: ["Scalar relation only.", "h is treated as a supplied constant in calculator runs."],
    calculatorPayloads: [
      calculatorPayload({
        id: "momentum_wavelength_payload",
        expression: "p = h / lambda",
        displayLatex: "p=\\frac{h}{\\lambda}",
        targetVariable: "p",
      }),
    ],
    sourceRefs: [literatureRef("de Broglie relation", "Canonical quantum reference.")],
    hintKeys: {
      subjects: ["quantum", "momentum"],
      symbols: ["p", "h", "lambda"],
      unitSignatures: ["M L T^-1"],
      repoPaths: [],
      equationFamilies: ["de_broglie_relation"],
      simulationOwners: ["general_physics"],
    },
  }),
  firstPrincipleBadge({
    id: "physics.quantum.uncertainty_position_momentum",
    title: "Position-Momentum Uncertainty",
    plainMeaning: "Represents the reference lower bound between position and momentum spread.",
    whyItMatters: "It gives quantum-limit prompts a non-scalar reference badge without pretending it is a full solve.",
    subjects: ["quantum", "uncertainty", "first_principles"],
    level: "law",
    status: "canonical_reference",
    simulationOwners: ["general_physics"],
    equationFamilies: ["uncertainty_relation"],
    tags: ["uncertainty", "bound"],
    equations: [
      {
        id: "position_momentum_uncertainty",
        role: "constraint",
        displayLatex: "\\Delta x\\Delta p\\geq\\frac{\\hbar}{2}",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["delta_x", "delta_p", "hbar"],
        outputSymbols: ["uncertainty_bound"],
      },
    ],
    units: [{ symbol: "\\Delta x\\Delta p", quantity: "action", dimensionSignature: "M L^2 T^-1" }],
    assumptions: ["Reference bound only.", "No scalar calculator payload until a numeric substitution context is supplied."],
    calculatorPayloads: [],
    sourceRefs: [literatureRef("Heisenberg uncertainty relation", "Canonical quantum reference.")],
    hintKeys: {
      subjects: ["quantum", "uncertainty"],
      symbols: ["delta_x", "delta_p", "hbar"],
      unitSignatures: ["M L^2 T^-1"],
      repoPaths: [],
      equationFamilies: ["uncertainty_relation"],
      simulationOwners: ["general_physics"],
    },
  }),
  firstPrincipleBadge({
    id: "physics.symmetry.energy_momentum_conservation",
    title: "Energy-Momentum Conservation",
    plainMeaning: "Represents conservation of the energy-momentum four-vector in symmetric settings.",
    whyItMatters: "It is an upstream guardrail for stress-energy and source consistency badges.",
    subjects: ["symmetry", "conservation", "energy", "momentum"],
    level: "law",
    status: "canonical_reference",
    simulationOwners: ["general_physics"],
    equationFamilies: ["energy_momentum_conservation"],
    tags: ["conservation", "symmetry"],
    equations: [
      {
        id: "energy_momentum_conservation",
        role: "constraint",
        displayLatex: "\\partial_{\\mu}P^{\\mu}=0",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["P_mu"],
        outputSymbols: ["div_P"],
      },
    ],
    units: [{ symbol: "P^{\\mu}", quantity: "energy_momentum", dimensionSignature: "mixed" }],
    assumptions: ["Reference conservation badge only.", "Tensor and field forms are outside scalar calculator scope."],
    calculatorPayloads: [],
    sourceRefs: [literatureRef("Noether energy-momentum conservation", "Canonical conservation reference.")],
    hintKeys: {
      subjects: ["symmetry", "conservation", "energy", "momentum"],
      symbols: ["P_mu", "div_P"],
      unitSignatures: ["mixed"],
      repoPaths: [],
      equationFamilies: ["energy_momentum_conservation"],
      simulationOwners: ["general_physics"],
    },
  }),
  firstPrincipleBadge({
    id: "physics.relativity.energy_momentum_relation",
    title: "Relativistic Energy-Momentum Relation",
    plainMeaning: "Connects total energy, momentum, mass, and c in special relativity.",
    whyItMatters: "It is a bridge from quantum momentum and c into rest-energy and energy-density badges.",
    subjects: ["relativity", "energy", "momentum"],
    level: "law",
    status: "canonical_reference",
    simulationOwners: ["general_physics"],
    equationFamilies: ["energy_momentum_relation"],
    tags: ["energy", "momentum", "mass", "c"],
    equations: [
      {
        id: "relativistic_energy_momentum",
        role: "law",
        displayLatex: "E^2=(pc)^2+(mc^2)^2",
        computableExpression: "E^2 = (p*c)^2 + (m*c^2)^2",
        operatorKind: "scalar_expression",
        inputSymbols: ["p", "c", "m"],
        outputSymbols: ["E"],
      },
    ],
    units: [{ symbol: "E", unit: "J", quantity: "energy", dimensionSignature: "M L^2 T^-2" }],
    assumptions: ["Scalar symbolic relation only.", "Calculator runs do not pick a physical branch without values."],
    calculatorPayloads: [
      calculatorPayload({
        id: "energy_momentum_relation_payload",
        expression: "E^2 = (p*c)^2 + (m*c^2)^2",
        displayLatex: "E^2=(pc)^2+(mc^2)^2",
        targetVariable: "E",
      }),
    ],
    sourceRefs: [literatureRef("Special relativity energy-momentum relation", "Canonical relativity reference.")],
    hintKeys: {
      subjects: ["relativity", "energy", "momentum"],
      symbols: ["E", "p", "c", "m"],
      unitSignatures: ["M L^2 T^-2"],
      repoPaths: [],
      equationFamilies: ["energy_momentum_relation"],
      simulationOwners: ["general_physics"],
    },
  }),
  firstPrincipleBadge({
    id: "physics.relativity.rest_energy",
    title: "Rest Energy",
    plainMeaning: "Relates rest mass to rest energy through c squared.",
    whyItMatters: "It is a major bridge badge from relativity roots into energy-density and stress-energy reasoning.",
    subjects: ["relativity", "energy", "mass"],
    level: "derived_relation",
    status: "canonical_reference",
    simulationOwners: ["general_physics"],
    equationFamilies: ["rest_energy"],
    tags: ["energy", "mass", "c"],
    equations: [
      {
        id: "rest_energy",
        role: "definition",
        displayLatex: "E_0=mc^2",
        computableExpression: "E0 = m * c^2",
        operatorKind: "scalar_expression",
        inputSymbols: ["m", "c"],
        outputSymbols: ["E0"],
      },
    ],
    units: [{ symbol: "E_0", unit: "J", quantity: "energy", dimensionSignature: "M L^2 T^-2" }],
    assumptions: ["Rest-frame scalar relation only."],
    calculatorPayloads: [
      calculatorPayload({
        id: "rest_energy_payload",
        expression: "E0 = m * c^2",
        displayLatex: "E_0=mc^2",
        targetVariable: "E0",
      }),
    ],
    sourceRefs: [literatureRef("Rest energy", "Canonical relativity reference.")],
    hintKeys: {
      subjects: ["relativity", "energy", "mass"],
      symbols: ["E0", "m", "c"],
      unitSignatures: ["M L^2 T^-2"],
      repoPaths: [],
      equationFamilies: ["rest_energy"],
      simulationOwners: ["general_physics"],
    },
  }),
  firstPrincipleBadge({
    id: "physics.energy.energy_density",
    title: "Energy Density",
    plainMeaning: "Relates an energy quantity to volume as density.",
    whyItMatters: "It directly bridges general physics into NHM2 source, QEI, and stress-energy badges.",
    subjects: ["energy", "density", "units"],
    level: "derived_relation",
    status: "canonical_reference",
    simulationOwners: ["general_physics"],
    equationFamilies: ["energy_density"],
    tags: ["energy_density", "volume", "calculator_loadable"],
    equations: [
      {
        id: "energy_density",
        role: "definition",
        displayLatex: "\\rho=\\frac{E}{V}",
        computableExpression: "rho = E / V",
        operatorKind: "scalar_expression",
        inputSymbols: ["E", "V"],
        outputSymbols: ["rho"],
      },
    ],
    units: [{ symbol: "\\rho", unit: "J/m^3", quantity: "energy_density", dimensionSignature: "M L^-1 T^-2" }],
    assumptions: ["Scalar density relation only.", "Does not select a source mechanism."],
    calculatorPayloads: [
      calculatorPayload({
        id: "energy_density_payload",
        expression: "rho = E / V",
        displayLatex: "\\rho=\\frac{E}{V}",
        targetVariable: "rho",
      }),
    ],
    sourceRefs: [literatureRef("Energy density", "Canonical scalar definition.")],
    hintKeys: {
      subjects: ["energy", "density", "units"],
      symbols: ["rho", "E", "V"],
      unitSignatures: ["M L^-1 T^-2"],
      repoPaths: [],
      equationFamilies: ["energy_density"],
      simulationOwners: ["general_physics"],
    },
  }),
  firstPrincipleBadge({
    id: "physics.energy.power_rate",
    title: "Power Rate",
    plainMeaning: "Relates energy transfer to elapsed time.",
    whyItMatters: "It anchors duty-cycle and average-power calculator payloads.",
    subjects: ["energy", "power", "time"],
    level: "derived_relation",
    status: "canonical_reference",
    simulationOwners: ["general_physics"],
    equationFamilies: ["power_rate"],
    tags: ["power", "energy", "time", "calculator_loadable"],
    equations: [
      {
        id: "power_rate",
        role: "definition",
        displayLatex: "P=\\frac{E}{t}",
        computableExpression: "P = E / t",
        operatorKind: "scalar_expression",
        inputSymbols: ["E", "t"],
        outputSymbols: ["P"],
      },
    ],
    units: [{ symbol: "P", unit: "W", quantity: "power", dimensionSignature: "M L^2 T^-3" }],
    assumptions: ["Scalar average-rate relation only."],
    calculatorPayloads: [
      calculatorPayload({
        id: "power_rate_payload",
        expression: "P = E / t",
        displayLatex: "P=\\frac{E}{t}",
        targetVariable: "P",
      }),
    ],
    sourceRefs: [literatureRef("Power definition", "Canonical scalar definition.")],
    hintKeys: {
      subjects: ["energy", "power", "time"],
      symbols: ["P", "E", "t"],
      unitSignatures: ["M L^2 T^-3"],
      repoPaths: [],
      equationFamilies: ["power_rate"],
      simulationOwners: ["general_physics"],
    },
  }),
  firstPrincipleBadge({
    id: "physics.frames.lorentz_factor",
    title: "Lorentz Factor",
    plainMeaning: "Relates relative speed to the gamma factor used by relativistic frame comparisons.",
    whyItMatters: "It gives frame and velocity prompts a calculator-loadable relativity bridge.",
    subjects: ["relativity", "frames", "velocity"],
    level: "derived_relation",
    status: "canonical_reference",
    simulationOwners: ["general_physics"],
    equationFamilies: ["lorentz_factor"],
    tags: ["gamma", "velocity", "c", "calculator_loadable"],
    equations: [
      {
        id: "lorentz_factor",
        role: "definition",
        displayLatex: "\\gamma=\\frac{1}{\\sqrt{1-v^2/c^2}}",
        computableExpression: "gamma = 1 / sqrt(1 - v^2 / c^2)",
        operatorKind: "scalar_expression",
        inputSymbols: ["v", "c"],
        outputSymbols: ["gamma"],
      },
    ],
    units: [{ symbol: "\\gamma", quantity: "lorentz_factor", dimensionSignature: "1" }],
    assumptions: ["Requires |v| < c for ordinary real-valued interpretation."],
    calculatorPayloads: [
      calculatorPayload({
        id: "lorentz_factor_payload",
        expression: "gamma = 1 / sqrt(1 - v^2 / c^2)",
        displayLatex: "\\gamma=\\frac{1}{\\sqrt{1-v^2/c^2}}",
        targetVariable: "gamma",
      }),
    ],
    sourceRefs: [literatureRef("Lorentz factor", "Canonical special relativity definition.")],
    hintKeys: {
      subjects: ["relativity", "frames", "velocity"],
      symbols: ["gamma", "v", "c"],
      unitSignatures: ["1", "L T^-1"],
      repoPaths: [],
      equationFamilies: ["lorentz_factor"],
      simulationOwners: ["general_physics"],
    },
  }),
  firstPrincipleBadge({
    id: "physics.fields.stress_energy_tensor",
    title: "Stress-Energy Tensor",
    plainMeaning: "Organizes energy density, momentum flux, and stresses as the source object used by GR.",
    whyItMatters: "It is the field bridge from scalar energy-density badges into Einstein-equation references.",
    subjects: ["fields", "stress_energy", "general_relativity"],
    level: "model",
    status: "canonical_reference",
    simulationOwners: ["general_relativity"],
    equationFamilies: ["stress_energy_tensor"],
    tags: ["stress_energy", "tensor", "source"],
    equations: [
      {
        id: "stress_energy_tensor_reference",
        role: "definition",
        displayLatex: "T_{\\mu\\nu}",
        computableExpression: null,
        operatorKind: "tensor_component",
        inputSymbols: ["rho", "pressure", "momentum_flux"],
        outputSymbols: ["T_mu_nu"],
      },
    ],
    units: [{ symbol: "T_{\\mu\\nu}", unit: "Pa", quantity: "stress_energy", dimensionSignature: "M L^-1 T^-2" }],
    assumptions: ["Tensor reference only.", "Scalar calculator payloads feed related unit signatures, not tensor solving."],
    calculatorPayloads: [],
    sourceRefs: [literatureRef("Stress-energy tensor", "Canonical GR source object.")],
    hintKeys: {
      subjects: ["fields", "stress_energy", "general_relativity"],
      symbols: ["T_mu_nu", "rho", "pressure", "momentum_flux"],
      unitSignatures: ["M L^-1 T^-2"],
      repoPaths: [],
      equationFamilies: ["stress_energy_tensor"],
      simulationOwners: ["general_relativity"],
    },
  }),
];

export const FIRST_PRINCIPLES_THEORY_EDGES: TheoryBadgeEdgeV1[] = [
  {
    id: "dimension_consistency_bounds_energy_density",
    from: "physics.units.dimension_consistency",
    to: "physics.energy.energy_density",
    relation: "bounds",
    label: "Energy density is meaningful only when dimensions agree.",
    claimBoundaryNote: "Dimensional compatibility is a guardrail, not a physical mechanism claim.",
  },
  {
    id: "speed_of_light_feeds_energy_momentum",
    from: "physics.constants.speed_of_light",
    to: "physics.relativity.energy_momentum_relation",
    relation: "uses_constant",
    label: "The relativistic energy-momentum relation uses c.",
    claimBoundaryNote: "Constant usage is a reference edge only.",
  },
  {
    id: "speed_of_light_feeds_rest_energy",
    from: "physics.constants.speed_of_light",
    to: "physics.relativity.rest_energy",
    relation: "uses_constant",
    label: "Rest energy uses c squared.",
    claimBoundaryNote: "Constant usage is a reference edge only.",
  },
  {
    id: "energy_momentum_specializes_rest_energy",
    from: "physics.relativity.energy_momentum_relation",
    to: "physics.relativity.rest_energy",
    relation: "specializes",
    label: "Rest energy is the zero-momentum specialization of the energy-momentum relation.",
    claimBoundaryNote: "Specialization edge is a derivation hint.",
  },
  {
    id: "quantum_momentum_feeds_energy_momentum",
    from: "physics.quantum.momentum_wavelength",
    to: "physics.relativity.energy_momentum_relation",
    relation: "requires",
    label: "Momentum can feed the relativistic energy-momentum relation.",
    claimBoundaryNote: "Momentum relation is a reference bridge.",
  },
  {
    id: "energy_density_feeds_stress_energy_tensor",
    from: "physics.energy.energy_density",
    to: "physics.fields.stress_energy_tensor",
    relation: "requires",
    label: "Stress-energy components carry energy-density-like unit signatures.",
    claimBoundaryNote: "Unit bridge does not solve tensor field equations.",
  },
  {
    id: "conservation_feeds_stress_energy_tensor",
    from: "physics.symmetry.energy_momentum_conservation",
    to: "physics.fields.stress_energy_tensor",
    relation: "requires",
    label: "Stress-energy usage is constrained by conservation context.",
    claimBoundaryNote: "Reference conservation edge only.",
  },
  {
    id: "stress_energy_tensor_feeds_efe",
    from: "physics.fields.stress_energy_tensor",
    to: "physics.gr.einstein_field_equation",
    relation: "requires",
    label: "Einstein field equations use stress-energy as the source-side object.",
    claimBoundaryNote: "Reference edge only; no NHM2 physical claim.",
  },
  {
    id: "power_rate_feeds_tile_duty_cycle",
    from: "physics.energy.power_rate",
    to: "nhm2.tile.duty_cycle_average",
    relation: "requires",
    label: "Duty-cycle averages depend on energy-per-time reasoning.",
    claimBoundaryNote: "Executable scalar bridge remains diagnostic.",
  },
  {
    id: "energy_density_feeds_nhm2_source_proxy",
    from: "physics.energy.energy_density",
    to: "nhm2.source.energy_density_proxy",
    relation: "requires",
    label: "NHM2 source proxies reuse the canonical energy-density scalar relation.",
    claimBoundaryNote: "Shared scalar form does not validate NHM2.",
  },
  {
    id: "lorentz_factor_context_for_3p1",
    from: "physics.frames.lorentz_factor",
    to: "physics.gr.3p1_decomposition",
    relation: "documents",
    label: "Frame factors provide context for relativity-facing geometry terms.",
    claimBoundaryNote: "Documentation edge is not executable playback.",
  },
];
