import {
  type TheoryBadgeClaimBoundaryV1,
  type TheoryBadgeEdgeV1,
  type TheoryBadgeV1,
} from "../contracts/theory-badge-graph.v1";

const GALACTIC_BOUNDARY: TheoryBadgeClaimBoundaryV1 = {
  diagnosticOnly: true,
  doesValidateNHM2: false,
  validationClaimAllowed: false,
  physicalMechanismClaimAllowed: false,
  promotionAllowed: false,
};

const repoRef = (path: string, id?: string, note?: string): TheoryBadgeV1["sourceRefs"][number] => ({
  kind: "repo_module",
  path,
  id: id ?? null,
  note: note ?? null,
});

const docRef = (path: string, id?: string, note?: string): TheoryBadgeV1["sourceRefs"][number] => ({
  kind: "doc",
  path,
  id: id ?? null,
  note: note ?? null,
});

const payload = (args: {
  id: string;
  expression: string;
  displayLatex: string;
  targetVariable: string;
}): TheoryBadgeV1["calculatorPayloads"][number] => ({
  id: args.id,
  expression: args.expression,
  displayLatex: args.displayLatex,
  preferredAction: "solve_with_steps",
  targetVariable: args.targetVariable,
  setupContext: null,
});

const galacticBadge = (badge: Omit<TheoryBadgeV1, "claimBoundary">): TheoryBadgeV1 => ({
  ...badge,
  claimBoundary: GALACTIC_BOUNDARY,
});

export const GALACTIC_DYNAMICS_THEORY_BADGES: TheoryBadgeV1[] = [
  galacticBadge({
    id: "galactic.map.distance_3d",
    title: "Galactic Map 3D Distance",
    plainMeaning: "Computes Euclidean separation between two star-map nodes in parsecs.",
    whyItMatters: "It gives StarMap prompts a scalar geometry row before runtime graph building.",
    subjects: ["galactic", "star_map", "distance", "geometry"],
    level: "derived_relation",
    status: "project_derived",
    simulationOwners: ["starsim", "starsim_accordion"],
    equationFamilies: ["star_map_distance"],
    tags: ["distance", "calculator_loadable"],
    equations: [
      {
        id: "distance_3d",
        role: "calculator_demo",
        displayLatex: "d=\\sqrt{\\Delta x^2+\\Delta y^2+\\Delta z^2}",
        computableExpression: "distance_pc = sqrt(dx_pc^2 + dy_pc^2 + dz_pc^2)",
        operatorKind: "scalar_expression",
        inputSymbols: ["dx_pc", "dy_pc", "dz_pc"],
        outputSymbols: ["distance_pc"],
      },
    ],
    units: [{ symbol: "distance_pc", unit: "pc", quantity: "distance", dimensionSignature: "L" }],
    assumptions: ["Euclidean local-map helper.", "Coordinate-frame provenance must come from the map/runtime receipt."],
    calculatorPayloads: [
      payload({
        id: "galactic_distance_3d_payload",
        expression: "distance_pc = sqrt(dx_pc^2 + dy_pc^2 + dz_pc^2)",
        displayLatex: "d=\\sqrt{\\Delta x^2+\\Delta y^2+\\Delta z^2}",
        targetVariable: "distance_pc",
      }),
    ],
    sourceRefs: [
      repoRef("shared/starsim-fusion-microphysics.ts", "distance3", "Distance helper used by StarMap graph construction."),
      repoRef("shared/starsim-accordion-galactic-null-model.ts", "starSimAccordionStarNodeSchema", "Star-node coordinate schema."),
    ],
    hintKeys: {
      subjects: ["galactic", "star_map", "distance", "geometry"],
      symbols: ["distance_pc", "dx_pc", "dy_pc", "dz_pc"],
      unitSignatures: ["L"],
      repoPaths: ["shared/starsim-fusion-microphysics.ts", "shared/starsim-accordion-galactic-null-model.ts"],
      equationFamilies: ["star_map_distance"],
      simulationOwners: ["starsim", "starsim_accordion"],
    },
  }),
  galacticBadge({
    id: "galactic.map.relative_velocity",
    title: "Galactic Map Relative Velocity",
    plainMeaning: "Computes relative velocity magnitude between two star-map nodes.",
    whyItMatters: "It provides scalar support for velocity-field and stream prompts.",
    subjects: ["galactic", "star_map", "relative_velocity", "velocity"],
    level: "derived_relation",
    status: "project_derived",
    simulationOwners: ["starsim", "starsim_accordion"],
    equationFamilies: ["relative_velocity"],
    tags: ["velocity", "calculator_loadable"],
    equations: [
      {
        id: "relative_velocity_3d",
        role: "calculator_demo",
        displayLatex: "v_{rel}=\\sqrt{\\Delta v_x^2+\\Delta v_y^2+\\Delta v_z^2}",
        computableExpression: "relativeVelocity_kms = sqrt(dvx_kms^2 + dvy_kms^2 + dvz_kms^2)",
        operatorKind: "scalar_expression",
        inputSymbols: ["dvx_kms", "dvy_kms", "dvz_kms"],
        outputSymbols: ["relativeVelocity_kms"],
      },
    ],
    units: [{ symbol: "relativeVelocity_kms", unit: "km/s", quantity: "speed", dimensionSignature: "L T^-1" }],
    assumptions: ["Velocity-frame provenance must come from the observation/runtime context."],
    calculatorPayloads: [
      payload({
        id: "galactic_relative_velocity_payload",
        expression: "relativeVelocity_kms = sqrt(dvx_kms^2 + dvy_kms^2 + dvz_kms^2)",
        displayLatex: "v_{rel}=\\sqrt{\\Delta v_x^2+\\Delta v_y^2+\\Delta v_z^2}",
        targetVariable: "relativeVelocity_kms",
      }),
    ],
    sourceRefs: [
      repoRef("shared/starsim-fusion-microphysics.ts", "buildStarMapFusionGraph", "Optional relative velocity in StarMap graph edges."),
    ],
    hintKeys: {
      subjects: ["galactic", "star_map", "relative_velocity", "velocity"],
      symbols: ["relativeVelocity_kms", "dvx_kms", "dvy_kms", "dvz_kms"],
      unitSignatures: ["L T^-1"],
      repoPaths: ["shared/starsim-fusion-microphysics.ts"],
      equationFamilies: ["relative_velocity"],
      simulationOwners: ["starsim", "starsim_accordion"],
    },
  }),
  galacticBadge({
    id: "galactic.map.structure_weight_proxy",
    title: "Galactic Structure Weight Proxy",
    plainMeaning: "Assigns a reduced inverse-distance graph weight.",
    whyItMatters: "It mirrors the StarMap graph builder's structure-prior weighting row.",
    subjects: ["galactic", "star_map", "structure_weight", "graph"],
    level: "simulation_specific",
    status: "project_derived",
    simulationOwners: ["starsim", "starsim_accordion"],
    equationFamilies: ["star_map_structure_weight"],
    tags: ["structure_weight", "calculator_loadable"],
    equations: [
      {
        id: "structure_weight",
        role: "calculator_demo",
        displayLatex: "w=\\frac{1}{1+d}",
        computableExpression: "structureWeight = 1/(1 + distance_pc)",
        operatorKind: "scalar_expression",
        inputSymbols: ["distance_pc"],
        outputSymbols: ["structureWeight"],
      },
    ],
    units: [{ symbol: "structureWeight", unit: null, quantity: "weight", dimensionSignature: "1" }],
    assumptions: ["Structure prior only.", "Graph weights do not imply a physical spacetime connection."],
    calculatorPayloads: [
      payload({
        id: "galactic_structure_weight_payload",
        expression: "structureWeight = 1/(1 + distance_pc)",
        displayLatex: "w=\\frac{1}{1+d}",
        targetVariable: "structureWeight",
      }),
    ],
    sourceRefs: [
      repoRef("shared/starsim-fusion-microphysics.ts", "buildStarMapFusionGraph", "Uses 1/(1+distance_pc) for structure weight."),
      docRef("docs/research/starsim-accordion-galactic-dynamics-null-model-v1.md", "astrometric-structure-prior"),
    ],
    hintKeys: {
      subjects: ["galactic", "star_map", "structure_weight", "graph"],
      symbols: ["structureWeight", "distance_pc"],
      unitSignatures: ["1", "L"],
      repoPaths: ["shared/starsim-fusion-microphysics.ts", "docs/research/starsim-accordion-galactic-dynamics-null-model-v1.md"],
      equationFamilies: ["star_map_structure_weight"],
      simulationOwners: ["starsim", "starsim_accordion"],
    },
  }),
  galacticBadge({
    id: "galactic.rotation.circular_velocity_newtonian",
    title: "Newtonian Circular Velocity",
    plainMeaning: "Computes circular velocity from enclosed mass and radius.",
    whyItMatters: "It is the scalar root for baryonic Newtonian rotation-control prompts.",
    subjects: ["galactic", "rotation_curve", "newtonian", "gravity"],
    level: "law",
    status: "canonical_reference",
    simulationOwners: ["starsim_accordion"],
    equationFamilies: ["rotation_curve", "baryonic_newtonian"],
    tags: ["rotation", "calculator_loadable"],
    equations: [
      {
        id: "circular_velocity",
        role: "calculator_demo",
        displayLatex: "v_c=\\sqrt{GM(<r)/r}",
        computableExpression: "v_rot = sqrt(G*M_enc/r_kpc)",
        operatorKind: "scalar_expression",
        inputSymbols: ["G", "M_enc", "r_kpc"],
        outputSymbols: ["v_rot"],
      },
    ],
    units: [{ symbol: "v_rot", unit: "km/s", quantity: "speed", dimensionSignature: "L T^-1" }],
    assumptions: ["Reduced circular-orbit control row.", "Mass model and radius units must be explicit."],
    calculatorPayloads: [
      payload({
        id: "galactic_circular_velocity_payload",
        expression: "v_rot = sqrt(G*M_enc/r_kpc)",
        displayLatex: "v_c=\\sqrt{GM(<r)/r}",
        targetVariable: "v_rot",
      }),
    ],
    sourceRefs: [
      repoRef("shared/starsim-galactic-rotation-controls.ts", "baryonic_newtonian", "Baryonic Newtonian control model."),
    ],
    hintKeys: {
      subjects: ["galactic", "rotation_curve", "newtonian", "gravity"],
      symbols: ["v_rot", "G", "M_enc", "r_kpc"],
      unitSignatures: ["L T^-1", "M", "L"],
      repoPaths: ["shared/starsim-galactic-rotation-controls.ts"],
      equationFamilies: ["rotation_curve", "baryonic_newtonian"],
      simulationOwners: ["starsim_accordion"],
    },
  }),
  galacticBadge({
    id: "galactic.rotation.centripetal_acceleration",
    title: "Centripetal Acceleration",
    plainMeaning: "Computes acceleration implied by circular speed and radius.",
    whyItMatters: "It links rotation curves to low-acceleration control-model prompts.",
    subjects: ["galactic", "rotation_curve", "acceleration"],
    level: "derived_relation",
    status: "canonical_reference",
    simulationOwners: ["starsim_accordion"],
    equationFamilies: ["rotation_curve", "low_acceleration"],
    tags: ["rotation", "acceleration", "calculator_loadable"],
    equations: [
      {
        id: "centripetal_acceleration",
        role: "calculator_demo",
        displayLatex: "a_c=\\frac{v^2}{r}",
        computableExpression: "a_c = v_rot^2/r_kpc",
        operatorKind: "scalar_expression",
        inputSymbols: ["v_rot", "r_kpc"],
        outputSymbols: ["a_c"],
      },
    ],
    units: [{ symbol: "a_c", unit: "(km/s)^2/kpc", quantity: "acceleration", dimensionSignature: "L T^-2" }],
    assumptions: ["Unit conversion is explicit in downstream interpretation."],
    calculatorPayloads: [
      payload({
        id: "galactic_centripetal_acceleration_payload",
        expression: "a_c = v_rot^2/r_kpc",
        displayLatex: "a_c=\\frac{v^2}{r}",
        targetVariable: "a_c",
      }),
    ],
    sourceRefs: [
      repoRef("shared/starsim-galactic-rotation-controls.ts", "mond_low_acceleration", "Low-acceleration control-model context."),
    ],
    hintKeys: {
      subjects: ["galactic", "rotation_curve", "acceleration", "low_acceleration"],
      symbols: ["a_c", "v_rot", "r_kpc"],
      unitSignatures: ["L T^-2", "L T^-1", "L"],
      repoPaths: ["shared/starsim-galactic-rotation-controls.ts"],
      equationFamilies: ["rotation_curve", "low_acceleration"],
      simulationOwners: ["starsim_accordion"],
    },
  }),
  galacticBadge({
    id: "galactic.rotation.velocity_residual",
    title: "Rotation Velocity Residual",
    plainMeaning: "Compares observed rotation velocity with a selected model velocity.",
    whyItMatters: "It gives rotation-curve prompts a scalar residual row while keeping model selection separate.",
    subjects: ["galactic", "rotation_curve", "residual", "null_model"],
    level: "diagnostic_gate",
    status: "diagnostic",
    simulationOwners: ["starsim_accordion"],
    equationFamilies: ["rotation_curve_residual"],
    tags: ["residual", "calculator_loadable"],
    equations: [
      {
        id: "velocity_residual",
        role: "calculator_demo",
        displayLatex: "\\Delta v=v_{obs}-v_{model}",
        computableExpression: "velocity_residual = v_obs - v_model",
        operatorKind: "scalar_expression",
        inputSymbols: ["v_obs", "v_model"],
        outputSymbols: ["velocity_residual"],
      },
    ],
    units: [{ symbol: "velocity_residual", unit: "km/s", quantity: "velocity_residual", dimensionSignature: "L T^-1" }],
    assumptions: ["Null-model comparison only.", "Does not select a physical explanation."],
    calculatorPayloads: [
      payload({
        id: "galactic_velocity_residual_payload",
        expression: "velocity_residual = v_obs - v_model",
        displayLatex: "\\Delta v=v_{obs}-v_{model}",
        targetVariable: "velocity_residual",
      }),
    ],
    sourceRefs: [
      repoRef("shared/starsim-galactic-rotation-controls.ts", "residual_km_s", "Rotation-control residual calculation."),
      docRef("docs/knowledge/math-claims/starsim-accordion-galactic-dynamics.claims.json", "sparc_rotation_curve_null_model_context.v1"),
    ],
    hintKeys: {
      subjects: ["galactic", "rotation_curve", "residual", "null_model"],
      symbols: ["velocity_residual", "v_obs", "v_model"],
      unitSignatures: ["L T^-1"],
      repoPaths: ["shared/starsim-galactic-rotation-controls.ts", "docs/knowledge/math-claims/starsim-accordion-galactic-dynamics.claims.json"],
      equationFamilies: ["rotation_curve_residual"],
      simulationOwners: ["starsim_accordion"],
    },
  }),
  galacticBadge({
    id: "galactic.rotation.rms_residual_proxy",
    title: "Rotation RMS Residual Proxy",
    plainMeaning: "Computes RMS residual from a sum of squared velocity residuals.",
    whyItMatters: "It mirrors the reduced fit-quality summary used by rotation controls.",
    subjects: ["galactic", "rotation_curve", "rms", "null_model"],
    level: "diagnostic_gate",
    status: "diagnostic",
    simulationOwners: ["starsim_accordion"],
    equationFamilies: ["rotation_curve_residual"],
    tags: ["rms", "calculator_loadable"],
    equations: [
      {
        id: "rms_residual",
        role: "calculator_demo",
        displayLatex: "RMS=\\sqrt{\\sum \\Delta v^2/N}",
        computableExpression: "rms_residual = sqrt(residual_sum_sq/N_points)",
        operatorKind: "scalar_expression",
        inputSymbols: ["residual_sum_sq", "N_points"],
        outputSymbols: ["rms_residual"],
      },
    ],
    units: [{ symbol: "rms_residual", unit: "km/s", quantity: "velocity_residual", dimensionSignature: "L T^-1" }],
    assumptions: ["Reduced aggregate row.", "Fit labels require runtime threshold context."],
    calculatorPayloads: [
      payload({
        id: "galactic_rms_residual_payload",
        expression: "rms_residual = sqrt(residual_sum_sq/N_points)",
        displayLatex: "RMS=\\sqrt{\\sum \\Delta v^2/N}",
        targetVariable: "rms_residual",
      }),
    ],
    sourceRefs: [
      repoRef("shared/starsim-galactic-rotation-controls.ts", "rmsResidual_km_s", "Rotation-control fit summary."),
    ],
    hintKeys: {
      subjects: ["galactic", "rotation_curve", "rms", "null_model"],
      symbols: ["rms_residual", "residual_sum_sq", "N_points"],
      unitSignatures: ["L T^-1", "1"],
      repoPaths: ["shared/starsim-galactic-rotation-controls.ts"],
      equationFamilies: ["rotation_curve_residual"],
      simulationOwners: ["starsim_accordion"],
    },
  }),
  galacticBadge({
    id: "galactic.runtime.rotation_controls",
    title: "Galactic Rotation Controls Runtime",
    plainMeaning: "Reference node for baryonic, halo, MOND, and SPARC-like rotation-control comparisons.",
    whyItMatters: "It keeps rotation model comparison in runtime/null-model scope instead of scalar calculator scope.",
    subjects: ["galactic", "runtime", "rotation_curve", "null_model"],
    level: "diagnostic_gate",
    status: "diagnostic",
    simulationOwners: ["starsim_accordion"],
    equationFamilies: ["rotation_curve_controls"],
    tags: ["runtime_reference"],
    equations: [
      {
        id: "rotation_controls_reference",
        role: "noncomputable_reference",
        displayLatex: "controls=\\{baryonic,NFW,Burkert,MOND,SPARC\\}",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["rotationCurve"],
        outputSymbols: ["controls"],
      },
    ],
    units: [],
    assumptions: ["Runtime control comparison only.", "The runtime does not select a physics winner."],
    calculatorPayloads: [],
    sourceRefs: [
      repoRef("shared/starsim-galactic-rotation-controls.ts", "computeStarSimGalacticRotationControls"),
      docRef("docs/knowledge/math-claims/starsim-accordion-galactic-dynamics.claims.json", "mond_control_model_context.v1"),
    ],
    hintKeys: {
      subjects: ["galactic", "runtime", "rotation_curve", "null_model"],
      symbols: ["controls", "rmsResidual_km_s", "fitQuality"],
      unitSignatures: ["L T^-1"],
      repoPaths: ["shared/starsim-galactic-rotation-controls.ts", "docs/knowledge/math-claims/starsim-accordion-galactic-dynamics.claims.json"],
      equationFamilies: ["rotation_curve_controls"],
      simulationOwners: ["starsim_accordion"],
    },
  }),
  galacticBadge({
    id: "galactic.runtime.accordion_null_model",
    title: "Accordion Galactic Null Model Runtime",
    plainMeaning: "Reference node for Accordion cosmology context joined with star population and rotation controls.",
    whyItMatters: "It prevents prompts from treating cosmological expansion as a local bound-system solve.",
    subjects: ["galactic", "accordion", "runtime", "null_model", "cosmology"],
    level: "simulation_specific",
    status: "diagnostic",
    simulationOwners: ["starsim_accordion"],
    equationFamilies: ["accordion_galactic_null_model"],
    tags: ["runtime_reference", "bound_system_guardrail"],
    equations: [
      {
        id: "accordion_null_model_reference",
        role: "noncomputable_reference",
        displayLatex: "Accordion_{galaxy}=runtime(cosmology,stars,rotation)",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["cosmology", "starNodes", "rotation"],
        outputSymbols: ["galactic_null_evaluation"],
      },
    ],
    units: [],
    assumptions: ["Runtime/null-model context only.", "Bound systems require local dynamics models."],
    calculatorPayloads: [],
    sourceRefs: [
      repoRef("shared/starsim-accordion-galactic-null-model.ts", "runStarSimAccordionGalacticNullModel"),
      repoRef("shared/starsim-accordion-cosmology-context.ts", "buildStarSimAccordionCosmologyContext"),
      docRef("docs/research/starsim-accordion-galactic-dynamics-null-model-v1.md", "null-model"),
    ],
    hintKeys: {
      subjects: ["galactic", "accordion", "runtime", "null_model", "cosmology"],
      symbols: ["galactic_null_evaluation", "spacetimeCL", "mayPromoteToCL4"],
      unitSignatures: [],
      repoPaths: [
        "shared/starsim-accordion-galactic-null-model.ts",
        "shared/starsim-accordion-cosmology-context.ts",
        "docs/research/starsim-accordion-galactic-dynamics-null-model-v1.md",
      ],
      equationFamilies: ["accordion_galactic_null_model"],
      simulationOwners: ["starsim_accordion"],
    },
  }),
  galacticBadge({
    id: "galactic.claim_boundary.null_model_only",
    title: "Galactic Null-Model Boundary",
    plainMeaning: "Keeps galactic dynamics rows in local dynamics and null-model comparison scope.",
    whyItMatters: "It blocks over-reading star maps, rotation residuals, or Accordion context as high-level spacetime evidence.",
    subjects: ["galactic", "claim_boundary", "null_model"],
    level: "claim_boundary",
    status: "blocked",
    simulationOwners: ["starsim_accordion"],
    equationFamilies: ["galactic_claim_boundary"],
    tags: ["claim_boundary"],
    equations: [
      {
        id: "galactic_boundary_reference",
        role: "noncomputable_reference",
        displayLatex: "\\mathrm{null\\ model\\ only}",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: [],
        outputSymbols: ["claim_boundary"],
      },
    ],
    units: [],
    assumptions: [
      "Rotation-control rows are null-model comparisons.",
      "Star maps are population and structure priors.",
      "No galactic row promotes outputs to ER/EPR evidence or CL support.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      docRef("docs/knowledge/math-claims/starsim-accordion-galactic-dynamics.claims.json", "bound_systems_not_local_hubble_flow_guardrail.v1"),
      repoRef("shared/starsim-galactic-dynamics-safe-language.ts", "safe language guardrails"),
    ],
    hintKeys: {
      subjects: ["galactic", "claim_boundary", "null_model"],
      symbols: ["claim_boundary"],
      unitSignatures: [],
      repoPaths: [
        "docs/knowledge/math-claims/starsim-accordion-galactic-dynamics.claims.json",
        "shared/starsim-galactic-dynamics-safe-language.ts",
      ],
      equationFamilies: ["galactic_claim_boundary"],
      simulationOwners: ["starsim_accordion"],
    },
  }),
];

export const GALACTIC_DYNAMICS_THEORY_EDGES: TheoryBadgeEdgeV1[] = [
  {
    id: "galactic_distance_feeds_structure_weight",
    from: "galactic.map.distance_3d",
    to: "galactic.map.structure_weight_proxy",
    relation: "derives",
    label: "Structure weight uses star-map distance.",
    claimBoundaryNote: "Structure weight remains a graph prior.",
  },
  {
    id: "galactic_structure_weight_feeds_starmap_runtime",
    from: "galactic.map.structure_weight_proxy",
    to: "starsim.runtime.build_star_map_fusion_graph",
    relation: "numerically_solves",
    label: "The runtime graph uses structure-weight-like edge context.",
    claimBoundaryNote: "Graph edges do not imply spacetime connections.",
  },
  {
    id: "galactic_relative_velocity_feeds_starmap_runtime",
    from: "galactic.map.relative_velocity",
    to: "starsim.runtime.build_star_map_fusion_graph",
    relation: "documents",
    label: "Relative velocity documents star-map edge context.",
    claimBoundaryNote: "Velocity fields remain observational priors.",
  },
  {
    id: "cosmic_context_documents_galactic_null_model",
    from: "cosmic.low_z.hubble_distance",
    to: "galactic.runtime.accordion_null_model",
    relation: "documents",
    label: "Cosmology provides context, not local bound-system expansion.",
    claimBoundaryNote: "Bound systems require local dynamics.",
  },
  {
    id: "galactic_circular_velocity_feeds_rotation_controls",
    from: "galactic.rotation.circular_velocity_newtonian",
    to: "galactic.runtime.rotation_controls",
    relation: "documents",
    label: "Circular velocity is one scalar input family for rotation controls.",
    claimBoundaryNote: "Controls do not select a physics winner.",
  },
  {
    id: "galactic_circular_velocity_feeds_acceleration",
    from: "galactic.rotation.circular_velocity_newtonian",
    to: "galactic.rotation.centripetal_acceleration",
    relation: "derives",
    label: "Acceleration can be computed from rotation speed and radius.",
    claimBoundaryNote: "Low-acceleration rows are control-model context.",
  },
  {
    id: "galactic_velocity_residual_feeds_rms",
    from: "galactic.rotation.velocity_residual",
    to: "galactic.rotation.rms_residual_proxy",
    relation: "derives",
    label: "RMS residual aggregates velocity residuals.",
    claimBoundaryNote: "Residual size is a diagnostic summary.",
  },
  {
    id: "galactic_rms_documents_rotation_controls",
    from: "galactic.rotation.rms_residual_proxy",
    to: "galactic.runtime.rotation_controls",
    relation: "diagnostic_checks",
    label: "RMS residual documents rotation-control fit quality.",
    claimBoundaryNote: "Fit quality is runtime/null-model context.",
  },
  {
    id: "galactic_rotation_controls_feed_null_model",
    from: "galactic.runtime.rotation_controls",
    to: "galactic.runtime.accordion_null_model",
    relation: "documents",
    label: "Rotation controls can be attached to the Accordion galactic null model.",
    claimBoundaryNote: "Accordion context remains proxy-only.",
  },
  {
    id: "galactic_null_model_documents_boundary",
    from: "galactic.runtime.accordion_null_model",
    to: "galactic.claim_boundary.null_model_only",
    relation: "documents",
    label: "Null-model runtimes must expose their claim boundary.",
    claimBoundaryNote: "No claim promotion is allowed.",
  },
  {
    id: "galactic_rotation_controls_block_promotion",
    from: "galactic.runtime.rotation_controls",
    to: "galactic.claim_boundary.null_model_only",
    relation: "blocks",
    label: "Rotation controls cannot promote themselves into a physical winner.",
    claimBoundaryNote: "Control comparison stays diagnostic.",
  },
];

export function buildGalacticDynamicsTheoryBadgesV1(): {
  badges: TheoryBadgeV1[];
  edges: TheoryBadgeEdgeV1[];
} {
  return {
    badges: GALACTIC_DYNAMICS_THEORY_BADGES,
    edges: GALACTIC_DYNAMICS_THEORY_EDGES,
  };
}
