export const NHM2_RUNTIME_FIELD_BINDING_KIND_VALUES = [
  "model_relation",
  "runtime_bound_output",
  "runtime_gate",
  "claim_boundary",
] as const;

export type Nhm2RuntimeFieldBindingKind =
  (typeof NHM2_RUNTIME_FIELD_BINDING_KIND_VALUES)[number];

export type Nhm2RuntimeFieldBinding = {
  badgeId: string;
  kind: Nhm2RuntimeFieldBindingKind;
  runtimeId: string;
  laneId: "warp_gr_nhm2" | "qei_stress_energy";
  artifactFields: string[];
  scalarCuts: Array<{
    id: string;
    expression: string;
    displayLatex: string;
    outputSymbols: string[];
  }>;
  gates: string[];
  requiredEvidence: string[];
  claimBoundaryNotes: string[];
};

const NHM2_PROMOTION_EVIDENCE = [
  "source_closure_artifact",
  "observer_audit",
  "qei_worldline_dossier",
  "stage3_certificate",
  "certificate_integrity",
] as const;

export const NHM2_RUNTIME_FIELD_BINDINGS: Nhm2RuntimeFieldBinding[] = [
  {
    badgeId: "physics.gr.einstein_field_equation",
    kind: "model_relation",
    runtimeId: "gr_nhm2.artifact_reader",
    laneId: "warp_gr_nhm2",
    artifactFields: ["metricT00Geom", "metricT00Si", "G_mu_nu", "T_mu_nu"],
    scalarCuts: [],
    gates: ["hard_constraints", "observer_audit"],
    requiredEvidence: [
      "observer_audit",
      "hard_constraint_report",
      "metric_contract",
    ],
    claimBoundaryNotes: [
      "Einstein field equation rows are tensor/model context; scalar calculator rows may only inspect cuts around the runtime.",
    ],
  },
  {
    badgeId: "physics.gr.stress_energy_conservation",
    kind: "model_relation",
    runtimeId: "gr_nhm2.artifact_reader",
    laneId: "warp_gr_nhm2",
    artifactFields: [
      "sourceClosureResidualRms",
      "sourceClosureResidualMax",
      "divergenceRms",
    ],
    scalarCuts: [],
    gates: ["source_closure", "observer_audit"],
    requiredEvidence: ["source_closure_artifact", "observer_audit"],
    claimBoundaryNotes: [
      "Stress-energy conservation must be backed by source-closure and observer-audit evidence before interpretation.",
    ],
  },
  {
    badgeId: "physics.gr.3p1_decomposition",
    kind: "model_relation",
    runtimeId: "gr_nhm2.artifact_reader",
    laneId: "warp_gr_nhm2",
    artifactFields: [
      "alpha",
      "beta_i",
      "betaOverAlphaMax",
      "wallHorizonMargin",
    ],
    scalarCuts: [
      {
        id: "wall_horizon_margin_cut",
        expression: "wallHorizonMargin = 1 - betaOverAlphaMax",
        displayLatex: "margin_{wall}=1-\\max(\\beta/\\alpha)",
        outputSymbols: ["wallHorizonMargin"],
      },
    ],
    gates: ["hard_constraints"],
    requiredEvidence: ["shift_lapse_audit", "hard_constraint_report"],
    claimBoundaryNotes: [
      "3+1 decomposition badges bind to sampled lapse/shift diagnostics, not a standalone scalar solve.",
    ],
  },
  {
    badgeId: "nhm2.geometry.lapse_shift_profile",
    kind: "runtime_bound_output",
    runtimeId: "gr_nhm2.artifact_reader",
    laneId: "warp_gr_nhm2",
    artifactFields: [
      "tauSelected",
      "properTimeS",
      "savedDays",
      "betaOverAlphaMax",
      "wallHorizonMargin",
    ],
    scalarCuts: [
      {
        id: "proper_time_offset_cut",
        expression: "t_proper = t_shift + delta_t_lapse",
        displayLatex: "t_{proper}=t_{shift}+\\Delta t_{lapse}",
        outputSymbols: ["t_proper"],
      },
      {
        id: "wall_horizon_margin_cut",
        expression: "wallHorizonMargin = 1 - betaOverAlphaMax",
        displayLatex: "margin_{wall}=1-\\max(\\beta/\\alpha)",
        outputSymbols: ["wallHorizonMargin"],
      },
    ],
    gates: ["hard_constraints", "observer_audit"],
    requiredEvidence: ["shift_lapse_audit", "observer_audit"],
    claimBoundaryNotes: [
      "Lapse/shift profile values are runtime-bound samples from a selected solve family.",
    ],
  },
  {
    badgeId: "nhm2.source.energy_density_proxy",
    kind: "runtime_bound_output",
    runtimeId: "gr_nhm2.artifact_reader",
    laneId: "warp_gr_nhm2",
    artifactFields: [
      "rhoMetric",
      "rhoProxy",
      "rhoCoupledShadow",
      "couplingResidualRel",
    ],
    scalarCuts: [
      {
        id: "energy_density_proxy_cut",
        expression: "rho = E / V",
        displayLatex: "\\rho=E/V",
        outputSymbols: ["rho"],
      },
    ],
    gates: ["source_closure", "qei_applicability"],
    requiredEvidence: ["source_closure_artifact", "qei_worldline_dossier"],
    claimBoundaryNotes: [
      "Energy-density proxy values are source-context diagnostics and do not prove a physical source mechanism.",
    ],
  },
  {
    badgeId: "nhm2.closure.wall_t00_source_residual",
    kind: "runtime_bound_output",
    runtimeId: "gr_nhm2.artifact_reader",
    laneId: "warp_gr_nhm2",
    artifactFields: [
      "nhm2WallSourceClosure.required.T00_SI",
      "nhm2WallSourceClosure.required.componentStatus",
      "nhm2WallSourceClosure.available.sourceKind",
      "nhm2WallSourceClosure.available.T00_SI",
      "nhm2WallSourceClosure.available.componentStatus",
      "nhm2WallSourceClosure.residual.absolute",
      "nhm2WallSourceClosure.residual.relative",
      "nhm2WallSourceClosure.residual.tolerance",
      "nhm2WallSourceClosure.residual.pass",
      "nhm2WallSourceClosure.blockers",
      "sourceClosure.wallSourceClosure.residual.pass",
    ],
    scalarCuts: [
      {
        id: "wall_t00_source_residual_cut",
        expression: "R_wall_T00 = T00_wall_required - T00_wall_available",
        displayLatex: "R_{wall,T00}=T00_{wall,required}-T00_{wall,available}",
        outputSymbols: ["R_wall_T00"],
      },
    ],
    gates: ["source_closure", "wall_source_closure"],
    requiredEvidence: [
      "wall_source_closure_artifact",
      "metric_required_wall_tensor",
      "tile_effective_wall_tensor",
    ],
    claimBoundaryNotes: [
      "Wall T00 source residual is the front-door source-closure gate; global residuals are secondary context.",
    ],
  },
  {
    badgeId: "nhm2.closure.source_residual",
    kind: "runtime_bound_output",
    runtimeId: "gr_nhm2.artifact_reader",
    laneId: "warp_gr_nhm2",
    artifactFields: [
      "sourceClosureResidualRms",
      "sourceClosureResidualMax",
      "sourceClosureResidualByRegion",
    ],
    scalarCuts: [
      {
        id: "source_residual_difference_cut",
        expression: "R_source = source_required - source_available",
        displayLatex: "R_{source}=source_{required}-source_{available}",
        outputSymbols: ["R_source"],
      },
    ],
    gates: ["source_closure"],
    requiredEvidence: [
      "source_closure_artifact",
      "source_closure_region_report",
      "observer_audit",
    ],
    claimBoundaryNotes: [
      "Source residual is runtime-bound closure evidence; a scalar residual row is only a local diagnostic check.",
    ],
  },
  {
    badgeId: "nhm2.source.wall_t00_trace",
    kind: "runtime_bound_output",
    runtimeId: "gr_nhm2.artifact_reader",
    laneId: "warp_gr_nhm2",
    artifactFields: [
      "sourceClosureResidualByRegion.wall.residualNorms.relLInf",
      "sourceClosureWallT00RelLInf",
      "wallT00RelLInf",
      "t00_mismatch_present",
    ],
    scalarCuts: [
      {
        id: "wall_t00_rel_linf_cut",
        expression:
          "wall_t00_relLInf = abs(T00_geom_wall - T00_tile_wall) / max(abs(T00_geom_wall), eps)",
        displayLatex:
          "\\mathrm{relLInf}_{wall}=|T_{00,geom}^{wall}-T_{00,tile}^{wall}|/\\max(|T_{00,geom}^{wall}|,\\epsilon)",
        outputSymbols: ["wall_t00_relLInf"],
      },
    ],
    gates: ["source_closure", "wall_t00_trace"],
    requiredEvidence: [
      "source_closure_region_report",
      "metric_required_wall_tensor",
      "tile_effective_wall_tensor",
    ],
    claimBoundaryNotes: [
      "Wall T00 trace is a runtime-bound blocker; global source closure summaries must not hide wall-region mismatch.",
    ],
  },
  {
    badgeId: "nhm2.tensor.full_authority_gate",
    kind: "runtime_gate",
    runtimeId: "gr_nhm2.artifact_reader",
    laneId: "warp_gr_nhm2",
    artifactFields: [
      "observerMetricEmissionAdmissionStatus",
      "observerMetricT0iAdmissionStatus",
      "observerMetricOffDiagonalTijAdmissionStatus",
      "sameChartFullTensor.adm.alphaStatus",
      "sameChartFullTensor.adm.betaStatus",
      "sameChartFullTensor.adm.gammaStatus",
      "sameChartFullTensor.adm.extrinsicCurvatureStatus",
      "sameChartFullTensor.components",
      "sameChartFullTensor.components[].componentId",
      "sameChartFullTensor.components[].status",
      "sameChartFullTensor.components[].valueSI",
      "sameChartFullTensor.components[].provenance.source",
      "sameChartFullTensor.components[].provenance.routeId",
      "sameChartFullTensor.completeness.hasT0i",
      "sameChartFullTensor.completeness.hasOffDiagonalTij",
      "sameChartFullTensor.completeness.fullTensorComplete",
      "sameChartFullTensor.completeness.missingComponentIds",
      "tensorAuthorityStatus",
    ],
    scalarCuts: [],
    gates: ["observer_audit", "tensor_authority"],
    requiredEvidence: [
      "observer_audit",
      "metric_t0i_emission",
      "metric_off_diagonal_tij_emission",
    ],
    claimBoundaryNotes: [
      "Full tensor authority remains blocked until same-chart T00, J_i, diagonal S_ij, and off-diagonal S_ij evidence is present.",
    ],
  },
  {
    badgeId: "nhm2.tensor.same_chart_full_tensor",
    kind: "runtime_gate",
    runtimeId: "gr_nhm2.artifact_reader",
    laneId: "warp_gr_nhm2",
    artifactFields: [
      "sameChartFullTensor.contractVersion",
      "sameChartFullTensor.chartId",
      "sameChartFullTensor.adm.alphaStatus",
      "sameChartFullTensor.adm.betaStatus",
      "sameChartFullTensor.adm.gammaStatus",
      "sameChartFullTensor.adm.extrinsicCurvatureStatus",
      "sameChartFullTensor.components[].componentId",
      "sameChartFullTensor.components[].valueSI",
      "sameChartFullTensor.components[].unit",
      "sameChartFullTensor.components[].status",
      "sameChartFullTensor.components[].provenance.source",
      "sameChartFullTensor.components[].provenance.routeId",
      "sameChartFullTensor.components[].blockers",
      "sameChartFullTensor.completeness.hasT00",
      "sameChartFullTensor.completeness.hasT0i",
      "sameChartFullTensor.completeness.hasDiagonalTij",
      "sameChartFullTensor.completeness.hasOffDiagonalTij",
      "sameChartFullTensor.completeness.fullTensorComplete",
      "sameChartFullTensor.completeness.missingComponentIds",
    ],
    scalarCuts: [],
    gates: ["tensor_authority", "same_chart_full_tensor", "adm_projection"],
    requiredEvidence: [
      "same_chart_full_tensor_artifact",
      "adm_projection_state",
      "metric_t0i_emission",
      "metric_off_diagonal_tij_emission",
    ],
    claimBoundaryNotes: [
      "Same-chart tensor evidence is status-bearing component evidence; missing momentum or off-diagonal stress components are blockers, not zero values.",
    ],
  },
  {
    badgeId: "nhm2.source.same_basis_tensor_authority",
    kind: "runtime_gate",
    runtimeId: "gr_nhm2.artifact_reader",
    laneId: "warp_gr_nhm2",
    artifactFields: [
      "nhm2SourceSideSameBasisTensorAuthority.contractVersion",
      "nhm2SourceSideSameBasisTensorAuthority.chartId",
      "nhm2SourceSideSameBasisTensorAuthority.sourceModelId",
      "nhm2SourceSideSameBasisTensorAuthority.sourceTensorArtifactRef",
      "nhm2SourceSideSameBasisTensorAuthority.counterpartArtifactRef",
      "nhm2SourceSideSameBasisTensorAuthority.regions[].regionId",
      "nhm2SourceSideSameBasisTensorAuthority.regions[].status",
      "nhm2SourceSideSameBasisTensorAuthority.regions[].sourceTensorRef",
      "nhm2SourceSideSameBasisTensorAuthority.regions[].comparisonRole",
      "nhm2SourceSideSameBasisTensorAuthority.regions[].tensorAuthorityMode",
      "nhm2SourceSideSameBasisTensorAuthority.regions[].derivationMode",
      "nhm2SourceSideSameBasisTensorAuthority.regions[].notDerivedFromMetricRequiredTensor",
      "nhm2SourceSideSameBasisTensorAuthority.regions[].hasFullTensorComponents",
      "nhm2SourceSideSameBasisTensorAuthority.regions[].missingComponentIds",
      "nhm2SourceSideSameBasisTensorAuthority.regions[].blockers",
      "nhm2SourceSideSameBasisTensorAuthority.summary.hasWallAuthority",
      "nhm2SourceSideSameBasisTensorAuthority.summary.allRequiredRegionsAuthoritative",
      "nhm2SourceSideSameBasisTensorAuthority.summary.anyMetricEcho",
      "nhm2SourceSideSameBasisTensorAuthority.summary.anyProxy",
      "nhm2SourceSideSameBasisTensorAuthority.summary.anyMissingCounterpart",
      "nhm2WallSourceClosure.available.sourceAuthorityStatus",
      "nhm2WallSourceClosure.available.sourceAuthorityRef",
    ],
    scalarCuts: [],
    gates: [
      "source_closure",
      "source_side_same_basis_tensor_authority",
      "wall_t00_trace",
    ],
    requiredEvidence: [
      "source_side_same_basis_tensor_authority_artifact",
      "tile_effective_counterpart_artifact",
      "same_chart_full_tensor_artifact",
      "material_receipt_artifact",
    ],
    claimBoundaryNotes: [
      "Wall closure cannot be promoted from scalar, diagonal-only, proxy, or metric-echo source rows; source-side same-basis tensor authority must be explicit.",
    ],
  },
  {
    badgeId: "nhm2.meta.experiment_ready_theory_closure",
    kind: "runtime_gate",
    runtimeId: "gr_nhm2.artifact_reader",
    laneId: "warp_gr_nhm2",
    artifactFields: [
      "nhm2ExperimentReadyTheoryClosure.contractVersion",
      "nhm2ExperimentReadyTheoryClosure.evaluationAuthority",
      "nhm2ExperimentReadyTheoryClosure.candidate.candidateId",
      "nhm2ExperimentReadyTheoryClosure.candidate.primaryRunId",
      "nhm2ExperimentReadyTheoryClosure.candidate.primaryRequestId",
      "nhm2ExperimentReadyTheoryClosure.candidate.primaryRuntimeId",
      "nhm2ExperimentReadyTheoryClosure.candidate.chartId",
      "nhm2ExperimentReadyTheoryClosure.candidate.atlasSha256",
      "nhm2ExperimentReadyTheoryClosure.candidate.unitsSha256",
      "nhm2ExperimentReadyTheoryClosure.candidate.normalizationSha256",
      "nhm2ExperimentReadyTheoryClosure.candidate.candidateManifestSha256",
      "nhm2ExperimentReadyTheoryClosure.candidate.candidateManifestId",
      "nhm2ExperimentReadyTheoryClosure.candidate.candidateManifestContractVersion",
      "nhm2ExperimentReadyTheoryClosure.candidate.numericPolicySetPath",
      "nhm2ExperimentReadyTheoryClosure.candidate.numericPolicySetSha256",
      "nhm2ExperimentReadyTheoryClosure.candidate.numericPolicySetSemanticSha256",
      "nhm2ExperimentReadyTheoryClosure.candidate.primaryReceiptPath",
      "nhm2ExperimentReadyTheoryClosure.candidate.primaryReceiptSha256",
      "nhm2ExperimentReadyTheoryClosure.evidence[].artifactContractVersion",
      "nhm2ExperimentReadyTheoryClosure.evidence[].receiptPath",
      "nhm2ExperimentReadyTheoryClosure.evidence[].receiptSha256",
      "nhm2ExperimentReadyTheoryClosure.evidence[].checks.*.frozenPolicySha256",
      "nhm2ExperimentReadyTheoryClosure.evidence[].checks.*.policySetSemanticSha256",
      "nhm2ExperimentReadyTheoryClosure.gates[].gateId",
      "nhm2ExperimentReadyTheoryClosure.gates[].status",
      "nhm2ExperimentReadyTheoryClosure.gates[].blockers",
      "nhm2ExperimentReadyTheoryClosure.gates[].failedCheckIds",
      "nhm2ExperimentReadyTheoryClosure.status",
      "nhm2ExperimentReadyTheoryClosure.verdictLabel",
      "nhm2ExperimentReadyTheoryClosure.summary.experimentReadyTheoryClosed",
      "nhm2ExperimentReadyTheoryClosure.summary.filesystemVerificationRequired",
      "nhm2ExperimentReadyTheoryClosure.summary.allEvidenceRunBoundFreshAndHashed",
      "nhm2ExperimentReadyTheoryClosure.summary.firstBlocker",
      "nhm2ExperimentReadyTheoryClosure.summary.empiricalStatus",
      "nhm2ExperimentReadyTheoryClosure.claimBoundary.physicalViabilityClaimAllowed",
      "nhm2ExperimentReadyTheoryClosure.claimBoundary.transportClaimAllowed",
      "nhm2ExperimentReadyTheoryClosure.claimBoundary.propulsionClaimAllowed",
      "nhm2ExperimentReadyTheoryClosure.claimBoundary.routeEtaClaimAllowed",
      "nhm2ExperimentReadyTheoryClosure.claimBoundary.speedAuthorityClaimAllowed",
    ],
    scalarCuts: [],
    gates: [
      "experiment_ready_theory_closure",
      "runtime_reproducibility",
      "same_chart_full_source_tensor",
      "semiclassical_state_realizability",
      "covariant_conservation",
      "continuous_observer_optimization",
      "worldline_qei_coverage",
      "dynamic_backreaction_stability_causality",
      "finite_temperature_finite_geometry_material_model",
      "mechanical_control_energy_margin",
      "independent_numerical_formal_replication",
      "prediction_falsifier_freeze",
    ],
    requiredEvidence: [
      "theory_runtime_receipt",
      "theory_runtime_output_manifest",
      "theory_runtime_freshness_snapshot_proof",
      "persisted_theory_runtime_receipts",
      "candidate_manifest",
      "full_apparatus_source_tensor",
      "semiclassical_state",
      "covariant_conservation",
      "continuous_observer_optimizer",
      "worldline_qei",
      "dynamic_backreaction_stability_causality",
      "finite_temperature_finite_geometry_maxwell_stress",
      "mechanical_support_control_margin",
      "independent_numerical_replication",
      "formal_manifest_certificate",
      "prediction_falsifier_freeze",
    ],
    claimBoundaryNotes: [
      "Experiment-ready theory closure is a separate runtime meta gate; it does not replace regional source-closure status.",
      "The pre-run candidate manifest freezes identities, execution plans, and semantic numeric policy; post-run receipts and output manifests must then bind fresh typed evidence before filesystem replay can produce THEORY_CLOSED_EXPERIMENT_READY_CANDIDATE.",
      "Even a theory-closed candidate leaves physical viability, transport, propulsion, route ETA, and speed authority blocked pending empirical receipts.",
    ],
  },
  {
    badgeId: "nhm2.qei.feasibility_frontier",
    kind: "runtime_bound_output",
    runtimeId: "nhm2.qei.feasibility_frontier",
    laneId: "qei_stress_energy",
    artifactFields: [
      "nhm2QeiFeasibilityFrontier.contractVersion",
      "nhm2QeiFeasibilityFrontier.provenance.run.runId",
      "nhm2QeiFeasibilityFrontier.provenance.run.commitSha",
      "nhm2QeiFeasibilityFrontier.provenance.run.epochId",
      "nhm2QeiFeasibilityFrontier.provenance.runManifest.sha256",
      "nhm2QeiFeasibilityFrontier.provenance.runtimeReceipt.sha256",
      "nhm2QeiFeasibilityFrontier.domain.finiteDomainDeclared",
      "nhm2QeiFeasibilityFrontier.domain.cartesianCoverageRequired",
      "nhm2QeiFeasibilityFrontier.candidates[].coverage.complete",
      "nhm2QeiFeasibilityFrontier.candidates[].evaluationStatus",
      "nhm2QeiFeasibilityFrontier.candidates[].worstCase.marginRawComputed",
      "nhm2QeiFeasibilityFrontier.candidates[].distanceToStrictBoundary.worstMargin",
      "nhm2QeiFeasibilityFrontier.candidates[].distanceToStrictBoundary.strictMarginGap",
      "nhm2QeiFeasibilityFrontier.candidates[].evaluations[].sensitivity.theoremCrossoverTauSeconds",
      "nhm2QeiFeasibilityFrontier.candidates[].evaluations[].sensitivity.currentTauToCrossoverRatio",
      "nhm2QeiFeasibilityFrontier.candidates[].evaluations[].sensitivity.logRawMarginLogTauSensitivity",
      "nhm2QeiFeasibilityFrontier.evaluationStatus",
      "nhm2QeiFeasibilityFrontier.verdict",
      "nhm2QeiFeasibilityFrontier.summary.frontierComplete",
      "nhm2QeiFeasibilityFrontier.summary.closestCandidateId",
      "nhm2QeiFeasibilityFrontier.summary.closestCandidateWorstMargin",
      "nhm2QeiFeasibilityFrontier.summary.closestStrictMarginGap",
      "nhm2QeiFeasibilityFrontier.summary.firstBlocker",
      "nhm2QeiFeasibilityFrontier.claimBoundary.finiteDomainNoCandidateIsNotUniversalNoGo",
      "nhm2QeiFeasibilityFrontier.claimBoundary.filesystemVerificationRequired",
      "nhm2QeiFeasibilityFrontier.claimBoundary.cannotSatisfyWorldlineQeiClosure",
      "nhm2QeiFeasibilityFrontier.claimBoundary.sensitivityDoesNotAuthorizeParameterScaling",
      "nhm2QeiFeasibilityFrontier.claimBoundary.physicalViabilityClaimAllowed",
      "nhm2QeiFeasibilityFrontier.claimBoundary.transportClaimAllowed",
      "nhm2QeiFeasibilityFrontier.claimBoundary.propulsionClaimAllowed",
      "nhm2QeiFeasibilityFrontier.claimBoundary.routeEtaClaimAllowed",
      "nhm2QeiFeasibilityFrontier.claimBoundary.certifiedSpeedClaimAllowed",
    ],
    scalarCuts: [],
    gates: [
      "qei_feasibility_frontier",
      "qei_frontier_filesystem_verification",
      "qei_frontier_cartesian_coverage",
      "qei_frontier_raw_margin",
      "qei_frontier_same_epoch_provenance",
    ],
    requiredEvidence: [
      "qei_feasibility_frontier_artifact",
      "qei_frontier_runtime_receipt",
      "qei_frontier_run_manifest",
      "qei_frontier_filesystem_evaluation",
      "qei_frontier_raw_evaluation_evidence",
      "qei_frontier_quadrature_evidence",
      "same_epoch_full_tensor_qft_observer_worldline_bindings",
    ],
    claimBoundaryNotes: [
      "The invariant cannotSatisfyWorldlineQeiClosure lock means this finite-domain frontier cannot satisfy the worldline-QEI dossier or experiment-ready theory-closure gate.",
      "A candidate-found or no-candidate result remains a diagnostic statement about the declared finite domain, not a universal QEI no-go or promotion authority.",
      "Crossover times and distance-to-boundary sensitivities are analytic diagnostics only; they do not authorize direct T00 scaling or assert that a boundary point is dynamically, causally, or materially realizable.",
      "Physical viability, transport, propulsion, route ETA, and certified-speed claims remain blocked pending separate theory-closure and empirical receipts.",
    ],
  },
  {
    badgeId: "nhm2.qei.sampling_window",
    kind: "runtime_bound_output",
    runtimeId: "qei_stress_energy.artifact_reader",
    laneId: "qei_stress_energy",
    artifactFields: [
      "qei_bound",
      "qei_sample",
      "qei_margin",
      "marginRatio",
      "tauSelected",
      "tauWindow",
    ],
    scalarCuts: [
      {
        id: "qei_margin_difference_cut",
        expression: "qei_margin = qei_bound - qei_sample",
        displayLatex: "margin_{qei}=bound_{qei}-sample_{qei}",
        outputSymbols: ["qei_margin"],
      },
      {
        id: "tau_margin_cut",
        expression: "tau_margin = tauWindow - tauSelected",
        displayLatex: "margin_{\\tau}=\\tau_{window}-\\tau_{selected}",
        outputSymbols: ["tau_margin"],
      },
    ],
    gates: [
      "timelike_worldline",
      "hadamard_state",
      "point_splitting",
      "unit_integral_sampling",
      "operator_mapping",
      "semantic_bridge",
      "qei_margin",
    ],
    requiredEvidence: [
      "qei_worldline_dossier",
      "operator_mapping",
      "semantic_bridge",
      "sampling_normalization",
    ],
    claimBoundaryNotes: [
      "QEI sampling values are runtime-bound applicability diagnostics and must fail closed when semantics are missing.",
    ],
  },
  {
    badgeId: "nhm2.qei.worldline_dossier",
    kind: "runtime_gate",
    runtimeId: "qei_stress_energy.artifact_reader",
    laneId: "qei_stress_energy",
    artifactFields: [
      "worldline",
      "samplingFunction",
      "rhoSource",
      "qeiBoundSource",
      "regionalMargins",
      "dutyLightCrossingConsistency",
    ],
    scalarCuts: [],
    gates: [
      "timelike_worldline",
      "sampling_normalization",
      "operator_mapping",
      "qei_margin",
      "qei_dossier",
    ],
    requiredEvidence: [
      "qei_worldline_dossier",
      "sampling_normalization",
      "operator_mapping",
      "regional_margin_report",
    ],
    claimBoundaryNotes: [
      "QEI worldline dossier is a blocked provenance gate until worldline, sampling, source, bound, and regional margin receipts exist.",
    ],
  },
  {
    badgeId: "nhm2.natario.curvature_invariants",
    kind: "runtime_bound_output",
    runtimeId: "gr_nhm2.artifact_reader",
    laneId: "warp_gr_nhm2",
    artifactFields: [
      "weylScalar",
      "ricciInvariant",
      "petrovClass",
      "momentumDensity",
      "natarioInvariantStatus",
    ],
    scalarCuts: [],
    gates: ["observer_audit", "tensor_authority", "curvature_invariants"],
    requiredEvidence: [
      "curvature_invariant_report",
      "observer_audit",
      "metric_t0i_emission",
    ],
    claimBoundaryNotes: [
      "Natario curvature invariants are runtime targets and cannot promote NHM2 without observer and tensor authority.",
    ],
  },
  {
    badgeId: "nhm2.natario.invariant_audit",
    kind: "runtime_gate",
    runtimeId: "gr_nhm2.artifact_reader",
    laneId: "warp_gr_nhm2",
    artifactFields: [
      "nhm2NatarioInvariantAudit.contractVersion",
      "nhm2NatarioInvariantAudit.expansion.thetaMaxAbs",
      "nhm2NatarioInvariantAudit.expansion.thetaFlatnessStatus",
      "nhm2NatarioInvariantAudit.expansion.expansionLeakageBound",
      "nhm2NatarioInvariantAudit.invariants.ricciScalar",
      "nhm2NatarioInvariantAudit.invariants.kretschmannScalar",
      "nhm2NatarioInvariantAudit.invariants.weylScalarProxy",
      "nhm2NatarioInvariantAudit.invariants.petrovClass",
      "nhm2NatarioInvariantAudit.invariants.status",
      "nhm2NatarioInvariantAudit.momentumDensity.Jx",
      "nhm2NatarioInvariantAudit.momentumDensity.Jy",
      "nhm2NatarioInvariantAudit.momentumDensity.Jz",
      "nhm2NatarioInvariantAudit.momentumDensity.status",
      "nhm2NatarioInvariantAudit.stability.tidalMax",
      "nhm2NatarioInvariantAudit.stability.blueshiftMax",
      "nhm2NatarioInvariantAudit.stability.convergenceStatus",
      "nhm2NatarioInvariantAudit.blockers",
    ],
    scalarCuts: [],
    gates: [
      "natario_invariant_audit",
      "curvature_invariants",
      "observer_audit",
    ],
    requiredEvidence: [
      "natario_invariant_audit_artifact",
      "curvature_invariant_report",
      "momentum_density_report",
      "stability_diagnostic_report",
    ],
    claimBoundaryNotes: [
      "Natario zero-expansion status is separate from curvature, momentum-density, tidal, blueshift, and convergence diagnostics.",
    ],
  },
  {
    badgeId: "nhm2.energy_condition.observer_robust_gate",
    kind: "runtime_gate",
    runtimeId: "qei_stress_energy.artifact_reader",
    laneId: "qei_stress_energy",
    artifactFields: [
      "nhm2ObserverRobustEnergyConditions.contractVersion",
      "nhm2ObserverRobustEnergyConditions.tensorRef",
      "nhm2ObserverRobustEnergyConditions.observerFamilies[].familyId",
      "nhm2ObserverRobustEnergyConditions.observerFamilies[].status",
      "nhm2ObserverRobustEnergyConditions.observerFamilies[].sampleCount",
      "nhm2ObserverRobustEnergyConditions.observerFamilies[].optimizerUsed",
      "nhm2ObserverRobustEnergyConditions.observerFamilies[].worstCase.condition",
      "nhm2ObserverRobustEnergyConditions.observerFamilies[].worstCase.value",
      "nhm2ObserverRobustEnergyConditions.summary.eulerianOnly",
      "nhm2ObserverRobustEnergyConditions.summary.robustCheckComplete",
      "nhm2ObserverRobustEnergyConditions.summary.anyViolation",
      "nhm2ObserverRobustEnergyConditions.summary.missedViolationRisk",
    ],
    scalarCuts: [],
    gates: [
      "observer_audit",
      "observer_robust_energy_conditions",
      "tensor_authority",
    ],
    requiredEvidence: [
      "observer_robust_energy_conditions_artifact",
      "same_chart_full_tensor_artifact",
      "observer_family_samples",
    ],
    claimBoundaryNotes: [
      "Eulerian-only energy-condition checks must be labeled as restricted-frame checks and cannot be presented as observer-robust.",
    ],
  },
  {
    badgeId: "nhm2.energy_condition.diagnostic_gate",
    kind: "runtime_gate",
    runtimeId: "qei_stress_energy.artifact_reader",
    laneId: "qei_stress_energy",
    artifactFields: [
      "gateStatus",
      "gateDetails",
      "missingSignals",
      "requiredSignals",
    ],
    scalarCuts: [],
    gates: [
      "source_closure",
      "qei_applicability",
      "observer_audit",
      "hard_constraints",
      "qei_margin",
    ],
    requiredEvidence: [
      "source_closure_artifact",
      "qei_worldline_dossier",
      "observer_audit",
    ],
    claimBoundaryNotes: [
      "Energy-condition gate badges are gate summaries, not calculator validations.",
    ],
  },
  {
    badgeId: "nhm2.claim_boundary.diagnostic_only",
    kind: "claim_boundary",
    runtimeId: "gr_nhm2.artifact_reader",
    laneId: "warp_gr_nhm2",
    artifactFields: [
      "claimPosture",
      "promotionBlockedBy",
      "certificateIntegrity",
      "certificateIssued",
    ],
    scalarCuts: [],
    gates: ["certificate_issued", "certificate_integrity"],
    requiredEvidence: [...NHM2_PROMOTION_EVIDENCE],
    claimBoundaryNotes: [
      "NHM2 remains diagnostic unless source closure, observer audit, QEI dossier, certificate issuance, and certificate integrity are all present and passing.",
    ],
  },
];

export function getNhm2RuntimeFieldBinding(
  badgeId: string,
): Nhm2RuntimeFieldBinding | null {
  return (
    NHM2_RUNTIME_FIELD_BINDINGS.find(
      (binding) => binding.badgeId === badgeId,
    ) ?? null
  );
}

export function findNhm2RuntimeFieldBindingsForGate(
  gateId: string,
): Nhm2RuntimeFieldBinding[] {
  return NHM2_RUNTIME_FIELD_BINDINGS.filter((binding) =>
    binding.gates.includes(gateId),
  );
}

export function isNhm2RuntimeBoundBadge(badgeId: string): boolean {
  const binding = getNhm2RuntimeFieldBinding(badgeId);
  return Boolean(binding && binding.kind !== "model_relation");
}
