import {
  type TheoryBadgeClaimBoundaryV1,
  type TheoryBadgeEdgeV1,
  type TheoryBadgeV1,
} from "../contracts/theory-badge-graph.v1";
import type { ElementOriginFamily } from "../periodic-table";

export const NUCLEOSYNTHESIS_ORIGIN_BADGE_BY_FAMILY: Record<ElementOriginFamily, string> = {
  big_bang_nucleosynthesis: "nucleosynthesis.big_bang.light_elements",
  hydrogen_burning: "nucleosynthesis.hydrogen_burning.helium_production",
  helium_burning_triple_alpha: "nucleosynthesis.helium_burning.triple_alpha_carbon",
  alpha_capture: "nucleosynthesis.alpha_capture.oxygen_neon_magnesium",
  advanced_stellar_burning: "nucleosynthesis.advanced_burning.iron_peak",
  explosive_nucleosynthesis: "nucleosynthesis.explosive_burning.supernova_yields",
  cosmic_ray_spallation: "nucleosynthesis.spallation.li_be_b",
  s_process: "nucleosynthesis.s_process.slow_neutron_capture",
  r_process: "nucleosynthesis.r_process.rapid_neutron_capture",
  p_process_or_photodisintegration: "nucleosynthesis.p_process.photodisintegration_context",
  radioactive_decay_chain: "nucleosynthesis.decay_chain.radioactive_inheritance",
  synthetic_lab: "nucleosynthesis.synthetic.superheavy_lab",
};

const ORIGIN_BOUNDARY: TheoryBadgeClaimBoundaryV1 = {
  diagnosticOnly: true,
  doesValidateNHM2: false,
  validationClaimAllowed: false,
  physicalMechanismClaimAllowed: false,
  promotionAllowed: false,
};

const literatureRef = (id: string, note?: string): TheoryBadgeV1["sourceRefs"][number] => ({
  kind: "literature_ref",
  id,
  note: note ?? null,
});

const docRef = (path: string, id?: string, note?: string): TheoryBadgeV1["sourceRefs"][number] => ({
  kind: "doc",
  path,
  id: id ?? null,
  note: note ?? null,
});

const originBadge = (badge: Omit<TheoryBadgeV1, "claimBoundary">): TheoryBadgeV1 => ({
  ...badge,
  claimBoundary: ORIGIN_BOUNDARY,
});

const commonAssumptions = [
  "Origin-family rows are diagnostic context for element production channels.",
  "Element origin does not prove molecular formation, prebiotic success, biology, consciousness, or objective collapse.",
  "Production channels can be isotope- and environment-dependent; element badges may carry multiple origin families.",
];

export const NUCLEOSYNTHESIS_ORIGIN_THEORY_BADGES: TheoryBadgeV1[] = [
  originBadge({
    id: "nucleosynthesis.big_bang.light_elements",
    title: "Big Bang Light-Element Nucleosynthesis",
    plainMeaning: "Represents early-universe production context for the lightest nuclei.",
    whyItMatters: "It anchors hydrogen, helium, and lithium context before stellar chemical evolution enters the graph.",
    subjects: ["nucleosynthesis", "big_bang", "light_elements", "isotopic_abundance"],
    level: "first_principle",
    status: "canonical_reference",
    simulationOwners: ["stellar_reference"],
    equationFamilies: ["big_bang_nucleosynthesis", "abundance_context"],
    tags: ["light_elements", "isotopic_abundance", "canonical_reference"],
    equations: [
      {
        id: "big_bang_light_element_context",
        role: "noncomputable_reference",
        displayLatex: "Y_{light}=\\mathrm{BBN}(\\eta,T,t)",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["eta", "T", "t"],
        outputSymbols: ["Y_light"],
      },
    ],
    units: [{ symbol: "Y_light", quantity: "light_element_abundance", dimensionSignature: "1" }],
    assumptions: commonAssumptions,
    calculatorPayloads: [],
    sourceRefs: [
      literatureRef("doi:10.1086/149126", "Wagoner, Fowler, and Hoyle very-high-temperature synthesis reference."),
    ],
    hintKeys: {
      subjects: ["nucleosynthesis", "big_bang", "light_elements"],
      symbols: ["Y_light", "eta", "T", "t"],
      unitSignatures: ["1"],
      repoPaths: [],
      equationFamilies: ["big_bang_nucleosynthesis"],
      simulationOwners: ["stellar_reference"],
    },
  }),
  originBadge({
    id: "nucleosynthesis.hydrogen_burning.helium_production",
    title: "Hydrogen Burning Helium Production",
    plainMeaning: "Represents proton-proton and CNO-cycle hydrogen burning as helium-production context.",
    whyItMatters: "It prevents prompts from treating hydrogen burning as direct oxygen production.",
    subjects: ["nucleosynthesis", "hydrogen_burning", "helium", "cno_cycle", "proton_proton_chain"],
    level: "law",
    status: "canonical_reference",
    simulationOwners: ["stellar_reference", "starsim"],
    equationFamilies: ["hydrogen_burning", "stellar_energy_generation"],
    tags: ["hydrogen_burning", "helium_production", "coulomb_barrier", "quantum_tunneling"],
    equations: [
      {
        id: "hydrogen_burning_context",
        role: "noncomputable_reference",
        displayLatex: "4p\\rightarrow{}^{4}\\mathrm{He}+2e^{+}+2\\nu_e+\\gamma",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["p"],
        outputSymbols: ["He4", "nu_e"],
      },
    ],
    units: [],
    assumptions: [
      ...commonAssumptions,
      "Fusion entrance is limited by Coulomb repulsion; the strong interaction binds nuclei only at short range.",
      "Hydrogen burning primarily produces helium, not direct oxygen production.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      literatureRef("doi:10.1103/PhysRev.55.434", "Bethe stellar energy-production reference."),
      literatureRef("doi:10.1103/RevModPhys.29.547", "B2FH stellar nucleosynthesis review."),
    ],
    hintKeys: {
      subjects: ["nucleosynthesis", "hydrogen_burning", "helium", "cno_cycle"],
      symbols: ["p", "He4", "nu_e"],
      unitSignatures: [],
      repoPaths: [],
      equationFamilies: ["hydrogen_burning"],
      simulationOwners: ["stellar_reference", "starsim"],
    },
  }),
  originBadge({
    id: "nucleosynthesis.helium_burning.triple_alpha_carbon",
    title: "Triple-Alpha Carbon Production",
    plainMeaning: "Represents helium-burning carbon synthesis through the triple-alpha channel.",
    whyItMatters: "It anchors carbon-origin badges before aromatic carbon or prebiotic chemistry context is discussed.",
    subjects: ["nucleosynthesis", "helium_burning", "triple_alpha", "carbon"],
    level: "law",
    status: "canonical_reference",
    simulationOwners: ["stellar_reference"],
    equationFamilies: ["helium_burning", "triple_alpha"],
    tags: ["carbon_origin", "helium_burning"],
    equations: [
      {
        id: "triple_alpha_context",
        role: "noncomputable_reference",
        displayLatex: "3{}^{4}\\mathrm{He}\\rightarrow{}^{12}\\mathrm{C}+\\gamma",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["He4"],
        outputSymbols: ["C12"],
      },
    ],
    units: [],
    assumptions: commonAssumptions,
    calculatorPayloads: [],
    sourceRefs: [
      literatureRef("doi:10.1103/RevModPhys.29.547", "B2FH stellar nucleosynthesis review."),
      literatureRef("1954ApJS....1..121H", "Hoyle carbon-to-nickel synthesis context."),
    ],
    hintKeys: {
      subjects: ["nucleosynthesis", "helium_burning", "triple_alpha", "carbon"],
      symbols: ["He4", "C12"],
      unitSignatures: [],
      repoPaths: [],
      equationFamilies: ["helium_burning", "triple_alpha"],
      simulationOwners: ["stellar_reference"],
    },
  }),
  originBadge({
    id: "nucleosynthesis.alpha_capture.oxygen_neon_magnesium",
    title: "Alpha-Capture Oxygen-Neon-Magnesium Context",
    plainMeaning: "Represents alpha-capture pathways that populate oxygen and neighboring alpha elements.",
    whyItMatters: "It anchors oxygen origin separately from hydrogen burning and before molecular water context.",
    subjects: ["nucleosynthesis", "alpha_capture", "oxygen", "neon", "magnesium"],
    level: "derived_relation",
    status: "canonical_reference",
    simulationOwners: ["stellar_reference"],
    equationFamilies: ["alpha_capture", "stellar_nucleosynthesis"],
    tags: ["oxygen_origin", "alpha_element"],
    equations: [
      {
        id: "alpha_capture_context",
        role: "noncomputable_reference",
        displayLatex: "{}^{12}\\mathrm{C}(\\alpha,\\gamma){}^{16}\\mathrm{O}",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["C12", "alpha"],
        outputSymbols: ["O16"],
      },
    ],
    units: [],
    assumptions: commonAssumptions,
    calculatorPayloads: [],
    sourceRefs: [
      literatureRef("1954ApJS....1..121H", "Hoyle advanced stellar reaction context."),
      literatureRef("doi:10.1103/RevModPhys.29.547", "B2FH stellar nucleosynthesis review."),
      literatureRef("2020ApJ...900..179K", "Modern element-origin and chemical-evolution context."),
    ],
    hintKeys: {
      subjects: ["nucleosynthesis", "alpha_capture", "oxygen", "alpha_element"],
      symbols: ["C12", "alpha", "O16"],
      unitSignatures: [],
      repoPaths: [],
      equationFamilies: ["alpha_capture"],
      simulationOwners: ["stellar_reference"],
    },
  }),
  originBadge({
    id: "nucleosynthesis.advanced_burning.iron_peak",
    title: "Advanced Stellar Burning Iron-Peak Context",
    plainMeaning: "Represents late stellar burning stages that populate iron-peak context.",
    whyItMatters: "It keeps iron-peak production separate from energy-producing fusion beyond iron.",
    subjects: ["nucleosynthesis", "advanced_burning", "iron_peak", "massive_stars"],
    level: "derived_relation",
    status: "canonical_reference",
    simulationOwners: ["stellar_reference"],
    equationFamilies: ["advanced_stellar_burning", "iron_peak"],
    tags: ["iron_peak", "advanced_burning"],
    equations: [
      {
        id: "iron_peak_context",
        role: "noncomputable_reference",
        displayLatex: "Y_{Fe\\ peak}=\\mathrm{context}(T,\\rho,\\mathrm{burning\\ stage})",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["T", "rho", "burning_stage"],
        outputSymbols: ["Y_Fe_peak"],
      },
    ],
    units: [{ symbol: "Y_Fe_peak", quantity: "iron_peak_abundance_context", dimensionSignature: "1" }],
    assumptions: commonAssumptions,
    calculatorPayloads: [],
    sourceRefs: [
      literatureRef("1954ApJS....1..121H", "Hoyle carbon-to-nickel synthesis context."),
      literatureRef("doi:10.1103/RevModPhys.29.547", "B2FH stellar nucleosynthesis review."),
      literatureRef("2020ApJ...900..179K", "Modern element-origin and chemical-evolution context."),
    ],
    hintKeys: {
      subjects: ["nucleosynthesis", "advanced_burning", "iron_peak"],
      symbols: ["Y_Fe_peak", "T", "rho"],
      unitSignatures: ["1"],
      repoPaths: [],
      equationFamilies: ["advanced_stellar_burning", "iron_peak"],
      simulationOwners: ["stellar_reference"],
    },
  }),
  originBadge({
    id: "nucleosynthesis.explosive_burning.supernova_yields",
    title: "Explosive Nucleosynthesis Supernova Yields",
    plainMeaning: "Represents explosive stellar-event yields as element-origin context.",
    whyItMatters: "It provides a bounded route for elements whose origin depends on explosive burning or event ejecta.",
    subjects: ["nucleosynthesis", "supernova", "explosive_nucleosynthesis", "stellar_yields"],
    level: "model",
    status: "diagnostic",
    simulationOwners: ["stellar_reference"],
    equationFamilies: ["explosive_nucleosynthesis", "stellar_yields"],
    tags: ["supernova_yields", "event_context"],
    equations: [
      {
        id: "explosive_yield_context",
        role: "noncomputable_reference",
        displayLatex: "Y_i=\\mathrm{yield}_i(M,Z,E_{explosion})",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["M", "Z", "E_explosion"],
        outputSymbols: ["Y_i"],
      },
    ],
    units: [{ symbol: "Y_i", quantity: "element_yield", dimensionSignature: "1" }],
    assumptions: commonAssumptions,
    calculatorPayloads: [],
    sourceRefs: [
      literatureRef("AECL-CRL-41", "Cameron nucleogenesis and stellar-evolution context."),
      literatureRef("doi:10.1103/RevModPhys.29.547", "B2FH stellar nucleosynthesis review."),
      literatureRef("2020ApJ...900..179K", "Modern element-origin and chemical-evolution context."),
    ],
    hintKeys: {
      subjects: ["nucleosynthesis", "supernova", "explosive_nucleosynthesis", "stellar_yields"],
      symbols: ["Y_i", "M", "Z", "E_explosion"],
      unitSignatures: ["1"],
      repoPaths: [],
      equationFamilies: ["explosive_nucleosynthesis", "stellar_yields"],
      simulationOwners: ["stellar_reference"],
    },
  }),
  originBadge({
    id: "nucleosynthesis.spallation.li_be_b",
    title: "Cosmic-Ray Spallation Li-Be-B Context",
    plainMeaning: "Represents cosmic-ray spallation production context for lithium, beryllium, and boron.",
    whyItMatters: "It prevents Li-Be-B from being flattened into ordinary stellar fusion products.",
    subjects: ["nucleosynthesis", "cosmic_ray_spallation", "lithium", "beryllium", "boron"],
    level: "model",
    status: "diagnostic",
    simulationOwners: ["stellar_reference"],
    equationFamilies: ["cosmic_ray_spallation", "light_element_origin"],
    tags: ["li_be_b", "spallation"],
    equations: [
      {
        id: "spallation_context",
        role: "noncomputable_reference",
        displayLatex: "\\mathrm{CNO}+\\mathrm{GCR}\\rightarrow\\mathrm{LiBeB}+X",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["CNO", "GCR"],
        outputSymbols: ["LiBeB"],
      },
    ],
    units: [],
    assumptions: commonAssumptions,
    calculatorPayloads: [],
    sourceRefs: [literatureRef("OSTI:6532243", "Cosmic synthesis of lithium, beryllium, and boron.")],
    hintKeys: {
      subjects: ["nucleosynthesis", "cosmic_ray_spallation", "lithium", "beryllium", "boron"],
      symbols: ["CNO", "GCR", "LiBeB"],
      unitSignatures: [],
      repoPaths: [],
      equationFamilies: ["cosmic_ray_spallation"],
      simulationOwners: ["stellar_reference"],
    },
  }),
  originBadge({
    id: "nucleosynthesis.s_process.slow_neutron_capture",
    title: "Slow Neutron-Capture Process",
    plainMeaning: "Represents s-process neutron capture in AGB and massive-star environments.",
    whyItMatters: "It gives heavy-element badges a slow-capture route distinct from r-process context.",
    subjects: ["nucleosynthesis", "s_process", "neutron_capture", "agb_stars", "heavy_elements"],
    level: "model",
    status: "canonical_reference",
    simulationOwners: ["stellar_reference"],
    equationFamilies: ["s_process", "neutron_capture"],
    tags: ["slow_neutron_capture", "heavy_elements"],
    equations: [
      {
        id: "s_process_context",
        role: "noncomputable_reference",
        displayLatex: "(Z,A)+n\\rightarrow(Z,A+1)+\\gamma",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["seed_nucleus", "n"],
        outputSymbols: ["s_process_product"],
      },
    ],
    units: [],
    assumptions: commonAssumptions,
    calculatorPayloads: [],
    sourceRefs: [
      literatureRef("doi:10.1103/RevModPhys.83.157", "s-process review."),
      literatureRef("doi:10.1103/RevModPhys.29.547", "B2FH stellar nucleosynthesis review."),
    ],
    hintKeys: {
      subjects: ["nucleosynthesis", "s_process", "neutron_capture", "heavy_elements"],
      symbols: ["seed_nucleus", "n", "s_process_product"],
      unitSignatures: [],
      repoPaths: [],
      equationFamilies: ["s_process", "neutron_capture"],
      simulationOwners: ["stellar_reference"],
    },
  }),
  originBadge({
    id: "nucleosynthesis.r_process.rapid_neutron_capture",
    title: "Rapid Neutron-Capture Process",
    plainMeaning: "Represents rapid neutron-capture context for many heavy elements from iron-group seeds toward uranium.",
    whyItMatters: "It anchors gold, uranium, and other heavy-element badges in a distinct high-neutron-flux channel.",
    subjects: ["nucleosynthesis", "r_process", "neutron_capture", "heavy_elements", "kilonova"],
    level: "model",
    status: "canonical_reference",
    simulationOwners: ["stellar_reference"],
    equationFamilies: ["r_process", "neutron_capture"],
    tags: ["rapid_neutron_capture", "heavy_elements"],
    equations: [
      {
        id: "r_process_context",
        role: "noncomputable_reference",
        displayLatex: "(Z,A)+n\\xrightarrow{rapid}(Z,A+k)\\xrightarrow{\\beta^-}\\mathrm{heavy\\ element}",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["seed_nucleus", "n"],
        outputSymbols: ["r_process_product"],
      },
    ],
    units: [],
    assumptions: commonAssumptions,
    calculatorPayloads: [],
    sourceRefs: [
      literatureRef("doi:10.1103/RevModPhys.93.015002", "r-process review."),
      literatureRef("doi:10.1103/RevModPhys.29.547", "B2FH stellar nucleosynthesis review."),
    ],
    hintKeys: {
      subjects: ["nucleosynthesis", "r_process", "neutron_capture", "heavy_elements", "kilonova"],
      symbols: ["seed_nucleus", "n", "r_process_product"],
      unitSignatures: [],
      repoPaths: [],
      equationFamilies: ["r_process", "neutron_capture"],
      simulationOwners: ["stellar_reference"],
    },
  }),
  originBadge({
    id: "nucleosynthesis.p_process.photodisintegration_context",
    title: "p-Process Photodisintegration Context",
    plainMeaning: "Represents p-process or photodisintegration context for proton-rich isotope families.",
    whyItMatters: "It preserves isotope-specific origin ambiguity rather than forcing all heavy elements into s- or r-process only.",
    subjects: ["nucleosynthesis", "p_process", "photodisintegration", "proton_rich_isotopes"],
    level: "model",
    status: "review",
    simulationOwners: ["stellar_reference"],
    equationFamilies: ["p_process", "photodisintegration"],
    tags: ["isotope_specific", "review"],
    equations: [
      {
        id: "p_process_context",
        role: "noncomputable_reference",
        displayLatex: "(\\gamma,n),(\\gamma,p),(\\gamma,\\alpha)",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["gamma", "seed_nucleus"],
        outputSymbols: ["p_process_product"],
      },
    ],
    units: [],
    assumptions: commonAssumptions,
    calculatorPayloads: [],
    sourceRefs: [
      literatureRef("doi:10.1103/RevModPhys.29.547", "B2FH stellar nucleosynthesis review."),
      literatureRef("2020ApJ...900..179K", "Modern element-origin and chemical-evolution context."),
    ],
    hintKeys: {
      subjects: ["nucleosynthesis", "p_process", "photodisintegration"],
      symbols: ["gamma", "seed_nucleus", "p_process_product"],
      unitSignatures: [],
      repoPaths: [],
      equationFamilies: ["p_process", "photodisintegration"],
      simulationOwners: ["stellar_reference"],
    },
  }),
  originBadge({
    id: "nucleosynthesis.decay_chain.radioactive_inheritance",
    title: "Radioactive Decay-Chain Inheritance",
    plainMeaning: "Represents radioactive inheritance and decay-chain context for unstable heavy elements.",
    whyItMatters: "It lets actinide badges distinguish production routes from later decay-chain observables.",
    subjects: ["nucleosynthesis", "radioactive_decay", "actinides", "heavy_elements"],
    level: "model",
    status: "diagnostic",
    simulationOwners: ["stellar_reference"],
    equationFamilies: ["radioactive_decay_chain", "heavy_element_context"],
    tags: ["decay_chain", "actinide_context"],
    equations: [
      {
        id: "decay_chain_context",
        role: "noncomputable_reference",
        displayLatex: "N(t)=N_0 e^{-\\lambda t}",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["N_0", "lambda", "t"],
        outputSymbols: ["N_t"],
      },
    ],
    units: [{ symbol: "lambda", quantity: "decay_constant", dimensionSignature: "T^-1" }],
    assumptions: commonAssumptions,
    calculatorPayloads: [],
    sourceRefs: [
      literatureRef("doi:10.1103/RevModPhys.93.015002", "r-process and heavy-element context."),
      literatureRef("2020ApJ...900..179K", "Modern element-origin and chemical-evolution context."),
    ],
    hintKeys: {
      subjects: ["nucleosynthesis", "radioactive_decay", "actinides"],
      symbols: ["N_0", "lambda", "t", "N_t"],
      unitSignatures: ["T^-1"],
      repoPaths: [],
      equationFamilies: ["radioactive_decay_chain"],
      simulationOwners: ["stellar_reference"],
    },
  }),
  originBadge({
    id: "nucleosynthesis.synthetic.superheavy_lab",
    title: "Synthetic Superheavy Laboratory Context",
    plainMeaning: "Represents laboratory synthesis context for superheavy elements.",
    whyItMatters: "It prevents synthetic superheavy badges from being treated as naturally abundant astrophysical products.",
    subjects: ["nucleosynthesis", "synthetic_lab", "superheavy_elements", "laboratory_decay_chain"],
    level: "diagnostic_gate",
    status: "diagnostic",
    simulationOwners: ["stellar_reference"],
    equationFamilies: ["synthetic_lab", "superheavy_elements"],
    tags: ["superheavy", "laboratory_synthesis", "claim_boundary"],
    equations: [
      {
        id: "superheavy_synthesis_context",
        role: "noncomputable_reference",
        displayLatex: "\\mathrm{target}+\\mathrm{beam}\\rightarrow\\mathrm{superheavy\\ nucleus}+xn",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["target", "beam"],
        outputSymbols: ["superheavy_nucleus"],
      },
    ],
    units: [],
    assumptions: [
      ...commonAssumptions,
      "Superheavy element badges are laboratory-synthesis context unless a source explicitly supports natural occurrence.",
    ],
    calculatorPayloads: [],
    sourceRefs: [literatureRef("doi:10.1103/RevModPhys.91.011001", "Superheavy elements review.")],
    hintKeys: {
      subjects: ["nucleosynthesis", "synthetic_lab", "superheavy_elements"],
      symbols: ["target", "beam", "superheavy_nucleus"],
      unitSignatures: [],
      repoPaths: [],
      equationFamilies: ["synthetic_lab", "superheavy_elements"],
      simulationOwners: ["stellar_reference"],
    },
  }),
];

export const NUCLEOSYNTHESIS_ORIGIN_THEORY_EDGES: TheoryBadgeEdgeV1[] = [
  {
    id: "hydrogen_burning_documents_starsim_yield_prior",
    from: "nucleosynthesis.hydrogen_burning.helium_production",
    to: "starsim.nucleosynthesis.element_yield_prior",
    relation: "documents",
    label: "Hydrogen-burning context documents reduced-order stellar yield priors.",
    claimBoundaryNote: "Hydrogen-burning rows do not directly produce oxygen or heavier element claims.",
  },
  {
    id: "triple_alpha_documents_aromatic_carbon_context",
    from: "nucleosynthesis.helium_burning.triple_alpha_carbon",
    to: "astrochemistry.aromatic_carbon.interstellar_context",
    relation: "documents",
    label: "Triple-alpha carbon context documents later aromatic carbon discussions.",
    claimBoundaryNote: "Carbon origin context is not prebiotic success or biology evidence.",
  },
  {
    id: "alpha_capture_documents_molecular_cloud_inheritance",
    from: "nucleosynthesis.alpha_capture.oxygen_neon_magnesium",
    to: "astrochemistry.molecular_cloud.elemental_inheritance_context",
    relation: "documents",
    label: "Alpha-capture oxygen context documents inherited molecular-cloud element inventories.",
    claimBoundaryNote: "Elemental oxygen context does not guarantee water formation.",
  },
];

export function buildNucleosynthesisOriginTheoryBadgesV1(): {
  badges: TheoryBadgeV1[];
  edges: TheoryBadgeEdgeV1[];
} {
  return {
    badges: NUCLEOSYNTHESIS_ORIGIN_THEORY_BADGES.map((badge) => ({ ...badge })),
    edges: NUCLEOSYNTHESIS_ORIGIN_THEORY_EDGES.map((edge) => ({ ...edge })),
  };
}
