import {
  type TheoryBadgeClaimBoundaryV1,
  type TheoryBadgeEdgeV1,
  type TheoryBadgeV1,
} from "../contracts/theory-badge-graph.v1";

const PHASE_BOUNDARY: TheoryBadgeClaimBoundaryV1 = {
  diagnosticOnly: true,
  doesValidateNHM2: false,
  validationClaimAllowed: false,
  physicalMechanismClaimAllowed: false,
  promotionAllowed: false,
};

const literatureRef = (id: string, note?: string): TheoryBadgeV1["sourceRefs"][number] => ({
  kind: "literature_ref",
  id,
  note: note ?? null,
});

const phaseBadge = (badge: Omit<TheoryBadgeV1, "claimBoundary">): TheoryBadgeV1 => ({
  ...badge,
  claimBoundary: PHASE_BOUNDARY,
});

export const PHASE_OF_MATTER_THEORY_BADGES: TheoryBadgeV1[] = [
  phaseBadge({
    id: "matter.phase.composition_identity_context",
    title: "Composition Identity Across Phases",
    plainMeaning:
      "Represents the rule that an element or molecule can persist across ordinary phase changes while its arrangement changes.",
    whyItMatters:
      "It keeps identity, phase, and structure separate so phase badges do not accidentally become chemical or nuclear reaction claims.",
    subjects: ["matter", "phase", "composition_identity", "chemistry"],
    level: "first_principle",
    status: "canonical_reference",
    simulationOwners: ["general_physics", "astrochemistry_prebiotic"],
    equationFamilies: ["composition_identity", "phase_context"],
    tags: ["phase_of_matter", "composition_identity", "claim_boundary"],
    equations: [
      {
        id: "composition_identity_phase_context",
        role: "noncomputable_reference",
        displayLatex: "\\mathrm{identity}=\\mathrm{context}(\\mathrm{composition},\\mathrm{reaction\\ boundary})",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["composition", "reaction_boundary"],
        outputSymbols: ["composition_identity_context"],
      },
    ],
    units: [{ symbol: "composition", unit: null, quantity: "chemical_identity", dimensionSignature: "1" }],
    assumptions: [
      "Ordinary phase changes preserve composition identity unless a chemical reaction, ionization, dissociation, isotope change, or nuclear reaction is admitted as separate evidence.",
      "Element-origin badges provide composition context, not a phase, structure, or density solve.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      literatureRef("Gibbs 1876 heterogeneous substances", "Classical thermodynamic phase-equilibrium foundation."),
      literatureRef("Atkins physical chemistry phase equilibrium", "Reference chemistry framing for phase and composition identity."),
    ],
    hintKeys: {
      subjects: ["matter", "phase", "composition_identity", "chemistry"],
      symbols: ["composition", "reaction_boundary", "composition_identity_context"],
      unitSignatures: ["1"],
      repoPaths: [],
      equationFamilies: ["composition_identity", "phase_context"],
      simulationOwners: ["general_physics", "astrochemistry_prebiotic"],
    },
  }),
  phaseBadge({
    id: "matter.phase.thermodynamic_state_context",
    title: "Thermodynamic State Phase Context",
    plainMeaning:
      "Represents phase as a condition-dependent state selected by temperature, pressure, composition, and relevant intensive variables.",
    whyItMatters:
      "It lets Helix ask for temperature and pressure conditions before assigning solid, liquid, gas, plasma, supercritical, or mixed-state meaning.",
    subjects: ["matter", "phase", "thermodynamics", "temperature", "pressure"],
    level: "law",
    status: "canonical_reference",
    simulationOwners: ["general_physics"],
    equationFamilies: ["thermodynamic_state", "phase_equilibrium"],
    tags: ["phase_of_matter", "temperature", "pressure", "conditioned_state"],
    equations: [
      {
        id: "phase_state_context",
        role: "noncomputable_reference",
        displayLatex: "\\alpha=\\mathrm{phase}(T,P,x_i,\\mu_i,\\mathrm{boundary})",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["T_K", "P_Pa", "x_i", "mu_i", "phase_boundary"],
        outputSymbols: ["phase_alpha"],
      },
    ],
    units: [
      { symbol: "T_K", unit: "K", quantity: "temperature", dimensionSignature: "Theta" },
      { symbol: "P_Pa", unit: "Pa", quantity: "pressure", dimensionSignature: "M L^-1 T^-2" },
      { symbol: "x_i", unit: null, quantity: "composition_fraction", dimensionSignature: "1" },
    ],
    assumptions: [
      "A phase label is condition-dependent and may require an equilibrium model, phase diagram, or measured state table.",
      "Temperature and pressure constrain phase; they do not alone determine molecular structure for every material without composition and boundary context.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      literatureRef("Gibbs 1876 heterogeneous substances", "Equilibrium and phase-rule foundation."),
      literatureRef("Callen thermodynamics", "Thermodynamic state variable reference."),
    ],
    hintKeys: {
      subjects: ["matter", "phase", "thermodynamics", "temperature", "pressure"],
      symbols: ["T_K", "P_Pa", "x_i", "mu_i", "phase_alpha"],
      unitSignatures: ["Theta", "M L^-1 T^-2", "1"],
      repoPaths: [],
      equationFamilies: ["thermodynamic_state", "phase_equilibrium"],
      simulationOwners: ["general_physics"],
    },
  }),
  phaseBadge({
    id: "matter.phase.equation_of_state_density_context",
    title: "Equation-Of-State Density Context",
    plainMeaning:
      "Represents bulk density as a condition-dependent property from an equation of state, measured table, or simulation receipt.",
    whyItMatters:
      "It blocks the unsafe shortcut from quantum frequency or rest energy directly to phase density without EOS or structural evidence.",
    subjects: ["matter", "phase", "density", "equation_of_state", "thermodynamics"],
    level: "model",
    status: "canonical_reference",
    simulationOwners: ["general_physics", "astrochemistry_prebiotic"],
    equationFamilies: ["equation_of_state", "mass_density", "phase_context"],
    tags: ["density", "equation_of_state", "phase_of_matter", "conditioned_state"],
    equations: [
      {
        id: "phase_density_eos_context",
        role: "noncomputable_reference",
        displayLatex: "\\rho_m=\\mathrm{EOS}(T,P,x_i,\\alpha,\\mathrm{model})",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["T_K", "P_Pa", "x_i", "phase_alpha", "eos_model"],
        outputSymbols: ["rho_m_kg_m3"],
      },
    ],
    units: [
      { symbol: "rho_m_kg_m3", unit: "kg/m^3", quantity: "mass_density", dimensionSignature: "M L^-3" },
      { symbol: "T_K", unit: "K", quantity: "temperature", dimensionSignature: "Theta" },
      { symbol: "P_Pa", unit: "Pa", quantity: "pressure", dimensionSignature: "M L^-1 T^-2" },
    ],
    assumptions: [
      "Bulk density is selected by EOS, measured table, or simulation evidence under a declared validity range.",
      "Mass-energy equivalence can map mass density into rest-energy density only after mass density and volume context are established.",
      "Quantum frequency observables do not by themselves determine bulk density or phase.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      literatureRef("doi:10.1063/1.1461829", "Wagner and Pruss IAPWS-95 water thermodynamic formulation."),
      literatureRef("IAPWS R6-95(2018)", "Official IAPWS release for ordinary water substance in fluid phases."),
      literatureRef("NIST Chemistry WebBook SRD 69", "Thermochemical and thermophysical reference data source."),
    ],
    hintKeys: {
      subjects: ["matter", "phase", "density", "equation_of_state", "thermodynamics"],
      symbols: ["rho_m_kg_m3", "T_K", "P_Pa", "x_i", "phase_alpha", "eos_model"],
      unitSignatures: ["M L^-3", "Theta", "M L^-1 T^-2", "1"],
      repoPaths: [],
      equationFamilies: ["equation_of_state", "mass_density", "phase_context"],
      simulationOwners: ["general_physics", "astrochemistry_prebiotic"],
    },
  }),
  phaseBadge({
    id: "matter.phase.structural_order_context",
    title: "Phase Structural Order Context",
    plainMeaning:
      "Represents molecular or atomic arrangement through lattice, amorphous, radial-distribution, coordination, or ionization descriptors.",
    whyItMatters:
      "It makes the structure change explicit while preserving the distinction between composition identity and phase-conditioned arrangement.",
    subjects: ["matter", "phase", "structure", "condensed_matter", "molecular_structure"],
    level: "model",
    status: "canonical_reference",
    simulationOwners: ["general_physics", "astrochemistry_prebiotic"],
    equationFamilies: ["structural_order", "phase_context"],
    tags: ["structure", "phase_of_matter", "lattice", "radial_distribution", "coordination"],
    equations: [
      {
        id: "structural_order_context",
        role: "noncomputable_reference",
        displayLatex: "\\mathrm{structure}=\\mathrm{context}(g(r),\\mathrm{lattice},N_c,\\chi_e,\\alpha)",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["g_r", "lattice", "N_c", "chi_e", "phase_alpha"],
        outputSymbols: ["structure_context"],
      },
    ],
    units: [
      { symbol: "g_r", unit: null, quantity: "radial_distribution_function", dimensionSignature: "1" },
      { symbol: "N_c", unit: null, quantity: "coordination_number", dimensionSignature: "1" },
      { symbol: "chi_e", unit: null, quantity: "ionization_fraction", dimensionSignature: "1" },
    ],
    assumptions: [
      "Structure descriptors are evidence-conditioned and may come from diffraction, scattering, spectroscopy, microscopy, or simulation.",
      "A phase label alone is not a complete molecular-structure description.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      literatureRef("Ashcroft Mermin solid state physics", "Condensed-matter structural and lattice reference."),
      literatureRef("Hansen McDonald theory of simple liquids", "Radial-distribution and liquid-structure reference."),
    ],
    hintKeys: {
      subjects: ["matter", "phase", "structure", "condensed_matter", "molecular_structure"],
      symbols: ["g_r", "lattice", "N_c", "chi_e", "phase_alpha", "structure_context"],
      unitSignatures: ["1"],
      repoPaths: [],
      equationFamilies: ["structural_order", "phase_context"],
      simulationOwners: ["general_physics", "astrochemistry_prebiotic"],
    },
  }),
  phaseBadge({
    id: "matter.phase.dynamical_order_context",
    title: "Dynamical Order Context",
    plainMeaning:
      "Represents ordered behavior in time through correlation functions, driven response, synchronization, or long-lived non-equilibrium dynamics.",
    whyItMatters:
      "It extends phase structure from spatial arrangement into temporal ordering without treating every oscillation as a phase of matter.",
    subjects: ["matter", "phase", "dynamical_order", "non_equilibrium", "correlation_function"],
    level: "model",
    status: "canonical_reference",
    simulationOwners: ["general_physics"],
    equationFamilies: ["dynamical_order", "non_equilibrium_phase", "correlation_function"],
    tags: ["dynamical_order", "non_equilibrium", "time_correlation", "claim_boundary"],
    equations: [
      {
        id: "dynamical_order_correlation_context",
        role: "noncomputable_reference",
        displayLatex: "C(t)=\\langle O(t)O(0)\\rangle",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["O_t", "O_0", "t_s"],
        outputSymbols: ["C_t"],
      },
    ],
    units: [
      { symbol: "t_s", unit: "s", quantity: "time", dimensionSignature: "T" },
      { symbol: "C_t", unit: null, quantity: "correlation_function", dimensionSignature: "mixed" },
    ],
    assumptions: [
      "Dynamical order requires time-correlation or response evidence, not only visual periodicity.",
      "Non-equilibrium order must name the drive, coupling, dissipation, disorder, measurement, and stability context when those are relevant.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      literatureRef("doi:10.1103/PhysRevLett.116.250401", "Phase structure of driven quantum systems."),
      literatureRef("doi:10.1103/RevModPhys.95.031001", "Review of quantum and classical discrete time crystals."),
    ],
    hintKeys: {
      subjects: ["matter", "phase", "dynamical_order", "non_equilibrium", "correlation_function"],
      symbols: ["O_t", "O_0", "t_s", "C_t"],
      unitSignatures: ["T", "mixed"],
      repoPaths: [],
      equationFamilies: ["dynamical_order", "non_equilibrium_phase", "correlation_function"],
      simulationOwners: ["general_physics"],
    },
  }),
  phaseBadge({
    id: "matter.phase.time_translation_symmetry_context",
    title: "Time-Translation Symmetry Context",
    plainMeaning:
      "Represents time-crystal questions as symmetry-breaking questions about continuous or discrete time translations.",
    whyItMatters:
      "It separates the symmetry criterion from platform details such as ions, spins, cavities, or material density.",
    subjects: ["matter", "phase", "time_crystal", "time_translation_symmetry", "symmetry_breaking"],
    level: "law",
    status: "canonical_reference",
    simulationOwners: ["general_physics"],
    equationFamilies: ["time_translation_symmetry", "symmetry_breaking", "dynamical_order"],
    tags: ["time_crystal", "time_translation_symmetry", "symmetry_breaking"],
    equations: [
      {
        id: "time_translation_symmetry_context",
        role: "noncomputable_reference",
        displayLatex: "t\\rightarrow t+T",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["t_s", "T_drive_s"],
        outputSymbols: ["time_translation_context"],
      },
    ],
    units: [
      { symbol: "t_s", unit: "s", quantity: "time", dimensionSignature: "T" },
      { symbol: "T_drive_s", unit: "s", quantity: "drive_period", dimensionSignature: "T" },
    ],
    assumptions: [
      "A time-crystal claim must identify the time-translation symmetry being considered.",
      "Discrete and continuous time-translation cases have different admissibility boundaries.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      literatureRef("doi:10.1103/PhysRevLett.109.160401", "Original quantum time-crystal proposal."),
      literatureRef("doi:10.1103/PhysRevLett.114.251603", "No-go theorem for equilibrium time crystals under broad assumptions."),
      literatureRef("doi:10.1103/PhysRevLett.117.090402", "Floquet time-crystal formulation."),
    ],
    hintKeys: {
      subjects: ["matter", "phase", "time_crystal", "time_translation_symmetry", "symmetry_breaking"],
      symbols: ["t_s", "T_drive_s", "time_translation_context"],
      unitSignatures: ["T"],
      repoPaths: [],
      equationFamilies: ["time_translation_symmetry", "symmetry_breaking", "dynamical_order"],
      simulationOwners: ["general_physics"],
    },
  }),
  phaseBadge({
    id: "matter.phase.equilibrium_time_crystal_claim_context",
    title: "Equilibrium Time-Crystal Claim Context",
    plainMeaning:
      "Represents claims that a ground-state or canonical-equilibrium Hamiltonian system has time-crystalline order.",
    whyItMatters:
      "It gives the graph a concrete target for the no-go theorem to block before stronger time-crystal language is admitted.",
    subjects: ["matter", "phase", "time_crystal", "equilibrium", "claim_boundary"],
    level: "claim_boundary",
    status: "blocked",
    simulationOwners: ["general_physics"],
    equationFamilies: ["equilibrium_time_crystal_claim", "time_translation_symmetry"],
    tags: ["time_crystal", "equilibrium", "blocked_claim", "claim_boundary"],
    equations: [
      {
        id: "equilibrium_time_crystal_claim_context",
        role: "noncomputable_reference",
        displayLatex: "\\mathrm{claim}=\\mathrm{time\\ order}(\\mathrm{ground\\ state\\ or\\ canonical\\ ensemble})",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["ground_state", "canonical_ensemble", "time_order_claim"],
        outputSymbols: ["equilibrium_time_crystal_claim"],
      },
    ],
    units: [{ symbol: "time_order_claim", unit: null, quantity: "claim_context", dimensionSignature: "1" }],
    assumptions: [
      "This badge is a blocked claim target, not an accepted phase badge.",
      "Equilibrium claims require explicit handling of the Watanabe-Oshikawa no-go boundary.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      literatureRef("doi:10.1103/PhysRevLett.114.251603", "Equilibrium no-go theorem based on time-dependent order-parameter correlations."),
    ],
    hintKeys: {
      subjects: ["matter", "phase", "time_crystal", "equilibrium", "claim_boundary"],
      symbols: ["ground_state", "canonical_ensemble", "time_order_claim", "equilibrium_time_crystal_claim"],
      unitSignatures: ["1"],
      repoPaths: [],
      equationFamilies: ["equilibrium_time_crystal_claim", "time_translation_symmetry"],
      simulationOwners: ["general_physics"],
    },
  }),
  phaseBadge({
    id: "matter.phase.equilibrium_time_crystal_no_go_boundary",
    title: "Equilibrium Time-Crystal No-Go Boundary",
    plainMeaning:
      "Represents the no-go result that rules out ordinary equilibrium time-crystal order for broad Hamiltonian systems with not-too-long-range interactions.",
    whyItMatters:
      "It prevents the graph from promoting historical equilibrium proposals into accepted phase claims.",
    subjects: ["matter", "phase", "time_crystal", "no_go_theorem", "equilibrium"],
    level: "claim_boundary",
    status: "canonical_reference",
    simulationOwners: ["general_physics"],
    equationFamilies: ["time_crystal_no_go", "equilibrium_boundary"],
    tags: ["time_crystal", "no_go", "equilibrium", "claim_boundary"],
    equations: [
      {
        id: "equilibrium_time_crystal_no_go_context",
        role: "constraint",
        displayLatex: "\\mathrm{equilibrium\\ TC}=\\mathrm{blocked\\ under\\ no\\mbox{-}go\\ assumptions}",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["equilibrium_assumptions", "interaction_range", "order_parameter_correlation"],
        outputSymbols: ["equilibrium_time_crystal_blocked"],
      },
    ],
    units: [{ symbol: "equilibrium_time_crystal_blocked", unit: null, quantity: "boundary_status", dimensionSignature: "1" }],
    assumptions: [
      "The no-go boundary applies to ground-state and canonical-equilibrium claims under the stated Hamiltonian assumptions.",
      "Driven, prethermal, and driven-dissipative time-crystal contexts must be represented separately.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      literatureRef("doi:10.1103/PhysRevLett.114.251603", "Absence of quantum time crystals no-go theorem."),
    ],
    hintKeys: {
      subjects: ["matter", "phase", "time_crystal", "no_go_theorem", "equilibrium"],
      symbols: ["equilibrium_assumptions", "interaction_range", "order_parameter_correlation", "equilibrium_time_crystal_blocked"],
      unitSignatures: ["1"],
      repoPaths: [],
      equationFamilies: ["time_crystal_no_go", "equilibrium_boundary"],
      simulationOwners: ["general_physics"],
    },
  }),
  phaseBadge({
    id: "matter.phase.floquet_discrete_time_crystal_context",
    title: "Floquet Discrete Time-Crystal Context",
    plainMeaning:
      "Represents a periodically driven non-equilibrium phase with rigid subharmonic response relative to the drive period.",
    whyItMatters:
      "It encodes the accepted route where discrete time-translation symmetry can be broken without relying on an equilibrium ground-state claim.",
    subjects: ["matter", "phase", "time_crystal", "floquet", "discrete_time_crystal"],
    level: "model",
    status: "canonical_reference",
    simulationOwners: ["general_physics"],
    equationFamilies: ["floquet_time_crystal", "subharmonic_response", "non_equilibrium_phase"],
    tags: ["time_crystal", "floquet", "discrete", "subharmonic", "non_equilibrium"],
    equations: [
      {
        id: "floquet_discrete_time_crystal_context",
        role: "noncomputable_reference",
        displayLatex: "T_{\\mathrm{response}}=nT_{\\mathrm{drive}}",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["T_drive_s", "n_period_multiplier", "response_correlation"],
        outputSymbols: ["T_response_s"],
      },
    ],
    units: [
      { symbol: "T_drive_s", unit: "s", quantity: "drive_period", dimensionSignature: "T" },
      { symbol: "T_response_s", unit: "s", quantity: "response_period", dimensionSignature: "T" },
      { symbol: "n_period_multiplier", unit: null, quantity: "period_multiplier", dimensionSignature: "1" },
    ],
    assumptions: [
      "A discrete time-crystal claim requires subharmonic response, rigidity against perturbations, and many-body stabilization evidence.",
      "The periodic drive is part of the phase context and is not a contradiction of energy conservation.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      literatureRef("doi:10.1103/PhysRevLett.117.090402", "Floquet time-crystal theory."),
      literatureRef("doi:10.1103/PhysRevLett.116.250401", "Driven-system phase structure."),
      literatureRef("doi:10.1103/PhysRevLett.118.030401", "Discrete time-crystal rigidity and realizations."),
    ],
    hintKeys: {
      subjects: ["matter", "phase", "time_crystal", "floquet", "discrete_time_crystal"],
      symbols: ["T_drive_s", "n_period_multiplier", "response_correlation", "T_response_s"],
      unitSignatures: ["T", "1"],
      repoPaths: [],
      equationFamilies: ["floquet_time_crystal", "subharmonic_response", "non_equilibrium_phase"],
      simulationOwners: ["general_physics"],
    },
  }),
  phaseBadge({
    id: "matter.phase.prethermal_discrete_time_crystal_context",
    title: "Prethermal Discrete Time-Crystal Context",
    plainMeaning:
      "Represents a long-lived non-equilibrium time-crystal regime stabilized for a finite prethermal window rather than by permanent equilibrium order.",
    whyItMatters:
      "It distinguishes prethermal stabilization from many-body-localized or dissipative routes and keeps lifetime boundaries explicit.",
    subjects: ["matter", "phase", "time_crystal", "prethermal", "discrete_time_crystal"],
    level: "model",
    status: "canonical_reference",
    simulationOwners: ["general_physics"],
    equationFamilies: ["prethermal_time_crystal", "lifetime_window", "non_equilibrium_phase"],
    tags: ["time_crystal", "prethermal", "lifetime_window", "subharmonic", "non_equilibrium"],
    equations: [
      {
        id: "prethermal_time_crystal_context",
        role: "noncomputable_reference",
        displayLatex: "t<t_*\\;\\Rightarrow\\;C(t)\\;\\mathrm{may\\ show\\ subharmonic\\ order}",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["t_s", "t_star_s", "drive_frequency_Hz", "initial_energy_density"],
        outputSymbols: ["prethermal_time_crystal_context"],
      },
    ],
    units: [
      { symbol: "t_s", unit: "s", quantity: "time", dimensionSignature: "T" },
      { symbol: "t_star_s", unit: "s", quantity: "prethermal_lifetime", dimensionSignature: "T" },
      { symbol: "drive_frequency_Hz", unit: "Hz", quantity: "drive_frequency", dimensionSignature: "T^-1" },
    ],
    assumptions: [
      "Prethermal time-crystal evidence is lifetime-bounded and must report the stability window.",
      "Initial-state energy density can condition prethermal behavior but does not define a time crystal by itself.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      literatureRef("doi:10.1126/science.abg8102", "Observation of a prethermal discrete time crystal."),
      literatureRef("doi:10.1103/RevModPhys.95.031001", "Review context for prethermal and other stabilization routes."),
    ],
    hintKeys: {
      subjects: ["matter", "phase", "time_crystal", "prethermal", "discrete_time_crystal"],
      symbols: ["t_s", "t_star_s", "drive_frequency_Hz", "initial_energy_density", "prethermal_time_crystal_context"],
      unitSignatures: ["T", "T^-1"],
      repoPaths: [],
      equationFamilies: ["prethermal_time_crystal", "lifetime_window", "non_equilibrium_phase"],
      simulationOwners: ["general_physics"],
    },
  }),
  phaseBadge({
    id: "matter.phase.driven_dissipative_continuous_time_crystal_context",
    title: "Driven-Dissipative Continuous Time-Crystal Context",
    plainMeaning:
      "Represents continuous time-translation symmetry breaking in driven-dissipative systems, usually through robust limit-cycle order.",
    whyItMatters:
      "It keeps continuous time-crystal claims outside the equilibrium no-go route by requiring open-system drive and dissipation context.",
    subjects: ["matter", "phase", "time_crystal", "continuous_time_crystal", "driven_dissipative"],
    level: "model",
    status: "review",
    simulationOwners: ["general_physics"],
    equationFamilies: ["continuous_time_crystal", "driven_dissipative_phase", "limit_cycle"],
    tags: ["time_crystal", "continuous", "driven_dissipative", "limit_cycle", "open_system"],
    equations: [
      {
        id: "driven_dissipative_continuous_time_crystal_context",
        role: "noncomputable_reference",
        displayLatex: "\\mathrm{CTC}=\\mathrm{limit\\ cycle}(\\mathrm{drive},\\mathrm{dissipation},\\mathrm{many\\ body\\ state})",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["drive_context", "dissipation_context", "limit_cycle_signal"],
        outputSymbols: ["continuous_time_crystal_context"],
      },
    ],
    units: [{ symbol: "limit_cycle_signal", unit: null, quantity: "time_series_observable", dimensionSignature: "mixed" }],
    assumptions: [
      "Continuous time-crystal claims require open-system drive, dissipation, spontaneous phase selection, and robustness evidence.",
      "A driven-dissipative limit cycle is not an equilibrium ground-state time-crystal claim.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      literatureRef("doi:10.1126/science.abo3382", "Observation of a continuous time crystal in a driven-dissipative atom-cavity system."),
      literatureRef("doi:10.1103/RevModPhys.95.031001", "Review context for continuous and dissipative routes."),
    ],
    hintKeys: {
      subjects: ["matter", "phase", "time_crystal", "continuous_time_crystal", "driven_dissipative"],
      symbols: ["drive_context", "dissipation_context", "limit_cycle_signal", "continuous_time_crystal_context"],
      unitSignatures: ["mixed"],
      repoPaths: [],
      equationFamilies: ["continuous_time_crystal", "driven_dissipative_phase", "limit_cycle"],
      simulationOwners: ["general_physics"],
    },
  }),
  phaseBadge({
    id: "matter.phase.time_crystal_observable_signature_context",
    title: "Time-Crystal Observable Signature Context",
    plainMeaning:
      "Represents evidence requirements such as subharmonic spectral peaks, long-lived time correlations, rigidity, and phase-boundary tests.",
    whyItMatters:
      "It prevents frequency observations or repeated oscillations from being treated as sufficient evidence on their own.",
    subjects: ["matter", "phase", "time_crystal", "observable_signature", "spectroscopy"],
    level: "diagnostic_gate",
    status: "canonical_reference",
    simulationOwners: ["general_physics"],
    equationFamilies: ["time_crystal_signature", "subharmonic_response", "correlation_function"],
    tags: ["time_crystal", "observable", "subharmonic", "rigidity", "phase_boundary", "claim_boundary"],
    equations: [
      {
        id: "time_crystal_observable_signature",
        role: "gate",
        displayLatex: "\\{C(t),S(\\omega),\\mathrm{rigidity},\\mathrm{phase\\ boundary}\\}\\Rightarrow\\mathrm{candidate\\ DTC}",
        computableExpression: null,
        operatorKind: "gate_status",
        inputSymbols: ["C_t", "S_omega", "rigidity_test", "phase_boundary_test"],
        outputSymbols: ["time_crystal_signature_context"],
      },
    ],
    units: [
      { symbol: "S_omega", unit: null, quantity: "frequency_spectrum", dimensionSignature: "mixed" },
      { symbol: "rigidity_test", unit: null, quantity: "diagnostic_test", dimensionSignature: "1" },
    ],
    assumptions: [
      "A frequency peak is evidence only after mode assignment, drive comparison, stability testing, and perturbation checks.",
      "Accepted time-crystal evidence should include subharmonic response or limit-cycle order plus robustness and phase-boundary context.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      literatureRef("doi:10.1103/PhysRevLett.118.030401", "Rigidity, criticality, and measurable signatures."),
      literatureRef("doi:10.1038/nature21413", "Trapped-ion discrete time-crystal observation."),
      literatureRef("doi:10.1038/nature21426", "Disordered dipolar spin time-crystalline order observation."),
    ],
    hintKeys: {
      subjects: ["matter", "phase", "time_crystal", "observable_signature", "spectroscopy"],
      symbols: ["C_t", "S_omega", "rigidity_test", "phase_boundary_test", "time_crystal_signature_context"],
      unitSignatures: ["mixed", "1"],
      repoPaths: [],
      equationFamilies: ["time_crystal_signature", "subharmonic_response", "correlation_function"],
      simulationOwners: ["general_physics"],
    },
  }),
  phaseBadge({
    id: "matter.phase.time_crystal_platform_parameter_context",
    title: "Time-Crystal Platform Parameter Context",
    plainMeaning:
      "Represents platform-specific conditions such as spin density, ion spacing, disorder, interaction strength, cavity pump, and dissipation.",
    whyItMatters:
      "It provides a weak place for density-like parameters without making density the defining criterion for time-crystalline order.",
    subjects: ["matter", "phase", "time_crystal", "platform_parameter", "density"],
    level: "model",
    status: "diagnostic",
    simulationOwners: ["general_physics"],
    equationFamilies: ["time_crystal_platform_parameter", "experimental_context"],
    tags: ["time_crystal", "platform_parameter", "density_context", "experimental_context"],
    equations: [
      {
        id: "time_crystal_platform_parameter_context",
        role: "noncomputable_reference",
        displayLatex: "\\mathrm{platform}=\\mathrm{context}(\\rho,N,J,W,\\Omega,\\Gamma)",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["rho_platform", "N", "J", "W", "Omega", "Gamma"],
        outputSymbols: ["time_crystal_platform_context"],
      },
    ],
    units: [
      { symbol: "rho_platform", unit: null, quantity: "platform_density_or_concentration", dimensionSignature: "contextual" },
      { symbol: "Omega", unit: "rad/s", quantity: "drive_rate", dimensionSignature: "T^-1" },
      { symbol: "Gamma", unit: "1/s", quantity: "dissipation_rate", dimensionSignature: "T^-1" },
    ],
    assumptions: [
      "Density-like parameters can affect an experimental platform but are not time-crystal order parameters by themselves.",
      "Platform context must be paired with observable signature evidence before a time-crystal claim is admitted.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      literatureRef("doi:10.1038/nature21413", "Trapped-ion experimental platform."),
      literatureRef("doi:10.1038/nature21426", "Diamond spin-impurity experimental platform."),
      literatureRef("doi:10.1126/science.abo3382", "Driven-dissipative atom-cavity platform."),
    ],
    hintKeys: {
      subjects: ["matter", "phase", "time_crystal", "platform_parameter", "density"],
      symbols: ["rho_platform", "N", "J", "W", "Omega", "Gamma", "time_crystal_platform_context"],
      unitSignatures: ["contextual", "T^-1"],
      repoPaths: [],
      equationFamilies: ["time_crystal_platform_parameter", "experimental_context"],
      simulationOwners: ["general_physics"],
    },
  }),
  phaseBadge({
    id: "matter.phase.time_crystal_claim_boundary",
    title: "Time-Crystal Claim Boundary",
    plainMeaning:
      "Represents the guardrail that time-crystal language needs symmetry, non-equilibrium route, stability, and observable-signature evidence.",
    whyItMatters:
      "It blocks promotional or shortcut claims while still allowing grounded time-crystal evidence to enter the theory graph.",
    subjects: ["matter", "phase", "time_crystal", "claim_boundary", "overclaim_guard"],
    level: "claim_boundary",
    status: "canonical_reference",
    simulationOwners: ["general_physics"],
    equationFamilies: ["time_crystal_claim_boundary", "overclaim_guard"],
    tags: ["time_crystal", "claim_boundary", "overclaim_guard"],
    equations: [
      {
        id: "time_crystal_claim_boundary",
        role: "gate",
        displayLatex: "\\mathrm{TC\\ claim}\\Rightarrow\\mathrm{symmetry}+\\mathrm{route}+\\mathrm{stability}+\\mathrm{signature}",
        computableExpression: null,
        operatorKind: "gate_status",
        inputSymbols: ["symmetry_context", "route_context", "stability_context", "signature_context"],
        outputSymbols: ["time_crystal_claim_admissible"],
      },
    ],
    units: [{ symbol: "time_crystal_claim_admissible", unit: null, quantity: "claim_gate", dimensionSignature: "1" }],
    assumptions: [
      "Repeated motion, frequency response, or platform density alone is insufficient for a time-crystal claim.",
      "Energy-conservation, work-extraction, and broad material-phase claims remain blocked unless the route-specific evidence explicitly admits them.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      literatureRef("doi:10.1103/PhysRevLett.114.251603", "Equilibrium no-go boundary."),
      literatureRef("doi:10.1103/RevModPhys.95.031001", "Modern review of admissible routes and evidence boundaries."),
    ],
    hintKeys: {
      subjects: ["matter", "phase", "time_crystal", "claim_boundary", "overclaim_guard"],
      symbols: ["symmetry_context", "route_context", "stability_context", "signature_context", "time_crystal_claim_admissible"],
      unitSignatures: ["1"],
      repoPaths: [],
      equationFamilies: ["time_crystal_claim_boundary", "overclaim_guard"],
      simulationOwners: ["general_physics"],
    },
  }),
  phaseBadge({
    id: "matter.phase.quantized_mode_frequency_context",
    title: "Quantized Mode Frequency Context",
    plainMeaning:
      "Represents rotational, vibrational, phonon, electronic, spectral-line, or plasma modes as energy-gap observables using Delta E = h nu.",
    whyItMatters:
      "It gives frequency observables a safe quantum bridge while preventing frequency rows from replacing EOS or structure evidence.",
    subjects: ["matter", "phase", "frequency", "spectroscopy", "quantum"],
    level: "derived_relation",
    status: "canonical_reference",
    simulationOwners: ["general_physics", "astrochemistry_prebiotic", "stellar_reference"],
    equationFamilies: ["planck_relation", "spectroscopy", "phase_observable"],
    tags: ["frequency", "spectroscopy", "phonon", "vibrational_mode", "rotational_mode", "claim_boundary"],
    equations: [
      {
        id: "phase_mode_energy_frequency",
        role: "law",
        displayLatex: "\\Delta E=h\\nu",
        computableExpression: "deltaE = h * nu",
        operatorKind: "scalar_expression",
        inputSymbols: ["h", "nu_Hz"],
        outputSymbols: ["deltaE_J"],
      },
    ],
    units: [
      { symbol: "nu_Hz", unit: "Hz", quantity: "frequency", dimensionSignature: "T^-1" },
      { symbol: "deltaE_J", unit: "J", quantity: "transition_energy", dimensionSignature: "M L^2 T^-2" },
    ],
    assumptions: [
      "Delta E = h nu applies to specific quanta or transition energy gaps, not to bulk phase density by itself.",
      "Observed frequencies require mode assignment, calibration, and environmental broadening context before structural claims are promoted.",
      "Phase-dependent frequency shifts can document structure or environment only when compared against admitted reference evidence.",
    ],
    calculatorPayloads: [
      {
        id: "phase_mode_energy_frequency_payload",
        expression: "deltaE = h * nu",
        displayLatex: "\\Delta E=h\\nu",
        preferredAction: "solve_with_steps",
        targetVariable: "deltaE",
        setupContext: null,
      },
    ],
    sourceRefs: [
      literatureRef("Planck relation", "Canonical energy-frequency relation."),
      literatureRef("doi:10.1016/j.jqsrt.2021.107949", "HITRAN2020 molecular spectroscopic database."),
      literatureRef("NIST Chemistry WebBook SRD 69", "Reference spectra and thermophysical data source."),
    ],
    hintKeys: {
      subjects: ["matter", "phase", "frequency", "spectroscopy", "quantum"],
      symbols: ["h", "nu_Hz", "deltaE_J", "structure_context"],
      unitSignatures: ["T^-1", "M L^2 T^-2"],
      repoPaths: [],
      equationFamilies: ["planck_relation", "spectroscopy", "phase_observable"],
      simulationOwners: ["general_physics", "astrochemistry_prebiotic", "stellar_reference"],
    },
  }),
  phaseBadge({
    id: "matter.phase.water_conditioned_state_context",
    title: "Water Conditioned Phase-State Context",
    plainMeaning:
      "Represents H2O phase, density, and structure as conditioned by temperature, pressure, composition, and environment.",
    whyItMatters:
      "It extends the water-origin badge into phase behavior without saying hydrogen and oxygen availability determines water state or density.",
    subjects: ["matter", "phase", "water", "H2O", "density", "structure"],
    level: "model",
    status: "canonical_reference",
    simulationOwners: ["astrochemistry_prebiotic", "general_physics"],
    equationFamilies: ["water_phase_context", "equation_of_state", "gas_ice_chemistry"],
    tags: ["water", "ice", "liquid", "vapor", "supercritical", "phase_of_matter", "density"],
    equations: [
      {
        id: "water_conditioned_phase_context",
        role: "noncomputable_reference",
        displayLatex: "\\mathrm{H_2O\\ phase}=\\mathrm{context}(T,P,\\rho_m,\\mathrm{structure},\\mathrm{chemistry})",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["H2O", "T_K", "P_Pa", "rho_m_kg_m3", "structure_context", "chemistry_context"],
        outputSymbols: ["H2O_phase_context"],
      },
    ],
    units: [
      { symbol: "T_K", unit: "K", quantity: "temperature", dimensionSignature: "Theta" },
      { symbol: "P_Pa", unit: "Pa", quantity: "pressure", dimensionSignature: "M L^-1 T^-2" },
      { symbol: "rho_m_kg_m3", unit: "kg/m^3", quantity: "mass_density", dimensionSignature: "M L^-3" },
    ],
    assumptions: [
      "H2O identity can persist across ice, liquid, vapor, and supercritical contexts, but molecular network structure and density change with conditions.",
      "Water phase assignment requires temperature, pressure, composition, and validity range evidence.",
      "Water phase context is not a habitability, life, prebiotic-success, or fusion-origin claim.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      literatureRef("doi:10.1063/1.1461829", "IAPWS-95 scientific formulation for ordinary water substance."),
      literatureRef("IAPWS R6-95(2018)", "Official thermodynamic release for ordinary water substance."),
      literatureRef("NIST Chemistry WebBook SRD 69", "Water thermochemical and thermophysical data source."),
    ],
    hintKeys: {
      subjects: ["matter", "phase", "water", "H2O", "density", "structure"],
      symbols: ["H2O", "T_K", "P_Pa", "rho_m_kg_m3", "H2O_phase_context"],
      unitSignatures: ["Theta", "M L^-1 T^-2", "M L^-3"],
      repoPaths: [],
      equationFamilies: ["water_phase_context", "equation_of_state", "gas_ice_chemistry"],
      simulationOwners: ["astrochemistry_prebiotic", "general_physics"],
    },
  }),
];

export const PHASE_OF_MATTER_THEORY_EDGES: TheoryBadgeEdgeV1[] = [
  {
    id: "composition_identity_requires_dimension_consistency",
    from: "physics.units.dimension_consistency",
    to: "matter.phase.composition_identity_context",
    relation: "requires",
    label: "Composition identity still requires dimensionally coherent state descriptors.",
    claimBoundaryNote: "Identity context is not a reaction or phase-density solve.",
  },
  {
    id: "composition_identity_bounds_thermodynamic_phase_state",
    from: "matter.phase.composition_identity_context",
    to: "matter.phase.thermodynamic_state_context",
    relation: "bounds",
    label: "Thermodynamic phase state is interpreted within a declared composition identity.",
    claimBoundaryNote: "A phase label cannot replace composition or reaction-boundary evidence.",
  },
  {
    id: "thermodynamic_state_requires_eos_density_context",
    from: "matter.phase.thermodynamic_state_context",
    to: "matter.phase.equation_of_state_density_context",
    relation: "requires",
    label: "Density claims require thermodynamic state and EOS or table context.",
    claimBoundaryNote: "Temperature and pressure are necessary context, not a universal density derivation.",
  },
  {
    id: "thermodynamic_state_conditions_structural_order",
    from: "matter.phase.thermodynamic_state_context",
    to: "matter.phase.structural_order_context",
    relation: "requires",
    label: "Structural-order claims require thermodynamic condition context.",
    claimBoundaryNote: "Phase labels do not uniquely determine microscopic structure.",
  },
  {
    id: "structural_order_documents_dynamical_order_context",
    from: "matter.phase.structural_order_context",
    to: "matter.phase.dynamical_order_context",
    relation: "documents",
    label: "Spatial or microscopic structure can document the platform in which dynamical order is tested.",
    claimBoundaryNote: "Static structure is not enough to prove temporal order.",
  },
  {
    id: "thermodynamic_state_requires_dynamical_order_context",
    from: "matter.phase.thermodynamic_state_context",
    to: "matter.phase.dynamical_order_context",
    relation: "requires",
    label: "Dynamical-order claims require state and boundary context.",
    claimBoundaryNote: "Non-equilibrium order cannot be inferred from a phase label alone.",
  },
  {
    id: "dynamical_order_requires_time_translation_symmetry_context",
    from: "matter.phase.dynamical_order_context",
    to: "matter.phase.time_translation_symmetry_context",
    relation: "requires",
    label: "Time-crystal order is a time-translation symmetry-breaking question.",
    claimBoundaryNote: "Repeated dynamics must be tied to a symmetry criterion before time-crystal language is admitted.",
  },
  {
    id: "time_translation_documents_equilibrium_time_crystal_claim_context",
    from: "matter.phase.time_translation_symmetry_context",
    to: "matter.phase.equilibrium_time_crystal_claim_context",
    relation: "documents",
    label: "The historical equilibrium time-crystal claim is represented as a boundary target.",
    claimBoundaryNote: "This documents the claim surface only; it does not admit the claim.",
  },
  {
    id: "equilibrium_no_go_blocks_equilibrium_time_crystal_claim",
    from: "matter.phase.equilibrium_time_crystal_no_go_boundary",
    to: "matter.phase.equilibrium_time_crystal_claim_context",
    relation: "blocks",
    label: "The equilibrium no-go theorem blocks ordinary ground-state or canonical-equilibrium time-crystal claims.",
    claimBoundaryNote: "Driven and open-system routes must be represented separately from the blocked equilibrium claim.",
  },
  {
    id: "time_translation_specializes_floquet_discrete_time_crystal",
    from: "matter.phase.time_translation_symmetry_context",
    to: "matter.phase.floquet_discrete_time_crystal_context",
    relation: "specializes",
    label: "Floquet discrete time crystals specialize time-translation symmetry breaking to periodically driven systems.",
    claimBoundaryNote: "Floquet context requires an admitted drive period and non-equilibrium route.",
  },
  {
    id: "time_translation_specializes_prethermal_discrete_time_crystal",
    from: "matter.phase.time_translation_symmetry_context",
    to: "matter.phase.prethermal_discrete_time_crystal_context",
    relation: "specializes",
    label: "Prethermal discrete time crystals specialize the discrete route to a finite stability window.",
    claimBoundaryNote: "The lifetime window must be explicit.",
  },
  {
    id: "time_translation_specializes_driven_dissipative_continuous_time_crystal",
    from: "matter.phase.time_translation_symmetry_context",
    to: "matter.phase.driven_dissipative_continuous_time_crystal_context",
    relation: "specializes",
    label: "Driven-dissipative continuous time crystals specialize time-translation symmetry breaking to open-system limit-cycle order.",
    claimBoundaryNote: "Continuous time-crystal context is not an equilibrium ground-state claim.",
  },
  {
    id: "floquet_discrete_requires_time_crystal_observable_signature",
    from: "matter.phase.floquet_discrete_time_crystal_context",
    to: "matter.phase.time_crystal_observable_signature_context",
    relation: "requires",
    label: "Floquet discrete time-crystal claims require subharmonic response and rigidity evidence.",
    claimBoundaryNote: "A drive plus oscillation is not sufficient without robustness and phase-boundary evidence.",
  },
  {
    id: "prethermal_discrete_requires_time_crystal_observable_signature",
    from: "matter.phase.prethermal_discrete_time_crystal_context",
    to: "matter.phase.time_crystal_observable_signature_context",
    relation: "requires",
    label: "Prethermal time-crystal claims require lifetime-window and observable-signature evidence.",
    claimBoundaryNote: "Finite prethermal order must not be described as permanent equilibrium order.",
  },
  {
    id: "continuous_driven_dissipative_requires_time_crystal_observable_signature",
    from: "matter.phase.driven_dissipative_continuous_time_crystal_context",
    to: "matter.phase.time_crystal_observable_signature_context",
    relation: "requires",
    label: "Driven-dissipative continuous time-crystal claims require robust limit-cycle evidence.",
    claimBoundaryNote: "Open-system oscillation needs spontaneous phase selection and perturbation robustness context.",
  },
  {
    id: "time_crystal_observable_documents_phase_mode_frequency",
    from: "matter.phase.time_crystal_observable_signature_context",
    to: "matter.phase.quantized_mode_frequency_context",
    relation: "documents",
    label: "Time-crystal signatures may include spectral or frequency-response observables.",
    claimBoundaryNote: "Frequency evidence is necessary context in some platforms but is not sufficient alone.",
  },
  {
    id: "phase_eos_density_documents_time_crystal_platform_parameters",
    from: "matter.phase.equation_of_state_density_context",
    to: "matter.phase.time_crystal_platform_parameter_context",
    relation: "documents",
    label: "Density-like quantities can document platform conditions for time-crystal experiments.",
    claimBoundaryNote: "Density is a platform parameter, not the defining time-crystal order parameter.",
  },
  {
    id: "platform_parameters_document_time_crystal_observable_signature",
    from: "matter.phase.time_crystal_platform_parameter_context",
    to: "matter.phase.time_crystal_observable_signature_context",
    relation: "documents",
    label: "Platform parameters document the experimental conditions under which time-crystal signatures are tested.",
    claimBoundaryNote: "Platform parameters do not replace observable signature evidence.",
  },
  {
    id: "time_crystal_signature_documents_claim_boundary",
    from: "matter.phase.time_crystal_observable_signature_context",
    to: "matter.phase.time_crystal_claim_boundary",
    relation: "documents",
    label: "Observable-signature evidence must be interpreted through the time-crystal claim boundary.",
    claimBoundaryNote: "The claim boundary remains diagnostic and does not promote evidence into a universal material claim.",
  },
  {
    id: "equilibrium_no_go_documents_time_crystal_claim_boundary",
    from: "matter.phase.equilibrium_time_crystal_no_go_boundary",
    to: "matter.phase.time_crystal_claim_boundary",
    relation: "documents",
    label: "The equilibrium no-go result is part of the time-crystal claim boundary.",
    claimBoundaryNote: "Historical proposals must not bypass the no-go boundary.",
  },
  {
    id: "structural_order_documents_mode_frequency_context",
    from: "matter.phase.structural_order_context",
    to: "matter.phase.quantized_mode_frequency_context",
    relation: "documents",
    label: "Structure context can document which frequency modes are meaningful.",
    claimBoundaryNote: "Frequency observations still need mode assignment and calibration evidence.",
  },
  {
    id: "quantum_energy_frequency_specializes_phase_mode_frequency",
    from: "physics.quantum.energy_frequency",
    to: "matter.phase.quantized_mode_frequency_context",
    relation: "specializes",
    label: "Phase mode frequencies use the shared quantum energy-frequency relation for transition gaps.",
    claimBoundaryNote: "Delta E = h nu is a transition relation, not a bulk-density equation of state.",
  },
  {
    id: "phase_eos_density_documents_energy_density_bridge",
    from: "matter.phase.equation_of_state_density_context",
    to: "physics.energy.energy_density",
    relation: "documents",
    label: "Mass-density context can document later energy-density bridges only after EOS and volume context are admitted.",
    claimBoundaryNote: "Mass density is not automatically stress-energy or NHM2 source evidence.",
  },
  {
    id: "water_binding_requires_conditioned_phase_state",
    from: "astrochemistry.water.h_o_binding_context",
    to: "matter.phase.water_conditioned_state_context",
    relation: "requires",
    label: "Water molecular context must be condition-qualified before phase, structure, or density claims.",
    claimBoundaryNote: "Hydrogen and oxygen availability does not determine water phase or density.",
  },
  {
    id: "thermodynamic_phase_state_specializes_water_state",
    from: "matter.phase.thermodynamic_state_context",
    to: "matter.phase.water_conditioned_state_context",
    relation: "specializes",
    label: "Water phase-state context specializes the generic thermodynamic phase condition pattern.",
    claimBoundaryNote: "Water-specific state selection requires an admitted water EOS or measured reference table.",
  },
  {
    id: "eos_density_context_specializes_water_density",
    from: "matter.phase.equation_of_state_density_context",
    to: "matter.phase.water_conditioned_state_context",
    relation: "specializes",
    label: "Water density context specializes the generic EOS density pattern.",
    claimBoundaryNote: "The selected water formulation has a validity range and cannot be used outside it without a boundary note.",
  },
  {
    id: "water_state_documents_phase_mode_frequency",
    from: "matter.phase.water_conditioned_state_context",
    to: "matter.phase.quantized_mode_frequency_context",
    relation: "documents",
    label: "Water state can document rotational, vibrational, librational, or phonon mode contexts.",
    claimBoundaryNote: "Frequency modes are observables, not a direct derivation of water density.",
  },
];

export function buildPhaseOfMatterTheoryBadgesV1(): {
  badges: TheoryBadgeV1[];
  edges: TheoryBadgeEdgeV1[];
} {
  return {
    badges: PHASE_OF_MATTER_THEORY_BADGES.map((badge) => ({ ...badge })),
    edges: PHASE_OF_MATTER_THEORY_EDGES.map((edge) => ({ ...edge })),
  };
}
