import {
  buildPhysicsAtlasV1,
  type PhysicsAtlasBlockV1,
  type PhysicsAtlasV1,
} from "../contracts/physics-atlas.v1";
import type { TheoryBadgeGraphV1 } from "../contracts/theory-badge-graph.v1";

const sourceRef = (
  kind: PhysicsAtlasBlockV1["sourceRefs"][number]["kind"],
  path: string,
  note?: string,
  id?: string,
): PhysicsAtlasBlockV1["sourceRefs"][number] => ({
  kind,
  path,
  id: id ?? null,
  note: note ?? null,
});

export const PHYSICS_ATLAS_BLOCKS: PhysicsAtlasBlockV1[] = [
  {
    id: "stellar_evolution",
    title: "Stellar Evolution",
    shortTitle: "Stellar",
    glyph: "★",
    description: "StarSim stellar stages, object bindings, scalar observables, runtime classification, and Stage 1 boundaries.",
    status: "active",
    subjects: ["starsim", "stellar", "stellar_structure", "fusion", "main_sequence", "red_giant", "compact_object"],
    symbols: ["T_eff", "M", "R", "L", "rho_mean", "compactness_scale", "dominantFusionChannel"],
    unitSignatures: ["Theta", "M", "L", "M L^-3"],
    equationFamilies: ["stellar_observable_proxy", "stellar_structure_proxy", "fusion_classifier_margin"],
    simulationOwners: ["starsim"],
    repoPathHints: [
      "shared/theory/starsim-theory-badges.ts",
      "shared/theory/starsim-stellar-evolution-map.ts",
      "shared/starsim-fusion-microphysics.ts",
    ],
    primaryBadgeIds: [
      "starsim.observable.surface_temperature_proxy",
      "starsim.observable.surface_gravity",
      "starsim.observable.mean_density",
      "starsim.runtime.evaluate_fusion_microphysics",
      "starsim.claim_boundary.stage1_reduced_order_prior",
    ],
    rootBadgeIds: ["physics.energy.energy_density", "physics.energy.power_rate"],
    claimBoundaryBadgeIds: ["starsim.claim_boundary.stage1_reduced_order_prior"],
    calculatorExamples: [
      {
        label: "Surface temperature proxy",
        expression: "T_eff = T_sun*(L/(R^2))^(1/4)",
        displayLatex: "T_{eff}=T_{sun}\\left(\\frac{L}{R^2}\\right)^{1/4}",
        symbols: ["T_eff", "T_sun", "L", "R"],
      },
    ],
    runtimeActions: [
      {
        actionId: "theory-badge-graph.run_runtime_badge",
        label: "Run StarSim fusion microphysics",
        badgeId: "starsim.runtime.evaluate_fusion_microphysics",
        note: "Returns a StarSim runtime receipt; calculator rows remain scalar support.",
      },
    ],
    sourceRefs: [
      sourceRef("repo_module", "shared/starsim-fusion-microphysics.ts", "StarSim Stage 1 reduced-order runtime."),
      sourceRef("repo_module", "shared/theory/starsim-theory-badges.ts", "Theory badge branch."),
      sourceRef("doc", "docs/research/starsim-fusion-microphysics-stage1.md", "Stage 1 caveats and boundaries."),
    ],
    claimBoundaryNotes: [
      "StarSim Stage 1 is a reduced-order astrophysical prior lane, not a full stellar-evolution solve.",
      "StarSim paths stay in reduced-order prior scope and cannot promote external physics claims.",
    ],
  },
  {
    id: "cosmic_distance_ladder",
    title: "Cosmic Distance Ladder",
    shortTitle: "Distance",
    glyph: "z",
    description: "Spectral shifts, parallax, Cepheids, distance modulus, and Hubble-law distance estimates.",
    status: "active",
    subjects: ["cosmic_distance", "redshift", "blueshift", "parallax", "cepheid", "standard_candle", "hubble_law"],
    symbols: ["z", "lambda_obs", "lambda_rest", "d_pc", "P_days", "M_abs", "m_app", "H0"],
    unitSignatures: ["1", "L", "T"],
    equationFamilies: ["spectral_shift", "parallax_distance", "cepheid_period_luminosity", "distance_modulus", "hubble_law"],
    simulationOwners: ["cosmic_distance_ladder", "starsim_accordion"],
    repoPathHints: ["shared/theory/cosmic-distance-ladder-badges.ts", "shared/starsim-accordion-cosmology-context.ts"],
    primaryBadgeIds: [
      "cosmic.spectral.redshift",
      "cosmic.parallax.distance",
      "cosmic.cepheid.period_luminosity",
      "cosmic.distance_modulus",
      "cosmic.low_z.hubble_distance",
    ],
    rootBadgeIds: ["physics.constants.speed_of_light", "physics.frames.lorentz_factor"],
    claimBoundaryBadgeIds: ["cosmic.claim_boundary.distance_model_dependent"],
    calculatorExamples: [
      {
        label: "Redshift from wavelength",
        expression: "z = (lambda_obs - lambda_rest) / lambda_rest",
        displayLatex: "z=\\frac{\\lambda_{obs}-\\lambda_{rest}}{\\lambda_{rest}}",
        symbols: ["z", "lambda_obs", "lambda_rest"],
      },
    ],
    runtimeActions: [],
    sourceRefs: [
      sourceRef("repo_module", "shared/theory/cosmic-distance-ladder-badges.ts", "Cosmic ladder badge branch."),
      sourceRef("repo_module", "shared/starsim-accordion-cosmology-context.ts", "Accordion cosmology context."),
    ],
    claimBoundaryNotes: [
      "Distance-ladder estimates are calibration/model dependent.",
      "Cosmological background expansion must not be conflated with local bound-system expansion.",
    ],
  },
  {
    id: "solar_surface_spectrum",
    title: "Solar Surface & Spectrum",
    shortTitle: "Solar",
    glyph: "☀",
    description: "Solar spectrum, photon energy, Doppler shifts, blackbody proxies, and flare-energy observation rows.",
    status: "active",
    subjects: ["solar", "spectrum", "wavelength", "radiation", "blackbody", "flare", "doppler"],
    symbols: ["lambda", "lambda_obs", "lambda0", "f", "E", "v", "T", "F", "E_flare"],
    unitSignatures: ["L", "T^-1", "M L^2 T^-2", "L T^-1", "Theta"],
    equationFamilies: ["spectral_observable", "planck_relation", "doppler_shift", "blackbody_radiation", "flare_energy_proxy"],
    simulationOwners: ["solar_spectrum", "solar_flare"],
    repoPathHints: [
      "shared/solar-spectrum-analysis.ts",
      "server/services/essence/solar-spectrum-ingest.ts",
      "server/services/essence/solar-spectrum-models.ts",
      "shared/solar-flare-observable-contract.v1.ts",
    ],
    primaryBadgeIds: [
      "solar.spectrum.photon_energy",
      "solar.spectrum.wien_peak",
      "solar.spectrum.stefan_boltzmann_luminosity",
      "solar.spectrum.halpha_line_reference",
      "solar.spectrum.doppler_shift",
      "solar.spectrum.radial_velocity_proxy",
      "solar.spectrum.blackbody_curve_reference",
      "solar.magnetic.zeeman_split_proxy",
      "solar.flare.energy_proxy",
      "solar.runtime.spectrum_analysis",
      "solar.claim_boundary.observational_proxy",
    ],
    rootBadgeIds: ["physics.constants.speed_of_light", "physics.quantum.energy_frequency", "physics.energy.power_rate"],
    claimBoundaryBadgeIds: ["solar.claim_boundary.observational_proxy"],
    calculatorExamples: [
      {
        label: "Photon energy from wavelength",
        expression: "E = h*c/lambda",
        displayLatex: "E=\\frac{hc}{\\lambda}",
        symbols: ["E", "h", "c", "lambda"],
      },
      {
        label: "Solar line Doppler velocity",
        expression: "v = c*(lambda_obs - lambda0)/lambda0",
        displayLatex: "v=c\\frac{\\lambda_{obs}-\\lambda_0}{\\lambda_0}",
        symbols: ["v", "c", "lambda_obs", "lambda0"],
      },
    ],
    runtimeActions: [
      {
        actionId: "theory-badge-graph.locate_context",
        label: "Locate solar spectrum context",
        note: "Locates solar spectrum badges and calculator payloads; observation runtimes remain separate.",
      },
    ],
    sourceRefs: [
      sourceRef("repo_module", "shared/solar-spectrum-analysis.ts", "Solar spectrum analysis helpers."),
      sourceRef("repo_module", "server/services/essence/solar-spectrum-ingest.ts", "Solar spectrum ingest path."),
      sourceRef("contract", "shared/solar-flare-observable-contract.v1.ts", "Solar flare observable contract."),
      sourceRef("doc", "docs/knowledge/physics/solar-radiative-observables-tree.json", "Solar radiative observables tree."),
    ],
    claimBoundaryNotes: [
      "Solar spectral and flare rows are observation/model proxies.",
      "Instrument calibration and bandpass context are required before physical interpretation.",
    ],
  },
  {
    id: "casimir_cavity_modes",
    title: "Casimir Cavities",
    shortTitle: "Cavity",
    glyph: "▣",
    description: "Static and dynamic Casimir, cavity modes, Q factors, gaps, and cavity telemetry.",
    status: "active",
    subjects: ["casimir", "cavity", "parallel_plate", "vacuum_energy", "q_factor", "mode_frequency"],
    symbols: ["a", "gap", "Q_L", "U_static", "E_area", "E_tile", "M_proxy", "f_n"],
    unitSignatures: ["L", "M L^2 T^-2", "M L^-1 T^-2", "T^-1"],
    equationFamilies: ["casimir_energy", "casimir_tile_budget", "casimir_gain_ladder", "cavity_mode"],
    simulationOwners: ["casimir", "NHM2"],
    repoPathHints: [
      "modules/sim_core/static-casimir.ts",
      "modules/dynamic/dynamic-casimir.ts",
      "server/services/casimir/telemetry.ts",
      "server/energy-pipeline.ts",
      "docs/casimir-tile-mechanism.md",
    ],
    primaryBadgeIds: [
      "casimir.cavity.parallel_plate_energy_density",
      "casimir.cavity.parallel_plate_pressure",
      "casimir.cavity.per_tile_energy",
      "casimir.cavity.static_tile_budget",
      "casimir.cavity.geometry_gain",
      "casimir.cavity.output_energy_proxy",
      "casimir.cavity.mass_equivalent_proxy",
      "casimir.cavity.mode_frequency",
      "casimir.cavity.mode_photon_energy",
      "casimir.runtime.static_casimir_module",
      "casimir.claim_boundary.diagnostic_source_context",
    ],
    rootBadgeIds: ["physics.energy.energy_density", "physics.quantum.energy_frequency"],
    claimBoundaryBadgeIds: ["casimir.claim_boundary.diagnostic_source_context", "nhm2.claim_boundary.diagnostic_only"],
    calculatorExamples: [
      {
        label: "Parallel-plate energy per area",
        expression: "E_area = -(pi^2*hbar_c)/(720*a^3)",
        displayLatex: "E_A=-\\frac{\\pi^2\\hbar c}{720a^3}",
        symbols: ["E_area", "pi", "hbar_c", "a"],
      },
      {
        label: "Cavity mode frequency",
        expression: "f_n = n*c/(2*L)",
        displayLatex: "f_n=\\frac{nc}{2L}",
        symbols: ["f_n", "n", "c", "L"],
      },
    ],
    runtimeActions: [],
    sourceRefs: [
      sourceRef("repo_module", "modules/sim_core/static-casimir.ts", "Static Casimir simulation path."),
      sourceRef("repo_module", "modules/dynamic/dynamic-casimir.ts", "Dynamic Casimir simulation path."),
      sourceRef("repo_module", "server/services/casimir/telemetry.ts", "Casimir telemetry service."),
      sourceRef("repo_module", "server/energy-pipeline.ts", "Energy pipeline static budget and gain ladder."),
      sourceRef("doc", "docs/casimir-tile-mechanism.md", "Mechanism note and caveats."),
    ],
    claimBoundaryNotes: [
      "Casimir rows are diagnostic/source-context rows and do not establish propulsion evidence.",
      "Material, finite-temperature, and measurement interpretations require separate runtime receipts.",
    ],
  },
  {
    id: "warp_gr_nhm2",
    title: "Warp / GR / NHM2",
    shortTitle: "Warp/GR",
    glyph: "G",
    description: "GR roots, 3+1 references, NHM2 geometry/source diagnostics, and full-solve context.",
    status: "active",
    subjects: ["general_relativity", "nhm2", "geometry", "adm", "warp", "source", "diagnostic"],
    symbols: ["G_mu_nu", "T_mu_nu", "alpha", "beta_i", "rho", "R_source", "t_proper", "qei_margin"],
    unitSignatures: ["L^-2", "M L^-1 T^-2", "L T^-1", "T"],
    equationFamilies: [
      "einstein_field_equation",
      "adm_decomposition",
      "lapse_shift_profile",
      "energy_density_proxy",
      "duty_cycle_average",
      "source_residual",
      "qei_sampling_window",
    ],
    simulationOwners: ["NHM2", "general_relativity"],
    repoPathHints: ["configs/warp-needle-hull-mark2-theory-directory.v1.json", "scripts/warp-full-solve-calculator.ts"],
    primaryBadgeIds: [
      "physics.gr.einstein_field_equation",
      "physics.gr.stress_energy_conservation",
      "physics.gr.3p1_decomposition",
      "nhm2.geometry.lapse_shift_profile",
      "nhm2.source.energy_density_proxy",
      "nhm2.tile.duty_cycle_average",
      "nhm2.closure.source_residual",
      "nhm2.energy_condition.diagnostic_gate",
      "nhm2.claim_boundary.diagnostic_only",
    ],
    rootBadgeIds: ["physics.fields.stress_energy_tensor", "physics.energy.energy_density"],
    claimBoundaryBadgeIds: ["nhm2.claim_boundary.diagnostic_only"],
    calculatorExamples: [
      {
        label: "Lapse-shift scalar timing",
        expression: "t_proper = t_shift + delta_t_lapse",
        displayLatex: "t_{proper}=t_{shift}+\\Delta t_{lapse}",
        symbols: ["t_proper", "t_shift", "delta_t_lapse"],
      },
      {
        label: "Source residual",
        expression: "R_source = source_required - source_available",
        displayLatex: "R_{source}=source_{required}-source_{available}",
        symbols: ["R_source", "source_required", "source_available"],
      },
    ],
    runtimeActions: [
      {
        actionId: "theory-badge-graph.run_badge_path",
        label: "Run NHM2 diagnostic badge path",
        badgeId: "nhm2.claim_boundary.diagnostic_only",
        note: "Runs scalar badge-path playback only; tensor/runtime steps remain context rows.",
      },
    ],
    sourceRefs: [
      sourceRef("config", "configs/warp-needle-hull-mark2-theory-directory.v1.json", "NHM2 theory directory."),
      sourceRef("runtime", "scripts/warp-full-solve-calculator.ts", "Full-solve calculator script."),
    ],
    claimBoundaryNotes: ["NHM2 rows remain diagnostic-only and must not be promoted into propulsion claims."],
  },
  {
    id: "qei_stress_energy",
    title: "QEI / Stress-Energy",
    shortTitle: "QEI",
    glyph: "Q",
    description: "Energy-condition gates, QEI sampling margins, stress-energy units, and source residual diagnostics.",
    status: "active",
    subjects: ["qei", "stress_energy", "energy_conditions", "diagnostic", "source", "energy_density"],
    symbols: ["qei_margin", "qei_bound", "qei_sample", "T_mu_nu", "rho", "R_source"],
    unitSignatures: ["M L^-1 T^-2"],
    equationFamilies: [
      "qei_sampling_window",
      "stress_energy_tensor",
      "energy_condition_gate",
      "energy_density_proxy",
      "source_residual",
    ],
    simulationOwners: ["NHM2", "general_relativity"],
    repoPathHints: ["configs/physics-equation-backbone.v1.json", "server/gr/evolution/stress-energy.ts"],
    primaryBadgeIds: [
      "physics.fields.stress_energy_tensor",
      "physics.gr.stress_energy_conservation",
      "nhm2.source.energy_density_proxy",
      "nhm2.closure.source_residual",
      "nhm2.qei.sampling_window",
      "nhm2.energy_condition.diagnostic_gate",
      "nhm2.claim_boundary.diagnostic_only",
    ],
    rootBadgeIds: ["physics.energy.energy_density", "physics.gr.stress_energy_conservation"],
    claimBoundaryBadgeIds: ["nhm2.claim_boundary.diagnostic_only"],
    calculatorExamples: [
      {
        label: "Source residual",
        expression: "R_source = source_required - source_available",
        displayLatex: "R_{source}=source_{required}-source_{available}",
        symbols: ["R_source", "source_required", "source_available"],
      },
      {
        label: "QEI margin",
        expression: "qei_margin = qei_bound - qei_sample",
        displayLatex: "qei_{margin}=qei_{bound}-qei_{sample}",
        symbols: ["qei_margin", "qei_bound", "qei_sample"],
      },
    ],
    runtimeActions: [],
    sourceRefs: [
      sourceRef("config", "configs/physics-equation-backbone.v1.json", "Physics equation backbone."),
      sourceRef("repo_module", "server/gr/evolution/stress-energy.ts", "Stress-energy runtime module."),
    ],
    claimBoundaryNotes: ["QEI and energy-condition rows are diagnostics and cannot be promoted to physical confirmation."],
  },
  {
    id: "tokamak_plasma",
    title: "Tokamak Plasma",
    shortTitle: "Plasma",
    glyph: "⊙",
    description: "Tokamak energy fields, stability proxies, precursor detection, and synthetic diagnostics.",
    status: "active",
    subjects: ["tokamak", "plasma", "pressure", "beta", "diagnostics", "energy_field", "precursor", "flux"],
    symbols: [
      "p_B",
      "p_Pa",
      "beta",
      "B_T",
      "n_m3",
      "T_eV",
      "P_net",
      "W_th",
      "precursor_margin",
      "core_fraction",
      "edge_fraction",
    ],
    unitSignatures: ["1", "Theta", "M L^-1 T^-2"],
    equationFamilies: [
      "plasma_pressure",
      "plasma_beta",
      "tokamak_power_balance",
      "tokamak_confinement_proxy",
      "tokamak_precursor",
      "tokamak_flux_band",
      "tokamak_energy_field",
      "tokamak_synthetic_diagnostics",
    ],
    simulationOwners: ["tokamak"],
    repoPathHints: [
      "shared/theory/tokamak-plasma-theory-badges.ts",
      "shared/tokamak-sim.ts",
      "shared/tokamak-stability-proxies.ts",
      "shared/tokamak-energy-field.ts",
      "shared/tokamak-synthetic-diagnostics.ts",
      "shared/tokamak-precursor.ts",
      "shared/tokamak-flux-coords.ts",
    ],
    primaryBadgeIds: [
      "tokamak.plasma.magnetic_pressure",
      "tokamak.plasma.thermal_pressure_proxy",
      "tokamak.plasma.beta_proxy",
      "tokamak.energy.power_balance",
      "tokamak.energy.confinement_time_proxy",
      "tokamak.precursor.score_margin",
      "tokamak.flux.core_fraction",
      "tokamak.flux.edge_fraction",
      "tokamak.runtime.energy_field",
      "tokamak.runtime.synthetic_diagnostics",
      "tokamak.runtime.precursor_report",
      "tokamak.claim_boundary.diagnostic_proxy",
    ],
    rootBadgeIds: ["physics.energy.power_rate", "physics.fields.stress_energy_tensor"],
    claimBoundaryBadgeIds: ["tokamak.claim_boundary.diagnostic_proxy"],
    calculatorExamples: [
      {
        label: "Magnetic pressure",
        expression: "p_B = B_T^2/(2*mu0)",
        displayLatex: "p_B=\\frac{B^2}{2\\mu_0}",
        symbols: ["p_B", "B_T", "mu0"],
      },
      {
        label: "Beta proxy",
        expression: "beta = p_Pa/p_B",
        displayLatex: "\\beta=\\frac{p}{p_B}",
        symbols: ["beta", "p_Pa", "p_B"],
      },
      {
        label: "Power balance proxy",
        expression: "P_net = P_in - P_loss",
        displayLatex: "P_{net}=P_{in}-P_{loss}",
        symbols: ["P_net", "P_in", "P_loss"],
      },
    ],
    runtimeActions: [
      {
        actionId: "theory-badge-graph.locate_context",
        label: "Locate tokamak runtime context",
        note: "Locates tokamak runtime/reference badges; scalar rows remain calculator-only.",
      },
    ],
    sourceRefs: [
      sourceRef("repo_module", "shared/tokamak-sim.ts", "Tokamak simulation types."),
      sourceRef("repo_module", "shared/tokamak-energy-field.ts", "RZ energy-field contract."),
      sourceRef("repo_module", "shared/tokamak-stability-proxies.ts", "Reduced stability proxy metrics."),
      sourceRef("repo_module", "shared/tokamak-synthetic-diagnostics.ts", "Synthetic diagnostics."),
      sourceRef("repo_module", "shared/tokamak-precursor.ts", "Precursor report contract."),
      sourceRef("repo_module", "shared/tokamak-flux-coords.ts", "Flux-band mask generation."),
    ],
    claimBoundaryNotes: [
      "Tokamak scalar rows are diagnostic/proxy helpers and do not establish plasma stability.",
      "Runtime receipts are required before interpreting energy-field, synthetic diagnostic, or precursor outputs.",
    ],
  },
  {
    id: "galactic_dynamics",
    title: "Galactic Dynamics",
    shortTitle: "Galactic",
    glyph: "◎",
    description: "StarMap distances, relative velocities, galactic rotation controls, and Accordion null-model context.",
    status: "active",
    subjects: [
      "galactic",
      "star_map",
      "distance",
      "relative_velocity",
      "rotation_curve",
      "accordion",
      "null_model",
      "bound_system",
      "self_gravity",
      "tidal_response",
      "love_number",
      "granular",
      "rubble_pile",
      "material_response",
    ],
    symbols: [
      "distance_pc",
      "relativeVelocity_kms",
      "structureWeight",
      "dx_pc",
      "dy_pc",
      "dz_pc",
      "dvx_kms",
      "dvy_kms",
      "dvz_kms",
      "v_rot",
      "v_obs",
      "v_model",
      "velocity_residual",
      "rms_residual",
      "M_enc",
      "r_kpc",
      "R_p_proxy",
      "sigma_y",
      "rho",
      "Q_tide",
      "E_stored",
      "E_lost_per_cycle",
      "h2",
      "U_tide",
      "g_surface",
      "deltaR_m",
    ],
    unitSignatures: ["L", "L T^-1"],
    equationFamilies: [
      "star_map_distance",
      "relative_velocity",
      "star_map_structure_weight",
      "rotation_curve",
      "rotation_curve_residual",
      "rotation_curve_controls",
      "accordion_galactic_null_model",
      "potato_radius_strength_balance",
      "granular_dissipation_closure",
      "tidal_quality_factor",
      "love_number_response",
      "granular_tidal_response",
    ],
    simulationOwners: ["starsim", "starsim_accordion", "self_gravity_shape", "granular_tidal_response"],
    repoPathHints: [
      "shared/theory/galactic-dynamics-theory-badges.ts",
      "shared/theory/granular-tidal-love-number-theory-badges.ts",
      "shared/starsim-fusion-microphysics.ts",
      "shared/starsim-accordion-galactic-null-model.ts",
      "shared/starsim-galactic-rotation-controls.ts",
      "docs/knowledge/physics/tidal-bulge-response.md",
      "docs/knowledge/physics/tidal-quality-factor.md",
      "docs/knowledge/physics/granular-tidal-response-diagnostic.md",
      "docs/knowledge/math-claims/starsim-accordion-galactic-dynamics.claims.json",
    ],
    primaryBadgeIds: [
      "galactic.map.distance_3d",
      "galactic.map.relative_velocity",
      "galactic.map.structure_weight_proxy",
      "galactic.rotation.circular_velocity_newtonian",
      "galactic.rotation.centripetal_acceleration",
      "galactic.rotation.velocity_residual",
      "galactic.rotation.rms_residual_proxy",
      "galactic.runtime.rotation_controls",
      "galactic.runtime.accordion_null_model",
      "starsim.map.structure_weight",
      "starsim.runtime.build_star_map_fusion_graph",
      "self_gravity.shape.strength_balance",
      "granular.rubble_pile.dissipation_closure",
      "tidal.quality_factor.damping_proxy",
      "tidal.love_number.displacement_response",
      "tidal.runtime.granular_response_diagnostic",
    ],
    rootBadgeIds: ["physics.frames.lorentz_factor", "physics.energy.energy_density"],
    claimBoundaryBadgeIds: [
      "galactic.claim_boundary.null_model_only",
      "starsim.claim_boundary.stage1_reduced_order_prior",
      "tidal.claim_boundary.material_response_only",
    ],
    calculatorExamples: [
      {
        label: "3D map distance",
        expression: "distance_pc = sqrt(dx_pc^2 + dy_pc^2 + dz_pc^2)",
        displayLatex: "d=\\sqrt{\\Delta x^2+\\Delta y^2+\\Delta z^2}",
        symbols: ["distance_pc", "dx_pc", "dy_pc", "dz_pc"],
      },
      {
        label: "Relative velocity",
        expression: "relativeVelocity_kms = sqrt(dvx_kms^2 + dvy_kms^2 + dvz_kms^2)",
        displayLatex: "v_{rel}=\\sqrt{\\Delta v_x^2+\\Delta v_y^2+\\Delta v_z^2}",
        symbols: ["relativeVelocity_kms", "dvx_kms", "dvy_kms", "dvz_kms"],
      },
      {
        label: "Rotation velocity residual",
        expression: "velocity_residual = v_obs - v_model",
        displayLatex: "\\Delta v=v_{obs}-v_{model}",
        symbols: ["velocity_residual", "v_obs", "v_model"],
      },
      {
        label: "StarMap structure weight",
        expression: "structureWeight = 1/(1 + distance_pc)",
        displayLatex: "w_{structure}=\\frac{1}{1+d_{pc}}",
        symbols: ["structureWeight", "distance_pc"],
      },
      {
        label: "Self-gravity strength balance",
        expression: "R_p_proxy = sqrt(sigma_y/(G*rho^2))",
        displayLatex: "R_p\\approx\\sqrt{\\frac{\\sigma_y}{G\\rho^2}}",
        symbols: ["R_p_proxy", "sigma_y", "G", "rho"],
      },
      {
        label: "Tidal Q dissipation",
        expression: "Q_tide = 2*pi*E_stored/E_lost_per_cycle",
        displayLatex: "Q_{tide}=\\frac{2\\pi E_{stored}}{E_{lost/cycle}}",
        symbols: ["Q_tide", "E_stored", "E_lost_per_cycle"],
      },
      {
        label: "Love-number radial displacement",
        expression: "deltaR_m = h2*U_tide/g_surface",
        displayLatex: "\\Delta R=h_2U_{tide}/g_{surface}",
        symbols: ["deltaR_m", "h2", "U_tide", "g_surface"],
      },
    ],
    runtimeActions: [
      {
        actionId: "theory-badge-graph.locate_context",
        label: "Locate galactic dynamics context",
        note: "Locates galactic null-model and rotation-control badges; runtime comparison remains separate.",
      },
    ],
    sourceRefs: [
      sourceRef("repo_module", "shared/theory/galactic-dynamics-theory-badges.ts", "Galactic theory badge seed."),
      sourceRef("repo_module", "shared/theory/granular-tidal-love-number-theory-badges.ts", "Granular/tidal Love-number badge seed."),
      sourceRef("repo_module", "shared/starsim-fusion-microphysics.ts", "StarMap graph builder support."),
      sourceRef("repo_module", "shared/starsim-accordion-galactic-null-model.ts", "Accordion galactic null model."),
      sourceRef("repo_module", "shared/starsim-galactic-rotation-controls.ts", "Galactic rotation controls."),
      sourceRef("doc", "docs/knowledge/physics/tidal-bulge-response.md", "Tidal deformation response."),
      sourceRef("doc", "docs/knowledge/physics/tidal-quality-factor.md", "Tidal Q dissipation summary."),
      sourceRef("doc", "docs/knowledge/physics/granular-tidal-response-diagnostic.md", "Low-order rubble-pile closure."),
      sourceRef("doc", "docs/knowledge/math-claims/starsim-accordion-galactic-dynamics.claims.json", "Claim boundary ledger."),
    ],
    claimBoundaryNotes: [
      "Galactic rows are null-model and population-prior helpers; they do not select a physics winner.",
      "Bound systems require local dynamics context, not local Hubble-flow interpretation.",
      "Granular/tidal rows are material-response diagnostics and require body-specific evidence before interpretation.",
    ],
  },
  {
    id: "curvature_collapse",
    title: "Curvature / Collapse",
    shortTitle: "Collapse",
    glyph: "κ",
    description: "Curvature proxy rows, objective-collapse comparison seeds, collapse benchmark cadence, uncertainty margins, and diagnostic runtime receipts.",
    status: "active",
    subjects: [
      "curvature",
      "collapse",
      "objective_collapse",
      "dp",
      "benchmark",
      "uncertainty",
      "kappa",
      "runtime",
      "orch_or",
      "microtubule",
      "gamma_synchrony",
      "time_crystal",
      "coherence",
    ],
    symbols: [
      "kappa_body",
      "kappa_drive",
      "eta_kappa",
      "E_J",
      "f_Hz",
      "T_s",
      "delta_rho",
      "deltaE_G_J",
      "tau_DP_s",
      "tau_DP_ms",
      "Gamma_DP_Hz",
      "L_present_DP",
      "p_DP_trigger",
      "dt_s",
      "p_trigger",
      "L_present",
      "kappa_present",
      "margin",
      "z_score",
      "tau_ms",
      "r_c_m",
      "tau_coherence_s",
      "coherence_margin_s",
      "f_mt_Hz",
      "T_mt_s",
      "f_gamma_Hz",
      "T_gamma_s",
      "phase_lock_ratio",
      "N_gamma_cycles",
      "subharmonic_ratio",
      "f_response_Hz",
      "f_drive_Hz",
    ],
    unitSignatures: ["L^-2", "L", "T", "T^-1", "M L^2 T^-2", "M L^-3", "1"],
    equationFamilies: [
      "curvature_proxy",
      "collapse_benchmark",
      "objective_collapse",
      "dp_collapse",
      "energy_frequency",
      "mass_energy",
      "objective_collapse_bounds",
      "uncertainty_propagation",
      "curvature_benchmark",
      "orch_or_comparison",
      "coherence_window",
      "microtubule_observable",
      "neural_oscillation",
      "frequency_ratio",
      "cross_scale_locking",
      "time_crystal_criteria",
      "subharmonic_locking",
      "orch_or_claim_boundary",
    ],
    simulationOwners: ["curvature_collapse", "warp_gr_nhm2", "orch_or_coherence"],
    repoPathHints: [
      "shared/theory/curvature-collapse-theory-badges.ts",
      "shared/theory/orch-or-coherence-theory-badges.ts",
      "shared/curvature-proxy.ts",
      "shared/collapse-benchmark.ts",
      "shared/dp-collapse.ts",
      "client/src/physics/curvature.ts",
      "docs/DP_COLLAPSE_DERIVATION.md",
      "docs/architecture/orch-or-time-crystal-research-packet.md",
      "server/routes/benchmarks.collapse.ts",
      "server/services/collapse-benchmark.ts",
      "scripts/curvature-leverage-benchmark-ladder.ts",
    ],
    primaryBadgeIds: [
      "curvature.proxy.body_density",
      "curvature.proxy.drive_power_flux",
      "curvature.proxy.drive_body_ratio",
      "collapse.objective.energy_frequency_period",
      "collapse.objective.mass_energy_density",
      "collapse.objective.mass_density_branch_difference",
      "collapse.objective.dp_gravitational_self_energy",
      "collapse.objective.dp_timescale",
      "collapse.objective.dp_rate",
      "collapse.objective.present_window",
      "collapse.objective.dp_hazard_probability",
      "collapse.objective.experimental_bounds",
      "collapse.benchmark.hazard_probability",
      "collapse.benchmark.present_length",
      "collapse.benchmark.kappa_present",
      "curvature.uncertainty.margin",
      "curvature.uncertainty.z_score",
      "collapse.runtime.benchmark_route",
      "curvature.runtime.leverage_benchmark",
      "orch_or.microtubule.coherence_window",
      "orch_or.microtubule.mode_frequency",
      "orch_or.gamma_synchrony.neural_band",
      "orch_or.frequency_hierarchy.cross_scale_locking",
      "orch_or.time_crystal.subharmonic_locking_test",
      "orch_or.time_crystal.robustness_window",
    ],
    rootBadgeIds: [
      "physics.gr.einstein_field_equation",
      "physics.units.dimension_consistency",
      "physics.quantum.energy_frequency",
      "physics.energy.energy_density",
    ],
    claimBoundaryBadgeIds: ["curvature.claim_boundary.benchmark_only", "orch_or.claim_boundary.exploratory_only"],
    calculatorExamples: [
      {
        label: "Body curvature proxy",
        expression: "kappa_body = 6.217e-27*rho_kg_m3",
        displayLatex: "\\kappa_{body}=\\frac{8\\pi G}{3c^2}\\rho",
        symbols: ["kappa_body", "rho_kg_m3"],
      },
      {
        label: "Collapse hazard",
        expression: "p_trigger = 1 - exp(-dt_ms/tau_ms)",
        displayLatex: "p=1-e^{-dt/\\tau}",
        symbols: ["p_trigger", "dt_ms", "tau_ms"],
      },
      {
        label: "Energy period",
        expression: "T_s = h/E_J",
        displayLatex: "T=h/E",
        symbols: ["T_s", "h", "E_J"],
      },
      {
        label: "DP timescale",
        expression: "tau_DP_s = hbar/deltaE_G_J",
        displayLatex: "\\tau_{DP}=\\hbar/\\Delta E_G",
        symbols: ["tau_DP_s", "hbar", "deltaE_G_J"],
      },
      {
        label: "DP rate",
        expression: "Gamma_DP_Hz = deltaE_G_J/hbar",
        displayLatex: "\\Gamma_{DP}=\\Delta E_G/\\hbar",
        symbols: ["Gamma_DP_Hz", "deltaE_G_J", "hbar"],
      },
      {
        label: "DP present window",
        expression: "L_present_DP = min(r_c_m, c*tau_DP_s)",
        displayLatex: "L_{present,DP}=\\min(r_c,c\\tau_{DP})",
        symbols: ["L_present_DP", "r_c_m", "c", "tau_DP_s"],
      },
      {
        label: "DP timestep hazard",
        expression: "p_DP_trigger = 1 - exp(-dt_s/tau_DP_s)",
        displayLatex: "p_{DP}(dt)=1-e^{-dt/\\tau_{DP}}",
        symbols: ["p_DP_trigger", "dt_s", "tau_DP_s"],
      },
      {
        label: "Kappa present",
        expression: "kappa_present = 1/(L_present^2)",
        displayLatex: "\\kappa_{present}=1/L_{present}^2",
        symbols: ["kappa_present", "L_present"],
      },
      {
        label: "Uncertainty margin",
        expression: "margin = observed - bound",
        displayLatex: "margin=observed-bound",
        symbols: ["margin", "observed", "bound"],
      },
      {
        label: "Orch-OR coherence margin",
        expression: "coherence_margin_s = tau_coherence_s - tau_DP_s",
        displayLatex: "\\Delta t_{coh}=\\tau_{coherence}-\\tau_{DP}",
        symbols: ["coherence_margin_s", "tau_coherence_s", "tau_DP_s"],
      },
      {
        label: "Gamma period",
        expression: "T_gamma_s = 1/f_gamma_Hz",
        displayLatex: "T_\\gamma=1/f_\\gamma",
        symbols: ["T_gamma_s", "f_gamma_Hz"],
      },
      {
        label: "Gamma cycles per DP tau",
        expression: "N_gamma_cycles = tau_DP_s*f_gamma_Hz",
        displayLatex: "N_\\gamma=\\tau_{DP}f_\\gamma",
        symbols: ["N_gamma_cycles", "tau_DP_s", "f_gamma_Hz"],
      },
      {
        label: "Time-crystal subharmonic ratio",
        expression: "subharmonic_ratio = f_response_Hz/f_drive_Hz",
        displayLatex: "R_{sub}=f_{response}/f_{drive}",
        symbols: ["subharmonic_ratio", "f_response_Hz", "f_drive_Hz"],
      },
    ],
    runtimeActions: [
      {
        actionId: "theory-badge-graph.locate_context",
        label: "Locate curvature/collapse context",
        note: "Locates curvature proxy and collapse benchmark badges; runtime receipts remain separate.",
      },
    ],
    sourceRefs: [
      sourceRef("repo_module", "shared/theory/curvature-collapse-theory-badges.ts", "Curvature/collapse theory badge seed."),
      sourceRef("repo_module", "shared/theory/orch-or-coherence-theory-badges.ts", "Exploratory Orch-OR/coherence theory badge seed."),
      sourceRef("repo_module", "shared/curvature-proxy.ts", "Curvature proxy helpers."),
      sourceRef("repo_module", "shared/collapse-benchmark.ts", "Collapse benchmark contract and scalar helpers."),
      sourceRef("repo_module", "shared/dp-collapse.ts", "Diosi-Penrose collapse diagnostic helpers."),
      sourceRef("repo_module", "client/src/physics/curvature.ts", "Client curvature helpers."),
      sourceRef("doc", "docs/DP_COLLAPSE_DERIVATION.md", "DP collapse derivation and diagnostic boundary."),
      sourceRef("doc", "docs/architecture/orch-or-time-crystal-research-packet.md", "Exploratory gravity-related collapse source packet."),
      sourceRef("repo_module", "server/routes/benchmarks.collapse.ts", "Collapse benchmark route."),
      sourceRef("repo_module", "server/services/collapse-benchmark.ts", "Collapse benchmark service."),
      sourceRef("runtime", "scripts/curvature-leverage-benchmark-ladder.ts", "Curvature benchmark ladder."),
    ],
    claimBoundaryNotes: [
      "Curvature/collapse rows are benchmark diagnostics unless backed by explicit receipts.",
      "Objective-collapse rows are exploratory model-comparison helpers, not proof of physical wavefunction collapse.",
      "DP timescale and rate rows require mass-density branch evidence and experimental-bound context.",
      "Orch-OR rows are exploratory comparison helpers, not consciousness or objective-collapse validation.",
      "Gamma synchrony and microtubule frequency rows do not establish a biological time crystal.",
      "Calculator rows do not certify curvature gravity or provide mechanism claims.",
    ],
  },
];

export function buildPhysicsAtlasBlocks(_args: { graph: TheoryBadgeGraphV1 }): PhysicsAtlasBlockV1[] {
  return PHYSICS_ATLAS_BLOCKS.map((block: PhysicsAtlasBlockV1) => ({ ...block }));
}

export function buildHelixPhysicsAtlasV1(args: { graph: TheoryBadgeGraphV1 }): PhysicsAtlasV1 {
  return buildPhysicsAtlasV1({
    graphId: args.graph.graphId,
    alwaysOnFoundationSubjects: ["units", "dimensions", "constants", "energy", "relativity", "stress_energy"],
    alwaysOnFoundationBadgeIds: [
      "physics.units.dimension_consistency",
      "physics.constants.speed_of_light",
      "physics.quantum.energy_frequency",
      "physics.energy.energy_density",
      "physics.energy.power_rate",
      "physics.fields.stress_energy_tensor",
    ],
    alwaysOnClaimBoundaryBadgeIds: [
      "nhm2.claim_boundary.diagnostic_only",
      "starsim.claim_boundary.stage1_reduced_order_prior",
      "solar.claim_boundary.observational_proxy",
      "casimir.claim_boundary.diagnostic_source_context",
    ],
    blocks: buildPhysicsAtlasBlocks(args),
  });
}

export function buildPhysicsAtlasBlocksV1(graphId = "nhm2-theory-badge-graph"): PhysicsAtlasV1 {
  return buildPhysicsAtlasV1({
    graphId,
    alwaysOnFoundationSubjects: ["units", "dimensions", "constants", "energy", "relativity", "stress_energy"],
    alwaysOnFoundationBadgeIds: [
      "physics.units.dimension_consistency",
      "physics.constants.speed_of_light",
      "physics.quantum.energy_frequency",
      "physics.energy.energy_density",
      "physics.energy.power_rate",
      "physics.fields.stress_energy_tensor",
    ],
    alwaysOnClaimBoundaryBadgeIds: [
      "nhm2.claim_boundary.diagnostic_only",
      "starsim.claim_boundary.stage1_reduced_order_prior",
      "solar.claim_boundary.observational_proxy",
      "casimir.claim_boundary.diagnostic_source_context",
    ],
    blocks: PHYSICS_ATLAS_BLOCKS,
  });
}
