import {
  buildPhysicsAtlasV1,
  type PhysicsAtlasBlockV1,
  type PhysicsAtlasV1,
} from "../contracts/physics-atlas.v1";
import type { TheoryBadgeGraphV1 } from "../contracts/theory-badge-graph.v1";

const sourceRef = (
  kind: PhysicsAtlasBlockV1["sourceRefs"][number]["kind"],
  path: string,
  note?: string,
  id?: string,
): PhysicsAtlasBlockV1["sourceRefs"][number] => ({
  kind,
  path,
  id: id ?? null,
  note: note ?? null,
});

export const PHYSICS_ATLAS_BLOCKS: PhysicsAtlasBlockV1[] = [
  {
    id: "stellar_evolution",
    title: "Stellar Evolution",
    shortTitle: "Stellar",
    glyph: "★",
    description: "StarSim stellar stages, object bindings, scalar observables, runtime classification, and Stage 1 boundaries.",
    status: "active",
    subjects: ["starsim", "stellar", "stellar_structure", "fusion", "main_sequence", "red_giant", "compact_object"],
    symbols: ["T_eff", "M", "R", "L", "rho_mean", "compactness_scale", "dominantFusionChannel"],
    unitSignatures: ["Theta", "M", "L", "M L^-3"],
    equationFamilies: ["stellar_observable_proxy", "stellar_structure_proxy", "fusion_classifier_margin"],
    simulationOwners: ["starsim"],
    repoPathHints: [
      "shared/theory/starsim-theory-badges.ts",
      "shared/theory/starsim-stellar-evolution-map.ts",
      "shared/starsim-fusion-microphysics.ts",
    ],
    primaryBadgeIds: [
      "starsim.observable.surface_temperature_proxy",
      "starsim.observable.surface_gravity",
      "starsim.observable.mean_density",
      "starsim.runtime.evaluate_fusion_microphysics",
      "starsim.claim_boundary.stage1_reduced_order_prior",
    ],
    rootBadgeIds: ["physics.energy.energy_density", "physics.energy.power_rate"],
    claimBoundaryBadgeIds: ["starsim.claim_boundary.stage1_reduced_order_prior"],
    calculatorExamples: [
      {
        label: "Surface temperature proxy",
        expression: "T_eff = T_sun*(L/(R^2))^(1/4)",
        displayLatex: "T_{eff}=T_{sun}\\left(\\frac{L}{R^2}\\right)^{1/4}",
        symbols: ["T_eff", "T_sun", "L", "R"],
      },
    ],
    runtimeActions: [
      {
        actionId: "theory-badge-graph.run_runtime_badge",
        label: "Run StarSim fusion microphysics",
        badgeId: "starsim.runtime.evaluate_fusion_microphysics",
        note: "Returns a StarSim runtime receipt; calculator rows remain scalar support.",
      },
    ],
    sourceRefs: [
      sourceRef("repo_module", "shared/starsim-fusion-microphysics.ts", "StarSim Stage 1 reduced-order runtime."),
      sourceRef("repo_module", "shared/theory/starsim-theory-badges.ts", "Theory badge branch."),
      sourceRef("doc", "docs/research/starsim-fusion-microphysics-stage1.md", "Stage 1 caveats and boundaries."),
    ],
    claimBoundaryNotes: [
      "StarSim Stage 1 is a reduced-order astrophysical prior lane, not a full stellar-evolution solve.",
      "StarSim paths stay in reduced-order prior scope and cannot promote external physics claims.",
    ],
  },
  {
    id: "cosmic_distance_ladder",
    title: "Cosmic Distance Ladder",
    shortTitle: "Distance",
    glyph: "z",
    description: "Spectral shifts, parallax, Cepheids, distance modulus, and Hubble-law distance estimates.",
    status: "active",
    subjects: ["cosmic_distance", "redshift", "blueshift", "parallax", "cepheid", "standard_candle", "hubble_law"],
    symbols: ["z", "lambda_obs", "lambda_rest", "d_pc", "P_days", "M_abs", "m_app", "H0"],
    unitSignatures: ["1", "L", "T"],
    equationFamilies: ["spectral_shift", "parallax_distance", "cepheid_period_luminosity", "distance_modulus", "hubble_law"],
    simulationOwners: ["cosmic_distance_ladder", "starsim_accordion"],
    repoPathHints: ["shared/theory/cosmic-distance-ladder-badges.ts", "shared/starsim-accordion-cosmology-context.ts"],
    primaryBadgeIds: [
      "cosmic.spectral.redshift",
      "cosmic.parallax.distance",
      "cosmic.cepheid.period_luminosity",
      "cosmic.distance_modulus",
      "cosmic.hubble_law.distance",
    ],
    rootBadgeIds: ["physics.constants.speed_of_light", "physics.frames.lorentz_factor"],
    claimBoundaryBadgeIds: ["cosmic.claim_boundary.distance_model_dependent"],
    calculatorExamples: [
      {
        label: "Redshift from wavelength",
        expression: "z = (lambda_obs - lambda_rest) / lambda_rest",
        displayLatex: "z=\\frac{\\lambda_{obs}-\\lambda_{rest}}{\\lambda_{rest}}",
        symbols: ["z", "lambda_obs", "lambda_rest"],
      },
    ],
    runtimeActions: [],
    sourceRefs: [
      sourceRef("repo_module", "shared/theory/cosmic-distance-ladder-badges.ts", "Cosmic ladder badge branch."),
      sourceRef("repo_module", "shared/starsim-accordion-cosmology-context.ts", "Accordion cosmology context."),
    ],
    claimBoundaryNotes: [
      "Distance-ladder estimates are calibration/model dependent.",
      "Cosmological background expansion must not be conflated with local bound-system expansion.",
    ],
  },
  {
    id: "solar_surface_spectrum",
    title: "Solar Surface & Spectrum",
    shortTitle: "Solar",
    glyph: "☀",
    description: "Solar spectrum, photon energy, Doppler shifts, blackbody proxies, and flare-energy observation rows.",
    status: "active",
    subjects: ["solar", "spectrum", "wavelength", "radiation", "blackbody", "flare", "doppler"],
    symbols: ["lambda", "lambda_obs", "lambda0", "f", "E", "v", "T", "F", "E_flare"],
    unitSignatures: ["L", "T^-1", "M L^2 T^-2", "L T^-1", "Theta"],
    equationFamilies: ["spectral_observable", "planck_relation", "doppler_shift", "blackbody_radiation", "flare_energy_proxy"],
    simulationOwners: ["solar_spectrum", "solar_flare"],
    repoPathHints: [
      "shared/solar-spectrum-analysis.ts",
      "server/services/essence/solar-spectrum-ingest.ts",
      "server/services/essence/solar-spectrum-models.ts",
      "shared/solar-flare-observable-contract.v1.ts",
    ],
    primaryBadgeIds: [
      "solar.spectrum.frequency_from_wavelength",
      "solar.spectrum.photon_energy_wavelength",
      "solar.spectrum.doppler_velocity",
      "solar.radiation.wien_peak",
      "solar.radiation.stefan_boltzmann_flux",
      "solar.flare.radiant_energy_proxy",
      "solar.claim_boundary.observation_proxy",
    ],
    rootBadgeIds: ["physics.constants.speed_of_light", "physics.quantum.energy_frequency", "physics.energy.power_rate"],
    claimBoundaryBadgeIds: ["solar.claim_boundary.observation_proxy"],
    calculatorExamples: [
      {
        label: "Photon energy from wavelength",
        expression: "E = h*c/lambda",
        displayLatex: "E=\\frac{hc}{\\lambda}",
        symbols: ["E", "h", "c", "lambda"],
      },
      {
        label: "Solar line Doppler velocity",
        expression: "v = c*(lambda_obs - lambda0)/lambda0",
        displayLatex: "v=c\\frac{\\lambda_{obs}-\\lambda_0}{\\lambda_0}",
        symbols: ["v", "c", "lambda_obs", "lambda0"],
      },
    ],
    runtimeActions: [
      {
        actionId: "theory-badge-graph.locate_context",
        label: "Locate solar spectrum context",
        note: "Locates solar spectrum badges and calculator payloads; observation runtimes remain separate.",
      },
    ],
    sourceRefs: [
      sourceRef("repo_module", "shared/solar-spectrum-analysis.ts", "Solar spectrum analysis helpers."),
      sourceRef("repo_module", "server/services/essence/solar-spectrum-ingest.ts", "Solar spectrum ingest path."),
      sourceRef("contract", "shared/solar-flare-observable-contract.v1.ts", "Solar flare observable contract."),
      sourceRef("doc", "docs/knowledge/physics/solar-radiative-observables-tree.json", "Solar radiative observables tree."),
    ],
    claimBoundaryNotes: [
      "Solar spectral and flare rows are observation/model proxies.",
      "Instrument calibration and bandpass context are required before physical interpretation.",
    ],
  },
  {
    id: "casimir_cavity_modes",
    title: "Casimir Cavities",
    shortTitle: "Casimir",
    glyph: "▣",
    description: "Static and dynamic Casimir, cavity modes, Q factors, gaps, and cavity telemetry.",
    status: "planned",
    subjects: ["casimir", "cavity", "negative_energy", "q_factor", "mode_frequency"],
    symbols: ["a", "gap", "Q", "U_static", "rho", "omega"],
    unitSignatures: ["L", "M L^2 T^-2", "M L^-1 T^-2", "T^-1"],
    equationFamilies: ["casimir_energy", "cavity_mode", "q_factor"],
    simulationOwners: ["casimir", "NHM2"],
    repoPathHints: ["modules/sim_core/static-casimir.ts", "modules/dynamic/dynamic-casimir.ts", "server/services/casimir/telemetry.ts"],
    primaryBadgeIds: ["nhm2.source.energy_density_proxy"],
    rootBadgeIds: ["physics.energy.energy_density", "physics.quantum.energy_frequency"],
    claimBoundaryBadgeIds: ["nhm2.claim_boundary.diagnostic_only"],
    calculatorExamples: [
      {
        label: "Cavity energy density proxy",
        expression: "rho = E / V",
        displayLatex: "\\rho=\\frac{E}{V}",
        symbols: ["rho", "E", "V"],
      },
    ],
    runtimeActions: [],
    sourceRefs: [
      sourceRef("repo_module", "modules/sim_core/static-casimir.ts", "Static Casimir simulation path."),
      sourceRef("repo_module", "modules/dynamic/dynamic-casimir.ts", "Dynamic Casimir simulation path."),
      sourceRef("repo_module", "server/services/casimir/telemetry.ts", "Casimir telemetry service."),
    ],
    claimBoundaryNotes: ["Casimir rows are diagnostic/source-context rows and do not establish propulsion evidence."],
  },
  {
    id: "warp_gr_nhm2",
    title: "Warp / GR / NHM2",
    shortTitle: "Warp",
    glyph: "G",
    description: "GR roots, 3+1 references, NHM2 geometry/source diagnostics, and full-solve context.",
    status: "planned",
    subjects: ["general_relativity", "nhm2", "geometry", "adm", "warp", "source"],
    symbols: ["G_mu_nu", "T_mu_nu", "alpha", "beta_i", "rho", "R_source"],
    unitSignatures: ["L^-2", "M L^-1 T^-2", "L T^-1"],
    equationFamilies: ["einstein_field_equation", "adm_decomposition", "lapse_shift_profile", "source_residual"],
    simulationOwners: ["NHM2", "general_relativity"],
    repoPathHints: ["configs/warp-needle-hull-mark2-theory-directory.v1.json", "scripts/warp-full-solve-calculator.ts"],
    primaryBadgeIds: [
      "physics.gr.einstein_field_equation",
      "physics.gr.3p1_decomposition",
      "nhm2.geometry.lapse_shift_profile",
      "nhm2.closure.source_residual",
    ],
    rootBadgeIds: ["physics.fields.stress_energy_tensor", "physics.energy.energy_density"],
    claimBoundaryBadgeIds: ["nhm2.claim_boundary.diagnostic_only"],
    calculatorExamples: [
      {
        label: "Source residual",
        expression: "R_source = source_required - source_available",
        displayLatex: "R_{source}=source_{required}-source_{available}",
        symbols: ["R_source", "source_required", "source_available"],
      },
    ],
    runtimeActions: [
      {
        actionId: "theory-badge-graph.run_badge_path",
        label: "Run NHM2 diagnostic badge path",
        badgeId: "nhm2.claim_boundary.diagnostic_only",
        note: "Runs scalar badge-path playback only; tensor/runtime steps remain context rows.",
      },
    ],
    sourceRefs: [
      sourceRef("config", "configs/warp-needle-hull-mark2-theory-directory.v1.json", "NHM2 theory directory."),
      sourceRef("runtime", "scripts/warp-full-solve-calculator.ts", "Full-solve calculator script."),
    ],
    claimBoundaryNotes: ["NHM2 rows remain diagnostic-only and must not be promoted into propulsion claims."],
  },
  {
    id: "qei_stress_energy",
    title: "QEI / Stress-Energy",
    shortTitle: "QEI",
    glyph: "Q",
    description: "Energy-condition gates, QEI sampling margins, stress-energy units, and source residual diagnostics.",
    status: "planned",
    subjects: ["qei", "stress_energy", "energy_conditions", "diagnostic", "source"],
    symbols: ["qei_margin", "qei_bound", "qei_sample", "T_mu_nu", "rho"],
    unitSignatures: ["M L^-1 T^-2"],
    equationFamilies: ["qei_sampling", "stress_energy_tensor", "energy_condition_gate"],
    simulationOwners: ["NHM2", "general_relativity"],
    repoPathHints: ["configs/physics-equation-backbone.v1.json", "server/gr/evolution/stress-energy.ts"],
    primaryBadgeIds: [
      "physics.fields.stress_energy_tensor",
      "nhm2.qei.sampling_window",
      "nhm2.energy_condition.diagnostic_gate",
    ],
    rootBadgeIds: ["physics.energy.energy_density", "physics.gr.stress_energy_conservation"],
    claimBoundaryBadgeIds: ["nhm2.claim_boundary.diagnostic_only"],
    calculatorExamples: [
      {
        label: "QEI margin",
        expression: "qei_margin = qei_bound - qei_sample",
        displayLatex: "qei_{margin}=qei_{bound}-qei_{sample}",
        symbols: ["qei_margin", "qei_bound", "qei_sample"],
      },
    ],
    runtimeActions: [],
    sourceRefs: [
      sourceRef("config", "configs/physics-equation-backbone.v1.json", "Physics equation backbone."),
      sourceRef("repo_module", "server/gr/evolution/stress-energy.ts", "Stress-energy runtime module."),
    ],
    claimBoundaryNotes: ["QEI and energy-condition rows are diagnostics and cannot be promoted to physical confirmation."],
  },
  {
    id: "tokamak_plasma",
    title: "Tokamak Plasma",
    shortTitle: "Tokamak",
    glyph: "⊙",
    description: "Tokamak energy fields, stability proxies, precursor detection, and synthetic diagnostics.",
    status: "planned",
    subjects: ["tokamak", "plasma", "stability", "diagnostics", "energy_field"],
    symbols: ["beta", "q", "n", "T", "B", "P_loss"],
    unitSignatures: ["1", "Theta", "M L^-1 T^-2"],
    equationFamilies: ["plasma_stability", "tokamak_energy_proxy", "synthetic_diagnostics"],
    simulationOwners: ["tokamak"],
    repoPathHints: ["shared/tokamak-sim.ts", "shared/tokamak-stability-proxies.ts", "shared/tokamak-synthetic-diagnostics.ts"],
    primaryBadgeIds: [],
    rootBadgeIds: ["physics.energy.power_rate", "physics.fields.stress_energy_tensor"],
    claimBoundaryBadgeIds: [],
    calculatorExamples: [
      {
        label: "Power balance proxy",
        expression: "P_net = P_in - P_loss",
        displayLatex: "P_{net}=P_{in}-P_{loss}",
        symbols: ["P_net", "P_in", "P_loss"],
      },
    ],
    runtimeActions: [],
    sourceRefs: [
      sourceRef("repo_module", "shared/tokamak-sim.ts", "Tokamak simulation types."),
      sourceRef("repo_module", "shared/tokamak-synthetic-diagnostics.ts", "Synthetic diagnostics."),
    ],
    claimBoundaryNotes: ["Tokamak rows should separate scalar proxies from runtime stability diagnostics."],
  },
  {
    id: "galactic_dynamics",
    title: "Galactic Dynamics",
    shortTitle: "Galactic",
    glyph: "◎",
    description: "StarMap distances, relative velocities, galactic rotation controls, and Accordion null-model context.",
    status: "planned",
    subjects: ["galactic", "star_map", "distance", "relative_velocity", "accordion"],
    symbols: ["distance_pc", "relativeVelocity_kms", "v_rot", "r"],
    unitSignatures: ["L", "L T^-1"],
    equationFamilies: ["star_map_distance", "relative_velocity", "rotation_curve"],
    simulationOwners: ["starsim", "starsim_accordion"],
    repoPathHints: ["shared/starsim-accordion-galactic-null-model.ts", "shared/starsim-galactic-rotation-controls.ts"],
    primaryBadgeIds: ["starsim.map.structure_weight"],
    rootBadgeIds: ["physics.frames.lorentz_factor", "physics.energy.energy_density"],
    claimBoundaryBadgeIds: ["starsim.claim_boundary.stage1_reduced_order_prior"],
    calculatorExamples: [
      {
        label: "StarMap structure weight",
        expression: "structureWeight = 1/(1 + distance_pc)",
        displayLatex: "w_{structure}=\\frac{1}{1+d_{pc}}",
        symbols: ["structureWeight", "distance_pc"],
      },
    ],
    runtimeActions: [],
    sourceRefs: [
      sourceRef("repo_module", "shared/starsim-accordion-galactic-null-model.ts", "Accordion galactic null model."),
      sourceRef("repo_module", "shared/starsim-galactic-rotation-controls.ts", "Galactic rotation controls."),
    ],
    claimBoundaryNotes: ["Galactic dynamics rows are null-model or diagnostic context until runtime receipts are added."],
  },
  {
    id: "curvature_collapse",
    title: "Curvature / Collapse",
    shortTitle: "Collapse",
    glyph: "κ",
    description: "Curvature leverage, DP/collapse diagnostics, uncertainty propagation, and benchmark receipts.",
    status: "planned",
    subjects: ["curvature", "collapse", "dp", "benchmark", "uncertainty"],
    symbols: ["R", "K", "sigma", "collapse_margin"],
    unitSignatures: ["L^-2", "1"],
    equationFamilies: ["curvature_proxy", "collapse_benchmark", "uncertainty_propagation"],
    simulationOwners: ["curvature_collapse"],
    repoPathHints: ["client/src/physics/curvature.ts", "server/services/dp-adapters.ts", "scripts/curvature-leverage-benchmark-ladder.ts"],
    primaryBadgeIds: [],
    rootBadgeIds: ["physics.gr.einstein_field_equation", "physics.units.dimension_consistency"],
    claimBoundaryBadgeIds: [],
    calculatorExamples: [
      {
        label: "Uncertainty margin",
        expression: "margin = observed - bound",
        displayLatex: "margin=observed-bound",
        symbols: ["margin", "observed", "bound"],
      },
    ],
    runtimeActions: [],
    sourceRefs: [
      sourceRef("repo_module", "client/src/physics/curvature.ts", "Curvature client physics helpers."),
      sourceRef("repo_module", "server/services/dp-adapters.ts", "DP adapter service."),
      sourceRef("runtime", "scripts/curvature-leverage-benchmark-ladder.ts", "Curvature benchmark ladder."),
    ],
    claimBoundaryNotes: ["Curvature/collapse rows should remain benchmark diagnostics unless backed by explicit receipts."],
  },
];

export function buildPhysicsAtlasBlocks(_args: { graph: TheoryBadgeGraphV1 }): PhysicsAtlasBlockV1[] {
  return PHYSICS_ATLAS_BLOCKS.map((block: PhysicsAtlasBlockV1) => ({ ...block }));
}

export function buildHelixPhysicsAtlasV1(args: { graph: TheoryBadgeGraphV1 }): PhysicsAtlasV1 {
  return buildPhysicsAtlasV1({
    graphId: args.graph.graphId,
    alwaysOnFoundationSubjects: ["units", "dimensions", "constants", "energy", "relativity", "stress_energy"],
    alwaysOnFoundationBadgeIds: [
      "physics.units.dimension_consistency",
      "physics.constants.speed_of_light",
      "physics.quantum.energy_frequency",
      "physics.energy.energy_density",
      "physics.energy.power_rate",
      "physics.fields.stress_energy_tensor",
    ],
    alwaysOnClaimBoundaryBadgeIds: [
      "nhm2.claim_boundary.diagnostic_only",
      "starsim.claim_boundary.stage1_reduced_order_prior",
      "solar.claim_boundary.observation_proxy",
    ],
    blocks: buildPhysicsAtlasBlocks(args),
  });
}

export function buildPhysicsAtlasBlocksV1(graphId = "nhm2-theory-badge-graph"): PhysicsAtlasV1 {
  return buildPhysicsAtlasV1({
    graphId,
    alwaysOnFoundationSubjects: ["units", "dimensions", "constants", "energy", "relativity", "stress_energy"],
    alwaysOnFoundationBadgeIds: [
      "physics.units.dimension_consistency",
      "physics.constants.speed_of_light",
      "physics.quantum.energy_frequency",
      "physics.energy.energy_density",
      "physics.energy.power_rate",
      "physics.fields.stress_energy_tensor",
    ],
    alwaysOnClaimBoundaryBadgeIds: [
      "nhm2.claim_boundary.diagnostic_only",
      "starsim.claim_boundary.stage1_reduced_order_prior",
      "solar.claim_boundary.observation_proxy",
    ],
    blocks: PHYSICS_ATLAS_BLOCKS,
  });
}
