import {
  type TheoryBadgeClaimBoundaryV1,
  type TheoryBadgeEdgeV1,
  type TheoryBadgeV1,
} from "../contracts/theory-badge-graph.v1";
import { HELIX_CALCULATOR_SETUP_CONTEXT_SCHEMA } from "../helix-calculator-setup-context";

const STARSIM_BOUNDARY: TheoryBadgeClaimBoundaryV1 = {
  diagnosticOnly: true,
  doesValidateNHM2: false,
  validationClaimAllowed: false,
  physicalMechanismClaimAllowed: false,
  promotionAllowed: false,
};

const STARSIM_REPO_PATH = "shared/starsim-fusion-microphysics.ts";
const STARSIM_STAGE1_DOC = "docs/research/starsim-fusion-microphysics-stage1.md";
const STARSIM_MAP_DOC = "docs/research/starsim-accordion-galactic-dynamics-null-model-v1.md";
const DEEP_MIXING_PHYSICS_REPO_PATH = "client/src/lib/deepMixingPhysics.ts";
const DEEP_MIXING_PRESET_REPO_PATH = "client/src/lib/deepMixingPreset.ts";
const DEEP_MIXING_PLAN_DOC = "warp-web/deep-mixing-plan.html";
const DEEP_MIXING_KNOWLEDGE_DOC = "docs/knowledge/deep-mixing.md";
const SOLAR_RESTORATION_KNOWLEDGE_DOC = "docs/knowledge/solar-restoration.md";

const repoRef = (path: string, id?: string, note?: string): TheoryBadgeV1["sourceRefs"][number] => ({
  kind: "repo_module",
  path,
  id: id ?? null,
  note: note ?? null,
});

const docRef = (path: string, id?: string, note?: string): TheoryBadgeV1["sourceRefs"][number] => ({
  kind: "doc",
  path,
  id: id ?? null,
  note: note ?? null,
});

const testRef = (path: string, id?: string, note?: string): TheoryBadgeV1["sourceRefs"][number] => ({
  kind: "test",
  path,
  id: id ?? null,
  note: note ?? null,
});

const calculatorPayload = (args: {
  id: string;
  expression: string;
  displayLatex: string;
  targetVariable: string;
  subgoal: string;
  variables: Array<{
    symbol: string;
    value: string;
    unit?: string;
    meaning: string;
    dimensionSignature?: string;
  }>;
  resultUnit?: string;
  resultQuantity?: string;
  resultDimensionSignature?: string;
  assumptions?: string[];
}): TheoryBadgeV1["calculatorPayloads"][number] => ({
  id: args.id,
  expression: args.expression,
  displayLatex: args.displayLatex,
  preferredAction: "solve_with_steps",
  targetVariable: args.targetVariable,
  setupContext: {
    schema: HELIX_CALCULATOR_SETUP_CONTEXT_SCHEMA,
    expression: args.expression,
    display_latex: args.displayLatex,
    subgoal: args.subgoal,
    domain: "generic",
    equation: args.expression,
    variables: args.variables.map((variable) => ({
      symbol: variable.symbol,
      value: variable.value,
      unit: variable.unit ?? null,
      meaning: variable.meaning,
      dimension_signature: variable.dimensionSignature ?? null,
    })),
    unit_system: "custom",
    result_unit: args.resultUnit ?? null,
    result_quantity: args.resultQuantity ?? null,
    result_dimension_signature: args.resultDimensionSignature ?? null,
    assumptions: args.assumptions ?? [
      "StarSim Stage 1 reduced-order proxy.",
      "Diagnostic branch only; no claim promotion is allowed.",
    ],
    unit_options: [],
  },
});

const starsimBadge = (badge: Omit<TheoryBadgeV1, "claimBoundary">): TheoryBadgeV1 => ({
  ...badge,
  claimBoundary: STARSIM_BOUNDARY,
});

const commonSourceRefs = (id: string): TheoryBadgeV1["sourceRefs"] => [
  repoRef(STARSIM_REPO_PATH, id, "StarSim Stage 1 reduced-order microphysics runtime."),
  docRef(STARSIM_STAGE1_DOC, id, "Stage 1 scope, inputs, outputs, and caveats."),
];

export const STARSIM_THEORY_BADGES: TheoryBadgeV1[] = [
  starsimBadge({
    id: "starsim.observable.surface_temperature_proxy",
    title: "StarSim surface temperature proxy",
    plainMeaning: "Estimates stellar effective surface temperature from luminosity and radius.",
    whyItMatters: "It gives Helix Ask and the calculator a scalar entry point for StarSim observable prompts.",
    subjects: ["starsim", "stellar", "radiation", "observable", "temperature"],
    level: "derived_relation",
    status: "project_derived",
    simulationOwners: ["starsim"],
    equationFamilies: ["stellar_observable_proxy", "radiation_scaling"],
    tags: ["surface", "teff", "luminosity", "radius", "calculator_loadable"],
    equations: [
      {
        id: "teff_from_luminosity_radius",
        role: "calculator_demo",
        displayLatex: "T_{eff}=T_{sun}\\left(\\frac{L}{R^2}\\right)^{1/4}",
        computableExpression: "T_eff = T_sun*(L/(R^2))^(1/4)",
        operatorKind: "scalar_expression",
        inputSymbols: ["T_sun", "L", "R"],
        outputSymbols: ["T_eff"],
      },
    ],
    units: [
      { symbol: "T_eff", unit: "K", quantity: "temperature", dimensionSignature: "Theta" },
      { symbol: "T_sun", unit: "K", quantity: "temperature", dimensionSignature: "Theta" },
      { symbol: "L", unit: "Lsun", quantity: "luminosity", dimensionSignature: "M L^2 T^-3" },
      { symbol: "R", unit: "Rsun", quantity: "radius", dimensionSignature: "L" },
    ],
    assumptions: [
      "Surface observable proxy only.",
      "Luminosity and radius are solar-normalized in this reduced expression.",
      "Does not determine a full stellar interior profile.",
    ],
    calculatorPayloads: [
      calculatorPayload({
        id: "teff_from_luminosity_radius_payload",
        expression: "T_eff = T_sun*(L/(R^2))^(1/4)",
        displayLatex: "T_{eff}=T_{sun}\\left(\\frac{L}{R^2}\\right)^{1/4}",
        targetVariable: "T_eff",
        subgoal: "Estimate stellar effective temperature from luminosity and radius.",
        variables: [
          { symbol: "T_sun", value: "5772", unit: "K", meaning: "solar effective temperature", dimensionSignature: "Theta" },
          { symbol: "L", value: "1", unit: "Lsun", meaning: "stellar luminosity in solar units", dimensionSignature: "M L^2 T^-3" },
          { symbol: "R", value: "1", unit: "Rsun", meaning: "stellar radius in solar units", dimensionSignature: "L" },
        ],
        resultUnit: "K",
        resultQuantity: "temperature",
        resultDimensionSignature: "Theta",
      }),
    ],
    sourceRefs: commonSourceRefs("effectiveTemperatureFromSurface"),
    hintKeys: {
      subjects: ["starsim", "stellar", "temperature", "luminosity", "radius", "surface"],
      symbols: ["T_eff", "T_sun", "L", "R", "luminosity_Lsun", "radius_Rsun", "effectiveTemperature_K"],
      unitSignatures: ["Theta", "M L^2 T^-3", "L"],
      repoPaths: [STARSIM_REPO_PATH],
      equationFamilies: ["stellar_observable_proxy", "radiation_scaling"],
      simulationOwners: ["starsim"],
    },
  }),
  starsimBadge({
    id: "starsim.observable.surface_gravity",
    title: "StarSim surface gravity proxy",
    plainMeaning: "Relates stellar mass and radius to a surface-gravity estimate.",
    whyItMatters: "Surface gravity is a common observable bridge into StarSim classification context.",
    subjects: ["starsim", "stellar", "gravity", "observable"],
    level: "derived_relation",
    status: "project_derived",
    simulationOwners: ["starsim"],
    equationFamilies: ["stellar_observable_proxy", "newtonian_gravity"],
    tags: ["gravity", "mass", "radius", "calculator_loadable"],
    equations: [
      {
        id: "surface_gravity",
        role: "calculator_demo",
        displayLatex: "g=\\frac{GM}{R^2}",
        computableExpression: "g = G*M/(R^2)",
        operatorKind: "scalar_expression",
        inputSymbols: ["G", "M", "R"],
        outputSymbols: ["g"],
      },
    ],
    units: [
      { symbol: "g", unit: "m/s^2", quantity: "acceleration", dimensionSignature: "L T^-2" },
      { symbol: "M", unit: "Msun", quantity: "mass", dimensionSignature: "M" },
      { symbol: "R", unit: "Rsun", quantity: "radius", dimensionSignature: "L" },
    ],
    assumptions: ["Reduced scalar estimate.", "Requires consistent unit normalization before numeric interpretation."],
    calculatorPayloads: [
      calculatorPayload({
        id: "surface_gravity_payload",
        expression: "g = G*M/(R^2)",
        displayLatex: "g=\\frac{GM}{R^2}",
        targetVariable: "g",
        subgoal: "Estimate surface gravity from mass and radius.",
        variables: [
          { symbol: "G", value: "1", meaning: "gravitational constant in chosen normalized units", dimensionSignature: "L^3 M^-1 T^-2" },
          { symbol: "M", value: "1", unit: "Msun", meaning: "stellar mass", dimensionSignature: "M" },
          { symbol: "R", value: "1", unit: "Rsun", meaning: "stellar radius", dimensionSignature: "L" },
        ],
        resultUnit: "normalized acceleration",
        resultQuantity: "surface_gravity",
        resultDimensionSignature: "L T^-2",
      }),
    ],
    sourceRefs: commonSourceRefs("observables.logg_cgs"),
    hintKeys: {
      subjects: ["starsim", "stellar", "surface_gravity", "gravity", "mass", "radius"],
      symbols: ["g", "G", "M", "R", "mass_Msun", "radius_Rsun", "logg_cgs"],
      unitSignatures: ["L T^-2", "L^3 M^-1 T^-2", "M", "L"],
      repoPaths: [STARSIM_REPO_PATH],
      equationFamilies: ["stellar_observable_proxy", "newtonian_gravity"],
      simulationOwners: ["starsim"],
    },
  }),
  starsimBadge({
    id: "starsim.observable.mean_density",
    title: "StarSim mean density proxy",
    plainMeaning: "Estimates mean stellar density from mass and radius.",
    whyItMatters: "Mean density gives StarSim a simple scalar bridge from observables to structure proxies.",
    subjects: ["starsim", "stellar", "density", "observable"],
    level: "derived_relation",
    status: "project_derived",
    simulationOwners: ["starsim"],
    equationFamilies: ["stellar_observable_proxy", "density"],
    tags: ["density", "mass", "radius", "calculator_loadable"],
    equations: [
      {
        id: "mean_density",
        role: "calculator_demo",
        displayLatex: "\\rho_{mean}=\\frac{M}{(4/3)\\pi R^3}",
        computableExpression: "rho_mean = M/((4/3)*pi*R^3)",
        operatorKind: "scalar_expression",
        inputSymbols: ["M", "R"],
        outputSymbols: ["rho_mean"],
      },
    ],
    units: [
      { symbol: "rho_mean", unit: "kg/m^3", quantity: "density", dimensionSignature: "M L^-3" },
      { symbol: "M", unit: "Msun", quantity: "mass", dimensionSignature: "M" },
      { symbol: "R", unit: "Rsun", quantity: "radius", dimensionSignature: "L" },
    ],
    assumptions: ["Uniform-sphere proxy only.", "Does not substitute for a resolved stellar structure profile."],
    calculatorPayloads: [
      calculatorPayload({
        id: "mean_density_payload",
        expression: "rho_mean = M/((4/3)*pi*R^3)",
        displayLatex: "\\rho_{mean}=\\frac{M}{(4/3)\\pi R^3}",
        targetVariable: "rho_mean",
        subgoal: "Estimate mean stellar density from mass and radius.",
        variables: [
          { symbol: "M", value: "1", unit: "Msun", meaning: "stellar mass", dimensionSignature: "M" },
          { symbol: "R", value: "1", unit: "Rsun", meaning: "stellar radius", dimensionSignature: "L" },
        ],
        resultUnit: "Msun/Rsun^3",
        resultQuantity: "mean_density",
        resultDimensionSignature: "M L^-3",
      }),
    ],
    sourceRefs: commonSourceRefs("estimateCoreDensity"),
    hintKeys: {
      subjects: ["starsim", "stellar", "density", "mass", "radius"],
      symbols: ["rho_mean", "M", "R", "mass_Msun", "radius_Rsun"],
      unitSignatures: ["M L^-3", "M", "L"],
      repoPaths: [STARSIM_REPO_PATH],
      equationFamilies: ["stellar_observable_proxy", "density"],
      simulationOwners: ["starsim"],
    },
  }),
  starsimBadge({
    id: "starsim.structure.mass_continuity",
    title: "Stellar mass continuity reference",
    plainMeaning: "Names the one-dimensional stellar structure relation for enclosed mass.",
    whyItMatters: "It ties StarSim reduced-order density proxies back to a standard structure equation.",
    subjects: ["starsim", "stellar_structure", "density"],
    level: "law",
    status: "canonical_reference",
    simulationOwners: ["starsim"],
    equationFamilies: ["stellar_structure_equations"],
    tags: ["mass_continuity", "reference"],
    equations: [
      {
        id: "mass_continuity",
        role: "law",
        displayLatex: "\\frac{dm}{dr}=4\\pi r^2\\rho",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["r", "rho"],
        outputSymbols: ["dm_dr"],
      },
    ],
    units: [{ symbol: "dm/dr", quantity: "mass_gradient", dimensionSignature: "M L^-1" }],
    assumptions: ["Reference structure equation only.", "Stage 1 StarSim does not integrate this as a full stellar model."],
    calculatorPayloads: [],
    sourceRefs: [docRef(STARSIM_STAGE1_DOC, "stellar-structure-equations")],
    hintKeys: {
      subjects: ["starsim", "stellar_structure", "mass_continuity", "density"],
      symbols: ["dm_dr", "r", "rho"],
      unitSignatures: ["M L^-1", "M L^-3", "L"],
      repoPaths: [STARSIM_STAGE1_DOC],
      equationFamilies: ["stellar_structure_equations"],
      simulationOwners: ["starsim"],
    },
  }),
  starsimBadge({
    id: "starsim.structure.hydrostatic_balance",
    title: "Hydrostatic balance reference",
    plainMeaning: "Names the pressure-gradient balance between gravity and pressure support in stellar interiors.",
    whyItMatters: "It is the theory bridge between gravity roots and StarSim's reduced-order structure priors.",
    subjects: ["starsim", "stellar_structure", "gravity", "pressure"],
    level: "law",
    status: "canonical_reference",
    simulationOwners: ["starsim"],
    equationFamilies: ["stellar_structure_equations", "hydrostatic_balance"],
    tags: ["hydrostatic", "pressure", "reference"],
    equations: [
      {
        id: "hydrostatic_balance",
        role: "law",
        displayLatex: "\\frac{dP}{dr}=-\\frac{Gm(r)\\rho}{r^2}",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["G", "m_r", "rho", "r"],
        outputSymbols: ["dP_dr"],
      },
    ],
    units: [{ symbol: "dP/dr", quantity: "pressure_gradient", dimensionSignature: "M L^-2 T^-2" }],
    assumptions: ["Reference differential relation only.", "Stage 1 StarSim uses reduced-order proxies around this context."],
    calculatorPayloads: [],
    sourceRefs: [docRef(STARSIM_STAGE1_DOC, "stellar-structure-equations")],
    hintKeys: {
      subjects: ["starsim", "stellar_structure", "hydrostatic", "gravity", "pressure"],
      symbols: ["dP_dr", "G", "m_r", "rho", "r"],
      unitSignatures: ["M L^-2 T^-2", "L^3 M^-1 T^-2", "M L^-3"],
      repoPaths: [STARSIM_STAGE1_DOC],
      equationFamilies: ["stellar_structure_equations", "hydrostatic_balance"],
      simulationOwners: ["starsim"],
    },
  }),
  starsimBadge({
    id: "starsim.structure.luminosity_gradient",
    title: "Luminosity gradient reference",
    plainMeaning: "Names the stellar structure relation for luminosity generated inside radius r.",
    whyItMatters: "It connects nuclear-energy language to the runtime's fusion-zone summaries without claiming full integration.",
    subjects: ["starsim", "stellar_structure", "luminosity", "fusion"],
    level: "law",
    status: "canonical_reference",
    simulationOwners: ["starsim"],
    equationFamilies: ["stellar_structure_equations", "nuclear_luminosity"],
    tags: ["luminosity_gradient", "fusion", "reference"],
    equations: [
      {
        id: "luminosity_gradient",
        role: "law",
        displayLatex: "\\frac{dL}{dr}=4\\pi r^2\\rho\\epsilon_{nuc}",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["r", "rho", "epsilon_nuc"],
        outputSymbols: ["dL_dr"],
      },
    ],
    units: [{ symbol: "dL/dr", quantity: "luminosity_gradient", dimensionSignature: "M L T^-3" }],
    assumptions: ["Reference differential relation only.", "Stage 1 runtime reports a reduced fusion-zone summary."],
    calculatorPayloads: [],
    sourceRefs: [docRef(STARSIM_STAGE1_DOC, "stellar-structure-equations")],
    hintKeys: {
      subjects: ["starsim", "stellar_structure", "luminosity", "fusion"],
      symbols: ["dL_dr", "r", "rho", "epsilon_nuc"],
      unitSignatures: ["M L T^-3", "M L^-3"],
      repoPaths: [STARSIM_STAGE1_DOC],
      equationFamilies: ["stellar_structure_equations", "nuclear_luminosity"],
      simulationOwners: ["starsim"],
    },
  }),
  starsimBadge({
    id: "starsim.structure.core_temperature_proxy",
    title: "StarSim core temperature proxy",
    plainMeaning: "Scales a channel temperature by a compactness-like mass over radius factor.",
    whyItMatters: "It exposes the reduced-order structure idea around StarSim's core-temperature estimate.",
    subjects: ["starsim", "stellar_structure", "temperature", "fusion"],
    level: "model",
    status: "project_derived",
    simulationOwners: ["starsim"],
    equationFamilies: ["stellar_structure_proxy", "fusion_channel_prior"],
    tags: ["core_temperature", "compactness", "calculator_loadable"],
    equations: [
      {
        id: "core_temperature_proxy",
        role: "calculator_demo",
        displayLatex: "T_{core,proxy}=T_{channel}\\frac{M}{R}",
        computableExpression: "T_core_proxy = T_channel*(M/R)",
        operatorKind: "scalar_expression",
        inputSymbols: ["T_channel", "M", "R"],
        outputSymbols: ["T_core_proxy"],
      },
    ],
    units: [{ symbol: "T_core_proxy", unit: "K", quantity: "temperature", dimensionSignature: "Theta" }],
    assumptions: [
      "Reduced-order compactness scaling only.",
      "Does not replace resolved core-temperature modeling.",
      "Inactive and compact-object channels can intentionally skip this estimate.",
    ],
    calculatorPayloads: [
      calculatorPayload({
        id: "core_temperature_proxy_payload",
        expression: "T_core_proxy = T_channel*(M/R)",
        displayLatex: "T_{core,proxy}=T_{channel}\\frac{M}{R}",
        targetVariable: "T_core_proxy",
        subgoal: "Estimate a reduced-order StarSim core temperature proxy.",
        variables: [
          { symbol: "T_channel", value: "15000000", unit: "K", meaning: "channel baseline temperature", dimensionSignature: "Theta" },
          { symbol: "M", value: "1", unit: "Msun", meaning: "stellar mass", dimensionSignature: "M" },
          { symbol: "R", value: "1", unit: "Rsun", meaning: "stellar radius", dimensionSignature: "L" },
        ],
        resultUnit: "K",
        resultQuantity: "core_temperature_proxy",
        resultDimensionSignature: "Theta",
      }),
    ],
    sourceRefs: commonSourceRefs("estimateCoreTemperatureK"),
    hintKeys: {
      subjects: ["starsim", "stellar_structure", "core_temperature", "temperature", "fusion"],
      symbols: ["T_core_proxy", "T_channel", "M", "R", "estimatedCoreTemperature_K"],
      unitSignatures: ["Theta", "M", "L"],
      repoPaths: [STARSIM_REPO_PATH],
      equationFamilies: ["stellar_structure_proxy", "fusion_channel_prior"],
      simulationOwners: ["starsim"],
    },
  }),
  starsimBadge({
    id: "starsim.structure.core_density_proxy",
    title: "StarSim core density proxy",
    plainMeaning: "Scales a channel density by mass over radius cubed.",
    whyItMatters: "It turns StarSim's reduced-order density estimate into a calculator-visible scalar relation.",
    subjects: ["starsim", "stellar_structure", "density", "fusion"],
    level: "model",
    status: "project_derived",
    simulationOwners: ["starsim"],
    equationFamilies: ["stellar_structure_proxy", "fusion_channel_prior"],
    tags: ["core_density", "density", "calculator_loadable"],
    equations: [
      {
        id: "core_density_proxy",
        role: "calculator_demo",
        displayLatex: "\\rho_{core,proxy}=\\rho_{channel}\\frac{M}{R^3}",
        computableExpression: "rho_core_proxy = rho_channel*M/(R^3)",
        operatorKind: "scalar_expression",
        inputSymbols: ["rho_channel", "M", "R"],
        outputSymbols: ["rho_core_proxy"],
      },
    ],
    units: [{ symbol: "rho_core_proxy", unit: "g/cm^3", quantity: "density", dimensionSignature: "M L^-3" }],
    assumptions: [
      "Reduced-order density scaling only.",
      "Inactive and compact-object channels can intentionally skip this estimate.",
    ],
    calculatorPayloads: [
      calculatorPayload({
        id: "core_density_proxy_payload",
        expression: "rho_core_proxy = rho_channel*M/(R^3)",
        displayLatex: "\\rho_{core,proxy}=\\rho_{channel}\\frac{M}{R^3}",
        targetVariable: "rho_core_proxy",
        subgoal: "Estimate a reduced-order StarSim core density proxy.",
        variables: [
          { symbol: "rho_channel", value: "150", unit: "g/cm^3", meaning: "channel baseline density", dimensionSignature: "M L^-3" },
          { symbol: "M", value: "1", unit: "Msun", meaning: "stellar mass", dimensionSignature: "M" },
          { symbol: "R", value: "1", unit: "Rsun", meaning: "stellar radius", dimensionSignature: "L" },
        ],
        resultUnit: "g/cm^3",
        resultQuantity: "core_density_proxy",
        resultDimensionSignature: "M L^-3",
      }),
    ],
    sourceRefs: commonSourceRefs("estimateCoreDensity"),
    hintKeys: {
      subjects: ["starsim", "stellar_structure", "core_density", "density", "fusion"],
      symbols: ["rho_core_proxy", "rho_channel", "M", "R", "estimatedCoreDensity_g_cm3"],
      unitSignatures: ["M L^-3", "M", "L"],
      repoPaths: [STARSIM_REPO_PATH],
      equationFamilies: ["stellar_structure_proxy", "fusion_channel_prior"],
      simulationOwners: ["starsim"],
    },
  }),
  starsimBadge({
    id: "starsim.classifier.compactness_scale",
    title: "StarSim compactness scale",
    plainMeaning: "Computes the reduced mass-over-radius scale used around StarSim structure proxies.",
    whyItMatters: "It makes the classifier's surrounding structure context visible as scalar math.",
    subjects: ["starsim", "classifier", "stellar_structure", "compactness"],
    level: "simulation_specific",
    status: "diagnostic",
    simulationOwners: ["starsim"],
    equationFamilies: ["classifier_margin", "stellar_structure_proxy"],
    tags: ["compactness", "margin", "calculator_loadable"],
    equations: [
      {
        id: "compactness_scale",
        role: "calculator_demo",
        displayLatex: "compactness\\_scale=\\frac{M}{R}",
        computableExpression: "compactness_scale = M/R",
        operatorKind: "scalar_expression",
        inputSymbols: ["M", "R"],
        outputSymbols: ["compactness_scale"],
      },
    ],
    units: [{ symbol: "compactness_scale", quantity: "normalized compactness", dimensionSignature: "1" }],
    assumptions: [
      "Mass and radius are solar-normalized.",
      "Classifier explanation helper only; not a relativistic compactness calculation.",
    ],
    calculatorPayloads: [
      calculatorPayload({
        id: "compactness_scale_payload",
        expression: "compactness_scale = M/R",
        displayLatex: "compactness\\_scale=\\frac{M}{R}",
        targetVariable: "compactness_scale",
        subgoal: "Compute a reduced StarSim compactness scale.",
        variables: [
          { symbol: "M", value: "1", unit: "Msun", meaning: "stellar mass", dimensionSignature: "M" },
          { symbol: "R", value: "1", unit: "Rsun", meaning: "stellar radius", dimensionSignature: "L" },
        ],
        resultQuantity: "compactness_scale",
        resultDimensionSignature: "1",
      }),
    ],
    sourceRefs: commonSourceRefs("estimateCoreTemperatureK"),
    hintKeys: {
      subjects: ["starsim", "compactness", "classifier", "mass", "radius"],
      symbols: ["compactness_scale", "M", "R"],
      unitSignatures: ["1", "M", "L"],
      repoPaths: [STARSIM_REPO_PATH],
      equationFamilies: ["classifier_margin", "stellar_structure_proxy"],
      simulationOwners: ["starsim"],
    },
  }),
  starsimBadge({
    id: "starsim.classifier.brown_dwarf_mass_margin",
    title: "StarSim brown-dwarf mass margin",
    plainMeaning: "Shows distance from the reduced StarSim inactive-fusion mass threshold.",
    whyItMatters: "It helps Helix explain why a low-mass object routes away from ordinary stellar fusion.",
    subjects: ["starsim", "classifier", "brown_dwarf", "fusion"],
    level: "simulation_specific",
    status: "diagnostic",
    simulationOwners: ["starsim"],
    equationFamilies: ["classifier_margin", "fusion_channel_prior"],
    tags: ["brown_dwarf", "mass_threshold", "calculator_loadable"],
    equations: [
      {
        id: "brown_dwarf_margin",
        role: "calculator_demo",
        displayLatex: "brown\\_dwarf\\_margin=M-0.075",
        computableExpression: "brown_dwarf_margin = M - 0.075",
        operatorKind: "scalar_expression",
        inputSymbols: ["M"],
        outputSymbols: ["brown_dwarf_margin"],
      },
    ],
    units: [{ symbol: "brown_dwarf_margin", unit: "Msun", quantity: "mass margin", dimensionSignature: "M" }],
    assumptions: ["Mass is in solar masses.", "Margin is a classifier-explanation helper, not a reaction-network solve."],
    calculatorPayloads: [
      calculatorPayload({
        id: "brown_dwarf_mass_margin_payload",
        expression: "brown_dwarf_margin = M - 0.075",
        displayLatex: "brown\\_dwarf\\_margin=M-0.075",
        targetVariable: "brown_dwarf_margin",
        subgoal: "Compute margin from the reduced brown-dwarf inactive-fusion threshold.",
        variables: [{ symbol: "M", value: "1", unit: "Msun", meaning: "stellar mass", dimensionSignature: "M" }],
        resultUnit: "Msun",
        resultQuantity: "mass_margin",
        resultDimensionSignature: "M",
      }),
    ],
    sourceRefs: commonSourceRefs("inferDominantChannel"),
    hintKeys: {
      subjects: ["starsim", "brown_dwarf", "mass_threshold", "classifier"],
      symbols: ["brown_dwarf_margin", "M", "mass_Msun"],
      unitSignatures: ["M"],
      repoPaths: [STARSIM_REPO_PATH],
      equationFamilies: ["classifier_margin", "fusion_channel_prior"],
      simulationOwners: ["starsim"],
    },
  }),
  starsimBadge({
    id: "starsim.classifier.cno_mass_margin",
    title: "StarSim CNO mass margin",
    plainMeaning: "Shows distance from the reduced mass threshold used around CNO-cycle prior routing.",
    whyItMatters: "It makes high-mass classifier context visible before the runtime receipt.",
    subjects: ["starsim", "classifier", "cno", "fusion"],
    level: "simulation_specific",
    status: "diagnostic",
    simulationOwners: ["starsim"],
    equationFamilies: ["classifier_margin", "fusion_channel_prior"],
    tags: ["cno", "mass_threshold", "calculator_loadable"],
    equations: [
      {
        id: "cno_mass_margin",
        role: "calculator_demo",
        displayLatex: "cno\\_mass\\_margin=M-1.3",
        computableExpression: "cno_mass_margin = M - 1.3",
        operatorKind: "scalar_expression",
        inputSymbols: ["M"],
        outputSymbols: ["cno_mass_margin"],
      },
    ],
    units: [{ symbol: "cno_mass_margin", unit: "Msun", quantity: "mass margin", dimensionSignature: "M" }],
    assumptions: ["Mass is in solar masses.", "Margin is a classifier-explanation helper, not a reaction-network solve."],
    calculatorPayloads: [
      calculatorPayload({
        id: "cno_mass_margin_payload",
        expression: "cno_mass_margin = M - 1.3",
        displayLatex: "cno\\_mass\\_margin=M-1.3",
        targetVariable: "cno_mass_margin",
        subgoal: "Compute margin from the reduced CNO-prior mass threshold.",
        variables: [{ symbol: "M", value: "1", unit: "Msun", meaning: "stellar mass", dimensionSignature: "M" }],
        resultUnit: "Msun",
        resultQuantity: "mass_margin",
        resultDimensionSignature: "M",
      }),
    ],
    sourceRefs: commonSourceRefs("inferDominantChannel"),
    hintKeys: {
      subjects: ["starsim", "cno", "mass_threshold", "classifier"],
      symbols: ["cno_mass_margin", "M", "mass_Msun"],
      unitSignatures: ["M"],
      repoPaths: [STARSIM_REPO_PATH],
      equationFamilies: ["classifier_margin", "fusion_channel_prior"],
      simulationOwners: ["starsim"],
    },
  }),
  starsimBadge({
    id: "starsim.classifier.cno_temperature_margin",
    title: "StarSim CNO temperature margin",
    plainMeaning: "Shows distance from the reduced effective-temperature threshold used around CNO-cycle prior routing.",
    whyItMatters: "It links the surface-temperature proxy to the runtime fusion-channel receipt.",
    subjects: ["starsim", "classifier", "cno", "temperature"],
    level: "simulation_specific",
    status: "diagnostic",
    simulationOwners: ["starsim"],
    equationFamilies: ["classifier_margin", "fusion_channel_prior"],
    tags: ["cno", "temperature_threshold", "calculator_loadable"],
    equations: [
      {
        id: "cno_temperature_margin",
        role: "calculator_demo",
        displayLatex: "cno\\_temperature\\_margin=T_{eff}-6500",
        computableExpression: "cno_temperature_margin = T_eff - 6500",
        operatorKind: "scalar_expression",
        inputSymbols: ["T_eff"],
        outputSymbols: ["cno_temperature_margin"],
      },
    ],
    units: [{ symbol: "cno_temperature_margin", unit: "K", quantity: "temperature margin", dimensionSignature: "Theta" }],
    assumptions: [
      "Temperature is in kelvin.",
      "Margin is a classifier-explanation helper; spectral type and object class remain runtime inputs.",
    ],
    calculatorPayloads: [
      calculatorPayload({
        id: "cno_temperature_margin_payload",
        expression: "cno_temperature_margin = T_eff - 6500",
        displayLatex: "cno\\_temperature\\_margin=T_{eff}-6500",
        targetVariable: "cno_temperature_margin",
        subgoal: "Compute margin from the reduced CNO-prior effective-temperature threshold.",
        variables: [{ symbol: "T_eff", value: "5772", unit: "K", meaning: "effective surface temperature", dimensionSignature: "Theta" }],
        resultUnit: "K",
        resultQuantity: "temperature_margin",
        resultDimensionSignature: "Theta",
      }),
    ],
    sourceRefs: commonSourceRefs("inferDominantChannel"),
    hintKeys: {
      subjects: ["starsim", "cno", "temperature_threshold", "classifier"],
      symbols: ["cno_temperature_margin", "T_eff", "effectiveTemperature_K"],
      unitSignatures: ["Theta"],
      repoPaths: [STARSIM_REPO_PATH],
      equationFamilies: ["classifier_margin", "fusion_channel_prior"],
      simulationOwners: ["starsim"],
    },
  }),
  starsimBadge({
    id: "starsim.fusion.pp_chain_prior",
    title: "StarSim pp-chain prior",
    plainMeaning: "Represents StarSim's runtime prior for lower-mass main-sequence fusion classification.",
    whyItMatters: "It lets Helix locate Sun-like stellar prompts on the runtime classification branch.",
    subjects: ["starsim", "fusion", "stellar", "main_sequence"],
    level: "simulation_specific",
    status: "diagnostic",
    simulationOwners: ["starsim"],
    equationFamilies: ["fusion_channel_prior"],
    tags: ["pp_chain", "classifier", "runtime"],
    equations: [
      {
        id: "pp_chain_runtime_gate",
        role: "gate",
        displayLatex: "channel\\rightarrow pp\\_chain",
        computableExpression: null,
        operatorKind: "gate_status",
        inputSymbols: ["objectClass", "mass_Msun", "effectiveTemperature_K", "spectralType"],
        outputSymbols: ["dominantFusionChannel"],
      },
    ],
    units: [{ symbol: "mass_Msun", unit: "Msun", quantity: "mass", dimensionSignature: "M" }],
    assumptions: ["Runtime classifier badge.", "Calculator payloads around this badge are helper scalars, not the classifier itself."],
    calculatorPayloads: [],
    sourceRefs: [
      ...commonSourceRefs("inferDominantChannel"),
      testRef("shared/__tests__/starsim-fusion-microphysics.test.ts", "G/K/M main-sequence pp-chain cases"),
    ],
    hintKeys: {
      subjects: ["starsim", "fusion", "pp_chain", "main_sequence", "sun_like"],
      symbols: ["dominantFusionChannel", "pp_chain", "mass_Msun", "spectralType", "effectiveTemperature_K"],
      unitSignatures: ["M", "Theta"],
      repoPaths: [STARSIM_REPO_PATH, "shared/__tests__/starsim-fusion-microphysics.test.ts"],
      equationFamilies: ["fusion_channel_prior"],
      simulationOwners: ["starsim"],
    },
  }),
  starsimBadge({
    id: "starsim.fusion.cno_cycle_prior",
    title: "StarSim CNO-cycle prior",
    plainMeaning: "Represents StarSim's hotter or higher-mass main-sequence fusion-channel prior.",
    whyItMatters: "It distinguishes CNO-like runtime classification from the pp-chain branch.",
    subjects: ["starsim", "fusion", "stellar", "main_sequence"],
    level: "simulation_specific",
    status: "diagnostic",
    simulationOwners: ["starsim"],
    equationFamilies: ["fusion_channel_prior"],
    tags: ["cno_cycle", "classifier", "runtime"],
    equations: [
      {
        id: "cno_cycle_runtime_gate",
        role: "gate",
        displayLatex: "channel\\rightarrow cno\\_cycle",
        computableExpression: null,
        operatorKind: "gate_status",
        inputSymbols: ["objectClass", "mass_Msun", "effectiveTemperature_K", "spectralType"],
        outputSymbols: ["dominantFusionChannel"],
      },
    ],
    units: [{ symbol: "effectiveTemperature_K", unit: "K", quantity: "temperature", dimensionSignature: "Theta" }],
    assumptions: ["Runtime classifier badge.", "CNO selection remains a reduced-order prior in this branch."],
    calculatorPayloads: [],
    sourceRefs: [
      ...commonSourceRefs("inferDominantChannel"),
      testRef("shared/__tests__/starsim-fusion-microphysics.test.ts", "hotter main-sequence CNO cases"),
    ],
    hintKeys: {
      subjects: ["starsim", "fusion", "cno_cycle", "hot_star", "main_sequence"],
      symbols: ["dominantFusionChannel", "cno_cycle", "mass_Msun", "spectralType", "effectiveTemperature_K"],
      unitSignatures: ["M", "Theta"],
      repoPaths: [STARSIM_REPO_PATH, "shared/__tests__/starsim-fusion-microphysics.test.ts"],
      equationFamilies: ["fusion_channel_prior"],
      simulationOwners: ["starsim"],
    },
  }),
  starsimBadge({
    id: "starsim.fusion.compact_object_not_fusing",
    title: "Compact object not-fusing gate",
    plainMeaning: "Represents StarSim's compact-object branch where white dwarfs and neutron stars are not pp-chain fusion cases.",
    whyItMatters: "It gives Helix a clear locator target for compact-object prompts that should not be routed to ordinary stellar fusion.",
    subjects: ["starsim", "fusion", "compact_object", "guardrail"],
    level: "diagnostic_gate",
    status: "diagnostic",
    simulationOwners: ["starsim"],
    equationFamilies: ["fusion_channel_prior", "compact_object_context"],
    tags: ["neutron_star", "white_dwarf", "compact_object", "runtime"],
    equations: [
      {
        id: "compact_object_not_fusing_gate",
        role: "gate",
        displayLatex: "compact\\_object\\rightarrow not\\_fusing",
        computableExpression: null,
        operatorKind: "gate_status",
        inputSymbols: ["objectClass"],
        outputSymbols: ["dominantFusionChannel", "fusionActive"],
      },
    ],
    units: [],
    assumptions: [
      "Compact objects are routed to compact-object context rather than ordinary pp-chain fusion.",
      "This badge is a runtime guardrail, not a scalar calculator solve.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      ...commonSourceRefs("inferDominantChannel"),
      testRef("shared/__tests__/starsim-fusion-microphysics.test.ts", "neutron star compact-object guardrail"),
    ],
    hintKeys: {
      subjects: ["starsim", "compact_object", "neutron_star", "white_dwarf", "not_fusing"],
      symbols: ["objectClass", "dominantFusionChannel", "fusionActive", "compact_object_not_fusing"],
      unitSignatures: [],
      repoPaths: [STARSIM_REPO_PATH, "shared/__tests__/starsim-fusion-microphysics.test.ts"],
      equationFamilies: ["fusion_channel_prior", "compact_object_context"],
      simulationOwners: ["starsim"],
    },
  }),
  starsimBadge({
    id: "starsim.fusion_zone.active_volume_fraction",
    title: "StarSim active volume fraction",
    plainMeaning: "Approximates the active fusion-zone volume fraction from the r90 radius fraction.",
    whyItMatters: "It makes one StarSim fusion-zone output calculator-loadable while keeping the runtime context visible.",
    subjects: ["starsim", "fusion_zone", "stellar", "volume"],
    level: "simulation_specific",
    status: "project_derived",
    simulationOwners: ["starsim"],
    equationFamilies: ["fusion_zone_proxy"],
    tags: ["r90", "volume_fraction", "calculator_loadable"],
    equations: [
      {
        id: "active_volume_fraction",
        role: "calculator_demo",
        displayLatex: "activeVolumeFraction=r90_{Rstar}^{3}",
        computableExpression: "activeVolumeFraction = r90_Rstar^3",
        operatorKind: "scalar_expression",
        inputSymbols: ["r90_Rstar"],
        outputSymbols: ["activeVolumeFraction"],
      },
    ],
    units: [{ symbol: "activeVolumeFraction", quantity: "volume_fraction", dimensionSignature: "1" }],
    assumptions: ["Spherical fraction proxy only.", "Fusion-zone shape and shell structure still come from runtime context."],
    calculatorPayloads: [
      calculatorPayload({
        id: "active_volume_fraction_payload",
        expression: "activeVolumeFraction = r90_Rstar^3",
        displayLatex: "activeVolumeFraction=r90_{Rstar}^{3}",
        targetVariable: "activeVolumeFraction",
        subgoal: "Compute a StarSim active fusion-zone volume fraction from r90.",
        variables: [
          { symbol: "r90_Rstar", value: "0.25", meaning: "radius enclosing most active fusion output as a stellar-radius fraction", dimensionSignature: "1" },
        ],
        resultQuantity: "volume_fraction",
        resultDimensionSignature: "1",
      }),
    ],
    sourceRefs: commonSourceRefs("fusionZoneFor"),
    hintKeys: {
      subjects: ["starsim", "fusion_zone", "active_volume", "r90", "stellar"],
      symbols: ["activeVolumeFraction", "r90_Rstar", "r10_Rstar", "r50_Rstar"],
      unitSignatures: ["1"],
      repoPaths: [STARSIM_REPO_PATH],
      equationFamilies: ["fusion_zone_proxy"],
      simulationOwners: ["starsim"],
    },
  }),
  starsimBadge({
    id: "starsim.restoration.deep_mixing_mass_flux",
    title: "Solar deep-mixing mass flux",
    plainMeaning: "Relates a requested deep-mixing strength to the hydrogen-burning mass-flow scale.",
    whyItMatters: "It gives the calculator a first scalar entry point for the solar-restoration planning branch.",
    subjects: ["starsim", "solar_restoration", "deep_mixing", "tachocline", "mass_flux"],
    level: "model",
    status: "diagnostic",
    simulationOwners: ["starsim"],
    equationFamilies: ["solar_restoration_deep_mixing", "mass_flux_proxy"],
    tags: ["solar_restoration", "deep_mixing", "mass_flux", "calculator_loadable", "planning_forecast"],
    equations: [
      {
        id: "deep_mixing_mass_flux_fraction",
        role: "calculator_demo",
        displayLatex: "\\dot{M}_{mix}=\\epsilon\\dot{M}_{burn,sun}",
        computableExpression: "Mdot_mix = epsilon*Mdot_burn_sun",
        operatorKind: "scalar_expression",
        inputSymbols: ["epsilon", "Mdot_burn_sun"],
        outputSymbols: ["Mdot_mix"],
      },
      {
        id: "tachocline_flux_closure",
        role: "calculator_demo",
        displayLatex: "\\dot{M}_{mix}=4\\pi r_{tach}^{2}\\rho_{tach}f_{area}v_r",
        computableExpression: "Mdot_mix = 4*pi*r_tach^2*rho_tach*f_area*v_r",
        operatorKind: "scalar_expression",
        inputSymbols: ["r_tach", "rho_tach", "f_area", "v_r"],
        outputSymbols: ["Mdot_mix"],
      },
    ],
    units: [
      { symbol: "epsilon", quantity: "mixing_strength", dimensionSignature: "1" },
      { symbol: "Mdot_burn_sun", unit: "kg/s", quantity: "mass_flow_rate", dimensionSignature: "M T^-1" },
      { symbol: "Mdot_mix", unit: "kg/s", quantity: "mass_flow_rate", dimensionSignature: "M T^-1" },
      { symbol: "r_tach", unit: "m", quantity: "radius", dimensionSignature: "L" },
      { symbol: "rho_tach", unit: "kg/m^3", quantity: "density", dimensionSignature: "M L^-3" },
      { symbol: "v_r", unit: "m/s", quantity: "speed", dimensionSignature: "L T^-1" },
    ],
    assumptions: [
      "Reduced-order planning row only.",
      "Mdot_burn_sun is the solar hydrogen-burning mass-flow scale used by the deep-mixing plan.",
      "The row represents ordinary envelope-hydrogen transport, not hydrogen-3 fuel certification.",
      "It does not establish feasible stellar intervention.",
    ],
    calculatorPayloads: [
      calculatorPayload({
        id: "deep_mixing_mass_flux_payload",
        expression: "Mdot_mix = epsilon*Mdot_burn_sun",
        displayLatex: "\\dot{M}_{mix}=\\epsilon\\dot{M}_{burn,sun}",
        targetVariable: "Mdot_mix",
        subgoal: "Compute the reduced deep-mixing mass flux from the requested mixing strength.",
        variables: [
          { symbol: "epsilon", value: "0.01", meaning: "deep-mixing strength", dimensionSignature: "1" },
          { symbol: "Mdot_burn_sun", value: "6.0e11", unit: "kg/s", meaning: "solar hydrogen-burning mass-flow scale", dimensionSignature: "M T^-1" },
        ],
        resultUnit: "kg/s",
        resultQuantity: "mass_flow_rate",
        resultDimensionSignature: "M T^-1",
        assumptions: [
          "Planning/forecast row only.",
          "Uses the Save-the-Sun deep-mixing preset scale.",
          "Does not imply feasible solar intervention.",
        ],
      }),
      calculatorPayload({
        id: "tachocline_flux_closure_payload",
        expression: "Mdot_mix = 4*pi*r_tach^2*rho_tach*f_area*v_r",
        displayLatex: "\\dot{M}_{mix}=4\\pi r_{tach}^{2}\\rho_{tach}f_{area}v_r",
        targetVariable: "Mdot_mix",
        subgoal: "Check the tachocline area-density-flow closure for a proposed radial downflow.",
        variables: [
          { symbol: "r_tach", value: "4.8699e8", unit: "m", meaning: "tachocline radius near 0.70 solar radii", dimensionSignature: "L" },
          { symbol: "rho_tach", value: "200", unit: "kg/m^3", meaning: "representative tachocline density", dimensionSignature: "M L^-3" },
          { symbol: "f_area", value: "0.1", meaning: "engaged actuator-belt area fraction", dimensionSignature: "1" },
          { symbol: "v_r", value: "1.0e-10", unit: "m/s", meaning: "radial downflow speed", dimensionSignature: "L T^-1" },
        ],
        resultUnit: "kg/s",
        resultQuantity: "mass_flow_rate",
        resultDimensionSignature: "M T^-1",
        assumptions: [
          "Spherical tachocline belt proxy.",
          "Representative density is held constant.",
          "Planning/forecast row only.",
        ],
      }),
    ],
    sourceRefs: [
      repoRef(DEEP_MIXING_PHYSICS_REPO_PATH, "dotMmixFromVr", "Tachocline mass-flux helper."),
      repoRef(DEEP_MIXING_PRESET_REPO_PATH, "DEEP_MIXING_TARGETS", "Target epsilon presets."),
      docRef(DEEP_MIXING_PLAN_DOC, "deep-mixing-plan", "Save-the-Sun reduced-order planning note."),
      docRef(DEEP_MIXING_KNOWLEDGE_DOC, "deep-mixing", "Knowledge graph anchor for the deep-mixing branch."),
    ],
    hintKeys: {
      subjects: ["starsim", "solar_restoration", "deep_mixing", "tachocline", "mass_flux"],
      symbols: ["Mdot_mix", "epsilon", "Mdot_burn_sun", "r_tach", "rho_tach", "f_area", "v_r"],
      unitSignatures: ["M T^-1", "L", "M L^-3", "L T^-1", "1"],
      repoPaths: [DEEP_MIXING_PHYSICS_REPO_PATH, DEEP_MIXING_PRESET_REPO_PATH, DEEP_MIXING_PLAN_DOC],
      equationFamilies: ["solar_restoration_deep_mixing", "mass_flux_proxy"],
      simulationOwners: ["starsim"],
    },
  }),
  starsimBadge({
    id: "starsim.restoration.tachocline_downflow_setpoint",
    title: "Tachocline downflow setpoint",
    plainMeaning: "Solves the deep-mixing mass-flux closure for the radial downflow speed.",
    whyItMatters: "It turns the restoration preset into a concrete scalar that can be compared across calculator and runtime receipts.",
    subjects: ["starsim", "solar_restoration", "tachocline", "downflow", "setpoint"],
    level: "derived_relation",
    status: "diagnostic",
    simulationOwners: ["starsim"],
    equationFamilies: ["solar_restoration_deep_mixing", "tachocline_transport"],
    tags: ["deep_mixing", "tachocline", "downflow", "calculator_loadable", "planning_forecast"],
    equations: [
      {
        id: "tachocline_downflow_setpoint",
        role: "calculator_demo",
        displayLatex: "v_r=\\frac{\\epsilon\\dot{M}_{burn,sun}}{4\\pi r_{tach}^{2}\\rho_{tach}f_{area}}",
        computableExpression: "v_r = epsilon*Mdot_burn_sun/(4*pi*r_tach^2*rho_tach*f_area)",
        operatorKind: "scalar_expression",
        inputSymbols: ["epsilon", "Mdot_burn_sun", "r_tach", "rho_tach", "f_area"],
        outputSymbols: ["v_r"],
      },
    ],
    units: [
      { symbol: "v_r", unit: "m/s", quantity: "speed", dimensionSignature: "L T^-1" },
      { symbol: "epsilon", quantity: "mixing_strength", dimensionSignature: "1" },
      { symbol: "Mdot_burn_sun", unit: "kg/s", quantity: "mass_flow_rate", dimensionSignature: "M T^-1" },
      { symbol: "r_tach", unit: "m", quantity: "radius", dimensionSignature: "L" },
      { symbol: "rho_tach", unit: "kg/m^3", quantity: "density", dimensionSignature: "M L^-3" },
    ],
    assumptions: [
      "Spherical tachocline area proxy.",
      "Area fraction is clamped by the source helper before operational use.",
      "The downflow setpoint is a reduced-order planning scalar, not an actuator feasibility claim.",
    ],
    calculatorPayloads: [
      calculatorPayload({
        id: "tachocline_downflow_setpoint_payload",
        expression: "v_r = epsilon*Mdot_burn_sun/(4*pi*r_tach^2*rho_tach*f_area)",
        displayLatex: "v_r=\\frac{\\epsilon\\dot{M}_{burn,sun}}{4\\pi r_{tach}^{2}\\rho_{tach}f_{area}}",
        targetVariable: "v_r",
        subgoal: "Solve for the radial downflow setpoint implied by a deep-mixing preset.",
        variables: [
          { symbol: "epsilon", value: "0.01", meaning: "deep-mixing strength", dimensionSignature: "1" },
          { symbol: "Mdot_burn_sun", value: "6.0e11", unit: "kg/s", meaning: "solar hydrogen-burning mass-flow scale", dimensionSignature: "M T^-1" },
          { symbol: "r_tach", value: "4.8699e8", unit: "m", meaning: "tachocline radius near 0.70 solar radii", dimensionSignature: "L" },
          { symbol: "rho_tach", value: "200", unit: "kg/m^3", meaning: "representative tachocline density", dimensionSignature: "M L^-3" },
          { symbol: "f_area", value: "0.1", meaning: "engaged actuator-belt area fraction", dimensionSignature: "1" },
        ],
        resultUnit: "m/s",
        resultQuantity: "radial_speed",
        resultDimensionSignature: "L T^-1",
        assumptions: [
          "Uses the deep-mixing default area fraction and representative tachocline density.",
          "Planning/forecast row only.",
        ],
      }),
    ],
    sourceRefs: [
      repoRef(DEEP_MIXING_PHYSICS_REPO_PATH, "vrSetpoint", "Downflow setpoint helper."),
      repoRef(DEEP_MIXING_PRESET_REPO_PATH, "vrSetpointForPreset", "Preset-to-setpoint bridge."),
      docRef(DEEP_MIXING_PLAN_DOC, "tachocline-downflow", "Order-of-magnitude tachocline transport estimate."),
    ],
    hintKeys: {
      subjects: ["starsim", "solar_restoration", "tachocline", "downflow", "setpoint"],
      symbols: ["v_r", "epsilon", "Mdot_burn_sun", "r_tach", "rho_tach", "f_area"],
      unitSignatures: ["L T^-1", "M T^-1", "L", "M L^-3", "1"],
      repoPaths: [DEEP_MIXING_PHYSICS_REPO_PATH, DEEP_MIXING_PRESET_REPO_PATH, DEEP_MIXING_PLAN_DOC],
      equationFamilies: ["solar_restoration_deep_mixing", "tachocline_transport"],
      simulationOwners: ["starsim"],
    },
  }),
  starsimBadge({
    id: "starsim.restoration.core_hydrogen_balance",
    title: "Core hydrogen balance proxy",
    plainMeaning: "Tracks a one-zone core hydrogen fraction under burning and imported envelope hydrogen.",
    whyItMatters: "It is the reduced-order composition equation that connects deep mixing to red-giant-delay forecasts.",
    subjects: ["starsim", "solar_restoration", "hydrogen_burning", "composition", "red_giant"],
    level: "model",
    status: "diagnostic",
    simulationOwners: ["starsim"],
    equationFamilies: ["solar_restoration_deep_mixing", "composition_balance", "hydrogen_burning"],
    tags: ["core_hydrogen", "red_giant", "calculator_loadable", "planning_forecast"],
    equations: [
      {
        id: "hydrogen_burning_mass_rate",
        role: "calculator_demo",
        displayLatex: "\\dot{M}_{burn}=\\frac{L_{sun}}{Q_H}",
        computableExpression: "Mdot_burn = L_sun_W/Q_H",
        operatorKind: "scalar_expression",
        inputSymbols: ["L_sun_W", "Q_H"],
        outputSymbols: ["Mdot_burn"],
      },
      {
        id: "core_hydrogen_fraction_balance",
        role: "calculator_demo",
        displayLatex: "\\frac{dX_c}{dt}=\\frac{\\dot{M}_{mix}(X_e-X_c)-\\dot{M}_{burn}}{M_c}",
        computableExpression: "dXc_dt = (Mdot_mix*(X_e - X_c) - Mdot_burn)/M_c",
        operatorKind: "scalar_expression",
        inputSymbols: ["Mdot_mix", "X_e", "X_c", "Mdot_burn", "M_c"],
        outputSymbols: ["dXc_dt"],
      },
    ],
    units: [
      { symbol: "L_sun_W", unit: "W", quantity: "luminosity", dimensionSignature: "M L^2 T^-3" },
      { symbol: "Q_H", unit: "J/kg", quantity: "specific_energy", dimensionSignature: "L^2 T^-2" },
      { symbol: "Mdot_burn", unit: "kg/s", quantity: "mass_flow_rate", dimensionSignature: "M T^-1" },
      { symbol: "M_c", unit: "kg", quantity: "mass", dimensionSignature: "M" },
      { symbol: "dXc_dt", unit: "1/s", quantity: "fraction_rate", dimensionSignature: "T^-1" },
    ],
    assumptions: [
      "One-zone composition balance only.",
      "Does not resolve stellar transport, nuclear reaction networks, or shell burning.",
      "Envelope hydrogen fraction and core mass are scenario inputs.",
      "Planning/forecast row only.",
    ],
    calculatorPayloads: [
      calculatorPayload({
        id: "hydrogen_burning_mass_rate_payload",
        expression: "Mdot_burn = L_sun_W/Q_H",
        displayLatex: "\\dot{M}_{burn}=\\frac{L_{sun}}{Q_H}",
        targetVariable: "Mdot_burn",
        subgoal: "Estimate the hydrogen-burning mass-flow scale from luminosity and fusion specific energy.",
        variables: [
          { symbol: "L_sun_W", value: "3.828e26", unit: "W", meaning: "solar luminosity", dimensionSignature: "M L^2 T^-3" },
          { symbol: "Q_H", value: "6.3e14", unit: "J/kg", meaning: "hydrogen-to-helium fusion specific energy scale", dimensionSignature: "L^2 T^-2" },
        ],
        resultUnit: "kg/s",
        resultQuantity: "mass_flow_rate",
        resultDimensionSignature: "M T^-1",
      }),
      calculatorPayload({
        id: "core_hydrogen_balance_payload",
        expression: "dXc_dt = (Mdot_mix*(X_e - X_c) - Mdot_burn)/M_c",
        displayLatex: "\\frac{dX_c}{dt}=\\frac{\\dot{M}_{mix}(X_e-X_c)-\\dot{M}_{burn}}{M_c}",
        targetVariable: "dXc_dt",
        subgoal: "Compute the one-zone core hydrogen fraction drift for a deep-mixing scenario.",
        variables: [
          { symbol: "Mdot_mix", value: "6.0e9", unit: "kg/s", meaning: "deep-mixing mass flux", dimensionSignature: "M T^-1" },
          { symbol: "X_e", value: "0.70", meaning: "envelope hydrogen mass fraction", dimensionSignature: "1" },
          { symbol: "X_c", value: "0.34", meaning: "core hydrogen mass fraction", dimensionSignature: "1" },
          { symbol: "Mdot_burn", value: "6.0e11", unit: "kg/s", meaning: "hydrogen-burning mass-flow scale", dimensionSignature: "M T^-1" },
          { symbol: "M_c", value: "3.5e29", unit: "kg", meaning: "reduced one-zone core mass", dimensionSignature: "M" },
        ],
        resultUnit: "1/s",
        resultQuantity: "fraction_rate",
        resultDimensionSignature: "T^-1",
      }),
    ],
    sourceRefs: [
      repoRef("client/src/components/deepmix/DeepMixSweetSpot.tsx", "simulate", "One-zone composition drift used by the planning panel."),
      repoRef("client/src/components/deepmix/DeepMixGlobePanel.tsx", "simulate", "Globe panel red-giant suppression proxy."),
      docRef(DEEP_MIXING_PLAN_DOC, "core-hydrogen-balance", "Planning note for moving envelope hydrogen toward core access."),
    ],
    hintKeys: {
      subjects: ["starsim", "solar_restoration", "core_hydrogen", "hydrogen_burning", "red_giant"],
      symbols: ["dXc_dt", "X_c", "X_e", "Mdot_mix", "Mdot_burn", "M_c", "L_sun_W", "Q_H"],
      unitSignatures: ["T^-1", "M T^-1", "M", "M L^2 T^-3", "L^2 T^-2", "1"],
      repoPaths: ["client/src/components/deepmix/DeepMixSweetSpot.tsx", "client/src/components/deepmix/DeepMixGlobePanel.tsx", DEEP_MIXING_PLAN_DOC],
      equationFamilies: ["solar_restoration_deep_mixing", "composition_balance", "hydrogen_burning"],
      simulationOwners: ["starsim"],
    },
  }),
  starsimBadge({
    id: "starsim.restoration.lifetime_extension_proxy",
    title: "Solar lifetime extension proxy",
    plainMeaning: "Estimates a planning-only lifetime gain from accessible envelope hydrogen and the solar burn-rate scale.",
    whyItMatters: "It gives the theory panel a calculator-aligned way to represent the +10 Myr, +50 Myr, and +0.6 Gyr presets.",
    subjects: ["starsim", "solar_restoration", "lifetime", "fuel_budget", "red_giant"],
    level: "model",
    status: "diagnostic",
    simulationOwners: ["starsim"],
    equationFamilies: ["solar_restoration_deep_mixing", "fuel_budget_proxy"],
    tags: ["solar_restoration", "lifetime_extension", "calculator_loadable", "planning_forecast"],
    equations: [
      {
        id: "lifetime_extension_fuel_budget",
        role: "calculator_demo",
        displayLatex: "\\Delta t_{Myr}\\approx\\frac{\\alpha M_{env,H}}{\\dot{M}_{burn,sun}(31557600)(10^6)}",
        computableExpression: "Delta_t_Myr = alpha*M_env_H/(Mdot_burn_sun*31557600*1e6)",
        operatorKind: "scalar_expression",
        inputSymbols: ["alpha", "M_env_H", "Mdot_burn_sun"],
        outputSymbols: ["Delta_t_Myr"],
      },
    ],
    units: [
      { symbol: "Delta_t_Myr", unit: "Myr", quantity: "time", dimensionSignature: "T" },
      { symbol: "alpha", quantity: "accessible_fraction", dimensionSignature: "1" },
      { symbol: "M_env_H", unit: "kg", quantity: "mass", dimensionSignature: "M" },
      { symbol: "Mdot_burn_sun", unit: "kg/s", quantity: "mass_flow_rate", dimensionSignature: "M T^-1" },
    ],
    assumptions: [
      "Fuel-budget proxy only.",
      "Alpha represents the fraction of envelope hydrogen that the scenario treats as core-accessible.",
      "Does not model luminosity evolution, shell burning, or structural feedback.",
      "Planning/forecast row only.",
    ],
    calculatorPayloads: [
      calculatorPayload({
        id: "lifetime_extension_proxy_payload",
        expression: "Delta_t_Myr = alpha*M_env_H/(Mdot_burn_sun*31557600*1e6)",
        displayLatex: "\\Delta t_{Myr}\\approx\\frac{\\alpha M_{env,H}}{\\dot{M}_{burn,sun}(31557600)(10^6)}",
        targetVariable: "Delta_t_Myr",
        subgoal: "Estimate the planning-only lifetime extension from accessible envelope hydrogen.",
        variables: [
          { symbol: "alpha", value: "0.01", meaning: "fraction of envelope hydrogen treated as core-accessible", dimensionSignature: "1" },
          { symbol: "M_env_H", value: "1.1e30", unit: "kg", meaning: "envelope hydrogen mass proxy", dimensionSignature: "M" },
          { symbol: "Mdot_burn_sun", value: "6.0e11", unit: "kg/s", meaning: "solar hydrogen-burning mass-flow scale", dimensionSignature: "M T^-1" },
        ],
        resultUnit: "Myr",
        resultQuantity: "time",
        resultDimensionSignature: "T",
      }),
    ],
    sourceRefs: [
      repoRef(DEEP_MIXING_PRESET_REPO_PATH, "DEEP_MIXING_TARGETS", "Planning targets for +10 Myr, +50 Myr, and +0.6 Gyr."),
      docRef(DEEP_MIXING_PLAN_DOC, "lifetime-extension-equation", "Fuel-budget lifetime extension equation."),
      docRef(SOLAR_RESTORATION_KNOWLEDGE_DOC, "solar-restoration", "Mission framing for solar restoration prompts."),
    ],
    hintKeys: {
      subjects: ["starsim", "solar_restoration", "lifetime_extension", "fuel_budget", "red_giant"],
      symbols: ["Delta_t_Myr", "alpha", "M_env_H", "Mdot_burn_sun"],
      unitSignatures: ["T", "M", "M T^-1", "1"],
      repoPaths: [DEEP_MIXING_PRESET_REPO_PATH, DEEP_MIXING_PLAN_DOC, SOLAR_RESTORATION_KNOWLEDGE_DOC],
      equationFamilies: ["solar_restoration_deep_mixing", "fuel_budget_proxy"],
      simulationOwners: ["starsim"],
    },
  }),
  starsimBadge({
    id: "starsim.restoration.guardrail_constraints",
    title: "Solar restoration guardrail constraints",
    plainMeaning: "Keeps the deep-mixing plan bounded by luminosity, core-temperature, seismic, and neutrino guardrails.",
    whyItMatters: "It makes the calculator/runtime branch carry the same safety constraints as the planning autopilot.",
    subjects: ["starsim", "solar_restoration", "guardrail", "helioseismology", "neutrino"],
    level: "diagnostic_gate",
    status: "diagnostic",
    simulationOwners: ["starsim"],
    equationFamilies: ["solar_restoration_guardrail", "telemetry_gate"],
    tags: ["guardrail", "deep_mixing", "calculator_loadable", "planning_forecast"],
    equations: [
      {
        id: "luminosity_guardrail_margin",
        role: "calculator_demo",
        displayLatex: "margin_L=(d\\ln L/dt)_{max}-|d\\ln L/dt|",
        computableExpression: "luminosity_margin = dlnL_limit - dlnL_abs",
        operatorKind: "scalar_expression",
        inputSymbols: ["dlnL_limit", "dlnL_abs"],
        outputSymbols: ["luminosity_margin"],
      },
      {
        id: "core_temperature_guardrail_margin",
        role: "calculator_demo",
        displayLatex: "margin_{T_c}=(d\\ln T_c/dt)_{max}-|d\\ln T_c/dt|",
        computableExpression: "core_temp_margin = dlnTc_limit - dlnTc_abs",
        operatorKind: "scalar_expression",
        inputSymbols: ["dlnTc_limit", "dlnTc_abs"],
        outputSymbols: ["core_temp_margin"],
      },
      {
        id: "restoration_guardrail_gate",
        role: "gate",
        displayLatex: "|d\\ln L/dt|\\le 10^{-3},\\ |d\\ln T_c/dt|\\le 10^{-3},\\ seismicGrowth\\le 0,\\ neutrinoDelta\\le 0",
        computableExpression: null,
        operatorKind: "gate_status",
        inputSymbols: ["dlnL_abs", "dlnTc_abs", "seismicGrowth", "neutrinoDelta"],
        outputSymbols: ["guardrail_status"],
      },
    ],
    units: [
      { symbol: "dlnL_limit", unit: "1/Myr", quantity: "log_rate", dimensionSignature: "T^-1" },
      { symbol: "dlnTc_limit", unit: "1/Myr", quantity: "log_rate", dimensionSignature: "T^-1" },
      { symbol: "luminosity_margin", unit: "1/Myr", quantity: "log_rate_margin", dimensionSignature: "T^-1" },
      { symbol: "core_temp_margin", unit: "1/Myr", quantity: "log_rate_margin", dimensionSignature: "T^-1" },
    ],
    assumptions: [
      "Guardrails are planning constraints around telemetry, not proof of intervention safety.",
      "The runtime may report guardrail status when matching telemetry artifacts exist.",
      "Planning/forecast row only.",
    ],
    calculatorPayloads: [
      calculatorPayload({
        id: "luminosity_guardrail_margin_payload",
        expression: "luminosity_margin = dlnL_limit - dlnL_abs",
        displayLatex: "margin_L=(d\\ln L/dt)_{max}-|d\\ln L/dt|",
        targetVariable: "luminosity_margin",
        subgoal: "Compute luminosity guardrail margin for a deep-mixing telemetry row.",
        variables: [
          { symbol: "dlnL_limit", value: "1.0e-3", unit: "1/Myr", meaning: "maximum allowed luminosity log-rate magnitude", dimensionSignature: "T^-1" },
          { symbol: "dlnL_abs", value: "0", unit: "1/Myr", meaning: "observed luminosity log-rate magnitude", dimensionSignature: "T^-1" },
        ],
        resultUnit: "1/Myr",
        resultQuantity: "log_rate_margin",
        resultDimensionSignature: "T^-1",
      }),
      calculatorPayload({
        id: "core_temperature_guardrail_margin_payload",
        expression: "core_temp_margin = dlnTc_limit - dlnTc_abs",
        displayLatex: "margin_{T_c}=(d\\ln T_c/dt)_{max}-|d\\ln T_c/dt|",
        targetVariable: "core_temp_margin",
        subgoal: "Compute core-temperature guardrail margin for a deep-mixing telemetry row.",
        variables: [
          { symbol: "dlnTc_limit", value: "1.0e-3", unit: "1/Myr", meaning: "maximum allowed core-temperature log-rate magnitude", dimensionSignature: "T^-1" },
          { symbol: "dlnTc_abs", value: "0", unit: "1/Myr", meaning: "observed core-temperature log-rate magnitude", dimensionSignature: "T^-1" },
        ],
        resultUnit: "1/Myr",
        resultQuantity: "log_rate_margin",
        resultDimensionSignature: "T^-1",
      }),
    ],
    sourceRefs: [
      repoRef(DEEP_MIXING_PRESET_REPO_PATH, "controlStep", "Autopilot guardrail trimming."),
      repoRef(DEEP_MIXING_PRESET_REPO_PATH, "DeepMixingAutopilot", "Default guardrail limits."),
      docRef(DEEP_MIXING_PLAN_DOC, "monitoring-guardrails", "Helioseismology and neutrino monitoring guardrails."),
    ],
    hintKeys: {
      subjects: ["starsim", "solar_restoration", "guardrail", "helioseismology", "neutrino"],
      symbols: ["luminosity_margin", "core_temp_margin", "dlnL_limit", "dlnL_abs", "dlnTc_limit", "dlnTc_abs", "seismicGrowth", "neutrinoDelta"],
      unitSignatures: ["T^-1", "1"],
      repoPaths: [DEEP_MIXING_PRESET_REPO_PATH, DEEP_MIXING_PLAN_DOC],
      equationFamilies: ["solar_restoration_guardrail", "telemetry_gate"],
      simulationOwners: ["starsim"],
    },
  }),
  starsimBadge({
    id: "starsim.restoration.transition_hazard_proxy",
    title: "Red-giant transition hazard proxy",
    plainMeaning: "Summarizes the toy risk curve that rises when core hydrogen falls below a scenario threshold.",
    whyItMatters: "It lets the theory panel represent the red-giant delay plot as a diagnostic proxy rather than a proven forecast.",
    subjects: ["starsim", "solar_restoration", "red_giant", "hazard", "diagnostic"],
    level: "model",
    status: "diagnostic",
    simulationOwners: ["starsim"],
    equationFamilies: ["solar_restoration_deep_mixing", "transition_hazard_proxy"],
    tags: ["red_giant", "hazard", "calculator_loadable", "planning_forecast"],
    equations: [
      {
        id: "transition_hazard",
        role: "calculator_demo",
        displayLatex: "h=h_0\\exp(\\beta\\ deficit)",
        computableExpression: "h = h0*exp(beta*deficit)",
        operatorKind: "scalar_expression",
        inputSymbols: ["h0", "beta", "deficit"],
        outputSymbols: ["h"],
      },
      {
        id: "constant_hazard_probability",
        role: "calculator_demo",
        displayLatex: "P=1-\\exp(-hT)",
        computableExpression: "P = 1 - exp(-h*T)",
        operatorKind: "scalar_expression",
        inputSymbols: ["h", "T"],
        outputSymbols: ["P"],
      },
    ],
    units: [
      { symbol: "h", unit: "1/Gyr", quantity: "hazard_rate", dimensionSignature: "T^-1" },
      { symbol: "T", unit: "Gyr", quantity: "time", dimensionSignature: "T" },
      { symbol: "P", quantity: "probability", dimensionSignature: "1" },
    ],
    assumptions: [
      "Visualization and diagnostic proxy only.",
      "Deficit represents max(0, X_thr - X_c) as a scenario input.",
      "Does not replace a stellar-evolution calculation.",
      "Planning/forecast row only.",
    ],
    calculatorPayloads: [
      calculatorPayload({
        id: "transition_hazard_proxy_payload",
        expression: "h = h0*exp(beta*deficit)",
        displayLatex: "h=h_0\\exp(\\beta\\ deficit)",
        targetVariable: "h",
        subgoal: "Compute the toy red-giant transition hazard from core-hydrogen deficit.",
        variables: [
          { symbol: "h0", value: "0.002", unit: "1/Gyr", meaning: "baseline hazard rate", dimensionSignature: "T^-1" },
          { symbol: "beta", value: "6", meaning: "hazard growth coefficient", dimensionSignature: "1" },
          { symbol: "deficit", value: "0", meaning: "positive core-hydrogen deficit relative to threshold", dimensionSignature: "1" },
        ],
        resultUnit: "1/Gyr",
        resultQuantity: "hazard_rate",
        resultDimensionSignature: "T^-1",
      }),
      calculatorPayload({
        id: "constant_hazard_probability_payload",
        expression: "P = 1 - exp(-h*T)",
        displayLatex: "P=1-\\exp(-hT)",
        targetVariable: "P",
        subgoal: "Compute a constant-hazard transition probability over a scenario horizon.",
        variables: [
          { symbol: "h", value: "0.002", unit: "1/Gyr", meaning: "toy transition hazard rate", dimensionSignature: "T^-1" },
          { symbol: "T", value: "1", unit: "Gyr", meaning: "scenario horizon", dimensionSignature: "T" },
        ],
        resultQuantity: "probability",
        resultDimensionSignature: "1",
      }),
    ],
    sourceRefs: [
      repoRef("client/src/components/deepmix/DeepMixSweetSpot.tsx", "simulate", "Toy red-giant transition probability model."),
      repoRef("client/src/components/deepmix/DeepMixGlobePanel.tsx", "computeScenario", "Globe panel hazard summary."),
      docRef(DEEP_MIXING_PLAN_DOC, "red-giant-transition", "Planning context for red-giant delay."),
    ],
    hintKeys: {
      subjects: ["starsim", "solar_restoration", "red_giant", "hazard", "diagnostic"],
      symbols: ["h", "h0", "beta", "deficit", "X_thr", "X_c", "P", "T"],
      unitSignatures: ["T^-1", "T", "1"],
      repoPaths: ["client/src/components/deepmix/DeepMixSweetSpot.tsx", "client/src/components/deepmix/DeepMixGlobePanel.tsx", DEEP_MIXING_PLAN_DOC],
      equationFamilies: ["solar_restoration_deep_mixing", "transition_hazard_proxy"],
      simulationOwners: ["starsim"],
    },
  }),
  starsimBadge({
    id: "starsim.restoration.claim_boundary.planning_forecast_only",
    title: "Solar restoration planning boundary",
    plainMeaning: "Marks the solar-restoration branch as planning and forecast context only.",
    whyItMatters: "It prevents calculator or runtime rows from being promoted into claims of feasible stellar intervention.",
    subjects: ["starsim", "solar_restoration", "claim_boundary", "safety"],
    level: "claim_boundary",
    status: "diagnostic",
    simulationOwners: ["starsim"],
    equationFamilies: ["claim_boundary", "solar_restoration_deep_mixing"],
    tags: ["solar_restoration", "claim_boundary", "planning_forecast", "guardrail"],
    equations: [
      {
        id: "solar_restoration_planning_boundary_gate",
        role: "gate",
        displayLatex: "solar\\ restoration\\rightarrow planning\\ forecast\\ only",
        computableExpression: null,
        operatorKind: "gate_status",
        inputSymbols: ["restorationBadgeReceipt"],
        outputSymbols: ["planning_forecast_only"],
      },
    ],
    units: [],
    assumptions: [
      "Solar restoration rows are planning/forecast context only.",
      "They do not imply feasible or proven stellar intervention.",
      "They do not validate NHM2, warp operations, or full stellar-evolution solving.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      docRef(SOLAR_RESTORATION_KNOWLEDGE_DOC, "solar-restoration", "Solar restoration mission framing."),
      docRef(DEEP_MIXING_KNOWLEDGE_DOC, "deep-mixing", "Deep-mixing knowledge branch."),
      docRef("docs/theory-physics-inventory-audit.md", "solar_restoration_red_giant", "Inventory boundary for non-actionable forecast rows."),
      repoRef("server/services/helix-ask/theory-congruence/forbidden-claims.ts", "forbidden-claims", "Forbidden feasible-restoration claim patterns."),
    ],
    hintKeys: {
      subjects: ["starsim", "solar_restoration", "claim_boundary", "planning_forecast", "safety"],
      symbols: ["planning_forecast_only", "claimBoundary", "blockedClaims"],
      unitSignatures: [],
      repoPaths: [SOLAR_RESTORATION_KNOWLEDGE_DOC, DEEP_MIXING_KNOWLEDGE_DOC, "docs/theory-physics-inventory-audit.md"],
      equationFamilies: ["claim_boundary", "solar_restoration_deep_mixing"],
      simulationOwners: ["starsim"],
    },
  }),
  starsimBadge({
    id: "starsim.map.structure_weight",
    title: "StarSim map structure weight",
    plainMeaning: "Assigns a simple inverse-distance structure weight between star-map nodes.",
    whyItMatters: "It exposes a calculator-loadable scalar from the StarMap fusion graph builder.",
    subjects: ["starsim", "star_map", "graph", "distance"],
    level: "simulation_specific",
    status: "project_derived",
    simulationOwners: ["starsim"],
    equationFamilies: ["starmap_fusion_graph"],
    tags: ["distance", "structure_weight", "calculator_loadable"],
    equations: [
      {
        id: "structure_weight",
        role: "calculator_demo",
        displayLatex: "structureWeight=\\frac{1}{1+distance_{pc}}",
        computableExpression: "structureWeight = 1/(1 + distance_pc)",
        operatorKind: "scalar_expression",
        inputSymbols: ["distance_pc"],
        outputSymbols: ["structureWeight"],
      },
    ],
    units: [
      { symbol: "distance_pc", unit: "pc", quantity: "distance", dimensionSignature: "L" },
      { symbol: "structureWeight", quantity: "graph_weight", dimensionSignature: "1" },
    ],
    assumptions: ["StarMap structure prior only.", "Distance weighting is contextual and not a dynamical orbit solve."],
    calculatorPayloads: [
      calculatorPayload({
        id: "structure_weight_payload",
        expression: "structureWeight = 1/(1 + distance_pc)",
        displayLatex: "structureWeight=\\frac{1}{1+distance_{pc}}",
        targetVariable: "structureWeight",
        subgoal: "Compute the StarMap inverse-distance structure weight.",
        variables: [
          { symbol: "distance_pc", value: "1", unit: "pc", meaning: "pairwise distance between star-map nodes", dimensionSignature: "L" },
        ],
        resultQuantity: "graph_weight",
        resultDimensionSignature: "1",
      }),
    ],
    sourceRefs: [
      repoRef(STARSIM_REPO_PATH, "buildStarMapFusionGraph", "Pairwise star-map fusion graph builder."),
      docRef(STARSIM_MAP_DOC, "astrometric-structure-prior", "StarMap graph output is a structure prior."),
    ],
    hintKeys: {
      subjects: ["starsim", "star_map", "distance", "structure_weight", "graph"],
      symbols: ["structureWeight", "distance_pc", "x", "y", "z"],
      unitSignatures: ["1", "L"],
      repoPaths: [STARSIM_REPO_PATH, STARSIM_MAP_DOC],
      equationFamilies: ["starmap_fusion_graph"],
      simulationOwners: ["starsim"],
    },
  }),
  starsimBadge({
    id: "starsim.runtime.evaluate_fusion_microphysics",
    title: "StarSim fusion microphysics runtime",
    plainMeaning: "Represents the Stage 1 runtime evaluator that classifies fusion context and reports reduced-order outputs.",
    whyItMatters: "It tells Helix that some StarSim answers require runtime classification rather than a scalar calculator solve.",
    subjects: ["starsim", "runtime", "fusion", "classifier"],
    level: "simulation_specific",
    status: "diagnostic",
    simulationOwners: ["starsim"],
    equationFamilies: ["fusion_runtime_evaluation"],
    tags: ["evaluateStarSimFusionMicrophysics", "runtime", "classifier"],
    equations: [
      {
        id: "starsim_runtime_evaluation",
        role: "gate",
        displayLatex: "evaluateStarSimFusionMicrophysics(input)\\rightarrow receipt",
        computableExpression: null,
        operatorKind: "gate_status",
        inputSymbols: ["objectClass", "observables", "modelMode"],
        outputSymbols: ["dominantFusionChannel", "fusionZone", "blockedClaims"],
      },
    ],
    units: [],
    assumptions: [
      "Runtime evaluation badge only.",
      "Scalar helper equations live on neighboring calculator-loadable badges.",
      "Stage 1 output remains a reduced-order astrophysical prior.",
    ],
    calculatorPayloads: [],
    sourceRefs: commonSourceRefs("evaluateStarSimFusionMicrophysics"),
    hintKeys: {
      subjects: ["starsim", "runtime", "fusion_microphysics", "classifier", "modelMode"],
      symbols: ["dominantFusionChannel", "fusionZone", "blockedClaims", "objectClass", "modelMode"],
      unitSignatures: [],
      repoPaths: [STARSIM_REPO_PATH],
      equationFamilies: ["fusion_runtime_evaluation"],
      simulationOwners: ["starsim"],
    },
  }),
  starsimBadge({
    id: "starsim.runtime.build_star_map_fusion_graph",
    title: "StarSim map fusion graph runtime",
    plainMeaning: "Represents the runtime builder for pairwise StarMap structure and fusion-contrast weights.",
    whyItMatters: "It lets Helix distinguish star-map graph construction from scalar distance or weight formulas.",
    subjects: ["starsim", "runtime", "star_map", "graph"],
    level: "simulation_specific",
    status: "diagnostic",
    simulationOwners: ["starsim"],
    equationFamilies: ["starmap_fusion_graph"],
    tags: ["buildStarMapFusionGraph", "runtime", "graph"],
    equations: [
      {
        id: "starmap_runtime_graph",
        role: "gate",
        displayLatex: "buildStarMapFusionGraph(nodes)\\rightarrow edges",
        computableExpression: null,
        operatorKind: "gate_status",
        inputSymbols: ["starMapNodes"],
        outputSymbols: ["distance_pc", "relativeVelocity_kms", "structureWeight", "fusionContrastWeight"],
      },
    ],
    units: [
      { symbol: "distance_pc", unit: "pc", quantity: "distance", dimensionSignature: "L" },
      { symbol: "relativeVelocity_kms", unit: "km/s", quantity: "speed", dimensionSignature: "L T^-1" },
    ],
    assumptions: ["Astrometric structure prior only.", "Graph weights do not imply a spacetime connection."],
    calculatorPayloads: [],
    sourceRefs: [
      repoRef(STARSIM_REPO_PATH, "buildStarMapFusionGraph", "Runtime graph builder."),
      docRef(STARSIM_MAP_DOC, "null-model", "Galactic dynamics null-model context."),
    ],
    hintKeys: {
      subjects: ["starsim", "runtime", "star_map", "graph", "distance"],
      symbols: ["distance_pc", "relativeVelocity_kms", "structureWeight", "fusionContrastWeight"],
      unitSignatures: ["L", "L T^-1", "1"],
      repoPaths: [STARSIM_REPO_PATH, STARSIM_MAP_DOC],
      equationFamilies: ["starmap_fusion_graph"],
      simulationOwners: ["starsim"],
    },
  }),
  starsimBadge({
    id: "starsim.claim_boundary.stage1_reduced_order_prior",
    title: "StarSim Stage 1 boundary",
    plainMeaning: "Marks StarSim fusion microphysics as a reduced-order astrophysical prior with explicit limits.",
    whyItMatters: "It keeps Helix answers anchored to what the StarSim branch can and cannot support.",
    subjects: ["starsim", "claim_boundary", "safety"],
    level: "claim_boundary",
    status: "diagnostic",
    simulationOwners: ["starsim"],
    equationFamilies: ["claim_boundary"],
    tags: ["stage1", "boundary", "guardrail"],
    equations: [
      {
        id: "starsim_stage1_boundary_gate",
        role: "gate",
        displayLatex: "StarSim_{Stage1}\\rightarrow diagnostic\\_prior",
        computableExpression: null,
        operatorKind: "gate_status",
        inputSymbols: ["starsimRuntimeReceipt"],
        outputSymbols: ["claimBoundary"],
      },
    ],
    units: [],
    assumptions: [
      "Reduced-order astrophysical prior only.",
      "Does not support propulsion, spacetime-mechanism, stress-energy sourcing, or claim-level promotion.",
      "Calculator payloads are scalar helpers around the runtime, not a complete stellar-evolution solver.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      docRef(STARSIM_STAGE1_DOC, "claim-boundary"),
      docRef(STARSIM_MAP_DOC, "astrometric-structure-prior"),
      repoRef("shared/starsim-fusion-safe-language.ts", "safe-language", "Safe-language guardrails for StarSim outputs."),
      repoRef("shared/starsim-fusion-claims.ts", "claim-policy", "Claim policy identifiers and blocked-claim handling."),
    ],
    hintKeys: {
      subjects: ["starsim", "claim_boundary", "stage1", "safety", "reduced_order_prior"],
      symbols: ["blockedClaims", "claimIds", "claimBoundary"],
      unitSignatures: [],
      repoPaths: [
        STARSIM_STAGE1_DOC,
        STARSIM_MAP_DOC,
        "shared/starsim-fusion-safe-language.ts",
        "shared/starsim-fusion-claims.ts",
      ],
      equationFamilies: ["claim_boundary"],
      simulationOwners: ["starsim"],
    },
  }),
];

export const STARSIM_THEORY_EDGES: TheoryBadgeEdgeV1[] = [
  {
    id: "dimension_consistency_bounds_starsim_surface_temperature",
    from: "physics.units.dimension_consistency",
    to: "starsim.observable.surface_temperature_proxy",
    relation: "bounds",
    label: "Surface temperature proxy depends on compatible temperature, luminosity, and radius units.",
    claimBoundaryNote: "Dimensional compatibility is a guardrail only.",
  },
  {
    id: "power_rate_feeds_starsim_surface_temperature",
    from: "physics.energy.power_rate",
    to: "starsim.observable.surface_temperature_proxy",
    relation: "requires",
    label: "Luminosity is an energy-per-time observable in the surface-temperature proxy.",
    claimBoundaryNote: "Scalar observable relation remains a reduced-order proxy.",
  },
  {
    id: "dimension_consistency_bounds_starsim_surface_gravity",
    from: "physics.units.dimension_consistency",
    to: "starsim.observable.surface_gravity",
    relation: "bounds",
    label: "Surface gravity requires consistent mass, radius, and constant units.",
    claimBoundaryNote: "Unit consistency does not establish runtime classification.",
  },
  {
    id: "dimension_consistency_bounds_starsim_mean_density",
    from: "physics.units.dimension_consistency",
    to: "starsim.observable.mean_density",
    relation: "bounds",
    label: "Mean density requires compatible mass and radius dimensions.",
    claimBoundaryNote: "Scalar density proxy is not a resolved stellar model.",
  },
  {
    id: "energy_density_shares_starsim_mean_density",
    from: "physics.energy.energy_density",
    to: "starsim.observable.mean_density",
    relation: "shares_units",
    label: "Energy-density and mass-density prompts often share density vocabulary.",
    claimBoundaryNote: "Shared vocabulary is context only.",
  },
  {
    id: "surface_gravity_feeds_hydrostatic_balance",
    from: "starsim.observable.surface_gravity",
    to: "starsim.structure.hydrostatic_balance",
    relation: "requires",
    label: "Gravity observables provide context for hydrostatic balance.",
    claimBoundaryNote: "Reference structure edge only.",
  },
  {
    id: "mean_density_feeds_mass_continuity",
    from: "starsim.observable.mean_density",
    to: "starsim.structure.mass_continuity",
    relation: "requires",
    label: "Mean density is the scalar proxy nearest the mass-continuity reference.",
    claimBoundaryNote: "Reduced scalar proxy does not integrate the structure equation.",
  },
  {
    id: "mass_continuity_feeds_luminosity_gradient",
    from: "starsim.structure.mass_continuity",
    to: "starsim.structure.luminosity_gradient",
    relation: "requires",
    label: "Luminosity generation references density and enclosed structure context.",
    claimBoundaryNote: "Reference edge only.",
  },
  {
    id: "hydrostatic_balance_feeds_core_temperature_proxy",
    from: "starsim.structure.hydrostatic_balance",
    to: "starsim.structure.core_temperature_proxy",
    relation: "approximates",
    label: "The core-temperature proxy approximates hydrostatic structure context with compactness scaling.",
    claimBoundaryNote: "Approximation remains Stage 1 diagnostic context.",
  },
  {
    id: "mean_density_feeds_core_density_proxy",
    from: "starsim.observable.mean_density",
    to: "starsim.structure.core_density_proxy",
    relation: "approximates",
    label: "The core-density proxy scales from observable mass and radius context.",
    claimBoundaryNote: "Approximation remains Stage 1 diagnostic context.",
  },
  {
    id: "surface_temperature_feeds_pp_chain_prior",
    from: "starsim.observable.surface_temperature_proxy",
    to: "starsim.fusion.pp_chain_prior",
    relation: "requires",
    label: "Surface temperature helps route lower-mass main-sequence fusion classification.",
    claimBoundaryNote: "Classifier edge is diagnostic only.",
  },
  {
    id: "surface_temperature_feeds_cno_prior",
    from: "starsim.observable.surface_temperature_proxy",
    to: "starsim.fusion.cno_cycle_prior",
    relation: "requires",
    label: "Surface temperature helps route hotter main-sequence fusion classification.",
    claimBoundaryNote: "Classifier edge is diagnostic only.",
  },
  {
    id: "core_temperature_feeds_cno_prior",
    from: "starsim.structure.core_temperature_proxy",
    to: "starsim.fusion.cno_cycle_prior",
    relation: "requires",
    label: "Core-temperature proxy provides context for hotter-channel classification.",
    claimBoundaryNote: "Reduced proxy does not replace runtime classification.",
  },
  {
    id: "core_density_feeds_pp_chain_prior",
    from: "starsim.structure.core_density_proxy",
    to: "starsim.fusion.pp_chain_prior",
    relation: "requires",
    label: "Core-density proxy provides context for pp-chain classification.",
    claimBoundaryNote: "Reduced proxy does not replace runtime classification.",
  },
  {
    id: "pp_chain_feeds_active_volume_fraction",
    from: "starsim.fusion.pp_chain_prior",
    to: "starsim.fusion_zone.active_volume_fraction",
    relation: "requires",
    label: "Fusion-channel context informs which runtime fusion zone is summarized.",
    claimBoundaryNote: "Runtime zone remains a Stage 1 diagnostic summary.",
  },
  {
    id: "cno_feeds_active_volume_fraction",
    from: "starsim.fusion.cno_cycle_prior",
    to: "starsim.fusion_zone.active_volume_fraction",
    relation: "requires",
    label: "CNO-channel context informs which runtime fusion zone is summarized.",
    claimBoundaryNote: "Runtime zone remains a Stage 1 diagnostic summary.",
  },
  {
    id: "fusion_priors_feed_starsim_runtime",
    from: "starsim.fusion.pp_chain_prior",
    to: "starsim.runtime.evaluate_fusion_microphysics",
    relation: "diagnostic_checks",
    label: "Runtime evaluation applies fusion-channel selection logic.",
    claimBoundaryNote: "Runtime result is a diagnostic receipt candidate, not a promotion.",
  },
  {
    id: "cno_prior_feeds_starsim_runtime",
    from: "starsim.fusion.cno_cycle_prior",
    to: "starsim.runtime.evaluate_fusion_microphysics",
    relation: "diagnostic_checks",
    label: "Runtime evaluation applies hot-star fusion-channel selection logic.",
    claimBoundaryNote: "Runtime result is a diagnostic receipt candidate, not a promotion.",
  },
  {
    id: "compact_gate_feeds_starsim_runtime",
    from: "starsim.fusion.compact_object_not_fusing",
    to: "starsim.runtime.evaluate_fusion_microphysics",
    relation: "diagnostic_checks",
    label: "Compact-object guardrail feeds runtime classification.",
    claimBoundaryNote: "Guardrail prevents ordinary fusion routing for compact objects.",
  },
  {
    id: "active_volume_feeds_starsim_runtime",
    from: "starsim.fusion_zone.active_volume_fraction",
    to: "starsim.runtime.evaluate_fusion_microphysics",
    relation: "diagnostic_checks",
    label: "Fusion-zone scalar summaries sit beside the runtime evaluation.",
    claimBoundaryNote: "Scalar summary remains diagnostic context.",
  },
  {
    id: "pp_chain_prior_feeds_deep_mixing_mass_flux",
    from: "starsim.fusion.pp_chain_prior",
    to: "starsim.restoration.deep_mixing_mass_flux",
    relation: "requires",
    label: "Sun-like pp-chain context supplies the hydrogen-burning branch that the restoration forecast references.",
    claimBoundaryNote: "Restoration mass flux is a planning proxy only.",
  },
  {
    id: "luminosity_gradient_feeds_core_hydrogen_balance",
    from: "starsim.structure.luminosity_gradient",
    to: "starsim.restoration.core_hydrogen_balance",
    relation: "requires",
    label: "Hydrogen-burning luminosity context feeds the one-zone composition-balance proxy.",
    claimBoundaryNote: "Composition balance remains reduced-order diagnostic context.",
  },
  {
    id: "deep_mixing_mass_flux_derives_tachocline_downflow",
    from: "starsim.restoration.deep_mixing_mass_flux",
    to: "starsim.restoration.tachocline_downflow_setpoint",
    relation: "derives",
    label: "The tachocline downflow setpoint solves the mass-flux closure for radial speed.",
    claimBoundaryNote: "Downflow is a scalar setpoint, not an actuator feasibility claim.",
  },
  {
    id: "deep_mixing_mass_flux_feeds_core_hydrogen_balance",
    from: "starsim.restoration.deep_mixing_mass_flux",
    to: "starsim.restoration.core_hydrogen_balance",
    relation: "approximates",
    label: "The imported hydrogen mass flux feeds the one-zone core-hydrogen balance proxy.",
    claimBoundaryNote: "One-zone balance does not replace a stellar-evolution solve.",
  },
  {
    id: "core_hydrogen_balance_feeds_lifetime_extension",
    from: "starsim.restoration.core_hydrogen_balance",
    to: "starsim.restoration.lifetime_extension_proxy",
    relation: "approximates",
    label: "The composition-balance branch feeds the fuel-budget lifetime-extension proxy.",
    claimBoundaryNote: "Lifetime extension remains a heuristic forecast row.",
  },
  {
    id: "core_hydrogen_balance_feeds_transition_hazard",
    from: "starsim.restoration.core_hydrogen_balance",
    to: "starsim.restoration.transition_hazard_proxy",
    relation: "approximates",
    label: "Core hydrogen fraction context feeds the red-giant transition hazard proxy.",
    claimBoundaryNote: "Hazard output is visualization context only.",
  },
  {
    id: "guardrails_bound_tachocline_downflow",
    from: "starsim.restoration.guardrail_constraints",
    to: "starsim.restoration.tachocline_downflow_setpoint",
    relation: "bounds",
    label: "Telemetry guardrails bound the downflow setpoint branch.",
    claimBoundaryNote: "Passing guardrails would not prove safe intervention.",
  },
  {
    id: "guardrails_bound_core_hydrogen_balance",
    from: "starsim.restoration.guardrail_constraints",
    to: "starsim.restoration.core_hydrogen_balance",
    relation: "bounds",
    label: "Luminosity, core-temperature, seismic, and neutrino constraints bound the composition proxy.",
    claimBoundaryNote: "Guardrail margins remain diagnostic telemetry checks.",
  },
  {
    id: "deep_mixing_mass_flux_feeds_planning_boundary",
    from: "starsim.restoration.deep_mixing_mass_flux",
    to: "starsim.restoration.claim_boundary.planning_forecast_only",
    relation: "diagnostic_checks",
    label: "Mass-flux restoration rows terminate in the planning-only boundary.",
    claimBoundaryNote: "Solar restoration mass-flow rows cannot promote to feasible-intervention claims.",
  },
  {
    id: "lifetime_extension_feeds_planning_boundary",
    from: "starsim.restoration.lifetime_extension_proxy",
    to: "starsim.restoration.claim_boundary.planning_forecast_only",
    relation: "diagnostic_checks",
    label: "Lifetime-extension forecasts terminate in the planning-only boundary.",
    claimBoundaryNote: "Fuel-budget forecasts cannot become validation claims.",
  },
  {
    id: "transition_hazard_feeds_planning_boundary",
    from: "starsim.restoration.transition_hazard_proxy",
    to: "starsim.restoration.claim_boundary.planning_forecast_only",
    relation: "diagnostic_checks",
    label: "Transition-hazard rows terminate in the planning-only boundary.",
    claimBoundaryNote: "Hazard curves remain diagnostic visualization context.",
  },
  {
    id: "stage1_boundary_bounds_restoration_boundary",
    from: "starsim.claim_boundary.stage1_reduced_order_prior",
    to: "starsim.restoration.claim_boundary.planning_forecast_only",
    relation: "bounds",
    label: "The StarSim Stage 1 boundary also bounds the solar-restoration branch.",
    claimBoundaryNote: "Restoration rows are no stronger than StarSim Stage 1 reduced-order priors.",
  },
  {
    id: "surface_temperature_feeds_cno_temperature_margin",
    from: "starsim.observable.surface_temperature_proxy",
    to: "starsim.classifier.cno_temperature_margin",
    relation: "requires",
    label: "Surface-temperature proxy supplies the reduced CNO temperature margin.",
    claimBoundaryNote: "Margin is explanatory classifier context only.",
  },
  {
    id: "core_temperature_feeds_cno_temperature_margin",
    from: "starsim.structure.core_temperature_proxy",
    to: "starsim.classifier.cno_temperature_margin",
    relation: "requires",
    label: "Core-temperature proxy sits beside the CNO temperature threshold context.",
    claimBoundaryNote: "Reduced proxy does not replace runtime classification.",
  },
  {
    id: "mean_density_feeds_compactness_scale",
    from: "starsim.observable.mean_density",
    to: "starsim.classifier.compactness_scale",
    relation: "requires",
    label: "Mass/radius observable context supports compactness-scale calculation.",
    claimBoundaryNote: "Compactness scale is normalized classifier context.",
  },
  {
    id: "compactness_scale_feeds_starsim_runtime",
    from: "starsim.classifier.compactness_scale",
    to: "starsim.runtime.evaluate_fusion_microphysics",
    relation: "diagnostic_checks",
    label: "Compactness-scale row helps explain runtime classification context.",
    claimBoundaryNote: "Runtime result remains Stage 1 diagnostic context.",
  },
  {
    id: "brown_dwarf_margin_feeds_starsim_runtime",
    from: "starsim.classifier.brown_dwarf_mass_margin",
    to: "starsim.runtime.evaluate_fusion_microphysics",
    relation: "diagnostic_checks",
    label: "Brown-dwarf mass margin helps explain inactive-fusion routing.",
    claimBoundaryNote: "Margin is explanatory classifier context only.",
  },
  {
    id: "cno_mass_margin_feeds_starsim_runtime",
    from: "starsim.classifier.cno_mass_margin",
    to: "starsim.runtime.evaluate_fusion_microphysics",
    relation: "diagnostic_checks",
    label: "CNO mass margin helps explain hot/high-mass routing.",
    claimBoundaryNote: "Margin is explanatory classifier context only.",
  },
  {
    id: "cno_temperature_margin_feeds_starsim_runtime",
    from: "starsim.classifier.cno_temperature_margin",
    to: "starsim.runtime.evaluate_fusion_microphysics",
    relation: "diagnostic_checks",
    label: "CNO temperature margin helps explain hot-star routing.",
    claimBoundaryNote: "Margin is explanatory classifier context only.",
  },
  {
    id: "starmap_structure_weight_feeds_starmap_runtime",
    from: "starsim.map.structure_weight",
    to: "starsim.runtime.build_star_map_fusion_graph",
    relation: "numerically_solves",
    label: "The structure-weight scalar is one expression used around StarMap graph construction.",
    claimBoundaryNote: "Graph structure is a prior, not a mechanism claim.",
  },
  {
    id: "starsim_runtime_feeds_stage1_boundary",
    from: "starsim.runtime.evaluate_fusion_microphysics",
    to: "starsim.claim_boundary.stage1_reduced_order_prior",
    relation: "diagnostic_checks",
    label: "StarSim runtime outputs carry Stage 1 boundary notes.",
    claimBoundaryNote: "Boundary edge keeps answers in diagnostic-prior language.",
  },
  {
    id: "starsim_starmap_runtime_feeds_stage1_boundary",
    from: "starsim.runtime.build_star_map_fusion_graph",
    to: "starsim.claim_boundary.stage1_reduced_order_prior",
    relation: "diagnostic_checks",
    label: "StarMap graph outputs carry structure-prior boundary notes.",
    claimBoundaryNote: "Boundary edge keeps graph outputs in prior language.",
  },
];

export function buildStarSimTheoryBadgesV1(): {
  badges: TheoryBadgeV1[];
  edges: TheoryBadgeEdgeV1[];
} {
  return {
    badges: STARSIM_THEORY_BADGES,
    edges: STARSIM_THEORY_EDGES,
  };
}
