import {
  type TheoryBadgeClaimBoundaryV1,
  type TheoryBadgeEdgeV1,
  type TheoryBadgeV1,
} from "../contracts/theory-badge-graph.v1";

const TOKAMAK_BOUNDARY: TheoryBadgeClaimBoundaryV1 = {
  diagnosticOnly: true,
  doesValidateNHM2: false,
  validationClaimAllowed: false,
  physicalMechanismClaimAllowed: false,
  promotionAllowed: false,
};

const repoRef = (path: string, id?: string, note?: string): TheoryBadgeV1["sourceRefs"][number] => ({
  kind: "repo_module",
  path,
  id: id ?? null,
  note: note ?? null,
});

const docRef = (path: string, id?: string, note?: string): TheoryBadgeV1["sourceRefs"][number] => ({
  kind: "doc",
  path,
  id: id ?? null,
  note: note ?? null,
});

const payload = (args: {
  id: string;
  expression: string;
  displayLatex: string;
  targetVariable: string;
}): TheoryBadgeV1["calculatorPayloads"][number] => ({
  id: args.id,
  expression: args.expression,
  displayLatex: args.displayLatex,
  preferredAction: "solve_with_steps",
  targetVariable: args.targetVariable,
  setupContext: null,
});

const tokamakBadge = (badge: Omit<TheoryBadgeV1, "claimBoundary">): TheoryBadgeV1 => ({
  ...badge,
  claimBoundary: TOKAMAK_BOUNDARY,
});

export const TOKAMAK_PLASMA_THEORY_BADGES: TheoryBadgeV1[] = [
  tokamakBadge({
    id: "tokamak.plasma.magnetic_pressure",
    title: "Tokamak Magnetic Pressure",
    plainMeaning: "Computes a scalar magnetic-pressure proxy from magnetic field strength.",
    whyItMatters: "It anchors plasma beta and energy-field diagnostics to a calculator-loadable pressure row.",
    subjects: ["tokamak", "plasma", "magnetic_field", "pressure"],
    level: "derived_relation",
    status: "canonical_reference",
    simulationOwners: ["tokamak"],
    equationFamilies: ["plasma_pressure", "plasma_beta"],
    tags: ["magnetic_pressure", "calculator_loadable"],
    equations: [
      {
        id: "magnetic_pressure",
        role: "calculator_demo",
        displayLatex: "p_B=\\frac{B^2}{2\\mu_0}",
        computableExpression: "p_B = B_T^2/(2*mu0)",
        operatorKind: "scalar_expression",
        inputSymbols: ["B_T", "mu0"],
        outputSymbols: ["p_B"],
      },
    ],
    units: [
      { symbol: "p_B", unit: "Pa", quantity: "magnetic_pressure", dimensionSignature: "M L^-1 T^-2" },
      { symbol: "B_T", unit: "T", quantity: "magnetic_field", dimensionSignature: "M T^-2 I^-1" },
      { symbol: "mu0", unit: "N/A^2", quantity: "vacuum_permeability", dimensionSignature: "M L T^-2 I^-2" },
    ],
    assumptions: ["Reduced scalar pressure proxy.", "Does not solve MHD equilibrium."],
    calculatorPayloads: [
      payload({
        id: "tokamak_magnetic_pressure_payload",
        expression: "p_B = B_T^2/(2*mu0)",
        displayLatex: "p_B=\\frac{B^2}{2\\mu_0}",
        targetVariable: "p_B",
      }),
    ],
    sourceRefs: [
      repoRef("shared/tokamak-energy-field.ts", "TokamakRZEnergySnapshot", "RZ energy fields include magnetic-energy-density channels."),
      repoRef("shared/tokamak-stability-proxies.ts", "TokamakStabilityMetrics", "Stability proxy fields include reduced diagnostic metrics."),
    ],
    hintKeys: {
      subjects: ["tokamak", "plasma", "magnetic_pressure", "magnetic_field"],
      symbols: ["p_B", "B_T", "mu0"],
      unitSignatures: ["M L^-1 T^-2", "M T^-2 I^-1"],
      repoPaths: ["shared/tokamak-energy-field.ts", "shared/tokamak-stability-proxies.ts"],
      equationFamilies: ["plasma_pressure", "plasma_beta"],
      simulationOwners: ["tokamak"],
    },
  }),
  tokamakBadge({
    id: "tokamak.plasma.thermal_pressure_proxy",
    title: "Tokamak Thermal Pressure Proxy",
    plainMeaning: "Estimates thermal pressure from density and electron-volt temperature.",
    whyItMatters: "It gives beta prompts a scalar pressure row connected to observable plasma state.",
    subjects: ["tokamak", "plasma", "pressure", "temperature", "density"],
    level: "derived_relation",
    status: "project_derived",
    simulationOwners: ["tokamak"],
    equationFamilies: ["plasma_pressure", "plasma_beta"],
    tags: ["thermal_pressure", "calculator_loadable"],
    equations: [
      {
        id: "thermal_pressure_proxy",
        role: "calculator_demo",
        displayLatex: "p=nT_{eV}e",
        computableExpression: "p_Pa = n_m3*T_eV*e_charge",
        operatorKind: "scalar_expression",
        inputSymbols: ["n_m3", "T_eV", "e_charge"],
        outputSymbols: ["p_Pa"],
      },
    ],
    units: [
      { symbol: "p_Pa", unit: "Pa", quantity: "thermal_pressure", dimensionSignature: "M L^-1 T^-2" },
      { symbol: "n_m3", unit: "m^-3", quantity: "number_density", dimensionSignature: "L^-3" },
      { symbol: "T_eV", unit: "eV", quantity: "temperature_energy", dimensionSignature: "M L^2 T^-2" },
    ],
    assumptions: ["Single-temperature reduced proxy.", "Species composition and profile variation require runtime context."],
    calculatorPayloads: [
      payload({
        id: "tokamak_thermal_pressure_payload",
        expression: "p_Pa = n_m3*T_eV*e_charge",
        displayLatex: "p=nT_{eV}e",
        targetVariable: "p_Pa",
      }),
    ],
    sourceRefs: [
      repoRef("shared/tokamak-stability-proxies.ts", "TokamakStabilityMetrics", "Reduced plasma stability metric context."),
      repoRef("shared/tokamak-energy-field.ts", "u_gradp_Jm3", "Pressure-gradient energy channel context."),
    ],
    hintKeys: {
      subjects: ["tokamak", "plasma", "thermal_pressure", "temperature", "density"],
      symbols: ["p_Pa", "n_m3", "T_eV", "e_charge"],
      unitSignatures: ["M L^-1 T^-2", "L^-3"],
      repoPaths: ["shared/tokamak-stability-proxies.ts", "shared/tokamak-energy-field.ts"],
      equationFamilies: ["plasma_pressure", "plasma_beta"],
      simulationOwners: ["tokamak"],
    },
  }),
  tokamakBadge({
    id: "tokamak.plasma.beta_proxy",
    title: "Tokamak Beta Proxy",
    plainMeaning: "Compares thermal pressure to magnetic pressure as a reduced beta row.",
    whyItMatters: "It localizes plasma-state prompts around pressure balance without claiming runtime stability.",
    subjects: ["tokamak", "plasma", "beta", "pressure"],
    level: "derived_relation",
    status: "project_derived",
    simulationOwners: ["tokamak"],
    equationFamilies: ["plasma_beta"],
    tags: ["beta", "calculator_loadable"],
    equations: [
      {
        id: "beta_proxy",
        role: "calculator_demo",
        displayLatex: "\\beta=\\frac{p}{p_B}",
        computableExpression: "beta = p_Pa/p_B",
        operatorKind: "scalar_expression",
        inputSymbols: ["p_Pa", "p_B"],
        outputSymbols: ["beta"],
      },
    ],
    units: [
      { symbol: "beta", unit: null, quantity: "pressure_ratio", dimensionSignature: "1" },
      { symbol: "p_Pa", unit: "Pa", quantity: "thermal_pressure", dimensionSignature: "M L^-1 T^-2" },
      { symbol: "p_B", unit: "Pa", quantity: "magnetic_pressure", dimensionSignature: "M L^-1 T^-2" },
    ],
    assumptions: ["Reduced scalar beta row.", "Does not establish equilibrium or confinement quality."],
    calculatorPayloads: [
      payload({
        id: "tokamak_beta_proxy_payload",
        expression: "beta = p_Pa/p_B",
        displayLatex: "\\beta=\\frac{p}{p_B}",
        targetVariable: "beta",
      }),
    ],
    sourceRefs: [
      repoRef("shared/tokamak-stability-proxies.ts", "TokamakStabilityMetrics", "Reduced tokamak diagnostic metric context."),
    ],
    hintKeys: {
      subjects: ["tokamak", "plasma", "beta", "pressure"],
      symbols: ["beta", "p_Pa", "p_B"],
      unitSignatures: ["1", "M L^-1 T^-2"],
      repoPaths: ["shared/tokamak-stability-proxies.ts"],
      equationFamilies: ["plasma_beta"],
      simulationOwners: ["tokamak"],
    },
  }),
  tokamakBadge({
    id: "tokamak.energy.power_balance",
    title: "Tokamak Power Balance Proxy",
    plainMeaning: "Computes a scalar net-power proxy from input and loss channels.",
    whyItMatters: "It links power prompts to energy-field and confinement runtime context.",
    subjects: ["tokamak", "plasma", "power", "energy"],
    level: "derived_relation",
    status: "project_derived",
    simulationOwners: ["tokamak"],
    equationFamilies: ["tokamak_power_balance"],
    tags: ["power_balance", "calculator_loadable"],
    equations: [
      {
        id: "power_balance",
        role: "calculator_demo",
        displayLatex: "P_{net}=P_{in}-P_{loss}",
        computableExpression: "P_net = P_in - P_loss",
        operatorKind: "scalar_expression",
        inputSymbols: ["P_in", "P_loss"],
        outputSymbols: ["P_net"],
      },
    ],
    units: [
      { symbol: "P_net", unit: "W", quantity: "power", dimensionSignature: "M L^2 T^-3" },
      { symbol: "P_in", unit: "W", quantity: "power", dimensionSignature: "M L^2 T^-3" },
      { symbol: "P_loss", unit: "W", quantity: "power", dimensionSignature: "M L^2 T^-3" },
    ],
    assumptions: ["Scalar channel accounting only.", "Transport and profile dynamics remain runtime context."],
    calculatorPayloads: [
      payload({
        id: "tokamak_power_balance_payload",
        expression: "P_net = P_in - P_loss",
        displayLatex: "P_{net}=P_{in}-P_{loss}",
        targetVariable: "P_net",
      }),
    ],
    sourceRefs: [repoRef("shared/tokamak-energy-field.ts", "TokamakRZEnergySnapshot", "Energy-field channel context.")],
    hintKeys: {
      subjects: ["tokamak", "power", "energy"],
      symbols: ["P_net", "P_in", "P_loss"],
      unitSignatures: ["M L^2 T^-3"],
      repoPaths: ["shared/tokamak-energy-field.ts"],
      equationFamilies: ["tokamak_power_balance"],
      simulationOwners: ["tokamak"],
    },
  }),
  tokamakBadge({
    id: "tokamak.energy.confinement_time_proxy",
    title: "Tokamak Confinement Energy Proxy",
    plainMeaning: "Estimates stored thermal energy from loss power and energy-confinement time.",
    whyItMatters: "It gives confinement prompts a scalar row while leaving transport modeling to runtimes.",
    subjects: ["tokamak", "plasma", "confinement", "energy"],
    level: "derived_relation",
    status: "project_derived",
    simulationOwners: ["tokamak"],
    equationFamilies: ["tokamak_confinement_proxy"],
    tags: ["confinement", "calculator_loadable"],
    equations: [
      {
        id: "confinement_energy",
        role: "calculator_demo",
        displayLatex: "W_{th}=P_{loss}\\tau_E",
        computableExpression: "W_th = P_loss*tau_E",
        operatorKind: "scalar_expression",
        inputSymbols: ["P_loss", "tau_E"],
        outputSymbols: ["W_th"],
      },
    ],
    units: [
      { symbol: "W_th", unit: "J", quantity: "energy", dimensionSignature: "M L^2 T^-2" },
      { symbol: "P_loss", unit: "W", quantity: "power", dimensionSignature: "M L^2 T^-3" },
      { symbol: "tau_E", unit: "s", quantity: "time", dimensionSignature: "T" },
    ],
    assumptions: ["Reduced scalar confinement proxy only."],
    calculatorPayloads: [
      payload({
        id: "tokamak_confinement_energy_payload",
        expression: "W_th = P_loss*tau_E",
        displayLatex: "W_{th}=P_{loss}\\tau_E",
        targetVariable: "W_th",
      }),
    ],
    sourceRefs: [repoRef("shared/tokamak-energy-field.ts", "TokamakRZEnergySnapshot", "Stored energy context.")],
    hintKeys: {
      subjects: ["tokamak", "confinement", "energy"],
      symbols: ["W_th", "P_loss", "tau_E"],
      unitSignatures: ["M L^2 T^-2", "M L^2 T^-3", "T"],
      repoPaths: ["shared/tokamak-energy-field.ts"],
      equationFamilies: ["tokamak_confinement_proxy"],
      simulationOwners: ["tokamak"],
    },
  }),
  tokamakBadge({
    id: "tokamak.precursor.score_margin",
    title: "Tokamak Precursor Score Margin",
    plainMeaning: "Compares a reduced precursor score with a diagnostic threshold.",
    whyItMatters: "It gives precursor prompts a calculator row without treating the score as a validated predictor.",
    subjects: ["tokamak", "precursor", "diagnostic", "threshold"],
    level: "diagnostic_gate",
    status: "diagnostic",
    simulationOwners: ["tokamak"],
    equationFamilies: ["tokamak_precursor"],
    tags: ["precursor", "calculator_loadable"],
    equations: [
      {
        id: "precursor_margin",
        role: "gate",
        displayLatex: "m_{precursor}=score-threshold",
        computableExpression: "precursor_margin = score - threshold",
        operatorKind: "scalar_expression",
        inputSymbols: ["score", "threshold"],
        outputSymbols: ["precursor_margin"],
      },
    ],
    units: [{ symbol: "precursor_margin", unit: null, quantity: "diagnostic_margin", dimensionSignature: "1" }],
    assumptions: ["Diagnostic margin only.", "Requires a runtime receipt before interpretation."],
    calculatorPayloads: [
      payload({
        id: "tokamak_precursor_margin_payload",
        expression: "precursor_margin = score - threshold",
        displayLatex: "m_{precursor}=score-threshold",
        targetVariable: "precursor_margin",
      }),
    ],
    sourceRefs: [
      repoRef("shared/tokamak-precursor.ts", "TokamakPrecursorReport", "Precursor report contract."),
      repoRef("tools/tokamak-precursor-runner.ts", "tokamak precursor runner", "Runtime report generation path."),
    ],
    hintKeys: {
      subjects: ["tokamak", "precursor", "diagnostic", "threshold"],
      symbols: ["precursor_margin", "score", "threshold"],
      unitSignatures: ["1"],
      repoPaths: ["shared/tokamak-precursor.ts", "tools/tokamak-precursor-runner.ts"],
      equationFamilies: ["tokamak_precursor"],
      simulationOwners: ["tokamak"],
    },
  }),
  tokamakBadge({
    id: "tokamak.flux.core_fraction",
    title: "Tokamak Core Flux Fraction",
    plainMeaning: "Computes the fraction of valid grid cells assigned to the core flux band.",
    whyItMatters: "It provides a scalar helper for flux-band masks and energy-field coverage.",
    subjects: ["tokamak", "flux", "core", "rz_grid"],
    level: "simulation_specific",
    status: "project_derived",
    simulationOwners: ["tokamak"],
    equationFamilies: ["tokamak_flux_band"],
    tags: ["flux_band", "calculator_loadable"],
    equations: [
      {
        id: "core_fraction",
        role: "calculator_demo",
        displayLatex: "f_{core}=N_{core}/N_{total}",
        computableExpression: "core_fraction = core_count/total_count",
        operatorKind: "scalar_expression",
        inputSymbols: ["core_count", "total_count"],
        outputSymbols: ["core_fraction"],
      },
    ],
    units: [{ symbol: "core_fraction", unit: null, quantity: "fraction", dimensionSignature: "1" }],
    assumptions: ["Grid-count helper only.", "Flux coordinate construction is runtime context."],
    calculatorPayloads: [
      payload({
        id: "tokamak_core_fraction_payload",
        expression: "core_fraction = core_count/total_count",
        displayLatex: "f_{core}=N_{core}/N_{total}",
        targetVariable: "core_fraction",
      }),
    ],
    sourceRefs: [repoRef("shared/tokamak-flux-coords.ts", "buildFluxBandMasks", "Flux-band mask generation.")],
    hintKeys: {
      subjects: ["tokamak", "flux", "core", "rz_grid"],
      symbols: ["core_fraction", "core_count", "total_count"],
      unitSignatures: ["1"],
      repoPaths: ["shared/tokamak-flux-coords.ts"],
      equationFamilies: ["tokamak_flux_band"],
      simulationOwners: ["tokamak"],
    },
  }),
  tokamakBadge({
    id: "tokamak.flux.edge_fraction",
    title: "Tokamak Edge Flux Fraction",
    plainMeaning: "Computes the fraction of valid grid cells assigned to the edge flux band.",
    whyItMatters: "It gives the map a scalar row for edge/SOL coverage prompts.",
    subjects: ["tokamak", "flux", "edge", "rz_grid"],
    level: "simulation_specific",
    status: "project_derived",
    simulationOwners: ["tokamak"],
    equationFamilies: ["tokamak_flux_band"],
    tags: ["flux_band", "calculator_loadable"],
    equations: [
      {
        id: "edge_fraction",
        role: "calculator_demo",
        displayLatex: "f_{edge}=N_{edge}/N_{total}",
        computableExpression: "edge_fraction = edge_count/total_count",
        operatorKind: "scalar_expression",
        inputSymbols: ["edge_count", "total_count"],
        outputSymbols: ["edge_fraction"],
      },
    ],
    units: [{ symbol: "edge_fraction", unit: null, quantity: "fraction", dimensionSignature: "1" }],
    assumptions: ["Grid-count helper only.", "Flux coordinate construction is runtime context."],
    calculatorPayloads: [
      payload({
        id: "tokamak_edge_fraction_payload",
        expression: "edge_fraction = edge_count/total_count",
        displayLatex: "f_{edge}=N_{edge}/N_{total}",
        targetVariable: "edge_fraction",
      }),
    ],
    sourceRefs: [repoRef("shared/tokamak-flux-coords.ts", "buildFluxBandMasks", "Flux-band mask generation.")],
    hintKeys: {
      subjects: ["tokamak", "flux", "edge", "rz_grid"],
      symbols: ["edge_fraction", "edge_count", "total_count"],
      unitSignatures: ["1"],
      repoPaths: ["shared/tokamak-flux-coords.ts"],
      equationFamilies: ["tokamak_flux_band"],
      simulationOwners: ["tokamak"],
    },
  }),
  tokamakBadge({
    id: "tokamak.runtime.energy_field",
    title: "Tokamak RZ Energy Field Runtime",
    plainMeaning: "Reference node for RZ energy-field snapshots and channel weighting.",
    whyItMatters: "It keeps field/runtime artifacts visible without pretending they are scalar calculator solves.",
    subjects: ["tokamak", "runtime", "energy_field", "rz_grid"],
    level: "simulation_specific",
    status: "project_derived",
    simulationOwners: ["tokamak"],
    equationFamilies: ["tokamak_energy_field"],
    tags: ["runtime_reference"],
    equations: [
      {
        id: "rz_energy_field_reference",
        role: "noncomputable_reference",
        displayLatex: "u_{total}=\\sum_i w_i u_i(R,Z)",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["u_deltaB", "u_gradp", "u_J", "u_rad"],
        outputSymbols: ["u_total"],
      },
    ],
    units: [{ symbol: "u_total", unit: "J/m^3", quantity: "energy_density", dimensionSignature: "M L^-1 T^-2" }],
    assumptions: ["Runtime/reference context only.", "Requires field snapshot receipt for numeric interpretation."],
    calculatorPayloads: [],
    sourceRefs: [
      repoRef("shared/tokamak-energy-field.ts", "TokamakRZEnergySnapshot", "Runtime energy-field contract."),
      repoRef("server/services/essence/tokamak-energy-adapter.ts", "tokamak energy adapter", "Server adapter for energy-field context."),
    ],
    hintKeys: {
      subjects: ["tokamak", "runtime", "energy_field", "rz_grid"],
      symbols: ["u_total", "u_deltaB", "u_gradp", "u_J", "u_rad"],
      unitSignatures: ["M L^-1 T^-2"],
      repoPaths: ["shared/tokamak-energy-field.ts", "server/services/essence/tokamak-energy-adapter.ts"],
      equationFamilies: ["tokamak_energy_field"],
      simulationOwners: ["tokamak"],
    },
  }),
  tokamakBadge({
    id: "tokamak.runtime.synthetic_diagnostics",
    title: "Tokamak Synthetic Diagnostics Runtime",
    plainMeaning: "Reference node for bolometry, interferometry, and probe diagnostic reports.",
    whyItMatters: "It marks where diagnostic observations enter the tokamak branch.",
    subjects: ["tokamak", "runtime", "synthetic_diagnostics"],
    level: "diagnostic_gate",
    status: "diagnostic",
    simulationOwners: ["tokamak"],
    equationFamilies: ["tokamak_synthetic_diagnostics"],
    tags: ["runtime_reference", "diagnostic"],
    equations: [
      {
        id: "synthetic_report_reference",
        role: "noncomputable_reference",
        displayLatex: "D_{synthetic}=\\{bolometry,interferometry,probe\\}",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["bolometry", "interferometry", "probe"],
        outputSymbols: ["synthetic_report"],
      },
    ],
    units: [],
    assumptions: ["Runtime diagnostic report context only."],
    calculatorPayloads: [],
    sourceRefs: [
      repoRef("shared/tokamak-synthetic-diagnostics.ts", "TokamakSyntheticDiagnosticReport", "Synthetic diagnostic contract."),
    ],
    hintKeys: {
      subjects: ["tokamak", "synthetic_diagnostics", "runtime"],
      symbols: ["synthetic_report", "bolometry", "interferometry", "probe"],
      unitSignatures: [],
      repoPaths: ["shared/tokamak-synthetic-diagnostics.ts"],
      equationFamilies: ["tokamak_synthetic_diagnostics"],
      simulationOwners: ["tokamak"],
    },
  }),
  tokamakBadge({
    id: "tokamak.runtime.precursor_report",
    title: "Tokamak Precursor Report Runtime",
    plainMeaning: "Reference node for reduced precursor report generation and threshold context.",
    whyItMatters: "It keeps precursor reports separate from the calculator margin row.",
    subjects: ["tokamak", "runtime", "precursor", "diagnostic"],
    level: "diagnostic_gate",
    status: "diagnostic",
    simulationOwners: ["tokamak"],
    equationFamilies: ["tokamak_precursor"],
    tags: ["runtime_reference", "precursor"],
    equations: [
      {
        id: "precursor_report_reference",
        role: "noncomputable_reference",
        displayLatex: "R_{precursor}=runtime(score,features)",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: ["score", "features"],
        outputSymbols: ["precursor_report"],
      },
    ],
    units: [],
    assumptions: ["Runtime diagnostic report context only.", "Score thresholds require calibrated receipts."],
    calculatorPayloads: [],
    sourceRefs: [
      repoRef("shared/tokamak-precursor.ts", "TokamakPrecursorReport", "Precursor report contract."),
      repoRef("server/routes/physics.tokamak.ts", "tokamak precursor route", "Tokamak route surface."),
    ],
    hintKeys: {
      subjects: ["tokamak", "precursor", "runtime", "diagnostic"],
      symbols: ["precursor_report", "score", "threshold"],
      unitSignatures: ["1"],
      repoPaths: ["shared/tokamak-precursor.ts", "server/routes/physics.tokamak.ts"],
      equationFamilies: ["tokamak_precursor"],
      simulationOwners: ["tokamak"],
    },
  }),
  tokamakBadge({
    id: "tokamak.claim_boundary.diagnostic_proxy",
    title: "Tokamak Diagnostic Proxy Boundary",
    plainMeaning: "Keeps tokamak calculator rows and runtime references in diagnostic/proxy scope.",
    whyItMatters: "It prevents pressure, beta, energy-field, or precursor rows from being overstated.",
    subjects: ["tokamak", "claim_boundary", "diagnostic"],
    level: "claim_boundary",
    status: "blocked",
    simulationOwners: ["tokamak"],
    equationFamilies: ["tokamak_claim_boundary"],
    tags: ["claim_boundary"],
    equations: [
      {
        id: "tokamak_boundary_reference",
        role: "noncomputable_reference",
        displayLatex: "\\mathrm{diagnostic\\ proxy\\ only}",
        computableExpression: null,
        operatorKind: "noncomputable_reference",
        inputSymbols: [],
        outputSymbols: ["claim_boundary"],
      },
    ],
    units: [],
    assumptions: [
      "Calculator rows are reduced diagnostic helpers.",
      "Tokamak runtime receipts are required before interpreting plasma-state outputs.",
      "No scalar row establishes plasma stability, disruption prediction, or control authority.",
    ],
    calculatorPayloads: [],
    sourceRefs: [
      repoRef("shared/tokamak-sim.ts", "TokamakSimState", "Tokamak runtime state contract."),
      repoRef("shared/tokamak-precursor.ts", "TokamakPrecursorReport", "Precursor report boundary context."),
      docRef("docs/knowledge/physics/tokamak", undefined, "Tokamak knowledge/context notes where present."),
    ],
    hintKeys: {
      subjects: ["tokamak", "claim_boundary", "diagnostic"],
      symbols: ["claim_boundary"],
      unitSignatures: [],
      repoPaths: ["shared/tokamak-sim.ts", "shared/tokamak-precursor.ts"],
      equationFamilies: ["tokamak_claim_boundary"],
      simulationOwners: ["tokamak"],
    },
  }),
];

export const TOKAMAK_PLASMA_THEORY_EDGES: TheoryBadgeEdgeV1[] = [
  {
    id: "energy_density_supports_tokamak_magnetic_pressure",
    from: "physics.energy.energy_density",
    to: "tokamak.plasma.magnetic_pressure",
    relation: "requires",
    label: "Magnetic pressure is an energy-density/pressure scalar row.",
    claimBoundaryNote: "Pressure support remains a diagnostic scalar context.",
  },
  {
    id: "energy_density_supports_tokamak_thermal_pressure",
    from: "physics.energy.energy_density",
    to: "tokamak.plasma.thermal_pressure_proxy",
    relation: "requires",
    label: "Thermal pressure uses the same stress-energy unit family.",
    claimBoundaryNote: "Thermal pressure is a reduced scalar proxy.",
  },
  {
    id: "tokamak_magnetic_pressure_feeds_beta",
    from: "tokamak.plasma.magnetic_pressure",
    to: "tokamak.plasma.beta_proxy",
    relation: "derives",
    label: "Beta compares thermal pressure against magnetic pressure.",
    claimBoundaryNote: "Beta is not a stability certificate.",
  },
  {
    id: "tokamak_thermal_pressure_feeds_beta",
    from: "tokamak.plasma.thermal_pressure_proxy",
    to: "tokamak.plasma.beta_proxy",
    relation: "derives",
    label: "Beta requires thermal pressure.",
    claimBoundaryNote: "Beta remains a reduced diagnostic row.",
  },
  {
    id: "power_rate_supports_tokamak_power_balance",
    from: "physics.energy.power_rate",
    to: "tokamak.energy.power_balance",
    relation: "requires",
    label: "Power balance is a project-specific power-rate row.",
    claimBoundaryNote: "Power accounting does not establish confinement quality.",
  },
  {
    id: "tokamak_power_balance_feeds_energy_field",
    from: "tokamak.energy.power_balance",
    to: "tokamak.runtime.energy_field",
    relation: "documents",
    label: "Power balance is adjacent context for RZ energy fields.",
    claimBoundaryNote: "Energy-field interpretation requires runtime receipts.",
  },
  {
    id: "tokamak_confinement_feeds_energy_field",
    from: "tokamak.energy.confinement_time_proxy",
    to: "tokamak.runtime.energy_field",
    relation: "documents",
    label: "Confinement proxy documents energy-field context.",
    claimBoundaryNote: "Transport modeling is outside the scalar calculator row.",
  },
  {
    id: "tokamak_energy_field_documents_synthetic_diagnostics",
    from: "tokamak.runtime.energy_field",
    to: "tokamak.runtime.synthetic_diagnostics",
    relation: "documents",
    label: "Synthetic diagnostics consume runtime field context.",
    claimBoundaryNote: "Diagnostic receipts are required before interpretation.",
  },
  {
    id: "tokamak_synthetic_diagnostics_feed_precursor_report",
    from: "tokamak.runtime.synthetic_diagnostics",
    to: "tokamak.runtime.precursor_report",
    relation: "diagnostic_checks",
    label: "Synthetic diagnostic outputs can feed precursor reports.",
    claimBoundaryNote: "Precursor rows are diagnostic only.",
  },
  {
    id: "tokamak_precursor_margin_checks_precursor_report",
    from: "tokamak.precursor.score_margin",
    to: "tokamak.runtime.precursor_report",
    relation: "diagnostic_checks",
    label: "Score-threshold margin documents precursor report context.",
    claimBoundaryNote: "Margin is not a validated prediction.",
  },
  {
    id: "tokamak_core_fraction_documents_energy_field",
    from: "tokamak.flux.core_fraction",
    to: "tokamak.runtime.energy_field",
    relation: "documents",
    label: "Core flux fraction documents energy-field coverage.",
    claimBoundaryNote: "Flux bands are runtime mask context.",
  },
  {
    id: "tokamak_edge_fraction_documents_energy_field",
    from: "tokamak.flux.edge_fraction",
    to: "tokamak.runtime.energy_field",
    relation: "documents",
    label: "Edge flux fraction documents energy-field coverage.",
    claimBoundaryNote: "Flux bands are runtime mask context.",
  },
  {
    id: "tokamak_beta_documents_boundary",
    from: "tokamak.plasma.beta_proxy",
    to: "tokamak.claim_boundary.diagnostic_proxy",
    relation: "documents",
    label: "Beta rows must point to tokamak diagnostic scope.",
    claimBoundaryNote: "Beta is a proxy row only.",
  },
  {
    id: "tokamak_precursor_blocks_validation",
    from: "tokamak.runtime.precursor_report",
    to: "tokamak.claim_boundary.diagnostic_proxy",
    relation: "blocks",
    label: "Precursor reports cannot be promoted without validation receipts.",
    claimBoundaryNote: "Precursor outputs stay diagnostic/proxy scoped.",
  },
];

export function buildTokamakPlasmaTheoryBadgesV1(): {
  badges: TheoryBadgeV1[];
  edges: TheoryBadgeEdgeV1[];
} {
  return {
    badges: TOKAMAK_PLASMA_THEORY_BADGES,
    edges: TOKAMAK_PLASMA_THEORY_EDGES,
  };
}
