import type { MoralWisdomPrinciple } from "../principle-types";

export const CIVIC_ORDER_MORAL_PRINCIPLES: readonly MoralWisdomPrinciple[] = [
  {
    id: "participation-consent-separation",
    sourceIdeologyNodeId: "participation-consent-separation",
    label: "Participation-Consent Separation",
    glyph: "P",
    summary: "Participation, use, payment, dependence, and compliance do not by themselves establish consent.",
    proceduralRole: "evidence_requirement",
    procedureOperator: "requires",
    proceduralRule: "Require explicit consent evidence before treating participation as endorsement or agreement.",
    traceBehavior: "Trace participation functions, dependency, alternatives, and the actual consent statement separately.",
    actionEffect: "Hold consent as unknown or constrained until direct evidence supports a stronger state.",
    evidenceNeeds: ["participation_functions", "dependency_context", "consent_statement", "available_alternatives"],
    refusesAuthority: ["participation_as_consent", "payment_as_endorsement", "dependence_as_loyalty"],
    tags: ["civic_order", "participation", "consent", "dependency", "anti_inference"],
  },
  {
    id: "inherited-order-participation",
    sourceIdeologyNodeId: "inherited-order-participation",
    label: "Inherited Order Participation",
    glyph: "I",
    summary: "Separate inherited entry into an order from a person's present chosen position within it.",
    proceduralRole: "balancer",
    procedureOperator: "balances",
    proceduralRule: "Represent birth, residence, employment, contract, migration, or membership entry before interpreting current participation.",
    traceBehavior: "Trace entry mode, maturation context, alternatives at entry, and present chosen position.",
    actionEffect: "Prevent inherited presence from being read as permanent endorsement or identity.",
    evidenceNeeds: ["entry_mode", "maturation_context", "alternatives_at_entry", "present_chosen_position"],
    refusesAuthority: ["birth_as_consent", "inheritance_as_identity", "presence_as_endorsement"],
    tags: ["civic_order", "inheritance", "conditioning", "participation", "identity"],
  },
  {
    id: "proximity-norm-reciprocity",
    sourceIdeologyNodeId: "proximity-norm-reciprocity",
    label: "Proximity, Norm, and Reciprocity",
    glyph: "N",
    summary: "Inspect how local proximity, custom, enforcement, and reciprocity reproduce a norm.",
    proceduralRole: "balancer",
    procedureOperator: "balances",
    proceduralRule: "Separate descriptive custom from expectation, codification, enforcement, contestation, and drift.",
    traceBehavior: "Trace norm source, scope, affected parties, exceptions, enforcement, dissent, and review.",
    actionEffect: "Keep local regularity descriptive until reciprocal effects and contestability are visible.",
    evidenceNeeds: ["norm_source", "norm_status", "affected_parties", "enforcement_channels", "dissent_path"],
    refusesAuthority: ["custom_as_justice", "proximity_as_legitimacy", "regularity_as_universal_rule"],
    tags: ["civic_order", "norms", "proximity", "reciprocity", "contestability"],
  },
  {
    id: "voice-exit-contestability",
    sourceIdeologyNodeId: "voice-exit-contestability",
    label: "Voice, Exit, and Contestability",
    glyph: "V",
    summary: "Distinguish formal voice or exit from paths that are usable without disproportionate cost or retaliation.",
    proceduralRole: "action_gate",
    procedureOperator: "requires",
    proceduralRule: "Require feasible voice, exit, appeal, repair, or re-entry evidence before treating participation as voluntary.",
    traceBehavior: "Trace formal paths, actual costs, alternatives, retaliation risk, repair, and re-entry.",
    actionEffect: "Block voluntary-participation claims when formal options are not feasible in practice.",
    evidenceNeeds: ["voice_path", "formal_exit_path", "feasible_exit_evidence", "retaliation_risk", "repair_or_reentry_path"],
    refusesAuthority: ["formal_exit_as_feasible_exit", "dissent_as_nonparticipation", "retaliation_blind_choice"],
    tags: ["civic_order", "voice", "exit", "appeal", "repair", "action_gate"],
  },
  {
    id: "adherence-legitimacy-separation",
    sourceIdeologyNodeId: "adherence-legitimacy-separation",
    label: "Adherence-Legitimacy Separation",
    glyph: "L",
    summary: "Popularity, compliance, stability, and repeated adherence do not establish legitimacy or justice.",
    proceduralRole: "constraint",
    procedureOperator: "constrains",
    proceduralRule: "Constrain legitimacy claims until reasons, rights, contestability, jurisdiction, and review are evidenced.",
    traceBehavior: "Trace support signals separately from coercion, necessity, rights, reasons, and review paths.",
    actionEffect: "Downgrade legitimacy language to descriptive adherence when justificatory evidence is missing.",
    evidenceNeeds: ["support_signal", "rights_context", "justification", "contestability_path", "review_path"],
    refusesAuthority: ["popularity_as_legitimacy", "stability_as_justice", "compliance_as_approval"],
    tags: ["civic_order", "legitimacy", "adherence", "justice", "due_process"],
  },
  {
    id: "coordination-pluralism",
    sourceIdeologyNodeId: "coordination-pluralism",
    label: "Coordination Pluralism",
    glyph: "C",
    summary: "Decompose labeled orders into the allocation, authority, and accountability channels actually in use.",
    proceduralRole: "balancer",
    procedureOperator: "balances",
    proceduralRule: "Represent multiple coordination channels without treating an ideology label as a complete mechanism or ranking.",
    traceBehavior: "Trace each channel's role, evidence, jurisdiction, fallback, and interaction with the others.",
    actionEffect: "Route comparisons toward mechanism profiles rather than universal ideology winners.",
    evidenceNeeds: ["allocation_channels", "authority_channels", "accountability_channels", "channel_roles"],
    refusesAuthority: ["ideology_label_as_mechanism", "single_mode_totalization", "ideology_rank"],
    tags: ["civic_order", "coordination", "pluralism", "allocation", "authority", "accountability"],
  },
];
