import type { MoralWisdomPrinciple } from "../principle-types";

export const PROVISIONING_MORAL_PRINCIPLES: readonly MoralWisdomPrinciple[] = [
  {
    id: "need-before-allocation",
    sourceIdeologyNodeId: "need-before-allocation",
    label: "Need Before Allocation",
    glyph: "N",
    summary: "Identify bounded viability needs and affected agents before choosing an allocation procedure.",
    proceduralRole: "first_principle",
    procedureOperator: "requires",
    proceduralRule: "Require need, threshold, coverage, affected-agent, and time-horizon evidence before allocation claims.",
    traceBehavior: "Trace the need primitive into provisioning functions without deriving policy from biology.",
    actionEffect: "Start provisioning reflection from evidenced continuity requirements rather than a preferred budget or ideology.",
    evidenceNeeds: ["need_primitive", "viability_threshold", "present_coverage", "affected_agents", "time_horizon"],
    refusesAuthority: ["biology_as_policy", "universal_budget", "need_claim_without_boundary"],
    tags: ["provisioning", "viability", "need", "coverage", "first_principle"],
  },
  {
    id: "efficiency-without-erasure",
    sourceIdeologyNodeId: "efficiency-without-erasure",
    label: "Efficiency Without Erasure",
    glyph: "E",
    summary: "Treat efficiency as a vector of flows, losses, resilience, rights, maintenance, and distribution rather than one score.",
    proceduralRole: "constraint",
    procedureOperator: "constrains",
    proceduralRule: "Constrain efficiency claims to an explicit lens and retain affected groups, externalities, and missing evidence.",
    traceBehavior: "Trace quantity, unit, loss, latency, reliability, buffer, substitute, burden, benefit, and rights checks.",
    actionEffect: "Replace scalar winners with lens-specific evidence and Pareto tradeoffs.",
    evidenceNeeds: ["selected_lens", "flow_measurements", "externalities", "burden_groups", "beneficiary_groups"],
    refusesAuthority: ["overall_efficiency_score", "civilization_balance_score", "distribution_erasure"],
    tags: ["provisioning", "efficiency", "vector", "distribution", "anti_scalar"],
  },
  {
    id: "mandate-bounded-hierarchy",
    sourceIdeologyNodeId: "mandate-bounded-hierarchy",
    label: "Mandate-Bounded Hierarchy",
    glyph: "H",
    summary: "Delegated authority must remain bounded by function, evidence, safety, review, exit, and retraining paths.",
    proceduralRole: "action_gate",
    procedureOperator: "requires",
    proceduralRule: "Require demand evidence and a bounded mandate before role specialization carries authority.",
    traceBehavior: "Trace assignment mode, authority scope, compensation, safety, exit, retraining, and review.",
    actionEffect: "Block role authority from expanding beyond its evidenced function and review lifecycle.",
    evidenceNeeds: ["demand_evidence", "assignment_mode", "authority_scope", "safety_checks", "review_path"],
    refusesAuthority: ["specialization_as_unbounded_power", "role_as_personal_worth", "opaque_mandate"],
    tags: ["provisioning", "hierarchy", "mandate", "role", "review", "action_gate"],
  },
  {
    id: "legible-rules-bounded-confidentiality",
    sourceIdeologyNodeId: "legible-rules-bounded-confidentiality",
    label: "Legible Rules, Bounded Confidentiality",
    glyph: "R",
    summary: "Keep governing rules, burdens, and review paths legible while limiting confidentiality to a justified scope.",
    proceduralRole: "constraint",
    procedureOperator: "constrains",
    proceduralRule: "Require public rule boundaries and a reviewable reason before confidentiality can hide operational evidence.",
    traceBehavior: "Trace which information is withheld, from whom, for what risk, for how long, and under which review.",
    actionEffect: "Preserve necessary confidentiality without allowing secrecy to become unaccountable privilege.",
    evidenceNeeds: ["published_rules", "confidentiality_scope", "risk_justification", "review_or_sunset"],
    refusesAuthority: ["secret_privilege", "confidentiality_without_scope", "opaque_allocation_rule"],
    tags: ["provisioning", "legibility", "confidentiality", "transparency", "review"],
  },
  {
    id: "cooperation-without-assimilation",
    sourceIdeologyNodeId: "cooperation-without-assimilation",
    label: "Cooperation Without Assimilation",
    glyph: "K",
    summary: "Cross-jurisdiction cooperation should preserve distinct agency, standards negotiation, dispute, and continuity paths.",
    proceduralRole: "balancer",
    procedureOperator: "balances",
    proceduralRule: "Require contributions, benefits, maintenance, knowledge policy, dispute, and exit evidence for shared projects.",
    traceBehavior: "Trace each jurisdiction's contribution, benefit, retained agency, standards, disputes, and continuity obligations.",
    actionEffect: "Support shared capacity without treating coordination as cultural or political assimilation.",
    evidenceNeeds: ["participating_jurisdictions", "contribution_map", "benefit_map", "maintenance_commitments", "dispute_and_exit_paths"],
    refusesAuthority: ["cooperation_as_assimilation", "shared_project_as_superiority", "exitless_coordination"],
    tags: ["provisioning", "cooperation", "jurisdiction", "pluralism", "non_domination"],
  },
  {
    id: "specialization-without-caste",
    sourceIdeologyNodeId: "specialization-without-caste",
    label: "Specialization Without Caste",
    glyph: "S",
    summary: "Treat specialization as a revisable function assignment, not a fixed identity or rank of human worth.",
    proceduralRole: "constraint",
    procedureOperator: "constrains",
    proceduralRule: "Require mobility, safety, compensation, retraining, exit, and review before stabilizing a specialized role.",
    traceBehavior: "Trace how a role is assigned, supported, revised, exited, and prevented from becoming inherited status.",
    actionEffect: "Constrain useful specialization from hardening into permanent caste or identity verdict.",
    evidenceNeeds: ["assignment_mode", "mobility_path", "safety_and_compensation", "retraining_path", "review_date"],
    refusesAuthority: ["role_as_caste", "occupation_as_human_worth", "inherited_status_without_review"],
    tags: ["provisioning", "specialization", "mobility", "anti_caste", "dignity"],
  },
];
