export {
  WORKSTATION_DYNAMIC_TOOL_ACTIONS,
  WORKSPACE_ACTION_REGISTRY,
  buildWorkstationDynamicTools,
  buildWorkstationDynamicToolSpec,
  buildWorkstationToolInputSchema,
  buildWorkstationToolName,
  findWorkstationDynamicTool,
  mapWorkstationDynamicToolCallToAction,
  resolveWorkstationToolTerminalArtifactKind,
  type WorkspaceActionRegistryEntry,
  type WorkstationDynamicToolActionDefinition,
  type WorkstationDynamicToolCallMapping,
  type WorkstationDynamicToolSpec,
} from "@shared/workstation-dynamic-tools";
