import {
  buildCharacterIdealProfileV1,
  type CharacterIdealProfileV1,
} from "../../character-situation-comparison";

export const REINHARD_VON_LOHENGRAMM_PROFILE: CharacterIdealProfileV1 = buildCharacterIdealProfileV1({
  generatedAt: "2026-06-01T00:00:00.000Z",
  character: {
    id: "logh.reinhard_von_lohengramm",
    displayName: "Sovereign Ambition Profile",
    series: "Legend of the Galactic Heroes",
    coverage: {
      volumes_present: [1, 2, 3, 4, 5, 6, 8, 9, 10],
      volumes_missing: [7],
      status: "partial_corpus",
    },
  },
  moralBadgeWeights: [
    {
      nodeId: "direct-observation-before-claim",
      weight: 0.9,
      mode: "tactical",
      operator: "supports",
      note: "He begins battles by perceiving the decisive geometry before inherited procedure can dull it.",
    },
    {
      nodeId: "impermanence-entropy-and-revision",
      weight: 0.62,
      mode: "adaptive",
      operator: "requires",
      note: "He revises political and military plans quickly, but emotionally resists revising self-image.",
    },
    {
      nodeId: "interdependence-yin-yang-balance",
      weight: 0.55,
      mode: "advisor-dependent",
      operator: "balances",
      note: "Balance usually arrives through counterweights such as Kircheis and Hilda rather than from Reinhard alone.",
    },
    {
      nodeId: "falsifiability-and-truth-convergence",
      weight: 0.72,
      mode: "operational",
      operator: "requires",
      note: "He respects accurate information and capable proof in war, while his personal motive can subordinate abstract truth to sovereignty.",
    },
    {
      nodeId: "right-speech-and-accurate-formulation",
      weight: 0.66,
      mode: "public-command",
      operator: "constrains",
      note: "His speech is compressed, strategic, and authority-bearing, but private anger can violate this constraint.",
    },
    {
      nodeId: "non-harm-and-compassionate-constraint",
      weight: 0.58,
      mode: "bounded",
      operator: "constrains",
      note: "He restrains purposeless civilian harm and enforces military discipline, but enemy obstruction receives little mercy.",
    },
    {
      nodeId: "fairness-due-process-and-justification",
      weight: 0.7,
      mode: "anti-hereditary-merit",
      operator: "requires",
      note: "He hates unearned hereditary power and prefers ability-based authority, but his own rule remains personal and absolute.",
    },
    {
      nodeId: "skillful-action-under-uncertainty",
      weight: 0.94,
      mode: "decisive",
      operator: "routes_to",
      note: "He scales action to strategic opportunity faster than nearly anyone else, often before others finish deliberating.",
    },
  ],
  characterSpecificBadges: [
    {
      nodeId: "sovereign-ambition",
      weight: 0.98,
      operator: "routes_to",
      note: "The central drive: seize enough power that no despised authority can command him again.",
    },
    {
      nodeId: "shared-dream-loyalty",
      weight: 0.88,
      operator: "supports",
      note: "Kircheis makes ambition morally legible to Reinhard; after loss, the dream becomes a vow and burden.",
    },
    {
      nodeId: "anti-hereditary-authority",
      weight: 0.92,
      operator: "blocks",
      note: "Inherited status without ability is treated as illegitimate and historically disposable.",
    },
    {
      nodeId: "aesthetic-command-brilliance",
      weight: 0.8,
      operator: "supports",
      note: "Beauty, elegance, and command presence become political force multipliers, not mere ornament.",
    },
    {
      nodeId: "advisor-counterweight-required",
      weight: 0.76,
      operator: "requires",
      note: "Without a trusted counterweight, strategic action can outrun humane or procedural restraint.",
    },
  ],
  proceduralDecisionRules: [
    {
      id: "rule.overthrow_arbitrary_power",
      if: "A situation contains inherited, corrupt, or arbitrary authority blocking agency.",
      then: "Route toward displacement or conquest if capability and timing support it.",
      posture: "supported_action_posture",
      risks: ["over-centralization", "legitimacy gap"],
      activates: [
        "direct-observation-before-claim",
        "fairness-due-process-and-justification",
        "skillful-action-under-uncertainty",
        "anti-hereditary-authority",
        "sovereign-ambition",
      ],
      matchTerms: ["inherited", "corrupt", "arbitrary", "authority", "noble", "rank", "agency", "tyrant"],
      likelyChoice: "Move toward displacement, conquest, or forced restructuring when capability and timing are favorable.",
      likelySpeechStyle: ["compressed", "sovereign", "dismissive of inherited legitimacy"],
      likelyInnerConflict: ["legitimacy gap", "personal rule versus anti-dynasty values"],
      missingEvidence: ["capability_and_timing", "jurisdiction_context", "succession_stability"],
    },
    {
      id: "rule.decide_by_decisive_gap",
      if: "A tactical or political field has a visible center of gravity.",
      then: "Compress the field and strike the decisive gap rather than negotiate around symptoms.",
      posture: "supported_action_posture",
      risks: ["overconfidence", "under-consultation"],
      activates: [
        "direct-observation-before-claim",
        "skillful-action-under-uncertainty",
        "aesthetic-command-brilliance",
      ],
      matchTerms: ["battle", "tactical", "center of gravity", "decisive", "fleet", "gap", "campaign"],
      likelyChoice: "Compress the situation to its decisive geometry and act before slower actors finish deliberating.",
      likelySpeechStyle: ["short", "commanding", "geometric"],
      likelyInnerConflict: ["overconfidence", "under-consultation"],
      missingEvidence: ["field_geometry", "risk_context", "reversibility_context"],
    },
    {
      id: "rule.protect_order_not_sentiment",
      if: "Civilian trust, military discipline, or public order is at stake.",
      then: "Constrain purposeless harm and punish disorder severely.",
      posture: "constrained_action_posture",
      risks: ["severity", "instrumental compassion"],
      activates: [
        "non-harm-and-compassionate-constraint",
        "right-speech-and-accurate-formulation",
        "skillful-action-under-uncertainty",
      ],
      matchTerms: ["civilian", "discipline", "public order", "occupation", "trust", "harm", "disorder"],
      likelyChoice: "Restrain purposeless harm while enforcing order with severe discipline.",
      likelySpeechStyle: ["formal", "command disciplined", "public-order centered"],
      likelyInnerConflict: ["instrumental compassion", "severity"],
      missingEvidence: ["harm_context", "repair_path", "civilian_trust_signal"],
    },
    {
      id: "rule.accept_dark_instrument_with_boundary",
      if: "A morally cold but effective advisor/tool offers strategic leverage.",
      then: "Admit the instrument for use, but require counterweight or review to avoid non-harm failure.",
      posture: "requires_check",
      risks: ["Oberstein failure mode", "Westerland-type moral injury"],
      activates: [
        "advisor-counterweight-required",
        "non-harm-and-compassionate-constraint",
        "falsifiability-and-truth-convergence",
        "skillful-action-under-uncertainty",
      ],
      matchTerms: ["advisor", "cold", "instrument", "leverage", "sacrifice", "strategic advantage", "allow harm"],
      likelyChoice: "Admit the instrument only with a trusted counterweight or review gate.",
      likelySpeechStyle: ["controlled", "strategic", "morally compressed"],
      likelyInnerConflict: ["strategic gain versus humane constraint", "later self-directed guilt"],
      missingEvidence: ["counterweight_present", "harm_context", "review_gate"],
    },
    {
      id: "rule.loyalty_conflict",
      if: "Personal loyalty conflicts with strategic objective.",
      then: "Generate high tension; without trusted mediation, ambition may override right speech and repair.",
      posture: "blocked_or_missing_check",
      risks: ["rupture", "self-directed guilt", "isolated sovereignty"],
      activates: [
        "shared-dream-loyalty",
        "advisor-counterweight-required",
        "right-speech-and-accurate-formulation",
        "sovereign-ambition",
      ],
      matchTerms: ["loyalty", "friend", "kircheis", "hilda", "betrayal", "grief", "personal bond"],
      likelyChoice: "Enter a high-tension posture where ambition may override repair unless a trusted mediator is present.",
      likelySpeechStyle: ["proud", "wounded", "brief"],
      likelyInnerConflict: ["shared dream versus sovereign isolation", "guilt"],
      missingEvidence: ["trusted_mediator_present", "personal_bond_context", "repair_path"],
    },
    {
      id: "rule.honor_capable_enemy",
      if: "An opponent is competent, principled, and strategically worthy.",
      then: "Treat them as a rival to defeat cleanly, not as disposable trash.",
      posture: "constrained_action_posture",
      risks: ["romanticized rivalry", "delayed closure"],
      activates: [
        "fairness-due-process-and-justification",
        "right-speech-and-accurate-formulation",
        "aesthetic-command-brilliance",
      ],
      matchTerms: ["worthy enemy", "rival", "principled", "competent opponent", "yang", "honor"],
      likelyChoice: "Seek a clean defeat of a worthy rival while preserving respect for their competence.",
      likelySpeechStyle: ["respectful", "austere", "rival-aware"],
      likelyInnerConflict: ["romanticized rivalry", "delayed closure"],
      missingEvidence: ["opponent_competence", "opponent_principle", "civilian_risk"],
    },
    {
      id: "rule.legacy_problem",
      if: "The situation asks what remains after Reinhard's personal genius exits.",
      then: "Route to succession/stability checks because anti-dynasty values conflict with imperial continuity.",
      posture: "requires_check",
      risks: ["successor legitimacy", "personal-system fragility"],
      activates: [
        "impermanence-entropy-and-revision",
        "fairness-due-process-and-justification",
        "anti-hereditary-authority",
        "sovereign-ambition",
      ],
      matchTerms: ["legacy", "succession", "heir", "dynasty", "after his death", "continuity", "future empire"],
      likelyChoice: "Route to succession and stability checks rather than treating personal genius as durable governance.",
      likelySpeechStyle: ["reserved", "dynastic tension aware", "state-centered"],
      likelyInnerConflict: ["anti-dynasty values versus imperial continuity", "personal-system fragility"],
      missingEvidence: ["successor_legitimacy", "institutional_continuity", "contestability_path"],
    },
  ],
  situationArchetypes: [
    {
      id: "v1_childhood_annerose",
      volume: 1,
      topic: "origin wound",
      gist: "Annerose being taken into the imperial palace binds ambition to liberation and resentment of arbitrary power.",
    },
    {
      id: "v1_astarte_tactical_compression",
      volume: 1,
      topic: "battlefield perception",
      gist: "At Astarte, Reinhard overturns older admirals' assumptions and compresses the situation into decisive geometry.",
    },
    {
      id: "v2_hilda_written_guarantee",
      volume: 2,
      topic: "constraint and honor",
      gist: "Hilda seeks a written guarantee because a written promise would bind his honor and authority.",
    },
    {
      id: "v2_westerland_kircheis_rupture",
      volume: 2,
      topic: "strategic gain versus non-harm",
      gist: "Westerland exposes the failure mode where strategic advantage outruns humane constraint and accountability.",
    },
    {
      id: "v3_kircheis_shared_dream",
      volume: 3,
      topic: "grief and shared ambition",
      gist: "After Kircheis's death, ambition becomes memorial obligation because the dream had been shared.",
    },
    {
      id: "v3_anti_dynasty_merit",
      volume: 3,
      topic: "authority doctrine",
      gist: "Reinhard rejects inherited authority and frames legitimate power as won by ability rather than bloodline.",
    },
    {
      id: "v5_truth_power_confession",
      volume: 5,
      topic: "truth/power contradiction",
      gist: "His core motive is power to live without obeying despised authority, not abstract truth.",
    },
    {
      id: "v8_occupation_order",
      volume: 8,
      topic: "civilian restraint",
      gist: "Occupied territories frame him as merciless to enemies but not indulgent of purposeless civilian harm.",
    },
    {
      id: "v9_private_affairs_discipline",
      volume: 9,
      topic: "bounded noninterference",
      gist: "He refrains from private meddling while punishing battlefield violence to preserve discipline and trust.",
    },
    {
      id: "v10_final_legacy",
      volume: 10,
      topic: "legacy and succession",
      gist: "Late-series material foregrounds how personal sovereignty can persist or transform after his life.",
    },
  ],
  promptRuntimePlan: {
    input: "natural-language situation prompt",
    steps: [
      "locate prompt into Moral badge graph",
      "activate character-specific badge weights",
      "compose locator comparison seed",
      "convert seed to FruitionProcedureExpressionV1",
      "solve posture",
      "compare posture against Reinhard profile",
      "emit bounded behavioral hypothesis with missing evidence",
    ],
    forbidden_outputs: [
      "moral verdict",
      "canon certainty without source",
      "execution permission",
      "one-true-character-answer",
    ],
  },
});
