import express from "express";
import request from "supertest";
import { planRouter } from "./server/routes/agi.plan";
const app = express(); app.use(express.json()); app.use("/api/agi", planRouter);
const sessionId = `debug-inspect-testenv-${Date.now()}`;
const prompt = "Use calculator compute frequency from 500 nm then energy J then eV";
const prior = await request(app).post("/api/agi/ask/turn").send({ question: prompt, mode: "read", sessionId, debug: true });
console.log("answer\n", prior.body.text);
console.log("validations", prior.body.calculator_result_validations?.map((v:any)=>v));
console.log("coverage", prior.body.calculator_plan_coverage);
console.log("final draft", prior.body.final_answer_draft?.text);
const ledger = prior.body.current_turn_artifact_ledger || [];
console.log("ledger kinds", ledger.map((a:any)=>a.kind));
for (const a of ledger) if (["final_answer_draft","calculator_result_validations","calculator_plan_coverage"].includes(a.kind)) console.log(a.kind, JSON.stringify(a.payload).slice(0,1000));
