export type WorkstationPanelActionRisk = "low" | "medium" | "high";

export type WorkstationPanelActionDefinition = {
  id: string;
  title: string;
  description: string;
  risk: WorkstationPanelActionRisk;
  aliases?: string[];
  required_args?: string[];
  optional_args?: string[];
  requires_confirmation?: boolean;
  returns_artifact?: boolean;
};

export type WorkstationPanelCapabilities = {
  version: 1;
  can_read_state: boolean;
  can_run_action: boolean;
  safe_actions: string[];
  requires_confirmation_actions: string[];
  returns_artifact_actions: string[];
  v1_job_ready: boolean;
  actions: WorkstationPanelActionDefinition[];
};

const EMPTY_CAPABILITIES: WorkstationPanelCapabilities = {
  version: 1,
  can_read_state: false,
  can_run_action: false,
  safe_actions: [],
  requires_confirmation_actions: [],
  returns_artifact_actions: [],
  v1_job_ready: false,
  actions: [],
};

function makeCapabilities(
  input: Partial<WorkstationPanelCapabilities> & Pick<WorkstationPanelCapabilities, "actions">,
): WorkstationPanelCapabilities {
  const actions = input.actions ?? [];
  const safeActions =
    input.safe_actions ??
    actions.filter((action) => action.risk === "low").map((action) => action.id);
  const requiresConfirmation =
    input.requires_confirmation_actions ??
    actions.filter((action) => action.requires_confirmation).map((action) => action.id);
  const returnsArtifact =
    input.returns_artifact_actions ??
    actions.filter((action) => action.returns_artifact).map((action) => action.id);

  return {
    ...EMPTY_CAPABILITIES,
    ...input,
    actions,
    safe_actions: safeActions,
    requires_confirmation_actions: requiresConfirmation,
    returns_artifact_actions: returnsArtifact,
  };
}

export const WORKSTATION_V1_PANEL_CAPABILITIES: Record<string, WorkstationPanelCapabilities> = {
  "docs-viewer": makeCapabilities({
    can_read_state: true,
    can_run_action: true,
    v1_job_ready: true,
    actions: [
      {
        id: "open",
        title: "Open Docs Viewer",
        description: "Open and focus the Docs Viewer panel.",
        risk: "low",
        aliases: [
          "open docs",
          "show docs",
          "view docs",
          "open docs viewer",
          "go to docs",
          "switch to docs",
          "switch over to docs",
          "jump to docs",
          "jump over to docs",
          "jump over to docs viewer",
        ],
      },
      {
        id: "open_doc",
        title: "Open Document",
        description: "Open a local docs path (optionally with anchor) in the Docs Viewer panel.",
        risk: "low",
        aliases: ["open doc", "open document", "view doc", "show document"],
        required_args: ["path"],
        optional_args: ["anchor"],
        returns_artifact: true,
      },
      {
        id: "open_doc_by_path",
        title: "Open Document By Path",
        description: "Open a concrete local docs path in the Docs Viewer panel.",
        risk: "low",
        aliases: ["open docs path", "open this doc path", "open file in docs"],
        required_args: ["path"],
        optional_args: ["anchor"],
        returns_artifact: true,
      },
      {
        id: "open_latest_doc_by_topic",
        title: "Open Latest Document By Topic",
        description: "Resolve and open the latest local document matching a topic.",
        risk: "low",
        aliases: ["open latest doc", "pull up latest doc", "open latest nhm2 doc"],
        required_args: ["topic"],
        optional_args: ["path"],
        returns_artifact: true,
      },
      {
        id: "search_docs",
        title: "Search Docs",
        description: "Search local docs manifest entries by topic.",
        risk: "low",
        aliases: ["search docs", "find docs about", "look for docs about"],
        required_args: ["query"],
        optional_args: ["limit"],
        returns_artifact: true,
      },
      {
        id: "verify_active_doc",
        title: "Verify Active Document",
        description: "Verify the current active document path in Docs Viewer.",
        risk: "low",
        aliases: ["verify active doc", "check current doc", "confirm current document"],
        returns_artifact: true,
      },
      {
        id: "open_doc_and_read",
        title: "Open Document And Read",
        description: "Open a local docs path and start read-aloud in Docs Viewer.",
        risk: "low",
        aliases: [
          "read this doc",
          "read this document",
          "read current doc",
          "read doc to me",
          "read this doc aloud",
          "read this doc out loud",
          "read this document aloud",
          "read current doc out loud",
        ],
        required_args: ["path"],
        optional_args: ["anchor"],
        returns_artifact: true,
      },
      {
        id: "open_directory",
        title: "Open Docs Directory",
        description: "Switch Docs Viewer to directory mode.",
        risk: "low",
        aliases: ["open docs directory", "show docs directory", "view docs directory"],
        returns_artifact: true,
      },
      {
        id: "identify_current_doc",
        title: "Identify Current Document",
        description: "Return the current active document path/anchor from Docs Viewer.",
        risk: "low",
        aliases: [
          "what doc are we on",
          "what is the doc we are looking at",
          "which document is open right now",
          "what document is open",
          "current document",
        ],
        returns_artifact: true,
      },
      {
        id: "locate_in_doc",
        title: "Locate In Document",
        description: "Locate where a topic appears in the current/target document.",
        risk: "low",
        aliases: [
          "where in this doc does it talk about",
          "find in this doc",
          "locate in this document",
        ],
        required_args: ["query"],
        optional_args: ["path", "anchor"],
        returns_artifact: true,
      },
      {
        id: "summarize_doc",
        title: "Summarize Document",
        description: "Summarize the current/target document in Helix Ask.",
        risk: "low",
        aliases: ["summarize doc", "summarize document", "doc summary"],
        optional_args: ["path", "anchor", "selected_text"],
        returns_artifact: true,
      },
      {
        id: "summarize_section",
        title: "Summarize Section",
        description: "Summarize a section in the current/target document in Helix Ask.",
        risk: "low",
        aliases: ["summarize section", "summarize this section", "section summary"],
        optional_args: ["path", "anchor", "selected_text"],
        returns_artifact: true,
      },
      {
        id: "explain_paper",
        title: "Explain Paper",
        description: "Explain the current/target paper in plain language in Helix Ask.",
        risk: "low",
        aliases: ["explain this paper", "explain this doc", "what does this doc do"],
        optional_args: ["path", "anchor", "selected_text"],
        returns_artifact: true,
      },
    ],
  }),
  "agi-essence-console": makeCapabilities({
    can_read_state: true,
    can_run_action: true,
    v1_job_ready: true,
    actions: [
      {
        id: "open",
        title: "Open Console",
        description: "Open and focus the AGI Essence Console panel.",
        risk: "low",
      },
    ],
  }),
  "agi-task-history": makeCapabilities({
    can_read_state: true,
    can_run_action: true,
    v1_job_ready: true,
    actions: [
      {
        id: "open",
        title: "Open Task History",
        description: "Open and focus Task History to inspect run progression and outcomes.",
        risk: "low",
      },
    ],
  }),
  "needle-mk2-calculator": makeCapabilities({
    can_read_state: true,
    can_run_action: true,
    v1_job_ready: true,
    actions: [
      {
        id: "open",
        title: "Open Calculator",
        description: "Open and focus the NHM2 calculator panel for compute steps.",
        risk: "low",
      },
    ],
  }),
  "scientific-calculator": makeCapabilities({
    can_read_state: true,
    can_run_action: true,
    v1_job_ready: true,
    actions: [
      {
        id: "open",
        title: "Open Scientific Calculator",
        description: "Open and focus the scientific calculator panel.",
        risk: "low",
      },
      {
        id: "ingest_latex",
        title: "Ingest LaTeX",
        description: "Load LaTeX/expression text into the calculator workspace.",
        risk: "low",
        required_args: ["latex"],
        optional_args: ["source_path", "anchor"],
        returns_artifact: true,
      },
      {
        id: "solve_expression",
        title: "Solve Expression",
        description: "Solve/evaluate the current or provided expression.",
        risk: "low",
        optional_args: ["latex"],
        returns_artifact: true,
      },
      {
        id: "solve_with_steps",
        title: "Solve With Steps",
        description: "Solve/evaluate with an explicit step trace.",
        risk: "low",
        optional_args: ["latex"],
        returns_artifact: true,
      },
      {
        id: "copy_result",
        title: "Copy Result",
        description: "Copy the latest solve result to clipboard.",
        risk: "low",
        returns_artifact: true,
      },
      {
        id: "copy_debug_log",
        title: "Copy Debug Log",
        description: "Copy calculator event logs and workstation action trace data.",
        risk: "low",
        returns_artifact: true,
      },
      {
        id: "clear_workspace",
        title: "Clear Workspace",
        description: "Clear calculator input/result workspace state.",
        risk: "low",
        returns_artifact: true,
      },
      {
        id: "start_prime_stream",
        title: "Start Prime Stream",
        description: "Start the deterministic calculator prime live source.",
        risk: "medium",
        optional_args: ["environment_id", "source_id", "tick_rate_ms", "max_ticks", "start"],
        returns_artifact: true,
      },
      {
        id: "stop_live_source",
        title: "Stop Live Source",
        description: "Stop the active calculator live source.",
        risk: "medium",
        optional_args: ["source_id"],
        returns_artifact: true,
      },
      {
        id: "restart_live_source",
        title: "Restart Live Source",
        description: "Restart the deterministic calculator prime live source.",
        risk: "medium",
        optional_args: ["environment_id", "source_id", "tick_rate_ms", "max_ticks", "start"],
        returns_artifact: true,
      },
      {
        id: "emit_live_tick",
        title: "Emit Live Tick",
        description: "Emit one deterministic calculator live-source tick.",
        risk: "medium",
        optional_args: ["environment_id", "source_id"],
        returns_artifact: true,
      },
    ],
  }),
  "theory-badge-graph": makeCapabilities({
    can_read_state: true,
    can_run_action: true,
    v1_job_ready: true,
    actions: [
      {
        id: "open",
        title: "Open Theory Badge Graph",
        description: "Open and focus the theory badge graph panel.",
        risk: "low",
        aliases: ["open theory badge graph", "show theory badges", "open theory graph"],
      },
      {
        id: "locate_context",
        title: "Locate Theory Context",
        description: "Locate prompt, expression, symbols, unit signatures, or source refs on the theory achievement map without solving.",
        risk: "low",
        optional_args: [
          "query",
          "expression",
          "subjects",
          "symbols",
          "unit_signatures",
          "repo_paths",
          "equation_families",
          "simulation_owners",
          "atlas_block_ids",
          "atlas_block_id",
          "source",
          "overlay",
          "limit",
        ],
        returns_artifact: true,
      },
      {
        id: "reflect_discussion_context",
        title: "Reflect Discussion Context",
        description:
          "Locate the current prompt/conversation in theory badge graph space and show a soft discussion-zone overlay. Returns evidence only; does not solve or mutate calculator state.",
        risk: "low",
        optional_args: [
          "prompt",
          "conversation_context",
          "mentioned_equations",
          "mentioned_symbols",
          "mentioned_domains",
          "confidence_mode",
          "source",
          "overlay",
          "open_panel",
          "turn_id",
          "thread_id",
          "build_explanation_plan",
          "limit",
        ],
        returns_artifact: true,
      },
      {
        id: "propose_frontier_conjectures",
        title: "Propose Frontier Conjectures",
        description:
          "Locate unresolved badge bridges and missing intermediate regions from graph, biome, probability, and frontier-search evidence. Returns evidence only; does not validate, promote, solve, or mutate calculator state.",
        risk: "low",
        optional_args: [
          "prompt",
          "query",
          "text",
          "conversation_context",
          "mentioned_equations",
          "mentioned_symbols",
          "mentioned_domains",
          "confidence_mode",
          "source",
          "overlay",
          "open_panel",
          "turn_id",
          "thread_id",
          "frontier_search_seed",
          "limit",
        ],
        returns_artifact: true,
      },
      {
        id: "explain_reflected_context",
        title: "Explain Reflected Context",
        description:
          "Build a first-principles-to-branch explanation plan from a theory context reflection. Returns evidence only; does not solve or mutate calculator state.",
        risk: "low",
        optional_args: [
          "reflection",
          "artifact_v1",
          "reflection_id",
          "prompt",
          "query",
          "text",
          "conversation_context",
          "mentioned_equations",
          "mentioned_symbols",
          "mentioned_domains",
          "limit",
        ],
        returns_artifact: true,
      },
      {
        id: "plan_calculation_context",
        title: "Plan Physics Calculation Context",
        description:
          "Plan a compound physics workflow by locating atlas badges, previewing calculator rows, and returning next actions without executing solves.",
        risk: "low",
        optional_args: [
          "query",
          "prompt",
          "atlas_block_ids",
          "atlas_block_id",
          "subjects",
          "symbols",
          "unit_signatures",
          "equation_families",
          "simulation_owners",
          "object_context",
          "variable_bindings",
          "intent",
          "overlay",
          "limit",
        ],
        returns_artifact: true,
      },
      {
        id: "list_atlas_blocks",
        title: "List Atlas Blocks",
        description: "Return compact physics atlas blocks for Helix Ask without solving or mutating calculator state.",
        risk: "low",
        returns_artifact: true,
      },
      {
        id: "list_physics_atlas",
        title: "List Physics Atlas",
        description: "Return the compact physics atlas domain lenses over the theory badge graph.",
        risk: "low",
        returns_artifact: true,
      },
      {
        id: "focus_atlas_block",
        title: "Focus Atlas Block",
        description: "Focus an atlas block lens on the theory achievement map without solving or mutating calculator state.",
        risk: "low",
        required_args: ["atlas_block_id"],
        optional_args: ["overlay"],
        returns_artifact: true,
      },
      {
        id: "select_atlas_block",
        title: "Select Atlas Block",
        description: "Highlight a compact physics atlas block on the theory achievement map.",
        risk: "low",
        required_args: ["block_id"],
        optional_args: ["overlay"],
        returns_artifact: true,
      },
      {
        id: "lookup_badges",
        title: "Lookup Theory Badges",
        description: "Find matching theory badges by prompt text, subject, symbol, unit signature, source path, family, or simulation owner.",
        risk: "low",
        optional_args: [
          "query",
          "subjects",
          "symbols",
          "unit_signatures",
          "repo_paths",
          "equation_families",
          "simulation_owners",
          "atlas_block_ids",
          "atlas_block_id",
          "limit",
        ],
        returns_artifact: true,
      },
      {
        id: "get_badge_context",
        title: "Get Badge Context",
        description: "Return a badge with optional upstream/downstream neighbors, calculator payloads, units, assumptions, and claim boundary.",
        risk: "low",
        required_args: ["badge_id"],
        optional_args: ["include_neighbors", "include_payloads"],
        returns_artifact: true,
      },
      {
        id: "load_payloads_to_calculator",
        title: "Load Badge Payloads To Calculator",
        description: "Load a badge's primary or selected calculator payloads into the Scientific Calculator without solving.",
        risk: "low",
        required_args: ["badge_id"],
        optional_args: ["payload_ids", "load_mode", "compound_run_id"],
        returns_artifact: true,
      },
      {
        id: "build_calculator_loadout",
        title: "Build Calculator Loadout",
        description: "Build an object-aware theory calculator loadout from selected badges or a dependency path without mutating panels.",
        risk: "low",
        optional_args: ["badge_ids", "target_badge_id", "atlas_block_id", "mode", "query", "variable_bindings", "object_context", "include_context_items", "loadout"],
        returns_artifact: true,
      },
      {
        id: "load_calculator_loadout",
        title: "Load Calculator Loadout",
        description: "Load a theory calculator loadout into the Scientific Calculator without solving.",
        risk: "low",
        optional_args: ["badge_ids", "target_badge_id", "atlas_block_id", "mode", "query", "variable_bindings", "object_context", "include_context_items", "loadout"],
        returns_artifact: true,
      },
      {
        id: "solve_calculator_loadout",
        title: "Solve Calculator Loadout",
        description: "Solve scalar rows in a theory calculator loadout and optionally run StarSim runtime receipt rows.",
        risk: "low",
        optional_args: ["badge_ids", "target_badge_id", "atlas_block_id", "mode", "query", "variable_bindings", "object_context", "include_context_items", "loadout", "solve_scope"],
        returns_artifact: true,
      },
      {
        id: "build_compound_theory_run",
        title: "Build Compound Theory Run",
        description:
          "Build a unified theory run artifact with scalar calculator rows, tensor/runtime trace rows, evidence refs, gates, and claim boundaries without mutating panels.",
        risk: "low",
        optional_args: [
          "badge_ids",
          "badge_id",
          "target_badge_id",
          "atlas_block_id",
          "mode",
          "include_scalar",
          "include_runtime",
          "include_evidence",
          "include_boundaries",
          "run",
        ],
        returns_artifact: true,
      },
      {
        id: "load_compound_theory_run",
        title: "Load Compound Theory Run",
        description:
          "Load a compound theory run into the Scientific Calculator Theory Run workbench without solving scalar or runtime rows.",
        risk: "low",
        optional_args: ["run", "run_id", "badge_ids", "badge_id", "target_badge_id", "atlas_block_id", "mode"],
        returns_artifact: true,
      },
      {
        id: "solve_compound_theory_run",
        title: "Solve Compound Theory Run",
        description:
          "Solve available scalar calculator rows and validate static tensor/runtime trace rows in a compound theory run; does not execute long backend jobs.",
        risk: "low",
        optional_args: ["run", "run_id", "badge_ids", "badge_id", "target_badge_id", "atlas_block_id", "mode", "solve_scope", "scope"],
        returns_artifact: true,
      },
      {
        id: "get_runtime_math_trace",
        title: "Get Runtime Math Trace",
        description:
          "Return a static/reference tensor or runtime math trace for a badge or runtime family; no backend runtime is executed.",
        risk: "low",
        optional_args: ["badge_id", "runtime_family", "family", "trace_id"],
        returns_artifact: true,
      },
      {
        id: "load_scalar_cut_to_calculator",
        title: "Load Scalar Cut To Calculator",
        description:
          "Load a scalar cut from a tensor/runtime trace into the existing Scientific Calculator scalar workbench without solving.",
        risk: "low",
        optional_args: ["scalar_cut", "expression", "latex", "display_latex", "source_path", "anchor", "run_id"],
        returns_artifact: true,
      },
      {
        id: "run_runtime_badge",
        title: "Run Runtime Badge",
        description: "Run a StarSim runtime badge against an object context and return a typed runtime receipt.",
        risk: "low",
        required_args: ["badge_id", "object_context"],
        optional_args: ["include_raw_evaluation"],
        returns_artifact: true,
      },
      {
        id: "trace_badges",
        title: "Trace Badge Connections",
        description: "Return shared ancestors, connecting paths, shared subjects, symbols, unit signatures, and claim boundary notes for selected badges.",
        risk: "low",
        required_args: ["badge_ids"],
        returns_artifact: true,
      },
      {
        id: "clear_overlay",
        title: "Clear Theory Map Overlay",
        description: "Clear locator and trace overlays from the theory achievement map.",
        risk: "low",
        returns_artifact: true,
      },
      {
        id: "run_badge_path",
        title: "Run Badge Path",
        description: "Run calculator playback for the dependency path to a target theory badge.",
        risk: "low",
        required_args: ["target_badge_id"],
        returns_artifact: true,
      },
    ],
  }),
  "rag-admin": makeCapabilities({
    can_read_state: true,
    can_run_action: true,
    v1_job_ready: true,
    actions: [
      {
        id: "open",
        title: "Open RAG Admin",
        description: "Open and focus RAG Admin for retrieval indexing and source management.",
        risk: "low",
      },
    ],
  }),
  "code-admin": makeCapabilities({
    can_read_state: true,
    can_run_action: true,
    v1_job_ready: true,
    actions: [
      {
        id: "open",
        title: "Open Code Admin",
        description: "Open and focus Code Admin for code-oriented analysis workflows.",
        risk: "low",
      },
    ],
  }),
  "helix-noise-gens": makeCapabilities({
    can_read_state: true,
    can_run_action: true,
    v1_job_ready: true,
    actions: [
      {
        id: "open",
        title: "Open Noise Gens",
        description: "Open and focus Helix Noise Gens control surface.",
        risk: "low",
      },
    ],
  }),
  "agi-contribution-workbench": makeCapabilities({
    can_read_state: true,
    can_run_action: true,
    v1_job_ready: true,
    actions: [
      {
        id: "open",
        title: "Open Workbench",
        description: "Open and focus the contribution workbench for receipts/review workflows.",
        risk: "low",
      },
    ],
  }),
  "workstation-notes": makeCapabilities({
    can_read_state: true,
    can_run_action: true,
    v1_job_ready: true,
    actions: [
      {
        id: "open",
        title: "Open Notes",
        description: "Open and focus workstation notes for macro note storage.",
        risk: "low",
        aliases: ["open notes", "show notes", "view notes"],
      },
      {
        id: "create_note",
        title: "Create Note",
        description: "Create a note and set it as active.",
        risk: "low",
        aliases: ["create note", "new note", "start note"],
        optional_args: ["title", "topic", "body", "note_id"],
        returns_artifact: true,
      },
      {
        id: "append_to_note",
        title: "Append To Note",
        description: "Append text to a note body (defaults to active note).",
        risk: "low",
        aliases: ["append to note", "add to note", "note append"],
        required_args: ["text"],
        optional_args: ["note_id", "title"],
        returns_artifact: true,
      },
      {
        id: "create_live_note_sink",
        title: "Create Live Note Sink",
        description: "Create a note target for live workstation pipeline summaries.",
        risk: "low",
        optional_args: ["note_id", "title", "topic"],
        returns_artifact: true,
      },
      {
        id: "append_live_note_chunk",
        title: "Append Live Note Chunk",
        description: "Append a transformed live pipeline chunk with citation metadata.",
        risk: "low",
        required_args: ["chunk_text"],
        optional_args: ["note_id", "title", "topic", "trace_id"],
        returns_artifact: true,
      },
      {
        id: "set_active_note",
        title: "Set Active Note",
        description: "Switch the active note by id/title.",
        risk: "low",
        aliases: ["open note", "switch to note", "set active note", "select note"],
        optional_args: ["note_id", "title"],
        returns_artifact: true,
      },
      {
        id: "rename_note",
        title: "Rename Note",
        description: "Rename an existing note.",
        risk: "low",
        aliases: ["rename note"],
        required_args: ["title"],
        optional_args: ["note_id", "from_title"],
        returns_artifact: true,
      },
      {
        id: "delete_note",
        title: "Delete Note",
        description: "Delete an existing note.",
        risk: "high",
        aliases: ["delete note", "remove note"],
        optional_args: ["note_id", "title", "confirmed"],
        requires_confirmation: true,
        returns_artifact: true,
      },
      {
        id: "list_notes",
        title: "List Notes",
        description: "Return the current notes list and active note.",
        risk: "low",
        aliases: ["list notes", "show notes", "my notes"],
        returns_artifact: true,
      },
    ],
  }),
  "situation-room-sources": makeCapabilities({
    can_read_state: true,
    can_run_action: true,
    v1_job_ready: true,
    actions: [
      {
        id: "open",
        title: "Open Situation Room",
        description: "Open and focus the unified Situation Room panel on source setup.",
        risk: "low",
        aliases: ["open situation room", "open room sources", "show situation sources"],
      },
      {
        id: "attach_display_audio_source",
        title: "Attach Display Audio Source",
        description: "Start a browser-selected tab, window, or screen audio source for a room.",
        risk: "medium",
        aliases: ["attach source", "attach audio source", "add browser tab audio", "add display audio"],
        optional_args: ["room_id", "label"],
        returns_artifact: true,
      },
      {
        id: "save_room_as_note",
        title: "Save Room As Note",
        description: "Save a situation room transcript and event rail into Workstation Notes.",
        risk: "low",
        optional_args: ["room_id"],
        returns_artifact: true,
      },
      {
        id: "attach_room_to_helix_ask",
        title: "Attach Room To Helix Ask",
        description: "Attach a room or source snapshot to Helix Ask context.",
        risk: "low",
        optional_args: ["room_id", "source_id"],
        returns_artifact: true,
      },
      {
        id: "stop_room",
        title: "Stop Room Sources",
        description: "Stop all active sources in a situation room.",
        risk: "medium",
        optional_args: ["room_id"],
        returns_artifact: true,
      },
    ],
  }),
  "situation-room-pipelines": makeCapabilities({
    can_read_state: true,
    can_run_action: true,
    v1_job_ready: true,
    actions: [
      {
        id: "open",
        title: "Open Situation Room",
        description: "Open and focus the unified Situation Room panel for sources, live routes, jobs, and traces.",
        risk: "low",
        aliases: ["open pipelines", "open live source jobs", "show room pipelines", "open situation room"],
      },
      {
        id: "attach_display_audio_source",
        title: "Attach Display Audio Source",
        description: "Start a browser-selected tab, window, or screen audio source for a room.",
        risk: "medium",
        aliases: ["attach source", "attach audio source", "add browser tab audio", "add display audio"],
        optional_args: ["room_id", "label"],
        returns_artifact: true,
      },
      {
        id: "attach_mic_audio_source",
        title: "Attach Mic Audio Source",
        description: "Start a microphone audio source for a room.",
        risk: "medium",
        aliases: ["attach mic", "attach microphone", "add mic audio"],
        optional_args: ["room_id", "label"],
        returns_artifact: true,
      },
      {
        id: "save_room_as_note",
        title: "Save Room As Note",
        description: "Save a situation room transcript and event rail into Workstation Notes.",
        risk: "low",
        optional_args: ["room_id"],
        returns_artifact: true,
      },
      {
        id: "attach_room_to_helix_ask",
        title: "Attach Room To Helix Ask",
        description: "Attach a room or source snapshot to Helix Ask context.",
        risk: "low",
        optional_args: ["room_id", "source_id"],
        returns_artifact: true,
      },
      {
        id: "stop_room",
        title: "Stop Room Sources",
        description: "Stop all active sources in a situation room.",
        risk: "medium",
        optional_args: ["room_id"],
        returns_artifact: true,
      },
      {
        id: "create_job",
        title: "Create Source Job",
        description: "Create a supervised job over selected room/source transcript events.",
        risk: "medium",
        aliases: ["create source job", "create translate job", "translate room source", "route source to job"],
        required_args: ["kind"],
        optional_args: [
          "room_id",
          "source_ids",
          "target_language",
          "native_language",
          "input_text_policy",
          "output_render_policy",
          "chunk_ranges",
          "attachment_policy",
          "context_injection",
          "derived_outputs_auto_attach",
          "command_lane_enabled",
        ],
        returns_artifact: true,
      },
      {
        id: "run_job",
        title: "Run Source Job",
        description: "Process selected room/source evidence for an existing job.",
        risk: "medium",
        required_args: ["job_id"],
        returns_artifact: true,
      },
      {
        id: "attach_job_to_helix_ask",
        title: "Attach Job To Helix Ask",
        description: "Attach a bounded job output snapshot to Helix Ask context.",
        risk: "low",
        required_args: ["job_id"],
        returns_artifact: true,
      },
      {
        id: "save_job_as_note",
        title: "Save Job As Note",
        description: "Save job outputs to Workstation Notes with source/job citations.",
        risk: "low",
        required_args: ["job_id"],
        returns_artifact: true,
      },
      {
        id: "stop_job",
        title: "Stop Source Job",
        description: "Cancel a running source job without stopping source capture.",
        risk: "medium",
        required_args: ["job_id"],
        returns_artifact: true,
      },
      {
        id: "create_graph",
        title: "Create Situation Graph",
        description: "Create a node-style graph for sources, jobs, outputs, and Helix Ask attachment.",
        risk: "low",
        optional_args: ["room_id", "title"],
        returns_artifact: true,
      },
      {
        id: "add_node",
        title: "Add Graph Node",
        description: "Add a node to an existing Situation Room graph.",
        risk: "low",
        required_args: ["graph_id", "type", "title"],
        optional_args: ["column", "status", "source_id", "speaker_id", "job_id"],
        returns_artifact: true,
      },
      {
        id: "connect_nodes",
        title: "Connect Graph Nodes",
        description: "Connect two graph nodes with a typed lane.",
        risk: "low",
        required_args: ["graph_id", "from_node_id", "to_node_id", "lane"],
        optional_args: ["from_port", "to_port"],
        returns_artifact: true,
      },
      {
        id: "create_translation_pair",
        title: "Create Translation Pair",
        description: "Create a two-way translation graph node backed by two manual-attachment translate jobs.",
        risk: "medium",
        required_args: [
          "speaker_a_id",
          "speaker_b_id",
          "speaker_a_native_language",
          "speaker_b_native_language",
        ],
        optional_args: ["graph_id", "room_id", "source_ids", "render_policy", "voice_output", "title"],
        returns_artifact: true,
      },
      {
        id: "attach_graph_to_helix_ask",
        title: "Attach Graph To Helix Ask",
        description: "Attach a bounded graph snapshot to Helix Ask context.",
        risk: "low",
        required_args: ["graph_id"],
        returns_artifact: true,
      },
      {
        id: "create_live_answer_environment",
        title: "Create Live Answer Environment",
        description: "Create a turn-owned live answer card backed by Situation Room source updates.",
        risk: "medium",
        aliases: [
          "create live answer environment",
          "start live answer",
          "watch my minecraft run",
          "set up prime stream",
          "track this simulation",
        ],
        required_args: ["objective"],
        optional_args: ["thread_id", "room_id", "source_ids", "graph_id", "preset", "line_schema", "mode", "source_config"],
        returns_artifact: true,
      },
      {
        id: "create_live_workstation_pipeline",
        title: "Create Live Workstation Pipeline",
        description: "Create a live source transform pipeline with output sinks such as notes and live cards.",
        risk: "medium",
        aliases: [
          "create live workstation pipeline",
          "summarize transcript into note",
          "compare transcript to moral philosophy",
          "write methods note from simulation",
        ],
        required_args: ["objective"],
        optional_args: ["thread_id", "source_ids", "source_id", "environment_id", "mode", "line_schema"],
        returns_artifact: true,
      },
      {
        id: "set_live_commentary_policy",
        title: "Set Live Commentary Policy",
        description: "Enable or adjust Codex-style commentary for the active live answer environment.",
        risk: "medium",
        aliases: [
          "enable live commentary",
          "turn on commentary",
          "talk me through this live answer",
          "narrate the live situation",
          "show codex style commentary",
        ],
        required_args: [],
        optional_args: ["thread_id", "environment_id", "cadence", "status", "voice_mode"],
        returns_artifact: true,
      },
      {
        id: "request_agentic_review",
        title: "Request Agentic Review",
        description: "Run an explicit Helix review over compact live environment state.",
        risk: "medium",
        aliases: [
          "run agentic review",
          "review this live answer",
          "explain latest equation result",
          "why did the live card update",
        ],
        required_args: [],
        optional_args: ["thread_id", "environment_id", "question", "trigger"],
        returns_artifact: true,
      },
      {
        id: "set_companion_policy",
        title: "Set Companion Policy",
        description: "Configure mic-aware companion behavior while keeping Helix Ask as the true reasoning loop.",
        risk: "medium",
        aliases: [
          "set companion policy",
          "enable active companion",
          "keep me company",
          "turn on dottie mode",
        ],
        required_args: [],
        optional_args: [
          "thread_id",
          "voice_input_active",
          "voice_output_enabled",
          "companion_mode",
          "commentary_mode",
          "direct_address_names",
        ],
        returns_artifact: true,
      },
      {
        id: "construct.create_from_recipe",
        title: "Create Situation Construct",
        description: "Create a visible Situation Room construct from a recipe.",
        risk: "medium",
        aliases: [
          "create construct",
          "build dottie",
          "manifest dottie",
          "start transcriber",
          "create route watcher",
          "make live agent",
        ],
        required_args: ["recipe_id"],
        optional_args: [
          "thread_id",
          "room_id",
          "source_ids",
          "target_run_id",
          "environment_id",
          "mode",
          "voice_mode",
          "commentary_cadence",
          "output",
        ],
        returns_artifact: true,
      },
      {
        id: "construct.list_recipes",
        title: "List Construct Recipes",
        description: "List available Situation Room construct recipes.",
        risk: "low",
        aliases: ["list construct recipes", "show dottie recipe", "show transcriber recipe"],
        required_args: [],
        optional_args: ["recipe_id"],
        returns_artifact: true,
      },
      {
        id: "construct.query",
        title: "Query Constructs",
        description: "Query visible Situation Room constructs and recipe runs.",
        risk: "low",
        aliases: ["show constructs", "query construct", "what constructs exist"],
        required_args: [],
        optional_args: ["thread_id", "room_id", "construct_id", "recipe_id", "type", "status"],
        returns_artifact: true,
      },
      {
        id: "construct.explain",
        title: "Explain Construct",
        description: "Explain a Situation Room construct using its evidence-only receipts and bindings.",
        risk: "low",
        aliases: ["explain construct", "explain dottie construct", "why does this construct exist"],
        required_args: ["construct_id"],
        optional_args: ["thread_id", "room_id"],
        returns_artifact: true,
      },
      {
        id: "construct.set_operating_prompt",
        title: "Set Live Job Prompt",
        description: "Update a visible live job operating prompt without granting answer authority.",
        risk: "medium",
        aliases: ["change live job prompt", "edit dottie prompt", "set operating prompt"],
        required_args: ["contract_id", "operating_prompt"],
        optional_args: ["thread_id", "room_id", "reason"],
        returns_artifact: true,
      },
      {
        id: "construct.detach",
        title: "Detach Construct",
        description: "Mark a Situation Room construct as detached without deleting its receipts.",
        risk: "medium",
        aliases: ["detach construct", "stop construct", "detach dottie construct"],
        required_args: ["construct_id"],
        optional_args: ["thread_id", "room_id"],
        returns_artifact: true,
      },
      {
        id: "construct.activate",
        title: "Activate Construct",
        description: "Mark a planned or receipt-only Situation Room construct as active.",
        risk: "medium",
        aliases: ["activate construct", "start construct", "activate dottie construct"],
        required_args: ["construct_id"],
        optional_args: ["thread_id", "room_id"],
        returns_artifact: true,
      },
      {
        id: "construct.attach_source",
        title: "Attach Source To Construct",
        description: "Attach a Situation Room source to an existing construct.",
        risk: "medium",
        aliases: ["attach source to construct", "add source to dottie", "bind source to transcriber"],
        required_args: ["construct_id", "source_ids"],
        optional_args: ["thread_id", "room_id"],
        returns_artifact: true,
      },
      {
        id: "construct.bind_output",
        title: "Bind Construct Output",
        description: "Bind an output surface such as transcript stream, typed commentary, voice proposal, or live answer projection to a construct.",
        risk: "medium",
        aliases: ["bind construct output", "send construct to live answers", "bind dottie voice proposal"],
        required_args: ["construct_id", "output"],
        optional_args: ["thread_id", "room_id", "artifact_ref", "environment_id", "status"],
        returns_artifact: true,
      },
      {
        id: "dottie.manifest",
        title: "Manifest Dottie",
        description: "Create a witness-only Auntie Dottie observer preset for the active Situation Room.",
        risk: "medium",
        aliases: [
          "manifest dottie",
          "start auntie dottie",
          "build dottie observer",
          "make dottie watch this room",
        ],
        required_args: [],
        optional_args: [
          "thread_id",
          "room_id",
          "source_ids",
          "mode",
          "voice_mode",
          "commentary_cadence",
          "target_run_id",
          "objective",
          "max_chars",
        ],
        returns_artifact: true,
      },
      {
        id: "observer.attach",
        title: "Attach Observer",
        description: "Attach a witness-only observer to public Helix Ask run commentary.",
        risk: "medium",
        aliases: [
          "attach dottie observer",
          "have dottie watch this ask turn",
          "watch helix ask with dottie",
          "start dottie witness mode",
        ],
        required_args: ["target_run_id", "observer_profile"],
        optional_args: ["thread_id", "target_turn_id", "target_agent_id", "voice_mode", "max_chars", "event_filter"],
        returns_artifact: true,
      },
      {
        id: "observer.detach",
        title: "Detach Observer",
        description: "Detach a witness-only observer subscription.",
        risk: "medium",
        aliases: ["detach dottie observer", "stop dottie watching", "remove observer subscription"],
        required_args: ["observer_id"],
        optional_args: ["thread_id", "target_run_id"],
        returns_artifact: true,
      },
      {
        id: "observer.query",
        title: "Query Observers",
        description: "List witness-only observers and their public commentary targets.",
        risk: "low",
        aliases: ["show dottie observers", "list observer subscriptions", "what is dottie watching"],
        required_args: [],
        optional_args: ["thread_id", "target_run_id", "observer_profile"],
        returns_artifact: true,
      },
      {
        id: "voice_delivery.propose_from_trace",
        title: "Propose Voice From Trace",
        description: "Create a Dottie voice proposal from an eligible public trace/commentary event.",
        risk: "medium",
        aliases: ["propose dottie voice from trace", "speak first commentary", "prepare dottie callout"],
        required_args: ["source_event_id"],
        optional_args: ["observer_id", "voice_mode", "max_chars", "source_text", "source_event_schema", "target_turn_id", "target_agent_id"],
        returns_artifact: true,
      },
      {
        id: "pause_live_workstation_pipeline",
        title: "Pause Live Pipeline",
        description: "Pause a live workstation pipeline.",
        risk: "medium",
        required_args: ["pipeline_id"],
        optional_args: ["thread_id"],
        returns_artifact: true,
      },
      {
        id: "resume_live_workstation_pipeline",
        title: "Resume Live Pipeline",
        description: "Resume a live workstation pipeline.",
        risk: "medium",
        required_args: ["pipeline_id"],
        optional_args: ["thread_id"],
        returns_artifact: true,
      },
      {
        id: "stop_live_workstation_pipeline",
        title: "Stop Live Pipeline",
        description: "Stop a live workstation pipeline.",
        risk: "medium",
        required_args: ["pipeline_id"],
        optional_args: ["thread_id"],
        returns_artifact: true,
      },
      {
        id: "set_pipeline_transform",
        title: "Set Pipeline Transform",
        description: "Update a live pipeline transform configuration.",
        risk: "medium",
        required_args: ["pipeline_id", "transform_id"],
        optional_args: ["params", "model_policy"],
        returns_artifact: true,
      },
      {
        id: "set_pipeline_sink",
        title: "Set Pipeline Sink",
        description: "Update a live pipeline output sink configuration.",
        risk: "medium",
        required_args: ["pipeline_id", "sink_id"],
        optional_args: ["params", "write_policy"],
        returns_artifact: true,
      },
      {
        id: "attach_pipeline_to_live_answer_environment",
        title: "Attach Pipeline To Live Answer Environment",
        description: "Attach a live pipeline to an existing live answer environment.",
        risk: "medium",
        required_args: ["pipeline_id", "environment_id"],
        optional_args: ["thread_id"],
        returns_artifact: true,
      },
      {
        id: "attach_live_source",
        title: "Attach Live Source",
        description: "Attach a workstation live source to an existing live answer environment.",
        risk: "medium",
        required_args: ["environment_id", "source_id"],
        optional_args: ["thread_id", "source_family", "kind", "panel_id"],
        returns_artifact: true,
      },
      {
        id: "pause_live_answer_environment",
        title: "Pause Live Answer Environment",
        description: "Pause live line updates for a live answer environment.",
        risk: "medium",
        required_args: ["environment_id"],
        optional_args: ["thread_id"],
        returns_artifact: true,
      },
      {
        id: "resume_live_answer_environment",
        title: "Resume Live Answer Environment",
        description: "Resume live line updates for a live answer environment.",
        risk: "medium",
        required_args: ["environment_id"],
        optional_args: ["thread_id"],
        returns_artifact: true,
      },
      {
        id: "stop_live_answer_environment",
        title: "Stop Live Answer Environment",
        description: "Complete and stop a live answer environment.",
        risk: "medium",
        required_args: ["environment_id"],
        optional_args: ["thread_id"],
        returns_artifact: true,
      },
      {
        id: "set_live_line_schema",
        title: "Set Live Line Schema",
        description: "Replace the line schema for a live answer environment.",
        risk: "medium",
        required_args: ["environment_id", "line_schema"],
        optional_args: ["thread_id"],
        returns_artifact: true,
      },
      {
        id: "set_live_answer_line_schema",
        title: "Set Live Answer Line Schema",
        description: "Replace the line schema for a live answer environment.",
        risk: "medium",
        required_args: ["environment_id", "line_schema"],
        optional_args: ["thread_id"],
        returns_artifact: true,
      },
      {
        id: "pause_live_source",
        title: "Pause Live Source",
        description: "Pause a workstation live source.",
        risk: "medium",
        required_args: ["source_id"],
        optional_args: ["thread_id"],
        returns_artifact: true,
      },
      {
        id: "resume_live_source",
        title: "Resume Live Source",
        description: "Resume a workstation live source.",
        risk: "medium",
        required_args: ["source_id"],
        optional_args: ["thread_id"],
        returns_artifact: true,
      },
      {
        id: "stop_live_source",
        title: "Stop Live Source",
        description: "Stop a workstation live source.",
        risk: "medium",
        required_args: ["source_id"],
        optional_args: ["thread_id"],
        returns_artifact: true,
      },
      {
        id: "set_live_source_tick_rate",
        title: "Set Live Source Tick Rate",
        description: "Set the canonical tick rate for a workstation live source.",
        risk: "medium",
        required_args: ["source_id", "tick_rate_ms"],
        optional_args: ["thread_id"],
        returns_artifact: true,
      },
      {
        id: "live-source.set_rate",
        title: "Set Live Source Rate",
        description: "Set the cadence/rate policy for an active live source producer, such as visual screen capture.",
        risk: "medium",
        aliases: [
          "set interval on visual capture",
          "set visual capture interval",
          "set cadence on screen capture",
          "keep checking every 10 seconds",
          "capture every 10 seconds",
        ],
        required_args: ["cadence_ms"],
        optional_args: ["thread_id", "source_id", "producer_id", "modality", "capture_mode", "environment_id", "pipeline_id"],
        returns_artifact: true,
      },
      {
        id: "start_situation_goal_session",
        title: "Start Situation Goal Session",
        description: "Start a source-backed situation goal session without creating a separate ingestion system.",
        risk: "medium",
        required_args: ["thread_id"],
        optional_args: ["room_id", "source_id", "world_id", "graph_id", "objective", "mode", "standby_mode", "append_policy"],
        returns_artifact: true,
      },
      {
        id: "query_event_window",
        title: "Query Event Window",
        description: "Query the canonical Situation Room world-event journal for a bounded event window.",
        risk: "low",
        optional_args: ["thread_id", "room_id", "source_id", "world_id", "event_types", "from_ts", "to_ts", "limit", "include_raw_events"],
        returns_artifact: true,
      },
      {
        id: "query_synthetic_evidence",
        title: "Query Synthetic Evidence",
        description: "Query compact synthetic evidence derived from canonical Situation Room observations.",
        risk: "low",
        required_args: ["thread_id"],
        optional_args: ["limit"],
        returns_artifact: true,
      },
      {
        id: "goal_ledger.set_objective",
        title: "Set Situation Objective",
        description: "Set the active situation objective for source-backed goal tracking.",
        risk: "low",
        required_args: ["thread_id", "objective"],
        optional_args: ["room_id"],
        returns_artifact: true,
      },
      {
        id: "goal_ledger.mark_complete",
        title: "Mark Situation Goal Complete",
        description: "Mark a situation goal complete from an explicit operator action.",
        risk: "low",
        required_args: ["thread_id", "goal"],
        optional_args: ["room_id"],
        returns_artifact: true,
      },
      {
        id: "goal_ledger.mark_blocked",
        title: "Mark Situation Goal Blocked",
        description: "Mark a situation goal blocked with an optional reason.",
        risk: "low",
        required_args: ["thread_id", "goal"],
        optional_args: ["room_id", "reason"],
        returns_artifact: true,
      },
      {
        id: "goal.evaluate",
        title: "Evaluate Situation Goal",
        description: "Evaluate the active objective from compact continuation evidence without composing an answer.",
        risk: "low",
        required_args: ["thread_id"],
        optional_args: ["room_id", "job_id", "objective", "evidence_refs"],
        returns_artifact: true,
      },
      {
        id: "callout_policy.set_mode",
        title: "Set Callout Policy Mode",
        description: "Set the Situation Room callout mode while preserving typed voice delivery confirmation.",
        risk: "medium",
        required_args: ["thread_id", "mode"],
        optional_args: ["room_id"],
        returns_artifact: true,
      },
      {
        id: "voice_delivery.confirm_speak",
        title: "Confirm Voice Delivery",
        description: "Confirm an eligible voice proposal for delivery.",
        risk: "medium",
        required_args: ["thread_id"],
        optional_args: ["proposal_id", "delivery_id"],
        returns_artifact: true,
      },
      {
        id: "live_continuation.start",
        title: "Start Live Continuation",
        description: "Start a single-agent continuation baton for an existing Situation Room source stream.",
        risk: "medium",
        required_args: ["thread_id", "room_id", "objective"],
        optional_args: ["environment_id", "contract_id", "source_ids", "source_id", "voice_policy", "evidence_threshold", "lanes_enabled", "min_tick_interval_ms"],
        returns_artifact: true,
      },
      {
        id: "live_continuation.tick",
        title: "Run Live Continuation Tick",
        description: "Run one deterministic continuation tick for an active live continuation job.",
        risk: "medium",
        optional_args: ["job_id", "thread_id", "room_id", "trigger"],
        returns_artifact: true,
      },
      {
        id: "live_continuation.query",
        title: "Query Live Continuations",
        description: "List active live continuation jobs and their compact status.",
        risk: "low",
        optional_args: ["job_id", "thread_id", "room_id", "source_id", "status"],
        returns_artifact: true,
      },
      {
        id: "live_continuation.pause",
        title: "Pause Live Continuation",
        description: "Pause a live continuation job without deleting its receipts.",
        risk: "medium",
        required_args: ["job_id"],
        optional_args: ["thread_id"],
        returns_artifact: true,
      },
      {
        id: "live_continuation.resume",
        title: "Resume Live Continuation",
        description: "Resume a paused live continuation job.",
        risk: "medium",
        required_args: ["job_id"],
        optional_args: ["thread_id"],
        returns_artifact: true,
      },
      {
        id: "live_continuation.stop",
        title: "Stop Live Continuation",
        description: "Stop a live continuation job and leave existing receipts intact.",
        risk: "medium",
        required_args: ["job_id"],
        optional_args: ["thread_id"],
        returns_artifact: true,
      },
      {
        id: "worker_lane.run",
        title: "Run Worker Lane",
        description: "Run a compact procedural worker-lane reducer without spawning a new chat.",
        risk: "medium",
        required_args: ["lane"],
        optional_args: ["thread_id", "room_id", "job_id", "evidence_refs"],
        returns_artifact: true,
      },
      {
        id: "source_health.query",
        title: "Query Source Health",
        description: "Return a live source admission/freshness receipt for continuation routing.",
        risk: "low",
        optional_args: ["thread_id", "room_id", "source_id", "job_id"],
        returns_artifact: true,
      },
    ],
  }),
  "live-answer-environment": makeCapabilities({
    can_read_state: true,
    can_run_action: true,
    v1_job_ready: true,
    actions: [
      {
        id: "open",
        title: "Open Live Answer",
        description: "Open and focus the Live Answer environment panel, including visual capture and earbud audio transcript outputs.",
        risk: "low",
        aliases: ["open live answer", "show live answer", "open visual capture", "show earbud outputs", "open audio transcript earbuds"],
      },
      {
        id: "image_lens.focus_regions",
        title: "Run Image Lens Focus Regions",
        description: "Use Image Lens to submit crop regions into Live Answer visual evidence. Observation only.",
        risk: "medium",
        aliases: [
          "route image lens focus to live answer",
          "send crop focus to live answer",
          "focus visual capture with image lens",
        ],
        required_args: ["sourceId", "regions"],
        optional_args: ["mode", "maxRegions"],
        returns_artifact: true,
      },
    ],
  }),
  "image-lens": makeCapabilities({
    can_read_state: true,
    can_run_action: true,
    v1_job_ready: true,
    actions: [
      {
        id: "open",
        title: "Open Image Lens",
        description: "Open and focus the image crop panel for sending manual frames to Live Answer visual sources.",
        risk: "low",
        aliases: [
          "open image lens",
          "show image lens",
          "open image crop panel",
          "send image frame",
        ],
      },
      {
        id: "image_lens.focus_regions",
        title: "Run Image Lens Focus Regions",
        description: "Submit one or more Image Lens crop regions into Live Answer visual evidence. Observation only.",
        risk: "medium",
        aliases: [
          "focus image lens regions",
          "inspect cropped regions",
          "crop areas of interest",
          "send focus regions to visual capture",
        ],
        required_args: ["sourceId", "regions"],
        optional_args: ["mode", "maxRegions"],
        returns_artifact: true,
      },
    ],
  }),
  "document-image-lens": makeCapabilities({
    can_read_state: true,
    can_run_action: true,
    v1_job_ready: true,
    actions: [
      {
        id: "open",
        title: "Open Image Lens",
        description: "Open the legacy Image Lens panel route.",
        risk: "low",
        aliases: ["open document image lens"],
      },
      {
        id: "image_lens.focus_regions",
        title: "Run Image Lens Focus Regions",
        description: "Submit one or more Image Lens crop regions into Live Answer visual evidence. Observation only.",
        risk: "medium",
        required_args: ["sourceId", "regions"],
        optional_args: ["mode", "maxRegions"],
        returns_artifact: true,
      },
    ],
  }),
  narrator: makeCapabilities({
    can_read_state: true,
    can_run_action: true,
    v1_job_ready: true,
    actions: [
      {
        id: "open",
        title: "Open Narrator",
        description: "Open and focus the governed Narrator output router panel.",
        risk: "low",
        aliases: ["open narrator", "show narrator", "open read aloud router", "show voice events"],
      },
      {
        id: "narrator.set_source_policy",
        title: "Set Narrator Source Policy",
        description: "Set one source policy for the Narrator output router.",
        risk: "medium",
        required_args: ["source_kind"],
        optional_args: ["enabled", "delivery_mode", "max_chars", "cooldown_ms", "min_certainty"],
        returns_artifact: true,
      },
      {
        id: "narrator.confirm_speak_event",
        title: "Confirm Narrator Speech",
        description: "Confirm a specific narrator event for delivery through the existing voice stack.",
        risk: "medium",
        required_args: ["event_id"],
        optional_args: ["thread_id"],
        returns_artifact: true,
      },
      {
        id: "narrator.say",
        title: "Narrator Say",
        description: "Publish a custom non-terminal narrator utterance through the governed Narrator output router.",
        risk: "medium",
        aliases: ["say this with narrator", "narrator say", "speak through narrator"],
        required_args: ["text"],
        optional_args: ["source_kind", "source_id", "evidence_refs", "delivery_mode", "priority", "language", "dedupe_key"],
        returns_artifact: true,
      },
      {
        id: "narrator.bind_stream",
        title: "Bind Narrator Stream",
        description: "Bind a live workstation output stream, such as translated transcript, to the governed Narrator policy.",
        risk: "medium",
        aliases: ["turn on narrator for translation", "bind narrator to transcript", "read translation stream aloud"],
        required_args: ["source_ref", "stream_kind"],
        optional_args: ["preset_id", "delivery_mode", "voice_policy", "evidence_threshold"],
        returns_artifact: true,
      },
      {
        id: "narrator.debug_auto_speak_probe",
        title: "Narrator Auto-Speak Probe",
        description: "Publish an evidence-only narrator probe event that is eligible for the existing voice stack.",
        risk: "low",
        aliases: ["test narrator voice", "debug narrator auto speak", "trigger narrator probe"],
        optional_args: ["text", "trace_id"],
        returns_artifact: true,
      },
      {
        id: "narrator.clear_feed",
        title: "Clear Narrator Feed",
        description: "Clear local narrator event history without changing source policies.",
        risk: "low",
        returns_artifact: true,
      },
    ],
  }),
  "workstation-clipboard-history": makeCapabilities({
    can_read_state: true,
    can_run_action: true,
    v1_job_ready: true,
    actions: [
      {
        id: "open",
        title: "Open Clipboard History",
        description: "Open and focus clipboard receipts timeline.",
        risk: "low",
        aliases: ["open clipboard", "show clipboard", "view clipboard history"],
      },
      {
        id: "read_clipboard",
        title: "Read Clipboard",
        description: "Read current clipboard text and record receipt.",
        risk: "low",
        aliases: ["read clipboard", "what is in clipboard", "paste from clipboard"],
        returns_artifact: true,
      },
      {
        id: "write_clipboard",
        title: "Write Clipboard",
        description: "Write text to clipboard and record receipt.",
        risk: "low",
        aliases: ["write clipboard", "copy this to clipboard", "copy to clipboard"],
        required_args: ["text"],
        optional_args: ["source"],
        returns_artifact: true,
      },
      {
        id: "clear_history",
        title: "Clear Clipboard History",
        description: "Clear clipboard receipt history.",
        risk: "high",
        aliases: ["clear clipboard history", "clear clipboard", "wipe clipboard history"],
        optional_args: ["confirmed"],
        requires_confirmation: true,
        returns_artifact: true,
      },
      {
        id: "copy_receipt_to_clipboard",
        title: "Copy Receipt To Clipboard",
        description: "Copy latest/specified clipboard receipt text back into clipboard.",
        risk: "low",
        aliases: ["copy latest clipboard entry", "copy receipt to clipboard"],
        optional_args: ["receipt_id"],
        returns_artifact: true,
      },
      {
        id: "copy_receipt_to_note",
        title: "Copy Receipt To Note",
        description: "Append clipboard receipt text to a note.",
        risk: "low",
        aliases: ["copy latest clipboard entry to note", "copy receipt to note"],
        optional_args: ["receipt_id", "note_id", "note_title"],
        returns_artifact: true,
      },
      {
        id: "copy_selection_to_note",
        title: "Copy Selection To Note",
        description: "Append current UI text selection (or clipboard fallback) to a note.",
        risk: "low",
        aliases: [
          "copy this abstract to a note pad",
          "copy this abstract to note",
          "copy this section to note",
          "copy this excerpt to note",
        ],
        optional_args: ["note_id", "note_title"],
        returns_artifact: true,
      },
    ],
  }),
  "workstation-workflow-timeline": makeCapabilities({
    can_read_state: true,
    can_run_action: true,
    v1_job_ready: true,
    actions: [
      {
        id: "open",
        title: "Open Workflow Timeline",
        description: "Open and focus cross-panel workflow timeline.",
        risk: "low",
      },
    ],
  }),
  "workstation-process-graph": makeCapabilities({
    can_read_state: true,
    can_run_action: true,
    v1_job_ready: true,
    actions: [
      {
        id: "open",
        title: "Open Process Graph",
        description: "Open and focus the workstation process graph overview.",
        risk: "low",
        aliases: ["open process graph", "show process graph", "open workstation graph"],
      },
      {
        id: "get_snapshot",
        title: "Get Process Graph Snapshot",
        description: "Return a deterministic read-only snapshot of current workstation graph state.",
        risk: "low",
        optional_args: ["scope", "max_nodes", "include_timeline", "include_artifacts"],
        returns_artifact: true,
      },
      {
        id: "get_context_pack",
        title: "Get Process Graph Context Pack",
        description: "Return a compact read-only workstation overview for Helix Ask or agent preflight context.",
        risk: "low",
        optional_args: ["max_nodes", "max_artifacts", "max_timeline", "include_timeline"],
        returns_artifact: true,
      },
      {
        id: "query_snapshot",
        title: "Query Process Graph Snapshot",
        description: "Return a filtered read-only snapshot of workstation graph nodes, edges, and timeline.",
        risk: "low",
        required_args: ["query"],
        optional_args: ["max_nodes", "include_timeline", "include_artifacts"],
        returns_artifact: true,
      },
      {
        id: "focus_node",
        title: "Focus Graph Node",
        description: "Focus a node in the process graph panel without executing another workstation action.",
        risk: "low",
        required_args: ["node_id"],
        returns_artifact: true,
      },
      {
        id: "filter_view",
        title: "Filter Graph View",
        description: "Set the process graph panel filter.",
        risk: "low",
        optional_args: ["filter"],
        returns_artifact: true,
      },
      {
        id: "export_svg",
        title: "Export Process Graph SVG",
        description: "Return a generated SVG snapshot of the process graph.",
        risk: "low",
        optional_args: ["mode", "max_nodes"],
        returns_artifact: true,
      },
      {
        id: "clear_historical",
        title: "Clear Historical Graph State",
        description: "Prune inactive old graph nodes while preserving active routes.",
        risk: "low",
        returns_artifact: true,
      },
    ],
  }),
  "account-session": makeCapabilities({
    can_read_state: true,
    can_run_action: true,
    v1_job_ready: true,
    actions: [
      {
        id: "open",
        title: "Open Account Sessions",
        description: "Open and focus the Account & Sessions panel.",
        risk: "low",
        aliases: ["open account", "show sessions", "show token usage", "open profile"],
      },
      {
        id: "set_interface_language",
        title: "Set Interface Language",
        description: "Change the workstation interface language preference.",
        risk: "low",
        aliases: [
          "set interface language",
          "change interface language",
          "switch ui language",
          "switch interface to hawaiian",
          "set ui to hawaiian",
        ],
        required_args: ["language"],
        returns_artifact: true,
      },
    ],
  }),
};

export function getWorkstationPanelCapabilities(panelId: string): WorkstationPanelCapabilities | null {
  return WORKSTATION_V1_PANEL_CAPABILITIES[panelId] ?? null;
}
