export type WorkstationPanelActionRisk = "low" | "medium" | "high";

export type WorkstationPanelActionDefinition = {
  id: string;
  title: string;
  description: string;
  risk: WorkstationPanelActionRisk;
  aliases?: string[];
  required_args?: string[];
  optional_args?: string[];
  requires_confirmation?: boolean;
  returns_artifact?: boolean;
};

export type WorkstationPanelCapabilities = {
  version: 1;
  can_read_state: boolean;
  can_run_action: boolean;
  safe_actions: string[];
  requires_confirmation_actions: string[];
  returns_artifact_actions: string[];
  v1_job_ready: boolean;
  actions: WorkstationPanelActionDefinition[];
};

const EMPTY_CAPABILITIES: WorkstationPanelCapabilities = {
  version: 1,
  can_read_state: false,
  can_run_action: false,
  safe_actions: [],
  requires_confirmation_actions: [],
  returns_artifact_actions: [],
  v1_job_ready: false,
  actions: [],
};

function makeCapabilities(
  input: Partial<WorkstationPanelCapabilities> & Pick<WorkstationPanelCapabilities, "actions">,
): WorkstationPanelCapabilities {
  const actions = input.actions ?? [];
  const safeActions =
    input.safe_actions ??
    actions.filter((action) => action.risk === "low").map((action) => action.id);
  const requiresConfirmation =
    input.requires_confirmation_actions ??
    actions.filter((action) => action.requires_confirmation).map((action) => action.id);
  const returnsArtifact =
    input.returns_artifact_actions ??
    actions.filter((action) => action.returns_artifact).map((action) => action.id);

  return {
    ...EMPTY_CAPABILITIES,
    ...input,
    actions,
    safe_actions: safeActions,
    requires_confirmation_actions: requiresConfirmation,
    returns_artifact_actions: returnsArtifact,
  };
}

export const WORKSTATION_V1_PANEL_CAPABILITIES: Record<string, WorkstationPanelCapabilities> = {
  "docs-viewer": makeCapabilities({
    can_read_state: true,
    can_run_action: true,
    v1_job_ready: true,
    actions: [
      {
        id: "open",
        title: "Open Docs Viewer",
        description: "Open and focus the Docs Viewer panel.",
        risk: "low",
        aliases: [
          "open docs",
          "show docs",
          "view docs",
          "open docs viewer",
          "go to docs",
          "switch to docs",
          "switch over to docs",
          "jump to docs",
          "jump over to docs",
          "jump over to docs viewer",
        ],
      },
      {
        id: "open_doc",
        title: "Open Document",
        description: "Open a local docs path (optionally with anchor) in the Docs Viewer panel.",
        risk: "low",
        aliases: ["open doc", "open document", "view doc", "show document"],
        required_args: ["path"],
        optional_args: ["anchor"],
        returns_artifact: true,
      },
      {
        id: "open_doc_by_path",
        title: "Open Document By Path",
        description: "Open a concrete local docs path in the Docs Viewer panel.",
        risk: "low",
        aliases: ["open docs path", "open this doc path", "open file in docs"],
        required_args: ["path"],
        optional_args: ["anchor"],
        returns_artifact: true,
      },
      {
        id: "open_latest_doc_by_topic",
        title: "Open Latest Document By Topic",
        description: "Resolve and open the latest local document matching a topic.",
        risk: "low",
        aliases: ["open latest doc", "pull up latest doc", "open latest nhm2 doc"],
        required_args: ["topic"],
        optional_args: ["path"],
        returns_artifact: true,
      },
      {
        id: "search_docs",
        title: "Search Docs",
        description: "Search local docs manifest entries by topic.",
        risk: "low",
        aliases: ["search docs", "find docs about", "look for docs about"],
        required_args: ["query"],
        optional_args: ["limit"],
        returns_artifact: true,
      },
      {
        id: "verify_active_doc",
        title: "Verify Active Document",
        description: "Verify the current active document path in Docs Viewer.",
        risk: "low",
        aliases: ["verify active doc", "check current doc", "confirm current document"],
        returns_artifact: true,
      },
      {
        id: "open_doc_and_read",
        title: "Open Document And Read",
        description: "Open a local docs path and start read-aloud in Docs Viewer.",
        risk: "low",
        aliases: [
          "read this doc",
          "read this document",
          "read current doc",
          "read doc to me",
          "read this doc aloud",
          "read this doc out loud",
          "read this document aloud",
          "read current doc out loud",
        ],
        required_args: ["path"],
        optional_args: ["anchor"],
        returns_artifact: true,
      },
      {
        id: "open_directory",
        title: "Open Docs Directory",
        description: "Switch Docs Viewer to directory mode.",
        risk: "low",
        aliases: ["open docs directory", "show docs directory", "view docs directory"],
        returns_artifact: true,
      },
      {
        id: "identify_current_doc",
        title: "Identify Current Document",
        description: "Return the current active document path/anchor from Docs Viewer.",
        risk: "low",
        aliases: [
          "what doc are we on",
          "what is the doc we are looking at",
          "which document is open right now",
          "what document is open",
          "current document",
        ],
        returns_artifact: true,
      },
      {
        id: "locate_in_doc",
        title: "Locate In Document",
        description: "Locate where a topic appears in the current/target document.",
        risk: "low",
        aliases: [
          "where in this doc does it talk about",
          "find in this doc",
          "locate in this document",
        ],
        required_args: ["query"],
        optional_args: ["path", "anchor"],
        returns_artifact: true,
      },
      {
        id: "summarize_doc",
        title: "Summarize Document",
        description: "Summarize the current/target document in Helix Ask.",
        risk: "low",
        aliases: ["summarize doc", "summarize document", "doc summary"],
        optional_args: ["path", "anchor", "selected_text"],
        returns_artifact: true,
      },
      {
        id: "summarize_section",
        title: "Summarize Section",
        description: "Summarize a section in the current/target document in Helix Ask.",
        risk: "low",
        aliases: ["summarize section", "summarize this section", "section summary"],
        optional_args: ["path", "anchor", "selected_text"],
        returns_artifact: true,
      },
      {
        id: "explain_paper",
        title: "Explain Paper",
        description: "Explain the current/target paper in plain language in Helix Ask.",
        risk: "low",
        aliases: ["explain this paper", "explain this doc", "what does this doc do"],
        optional_args: ["path", "anchor", "selected_text"],
        returns_artifact: true,
      },
    ],
  }),
  "agi-essence-console": makeCapabilities({
    can_read_state: true,
    can_run_action: true,
    v1_job_ready: true,
    actions: [
      {
        id: "open",
        title: "Open Console",
        description: "Open and focus the AGI Essence Console panel.",
        risk: "low",
      },
    ],
  }),
  "agi-task-history": makeCapabilities({
    can_read_state: true,
    can_run_action: true,
    v1_job_ready: true,
    actions: [
      {
        id: "open",
        title: "Open Task History",
        description: "Open and focus Task History to inspect run progression and outcomes.",
        risk: "low",
      },
    ],
  }),
  "needle-mk2-calculator": makeCapabilities({
    can_read_state: true,
    can_run_action: true,
    v1_job_ready: true,
    actions: [
      {
        id: "open",
        title: "Open Calculator",
        description: "Open and focus the NHM2 calculator panel for compute steps.",
        risk: "low",
      },
    ],
  }),
  "scientific-calculator": makeCapabilities({
    can_read_state: true,
    can_run_action: true,
    v1_job_ready: true,
    actions: [
      {
        id: "open",
        title: "Open Scientific Calculator",
        description: "Open and focus the scientific calculator panel.",
        risk: "low",
      },
      {
        id: "ingest_latex",
        title: "Ingest LaTeX",
        description: "Load LaTeX/expression text into the calculator workspace.",
        risk: "low",
        required_args: ["latex"],
        optional_args: ["source_path", "anchor"],
        returns_artifact: true,
      },
      {
        id: "solve_expression",
        title: "Solve Expression",
        description: "Solve/evaluate the current or provided expression.",
        risk: "low",
        optional_args: ["latex"],
        returns_artifact: true,
      },
      {
        id: "solve_with_steps",
        title: "Solve With Steps",
        description: "Solve/evaluate with an explicit step trace.",
        risk: "low",
        optional_args: ["latex"],
        returns_artifact: true,
      },
      {
        id: "copy_result",
        title: "Copy Result",
        description: "Copy the latest solve result to clipboard.",
        risk: "low",
        returns_artifact: true,
      },
      {
        id: "copy_debug_log",
        title: "Copy Debug Log",
        description: "Copy calculator event logs and workstation action trace data.",
        risk: "low",
        returns_artifact: true,
      },
      {
        id: "clear_workspace",
        title: "Clear Workspace",
        description: "Clear calculator input/result workspace state.",
        risk: "low",
        returns_artifact: true,
      },
      {
        id: "start_prime_stream",
        title: "Start Prime Stream",
        description: "Start the deterministic calculator prime live source.",
        risk: "medium",
        optional_args: ["environment_id", "source_id", "tick_rate_ms", "max_ticks", "start"],
        returns_artifact: true,
      },
      {
        id: "stop_live_source",
        title: "Stop Live Source",
        description: "Stop the active calculator live source.",
        risk: "medium",
        optional_args: ["source_id"],
        returns_artifact: true,
      },
      {
        id: "restart_live_source",
        title: "Restart Live Source",
        description: "Restart the deterministic calculator prime live source.",
        risk: "medium",
        optional_args: ["environment_id", "source_id", "tick_rate_ms", "max_ticks", "start"],
        returns_artifact: true,
      },
      {
        id: "emit_live_tick",
        title: "Emit Live Tick",
        description: "Emit one deterministic calculator live-source tick.",
        risk: "medium",
        optional_args: ["environment_id", "source_id"],
        returns_artifact: true,
      },
    ],
  }),
  "rag-admin": makeCapabilities({
    can_read_state: true,
    can_run_action: true,
    v1_job_ready: true,
    actions: [
      {
        id: "open",
        title: "Open RAG Admin",
        description: "Open and focus RAG Admin for retrieval indexing and source management.",
        risk: "low",
      },
    ],
  }),
  "code-admin": makeCapabilities({
    can_read_state: true,
    can_run_action: true,
    v1_job_ready: true,
    actions: [
      {
        id: "open",
        title: "Open Code Admin",
        description: "Open and focus Code Admin for code-oriented analysis workflows.",
        risk: "low",
      },
    ],
  }),
  "helix-noise-gens": makeCapabilities({
    can_read_state: true,
    can_run_action: true,
    v1_job_ready: true,
    actions: [
      {
        id: "open",
        title: "Open Noise Gens",
        description: "Open and focus Helix Noise Gens control surface.",
        risk: "low",
      },
    ],
  }),
  "agi-contribution-workbench": makeCapabilities({
    can_read_state: true,
    can_run_action: true,
    v1_job_ready: true,
    actions: [
      {
        id: "open",
        title: "Open Workbench",
        description: "Open and focus the contribution workbench for receipts/review workflows.",
        risk: "low",
      },
    ],
  }),
  "workstation-notes": makeCapabilities({
    can_read_state: true,
    can_run_action: true,
    v1_job_ready: true,
    actions: [
      {
        id: "open",
        title: "Open Notes",
        description: "Open and focus workstation notes for macro note storage.",
        risk: "low",
        aliases: ["open notes", "show notes", "view notes"],
      },
      {
        id: "create_note",
        title: "Create Note",
        description: "Create a note and set it as active.",
        risk: "low",
        aliases: ["create note", "new note", "start note"],
        optional_args: ["title", "topic", "body", "note_id"],
        returns_artifact: true,
      },
      {
        id: "append_to_note",
        title: "Append To Note",
        description: "Append text to a note body (defaults to active note).",
        risk: "low",
        aliases: ["append to note", "add to note", "note append"],
        required_args: ["text"],
        optional_args: ["note_id", "title"],
        returns_artifact: true,
      },
      {
        id: "set_active_note",
        title: "Set Active Note",
        description: "Switch the active note by id/title.",
        risk: "low",
        aliases: ["open note", "switch to note", "set active note", "select note"],
        optional_args: ["note_id", "title"],
        returns_artifact: true,
      },
      {
        id: "rename_note",
        title: "Rename Note",
        description: "Rename an existing note.",
        risk: "low",
        aliases: ["rename note"],
        required_args: ["title"],
        optional_args: ["note_id", "from_title"],
        returns_artifact: true,
      },
      {
        id: "delete_note",
        title: "Delete Note",
        description: "Delete an existing note.",
        risk: "high",
        aliases: ["delete note", "remove note"],
        optional_args: ["note_id", "title", "confirmed"],
        requires_confirmation: true,
        returns_artifact: true,
      },
      {
        id: "list_notes",
        title: "List Notes",
        description: "Return the current notes list and active note.",
        risk: "low",
        aliases: ["list notes", "show notes", "my notes"],
        returns_artifact: true,
      },
    ],
  }),
  "situation-room-sources": makeCapabilities({
    can_read_state: true,
    can_run_action: true,
    v1_job_ready: true,
    actions: [
      {
        id: "open",
        title: "Open Situation Room Sources",
        description: "Open and focus the Situation Room Sources panel.",
        risk: "low",
        aliases: ["open situation room", "open room sources", "show situation sources"],
      },
      {
        id: "attach_display_audio_source",
        title: "Attach Display Audio Source",
        description: "Start a browser-selected tab, window, or screen audio source for a room.",
        risk: "medium",
        aliases: ["attach source", "attach audio source", "add browser tab audio", "add display audio"],
        optional_args: ["room_id", "label"],
        returns_artifact: true,
      },
      {
        id: "save_room_as_note",
        title: "Save Room As Note",
        description: "Save a situation room transcript and event rail into Workstation Notes.",
        risk: "low",
        optional_args: ["room_id"],
        returns_artifact: true,
      },
      {
        id: "attach_room_to_helix_ask",
        title: "Attach Room To Helix Ask",
        description: "Attach a room or source snapshot to Helix Ask context.",
        risk: "low",
        optional_args: ["room_id", "source_id"],
        returns_artifact: true,
      },
      {
        id: "stop_room",
        title: "Stop Room Sources",
        description: "Stop all active sources in a situation room.",
        risk: "medium",
        optional_args: ["room_id"],
        returns_artifact: true,
      },
    ],
  }),
  "situation-room-pipelines": makeCapabilities({
    can_read_state: true,
    can_run_action: true,
    v1_job_ready: true,
    actions: [
      {
        id: "open",
        title: "Open Situation Room Pipelines",
        description: "Open and focus supervised live-source jobs for situation rooms.",
        risk: "low",
        aliases: ["open pipelines", "open live source jobs", "show room pipelines"],
      },
      {
        id: "create_job",
        title: "Create Source Job",
        description: "Create a supervised job over selected room/source transcript events.",
        risk: "medium",
        aliases: ["create source job", "create translate job", "translate room source", "route source to job"],
        required_args: ["kind"],
        optional_args: [
          "room_id",
          "source_ids",
          "target_language",
          "native_language",
          "input_text_policy",
          "output_render_policy",
          "chunk_ranges",
          "attachment_policy",
          "context_injection",
          "derived_outputs_auto_attach",
          "command_lane_enabled",
        ],
        returns_artifact: true,
      },
      {
        id: "run_job",
        title: "Run Source Job",
        description: "Process selected room/source evidence for an existing job.",
        risk: "medium",
        required_args: ["job_id"],
        returns_artifact: true,
      },
      {
        id: "attach_job_to_helix_ask",
        title: "Attach Job To Helix Ask",
        description: "Attach a bounded job output snapshot to Helix Ask context.",
        risk: "low",
        required_args: ["job_id"],
        returns_artifact: true,
      },
      {
        id: "save_job_as_note",
        title: "Save Job As Note",
        description: "Save job outputs to Workstation Notes with source/job citations.",
        risk: "low",
        required_args: ["job_id"],
        returns_artifact: true,
      },
      {
        id: "stop_job",
        title: "Stop Source Job",
        description: "Cancel a running source job without stopping source capture.",
        risk: "medium",
        required_args: ["job_id"],
        returns_artifact: true,
      },
      {
        id: "create_graph",
        title: "Create Situation Graph",
        description: "Create a node-style graph for sources, jobs, outputs, and Helix Ask attachment.",
        risk: "low",
        optional_args: ["room_id", "title"],
        returns_artifact: true,
      },
      {
        id: "add_node",
        title: "Add Graph Node",
        description: "Add a node to an existing Situation Room graph.",
        risk: "low",
        required_args: ["graph_id", "type", "title"],
        optional_args: ["column", "status", "source_id", "speaker_id", "job_id"],
        returns_artifact: true,
      },
      {
        id: "connect_nodes",
        title: "Connect Graph Nodes",
        description: "Connect two graph nodes with a typed lane.",
        risk: "low",
        required_args: ["graph_id", "from_node_id", "to_node_id", "lane"],
        optional_args: ["from_port", "to_port"],
        returns_artifact: true,
      },
      {
        id: "create_translation_pair",
        title: "Create Translation Pair",
        description: "Create a two-way translation graph node backed by two manual-attachment translate jobs.",
        risk: "medium",
        required_args: [
          "speaker_a_id",
          "speaker_b_id",
          "speaker_a_native_language",
          "speaker_b_native_language",
        ],
        optional_args: ["graph_id", "room_id", "source_ids", "render_policy", "voice_output", "title"],
        returns_artifact: true,
      },
      {
        id: "attach_graph_to_helix_ask",
        title: "Attach Graph To Helix Ask",
        description: "Attach a bounded graph snapshot to Helix Ask context.",
        risk: "low",
        required_args: ["graph_id"],
        returns_artifact: true,
      },
      {
        id: "create_live_answer_environment",
        title: "Create Live Answer Environment",
        description: "Create a turn-owned live answer card backed by Situation Room source updates.",
        risk: "medium",
        aliases: [
          "create live answer environment",
          "start live answer",
          "watch my minecraft run",
          "set up prime stream",
          "track this simulation",
        ],
        required_args: ["objective"],
        optional_args: ["thread_id", "room_id", "source_ids", "graph_id", "preset", "line_schema", "mode", "source_config"],
        returns_artifact: true,
      },
      {
        id: "attach_live_source",
        title: "Attach Live Source",
        description: "Attach a workstation live source to an existing live answer environment.",
        risk: "medium",
        required_args: ["environment_id", "source_id"],
        optional_args: ["thread_id", "source_family", "kind", "panel_id"],
        returns_artifact: true,
      },
      {
        id: "pause_live_answer_environment",
        title: "Pause Live Answer Environment",
        description: "Pause live line updates for a live answer environment.",
        risk: "medium",
        required_args: ["environment_id"],
        optional_args: ["thread_id"],
        returns_artifact: true,
      },
      {
        id: "resume_live_answer_environment",
        title: "Resume Live Answer Environment",
        description: "Resume live line updates for a live answer environment.",
        risk: "medium",
        required_args: ["environment_id"],
        optional_args: ["thread_id"],
        returns_artifact: true,
      },
      {
        id: "stop_live_answer_environment",
        title: "Stop Live Answer Environment",
        description: "Complete and stop a live answer environment.",
        risk: "medium",
        required_args: ["environment_id"],
        optional_args: ["thread_id"],
        returns_artifact: true,
      },
      {
        id: "set_live_line_schema",
        title: "Set Live Line Schema",
        description: "Replace the line schema for a live answer environment.",
        risk: "medium",
        required_args: ["environment_id", "line_schema"],
        optional_args: ["thread_id"],
        returns_artifact: true,
      },
      {
        id: "set_live_answer_line_schema",
        title: "Set Live Answer Line Schema",
        description: "Replace the line schema for a live answer environment.",
        risk: "medium",
        required_args: ["environment_id", "line_schema"],
        optional_args: ["thread_id"],
        returns_artifact: true,
      },
      {
        id: "pause_live_source",
        title: "Pause Live Source",
        description: "Pause a workstation live source.",
        risk: "medium",
        required_args: ["source_id"],
        optional_args: ["thread_id"],
        returns_artifact: true,
      },
      {
        id: "resume_live_source",
        title: "Resume Live Source",
        description: "Resume a workstation live source.",
        risk: "medium",
        required_args: ["source_id"],
        optional_args: ["thread_id"],
        returns_artifact: true,
      },
      {
        id: "stop_live_source",
        title: "Stop Live Source",
        description: "Stop a workstation live source.",
        risk: "medium",
        required_args: ["source_id"],
        optional_args: ["thread_id"],
        returns_artifact: true,
      },
      {
        id: "set_live_source_tick_rate",
        title: "Set Live Source Tick Rate",
        description: "Set the canonical tick rate for a workstation live source.",
        risk: "medium",
        required_args: ["source_id", "tick_rate_ms"],
        optional_args: ["thread_id"],
        returns_artifact: true,
      },
    ],
  }),
  "workstation-clipboard-history": makeCapabilities({
    can_read_state: true,
    can_run_action: true,
    v1_job_ready: true,
    actions: [
      {
        id: "open",
        title: "Open Clipboard History",
        description: "Open and focus clipboard receipts timeline.",
        risk: "low",
        aliases: ["open clipboard", "show clipboard", "view clipboard history"],
      },
      {
        id: "read_clipboard",
        title: "Read Clipboard",
        description: "Read current clipboard text and record receipt.",
        risk: "low",
        aliases: ["read clipboard", "what is in clipboard", "paste from clipboard"],
        returns_artifact: true,
      },
      {
        id: "write_clipboard",
        title: "Write Clipboard",
        description: "Write text to clipboard and record receipt.",
        risk: "low",
        aliases: ["write clipboard", "copy this to clipboard", "copy to clipboard"],
        required_args: ["text"],
        optional_args: ["source"],
        returns_artifact: true,
      },
      {
        id: "clear_history",
        title: "Clear Clipboard History",
        description: "Clear clipboard receipt history.",
        risk: "high",
        aliases: ["clear clipboard history", "clear clipboard", "wipe clipboard history"],
        optional_args: ["confirmed"],
        requires_confirmation: true,
        returns_artifact: true,
      },
      {
        id: "copy_receipt_to_clipboard",
        title: "Copy Receipt To Clipboard",
        description: "Copy latest/specified clipboard receipt text back into clipboard.",
        risk: "low",
        aliases: ["copy latest clipboard entry", "copy receipt to clipboard"],
        optional_args: ["receipt_id"],
        returns_artifact: true,
      },
      {
        id: "copy_receipt_to_note",
        title: "Copy Receipt To Note",
        description: "Append clipboard receipt text to a note.",
        risk: "low",
        aliases: ["copy latest clipboard entry to note", "copy receipt to note"],
        optional_args: ["receipt_id", "note_id", "note_title"],
        returns_artifact: true,
      },
      {
        id: "copy_selection_to_note",
        title: "Copy Selection To Note",
        description: "Append current UI text selection (or clipboard fallback) to a note.",
        risk: "low",
        aliases: [
          "copy this abstract to a note pad",
          "copy this abstract to note",
          "copy this section to note",
          "copy this excerpt to note",
        ],
        optional_args: ["note_id", "note_title"],
        returns_artifact: true,
      },
    ],
  }),
  "workstation-workflow-timeline": makeCapabilities({
    can_read_state: true,
    can_run_action: true,
    v1_job_ready: true,
    actions: [
      {
        id: "open",
        title: "Open Workflow Timeline",
        description: "Open and focus cross-panel workflow timeline.",
        risk: "low",
      },
    ],
  }),
};

export function getWorkstationPanelCapabilities(panelId: string): WorkstationPanelCapabilities | null {
  return WORKSTATION_V1_PANEL_CAPABILITIES[panelId] ?? null;
}
