"""Generate the frozen G2-D scalar-jet and endpoint-quotient C++ tables.

Program gate: G2 — classical branch proof and terminal state
Workstream: exact proof-definition implementation
Capability or component: frozen Laurent scalar/quotient C++ code generation
Current maturity: calculation-only build artifact generator
Target maturity: exact native quotient consumption with independent audit
Required frozen inputs: endpoint sparse-algebra v1 source and wire seals
Required evidence: source pin, semantic wire pin, deterministic byte output
Stop/fail criteria: any source, shape, exponent, integer, or seal drift
Explicit non-goals: proof/candidate execution, issuer, manifest, or lamps
Downstream gate unlocked: native endpoint/radial-cover calculation canary
"""

from __future__ import annotations

import hashlib
import importlib.util
from pathlib import Path
import sys


HERE = Path(__file__).resolve().parent
SOURCE = HERE / "tail_endpoint_sparse_algebra.py"
OUTPUT = HERE / "tail_endpoint_sparse_algebra_generated.hpp"
EXPECTED_SOURCE_SHA256 = (
    "b5bf0fabfe46f7e47eb200ee12d2d2d7189418dcedb311848ab519b4eb2e841e"
)
EXPECTED_SCALAR_SHA256 = (
    "858e83405870b2a6bb170b42f9b85817f7cfd9413e6206faba1fbbd1ae27826d"
)
EXPECTED_SCALAR_SIZE = 12_234
EXPECTED_QUOTIENT_SHA256 = (
    "c19b4795d314597d72d18ab8ad6e8dbfe55d16f58f31472402fff548417022a7"
)
EXPECTED_QUOTIENT_SIZE = 99_867


def _fail(code: str) -> None:
    raise RuntimeError(code)


def _load_source() -> object:
    source_bytes = SOURCE.read_bytes()
    if hashlib.sha256(source_bytes).hexdigest() != EXPECTED_SOURCE_SHA256:
        _fail("endpoint_sparse_algebra_source_pin_mismatch")
    specification = importlib.util.spec_from_file_location(
        "_nhm2_tail_endpoint_codegen_source", SOURCE
    )
    if specification is None or specification.loader is None:
        _fail("endpoint_sparse_algebra_import_spec_unavailable")
    module = importlib.util.module_from_spec(specification)
    sys.modules[specification.name] = module
    specification.loader.exec_module(module)
    return module


def _checked_int(value: object, lower: int, upper: int, code: str) -> int:
    if type(value) is not int or not lower <= value <= upper:
        _fail(code)
    return value


def _collect(
    coefficients: object, expected_count: int
) -> tuple[list[int], list[tuple[int, int, int, str, str]]]:
    if type(coefficients) is not tuple or len(coefficients) != expected_count:
        _fail("endpoint_series_shape")
    terms: list[tuple[int, int, int, str, str]] = []
    offsets = [0]
    for polynomial in coefficients:
        if type(polynomial) is not list:
            _fail("endpoint_polynomial_shape")
        for term in polynomial:
            if type(term) is not list or len(term) != 5:
                _fail("endpoint_term_shape")
            s_exp = _checked_int(term[0], 0, 127, "endpoint_s_exponent")
            m_exp = _checked_int(term[1], 0, 127, "endpoint_m_exponent")
            k_exp = _checked_int(term[2], -127, 127, "endpoint_k_exponent")
            numerator = term[3]
            denominator = term[4]
            if (
                type(numerator) is not str
                or type(denominator) is not str
                or not numerator.lstrip("-").isdigit()
                or not denominator.isdigit()
                or denominator == "0"
            ):
                _fail("endpoint_rational_decimal")
            terms.append((s_exp, m_exp, k_exp, numerator, denominator))
        offsets.append(len(terms))
    return offsets, terms


def _render() -> bytes:
    module = _load_source()
    receipt = module._test_only_generate(module._TEST_MARKER)
    if (
        receipt.scalar_wire_sha256 != EXPECTED_SCALAR_SHA256
        or receipt.scalar_wire_size_bytes != EXPECTED_SCALAR_SIZE
        or receipt.quotient_wire_sha256 != EXPECTED_QUOTIENT_SHA256
        or receipt.quotient_wire_size_bytes != EXPECTED_QUOTIENT_SIZE
    ):
        _fail("endpoint_wire_pin_mismatch")
    scalar_offsets, scalar_terms = _collect(receipt.scalar_coefficients, 9)
    quotient_offsets, quotient_terms = _collect(
        receipt.quotient_coefficients, 17
    )

    lines = [
        "// Generated by generate_tail_endpoint_sparse_algebra_header.py.",
        "// Calculation-only frozen data; no proof or candidate authority.",
        "#pragma once",
        "",
        "#include <array>",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "namespace nhm2_tail_endpoint_generated {",
        "",
        "struct LaurentTerm {",
        "  std::int8_t sExponent;",
        "  std::int8_t mExponent;",
        "  std::int8_t kExponent;",
        "  const char* numerator;",
        "  const char* denominator;",
        "};",
        "",
        f'inline constexpr char kScalarSemanticSha256[] = "{EXPECTED_SCALAR_SHA256}";',
        f"inline constexpr std::size_t kScalarWireSizeBytes = {EXPECTED_SCALAR_SIZE};",
        f"inline constexpr std::array<std::size_t, {len(scalar_offsets)}> kScalarOffsets = {{{{",
        "    " + ", ".join(str(value) for value in scalar_offsets),
        "}};",
        f"inline constexpr std::array<LaurentTerm, {len(scalar_terms)}> kScalarTerms = {{{{",
    ]
    lines.extend(
        "    LaurentTerm{%d, %d, %d, \"%s\", \"%s\"}," % term
        for term in scalar_terms
    )
    lines.extend(
        [
            "}};",
            "",
            f'inline constexpr char kQuotientSemanticSha256[] = "{EXPECTED_QUOTIENT_SHA256}";',
            f"inline constexpr std::size_t kQuotientWireSizeBytes = {EXPECTED_QUOTIENT_SIZE};",
            "inline constexpr std::array<std::size_t, "
            f"{len(quotient_offsets)}> kQuotientOffsets = {{{{",
            "    " + ", ".join(str(value) for value in quotient_offsets),
            "}};",
            "inline constexpr std::array<LaurentTerm, "
            f"{len(quotient_terms)}> kQuotientTerms = {{{{",
        ]
    )
    lines.extend(
        "    LaurentTerm{%d, %d, %d, \"%s\", \"%s\"}," % term
        for term in quotient_terms
    )
    lines.extend(
        [
            "}};",
            "",
            "}  // namespace nhm2_tail_endpoint_generated",
            "",
        ]
    )
    return "\n".join(lines).encode("ascii")


def main() -> None:
    rendered = _render()
    temporary = OUTPUT.with_suffix(OUTPUT.suffix + ".tmp")
    temporary.write_bytes(rendered)
    temporary.replace(OUTPUT)
    print(
        hashlib.sha256(rendered).hexdigest(),
        len(rendered),
        OUTPUT.as_posix(),
    )


if __name__ == "__main__":
    main()
