import {
  buildCivilizationTraversabilityAtlasV1,
  type CivilizationTraversabilityAtlasV1,
} from "../civilization-traversability-atlas";

export const DEFAULT_CIVILIZATION_TRAVERSABILITY_SCENARIO_ID =
  "planetary_traversability_static_demo" as const;

const CLAIM_TIER = "diagnostic_bound" as const;

export function buildDefaultCivilizationTraversabilityAtlas(options?: {
  scenarioId?: string;
  generatedAt?: string;
  observedAt?: string;
}): CivilizationTraversabilityAtlasV1 {
  const scenarioId = options?.scenarioId ?? DEFAULT_CIVILIZATION_TRAVERSABILITY_SCENARIO_ID;
  const observedAt = options?.observedAt ?? "2026-07-01T00:00:00.000Z";
  const temporalFrame = {
    observedAt,
    validFrom: "2026-07-01T00:00:00.000Z",
    validTo: "2026-07-31T23:59:59.000Z",
    cadence: "seasonal" as const,
  };
  return buildCivilizationTraversabilityAtlasV1({
    generatedAt: options?.generatedAt,
    atlasId: `civilization-traversability:${scenarioId}`,
    scenarioId,
    title: "Planetary Traversability Atlas Fixture",
    temporalFrame,
    fieldLayers: [
      {
        fieldLayerId: "field:era5:north-atlantic-wind",
        kind: "atmospheric_wind",
        label: "North Atlantic wind field",
        temporalFrame: { ...temporalFrame, cadence: "hourly" },
        geometryRef: {
          refId: "geometry:era5:north-atlantic-wind:raster",
          kind: "raster",
          description: "Hourly atmospheric vector field subset used as route-cost modifier, not a permanent edge.",
          sourceRefs: ["external:copernicus-era5-hourly-single-levels"],
        },
        units: "m/s",
        resolution: "0.25 degree atmosphere grid",
        confidence: 0.7,
        uncertainty: 0.25,
        evidenceRefs: ["source:copernicus-era5-hourly-single-levels"],
        missingEvidence: ["operator_selected_time_slice", "route_specific_weather_hazard_receipts"],
        claimTier: CLAIM_TIER,
      },
      {
        fieldLayerId: "field:ocean:north-atlantic-current",
        kind: "ocean_current",
        label: "North Atlantic current field",
        temporalFrame: { ...temporalFrame, cadence: "daily" },
        geometryRef: {
          refId: "geometry:ocean:north-atlantic-current:raster",
          kind: "raster",
          description: "Modeled current field used beneath maritime candidates.",
          sourceRefs: ["external:copernicus-marine-current-field"],
        },
        units: "m/s",
        confidence: 0.58,
        uncertainty: 0.32,
        evidenceRefs: ["source:copernicus-marine-current-field"],
        missingEvidence: ["local_wave_hazard_receipts", "vessel_class_constraints"],
        claimTier: CLAIM_TIER,
      },
      {
        fieldLayerId: "field:sahara-amazon:dust-phosphorus",
        kind: "atmospheric_wind",
        label: "Sahara to Amazon dust and phosphorus transport",
        temporalFrame: { ...temporalFrame, cadence: "seasonal" },
        geometryRef: {
          refId: "geometry:sahara-amazon:dust-plume",
          kind: "external",
          description: "Trans-Atlantic dust plume teleconnection; evidence varies by year.",
          sourceRefs: ["external:nasa-calipso-sahara-amazon-dust"],
        },
        units: "mass transport and nutrient deposition",
        confidence: 0.72,
        uncertainty: 0.42,
        evidenceRefs: ["source:nasa-calipso-sahara-amazon-dust"],
        missingEvidence: ["current_year_plume_observation", "nutrient_deposition_uncertainty"],
        claimTier: CLAIM_TIER,
      },
      {
        fieldLayerId: "field:spun:mycorrhizal-biodiversity",
        kind: "fungal_biodiversity",
        label: "Predicted mycorrhizal biodiversity surface",
        temporalFrame: { observedAt, cadence: "static" },
        geometryRef: {
          refId: "geometry:spun:mycorrhizal-biodiversity:raster",
          kind: "raster",
          description: "Predictive biodiversity surface with uncertainty and model extrapolation.",
          sourceRefs: ["external:spun-underground-atlas-mycorrhizal-biodiversity"],
        },
        units: "predicted richness and endemism",
        resolution: "1 km2 pixel",
        confidence: 0.62,
        uncertainty: 0.4,
        evidenceRefs: ["source:spun-underground-atlas-mycorrhizal-biodiversity"],
        missingEvidence: ["local_soil_sample_receipts", "ecosystem_connectivity_validation"],
        claimTier: CLAIM_TIER,
      },
      {
        fieldLayerId: "field:solar:seasonal-irradiance",
        kind: "solar_irradiance",
        label: "Seasonal solar irradiance driver",
        temporalFrame,
        geometryRef: {
          refId: "geometry:solar:seasonal-irradiance",
          kind: "raster",
          description: "Latitude, season, atmosphere, and cloud-adjusted solar affordance layer.",
          sourceRefs: ["theory:solar-radiative-energy-bounds"],
        },
        units: "W/m2",
        confidence: 0.55,
        uncertainty: 0.35,
        evidenceRefs: ["theory:solar-radiative-energy-bounds"],
        missingEvidence: ["cloud_cover_time_slice", "grid_storage_capacity_refs"],
        claimTier: CLAIM_TIER,
      },
    ],
    infrastructureNodes: [
      {
        nodeId: "node:airport:jfk",
        kind: "airport",
        label: "New York JFK airport node",
        countryIso3: "USA",
        coordinates: { lat: 40.6413, lon: -73.7781 },
        activeFieldLayerIds: ["field:era5:north-atlantic-wind"],
        evidenceRefs: ["fixture:airport-node:jfk"],
        missingEvidence: ["slot_availability", "airspace_restriction_receipts"],
        confidence: 0.45,
        claimTier: CLAIM_TIER,
      },
      {
        nodeId: "node:airport:fra",
        kind: "airport",
        label: "Frankfurt airport node",
        countryIso3: "DEU",
        coordinates: { lat: 50.0379, lon: 8.5622 },
        activeFieldLayerIds: ["field:era5:north-atlantic-wind"],
        evidenceRefs: ["fixture:airport-node:fra"],
        missingEvidence: ["slot_availability", "airspace_restriction_receipts"],
        confidence: 0.45,
        claimTier: CLAIM_TIER,
      },
      {
        nodeId: "node:port:ny-nj",
        kind: "port",
        label: "Port of New York and New Jersey node",
        countryIso3: "USA",
        coordinates: { lat: 40.6681, lon: -74.0451 },
        activeFieldLayerIds: ["field:ocean:north-atlantic-current"],
        evidenceRefs: ["fixture:port-node:ny-nj"],
        missingEvidence: ["vessel_schedule_receipts", "port_capacity_time_slice"],
        confidence: 0.42,
        claimTier: CLAIM_TIER,
      },
      {
        nodeId: "node:port:rotterdam",
        kind: "port",
        label: "Port of Rotterdam node",
        countryIso3: "NLD",
        coordinates: { lat: 51.95, lon: 4.14 },
        activeFieldLayerIds: ["field:ocean:north-atlantic-current"],
        evidenceRefs: ["fixture:port-node:rotterdam"],
        missingEvidence: ["vessel_schedule_receipts", "port_capacity_time_slice"],
        confidence: 0.42,
        claimTier: CLAIM_TIER,
      },
      {
        nodeId: "node:rail:rhine-corridor",
        kind: "rail_junction",
        label: "Rhine-Alpine rail corridor node",
        countryIso3: "DEU",
        coordinates: { lat: 50.11, lon: 8.68 },
        activeFieldLayerIds: [],
        evidenceRefs: ["fixture:rail-node:rhine-alpine"],
        missingEvidence: ["rail_capacity_receipts", "maintenance_window_refs"],
        confidence: 0.36,
        claimTier: CLAIM_TIER,
      },
      {
        nodeId: "node:cable:ny",
        kind: "submarine_cable_landing",
        label: "New York cable landing node",
        countryIso3: "USA",
        coordinates: { lat: 40.7, lon: -73.9 },
        activeFieldLayerIds: [],
        evidenceRefs: ["fixture:cable-node:new-york"],
        missingEvidence: ["cable_operator_receipts", "latency_measurement_refs"],
        confidence: 0.33,
        claimTier: CLAIM_TIER,
      },
      {
        nodeId: "node:cable:uk",
        kind: "submarine_cable_landing",
        label: "United Kingdom cable landing node",
        countryIso3: "GBR",
        coordinates: { lat: 50.1, lon: -5.5 },
        activeFieldLayerIds: [],
        evidenceRefs: ["fixture:cable-node:uk"],
        missingEvidence: ["cable_operator_receipts", "latency_measurement_refs"],
        confidence: 0.33,
        claimTier: CLAIM_TIER,
      },
      {
        nodeId: "node:dust:bodele",
        kind: "dust_source_region",
        label: "Bodele Depression dust source region",
        countryIso3: "TCD",
        coordinates: { lat: 17.0, lon: 18.0 },
        activeFieldLayerIds: ["field:sahara-amazon:dust-phosphorus"],
        evidenceRefs: ["source:nasa-calipso-sahara-amazon-dust"],
        missingEvidence: ["current_year_dust_source_activation"],
        confidence: 0.7,
        claimTier: CLAIM_TIER,
      },
      {
        nodeId: "node:ecology:amazon-basin",
        kind: "deposition_region",
        label: "Amazon basin nutrient deposition region",
        countryIso3: "BRA",
        coordinates: { lat: -3.0, lon: -60.0 },
        activeFieldLayerIds: ["field:sahara-amazon:dust-phosphorus", "field:spun:mycorrhizal-biodiversity"],
        evidenceRefs: ["source:nasa-calipso-sahara-amazon-dust"],
        missingEvidence: ["current_year_deposition_observation", "local_ecosystem_response_receipts"],
        confidence: 0.68,
        claimTier: CLAIM_TIER,
      },
    ],
    routeCandidates: [
      {
        routeId: "route:air:jfk-fra:wind-adjusted",
        dependencyEdgeId: "dependency:urgent-air-logistics",
        label: "JFK to Frankfurt wind-adjusted air corridor",
        mode: "air",
        realization: "modeled_candidate",
        geometryRef: {
          refId: "geometry:route:air:jfk-fra",
          kind: "polyline",
          description: "Candidate air corridor; great-circle distance is only a lower-bound preview.",
          sourceRefs: ["fixture:route:air:jfk-fra"],
        },
        transferNodeIds: ["node:airport:jfk", "node:airport:fra"],
        activeFieldLayerIds: ["field:era5:north-atlantic-wind"],
        metrics: { distanceKm: 6200, durationHours: 7.7, energyCost: 0.82, reliability: 0.71 },
        feasibility: { physical: 0.9, infrastructure: 0.8, jurisdictional: 0.55, operationalEvidence: 0.35 },
        constraints: [
          { kind: "weather", refId: "field:era5:north-atlantic-wind", effect: "raises_cost" },
          { kind: "airspace", refId: "missing:airspace-restriction-receipts", effect: "unknown" },
        ],
        confidence: 0.46,
        uncertainty: 0.35,
        claimTier: CLAIM_TIER,
        evidenceRefs: ["fixture:route:air:jfk-fra", "source:copernicus-era5-hourly-single-levels"],
        missingEvidence: ["airspace_restriction_receipts", "flight_schedule_receipts"],
        theoryBadgeIds: ["relativity.signal_latency_bound", "thermodynamics.heat_sink_capacity"],
        zenNodeIds: ["direct-observation-before-claim", "provenance-protocol"],
      },
      {
        routeId: "route:sea:ny-nj-rotterdam:current-adjusted",
        dependencyEdgeId: "dependency:containerized-trade",
        label: "New York/New Jersey to Rotterdam maritime corridor",
        mode: "sea",
        realization: "modeled_candidate",
        geometryRef: {
          refId: "geometry:route:sea:ny-nj-rotterdam",
          kind: "polyline",
          description: "Candidate maritime corridor through ocean-current and weather fields.",
          sourceRefs: ["fixture:route:sea:ny-nj-rotterdam"],
        },
        transferNodeIds: ["node:port:ny-nj", "node:port:rotterdam"],
        activeFieldLayerIds: ["field:ocean:north-atlantic-current", "field:era5:north-atlantic-wind"],
        metrics: { distanceKm: 5900, durationHours: 240, capacity: 0.86, energyCost: 0.55, reliability: 0.64 },
        feasibility: { physical: 0.85, infrastructure: 0.78, jurisdictional: 0.62, operationalEvidence: 0.32 },
        constraints: [
          { kind: "current", refId: "field:ocean:north-atlantic-current", effect: "raises_cost" },
          { kind: "capacity", refId: "missing:port-capacity-time-slice", effect: "unknown" },
        ],
        confidence: 0.44,
        uncertainty: 0.38,
        claimTier: CLAIM_TIER,
        evidenceRefs: ["fixture:route:sea:ny-nj-rotterdam", "source:copernicus-marine-current-field"],
        missingEvidence: ["vessel_schedule_receipts", "port_capacity_time_slice"],
        theoryBadgeIds: ["physics.symmetry.energy_momentum_conservation"],
        zenNodeIds: ["interdependence-yin-yang-balance", "feedback-loop-hygiene"],
      },
      {
        routeId: "route:rail:rhine-alpine:inland",
        dependencyEdgeId: "dependency:inland-industrial-logistics",
        label: "Rhine-Alpine inland rail corridor",
        mode: "rail",
        realization: "modeled_candidate",
        geometryRef: {
          refId: "geometry:route:rail:rhine-alpine",
          kind: "polyline",
          description: "Inland rail route candidate through junction, maintenance, and border constraints.",
          sourceRefs: ["fixture:route:rail:rhine-alpine"],
        },
        transferNodeIds: ["node:rail:rhine-corridor"],
        activeFieldLayerIds: [],
        metrics: { distanceKm: 900, durationHours: 18, capacity: 0.7, energyCost: 0.33, reliability: 0.6 },
        feasibility: { physical: 0.78, infrastructure: 0.58, jurisdictional: 0.68, operationalEvidence: 0.22 },
        constraints: [
          { kind: "maintenance", refId: "missing:maintenance-window-refs", effect: "unknown" },
          { kind: "border", refId: "missing:border-customs-receipts", effect: "unknown" },
        ],
        confidence: 0.34,
        uncertainty: 0.48,
        claimTier: CLAIM_TIER,
        evidenceRefs: ["fixture:route:rail:rhine-alpine"],
        missingEvidence: ["rail_capacity_receipts", "maintenance_window_refs", "border_customs_receipts"],
        theoryBadgeIds: ["physics.symmetry.energy_momentum_conservation"],
        zenNodeIds: ["fairness-due-process-and-justification"],
      },
      {
        routeId: "route:atmospheric:sahara-amazon:dust",
        dependencyEdgeId: "dependency:natural-nutrient-teleconnection",
        label: "Sahara to Amazon atmospheric nutrient teleconnection",
        mode: "atmospheric",
        realization: "historical",
        geometryRef: {
          refId: "geometry:route:atmospheric:sahara-amazon",
          kind: "external",
          description: "Natural atmospheric pathway for dust and phosphorus transport.",
          sourceRefs: ["source:nasa-calipso-sahara-amazon-dust"],
        },
        transferNodeIds: ["node:dust:bodele", "node:ecology:amazon-basin"],
        activeFieldLayerIds: ["field:sahara-amazon:dust-phosphorus"],
        metrics: { distanceKm: 2600, reliability: 0.45 },
        feasibility: { physical: 0.9, infrastructure: null, jurisdictional: null, operationalEvidence: 0.72 },
        constraints: [
          { kind: "weather", refId: "field:sahara-amazon:dust-phosphorus", effect: "raises_cost" },
          { kind: "missing_observation", refId: "missing:current-year-plume-observation", effect: "unknown" },
        ],
        confidence: 0.72,
        uncertainty: 0.42,
        claimTier: CLAIM_TIER,
        evidenceRefs: ["source:nasa-calipso-sahara-amazon-dust"],
        missingEvidence: ["current_year_plume_observation", "nutrient_deposition_uncertainty"],
        theoryBadgeIds: ["biophysics.membrane.open_system_entropy_flow"],
        zenNodeIds: ["interbeing-systems", "direct-observation-before-claim"],
      },
      {
        routeId: "route:cable:new-york-uk:transatlantic",
        dependencyEdgeId: "dependency:signal-connectivity",
        label: "Trans-Atlantic submarine cable corridor",
        mode: "submarine_cable",
        realization: "modeled_candidate",
        geometryRef: {
          refId: "geometry:route:cable:new-york-uk",
          kind: "polyline",
          description: "Built signal corridor candidate; not an ecological or moral relation.",
          sourceRefs: ["fixture:route:cable:new-york-uk"],
        },
        transferNodeIds: ["node:cable:ny", "node:cable:uk"],
        activeFieldLayerIds: [],
        metrics: { distanceKm: 5600, durationHours: 0.00002, capacity: 0.8, reliability: 0.67 },
        feasibility: { physical: 0.95, infrastructure: 0.68, jurisdictional: 0.58, operationalEvidence: 0.25 },
        constraints: [
          { kind: "maintenance", refId: "missing:cable-maintenance-status", effect: "unknown" },
          { kind: "treaty", refId: "missing:jurisdictional-routing-refs", effect: "unknown" },
        ],
        confidence: 0.36,
        uncertainty: 0.5,
        claimTier: CLAIM_TIER,
        evidenceRefs: ["fixture:route:cable:new-york-uk"],
        missingEvidence: ["cable_operator_receipts", "latency_measurement_refs", "jurisdictional_routing_refs"],
        theoryBadgeIds: ["relativity.signal_latency_bound"],
        zenNodeIds: ["provenance-protocol", "integrity-protocols"],
      },
      {
        routeId: "route:ecological:mycorrhizal-probabilistic-surface",
        dependencyEdgeId: "dependency:ecosystem-connectivity",
        label: "Probabilistic mycorrhizal biodiversity surface",
        mode: "ecological",
        realization: "modeled_candidate",
        geometryRef: {
          refId: "geometry:route:ecological:mycorrhizal-surface",
          kind: "raster",
          description: "Ecological field relation; internet comparison is analogy only.",
          sourceRefs: ["source:spun-underground-atlas-mycorrhizal-biodiversity"],
        },
        transferNodeIds: ["node:ecology:amazon-basin"],
        activeFieldLayerIds: ["field:spun:mycorrhizal-biodiversity"],
        metrics: { reliability: 0.38 },
        feasibility: { physical: 0.7, infrastructure: null, jurisdictional: null, operationalEvidence: 0.3 },
        constraints: [
          { kind: "missing_observation", refId: "missing:local-soil-sample-receipts", effect: "unknown" },
        ],
        confidence: 0.44,
        uncertainty: 0.55,
        claimTier: CLAIM_TIER,
        evidenceRefs: ["source:spun-underground-atlas-mycorrhizal-biodiversity"],
        missingEvidence: ["local_soil_sample_receipts", "ecosystem_connectivity_validation"],
        theoryBadgeIds: ["biophysics.membrane.open_system_entropy_flow"],
        zenNodeIds: ["analogy_only", "direct-observation-before-claim"],
      },
    ],
    observedFlows: [
      {
        flowId: "flow:sahara-amazon:dust:calipso-2007-2013",
        routeId: "route:atmospheric:sahara-amazon:dust",
        label: "CALIPSO multi-year Saharan dust transport observation",
        observedAt: "2015-02-22",
        quantityLabel: "satellite-estimated dust and phosphorus transport, variable by year",
        sourceRefs: ["source:nasa-calipso-sahara-amazon-dust"],
        confidence: 0.72,
        evidenceRefs: ["source:nasa-calipso-sahara-amazon-dust"],
        missingEvidence: ["current_year_plume_observation"],
        claimTier: "historical_observation",
      },
      {
        flowId: "flow:air:jfk-fra:fixture",
        routeId: "route:air:jfk-fra:wind-adjusted",
        label: "Fixture air corridor operational evidence placeholder",
        observedAt,
        quantityLabel: "schedule and delay receipts not attached",
        sourceRefs: ["fixture:air-corridor-placeholder"],
        confidence: 0.2,
        evidenceRefs: ["fixture:air-corridor-placeholder"],
        missingEvidence: ["flight_schedule_receipts", "delay_failure_receipts"],
        claimTier: CLAIM_TIER,
      },
    ],
  });
}
