import type { ProceduralMoralPatternRule } from "./procedural-rule-types";

export const CIVIC_ORDER_PROCEDURAL_RULES: readonly ProceduralMoralPatternRule[] = [
  {
    id: "participation-consent-separation",
    cues: [
      /\b(?:participation is not consent|participat\w* without consent|payment is not consent)\b/i,
      /\b(?:pays?|uses?|complies?|depends?)\b[\s\S]{0,90}\b(?:consent|endorsement|loyalty|agreement)\b/i,
    ],
    observedPattern: "unclear_evidence",
    moralRootId: "participation-consent-separation",
    proceduralMove: "ask_for_concrete_evidence",
    explanation: "Participation functions and dependency are separated from consent, endorsement, and loyalty before interpreting the order.",
    missingEvidence: ["participation_functions", "dependency_context", "consent_statement", "available_alternatives"],
    warnings: ["avoid_participation_as_consent", "avoid_dependence_as_loyalty"],
    reasonCodes: ["participation_consent_separation", "anti_inference"],
  },
  {
    id: "inherited-order-participation",
    cues: [/\b(?:born into|inherited order|inherited system|(?:order|system) was inherited|raised in|socialized into|entered by residence)\b/i],
    observedPattern: "identity_view",
    moralRootId: "inherited-order-participation",
    proceduralMove: "reframe_without_finality",
    explanation: "Inherited entry is separated from present participation and a person's current chosen position.",
    missingEvidence: ["entry_mode", "maturation_context", "alternatives_at_entry", "present_chosen_position"],
    warnings: ["avoid_birth_as_consent", "avoid_inheritance_as_identity"],
    reasonCodes: ["inherited_order_participation", "conditioning_check"],
  },
  {
    id: "proximity-norm-reciprocity",
    cues: [/\b(?:local norm|shared custom|peer expectation|proximity effect|norm reciprocity)\b/i],
    observedPattern: "unclear_evidence",
    moralRootId: "proximity-norm-reciprocity",
    proceduralMove: "identify_affected_parties",
    explanation: "A local norm is decomposed into source, status, scope, affected parties, enforcement, dissent, and review.",
    missingEvidence: ["norm_source", "norm_status", "affected_parties", "enforcement_channels", "dissent_path"],
    warnings: ["avoid_custom_as_justice", "avoid_regular_pattern_as_universal_rule"],
    reasonCodes: ["proximity_norm_reciprocity", "norm_decomposition"],
  },
  {
    id: "voice-exit-contestability",
    cues: [
      /\b(?:voice,? exit,? and contestability|voice path|feasible exit|formal exit|retaliation risk|reentry path)\b/i,
      /\b(?:cannot afford to leave|no affordable alternative|exit exists but)\b/i,
    ],
    observedPattern: "unconsidered_harm",
    moralRootId: "voice-exit-contestability",
    proceduralMove: "identify_affected_parties",
    explanation: "Formal options are separated from voice and exit paths that remain usable under real costs and retaliation risk.",
    missingEvidence: ["voice_path", "formal_exit_path", "feasible_exit_evidence", "retaliation_risk", "repair_or_reentry_path"],
    warnings: ["avoid_formal_exit_as_feasible_exit", "avoid_dissent_as_nonparticipation"],
    reasonCodes: ["voice_exit_contestability", "feasibility_check"],
  },
  {
    id: "adherence-legitimacy-separation",
    cues: [
      /\b(?:popularity is not legitimacy|compliance is not endorsement|stability is not justice|adherence is not legitimacy)\b/i,
      /\b(?:popular|stable|widely used|high compliance)\b[\s\S]{0,80}\b(?:legitimate|just|good)\b/i,
    ],
    observedPattern: "unclear_evidence",
    moralRootId: "adherence-legitimacy-separation",
    proceduralMove: "ask_for_concrete_evidence",
    explanation: "Adherence and stability remain descriptive signals until reasons, rights, contestability, and review are evidenced.",
    missingEvidence: ["support_signal", "rights_context", "justification", "contestability_path", "review_path"],
    warnings: ["avoid_popularity_as_legitimacy", "avoid_stability_as_justice"],
    reasonCodes: ["adherence_legitimacy_separation", "due_process"],
  },
  {
    id: "coordination-pluralism",
    cues: [
      /\b(?:coordination pluralism|allocation channel|authority channel|accountability channel)\b/i,
      /\b(?:capitalism|socialism|communism|market|command|cooperative)\b[\s\S]{0,120}\b(?:compare|mechanism|channel|order)\b/i,
    ],
    observedPattern: "unclear_evidence",
    moralRootId: "coordination-pluralism",
    proceduralMove: "ask_for_concrete_evidence",
    explanation: "A labeled order is routed toward a multi-channel mechanism profile rather than an ideology ranking.",
    missingEvidence: ["allocation_channels", "authority_channels", "accountability_channels", "channel_roles"],
    warnings: ["avoid_ideology_label_as_mechanism", "avoid_ideology_rank"],
    reasonCodes: ["coordination_pluralism", "mechanism_profile"],
  },
];
