import type { ProceduralMoralPatternRule } from "./procedural-rule-types";

export const PROVISIONING_PROCEDURAL_RULES: readonly ProceduralMoralPatternRule[] = [
  {
    id: "need-before-allocation",
    cues: [
      /\b(?:need before allocation|viability need|need primitive|present coverage|viability threshold)\b/i,
      /\b(?:organism|plant|cell|biology)\b[\s\S]{0,100}\b(?:tax|budget|government|policy|hierarchy)\b/i,
    ],
    observedPattern: "unclear_evidence",
    moralRootId: "need-before-allocation",
    proceduralMove: "ask_for_concrete_evidence",
    explanation: "Biological continuity can identify bounded needs and dependencies, but allocation and policy remain separate evidence questions.",
    missingEvidence: ["need_primitive", "viability_threshold", "present_coverage", "affected_agents", "time_horizon"],
    warnings: ["avoid_biology_as_policy", "avoid_universal_budget"],
    reasonCodes: ["need_before_allocation", "biological_policy_boundary"],
  },
  {
    id: "efficiency-without-erasure",
    cues: [
      /\b(?:efficiency without erasure|overall efficiency score|civilization balance score|pareto frontier)\b/i,
      /\b(?:most efficient|best civilization|best country)\b/i,
    ],
    observedPattern: "unclear_evidence",
    moralRootId: "efficiency-without-erasure",
    proceduralMove: "ask_for_concrete_evidence",
    explanation: "Efficiency is routed toward an explicit lens and a vector of flows, distribution, resilience, rights, maintenance, and uncertainty.",
    missingEvidence: ["selected_lens", "flow_measurements", "externalities", "burden_groups", "beneficiary_groups"],
    warnings: ["avoid_scalar_civilization_ranking", "avoid_distribution_erasure"],
    reasonCodes: ["efficiency_without_erasure", "anti_scalar"],
  },
  {
    id: "mandate-bounded-hierarchy",
    cues: [/\b(?:mandate[-\s]?bounded hierarchy|delegated authority|role delegation|authority scope|reviewable mandate)\b/i],
    observedPattern: "unconsidered_harm",
    moralRootId: "mandate-bounded-hierarchy",
    proceduralMove: "identify_affected_parties",
    explanation: "Role authority is bounded by demand evidence, function, safety, compensation, exit, retraining, and review.",
    missingEvidence: ["demand_evidence", "assignment_mode", "authority_scope", "safety_checks", "review_path"],
    warnings: ["avoid_specialization_as_unbounded_power", "avoid_role_as_personal_worth"],
    reasonCodes: ["mandate_bounded_hierarchy", "delegation_review"],
  },
  {
    id: "legible-rules-bounded-confidentiality",
    cues: [/\b(?:legible rules|bounded confidentiality|secret privilege|confidentiality scope|opaque allocation)\b/i],
    observedPattern: "unclear_evidence",
    moralRootId: "legible-rules-bounded-confidentiality",
    proceduralMove: "ask_for_concrete_evidence",
    explanation: "Confidentiality is treated as a bounded risk control, not permission to hide governing rules or burdens.",
    missingEvidence: ["published_rules", "confidentiality_scope", "risk_justification", "review_or_sunset"],
    warnings: ["avoid_secret_privilege", "avoid_confidentiality_without_scope"],
    reasonCodes: ["legible_rules_bounded_confidentiality", "reviewable_secrecy"],
  },
  {
    id: "cooperation-without-assimilation",
    cues: [/\b(?:cooperation without assimilation|cross[-\s]?jurisdiction cooperation|shared research project|shared infrastructure project)\b/i],
    observedPattern: "unconsidered_harm",
    moralRootId: "cooperation-without-assimilation",
    proceduralMove: "identify_affected_parties",
    explanation: "Shared projects are decomposed into contributions, benefits, maintenance, standards, knowledge policy, disputes, and retained agency.",
    missingEvidence: ["participating_jurisdictions", "contribution_map", "benefit_map", "maintenance_commitments", "dispute_and_exit_paths"],
    warnings: ["avoid_cooperation_as_assimilation", "avoid_exitless_coordination"],
    reasonCodes: ["cooperation_without_assimilation", "jurisdictional_agency"],
  },
  {
    id: "specialization-without-caste",
    cues: [/\b(?:specialization without caste|inherited occupation|fixed social role|occupational caste|retraining path)\b/i],
    observedPattern: "identity_view",
    moralRootId: "specialization-without-caste",
    proceduralMove: "reframe_without_finality",
    explanation: "Specialization is treated as a revisable function assignment rather than a fixed identity, inherited status, or measure of worth.",
    missingEvidence: ["assignment_mode", "mobility_path", "safety_and_compensation", "retraining_path", "review_date"],
    warnings: ["avoid_role_as_caste", "avoid_occupation_as_human_worth"],
    reasonCodes: ["specialization_without_caste", "role_mobility"],
  },
];
