import type { HelixAskComposerActionToolbarSurfaceProps } from "./HelixAskComposerActionToolbarSurface";

export type HelixAskComposerActionToolbarState = HelixAskComposerActionToolbarSurfaceProps;

export type HelixAskComposerActionToolbarStateOptions = HelixAskComposerActionToolbarSurfaceProps;

export function buildHelixAskComposerActionToolbarState({
  carouselRef,
  imageInputRef,
  canScrollLeft,
  canScrollRight,
  onScrollLeft,
  onScrollRight,
  onImageSelect,
  onAttachImage,
  attachDisabled,
  hasReadyAttachment,
  hasAnyAttachment,
  micEnabled,
  voiceTranscribing,
  onToggleMic,
  showRetryVoiceSample,
  retryVoiceSampleDisabled,
  onRetryVoiceSample,
  showVisualCaptureControls,
  visualSituationSourceStatus,
  onCaptureVisualSource,
  visualSituationIncludeAudio,
  displayAudioStatus,
  visualAudioToggleDisabled,
  onToggleVisualAudio,
  runtimePickerModel,
  runtimeMenuOpen,
  onRuntimePrimaryClick,
  onRuntimeSelect,
  liveRuntimeControlsModel,
  submitViewModel,
  onSubmitIntent,
  onStop,
}: HelixAskComposerActionToolbarStateOptions): HelixAskComposerActionToolbarState {
  return {
    carouselRef,
    imageInputRef,
    canScrollLeft,
    canScrollRight,
    onScrollLeft,
    onScrollRight,
    onImageSelect,
    onAttachImage,
    attachDisabled,
    hasReadyAttachment,
    hasAnyAttachment,
    micEnabled,
    voiceTranscribing,
    onToggleMic,
    showRetryVoiceSample,
    retryVoiceSampleDisabled,
    onRetryVoiceSample,
    showVisualCaptureControls,
    visualSituationSourceStatus,
    onCaptureVisualSource,
    visualSituationIncludeAudio,
    displayAudioStatus,
    visualAudioToggleDisabled,
    onToggleVisualAudio,
    runtimePickerModel,
    runtimeMenuOpen,
    onRuntimePrimaryClick,
    onRuntimeSelect,
    liveRuntimeControlsModel,
    submitViewModel,
    onSubmitIntent,
    onStop,
  };
}
