package com.casimirbot.helixsensor.fabric;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

final class FabricFallRescueControllerTest {
    @Test
    void admitsOnlyAnUnprotectedSurvivalFall() {
        assertTrue(
            FabricFallRescueController.shouldAttempt(
                4.0d,
                -0.6d,
                false,
                false,
                false,
                false,
                false
            )
        );
        assertFalse(
            FabricFallRescueController.shouldAttempt(
                2.0d,
                -0.6d,
                false,
                false,
                false,
                false,
                false
            )
        );
        assertFalse(
            FabricFallRescueController.shouldAttempt(
                4.0d,
                -0.6d,
                true,
                false,
                false,
                false,
                false
            )
        );
        assertFalse(
            FabricFallRescueController.shouldAttempt(
                4.0d,
                -0.6d,
                false,
                true,
                false,
                false,
                false
            )
        );
        assertFalse(
            FabricFallRescueController.shouldAttempt(
                4.0d,
                -0.6d,
                false,
                false,
                false,
                false,
                true
            )
        );
        assertFalse(
            FabricFallRescueController.shouldAttempt(
                4.0d,
                -0.6d,
                false,
                false,
                true,
                false,
                false
            )
        );
        assertFalse(
            FabricFallRescueController.shouldAttempt(
                4.0d,
                -0.6d,
                false,
                false,
                false,
                true,
                false
            )
        );
        assertFalse(
            FabricFallRescueController.shouldAttempt(
                4.0d,
                -0.2d,
                false,
                false,
                false,
                false,
                false
            )
        );
    }
}
