import type { HelixCapabilityLaneTemplate } from "./lane-template";

export const workstationToolReferenceLaneTemplate: HelixCapabilityLaneTemplate = {
  lane_id: "workstation_tool_reference",
  family: "workstation_tool_reference",
  label: "Workstation tool reference",
  description: "Reference lane for the existing workstation gateway catalog; no tool migration occurs here.",
  backend_family: "helix_workstation_gateway",
  model_or_service_ref: "workstation_gateway_existing",
  safety_tags: ["existing_gateway_reference", "no_lane_reroute", "observation_or_receipt_only"],
  configured: () => true,
  cost_class: "free_local",
  latency_class: "local",
  privacy_class: "local_only",
  one_shot_supported: true,
  session_supported: false,
  goal_binding_supported: false,
  capabilities: [
    {
      capability_id: "workstation_tool_reference.list_capabilities",
      label: "List workstation gateway capabilities",
      one_shot_status: "executable",
      session_status: "not_supported",
      backend_provider_required: false,
      model_visible_hint: {
        required_input_fields: [],
        optional_input_fields: ["requested_backend_provider"],
        when_to_use:
          "Use to inspect the governed workstation gateway capability catalog as observation-only reference data.",
        request_shape_hint: {
          capability_lane_call: {
            capability: "workstation_tool_reference.list_capabilities",
          },
        },
      },
    },
    {
      capability_id: "workstation_tool_reference.collect_visible_translation_targets",
      label: "Collect visible translation targets",
      one_shot_status: "executable",
      session_status: "not_supported",
      backend_provider_required: false,
      model_visible_hint: {
        required_input_fields: [],
        optional_input_fields: [
          "active_panel_id",
          "doc_path",
          "source_hash",
          "projection_target",
          "account_locale",
          "target_language",
          "max_chunks",
          "visible_only",
          "selected_text",
          "selection_ref",
          "hover_text",
          "hover_ref",
          "active_region_text",
          "active_region_ref",
          "visible_text",
          "title_text",
          "body_text",
          "visible_text_chunks",
          "ui_text_regions",
          "panel_text_regions",
          "visible_ui_text_regions",
          "active_doc_visible_translation_context",
          "workspace_context_snapshot",
          "requested_backend_provider",
        ],
        when_to_use:
          "Use when the user asks to translate visible UI, the active document, current selection, hovered content, or account-language UI regions. It only collects visible source chunks; translate admitted chunks separately with live_translation.translate_text. Do not use it for arbitrary unseen files or whole-repo translation.",
        when_not_to_use:
          "Do not use for arbitrary unseen files, whole-repo translation, direct text translation without a visible source, or as a substitute for live_translation.translate_text. A collected target is source evidence, not translated text or final answer authority.",
        request_shape_hint: {
          capability_lane_call: {
            capability: "workstation_tool_reference.collect_visible_translation_targets",
            visible_only: true,
            max_chunks: 12,
            active_doc_visible_translation_context:
              "workspace_context_snapshot.active_doc_visible_translation_context",
          },
        },
      },
    },
    {
      capability_id: "workstation.visible_text.collect_translation_targets",
      label: "Collect visible text translation targets",
      one_shot_status: "executable",
      session_status: "not_supported",
      backend_provider_required: false,
      model_visible_hint: {
        required_input_fields: [],
        optional_input_fields: [
          "active_panel_id",
          "doc_path",
          "source_hash",
          "projection_target",
          "account_locale",
          "target_language",
          "max_chunks",
          "visible_only",
          "selected_text",
          "selection_ref",
          "hover_text",
          "hover_ref",
          "active_region_text",
          "active_region_ref",
          "visible_text",
          "title_text",
          "body_text",
          "visible_text_chunks",
          "ui_text_regions",
          "panel_text_regions",
          "visible_ui_text_regions",
          "active_doc_visible_translation_context",
          "workspace_context_snapshot",
          "requested_backend_provider",
        ],
        when_to_use:
          "Provider-neutral alias for collecting visible source chunks when the user asks to translate the visible document, selected content, hovered content, account-language UI regions, or visible workstation text. It only collects source chunks; translate admitted chunks separately with live_translation.translate_text.",
        when_not_to_use:
          "Do not use for arbitrary unseen files, whole-repo translation, direct text translation without a visible source, or as a substitute for live_translation.translate_text. A collected target is source evidence, not translated text or final answer authority.",
        request_shape_hint: {
          capability_lane_call: {
            capability: "workstation.visible_text.collect_translation_targets",
            visible_only: true,
            max_chunks: 12,
            active_doc_visible_translation_context:
              "workspace_context_snapshot.active_doc_visible_translation_context",
          },
        },
      },
    },
  ],
};
