export const hasAskTurnLiveSourceStandingWatchCue = (transcript: string): boolean =>
  /\b(?:watch|monitor|track|keep\s+watching|keep\s+an\s+eye\s+on|keep\s+watch|observe)\b[\s\S]{0,180}\b(?:describe|tell\s+me|summari[sz]e|announce|notify|speak|call\s*out|callout|report)\b[\s\S]{0,180}\b(?:mail\s+batch|new\s+mail|summary|summaries|observed|observation|changes?|happens?|important|source|visual|screen|this)\b/i.test(transcript) ||
  /\b(?:watch|monitor|track|keep\s+watching|keep\s+an\s+eye\s+on|keep\s+watch|observe)\b[\s\S]{0,180}\b(?:mail\s+batch|new\s+mail|summary|summaries|observed|observation|changes?|happens?|important|source|visual|screen|this)\b[\s\S]{0,180}\b(?:describe|tell\s+me|summari[sz]e|announce|notify|speak|call\s*out|callout|report)\b/i.test(transcript) ||
  /\b(?:watch|monitor|track|keep\s+watching|keep\s+an\s+eye\s+on|observe)\b[\s\S]{0,180}\b(?:interpret|compare|what\s+changed|what\s+is\s+happening|watch\s+next|predict|story\s+so\s+far)\b[\s\S]{0,180}\b(?:mail|summary|summaries|observation|source|visual|screen|this)\b/i.test(transcript) ||
  /\b(?:interpret|compare|what\s+changed|what\s+is\s+happening|watch\s+next|predict|story\s+so\s+far)\b[\s\S]{0,180}\b(?:mail|summary|summaries|observation|source|visual|screen|this)\b[\s\S]{0,180}\b(?:watch|monitor|track|keep\s+watching|observe)\b/i.test(transcript) ||
  /\b(?:watch|monitor|track|keep\s+watching|keep\s+an\s+eye\s+on|observe)\b[\s\S]{0,220}\b(?:minecraft\s+video\s+predictor|predictor\s+contract|prediction\s+watch|micro[-\s]?batch(?:es)?|chronological\s+micro[-\s]?batch(?:es)?|interpretation\s+contract)\b/i.test(transcript) ||
  /\b(?:every\s+time|whenever|when)\b[\s\S]{0,120}\b(?:summary|summaries|mail|mail\s+batch|update|observation|visual|source|it)\b[\s\S]{0,120}\b(?:comes?\s+in|arrives?|changes?|updates?|happens?|describe|tell\s+me|announce|notify|speak|report)\b/i.test(transcript) ||
  /\b(?:summary|summaries|mail|mail\s+batch|update|observation)\b[\s\S]{0,120}\b(?:comes?\s+in|arrives?|changes?|updates?)\b[\s\S]{0,120}\b(?:describe|tell\s+me|announce|notify|speak|report)\b/i.test(transcript) ||
  /\b(?:announce|notify|speak|call\s*out|callout|tell\s+me)\b[\s\S]{0,60}\bif\b[\s\S]{0,140}\b(?:anything\s+important|something\s+important|something\s+changes?|it\s+changes?|source\s+changes?|visual\s+changes?|screen\s+changes?|happens?)\b/i.test(transcript) ||
  /\bkeep\s+an\s+eye\s+on\s+(?:this|the\s+(?:visual|screen|source|capture|mailbox))\b/i.test(transcript);
