#!/usr/bin/env python3
"""Estimate the coherent misalignment amplitude for a 1e-17 eV field.

Sudden-oscillation, harmonic-potential screen only. It does not evolve a
specific pNGB potential, generate U(1) charge, or form boson stars.
"""
from __future__ import annotations

import json
import math
from pathlib import Path
from math import gamma

M_PHI_EV = 1.0e-17
M_PHI_GEV = M_PHI_EV * 1.0e-9
OMEGA_DM_H2 = 0.1198
H_REDUCED = 0.674
H0_KM_S_MPC = 67.4
M_REDUCED_GEV = 2.435e18
M_PLANCK_GEV = 1.22089e19
T0_GEV = 2.348e-13  # 2.7255 K
G_S0 = 3.91
F_PNGB_GEV = 6.7e17  # prior dilute-star scaling proxy, not a measured scale
KAPPA_ONSET = (1.0, 3.0)  # H=m and 3H=m onset conventions
G_STAR = (3.36, 10.75)
G_STAR_S = (3.91, 10.75)
FRACTIONS = (0.10, 1.0)
HBAR_GEV_S = 6.582119569e-25
MPC_KM = 3.0856775814913673e19
BESSEL_LATE_AMPLITUDE = 2.0**0.25 * gamma(1.25) * math.sqrt(2.0 / math.pi)

H0_GEV = H0_KM_S_MPC / MPC_KM * HBAR_GEV_S
RHO_CRIT0_GEV4 = 3.0 * H0_GEV**2 * M_REDUCED_GEV**2
OMEGA_DM = OMEGA_DM_H2 / H_REDUCED**2

rows = []
for kappa in KAPPA_ONSET:
    for g_star in G_STAR:
        temperature_gev = math.sqrt(
            (M_PHI_GEV / kappa) * M_PLANCK_GEV / (1.66 * math.sqrt(g_star))
        )
        for g_star_s in G_STAR_S:
            scale_factor = (T0_GEV / temperature_gev) * (G_S0 / g_star_s) ** (1.0 / 3.0)
            rho_dm_today = OMEGA_DM * RHO_CRIT0_GEV4
            for f_phi in FRACTIONS:
                rho_phi_today = f_phi * rho_dm_today
                phi_amplitude_gev = math.sqrt(
                    2.0 * rho_phi_today / (M_PHI_GEV**2 * scale_factor**3)
                )
                # In fixed-g* radiation domination, y(x)=phi/phi_i is
                # 2^(1/4) Gamma(5/4) x^(-1/4) J_(1/4)(x), with late envelope
                # A*x^(-3/4). Normalize the conserved a^3 rho_osc to today.
                x_reference = kappa / 2.0  # H=1/(2t), x=m*t
                phi_initial_exact_gev = (
                    phi_amplitude_gev
                    * x_reference**0.75
                    / BESSEL_LATE_AMPLITUDE
                )
                rho_r_osc = (math.pi**2 / 30.0) * g_star * temperature_gev**4
                rho_phi_osc = rho_phi_today / scale_factor**3
                rows.append({
                    "onset_condition_kappa_H_equals_m": kappa,
                    "g_star_energy": g_star,
                    "g_star_entropy": g_star_s,
                    "f_phi_of_total_DM": f_phi,
                    "T_osc_MeV": temperature_gev * 1.0e3,
                    "a_osc": scale_factor,
                    "phi_amplitude_at_oscillation_GeV": phi_amplitude_gev,
                    "phi_amplitude_over_reduced_Planck": phi_amplitude_gev / M_REDUCED_GEV,
                    "theta_if_f_6p7e17_GeV": phi_amplitude_gev / F_PNGB_GEV,
                    "initial_frozen_field_amplitude_exact_constant_g_GeV": phi_initial_exact_gev,
                    "initial_theta_if_f_6p7e17_GeV": phi_initial_exact_gev / F_PNGB_GEV,
                    "rho_phi_over_radiation_at_oscillation": rho_phi_osc / rho_r_osc,
                })

result = {
    "status": "conditional homogeneous-field abundance estimate; not a full cosmological evolution",
    "assumptions": {
        "standard_radiation_dominated_expansion": True,
        "constant_mass_harmonic_potential": True,
        "sudden_oscillation": "3H~m or H~m; both conventions included",
        "entropy_relation": "a*T*g_star_s^(1/3)=constant",
        "temperature_degrees_of_freedom": "bracketed independently across the e+e- annihilation transition; envelope is conservative, not a precision thermal-history trajectory",
        "initial_condition": "homogeneous misalignment amplitude, negligible initial velocity",
        "charge": "no conserved U(1) charge/asymmetry is generated by this calculation",
        "structure_formation": "not modeled; cosmic field fraction is not compact-star fraction",
    },
    "inputs": {
        "m_phi_eV": M_PHI_EV,
        "Omega_DM_h2": OMEGA_DM_H2,
        "h": H_REDUCED,
        "f_phi_grid": list(FRACTIONS),
        "f_pNGB_GeV_reference": F_PNGB_GEV,
    },
    "rows": rows,
    "summary": {
        "f_phi_0p1_phi_amplitude_GeV_envelope": [
            min(r["phi_amplitude_at_oscillation_GeV"] for r in rows if r["f_phi_of_total_DM"] == 0.1),
            max(r["phi_amplitude_at_oscillation_GeV"] for r in rows if r["f_phi_of_total_DM"] == 0.1),
        ],
        "f_phi_0p1_theta_f_6p7e17_envelope": [
            min(r["theta_if_f_6p7e17_GeV"] for r in rows if r["f_phi_of_total_DM"] == 0.1),
            max(r["theta_if_f_6p7e17_GeV"] for r in rows if r["f_phi_of_total_DM"] == 0.1),
        ],
        "f_phi_0p1_initial_frozen_amplitude_constant_g_GeV_envelope": [
            min(r["initial_frozen_field_amplitude_exact_constant_g_GeV"] for r in rows if r["f_phi_of_total_DM"] == 0.1),
            max(r["initial_frozen_field_amplitude_exact_constant_g_GeV"] for r in rows if r["f_phi_of_total_DM"] == 0.1),
        ],
        "f_phi_0p1_initial_theta_f_6p7e17_envelope": [
            min(r["initial_theta_if_f_6p7e17_GeV"] for r in rows if r["f_phi_of_total_DM"] == 0.1),
            max(r["initial_theta_if_f_6p7e17_GeV"] for r in rows if r["f_phi_of_total_DM"] == 0.1),
        ],
        "f_phi_0p1_rho_fraction_at_oscillation_envelope": [
            min(r["rho_phi_over_radiation_at_oscillation"] for r in rows if r["f_phi_of_total_DM"] == 0.1),
            max(r["rho_phi_over_radiation_at_oscillation"] for r in rows if r["f_phi_of_total_DM"] == 0.1),
        ],
        "T_osc_MeV_envelope": [min(r["T_osc_MeV"] for r in rows), max(r["T_osc_MeV"] for r in rows)],
    },
    "limitations": [
        "The amplitude uses a sudden-onset approximation; numerical integration through H~m changes it by an order-one factor.",
        "The g* and entropy brackets span the e+e- annihilation era but are not correlated by a finite-temperature equation of state.",
        "The analytic Bessel-function correction is exact only for constant-g radiation domination; the independently bracketed g* grid is not a self-consistent e+e- thermal history.",
        "This is a real coherent energy-density budget only. It does not provide the nonzero U(1) charge needed for a charged complex boson star.",
        "It does not solve isocurvature, perturbation transfer, self-interaction, BBN/CMB likelihoods, galactic structure formation, or boson-star production.",
        "No IDM portal or Casimir-DP laboratory response is generated by this separate-production estimate.",
    ],
}

out = Path(__file__).with_suffix(".json")
out.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
print(json.dumps(result, indent=2))
