export {
  buildIdeologyContextReflectionV1,
  isIdeologyContextReflectionV1,
  validateIdeologyContextReflectionV1,
  IDEOLOGY_CONTEXT_REFLECTION_ARTIFACT_ID,
  IDEOLOGY_CONTEXT_REFLECTION_GRAPH_SOURCE,
  IDEOLOGY_CONTEXT_REFLECTION_INPUT_KINDS,
  IDEOLOGY_CONTEXT_REFLECTION_SCHEMA_VERSION,
  IDEOLOGY_CONTEXT_REFLECTION_TENSION_SEVERITIES,
  type IdeologyActivatedTraitV1,
  type IdeologyContextReflectionActionGateWarningV1,
  type IdeologyContextReflectionAuthorityV1,
  type IdeologyContextReflectionClaimBoundariesV1,
  type IdeologyContextReflectionInputKindV1,
  type IdeologyContextReflectionOverlayV1,
  type IdeologyContextReflectionRecommendedActionV1,
  type IdeologyContextReflectionTensionSeverityV1,
  type IdeologyContextReflectionTensionV1,
  type IdeologyContextReflectionV1,
  type IdeologyNodeMatchV1,
} from "./contracts/ideology-context-reflection.v1";
