export const MATH_STAGE_LEVELS = {
  exploratory: 0,
  "reduced-order": 1,
  diagnostic: 2,
  certified: 3,
} as const;

export type MathStage = keyof typeof MATH_STAGE_LEVELS;

export type MathCheckType =
  | "test"
  | "policy"
  | "snapshot"
  | "doc"
  | "residual"
  | "stability";

export type MathCheck = {
  type: MathCheckType;
  path: string;
  note?: string;
};

export type UnitSignature = Record<string, string>;

export type MathStageEntry = {
  tag: string;
  module: string;
  stage: MathStage;
  notes?: string;
  checks?: MathCheck[];
  units?: UnitSignature;
  residualsRequired?: boolean;
};

export const mathStageRegistry: MathStageEntry[] = [
  {
    tag: "GR_CORE",
    module: "modules/gr/bssn-state.ts",
    stage: "diagnostic",
    notes: "Grid + BSSN state definitions.",
    checks: [
      { type: "residual", path: "tests/gr-constraint-network.spec.ts" },
      { type: "stability", path: "tests/gr-constraint-network.spec.ts" },       
    ],
    residualsRequired: false,
    units: {
      spacing: "L",
      bounds: "L",
      alpha: "1",
      beta_x: "1",
      beta_y: "1",
      beta_z: "1",
      gamma_xx: "1",
      gamma_yy: "1",
      gamma_zz: "1",
    },
  },
  {
    tag: "GR_CORE",
    module: "modules/gr/bssn-evolve.ts",
    stage: "diagnostic",
    notes: "BSSN evolution + constraint fields.",
    checks: [
      { type: "residual", path: "tests/gr-constraint-gate.spec.ts" },
      { type: "stability", path: "tests/gr-constraint-network.spec.ts" },       
    ],
    units: {
      dt: "T",
      time_s: "T",
      evolveDt_s: "T",
      spacing: "L",
      bounds: "L",
      H: "1",
      M: "1",
      Mx: "1",
      My: "1",
      Mz: "1",
      Mx: "1",
      My: "1",
      Mz: "1",
      Mx: "1",
      My: "1",
      Mz: "1",
      Mx: "1",
      My: "1",
      Mz: "1",
      Mx: "1",
      My: "1",
      Mz: "1",
      H_rms: "1",
      M_rms: "1",
      H_maxAbs: "1",
      M_maxAbs: "1",
      cfl: "1",
      gap_nm: "L",
      gap_m: "L",
      tileArea_cm2: "L^2",
      tileArea_m2: "L^2",
      tileCount: "1",
      dutyCycle: "1",
      dutyEffectiveFR: "1",
      dutyEff: "1",
      gammaGeo: "1",
      gammaVanDenBroeck: "1",
      qSpoilingFactor: "1",
      cavityQ: "1",
      U_static_J: "M L^2 T^-2",
      staticEnergy: "M L^2 T^-2",
      boostedEnergy: "M L^2 T^-2",
      cycleAverageEnergy: "M L^2 T^-2",
      totalEnergy_J: "M L^2 T^-2",
      exoticEnergyDensity: "M L^-1 T^-2",
      P_avg_W: "M L^2 T^-3",
      instantaneousPower: "M L^2 T^-3",
      averagePower: "M L^2 T^-3",
      modulationFreq_GHz: "T^-1",
      burst_us: "T",
      cycle_us: "T",
      T00: "M L^-1 T^-2",
      T11: "M L^-1 T^-2",
      T22: "M L^-1 T^-2",
      T33: "M L^-1 T^-2",
      T00_avg: "M L^-1 T^-2",
      T11_avg: "M L^-1 T^-2",
      T22_avg: "M L^-1 T^-2",
      T33_avg: "M L^-1 T^-2",
      rho_avg: "M L^-1 T^-2",
      rho_inst: "M L^-1 T^-2",
      rho: "M L^-1 T^-2",
      stressEnergyT00_inst: "M L^-1 T^-2",
      beta_avg: "1",
      sectorStrobingEfficiency: "1",
      homogenizationRatio: "1",
      metric: "1",
    },
  },
  {
    tag: "GR_CORE",
    module: "server/gr/evolution/solver.ts",
    stage: "diagnostic",
    notes: "Runs BSSN evolution (diagnostic).",
    checks: [
      { type: "residual", path: "tests/gr-constraint-network.spec.ts" },
      { type: "stability", path: "tests/gr-constraint-network.spec.ts" },       
    ],
    units: {
      dt: "T",
      evolveDt_s: "T",
      time_s: "T",
      spacing: "L",
      bounds: "L",
      H: "1",
      M: "1",
      Mx: "1",
      My: "1",
      Mz: "1",
      gap_nm: "L",
      gap_m: "L",
      tileArea_cm2: "L^2",
      tileArea_m2: "L^2",
      tileCount: "1",
      dutyCycle: "1",
      dutyEffectiveFR: "1",
      dutyEff: "1",
      gammaGeo: "1",
      gammaVanDenBroeck: "1",
      qSpoilingFactor: "1",
      cavityQ: "1",
      U_static_J: "M L^2 T^-2",
      staticEnergy: "M L^2 T^-2",
      boostedEnergy: "M L^2 T^-2",
      cycleAverageEnergy: "M L^2 T^-2",
      totalEnergy_J: "M L^2 T^-2",
      exoticEnergyDensity: "M L^-1 T^-2",
      T00: "M L^-1 T^-2",
      T11: "M L^-1 T^-2",
      T22: "M L^-1 T^-2",
      T33: "M L^-1 T^-2",
      T00_avg: "M L^-1 T^-2",
      T11_avg: "M L^-1 T^-2",
      T22_avg: "M L^-1 T^-2",
      T33_avg: "M L^-1 T^-2",
      rho_avg: "M L^-1 T^-2",
      rho_inst: "M L^-1 T^-2",
      rho: "M L^-1 T^-2",
      rho: "M L^-1 T^-2",
      rho: "M L^-1 T^-2",
      rho: "M L^-1 T^-2",
      rho: "M L^-1 T^-2",
      stressEnergyT00_inst: "M L^-1 T^-2",
      beta_avg: "1",
      P_avg_W: "M L^2 T^-3",
      instantaneousPower: "M L^2 T^-3",
      averagePower: "M L^2 T^-3",
      modulationFreq_GHz: "T^-1",
      burst_us: "T",
      cycle_us: "T",
      sectorStrobingEfficiency: "1",
      homogenizationRatio: "1",
      metric: "1",
      H_rms: "1",
      M_rms: "1",
      H_maxAbs: "1",
      M_maxAbs: "1",
      cfl: "1",
      rho: "M L^-1 T^-2",
    },
  },
  {
    tag: "GR_CORE",
    module: "server/gr-evolve-brick.ts",
    stage: "diagnostic",
    notes: "Builds GR diagnostics + residuals.",
    checks: [
      { type: "residual", path: "tests/gr-constraint-gate.spec.ts" },
      { type: "stability", path: "tests/gr-constraint-network.spec.ts" },       
    ],
    units: {
      dt: "T",
      time_s: "T",
      evolveDt_s: "T",
      spacing: "L",
      bounds: "L",
      H: "1",
      M: "1",
      Mx: "1",
      My: "1",
      Mz: "1",
      gap_nm: "L",
      gap_m: "L",
      tileArea_cm2: "L^2",
      tileArea_m2: "L^2",
      tileCount: "1",
      dutyCycle: "1",
      dutyEffectiveFR: "1",
      dutyEff: "1",
      gammaGeo: "1",
      gammaVanDenBroeck: "1",
      qSpoilingFactor: "1",
      cavityQ: "1",
      U_static_J: "M L^2 T^-2",
      staticEnergy: "M L^2 T^-2",
      boostedEnergy: "M L^2 T^-2",
      cycleAverageEnergy: "M L^2 T^-2",
      totalEnergy_J: "M L^2 T^-2",
      exoticEnergyDensity: "M L^-1 T^-2",
      T00: "M L^-1 T^-2",
      T11: "M L^-1 T^-2",
      T22: "M L^-1 T^-2",
      T33: "M L^-1 T^-2",
      T00_avg: "M L^-1 T^-2",
      T11_avg: "M L^-1 T^-2",
      T22_avg: "M L^-1 T^-2",
      T33_avg: "M L^-1 T^-2",
      rho_avg: "M L^-1 T^-2",
      rho_inst: "M L^-1 T^-2",
      rho: "M L^-1 T^-2",
      stressEnergyT00_inst: "M L^-1 T^-2",
      beta_avg: "1",
      P_avg_W: "M L^2 T^-3",
      instantaneousPower: "M L^2 T^-3",
      averagePower: "M L^2 T^-3",
      modulationFreq_GHz: "T^-1",
      burst_us: "T",
      cycle_us: "T",
      sectorStrobingEfficiency: "1",
      homogenizationRatio: "1",
      metric: "1",
      H_rms: "1",
      M_rms: "1",
      H_maxAbs: "1",
      M_maxAbs: "1",
      cfl: "1",
    },
  },
  {
    tag: "GR_GATE",
    module: "server/gr/constraint-evaluator.ts",
    stage: "certified",
    notes: "GR gate evaluation from diagnostics.",
    checks: [
      { type: "test", path: "tests/gr-constraint-gate.spec.ts" },
      { type: "policy", path: "WARP_AGENTS.md" },
    ],
    units: {
      H_rms: "1",
      M_rms: "1",
      H_maxAbs: "1",
      M_maxAbs: "1",
      dt: "T",
      time_s: "T",
      evolveDt_s: "T",
      spacing: "L",
      bounds: "L",
      H: "1",
      M: "1",
      Mx: "1",
      My: "1",
      Mz: "1",
      cfl: "1",
      gap_nm: "L",
      gap_m: "L",
      tileArea_cm2: "L^2",
      tileArea_m2: "L^2",
      tileCount: "1",
      dutyCycle: "1",
      dutyEffectiveFR: "1",
      dutyEff: "1",
      gammaGeo: "1",
      gammaVanDenBroeck: "1",
      qSpoilingFactor: "1",
      cavityQ: "1",
      U_static_J: "M L^2 T^-2",
      staticEnergy: "M L^2 T^-2",
      boostedEnergy: "M L^2 T^-2",
      cycleAverageEnergy: "M L^2 T^-2",
      totalEnergy_J: "M L^2 T^-2",
      exoticEnergyDensity: "M L^-1 T^-2",
      P_avg_W: "M L^2 T^-3",
      instantaneousPower: "M L^2 T^-3",
      averagePower: "M L^2 T^-3",
      modulationFreq_GHz: "T^-1",
      burst_us: "T",
      cycle_us: "T",
      T00: "M L^-1 T^-2",
      T11: "M L^-1 T^-2",
      T22: "M L^-1 T^-2",
      T33: "M L^-1 T^-2",
      T00_avg: "M L^-1 T^-2",
      T11_avg: "M L^-1 T^-2",
      T22_avg: "M L^-1 T^-2",
      T33_avg: "M L^-1 T^-2",
      rho_avg: "M L^-1 T^-2",
      rho_inst: "M L^-1 T^-2",
      rho: "M L^-1 T^-2",
      stressEnergyT00_inst: "M L^-1 T^-2",
      beta_avg: "1",
      sectorStrobingEfficiency: "1",
      homogenizationRatio: "1",
      metric: "1",
    },
  },
  {
    tag: "GR_GATE",
    module: "server/gr/gr-evaluation.ts",
    stage: "certified",
    notes: "Gate + certificate checks (policy).",
    checks: [
      { type: "test", path: "tests/gr-agent-loop.spec.ts" },
      { type: "policy", path: "WARP_AGENTS.md" },
    ],
  },
  {
    tag: "GR_LOOP",
    module: "server/gr/gr-agent-loop.ts",
    stage: "certified",
    notes: "Orchestration + acceptance gate.",
    checks: [
      { type: "test", path: "tests/gr-agent-loop.spec.ts" },
      { type: "test", path: "tests/gr-agent-loop-baseline.spec.ts" },
      { type: "policy", path: "WARP_AGENTS.md" },
    ],
    units: {
      evolveDt_s: "T",
      dt: "T",
      time_s: "T",
      spacing: "L",
      bounds: "L",
      cfl: "1",
      H_rms: "1",
      M_rms: "1",
      H_maxAbs: "1",
      M_maxAbs: "1",
      H: "1",
      M: "1",
      Mx: "1",
      My: "1",
      Mz: "1",
      gap_nm: "L",
      gap_m: "L",
      tileArea_cm2: "L^2",
      tileArea_m2: "L^2",
      tileCount: "1",
      dutyCycle: "1",
      dutyEffectiveFR: "1",
      dutyEff: "1",
      gammaGeo: "1",
      gammaVanDenBroeck: "1",
      qSpoilingFactor: "1",
      cavityQ: "1",
      U_static_J: "M L^2 T^-2",
      staticEnergy: "M L^2 T^-2",
      boostedEnergy: "M L^2 T^-2",
      cycleAverageEnergy: "M L^2 T^-2",
      totalEnergy_J: "M L^2 T^-2",
      exoticEnergyDensity: "M L^-1 T^-2",
      T00: "M L^-1 T^-2",
      T11: "M L^-1 T^-2",
      T22: "M L^-1 T^-2",
      T33: "M L^-1 T^-2",
      T00_avg: "M L^-1 T^-2",
      T11_avg: "M L^-1 T^-2",
      T22_avg: "M L^-1 T^-2",
      T33_avg: "M L^-1 T^-2",
      rho_avg: "M L^-1 T^-2",
      rho_inst: "M L^-1 T^-2",
      rho: "M L^-1 T^-2",
      stressEnergyT00_inst: "M L^-1 T^-2",
      beta_avg: "1",
      P_avg_W: "M L^2 T^-3",
      instantaneousPower: "M L^2 T^-3",
      averagePower: "M L^2 T^-3",
      modulationFreq_GHz: "T^-1",
      burst_us: "T",
      cycle_us: "T",
      sectorStrobingEfficiency: "1",
      homogenizationRatio: "1",
      metric: "1",
    },
  },
  {
    tag: "GR_CORE",
    module: "modules/gr/rk4.ts",
    stage: "diagnostic",
    notes: "RK4 integrator for BSSN evolution.",
    checks: [
      { type: "stability", path: "tests/gr-constraint-network.spec.ts" },
    ],
    residualsRequired: false,
  },
  {
    tag: "GR_CORE",
    module: "modules/gr/stencils.ts",
    stage: "diagnostic",
    notes: "Finite-difference stencils for BSSN evolution.",
    checks: [
      { type: "stability", path: "tests/gr-constraint-network.spec.ts" },
    ],
    residualsRequired: false,
  },
  {
    tag: "STRESS_FIELDS",
    module: "modules/gr/stress-energy.ts",
    stage: "reduced-order",
    notes: "Stress-energy field helpers (grid-aligned).",
    checks: [{ type: "test", path: "tests/stress-energy-matter.spec.ts" }],
  },
  {
    tag: "GR_CORE",
    module: "server/gr-initial-brick.ts",
    stage: "diagnostic",
    notes: "Initial data brick assembly for GR evolution.",
    checks: [
      { type: "stability", path: "tests/gr-constraint-network.spec.ts" },
    ],
    residualsRequired: false,
  },
  {
    tag: "GR_CORE",
    module: "server/gr/evolution.ts",
    stage: "diagnostic",
    notes: "GR evolution driver (constraints + evolution).",
    checks: [
      { type: "residual", path: "tests/gr-constraint-network.spec.ts" },
      { type: "stability", path: "tests/gr-constraint-network.spec.ts" },
    ],
  },
  {
    tag: "GR_CORE",
    module: "server/gr/evolution/brick.ts",
    stage: "diagnostic",
    notes: "GR evolution brick serialization helpers.",
    checks: [
      { type: "stability", path: "tests/gr-constraint-network.spec.ts" },
    ],
    residualsRequired: false,
  },
  {
    tag: "GR_CORE",
    module: "server/gr/evolution/initial-data.ts",
    stage: "diagnostic",
    notes: "Initial data solve utilities.",
    checks: [
      { type: "stability", path: "tests/gr-constraint-network.spec.ts" },
    ],
    residualsRequired: false,
  },
  {
    tag: "GR_CONSTRAINT",
    module: "server/gr/gr-constraint-network.ts",
    stage: "diagnostic",
    notes: "Constraint network evaluation for GR runs.",
    checks: [
      { type: "residual", path: "tests/gr-constraint-network.spec.ts" },
      { type: "stability", path: "tests/gr-constraint-network.spec.ts" },
    ],
  },
  {
    tag: "GR_POLICY",
    module: "server/gr/gr-constraint-policy.ts",
    stage: "reduced-order",
    notes: "Constraint policy thresholds for GR gate.",
    checks: [{ type: "test", path: "tests/gr-constraint-gate.spec.ts" }],
  },
  {
    tag: "GR_LOOP",
    module: "server/gr/gr-agent-loop-schema.ts",
    stage: "reduced-order",
    notes: "Schema for GR agent loop inputs/budgets.",
    checks: [{ type: "test", path: "tests/gr-agent-loop.spec.ts" }],
  },
  {
    tag: "GR_WORKER",
    module: "server/gr/gr-worker-client.ts",
    stage: "exploratory",
    notes: "Worker client for GR evolution execution.",
  },
  {
    tag: "GR_WORKER",
    module: "server/gr/gr-worker-types.ts",
    stage: "exploratory",
    notes: "Worker message types for GR evolution.",
  },
  {
    tag: "GR_WORKER",
    module: "server/gr/gr-worker.ts",
    stage: "exploratory",
    notes: "Worker runtime for GR evolution execution.",
  },
  {
    tag: "WARP_CORE",
    module: "modules/warp/natario-warp.ts",
    stage: "reduced-order",
    notes: "Analytic warp proxy (not full GR).",
    checks: [{ type: "test", path: "tests/theory-checks.spec.ts" }],
    units: {
      bowlRadius: "L",
      sagDepth: "L",
      gap: "L",
      burstDuration: "T",
      cycleDuration: "T",
      shiftAmplitude: "1",
      effectivePathLength: "L",
      baselineEnergyDensity: "M L^-1 T^-2",
      amplifiedEnergyDensity: "M L^-1 T^-2",
      exoticMassPerTile: "M",
      totalExoticMass: "M",
      powerDraw: "M L^2 T^-3",
      momentumFlux: "M L T^-2",
      betaAvg: "1",
    },
  },
  {
    tag: "WARP_CORE",
    module: "modules/warp/warp-module.ts",
    stage: "reduced-order",
    notes: "Warp module wrapper + diagnostics.",
    checks: [{ type: "test", path: "tests/theory-checks.spec.ts" }],
    units: {
      dutyEffectiveFR: "1",
      gammaGeo: "1",
      gammaVanDenBroeck: "1",
      qSpoilingFactor: "1",
      tileArea_m2: "L^2",
      tileCount: "1",
      P_avg_W: "M L^2 T^-3",
      exoticMassTarget_kg: "M",
    },
  },
  {
    tag: "WARP_CERT",
    module: "tools/warpViabilityCertificate.ts",
    stage: "certified",
    notes: "Certificate issuance (policy-gated).",
    checks: [
      { type: "test", path: "tests/theory-checks.spec.ts" },
      { type: "policy", path: "WARP_AGENTS.md" },
    ],
  },
  {
    tag: "WARP_CERT",
    module: "tools/verifyCertificate.ts",
    stage: "certified",
    notes: "Certificate integrity verification.",
    checks: [
      { type: "test", path: "tests/theory-checks.spec.ts" },
      { type: "policy", path: "WARP_AGENTS.md" },
    ],
  },
  {
    tag: "WARP_IO",
    module: "server/skills/physics.warp.viability.ts",
    stage: "certified",
    notes: "Public viability tool endpoint.",
    checks: [
      { type: "test", path: "tests/theory-checks.spec.ts" },
      { type: "policy", path: "WARP_AGENTS.md" },
    ],
  },
  {
    tag: "WARP_IO",
    module: "server/routes/warp-viability.ts",
    stage: "certified",
    notes: "HTTP route for viability + trace emission.",
    checks: [
      { type: "test", path: "tests/theory-checks.spec.ts" },
      { type: "policy", path: "WARP_AGENTS.md" },
    ],
  },
  {
    tag: "STRESS_MAP",
    module: "server/stress-energy-brick.ts",
    stage: "reduced-order",
    notes: "Reduced-order stress-energy mapping.",
    checks: [
      { type: "test", path: "tests/stress-energy-brick.spec.ts" },
      { type: "test", path: "tests/stress-energy-matter.spec.ts" },
    ],
    units: {
      t00: "M L^-1 T^-2",
      avgT00: "M L^-1 T^-2",
      totalEnergy_J: "M L^2 T^-2",
      gap_nm: "L",
      gap_m: "L",
      tileArea_cm2: "L^2",
      tileArea_m2: "L^2",
      tileCount: "1",
      dutyCycle: "1",
      dutyEffectiveFR: "1",
      dutyEff: "1",
      gammaGeo: "1",
      gammaVdB: "1",
      qSpoilingFactor: "1",
      cavityQ: "1",
      U_static_J: "M L^2 T^-2",
      staticEnergy: "M L^2 T^-2",
      boostedEnergy: "M L^2 T^-2",
      cycleAverageEnergy: "M L^2 T^-2",
      exoticEnergyDensity: "M L^-1 T^-2",
      P_avg_W: "M L^2 T^-3",
      instantaneousPower: "M L^2 T^-3",
      averagePower: "M L^2 T^-3",
      modulationFreq_GHz: "T^-1",
      burst_us: "T",
      cycle_us: "T",
      T00: "M L^-1 T^-2",
      T11: "M L^-1 T^-2",
      T22: "M L^-1 T^-2",
      T33: "M L^-1 T^-2",
      T00_avg: "M L^-1 T^-2",
      T11_avg: "M L^-1 T^-2",
      T22_avg: "M L^-1 T^-2",
      T33_avg: "M L^-1 T^-2",
      rho_avg: "M L^-1 T^-2",
      rho_inst: "M L^-1 T^-2",
      rho: "M L^-1 T^-2",
      stressEnergyT00_inst: "M L^-1 T^-2",
      beta_avg: "1",
      beta: "1",
      sectorStrobingEfficiency: "1",
      homogenizationRatio: "1",
      metric: "1",
      evolveDt_s: "T",
      dt: "T",
      time_s: "T",
      spacing: "L",
      bounds: "L",
      cfl: "1",
      H_rms: "1",
      M_rms: "1",
      H_maxAbs: "1",
      M_maxAbs: "1",
      H: "1",
      M: "1",
      Mx: "1",
      My: "1",
      Mz: "1",
    },
  },
  {
    tag: "STRESS_MAP",
    module: "server/gr/evolution/stress-energy.ts",
    stage: "reduced-order",
    notes: "Pipeline -> stress-energy fields.",
    checks: [
      { type: "test", path: "tests/stress-energy-brick.spec.ts" },
      { type: "test", path: "tests/stress-energy-matter.spec.ts" },
    ],
    units: {
      rho: "M L^-1 T^-2",
      dt: "T",
      evolveDt_s: "T",
      time_s: "T",
      spacing: "L",
      bounds: "L",
      H: "1",
      M: "1",
      Mx: "1",
      My: "1",
      Mz: "1",
      H_rms: "1",
      M_rms: "1",
      H_maxAbs: "1",
      M_maxAbs: "1",
      cfl: "1",
      gap_nm: "L",
      gap_m: "L",
      tileArea_cm2: "L^2",
      tileArea_m2: "L^2",
      tileCount: "1",
      dutyCycle: "1",
      dutyEffectiveFR: "1",
      dutyEff: "1",
      gammaGeo: "1",
      gammaVanDenBroeck: "1",
      qSpoilingFactor: "1",
      cavityQ: "1",
      U_static_J: "M L^2 T^-2",
      staticEnergy: "M L^2 T^-2",
      boostedEnergy: "M L^2 T^-2",
      cycleAverageEnergy: "M L^2 T^-2",
      totalEnergy_J: "M L^2 T^-2",
      exoticEnergyDensity: "M L^-1 T^-2",
      P_avg_W: "M L^2 T^-3",
      instantaneousPower: "M L^2 T^-3",
      averagePower: "M L^2 T^-3",
      modulationFreq_GHz: "T^-1",
      burst_us: "T",
      cycle_us: "T",
      T00: "M L^-1 T^-2",
      T11: "M L^-1 T^-2",
      T22: "M L^-1 T^-2",
      T33: "M L^-1 T^-2",
      T00_avg: "M L^-1 T^-2",
      T11_avg: "M L^-1 T^-2",
      T22_avg: "M L^-1 T^-2",
      T33_avg: "M L^-1 T^-2",
      rho_avg: "M L^-1 T^-2",
      rho_inst: "M L^-1 T^-2",
      rho: "M L^-1 T^-2",
      stressEnergyT00_inst: "M L^-1 T^-2",
      beta_avg: "1",
      sectorStrobingEfficiency: "1",
      homogenizationRatio: "1",
      metric: "1",
    },
  },
  {
    tag: "DYNAMIC",
    module: "modules/dynamic/stress-energy-equations.ts",
    stage: "reduced-order",
    notes: "Dynamic stress-energy helpers for pipeline/warp mapping.",
    checks: [
      { type: "test", path: "tests/stress-energy-brick.spec.ts" },
      { type: "test", path: "tests/stress-energy-matter.spec.ts" },
    ],
    units: {
      gap_m: "L",
      gap_nm: "L",
      tileArea_cm2: "L^2",
      tileArea_m2: "L^2",
      tileCount: "1",
      dutyCycle: "1",
      dutyEffectiveFR: "1",
      dutyEff: "1",
      gammaGeo: "1",
      gammaVdB: "1",
      qSpoilingFactor: "1",
      cavityQ: "1",
      U_static_J: "M L^2 T^-2",
      staticEnergy: "M L^2 T^-2",
      boostedEnergy: "M L^2 T^-2",
      cycleAverageEnergy: "M L^2 T^-2",
      totalEnergy_J: "M L^2 T^-2",
      exoticEnergyDensity: "M L^-1 T^-2",
      P_avg_W: "M L^2 T^-3",
      instantaneousPower: "M L^2 T^-3",
      averagePower: "M L^2 T^-3",
      modulationFreq_GHz: "T^-1",
      burst_us: "T",
      cycle_us: "T",
      rho_avg: "M L^-1 T^-2",
      rho_inst: "M L^-1 T^-2",
      rho: "M L^-1 T^-2",
      T00: "M L^-1 T^-2",
      T11: "M L^-1 T^-2",
      T22: "M L^-1 T^-2",
      T33: "M L^-1 T^-2",
      stressEnergyT00_inst: "M L^-1 T^-2",
      beta_avg: "1",
      beta: "1",
      sectorStrobingEfficiency: "1",
      homogenizationRatio: "1",
      metric: "1",
      evolveDt_s: "T",
      dt: "T",
      time_s: "T",
      spacing: "L",
      bounds: "L",
      cfl: "1",
      H_rms: "1",
      M_rms: "1",
      H_maxAbs: "1",
      M_maxAbs: "1",
      H: "1",
      M: "1",
      Mx: "1",
      My: "1",
      Mz: "1",
    },
  },
  {
    tag: "DYNAMIC",
    module: "modules/dynamic/dynamic-casimir.ts",
    stage: "reduced-order",
    notes: "Dynamic Casimir sweep helpers (pipeline).",
    checks: [{ type: "test", path: "tests/theory-checks.spec.ts" }],
    units: {
      staticEnergy: "M L^2 T^-2",
      modulationFreqGHz: "T^-1",
      burstLengthUs: "T",
      cycleLengthUs: "T",
      cavityQ: "1",
      tileCount: "1",
      boostedEnergy: "M L^2 T^-2",
      cycleAverageEnergy: "M L^2 T^-2",
      exoticEnergyDensity: "M L^-1 T^-2",
      instantaneousPower: "M L^2 T^-3",
      averagePower: "M L^2 T^-3",
      gap_nm: "L",
      gap_m: "L",
      tileArea_cm2: "L^2",
      tileArea_m2: "L^2",
      dutyCycle: "1",
      dutyEffectiveFR: "1",
      dutyEff: "1",
      gammaGeo: "1",
      gammaVanDenBroeck: "1",
      qSpoilingFactor: "1",
      U_static_J: "M L^2 T^-2",
      P_avg_W: "M L^2 T^-3",
      T00: "M L^-1 T^-2",
      T11: "M L^-1 T^-2",
      T22: "M L^-1 T^-2",
      T33: "M L^-1 T^-2",
      T00_avg: "M L^-1 T^-2",
      T11_avg: "M L^-1 T^-2",
      T22_avg: "M L^-1 T^-2",
      T33_avg: "M L^-1 T^-2",
      rho_avg: "M L^-1 T^-2",
      rho_inst: "M L^-1 T^-2",
      rho: "M L^-1 T^-2",
      stressEnergyT00_inst: "M L^-1 T^-2",
      beta_avg: "1",
      beta: "1",
      totalEnergy_J: "M L^2 T^-2",
      sectorStrobingEfficiency: "1",
      homogenizationRatio: "1",
      metric: "1",
      evolveDt_s: "T",
      dt: "T",
      time_s: "T",
      spacing: "L",
      bounds: "L",
      cfl: "1",
      H_rms: "1",
      M_rms: "1",
      H_maxAbs: "1",
      M_maxAbs: "1",
      H: "1",
      M: "1",
      Mx: "1",
      My: "1",
      Mz: "1",
    },
  },
  {
    tag: "DYNAMIC",
    module: "modules/dynamic/natario-metric.ts",
    stage: "reduced-order",
    notes: "Natario metric proxy helpers (pipeline).",
    checks: [{ type: "test", path: "tests/theory-checks.spec.ts" }],
    units: {
      stressEnergyT00: "M L^-1 T^-2",
      stressEnergyT11: "M L^-1 T^-2",
      stressEnergyT00_inst: "M L^-1 T^-2",
      natarioShiftAmplitude: "1",
      sectorStrobingEfficiency: "1",
      homogenizationRatio: "1",
      metric: "1",
      gap_nm: "L",
      gap_m: "L",
      tileArea_cm2: "L^2",
      tileArea_m2: "L^2",
      tileCount: "1",
      dutyCycle: "1",
      dutyEffectiveFR: "1",
      dutyEff: "1",
      gammaGeo: "1",
      gammaVanDenBroeck: "1",
      qSpoilingFactor: "1",
      cavityQ: "1",
      U_static_J: "M L^2 T^-2",
      staticEnergy: "M L^2 T^-2",
      boostedEnergy: "M L^2 T^-2",
      cycleAverageEnergy: "M L^2 T^-2",
      totalEnergy_J: "M L^2 T^-2",
      exoticEnergyDensity: "M L^-1 T^-2",
      P_avg_W: "M L^2 T^-3",
      instantaneousPower: "M L^2 T^-3",
      averagePower: "M L^2 T^-3",
      modulationFreq_GHz: "T^-1",
      burst_us: "T",
      cycle_us: "T",
      T00: "M L^-1 T^-2",
      T11: "M L^-1 T^-2",
      T22: "M L^-1 T^-2",
      T33: "M L^-1 T^-2",
      T00_avg: "M L^-1 T^-2",
      T11_avg: "M L^-1 T^-2",
      T22_avg: "M L^-1 T^-2",
      T33_avg: "M L^-1 T^-2",
      rho_avg: "M L^-1 T^-2",
      rho_inst: "M L^-1 T^-2",
      rho: "M L^-1 T^-2",
      beta_avg: "1",
      beta: "1",
      evolveDt_s: "T",
      dt: "T",
      time_s: "T",
      spacing: "L",
      bounds: "L",
      cfl: "1",
      H_rms: "1",
      M_rms: "1",
      H_maxAbs: "1",
      M_maxAbs: "1",
      H: "1",
      M: "1",
      Mx: "1",
      My: "1",
      Mz: "1",
    },
  },
  {
    tag: "PIPELINE",
    module: "server/energy-pipeline.ts",
    stage: "reduced-order",
    notes: "Energy pipeline core (mixed proxies + calibration).",
    checks: [{ type: "test", path: "tests/pipeline-ts-qi-guard.spec.ts" }],     
    units: {
      gap_nm: "L",
      gap_m: "L",
      tileArea_cm2: "L^2",
      tileArea_m2: "L^2",
      tileCount: "1",
      dutyCycle: "1",
      dutyEffectiveFR: "1",
      dutyEff: "1",
      gammaGeo: "1",
      gammaVanDenBroeck: "1",
      qSpoilingFactor: "1",
      cavityQ: "1",
      U_static_J: "M L^2 T^-2",
      staticEnergy: "M L^2 T^-2",
      boostedEnergy: "M L^2 T^-2",
      cycleAverageEnergy: "M L^2 T^-2",
      totalEnergy_J: "M L^2 T^-2",
      exoticEnergyDensity: "M L^-1 T^-2",
      P_avg_W: "M L^2 T^-3",
      instantaneousPower: "M L^2 T^-3",
      averagePower: "M L^2 T^-3",
      modulationFreq_GHz: "T^-1",
      burst_us: "T",
      cycle_us: "T",
      T00: "M L^-1 T^-2",
      T11: "M L^-1 T^-2",
      T22: "M L^-1 T^-2",
      T33: "M L^-1 T^-2",
      T00_avg: "M L^-1 T^-2",
      T11_avg: "M L^-1 T^-2",
      T22_avg: "M L^-1 T^-2",
      T33_avg: "M L^-1 T^-2",
      rho_avg: "M L^-1 T^-2",
      rho_inst: "M L^-1 T^-2",
      rho: "M L^-1 T^-2",
      stressEnergyT00_inst: "M L^-1 T^-2",
      beta_avg: "1",
      beta: "1",
      sectorStrobingEfficiency: "1",
      homogenizationRatio: "1",
      metric: "1",
      evolveDt_s: "T",
      dt: "T",
      time_s: "T",
      spacing: "L",
      bounds: "L",
      cfl: "1",
      H_rms: "1",
      M_rms: "1",
      H_maxAbs: "1",
      M_maxAbs: "1",
      H: "1",
      M: "1",
      Mx: "1",
      My: "1",
      Mz: "1",
    },
  },
  {
    tag: "WARP_EVAL",
    module: "tools/warpViability.ts",
    stage: "diagnostic",
    notes: "Warp viability evaluation from pipeline + guardrails.",
    checks: [
      { type: "stability", path: "tools/__tests__/warpViability.spec.ts" },
      { type: "policy", path: "WARP_AGENTS.md" },
    ],
  },
  {
    tag: "WARP_POLICY",
    module: "modules/physics/warpAgents.ts",
    stage: "reduced-order",
    notes: "Warp guardrail definitions (policy registry).",
    checks: [
      { type: "test", path: "tests/theory-checks.spec.ts" },
      { type: "policy", path: "WARP_AGENTS.md" },
    ],
  },
  {
    tag: "TRACE",
    module: "server/services/observability/training-trace-store.ts",
    stage: "diagnostic",
    notes: "Training trace storage and export (audit/data flywheel).",
    checks: [
      { type: "stability", path: "server/__tests__/training-trace.test.ts" },
    ],
  },
  {
    tag: "TRACE",
    module: "server/routes/training-trace.ts",
    stage: "diagnostic",
    notes: "Training trace API routes (ingest/list/export).",
    checks: [
      { type: "stability", path: "server/__tests__/training-trace.test.ts" },
    ],
  },
  {
    tag: "GR_AUDIT",
    module: "server/services/observability/gr-agent-loop-store.ts",
    stage: "diagnostic",
    notes: "GR agent loop audit log storage.",
    checks: [{ type: "stability", path: "tests/gr-agent-loop.spec.ts" }],
  },
  {
    tag: "LOG_STORE",
    module: "server/services/observability/tool-log-store.ts",
    stage: "exploratory",
    notes: "Tool log store (non-math telemetry).",
  },
  {
    tag: "ADAPTER",
    module: "server/routes/agi.adapter.ts",
    stage: "diagnostic",
    notes: "Adapter API (actions -> verdict + trace).",
    checks: [
      { type: "stability", path: "server/__tests__/agi.adapter.test.ts" },
    ],
  },
  {
    tag: "AGI_PLAN",
    module: "server/routes/agi.plan.ts",
    stage: "reduced-order",
    notes: "Plan/execute route (non-math runtime).",
    checks: [{ type: "test", path: "tests/agi-plan.spec.ts" }],
  },
  {
    tag: "AGI_EVAL",
    module: "server/routes/agi.eval.ts",
    stage: "reduced-order",
    notes: "Eval route for agent runs.",
    checks: [{ type: "test", path: "tests/eval-endpoint.spec.ts" }],
  },
  {
    tag: "AGI_MEMORY",
    module: "server/routes/agi.memory.ts",
    stage: "reduced-order",
    notes: "Memory CRUD routes.",
    checks: [{ type: "test", path: "tests/agi-memory.spec.ts" }],
  },
  {
    tag: "AGI_TRACE",
    module: "server/routes/agi.memory.trace.ts",
    stage: "reduced-order",
    notes: "Memory trace streaming route.",
    checks: [{ type: "test", path: "tests/trace-api.spec.ts" }],
  },
  {
    tag: "AGI_PERSONA",
    module: "server/routes/agi.persona.ts",
    stage: "reduced-order",
    notes: "Persona route wiring.",
    checks: [{ type: "test", path: "tests/persona-policy.spec.ts" }],
  },
  {
    tag: "AGI_PROFILE",
    module: "server/routes/agi.profile.ts",
    stage: "reduced-order",
    notes: "Profile summarizer endpoints.",
    checks: [{ type: "test", path: "tests/essence-dal.spec.ts" }],
  },
  {
    tag: "AGI_SPECIALISTS",
    module: "server/routes/agi.specialists.ts",
    stage: "reduced-order",
    notes: "Specialists routing and controls.",
    checks: [{ type: "test", path: "tests/specialists.math.spec.ts" }],
  },
  {
    tag: "AGI_STAR",
    module: "server/routes/agi.star.ts",
    stage: "reduced-order",
    notes: "Star telemetry route.",
    checks: [{ type: "test", path: "tests/solar-energy-adapter.spec.ts" }],
  },
  {
    tag: "AGI_TRACE",
    module: "server/routes/agi.trace.ts",
    stage: "reduced-order",
    notes: "Trace/log streaming routes.",
    checks: [{ type: "test", path: "tests/trace-api.spec.ts" }],
  },
  {
    tag: "AGI_DEBATE",
    module: "server/routes/agi.debate.ts",
    stage: "reduced-order",
    notes: "Debate routing + orchestration.",
    checks: [{ type: "test", path: "tests/debate-orchestrator.spec.ts" }],
  },
  {
    tag: "PACKS",
    module: "server/services/observability/constraint-pack-evaluator.ts",
    stage: "diagnostic",
    notes: "Constraint-pack evaluators for telemetry.",
    checks: [
      {
        type: "stability",
        path: "server/__tests__/constraint-packs.evaluate.test.ts",
      },
    ],
  },
  {
    tag: "PACKS",
    module: "server/services/observability/constraint-pack-normalizer.ts",
    stage: "diagnostic",
    notes: "Normalizer -> training trace records.",
    checks: [
      {
        type: "stability",
        path: "server/__tests__/constraint-packs.evaluate.test.ts",
      },
    ],
  },
  {
    tag: "PACKS",
    module: "server/services/observability/constraint-pack-telemetry.ts",
    stage: "diagnostic",
    notes: "Telemetry ingestion helpers (env -> pack inputs).",
    checks: [
      {
        type: "stability",
        path: "server/__tests__/constraint-packs.evaluate.test.ts",
      },
    ],
  },
  {
    tag: "PACKS",
    module: "server/routes/agi.constraint-packs.ts",
    stage: "diagnostic",
    notes: "Constraint-pack API routes (list/evaluate/policy).",
    checks: [
      {
        type: "stability",
        path: "server/__tests__/constraint-packs.evaluate.test.ts",
      },
    ],
  },
  {
    tag: "PACKS",
    module: "server/services/constraint-packs/constraint-pack-policy.ts",
    stage: "reduced-order",
    notes: "Policy override application and ladder enforcement.",
    checks: [
      {
        type: "test",
        path: "server/__tests__/constraint-packs.evaluate.test.ts",
      },
    ],
  },
  {
    tag: "PACKS",
    module: "server/services/constraint-packs/constraint-pack-policy-store.ts",
    stage: "reduced-order",
    notes: "Policy profile persistence (JSONL store).",
    checks: [
      {
        type: "test",
        path: "server/__tests__/constraint-packs.evaluate.test.ts",
      },
    ],
  },
  {
    tag: "ANALYSIS",
    module: "modules/analysis/constraint-loop.ts",
    stage: "exploratory",
    notes: "Generic constraint loop runner (prototype).",
  },
  {
    tag: "ANALYSIS",
    module: "modules/analysis/noise-field-loop.ts",
    stage: "exploratory",
    notes: "Noise field loop (prototype).",
  },
  {
    tag: "ANALYSIS",
    module: "modules/analysis/diffusion-loop.ts",
    stage: "exploratory",
    notes: "Diffusion loop stub (prototype).",
  },
  {
    tag: "ANALYSIS",
    module: "modules/analysis/belief-graph-loop.ts",
    stage: "exploratory",
    notes: "Belief graph loop (prototype).",
  },
  {
    tag: "ANALYSIS",
    module: "server/routes/analysis-loops.ts",
    stage: "exploratory",
    notes: "Analysis loop API endpoints.",
  },
  {
    tag: "OBS",
    module: "server/services/observability/otel-tracing.ts",
    stage: "exploratory",
    notes: "OTEL span helpers (instrumentation).",
  },
  {
    tag: "OBS",
    module: "server/services/observability/otel-middleware.ts",
    stage: "exploratory",
    notes: "OTEL middleware (instrumentation).",
  },
  {
    tag: "OBS",
    module: "server/services/observability/otel-span-store.ts",
    stage: "exploratory",
    notes: "In-memory OTEL span store (debug tooling).",
  },
];
