export const MATH_STAGE_LEVELS = {
  exploratory: 0,
  "reduced-order": 1,
  diagnostic: 2,
  certified: 3,
} as const;

export type MathStage = keyof typeof MATH_STAGE_LEVELS;

export type MathCheckType =
  | "test"
  | "policy"
  | "certificate"
  | "snapshot"
  | "doc"
  | "residual"
  | "stability";

export type MathCheck = {
  type: MathCheckType;
  path: string;
  note?: string;
};

export type UnitSignature = Record<string, string>;

export type MathStageEntry = {
  tag: string;
  module: string;
  stage: MathStage;
  notes?: string;
  motivation?: string;
  conceptualWaypoints?: string[];
  checks?: MathCheck[];
  units?: UnitSignature;
  residualsRequired?: boolean;
};

export const mathStageRegistry: MathStageEntry[] = [
  {
    tag: "GR_CORE",
    module: "modules/gr/bssn-state.ts",
    stage: "diagnostic",
    notes: "Grid + BSSN state definitions.",
    checks: [
      { type: "residual", path: "tests/gr-constraint-network.spec.ts" },
      { type: "stability", path: "tests/gr-constraint-network.spec.ts" },       
    ],
    residualsRequired: false,
    units: {
      spacing: "L",
      bounds: "L",
      alpha: "1",
      beta_x: "1",
      beta_y: "1",
      beta_z: "1",
      gamma_xx: "1",
      gamma_yy: "1",
      gamma_zz: "1",
    },
  },
  {
    tag: "GR_CORE",
    module: "modules/gr/bssn-evolve.ts",
    stage: "diagnostic",
    notes: "BSSN evolution + constraint fields.",
    checks: [
      { type: "residual", path: "tests/gr-constraint-gate.spec.ts" },
      { type: "stability", path: "tests/gr-constraint-network.spec.ts" },       
    ],
    units: {
      dt: "T",
      time_s: "T",
      evolveDt_s: "T",
      spacing: "L",
      bounds: "L",
      H: "1",
      M: "1",
      Mx: "1",
      My: "1",
      Mz: "1",
      H_rms: "1",
      M_rms: "1",
      H_maxAbs: "1",
      M_maxAbs: "1",
      cfl: "1",
      gap_nm: "L",
      gap_m: "L",
      tileArea_cm2: "L^2",
      tileArea_m2: "L^2",
      tileCount: "1",
      dutyCycle: "1",
      dutyEffectiveFR: "1",
      dutyEff: "1",
      gammaGeo: "1",
      gammaVanDenBroeck: "1",
      qSpoilingFactor: "1",
      cavityQ: "1",
      U_static_J: "M L^2 T^-2",
      staticEnergy: "M L^2 T^-2",
      boostedEnergy: "M L^2 T^-2",
      cycleAverageEnergy: "M L^2 T^-2",
      totalEnergy_J: "M L^2 T^-2",
        totalMomentum_kg_m_s: "M L T^-1",
        momentumMagnitude_kg_m_s: "M L T^-1",
        invariantMass_kg: "M",
        invariantMassSigma_kg: "M",
        invariantMassEnergy_J: "M L^2 T^-2",
        massSigma_kg: "M",
        exoticEnergyDensity: "M L^-1 T^-2",
      P_avg_W: "M L^2 T^-3",
      instantaneousPower: "M L^2 T^-3",
      averagePower: "M L^2 T^-3",
      modulationFreq_GHz: "T^-1",
      burst_us: "T",
      cycle_us: "T",
      T00: "M L^-1 T^-2",
      T11: "M L^-1 T^-2",
      T22: "M L^-1 T^-2",
      T33: "M L^-1 T^-2",
      T00_avg: "M L^-1 T^-2",
      T11_avg: "M L^-1 T^-2",
      T22_avg: "M L^-1 T^-2",
      T33_avg: "M L^-1 T^-2",
      rho_avg: "M L^-1 T^-2",
      rho_inst: "M L^-1 T^-2",
      rho: "M L^-1 T^-2",
      stressEnergyT00_inst: "M L^-1 T^-2",
      beta_avg: "1",
      sectorStrobingEfficiency: "1",
      homogenizationRatio: "1",
      metric: "1",
    },
  },
  {
    tag: "GR_CORE",
    module: "server/gr/evolution/solver.ts",
    stage: "diagnostic",
    notes: "Runs BSSN evolution (diagnostic).",
    checks: [
      { type: "residual", path: "tests/gr-constraint-network.spec.ts" },
      { type: "stability", path: "tests/gr-constraint-network.spec.ts" },       
    ],
    units: {
      dt: "T",
      evolveDt_s: "T",
      time_s: "T",
      spacing: "L",
      bounds: "L",
      H: "1",
      M: "1",
      Mx: "1",
      My: "1",
      Mz: "1",
      gap_nm: "L",
      gap_m: "L",
      tileArea_cm2: "L^2",
      tileArea_m2: "L^2",
      tileCount: "1",
      dutyCycle: "1",
      dutyEffectiveFR: "1",
      dutyEff: "1",
      gammaGeo: "1",
      gammaVanDenBroeck: "1",
      qSpoilingFactor: "1",
      cavityQ: "1",
      U_static_J: "M L^2 T^-2",
      staticEnergy: "M L^2 T^-2",
      boostedEnergy: "M L^2 T^-2",
      cycleAverageEnergy: "M L^2 T^-2",
      totalEnergy_J: "M L^2 T^-2",
      totalMomentum_kg_m_s: "M L T^-1",
      momentumMagnitude_kg_m_s: "M L T^-1",
      invariantMass_kg: "M",
      invariantMassEnergy_J: "M L^2 T^-2",
      exoticEnergyDensity: "M L^-1 T^-2",
      T00: "M L^-1 T^-2",
      T11: "M L^-1 T^-2",
      T22: "M L^-1 T^-2",
      T33: "M L^-1 T^-2",
      T00_avg: "M L^-1 T^-2",
      T11_avg: "M L^-1 T^-2",
      T22_avg: "M L^-1 T^-2",
      T33_avg: "M L^-1 T^-2",
      rho_avg: "M L^-1 T^-2",
      rho_inst: "M L^-1 T^-2",
      rho: "M L^-1 T^-2",
      stressEnergyT00_inst: "M L^-1 T^-2",
      beta_avg: "1",
      P_avg_W: "M L^2 T^-3",
      instantaneousPower: "M L^2 T^-3",
      averagePower: "M L^2 T^-3",
      modulationFreq_GHz: "T^-1",
      burst_us: "T",
      cycle_us: "T",
      sectorStrobingEfficiency: "1",
      homogenizationRatio: "1",
      metric: "1",
      H_rms: "1",
      M_rms: "1",
      H_maxAbs: "1",
      M_maxAbs: "1",
      cfl: "1",
    },
  },
  {
    tag: "GR_CORE",
    module: "server/gr-evolve-brick.ts",
    stage: "diagnostic",
    notes: "Builds GR diagnostics + residuals.",
    checks: [
      { type: "residual", path: "tests/gr-constraint-gate.spec.ts" },
      { type: "stability", path: "tests/gr-constraint-network.spec.ts" },       
    ],
    units: {
      dt: "T",
      time_s: "T",
      evolveDt_s: "T",
      spacing: "L",
      bounds: "L",
      H: "1",
      M: "1",
      Mx: "1",
      My: "1",
      Mz: "1",
      gap_nm: "L",
      gap_m: "L",
      tileArea_cm2: "L^2",
      tileArea_m2: "L^2",
      tileCount: "1",
      dutyCycle: "1",
      dutyEffectiveFR: "1",
      dutyEff: "1",
      gammaGeo: "1",
      gammaVanDenBroeck: "1",
      qSpoilingFactor: "1",
      cavityQ: "1",
      U_static_J: "M L^2 T^-2",
      staticEnergy: "M L^2 T^-2",
      boostedEnergy: "M L^2 T^-2",
      cycleAverageEnergy: "M L^2 T^-2",
      totalEnergy_J: "M L^2 T^-2",
      totalMomentum_kg_m_s: "M L T^-1",
      momentumMagnitude_kg_m_s: "M L T^-1",
      invariantMass_kg: "M",
      invariantMassEnergy_J: "M L^2 T^-2",
      exoticEnergyDensity: "M L^-1 T^-2",
      T00: "M L^-1 T^-2",
      T11: "M L^-1 T^-2",
      T22: "M L^-1 T^-2",
      T33: "M L^-1 T^-2",
      T00_avg: "M L^-1 T^-2",
      T11_avg: "M L^-1 T^-2",
      T22_avg: "M L^-1 T^-2",
      T33_avg: "M L^-1 T^-2",
      rho_avg: "M L^-1 T^-2",
      rho_inst: "M L^-1 T^-2",
      rho: "M L^-1 T^-2",
      stressEnergyT00_inst: "M L^-1 T^-2",
      beta_avg: "1",
      P_avg_W: "M L^2 T^-3",
      instantaneousPower: "M L^2 T^-3",
      averagePower: "M L^2 T^-3",
      modulationFreq_GHz: "T^-1",
      burst_us: "T",
      cycle_us: "T",
      sectorStrobingEfficiency: "1",
      homogenizationRatio: "1",
      metric: "1",
      H_rms: "1",
      M_rms: "1",
      H_maxAbs: "1",
      M_maxAbs: "1",
      cfl: "1",
    },
  },
  {
    tag: "GR_GATE",
    module: "server/gr/constraint-evaluator.ts",
    stage: "certified",
    notes: "GR gate evaluation from diagnostics.",
    motivation:
      "Turn GR constraint diagnostics into policy-gated pass/fail so downstream layers do not over-claim viability.",
    conceptualWaypoints: [
      "Summarize BSSN constraint fields into RMS and max-abs metrics.",
      "Apply policy thresholds with unknown-as-fail semantics.",
      "Emit constraint entries plus gate status for downstream evaluation.",
    ],
    checks: [
      { type: "test", path: "tests/gr-constraint-gate.spec.ts" },
      { type: "policy", path: "WARP_AGENTS.md" },
    ],
    units: {
      H_rms: "1",
      M_rms: "1",
      H_maxAbs: "1",
      M_maxAbs: "1",
      dt: "T",
      time_s: "T",
      evolveDt_s: "T",
      spacing: "L",
      bounds: "L",
      H: "1",
      M: "1",
      Mx: "1",
      My: "1",
      Mz: "1",
      cfl: "1",
      gap_nm: "L",
      gap_m: "L",
      tileArea_cm2: "L^2",
      tileArea_m2: "L^2",
      tileCount: "1",
      dutyCycle: "1",
      dutyEffectiveFR: "1",
      dutyEff: "1",
      gammaGeo: "1",
      gammaVanDenBroeck: "1",
      qSpoilingFactor: "1",
      cavityQ: "1",
      U_static_J: "M L^2 T^-2",
      staticEnergy: "M L^2 T^-2",
      boostedEnergy: "M L^2 T^-2",
      cycleAverageEnergy: "M L^2 T^-2",
      totalEnergy_J: "M L^2 T^-2",
      totalMomentum_kg_m_s: "M L T^-1",
      momentumMagnitude_kg_m_s: "M L T^-1",
      invariantMass_kg: "M",
      invariantMassEnergy_J: "M L^2 T^-2",
      exoticEnergyDensity: "M L^-1 T^-2",
      P_avg_W: "M L^2 T^-3",
      instantaneousPower: "M L^2 T^-3",
      averagePower: "M L^2 T^-3",
      modulationFreq_GHz: "T^-1",
      burst_us: "T",
      cycle_us: "T",
      T00: "M L^-1 T^-2",
      T11: "M L^-1 T^-2",
      T22: "M L^-1 T^-2",
      T33: "M L^-1 T^-2",
      T00_avg: "M L^-1 T^-2",
      T11_avg: "M L^-1 T^-2",
      T22_avg: "M L^-1 T^-2",
      T33_avg: "M L^-1 T^-2",
      rho_avg: "M L^-1 T^-2",
      rho_inst: "M L^-1 T^-2",
      rho: "M L^-1 T^-2",
      stressEnergyT00_inst: "M L^-1 T^-2",
      beta_avg: "1",
      sectorStrobingEfficiency: "1",
      homogenizationRatio: "1",
      metric: "1",
    },
  },
  {
    tag: "GR_GATE",
    module: "server/gr/gr-evaluation.ts",
    stage: "certified",
    notes: "Gate + certificate checks (policy).",
    motivation:
      "Combine GR gate results with warp certificate status to decide if an attempt is policy-admissible.",
    conceptualWaypoints: [
      "Load threshold and certificate policy from warp agent config.",
      "Evaluate the GR constraint gate from diagnostics.",
      "Issue a warp viability certificate and verify integrity/status.",
      "Pass only when gate, certificate presence, and status requirements are satisfied.",
    ],
    checks: [
      { type: "test", path: "tests/gr-agent-loop.spec.ts" },
      { type: "policy", path: "WARP_AGENTS.md" },
    ],
    units: {
      updatedAt: "T",
      H_rms: "1",
      M_rms: "1",
      H_maxAbs: "1",
      M_maxAbs: "1",
      cfl: "1",
      pass: "1",
    },
  },
  {
    tag: "GR_LOOP",
    module: "server/gr/gr-agent-loop.ts",
    stage: "certified",
    notes: "Orchestration + acceptance gate.",
    motivation:
      "Iterate the GR pipeline under budget until a gate- and certificate-clean attempt is found (or exhaustion is reported).",
    conceptualWaypoints: [
      "Generate proposals and run initial/evolve steps within timing budgets.",
      "Compute diagnostics and evaluate gate + certificate each attempt.",
      "Accept and commit the first passing attempt; otherwise record failures.",
    ],
    checks: [
      { type: "test", path: "tests/gr-agent-loop.spec.ts" },
      { type: "test", path: "tests/gr-agent-loop-baseline.spec.ts" },
      { type: "policy", path: "WARP_AGENTS.md" },
    ],
    units: {
      evolveDt_s: "T",
      dt: "T",
      time_s: "T",
      spacing: "L",
      bounds: "L",
      cfl: "1",
      H_rms: "1",
      M_rms: "1",
      H_maxAbs: "1",
      M_maxAbs: "1",
      H: "1",
      M: "1",
      Mx: "1",
      My: "1",
      Mz: "1",
      gap_nm: "L",
      gap_m: "L",
      tileArea_cm2: "L^2",
      tileArea_m2: "L^2",
      tileCount: "1",
      dutyCycle: "1",
      dutyEffectiveFR: "1",
      dutyEff: "1",
      gammaGeo: "1",
      gammaVanDenBroeck: "1",
      qSpoilingFactor: "1",
      cavityQ: "1",
      U_static_J: "M L^2 T^-2",
      staticEnergy: "M L^2 T^-2",
      boostedEnergy: "M L^2 T^-2",
      cycleAverageEnergy: "M L^2 T^-2",
      totalEnergy_J: "M L^2 T^-2",
      totalMomentum_kg_m_s: "M L T^-1",
      momentumMagnitude_kg_m_s: "M L T^-1",
      invariantMass_kg: "M",
      invariantMassEnergy_J: "M L^2 T^-2",
      exoticEnergyDensity: "M L^-1 T^-2",
      T00: "M L^-1 T^-2",
      T11: "M L^-1 T^-2",
      T22: "M L^-1 T^-2",
      T33: "M L^-1 T^-2",
      T00_avg: "M L^-1 T^-2",
      T11_avg: "M L^-1 T^-2",
      T22_avg: "M L^-1 T^-2",
      T33_avg: "M L^-1 T^-2",
      rho_avg: "M L^-1 T^-2",
      rho_inst: "M L^-1 T^-2",
      rho: "M L^-1 T^-2",
      stressEnergyT00_inst: "M L^-1 T^-2",
      beta_avg: "1",
      P_avg_W: "M L^2 T^-3",
      instantaneousPower: "M L^2 T^-3",
      averagePower: "M L^2 T^-3",
      modulationFreq_GHz: "T^-1",
      burst_us: "T",
      cycle_us: "T",
      sectorStrobingEfficiency: "1",
      homogenizationRatio: "1",
      metric: "1",
    },
  },
  {
    tag: "GR_CORE",
    module: "modules/gr/rk4.ts",
    stage: "diagnostic",
    notes: "RK4 integrator for BSSN evolution.",
    checks: [
      { type: "residual", path: "tests/gr-constraint-network.spec.ts" },
      { type: "stability", path: "tests/gr-constraint-network.spec.ts" },
    ],
    residualsRequired: false,
    units: {
      dt: "T",
    },
  },
  {
    tag: "GR_CORE",
    module: "modules/gr/stencils.ts",
    stage: "diagnostic",
    notes: "Finite-difference stencils for BSSN evolution.",
    checks: [
      { type: "residual", path: "tests/gr-constraint-network.spec.ts" },
      { type: "stability", path: "tests/gr-constraint-network.spec.ts" },
    ],
    residualsRequired: false,
    units: {
      spacing: "L",
    },
  },
  {
    tag: "STRESS_FIELDS",
    module: "modules/gr/stress-energy.ts",
    stage: "reduced-order",
    notes: "Stress-energy field helpers (grid-aligned).",
    checks: [{ type: "test", path: "tests/stress-energy-matter.spec.ts" }],
    units: {
      rho: "M L^-1 T^-2",
      Sx: "M L^-1 T^-2",
      Sy: "M L^-1 T^-2",
      Sz: "M L^-1 T^-2",
      S_xx: "M L^-1 T^-2",
      S_yy: "M L^-1 T^-2",
      S_zz: "M L^-1 T^-2",
      S_xy: "M L^-1 T^-2",
      S_xz: "M L^-1 T^-2",
      S_yz: "M L^-1 T^-2",
    },
  },
  {
    tag: "STRESS_MAP",
    module: "modules/gr/stress-energy-integrals.ts",
    stage: "diagnostic",
    notes: "Volume integrals for stress-energy totals + invariant mass.",
    checks: [
      { type: "test", path: "tests/stress-energy-matter.spec.ts" },
      { type: "stability", path: "tests/stress-energy-matter.spec.ts" },
    ],
    units: {
      rho: "M L^-1 T^-2",
      Sx: "M L^-1 T^-2",
      Sy: "M L^-1 T^-2",
      Sz: "M L^-1 T^-2",
      totalEnergy_J: "M L^2 T^-2",
      totalMomentum_kg_m_s: "M L T^-1",
      momentumMagnitude_kg_m_s: "M L T^-1",
      invariantMass_kg: "M",
      invariantMassEnergy_J: "M L^2 T^-2",
      cellVolume_m3: "L^3",
      sampleCount: "1",
    },
  },
  {
    tag: "GR_CORE",
    module: "server/gr-initial-brick.ts",
    stage: "diagnostic",
    notes: "Initial data brick assembly for GR evolution.",
    checks: [
      { type: "residual", path: "tests/gr-constraint-network.spec.ts" },
      { type: "stability", path: "tests/gr-constraint-network.spec.ts" },
    ],
    residualsRequired: false,
    units: {
      bounds: "L",
      voxelSize_m: "L",
      time_s: "T",
      dt_s: "T",
      iterations: "1",
      residual: "1",
      tolerance: "1",
      H_rms: "1",
      M_rms: "1",
      H_maxAbs: "1",
      M_maxAbs: "1",
    },
  },
  {
    tag: "GR_CORE",
    module: "server/gr/evolution.ts",
    stage: "diagnostic",
    notes: "GR evolution driver (constraints + evolution).",
    checks: [
      { type: "residual", path: "tests/gr-constraint-network.spec.ts" },
      { type: "stability", path: "tests/gr-constraint-network.spec.ts" },
    ],
    units: {
      bounds: "L",
      voxelSize_m: "L",
      time_s: "T",
      dt_s: "T",
      steps: "1",
      iterations: "1",
      tolerance: "1",
      cfl: "1",
      H_rms: "1",
      M_rms: "1",
    },
  },
  {
    tag: "GR_CORE",
    module: "server/gr/evolution/brick.ts",
    stage: "diagnostic",
    notes: "GR evolution brick serialization helpers.",
    checks: [
      { type: "residual", path: "tests/gr-constraint-network.spec.ts" },
      { type: "stability", path: "tests/gr-constraint-network.spec.ts" },
    ],
    residualsRequired: false,
    units: {
      bounds: "L",
      voxelSize_m: "L",
      time_s: "T",
      dt_s: "T",
      H_rms: "1",
      M_rms: "1",
      H_maxAbs: "1",
      M_maxAbs: "1",
    },
  },
  {
    tag: "GR_CORE",
    module: "server/gr/evolution/initial-data.ts",
    stage: "diagnostic",
    notes: "Initial data solve utilities.",
    checks: [
      { type: "residual", path: "tests/gr-constraint-network.spec.ts" },
      { type: "stability", path: "tests/gr-constraint-network.spec.ts" },
    ],
    residualsRequired: false,
    units: {
      bounds: "L",
      spacing: "L",
      iterations: "1",
      residual: "1",
      tolerance: "1",
      rho: "M L^-1 T^-2",
    },
  },
  {
    tag: "GR_CONSTRAINT",
    module: "server/gr/gr-constraint-network.ts",
    stage: "diagnostic",
    notes: "Constraint network evaluation for GR runs.",
    checks: [
      { type: "residual", path: "tests/gr-constraint-network.spec.ts" },
      { type: "stability", path: "tests/gr-constraint-network.spec.ts" },
    ],
    units: {
      updatedAt: "T",
      time_s: "T",
      dt_s: "T",
      steps: "1",
      iterations: "1",
      residual: "1",
      tolerance: "1",
      bounds: "L",
      voxelSize_m: "L",
      H_rms: "1",
      M_rms: "1",
      H_maxAbs: "1",
      M_maxAbs: "1",
    },
  },
  {
    tag: "GR_POLICY",
    module: "server/gr/gr-constraint-policy.ts",
    stage: "reduced-order",
    notes: "Constraint policy thresholds for GR gate.",
    checks: [{ type: "test", path: "tests/gr-constraint-gate.spec.ts" }],
    units: {
      H_rms_max: "1",
      M_rms_max: "1",
      H_maxAbs_max: "1",
      M_maxAbs_max: "1",
    },
  },
  {
    tag: "GR_LOOP",
    module: "server/gr/gr-agent-loop-schema.ts",
    stage: "reduced-order",
    notes: "Schema for GR agent loop inputs/budgets.",
    checks: [{ type: "test", path: "tests/gr-agent-loop.spec.ts" }],
    units: {
      maxIterations: "1",
      maxTotalMs: "T",
      maxAttemptMs: "T",
      evolveDt_s: "T",
      evolveSteps: "1",
      evolveIterations: "1",
      evolveTolerance: "1",
      initialIterations: "1",
      initialTolerance: "1",
      dims: "1",
      bounds: "L",
      dutyDecay: "1",
      gammaGeoDecay: "1",
      gammaVdBDecay: "1",
      qSpoilGrow: "1",
    },
  },
  {
    tag: "GR_WORKER",
    module: "server/gr/gr-worker-client.ts",
    stage: "exploratory",
    notes: "Worker client for GR evolution execution.",
    checks: [{ type: "doc", path: "docs/gr-solver-progress.md" }],
    units: {
      timeoutMs: "T",
      pendingCount: "1",
      enabled: "1",
      id: "1",
    },
  },
  {
    tag: "GR_WORKER",
    module: "server/gr/gr-worker-types.ts",
    stage: "exploratory",
    notes: "Worker message types for GR evolution.",
    checks: [{ type: "doc", path: "docs/gr-solver-progress.md" }],
    units: {
      id: "1",
      kind: "1",
      ok: "1",
      error: "1",
      stack: "1",
      dims: "1",
      bounds: "L",
      time_s: "T",
      dt_s: "T",
      steps: "1",
      iterations: "1",
      tolerance: "1",
    },
  },
  {
    tag: "GR_WORKER",
    module: "server/gr/gr-worker.ts",
    stage: "exploratory",
    notes: "Worker runtime for GR evolution execution.",
    checks: [{ type: "doc", path: "docs/gr-solver-progress.md" }],
    units: {
      id: "1",
      kind: "1",
      ok: "1",
      error: "1",
      stack: "1",
      bufferCount: "1",
    },
  },
  {
    tag: "WARP_CORE",
    module: "modules/warp/natario-warp.ts",
    stage: "reduced-order",
    notes: "Analytic warp proxy (not full GR).",
    checks: [{ type: "test", path: "tests/theory-checks.spec.ts" }],
    units: {
      bowlRadius: "L",
      sagDepth: "L",
      gap: "L",
      burstDuration: "T",
      cycleDuration: "T",
      shiftAmplitude: "1",
      effectivePathLength: "L",
      baselineEnergyDensity: "M L^-1 T^-2",
      amplifiedEnergyDensity: "M L^-1 T^-2",
      exoticMassPerTile: "M",
      totalExoticMass: "M",
      powerDraw: "M L^2 T^-3",
      momentumFlux: "M L T^-2",
      betaAvg: "1",
    },
  },
  {
    tag: "WARP_CORE",
    module: "modules/warp/warp-module.ts",
    stage: "reduced-order",
    notes: "Warp module wrapper + diagnostics.",
    checks: [{ type: "test", path: "tests/theory-checks.spec.ts" }],
    units: {
      dutyEffectiveFR: "1",
      gammaGeo: "1",
      gammaVanDenBroeck: "1",
      qSpoilingFactor: "1",
      tileArea_m2: "L^2",
      tileCount: "1",
      P_avg_W: "M L^2 T^-3",
      exoticMassTarget_kg: "M",
    },
  },
  {
    tag: "WARP_CERT",
    module: "tools/warpViabilityCertificate.ts",
    stage: "certified",
    notes: "Certificate issuance (policy-gated).",
    motivation:
      "Produce a deterministic, checkable certificate for warp viability based on the current pipeline evaluation.",
    conceptualWaypoints: [
      "Evaluate warp viability against constraints and capture snapshot data.",
      "Build canonical payload and header for reproducible hashing.",
      "Hash payload and certificate to provide integrity metadata.",
    ],
    checks: [
      { type: "test", path: "tests/theory-checks.spec.ts" },
      { type: "policy", path: "WARP_AGENTS.md" },
    ],
    units: {
      status: "1",
      certificateHash: "1",
      certificateId: "1",
      issuedAt: "T",
    },
  },
  {
    tag: "WARP_CERT",
    module: "tools/verifyCertificate.ts",
    stage: "certified",
    notes: "Certificate integrity verification.",
    motivation:
      "Recompute hashes to confirm certificate integrity and detect tampering.",
    conceptualWaypoints: [
      "Recreate the payload hash from canonical JSON.",
      "Rebuild the certificate hash and compare to the stored hash.",
      "Optionally re-evaluate and diff constraints/snapshot for drift checks.",
    ],
    checks: [
      { type: "test", path: "tests/theory-checks.spec.ts" },
      { type: "policy", path: "WARP_AGENTS.md" },
    ],
    units: {
      certificateHash: "1",
      integrityOk: "1",
    },
  },
  {
    tag: "WARP_IO",
    module: "server/skills/physics.warp.viability.ts",
    stage: "certified",
    notes: "Public viability tool endpoint.",
    motivation:
      "Expose warp viability evaluation to agents while enforcing policy gating and trace emission.",
    conceptualWaypoints: [
      "Validate tool input and build the warp config payload.",
      "Issue the certificate, verify integrity, and assemble response fields.",
      "Record training trace with constraint failures and certificate metadata.",
    ],
    checks: [
      { type: "test", path: "tests/theory-checks.spec.ts" },
      { type: "policy", path: "WARP_AGENTS.md" },
    ],
    units: {
      status: "1",
      certificateHash: "1",
      integrityOk: "1",
    },
  },
  {
    tag: "WARP_IO",
    module: "server/routes/warp-viability.ts",
    stage: "certified",
    notes: "HTTP route for viability + trace emission.",
    motivation:
      "Provide an HTTP endpoint that issues warp viability certificates and emits traces for external consumers.",
    conceptualWaypoints: [
      "Parse the request into a warp config and issue a certificate.",
      "Verify integrity and store results in the pipeline state.",
      "Emit a training trace with pass/fail and certificate status.",
    ],
    checks: [
      { type: "test", path: "tests/theory-checks.spec.ts" },
      { type: "policy", path: "WARP_AGENTS.md" },
    ],
    units: {
      status: "1",
      certificateHash: "1",
      integrityOk: "1",
    },
  },
  {
    tag: "STRESS_MAP",
    module: "server/stress-energy-brick.ts",
    stage: "reduced-order",
    notes: "Reduced-order stress-energy mapping.",
    checks: [
      { type: "test", path: "tests/stress-energy-brick.spec.ts" },
      { type: "test", path: "tests/stress-energy-matter.spec.ts" },
    ],
    units: {
      t00: "M L^-1 T^-2",
      avgT00: "M L^-1 T^-2",
      totalEnergy_J: "M L^2 T^-2",
      totalMomentum_kg_m_s: "M L T^-1",
      momentumMagnitude_kg_m_s: "M L T^-1",
      invariantMass_kg: "M",
      invariantMassEnergy_J: "M L^2 T^-2",
      gap_nm: "L",
      gap_m: "L",
      tileArea_cm2: "L^2",
      tileArea_m2: "L^2",
      tileCount: "1",
      dutyCycle: "1",
      dutyEffectiveFR: "1",
      dutyEff: "1",
      gammaGeo: "1",
      gammaVdB: "1",
      qSpoilingFactor: "1",
      cavityQ: "1",
      U_static_J: "M L^2 T^-2",
      staticEnergy: "M L^2 T^-2",
      boostedEnergy: "M L^2 T^-2",
      cycleAverageEnergy: "M L^2 T^-2",
      exoticEnergyDensity: "M L^-1 T^-2",
      P_avg_W: "M L^2 T^-3",
      instantaneousPower: "M L^2 T^-3",
      averagePower: "M L^2 T^-3",
      modulationFreq_GHz: "T^-1",
      burst_us: "T",
      cycle_us: "T",
      T00: "M L^-1 T^-2",
      T11: "M L^-1 T^-2",
      T22: "M L^-1 T^-2",
      T33: "M L^-1 T^-2",
      T00_avg: "M L^-1 T^-2",
      T11_avg: "M L^-1 T^-2",
      T22_avg: "M L^-1 T^-2",
      T33_avg: "M L^-1 T^-2",
      rho_avg: "M L^-1 T^-2",
      rho_inst: "M L^-1 T^-2",
      rho: "M L^-1 T^-2",
      stressEnergyT00_inst: "M L^-1 T^-2",
      beta_avg: "1",
      beta: "1",
      sectorStrobingEfficiency: "1",
      homogenizationRatio: "1",
      metric: "1",
      evolveDt_s: "T",
      dt: "T",
      time_s: "T",
      spacing: "L",
      bounds: "L",
      cfl: "1",
      H_rms: "1",
      M_rms: "1",
      H_maxAbs: "1",
      M_maxAbs: "1",
      H: "1",
      M: "1",
      Mx: "1",
      My: "1",
      Mz: "1",
    },
  },
  {
    tag: "STRESS_MAP",
    module: "server/gr/evolution/stress-energy.ts",
    stage: "reduced-order",
    notes: "Pipeline -> stress-energy fields.",
    checks: [
      { type: "test", path: "tests/stress-energy-brick.spec.ts" },
      { type: "test", path: "tests/stress-energy-matter.spec.ts" },
    ],
    units: {
      rho: "M L^-1 T^-2",
      dt: "T",
      evolveDt_s: "T",
      time_s: "T",
      spacing: "L",
      bounds: "L",
      H: "1",
      M: "1",
      Mx: "1",
      My: "1",
      Mz: "1",
      H_rms: "1",
      M_rms: "1",
      H_maxAbs: "1",
      M_maxAbs: "1",
      cfl: "1",
      gap_nm: "L",
      gap_m: "L",
      tileArea_cm2: "L^2",
      tileArea_m2: "L^2",
      tileCount: "1",
      dutyCycle: "1",
      dutyEffectiveFR: "1",
      dutyEff: "1",
      gammaGeo: "1",
      gammaVanDenBroeck: "1",
      qSpoilingFactor: "1",
      cavityQ: "1",
      U_static_J: "M L^2 T^-2",
      staticEnergy: "M L^2 T^-2",
      boostedEnergy: "M L^2 T^-2",
      cycleAverageEnergy: "M L^2 T^-2",
      totalEnergy_J: "M L^2 T^-2",
      totalMomentum_kg_m_s: "M L T^-1",
      momentumMagnitude_kg_m_s: "M L T^-1",
      invariantMass_kg: "M",
      invariantMassEnergy_J: "M L^2 T^-2",
      exoticEnergyDensity: "M L^-1 T^-2",
      P_avg_W: "M L^2 T^-3",
      instantaneousPower: "M L^2 T^-3",
      averagePower: "M L^2 T^-3",
      modulationFreq_GHz: "T^-1",
      burst_us: "T",
      cycle_us: "T",
      T00: "M L^-1 T^-2",
      T11: "M L^-1 T^-2",
      T22: "M L^-1 T^-2",
      T33: "M L^-1 T^-2",
      T00_avg: "M L^-1 T^-2",
      T11_avg: "M L^-1 T^-2",
      T22_avg: "M L^-1 T^-2",
      T33_avg: "M L^-1 T^-2",
      rho_avg: "M L^-1 T^-2",
      rho_inst: "M L^-1 T^-2",
      stressEnergyT00_inst: "M L^-1 T^-2",
      beta_avg: "1",
      sectorStrobingEfficiency: "1",
      homogenizationRatio: "1",
      metric: "1",
    },
  },
  {
    tag: "DYNAMIC",
    module: "modules/dynamic/stress-energy-equations.ts",
    stage: "reduced-order",
    notes: "Dynamic stress-energy helpers for pipeline/warp mapping.",
    checks: [
      { type: "test", path: "tests/stress-energy-brick.spec.ts" },
      { type: "test", path: "tests/stress-energy-matter.spec.ts" },
    ],
    units: {
      gap_m: "L",
      gap_nm: "L",
      tileArea_cm2: "L^2",
      tileArea_m2: "L^2",
      tileCount: "1",
      dutyCycle: "1",
      dutyEffectiveFR: "1",
      dutyEff: "1",
      gammaGeo: "1",
      gammaVdB: "1",
      qSpoilingFactor: "1",
      cavityQ: "1",
      U_static_J: "M L^2 T^-2",
      staticEnergy: "M L^2 T^-2",
      boostedEnergy: "M L^2 T^-2",
      cycleAverageEnergy: "M L^2 T^-2",
      totalEnergy_J: "M L^2 T^-2",
      totalMomentum_kg_m_s: "M L T^-1",
      momentumMagnitude_kg_m_s: "M L T^-1",
      invariantMass_kg: "M",
      invariantMassEnergy_J: "M L^2 T^-2",
      exoticEnergyDensity: "M L^-1 T^-2",
      P_avg_W: "M L^2 T^-3",
      instantaneousPower: "M L^2 T^-3",
      averagePower: "M L^2 T^-3",
      modulationFreq_GHz: "T^-1",
      burst_us: "T",
      cycle_us: "T",
      rho_avg: "M L^-1 T^-2",
      rho_inst: "M L^-1 T^-2",
      rho: "M L^-1 T^-2",
      T00: "M L^-1 T^-2",
      T11: "M L^-1 T^-2",
      T22: "M L^-1 T^-2",
      T33: "M L^-1 T^-2",
      stressEnergyT00_inst: "M L^-1 T^-2",
      beta_avg: "1",
      beta: "1",
      sectorStrobingEfficiency: "1",
      homogenizationRatio: "1",
      metric: "1",
      evolveDt_s: "T",
      dt: "T",
      time_s: "T",
      spacing: "L",
      bounds: "L",
      cfl: "1",
      H_rms: "1",
      M_rms: "1",
      H_maxAbs: "1",
      M_maxAbs: "1",
      H: "1",
      M: "1",
      Mx: "1",
      My: "1",
      Mz: "1",
    },
  },
  {
    tag: "DYNAMIC",
    module: "modules/dynamic/dynamic-casimir.ts",
    stage: "reduced-order",
    notes: "Dynamic Casimir sweep helpers (pipeline).",
    checks: [{ type: "test", path: "tests/theory-checks.spec.ts" }],
    units: {
      staticEnergy: "M L^2 T^-2",
      modulationFreqGHz: "T^-1",
      burstLengthUs: "T",
      cycleLengthUs: "T",
      cavityQ: "1",
      tileCount: "1",
      boostedEnergy: "M L^2 T^-2",
      cycleAverageEnergy: "M L^2 T^-2",
      exoticEnergyDensity: "M L^-1 T^-2",
      instantaneousPower: "M L^2 T^-3",
      averagePower: "M L^2 T^-3",
      gap_nm: "L",
      gap_m: "L",
      tileArea_cm2: "L^2",
      tileArea_m2: "L^2",
      dutyCycle: "1",
      dutyEffectiveFR: "1",
      dutyEff: "1",
      gammaGeo: "1",
      gammaVanDenBroeck: "1",
      qSpoilingFactor: "1",
      U_static_J: "M L^2 T^-2",
      P_avg_W: "M L^2 T^-3",
      T00: "M L^-1 T^-2",
      T11: "M L^-1 T^-2",
      T22: "M L^-1 T^-2",
      T33: "M L^-1 T^-2",
      T00_avg: "M L^-1 T^-2",
      T11_avg: "M L^-1 T^-2",
      T22_avg: "M L^-1 T^-2",
      T33_avg: "M L^-1 T^-2",
      rho_avg: "M L^-1 T^-2",
      rho_inst: "M L^-1 T^-2",
      rho: "M L^-1 T^-2",
      stressEnergyT00_inst: "M L^-1 T^-2",
      beta_avg: "1",
      beta: "1",
      totalEnergy_J: "M L^2 T^-2",
      totalMomentum_kg_m_s: "M L T^-1",
      momentumMagnitude_kg_m_s: "M L T^-1",
      invariantMass_kg: "M",
      invariantMassEnergy_J: "M L^2 T^-2",
      sectorStrobingEfficiency: "1",
      homogenizationRatio: "1",
      metric: "1",
      evolveDt_s: "T",
      dt: "T",
      time_s: "T",
      spacing: "L",
      bounds: "L",
      cfl: "1",
      H_rms: "1",
      M_rms: "1",
      H_maxAbs: "1",
      M_maxAbs: "1",
      H: "1",
      M: "1",
      Mx: "1",
      My: "1",
      Mz: "1",
    },
  },
  {
    tag: "DYNAMIC",
    module: "modules/dynamic/natario-metric.ts",
    stage: "reduced-order",
    notes: "Natario metric proxy helpers (pipeline).",
    checks: [{ type: "test", path: "tests/theory-checks.spec.ts" }],
    units: {
      stressEnergyT00: "M L^-1 T^-2",
      stressEnergyT11: "M L^-1 T^-2",
      stressEnergyT00_inst: "M L^-1 T^-2",
      natarioShiftAmplitude: "1",
      sectorStrobingEfficiency: "1",
      homogenizationRatio: "1",
      metric: "1",
      gap_nm: "L",
      gap_m: "L",
      tileArea_cm2: "L^2",
      tileArea_m2: "L^2",
      tileCount: "1",
      dutyCycle: "1",
      dutyEffectiveFR: "1",
      dutyEff: "1",
      gammaGeo: "1",
      gammaVanDenBroeck: "1",
      qSpoilingFactor: "1",
      cavityQ: "1",
      U_static_J: "M L^2 T^-2",
      staticEnergy: "M L^2 T^-2",
      boostedEnergy: "M L^2 T^-2",
      cycleAverageEnergy: "M L^2 T^-2",
      totalEnergy_J: "M L^2 T^-2",
      totalMomentum_kg_m_s: "M L T^-1",
      momentumMagnitude_kg_m_s: "M L T^-1",
      invariantMass_kg: "M",
      invariantMassEnergy_J: "M L^2 T^-2",
      exoticEnergyDensity: "M L^-1 T^-2",
      P_avg_W: "M L^2 T^-3",
      instantaneousPower: "M L^2 T^-3",
      averagePower: "M L^2 T^-3",
      modulationFreq_GHz: "T^-1",
      burst_us: "T",
      cycle_us: "T",
      T00: "M L^-1 T^-2",
      T11: "M L^-1 T^-2",
      T22: "M L^-1 T^-2",
      T33: "M L^-1 T^-2",
      T00_avg: "M L^-1 T^-2",
      T11_avg: "M L^-1 T^-2",
      T22_avg: "M L^-1 T^-2",
      T33_avg: "M L^-1 T^-2",
      rho_avg: "M L^-1 T^-2",
      rho_inst: "M L^-1 T^-2",
      rho: "M L^-1 T^-2",
      beta_avg: "1",
      beta: "1",
      evolveDt_s: "T",
      dt: "T",
      time_s: "T",
      spacing: "L",
      bounds: "L",
      cfl: "1",
      H_rms: "1",
      M_rms: "1",
      H_maxAbs: "1",
      M_maxAbs: "1",
      H: "1",
      M: "1",
      Mx: "1",
      My: "1",
      Mz: "1",
    },
  },
  {
    tag: "PIPELINE",
    module: "server/energy-pipeline.ts",
    stage: "reduced-order",
    notes: "Energy pipeline core (mixed proxies + calibration).",
    checks: [{ type: "test", path: "tests/pipeline-ts-qi-guard.spec.ts" }],     
    units: {
      gap_nm: "L",
      gap_m: "L",
      tileArea_cm2: "L^2",
      tileArea_m2: "L^2",
      tileCount: "1",
      dutyCycle: "1",
      dutyEffectiveFR: "1",
      dutyEff: "1",
      gammaGeo: "1",
      gammaVanDenBroeck: "1",
      qSpoilingFactor: "1",
      cavityQ: "1",
      U_static_J: "M L^2 T^-2",
      staticEnergy: "M L^2 T^-2",
      boostedEnergy: "M L^2 T^-2",
      cycleAverageEnergy: "M L^2 T^-2",
      totalEnergy_J: "M L^2 T^-2",
      totalMomentum_kg_m_s: "M L T^-1",
      momentumMagnitude_kg_m_s: "M L T^-1",
      invariantMass_kg: "M",
      invariantMassEnergy_J: "M L^2 T^-2",
      exoticEnergyDensity: "M L^-1 T^-2",
      P_avg_W: "M L^2 T^-3",
      instantaneousPower: "M L^2 T^-3",
      averagePower: "M L^2 T^-3",
      modulationFreq_GHz: "T^-1",
      burst_us: "T",
      cycle_us: "T",
      T00: "M L^-1 T^-2",
      T11: "M L^-1 T^-2",
      T22: "M L^-1 T^-2",
      T33: "M L^-1 T^-2",
      T00_avg: "M L^-1 T^-2",
      T11_avg: "M L^-1 T^-2",
      T22_avg: "M L^-1 T^-2",
      T33_avg: "M L^-1 T^-2",
      rho_avg: "M L^-1 T^-2",
      rho_inst: "M L^-1 T^-2",
      rho: "M L^-1 T^-2",
      stressEnergyT00_inst: "M L^-1 T^-2",
      beta_avg: "1",
      beta: "1",
      sectorStrobingEfficiency: "1",
      homogenizationRatio: "1",
      metric: "1",
      evolveDt_s: "T",
      dt: "T",
      time_s: "T",
      spacing: "L",
      bounds: "L",
      cfl: "1",
      H_rms: "1",
      M_rms: "1",
      H_maxAbs: "1",
      M_maxAbs: "1",
      H: "1",
      M: "1",
      Mx: "1",
      My: "1",
      Mz: "1",
    },
  },
  {
    tag: "WARP_EVAL",
    module: "tools/warpViability.ts",
    stage: "diagnostic",
    notes: "Warp viability evaluation from pipeline + guardrails.",
    checks: [
      { type: "stability", path: "tools/__tests__/warpViability.spec.ts" },
      { type: "policy", path: "WARP_AGENTS.md" },
    ],
    units: {
      status: "1",
      pass: "1",
      TS_ratio: "1",
      thetaCal: "1",
      gammaVdB: "1",
      M_exotic: "M",
      T00_avg: "M L^-1 T^-2",
      bubbleRadius_m: "L",
      wallThickness_m: "L",
      sectorPeriod_ms: "T",
      dwell_ms: "T",
      burst_ms: "T",
    },
  },
  {
    tag: "WARP_AUDIT",
    module: "shared/contracts/nhm2-full-loop-audit.v1.ts",
    stage: "diagnostic",
    notes:
      "Typed NHM2 full-loop audit contract for section-level readiness, blockers, and policy result reporting.",
    checks: [
      { type: "stability", path: "tests/nhm2-full-loop-audit-contract.spec.ts" },
      { type: "policy", path: "WARP_AGENTS.md" },
    ],
    units: {
      currentClaimTier: "1",
      maximumClaimTier: "1",
      highestPassingClaimTier: "1",
      overallState: "1",
      H_rms: "1",
      M_rms: "1",
      H_maxAbs: "1",
      M_maxAbs: "1",
      residualRms: "1",
      residualMax: "1",
      coordinateTimeEstimateSeconds: "T",
      properTimeEstimateSeconds: "T",
      properMinusCoordinateSeconds: "T",
      centerlineProperAcceleration_mps2: "L T^-2",
      wallNormalSafetyMargin: "1",
      blueshiftMax: "1",
      meshConvergenceOrder: "1",
      boundaryConditionSensitivity: "1",
      smoothingKernelSensitivity: "1",
    },
  },
  {
    tag: "WARP_POLICY",
    module: "modules/physics/warpAgents.ts",
    stage: "reduced-order",
    notes: "Warp guardrail definitions (policy registry).",
    checks: [
      { type: "test", path: "tests/theory-checks.spec.ts" },
      { type: "policy", path: "WARP_AGENTS.md" },
    ],
    units: {
      H_rms_max: "1",
      M_rms_max: "1",
      H_maxAbs_max: "1",
      M_maxAbs_max: "1",
      maxSamples: "1",
      concurrency: "1",
      topK: "1",
    },
  },
  {
    tag: "TRACE",
    module: "server/services/observability/training-trace-store.ts",
    stage: "diagnostic",
    notes: "Training trace storage and export (audit/data flywheel).",
    checks: [
      { type: "stability", path: "server/__tests__/training-trace.test.ts" },
    ],
    units: {
      seq: "1",
      ts: "T",
      pass: "1",
    },
  },
  {
    tag: "TRACE",
    module: "server/routes/training-trace.ts",
    stage: "diagnostic",
    notes: "Training trace API routes (ingest/list/export).",
    checks: [
      { type: "stability", path: "server/__tests__/training-trace.test.ts" },
    ],
    units: {
      limit: "1",
      ts: "T",
      pass: "1",
    },
  },
  {
    tag: "GR_AUDIT",
    module: "server/services/observability/gr-agent-loop-store.ts",
    stage: "diagnostic",
    notes: "GR agent loop audit log storage.",
    checks: [
      { type: "residual", path: "tests/gr-agent-loop.spec.ts" },
      { type: "stability", path: "tests/gr-agent-loop.spec.ts" },
    ],
    units: {
      duration_ms: "T",
      attempts: "1",
      accepted: "1",
      H_rms: "1",
      M_rms: "1",
      H_maxAbs: "1",
      M_maxAbs: "1",
    },
  },
  {
    tag: "LOG_STORE",
    module: "server/services/observability/tool-log-store.ts",
    stage: "exploratory",
    notes: "Tool log store (non-math telemetry).",
    checks: [{ type: "doc", path: "docs/TRACE-API.md" }],
    units: {
      durationMs: "T",
      ts: "T",
      seq: "1",
      limit: "1",
      bufferSize: "1",
      ok: "1",
    },
  },
  {
    tag: "ADAPTER",
    module: "server/routes/agi.adapter.ts",
    stage: "diagnostic",
    notes: "Adapter API (actions -> verdict + trace).",
    checks: [
      { type: "stability", path: "server/__tests__/agi.adapter.test.ts" },
    ],
    units: {
      duration_ms: "T",
      maxIterations: "1",
      maxTotalMs: "T",
      maxAttemptMs: "T",
      delta: "1",
    },
  },
  {
    tag: "AGI_PLAN",
    module: "server/routes/agi.plan.ts",
    stage: "reduced-order",
    notes: "Plan/execute route (non-math runtime).",
    checks: [{ type: "test", path: "tests/agi-plan.spec.ts" }],
    units: {
      duration_ms: "T",
      limit: "1",
      topK: "1",
    },
  },
  {
    tag: "AGI_EVAL",
    module: "server/routes/agi.eval.ts",
    stage: "reduced-order",
    notes: "Eval route for agent runs.",
    checks: [{ type: "test", path: "tests/eval-endpoint.spec.ts" }],
    units: {
      duration_ms: "T",
      limit: "1",
    },
  },
  {
    tag: "AGI_MEMORY",
    module: "server/routes/agi.memory.ts",
    stage: "reduced-order",
    notes: "Memory CRUD routes.",
    checks: [{ type: "test", path: "tests/agi-memory.spec.ts" }],
    units: {
      limit: "1",
      count: "1",
    },
  },
  {
    tag: "AGI_TRACE",
    module: "server/routes/agi.memory.trace.ts",
    stage: "reduced-order",
    notes: "Memory trace streaming route.",
    checks: [{ type: "test", path: "tests/trace-api.spec.ts" }],
    units: {
      limit: "1",
      count: "1",
    },
  },
  {
    tag: "AGI_PERSONA",
    module: "server/routes/agi.persona.ts",
    stage: "reduced-order",
    notes: "Persona route wiring.",
    checks: [{ type: "test", path: "tests/persona-policy.spec.ts" }],
    units: {
      count: "1",
    },
  },
  {
    tag: "AGI_PROFILE",
    module: "server/routes/agi.profile.ts",
    stage: "reduced-order",
    notes: "Profile summarizer endpoints.",
    checks: [{ type: "test", path: "tests/essence-dal.spec.ts" }],
    units: {
      count: "1",
    },
  },
  {
    tag: "AGI_SPECIALISTS",
    module: "server/routes/agi.specialists.ts",
    stage: "reduced-order",
    notes: "Specialists routing and controls.",
    checks: [{ type: "test", path: "tests/specialists.math.spec.ts" }],
    units: {
      count: "1",
    },
  },
  {
    tag: "AGI_STAR",
    module: "server/routes/agi.star.ts",
    stage: "reduced-order",
    notes: "Star telemetry route.",
    checks: [{ type: "test", path: "tests/solar-energy-adapter.spec.ts" }],
    units: {
      duration_ms: "T",
      count: "1",
    },
  },
  {
    tag: "NEURO",
    module: "shared/neuro-config.ts",
    stage: "exploratory",
    notes: "Neuro coherence defaults (gamma band + equilibrium thresholds).",
    checks: [
      { type: "doc", path: "docs/stellar-consciousness-orch-or-review.md" },
    ],
    units: {
      gamma_band_low_hz: "T^-1",
      gamma_band_high_hz: "T^-1",
      equilibrium_r_star: "1",
      equilibrium_dispersion_max: "1",
      equilibrium_hold_ms: "T",
    },
  },
  {
    tag: "AGI_TRACE",
    module: "server/routes/agi.trace.ts",
    stage: "reduced-order",
    notes: "Trace/log streaming routes.",
    checks: [{ type: "test", path: "tests/trace-api.spec.ts" }],
    units: {
      limit: "1",
      count: "1",
    },
  },
  {
    tag: "AGI_DEBATE",
    module: "server/routes/agi.debate.ts",
    stage: "reduced-order",
    notes: "Debate routing + orchestration.",
    checks: [{ type: "test", path: "tests/debate-orchestrator.spec.ts" }],
    units: {
      duration_ms: "T",
      count: "1",
    },
  },
  {
    tag: "PACKS",
    module: "server/services/observability/constraint-pack-evaluator.ts",
    stage: "diagnostic",
    notes: "Constraint-pack evaluators for telemetry.",
    checks: [
      {
        type: "stability",
        path: "server/__tests__/constraint-packs.evaluate.test.ts",
      },
    ],
    units: {
      time_to_green_ms: "T",
      durationMs: "T",
      runtime_ms: "T",
      cost_usd: "1",
      tests_failed: "1",
      tests_total: "1",
      steps_used: "1",
      ops_forbidden: "1",
    },
  },
  {
    tag: "PACKS",
    module: "server/services/observability/constraint-pack-normalizer.ts",
    stage: "diagnostic",
    notes: "Normalizer -> training trace records.",
    checks: [
      {
        type: "stability",
        path: "server/__tests__/constraint-packs.evaluate.test.ts",
      },
    ],
    units: {
      pass: "1",
      certificateHash: "1",
      ts: "T",
    },
  },
  {
    tag: "PACKS",
    module: "server/services/observability/constraint-pack-telemetry.ts",
    stage: "diagnostic",
    notes: "Telemetry ingestion helpers (env -> pack inputs).",
    checks: [
      {
        type: "stability",
        path: "server/__tests__/constraint-packs.evaluate.test.ts",
      },
    ],
    units: {
      durationMs: "T",
      time_to_green_ms: "T",
      runtime_ms: "T",
      tests_failed: "1",
      tests_total: "1",
      cost_usd: "1",
    },
  },
  {
    tag: "PACKS",
    module: "server/routes/agi.constraint-packs.ts",
    stage: "diagnostic",
    notes: "Constraint-pack API routes (list/evaluate/policy).",
    checks: [
      {
        type: "stability",
        path: "server/__tests__/constraint-packs.evaluate.test.ts",
      },
    ],
    units: {
      pass: "1",
      limit: "1",
      count: "1",
    },
  },
  {
    tag: "PACKS",
    module: "server/services/constraint-packs/constraint-pack-policy.ts",
    stage: "reduced-order",
    notes: "Policy override application and ladder enforcement.",
    checks: [
      {
        type: "test",
        path: "server/__tests__/constraint-packs.evaluate.test.ts",
      },
    ],
    units: {
      limit: "1",
      min: "1",
      max: "1",
    },
  },
  {
    tag: "PACKS",
    module: "server/services/constraint-packs/constraint-pack-policy-store.ts",
    stage: "reduced-order",
    notes: "Policy profile persistence (JSONL store).",
    checks: [
      {
        type: "test",
        path: "server/__tests__/constraint-packs.evaluate.test.ts",
      },
    ],
    units: {
      version: "1",
      createdAt: "T",
      updatedAt: "T",
      limit: "1",
    },
  },
  {
    tag: "ANALYSIS",
    module: "modules/analysis/constraint-loop.ts",
    stage: "exploratory",
    notes: "Generic constraint loop runner (prototype).",
    checks: [{ type: "doc", path: "modules/analysis/README.md" }],
    units: {
      iteration: "1",
      maxIterations: "1",
      accepted: "1",
      acceptedIteration: "1",
      residual: "1",
      status: "1",
    },
  },
  {
    tag: "ANALYSIS",
    module: "modules/analysis/noise-field-loop.ts",
    stage: "exploratory",
    notes: "Noise field loop (prototype).",
    checks: [{ type: "doc", path: "modules/analysis/README.md" }],
    units: {
      width: "1",
      height: "1",
      seed: "1",
      maxIterations: "1",
      stepSize: "1",
      laplacianRms: "1",
      laplacianMaxAbs: "1",
    },
  },
  {
    tag: "ANALYSIS",
    module: "modules/analysis/diffusion-loop.ts",
    stage: "exploratory",
    notes: "Diffusion loop stub (prototype).",
    checks: [{ type: "doc", path: "modules/analysis/README.md" }],
    units: {
      width: "1",
      height: "1",
      channels: "1",
      seed: "1",
      maxIterations: "1",
      stepSize: "1",
      scoreWeight: "1",
      smoothWeight: "1",
      scoreRms: "1",
      scoreMaxAbs: "1",
      fidelityRms: "1",
    },
  },
  {
    tag: "ANALYSIS",
    module: "modules/analysis/belief-graph-loop.ts",
    stage: "exploratory",
    notes: "Belief graph loop (prototype).",
    checks: [{ type: "doc", path: "modules/analysis/README.md" }],
    units: {
      maxIterations: "1",
      stepSize: "1",
      violationCount: "1",
      violationWeight: "1",
      axiomViolations: "1",
      impliesViolations: "1",
      excludesViolations: "1",
      maxAbsPressure: "1",
    },
  },
  {
    tag: "ANALYSIS",
    module: "server/routes/analysis-loops.ts",
    stage: "exploratory",
    notes: "Analysis loop API endpoints.",
    checks: [{ type: "doc", path: "modules/analysis/README.md" }],
    units: {
      width: "1",
      height: "1",
      channels: "1",
      seed: "1",
      maxIterations: "1",
      stepSize: "1",
      iterations: "1",
      min: "1",
      max: "1",
      mean: "1",
    },
  },
  {
    tag: "OBS",
    module: "server/services/observability/otel-tracing.ts",
    stage: "exploratory",
    notes: "OTEL span helpers (instrumentation).",
    checks: [{ type: "doc", path: "docs/ENVIRONMENT.md" }],
    units: {
      durationMs: "T",
      startTimeUnixNano: "T",
      endTimeUnixNano: "T",
      traceId: "1",
      spanId: "1",
      status: "1",
    },
  },
  {
    tag: "OBS",
    module: "server/services/observability/otel-middleware.ts",
    stage: "exploratory",
    notes: "OTEL middleware (instrumentation).",
    checks: [{ type: "doc", path: "docs/ENVIRONMENT.md" }],
    units: {
      status_code: "1",
      durationMs: "T",
    },
  },
  {
    tag: "OBS",
    module: "server/services/observability/otel-span-store.ts",
    stage: "exploratory",
    notes: "In-memory OTEL span store (debug tooling).",
    checks: [{ type: "doc", path: "docs/ENVIRONMENT.md" }],
    units: {
      durationMs: "T",
      startTimeUnixNano: "T",
      endTimeUnixNano: "T",
      ts: "T",
      seq: "1",
      limit: "1",
    },
  },
  {
    tag: "QST_PROXY",
    module: "shared/quantum-spacetime-congruence.ts",
    stage: "exploratory",
    notes: "Quantum-spacetime congruence proxy contract for entropy stretch, holographic area proxy, and vacuum-channel gating.",
    motivation:
      "Keep Big Bang expansion, ER=EPR, and entropy-stretch ideas in a diagnostic proxy lane that cannot bypass metric, stress-energy, or QI gates.",
    conceptualWaypoints: [
      "Separate entropy stretch from cosmological area/volume stretch.",
      "Encode holographic area as erDensityProxy, not wormhole inventory.",
      "Block Hubble-rate-only dynamic Casimir photon-production links.",
    ],
    checks: [
      { type: "test", path: "tests/quantum-spacetime-congruence.spec.ts" },
      { type: "policy", path: "docs/warp-tree-dag-congruence-policy.md" },
    ],
    units: {
      deltaS_nats: "1",
      lambda: "1",
      hbarEffectiveRatio: "1",
      quantumVisibility: "1",
      H0_sInv: "T^-1",
      scaleFactorRatio: "1",
      areaStretch: "1",
      volumeStretch: "1",
      entanglementEntropy_nats: "1",
      rtAreaProxy_m2: "L^2",
      erDensityProxy: "1",
      localDriveFrequency_Hz: "T^-1",
      expansionFrequency_Hz: "T^-1",
    },
  },
  {
    tag: "ER_EPR_STAGE1_SIM",
    module: "shared/er-epr-simulation.ts",
    stage: "reduced-order",
    notes: "Stage 1 ER=EPR simulation verdict contract for controlled holographic toy models, QST entropy-stretch demotion, and StarSim structure-prior boundaries.",
    motivation:
      "Test whether a controlled entangled model produces ER=EPR-like geometry observables while ordinary controls fail, without promoting the result into metric, stress-energy, or real-universe wormhole evidence.",
    conceptualWaypoints: [
      "Require holographic/toy-dual model family, two-sided entangled state, and correct-sign double-trace coupling.",
      "Require ordinary teleportation, shuffled-Hamiltonian, disentangled, and wrong-sign controls to fail.",
      "Require size-winding, scrambling, thermalization, causal-order, delay, and entropy/area tracking diagnostics.",
      "Use QST entropy stretch to demote quantum visibility instead of redefining hbar.",
      "Treat StarSim astrometry only as a cosmological structure prior, never direct ER=EPR evidence.",
      "Force spacetimeCL proxy_only and mayPromoteToCL4 false for every verdict.",
    ],
    checks: [
      { type: "test", path: "tests/er-epr-simulation.spec.ts" },
      { type: "doc", path: "docs/research/er-epr-stage1-simulation.md" },
      { type: "policy", path: "docs/warp-tree-dag-congruence-policy.md" },
    ],
    units: {
      nQubitsOrModes: "1",
      probeInsertionTime: "T",
      measurementWindow: "T",
      mutualInformation: "1",
      entanglementEntropy_nats: "1",
      rtAreaProxy_m2: "L^2",
      teleportationFidelity: "1",
      causalOrderingScore: "1",
      timeDelayScore: "1",
      operatorSizeWindingScore: "1",
      scramblingScore: "1",
      thermalizationScore: "1",
      entropyAreaProxyTrackingScore: "1",
      controlLeakage: "1",
      entropyVisibility: "1",
      visibilityAdjustedSignal: "1",
      clusteringEntropy_nats: "1",
      localDensityContrast: "1",
      velocityDispersion_km_s: "L T^-1",
    },
  },
  {
    tag: "ER_EPR_STAGE1_RUNNER",
    module: "shared/er-epr-stage1-runner.ts",
    stage: "reduced-order",
    notes: "Reproducible ER=EPR Stage 1 fixture/null-control runner and batch report contract.",
    motivation:
      "Make ER=EPR Stage 1 simulated-experiment claims replayable, control-paired, citation-bound, and explicitly fixture/simulation/reproduction scoped.",
    conceptualWaypoints: [
      "Consume normalized observables rather than pretending to solve SYK/JT dynamics.",
      "Require paired candidate and null-control evaluations before allowing model-internal support.",
      "Demote batch verdicts when controls carry signal or required controls are missing.",
      "Emit claim IDs, citations, source roles, uncertainty notes, caveats, and reproducibility status.",
      "Keep reports as generated evidence, not primary math source.",
    ],
    checks: [
      { type: "test", path: "tests/er-epr-stage1-runner.spec.ts" },
      { type: "test", path: "tests/er-epr-stage1-report.spec.ts" },
      { type: "fixture", path: "tests/fixtures/er-epr-stage1/plan.fixture.json" },
    ],
    units: {
      signalMin: "1",
      controlMax: "1",
      diagnosticMin: "1",
      entropyAreaTrackingMin: "1",
      entropyVisibilityMin: "1",
      strongSupportMin: "1",
      signalComposite: "1",
      controlLeakage: "1",
      entropyWashoutObserved: "1",
    },
  },
  {
    tag: "ER_EPR_STAGE1_RUNNER",
    module: "shared/er-epr-safe-language.ts",
    stage: "reduced-order",
    notes: "Claim-safe ER=EPR Stage 1 report language renderer and forbidden-phrase validator.",
    checks: [{ type: "test", path: "tests/er-epr-safe-language.spec.ts" }],
    units: {
      forbiddenPhraseCount: "1",
      claimIdCount: "1",
      citationCount: "1",
    },
  },
  {
    tag: "ER_EPR_STAGE1_SOLVER_ADAPTER_V1",
    module: "shared/er-epr-raw-observables.ts",
    stage: "diagnostic",
    notes:
      "Raw ER=EPR solver telemetry contract for declared toy-dual and control backends before interpretation.",
    motivation:
      "Prevent normalized-only scores from being mistaken for solver evidence by preserving backend, Hamiltonian, seed, correlator, operator-size, and provenance telemetry.",
    conceptualWaypoints: [
      "Declare backend family and model parameters.",
      "Preserve raw fidelity, correlator, time-delay, and operator-size telemetry.",
      "Require provenance, claim IDs, citations, and caveats.",
    ],
    checks: [
      { type: "test", path: "tests/er-epr-raw-observables.spec.ts" },
      { type: "stability", path: "tests/er-epr-raw-observables.spec.ts" },
      { type: "fixture", path: "tests/fixtures/er-epr-solver/two-sided-syk-raw.fixture.json" },
      { type: "doc", path: "docs/research/er-epr-stage1-solver-adapter-v1.md" },
      { type: "policy", path: "docs/knowledge/math-claims/er-epr-solver-adapter.claims.json" },
    ],
    units: {
      nQubitsOrModes: "1",
      beta: "1",
      injectionTime: "T",
      couplingTime: "T",
      extractionTime: "T",
      teleportationFidelityRaw: "1",
      leftRightMutualInformation: "1",
      entanglementEntropy_nats: "1",
    },
  },
  {
    tag: "ER_EPR_STAGE1_SOLVER_ADAPTER_V1",
    module: "shared/er-epr-observable-normalizer.ts",
    stage: "diagnostic",
    notes:
      "Normalizes raw solver telemetry into the existing ER_EPR_STAGE1_SIM observable contract.",
    checks: [
      { type: "test", path: "tests/er-epr-observable-normalizer.spec.ts" },
      { type: "stability", path: "tests/er-epr-observable-normalizer.spec.ts" },
    ],
    units: {
      teleportationFidelity: "1",
      causalOrderingScore: "1",
      timeDelayScore: "1",
      operatorSizeWindingScore: "1",
      scramblingScore: "1",
      thermalizationScore: "1",
      entropyAreaProxyTrackingScore: "1",
    },
  },
  {
    tag: "ER_EPR_STAGE1_SOLVER_ADAPTER_V1",
    module: "shared/er-epr-solver-adapter.ts",
    stage: "diagnostic",
    notes:
      "Solver adapter connecting raw declared toy-dual telemetry to ER_EPR_STAGE1_SIM evaluations with provenance gates.",
    checks: [
      { type: "test", path: "tests/er-epr-solver-adapter.spec.ts" },
      { type: "stability", path: "tests/er-epr-solver-adapter.spec.ts" },
      { type: "fixture", path: "tests/fixtures/er-epr-solver/high-entropy-washout-raw.fixture.json" },
      { type: "doc", path: "docs/research/er-epr-stage1-solver-adapter-v1.md" },
    ],
    units: {
      signalComposite: "1",
      controlLeakage: "1",
      entropyVisibility: "1",
      visibilityAdjustedSignal: "1",
    },
  },
  {
    tag: "ER_EPR_STAGE1_SOLVER_ADAPTER_V1",
    module: "shared/er-epr-solver-safe-language.ts",
    stage: "diagnostic",
    notes:
      "Safe-language renderer blocking real-universe, wormhole, NHM2 propulsion, stress-energy, and CL4 claims from solver telemetry.",
    checks: [
      { type: "test", path: "tests/er-epr-solver-safe-language.spec.ts" },
      { type: "test", path: "tests/er-epr-solver-artifact.spec.ts" },
      { type: "stability", path: "tests/er-epr-solver-safe-language.spec.ts" },
    ],
    units: {
      forbiddenPhraseCount: "1",
      claimIdCount: "1",
      citationCount: "1",
      uncertaintyNoteCount: "1",
    },
  },
  {
    tag: "STARSIM_FUSION_MICROPHYSICS_STAGE1",
    module: "shared/starsim-fusion-microphysics.ts",
    stage: "reduced-order",
    notes:
      "Stage 1 StarSim stellar fusion microphysics prior for fusion-channel, fusion-zone, hSpectralFit, compact-object, and star-map graph diagnostics.",
    motivation:
      "Add astrophysical microphysics and population priors to StarSim/QST experiments while blocking direct ER=EPR, wormhole, propulsion, stress-energy, and CL0-CL4 claims.",
    conceptualWaypoints: [
      "Separate surface effective temperature from core temperature.",
      "Classify PP-chain, CNO, red-giant shell burning, inactive brown dwarfs, and compact objects.",
      "Define fusion-zone volume by cumulative nuclear luminosity radii rather than whole-star volume.",
      "Treat hSpectralFit as calibration only because h is exact in SI.",
      "Use StarMap graph structure as an astrophysical population prior, not direct quantum-gravity evidence.",
      "Force spacetimeCL proxy_only and mayPromoteToCL4 false for every evaluation.",
    ],
    checks: [
      { type: "test", path: "tests/starsim-fusion-microphysics.spec.ts" },
      { type: "test", path: "tests/starsim-fusion-artifact.spec.ts" },
      { type: "doc", path: "docs/research/starsim-fusion-microphysics-stage1.md" },
      {
        type: "policy",
        path: "docs/knowledge/math-claims/starsim-fusion-microphysics.claims.json",
      },
    ],
    units: {
      luminosity_Lsun: "1",
      radius_Rsun: "1",
      effectiveTemperature_K: "Theta",
      mass_Msun: "1",
      metallicity_feh: "1",
      logg_cgs: "L T^-2",
      parallax_mas: "1",
      properMotionRa_masyr: "1 T^-1",
      properMotionDec_masyr: "1 T^-1",
      radialVelocity_kms: "L T^-1",
      estimatedCoreTemperature_K: "Theta",
      estimatedCoreDensity_g_cm3: "M L^-3",
      r10_Rstar: "1",
      r50_Rstar: "1",
      r90_Rstar: "1",
      activeVolumeFraction: "1",
      quantumProcessIndex: "1",
      entropyVisibilityProxy: "1",
      fittedH_Js: "M L^2 T^-1",
      exactH_Js: "M L^2 T^-1",
      position_pc: "L",
      velocity_km_s: "L T^-1",
      distance_pc: "L",
      relativeVelocity_km_s: "L T^-1",
      structureWeight: "1",
      fusionContrastWeight: "1",
    },
  },
  {
    tag: "STARSIM_FUSION_MICROPHYSICS_STAGE1",
    module: "shared/starsim-fusion-artifact.ts",
    stage: "reduced-order",
    notes:
      "Artifact contract for StarSim fusion microphysics evaluations with claim IDs, citations, caveats, and reproducibility status.",
    checks: [{ type: "test", path: "tests/starsim-fusion-artifact.spec.ts" }],
    units: {
      claimIdCount: "1",
      citationCount: "1",
      caveatCount: "1",
    },
  },
  {
    tag: "STARSIM_FUSION_SAFE_LANGUAGE",
    module: "shared/starsim-fusion-safe-language.ts",
    stage: "reduced-order",
    notes:
      "Claim-safe StarSim fusion report renderer and forbidden-language validator with source roles, uncertainty notes, and validity domains.",
    motivation:
      "Prevent reduced-order stellar microphysics priors from being rendered as direct ER=EPR, wormhole, propulsion, stress-energy, metric, or Planck-constant claims.",
    conceptualWaypoints: [
      "Render claim IDs, citations, source roles, uncertainty notes, validity domains, and caveats together.",
      "Block predictive overclaims while allowing explicit negative boundary language.",
      "Treat the renderer as reporting and policy support, not primary physics evidence.",
    ],
    checks: [
      { type: "test", path: "tests/starsim-fusion-safe-language.spec.ts" },
      { type: "test", path: "tests/starsim-fusion-claims.spec.ts" },
      { type: "doc", path: "docs/research/starsim-fusion-microphysics-stage1.md" },
    ],
    units: {
      forbiddenPhraseCount: "1",
      claimIdCount: "1",
      citationCount: "1",
      uncertaintyNoteCount: "1",
      validityDomainCount: "1",
    },
  },
  {
    tag: "STARSIM_FUSION_PROFILE_IMPORT_STAGE2_PREP",
    module: "shared/starsim-fusion-profile-import.ts",
    stage: "reduced-order",
    notes:
      "MESA-compatible StarSim fusion profile import schema for fixture, MESA, external, reduced-order, and compact-object profiles.",
    motivation:
      "Prepare the StarSim fusion lane for Stage 2 review by grounding reduced-order estimates in imported shell profiles without promoting QST or ER=EPR claims.",
    conceptualWaypoints: [
      "Validate shell profile provenance, reproducibility status, and integration basis.",
      "Require claim IDs, citations, and caveats for imported profiles.",
      "Keep profile import as Stage 1-to-Stage 2 preparation, not certified stellar evolution.",
    ],
    checks: [
      { type: "test", path: "tests/starsim-fusion-profile-import.spec.ts" },
      { type: "fixture", path: "tests/fixtures/starsim-fusion-profiles/solar-mesa-profile.fixture.json" },
      { type: "doc", path: "docs/research/starsim-fusion-profile-import-stage2-prep.md" },
      { type: "policy", path: "docs/knowledge/math-claims/starsim-fusion-profile-import.claims.json" },
    ],
    units: {
      radius_Rstar: "1",
      radius_cm: "L",
      massCoordinate_Msun: "1",
      enclosedMass_Msun: "1",
      shellMass_g: "M",
      temperature_K: "Theta",
      density_g_cm3: "M L^-3",
      pressure_dyn_cm2: "M L^-1 T^-2",
      luminosity_Lsun: "1",
      epsNuc_erg_g_s: "L^2 T^-3",
      epsPp_erg_g_s: "L^2 T^-3",
      epsCno_erg_g_s: "L^2 T^-3",
      epsTripleAlpha_erg_g_s: "L^2 T^-3",
      hydrogenMassFraction: "1",
      heliumMassFraction: "1",
      metallicityMassFraction: "1",
    },
  },
  {
    tag: "STARSIM_FUSION_PROFILE_IMPORT_STAGE2_PREP",
    module: "shared/starsim-fusion-profile-validation.ts",
    stage: "reduced-order",
    notes:
      "Profile validator for shell-integrated nuclear luminosity, channel fractions, fusion-zone radii, closure warnings, and Stage 1 proxy comparison.",
    checks: [{ type: "test", path: "tests/starsim-fusion-profile-validation.spec.ts" }],
    units: {
      integratedNucLuminosity_Lsun: "1",
      surfaceLuminosity_Lsun: "1",
      luminosityClosureRelErr: "1",
      ppFraction: "1",
      cnoFraction: "1",
      tripleAlphaFraction: "1",
      r10_Rstar: "1",
      r50_Rstar: "1",
      r90_Rstar: "1",
      activeVolumeFraction: "1",
      r90Delta: "1",
    },
  },
  {
    tag: "STARSIM_FUSION_PROFILE_IMPORT_STAGE2_PREP",
    module: "shared/starsim-fusion-profile-artifact.ts",
    stage: "reduced-order",
    notes:
      "Artifact contract for StarSim fusion profile validation with safe-language and hSpectralFit guardrails.",
    checks: [{ type: "test", path: "tests/starsim-fusion-profile-artifact.spec.ts" }],
    units: {
      claimIdCount: "1",
      citationCount: "1",
      caveatCount: "1",
      uncertaintyNoteCount: "1",
    },
  },
  {
    tag: "STARSIM_FUSION_BENCHMARK_STAGE2_CANDIDATE",
    module: "shared/starsim-fusion-benchmark-runner.ts",
    stage: "diagnostic",
    notes:
      "Benchmark runner for StarSim fusion profile packs with closure, uncertainty, blockers, and Stage 2 candidate verdicts.",
    motivation:
      "Make profile-grounded StarSim fusion claims auditable through deterministic benchmark reports while preserving proxy-only QST boundaries.",
    conceptualWaypoints: [
      "Compute benchmark verdicts from imported profile validations.",
      "Block Stage 2 candidate readiness without metadata, profile hashes, closure, and uncertainty.",
      "Emit citation-backed reports without direct ER=EPR, propulsion, stress-energy, or CL4 claims.",
    ],
    checks: [
      { type: "test", path: "tests/starsim-fusion-benchmark-runner.spec.ts" },
      { type: "test", path: "tests/starsim-fusion-benchmark-verdict.spec.ts" },
      { type: "stability", path: "tests/starsim-fusion-benchmark-runner.spec.ts" },
      { type: "fixture", path: "tests/fixtures/starsim-fusion-benchmarks/plan.fixture.json" },
      { type: "doc", path: "docs/research/starsim-fusion-benchmark-stage2-candidate.md" },
      { type: "policy", path: "docs/knowledge/math-claims/starsim-fusion-benchmark.claims.json" },
    ],
    units: {
      profileCount: "1",
      passedClosureCount: "1",
      failedClosureCount: "1",
      warningCount: "1",
      channelAgreementRate: "1",
      fusionZoneAgreementRate: "1",
      uncertaintyCoverageRate: "1",
    },
  },
  {
    tag: "STARSIM_FUSION_BENCHMARK_STAGE2_CANDIDATE",
    module: "shared/starsim-fusion-uncertainty.ts",
    stage: "diagnostic",
    notes: "Interval and fixture Monte Carlo uncertainty propagation for benchmark profile outputs.",
    checks: [
      { type: "test", path: "tests/starsim-fusion-uncertainty.spec.ts" },
      { type: "stability", path: "tests/starsim-fusion-uncertainty.spec.ts" },
    ],
    units: {
      samples: "1",
      ppFraction: "1",
      cnoFraction: "1",
      tripleAlphaFraction: "1",
      r90_Rstar: "1",
      activeVolumeFraction: "1",
      luminosityClosureRelErr: "1",
    },
  },
  {
    tag: "STARSIM_FUSION_BENCHMARK_STAGE2_CANDIDATE",
    module: "shared/starsim-fusion-profile-closure.ts",
    stage: "diagnostic",
    notes: "Observable closure checks for StarSim fusion benchmark reports.",
    checks: [
      { type: "test", path: "tests/starsim-fusion-profile-closure.spec.ts" },
      { type: "stability", path: "tests/starsim-fusion-profile-closure.spec.ts" },
    ],
    units: {
      effectiveTemperatureFromLR_K: "Theta",
      surfaceGravityLogg_cgs: "1",
      luminosityClosureRelErr: "1",
    },
  },
  {
    tag: "STARSIM_FUSION_BENCHMARK_STAGE2_CANDIDATE",
    module: "shared/starsim-fusion-benchmark-safe-language.ts",
    stage: "diagnostic",
    notes: "Safe-language renderer for StarSim fusion benchmark reports.",
    checks: [
      { type: "test", path: "tests/starsim-fusion-benchmark-safe-language.spec.ts" },
      { type: "stability", path: "tests/starsim-fusion-benchmark-safe-language.spec.ts" },
    ],
    units: {
      forbiddenPhraseCount: "1",
      claimIdCount: "1",
      citationCount: "1",
    },
  },
  {
    tag: "STARSIM_FUSION_EXTERNAL_REPRO_STAGE2_GATE",
    module: "shared/starsim-fusion-stage2-gate.ts",
    stage: "diagnostic",
    notes:
      "External-reproduction Stage 2 gate for StarSim fusion benchmark reports with MESA/GYRE metadata, solar closure, blockers, and proxy-only boundaries.",
    motivation:
      "Require solver fingerprints and observational closures before treating StarSim fusion profiles as ready for Stage 2 review.",
    conceptualWaypoints: [
      "Require MESA profile, inlist, network, and reaction-rate metadata.",
      "Gate solar neutrino and optional asteroseismic closure without certification.",
      "Block ER=EPR, propulsion, stress-energy, Planck-constant, and CL0-CL4 overclaims.",
    ],
    checks: [
      { type: "test", path: "tests/starsim-fusion-stage2-gate.spec.ts" },
      { type: "stability", path: "tests/starsim-fusion-stage2-gate.spec.ts" },
      { type: "fixture", path: "tests/fixtures/starsim-fusion-stage2-gate/solar-mesa-repro.fixture.json" },
      { type: "doc", path: "docs/research/starsim-fusion-external-repro-stage2-gate.md" },
      { type: "policy", path: "docs/knowledge/math-claims/starsim-fusion-stage2-gate.claims.json" },
    ],
    units: {
      blockerCount: "1",
      claimIdCount: "1",
      citationCount: "1",
      uncertaintyNoteCount: "1",
    },
  },
  {
    tag: "STARSIM_FUSION_EXTERNAL_REPRO_STAGE2_GATE",
    module: "shared/starsim-fusion-neutrino-closure.ts",
    stage: "diagnostic",
    notes: "Solar neutrino residual closure for StarSim fusion Stage 2 gate review.",
    checks: [
      { type: "test", path: "tests/starsim-fusion-neutrino-closure.spec.ts" },
      { type: "stability", path: "tests/starsim-fusion-neutrino-closure.spec.ts" },
    ],
    units: {
      ppFlux: "L^-2 T^-1",
      be7Flux: "L^-2 T^-1",
      pepFlux: "L^-2 T^-1",
      b8Flux: "L^-2 T^-1",
      cnoFlux: "L^-2 T^-1",
      maxRelErr: "1",
    },
  },
  {
    tag: "STARSIM_FUSION_EXTERNAL_REPRO_STAGE2_GATE",
    module: "shared/starsim-fusion-asteroseismic-closure.ts",
    stage: "diagnostic",
    notes: "GYRE-style asteroseismic closure summaries for Stage 2 gate review.",
    checks: [
      { type: "test", path: "tests/starsim-fusion-asteroseismic-closure.spec.ts" },
      { type: "stability", path: "tests/starsim-fusion-asteroseismic-closure.spec.ts" },
    ],
    units: {
      largeSeparation_uHz: "T^-1",
      smallSeparation_uHz: "T^-1",
      modeCount: "1",
      maxFrequencyResidual_uHz: "T^-1",
    },
  },
  {
    tag: "STARSIM_FUSION_EXTERNAL_REPRO_STAGE2_GATE",
    module: "shared/starsim-fusion-stage2-gate-safe-language.ts",
    stage: "diagnostic",
    notes: "Safe-language renderer for Stage 2 gate reports.",
    checks: [
      { type: "test", path: "tests/starsim-fusion-stage2-gate-safe-language.spec.ts" },
      { type: "stability", path: "tests/starsim-fusion-stage2-gate-safe-language.spec.ts" },
    ],
    units: {
      forbiddenPhraseCount: "1",
      claimIdCount: "1",
      citationCount: "1",
    },
  },
  {
    tag: "STARSIM_SOLAR_REFERENCE_REPRO_RUN_V1",
    module: "shared/starsim-solar-reference-run.ts",
    stage: "diagnostic",
    notes:
      "Canonical solar reference reproduction runner that composes fixture/import solver policy, profile validation, benchmark handoff, and Stage 2 gate handoff.",
    motivation:
      "Create the first replayable solar reference artifact that can feed the Stage 2 gate while clearly separating fixture-only and solver-backed evidence.",
    conceptualWaypoints: [
      "Explicit runtime policy prevents silent fixture fallback.",
      "Solar profile validation, benchmark, and Stage 2 gate artifacts are linked.",
      "Safe reports preserve proxy-only QST and no direct ER=EPR boundary.",
    ],
    checks: [
      { type: "test", path: "tests/starsim-solar-reference-run.spec.ts" },
      { type: "stability", path: "tests/starsim-solar-reference-run.spec.ts" },
      { type: "fixture", path: "tests/fixtures/starsim-solar-reference/solar-reference-plan.fixture.json" },
      { type: "doc", path: "docs/research/starsim-solar-reference-repro-run-v1.md" },
      { type: "policy", path: "docs/knowledge/math-claims/starsim-solar-reference-run.claims.json" },
    ],
    units: {
      runCount: "1",
      closureStatusCount: "1",
      claimIdCount: "1",
      citationCount: "1",
    },
  },
  {
    tag: "STARSIM_SOLAR_REFERENCE_REPRO_RUN_V1",
    module: "server/modules/starsim/external/mesa-solar-runner.ts",
    stage: "diagnostic",
    notes: "MESA solar runtime adapter with explicit fixture-only and unavailable external solver behavior.",
    checks: [
      { type: "test", path: "tests/mesa-solar-runner.spec.ts" },
      { type: "stability", path: "tests/mesa-solar-runner.spec.ts" },
    ],
    units: {
      profileHash: "1",
      inlistHash: "1",
      runtimeStatus: "1",
    },
  },
  {
    tag: "STARSIM_SOLAR_REFERENCE_REPRO_RUN_V1",
    module: "server/modules/starsim/external/gyre-summary-import.ts",
    stage: "diagnostic",
    notes: "GYRE summary import helper for optional solar oscillation closure.",
    checks: [
      { type: "test", path: "tests/gyre-summary-import.spec.ts" },
      { type: "stability", path: "tests/gyre-summary-import.spec.ts" },
    ],
    units: {
      largeSeparation_uHz: "T^-1",
      smallSeparation_uHz: "T^-1",
      modeCount: "1",
    },
  },
  {
    tag: "STARSIM_SOLAR_REFERENCE_REPRO_RUN_V1",
    module: "shared/starsim-solar-reference-safe-language.ts",
    stage: "diagnostic",
    notes: "Safe-language renderer for solar reference reproduction reports.",
    checks: [
      { type: "test", path: "tests/starsim-solar-reference-safe-language.spec.ts" },
      { type: "stability", path: "tests/starsim-solar-reference-safe-language.spec.ts" },
    ],
    units: {
      forbiddenPhraseCount: "1",
      claimIdCount: "1",
      citationCount: "1",
    },
  },
  {
    tag: "STARSIM_SOLAR_MESA_DOCKER_REPRO_V1",
    module: "server/modules/starsim/external/mesa-runtime-adapter.ts",
    stage: "diagnostic",
    notes:
      "External/import MESA runtime adapter with strict no-fixture-fallback policy and hash requirements.",
    motivation:
      "Move the solar reference pipeline from fixture-only routing toward auditable MESA output import and eventual solver reproduction.",
    conceptualWaypoints: [
      "Reject fixture_only mode in the MESA repro tool.",
      "Require inlist, profile, history, and run-log hashes for reproduced claims.",
      "Feed parsed MESA output through profile validation, benchmark, and Stage 2 gate contracts.",
    ],
    checks: [
      { type: "test", path: "tests/mesa-runtime-adapter.spec.ts" },
      { type: "stability", path: "tests/mesa-runtime-adapter.spec.ts" },
      { type: "fixture", path: "ops/mesa/solar-reference/mesa-runtime-policy.import-fixture.json" },
      { type: "doc", path: "docs/research/starsim-solar-mesa-docker-repro-v1.md" },
      { type: "policy", path: "docs/knowledge/math-claims/starsim-solar-mesa-repro.claims.json" },
    ],
    units: {
      inlistHash: "1",
      profileHash: "1",
      historyHash: "1",
      runLogHash: "1",
    },
  },
  {
    tag: "STARSIM_SOLAR_MESA_DOCKER_REPRO_V1",
    module: "server/modules/starsim/external/mesa-output-parser.ts",
    stage: "diagnostic",
    notes: "MESA-like profile/history parser for StarSim solar fusion profile imports.",
    checks: [
      { type: "test", path: "tests/mesa-output-parser.spec.ts" },
      { type: "stability", path: "tests/mesa-output-parser.spec.ts" },
    ],
    units: {
      radius_Rstar: "1",
      shellMass_g: "M",
      temperature_K: "Theta",
      density_g_cm3: "M L^-3",
      epsNuc_erg_g_s: "L^2 T^-3",
    },
  },
  {
    tag: "STARSIM_SOLAR_MESA_DOCKER_REPRO_V1",
    module: "shared/starsim-solar-mesa-repro-artifact.ts",
    stage: "diagnostic",
    notes: "Artifact contract for MESA solar reproduction/import reports with QST boundaries.",
    checks: [
      { type: "test", path: "tests/starsim-solar-mesa-repro-artifact.spec.ts" },
      { type: "stability", path: "tests/starsim-solar-mesa-repro-artifact.spec.ts" },
    ],
    units: {
      claimIdCount: "1",
      citationCount: "1",
      caveatCount: "1",
    },
  },
  {
    tag: "STARSIM_SOLAR_MESA_DOCKER_REPRO_V1",
    module: "shared/starsim-solar-mesa-repro-safe-language.ts",
    stage: "diagnostic",
    notes: "Safe-language renderer for MESA solar reproduction/import reports.",
    checks: [
      { type: "test", path: "tests/starsim-solar-mesa-repro-safe-language.spec.ts" },
      { type: "stability", path: "tests/starsim-solar-mesa-repro-safe-language.spec.ts" },
    ],
    units: {
      forbiddenPhraseCount: "1",
      claimIdCount: "1",
      citationCount: "1",
    },
  },
  {
    tag: "STARSIM_ACCORDION_GALACTIC_DYNAMICS_NULL_MODEL_V1",
    module: "shared/starsim-accordion-cosmology-context.ts",
    stage: "diagnostic",
    notes:
      "Observable Universe Accordion cosmology context with bound-system expansion guardrails.",
    motivation:
      "Use Accordion coordinates as cosmological context without turning bound stars or galaxies into local Hubble-flow claims.",
    conceptualWaypoints: [
      "Map redshift to scale factor when present.",
      "Mark galaxies and stellar cores as bound systems that require local dynamics.",
      "Preserve proxy-only QST boundaries.",
    ],
    checks: [
      { type: "test", path: "tests/starsim-accordion-cosmology-context.spec.ts" },
      { type: "stability", path: "tests/starsim-accordion-cosmology-context.spec.ts" },
      { type: "doc", path: "docs/research/starsim-accordion-galactic-dynamics-null-model-v1.md" },
      { type: "policy", path: "docs/knowledge/math-claims/starsim-accordion-galactic-dynamics.claims.json" },
    ],
    units: {
      redshift: "1",
      scaleFactor: "1",
      cosmicTime_Gyr: "T",
      lookbackTime_Gyr: "T",
      comovingDistance_Mpc: "L",
      properDistance_Mpc: "L",
    },
  },
  {
    tag: "STARSIM_ACCORDION_GALACTIC_DYNAMICS_NULL_MODEL_V1",
    module: "shared/starsim-galactic-rotation-controls.ts",
    stage: "diagnostic",
    notes:
      "Galactic rotation null controls for baryonic, dark-matter, MOND, and SPARC-like reference comparisons.",
    checks: [
      { type: "test", path: "tests/starsim-galactic-rotation-controls.spec.ts" },
      { type: "stability", path: "tests/starsim-galactic-rotation-controls.spec.ts" },
      { type: "fixture", path: "tests/fixtures/starsim-accordion/sparc-rotation-curve.fixture.json" },
      { type: "policy", path: "docs/knowledge/math-claims/starsim-accordion-galactic-dynamics.claims.json" },
    ],
    units: {
      radius_kpc: "L",
      observedVelocity_km_s: "L T^-1",
      modelVelocity_km_s: "L T^-1",
      baryonicVelocity_km_s: "L T^-1",
      residual_km_s: "L T^-1",
      rmsResidual_km_s: "L T^-1",
    },
  },
  {
    tag: "STARSIM_ACCORDION_GALACTIC_DYNAMICS_NULL_MODEL_V1",
    module: "shared/starsim-accordion-galactic-null-model.ts",
    stage: "diagnostic",
    notes:
      "Composes Accordion context, StarSim star nodes, fusion priors, rotation controls, and proxy-only QST annotations into a null-model report.",
    checks: [
      { type: "test", path: "tests/starsim-accordion-galactic-null-model.spec.ts" },
      { type: "stability", path: "tests/starsim-accordion-galactic-null-model.spec.ts" },
      { type: "fixture", path: "tests/fixtures/starsim-accordion/accordion-local-volume.fixture.json" },
      { type: "doc", path: "docs/research/starsim-accordion-galactic-dynamics-null-model-v1.md" },
    ],
    units: {
      nodeCount: "1",
      localDensityContrast: "1",
      velocityDispersion_km_s: "L T^-1",
      clusteringEntropy_nats: "1",
      streamCoherence: "1",
      erDensityProxy: "1",
    },
  },
  {
    tag: "STARSIM_ACCORDION_GALACTIC_DYNAMICS_NULL_MODEL_V1",
    module: "shared/starsim-galactic-dynamics-safe-language.ts",
    stage: "diagnostic",
    notes:
      "Safe-language renderer blocking direct ER=EPR, wormhole, propulsion, stress-energy, hydrostatic-rotation, and CL4 overclaims.",
    checks: [
      { type: "test", path: "tests/starsim-galactic-dynamics-safe-language.spec.ts" },
      { type: "test", path: "tests/starsim-galactic-dynamics-artifact.spec.ts" },
      { type: "stability", path: "tests/starsim-galactic-dynamics-safe-language.spec.ts" },
    ],
    units: {
      forbiddenPhraseCount: "1",
      claimIdCount: "1",
      citationCount: "1",
      uncertaintyNoteCount: "1",
    },
  },
  {
    tag: "ER_EPR_TINY_SYK_EXACT_DIAG_V1",
    module: "shared/er-epr-majorana-operators.ts",
    stage: "diagnostic",
    notes: "Tiny Clifford/Majorana operator construction for the Stage 1 SYK-like toy solver.",
    checks: [
      { type: "test", path: "tests/er-epr-majorana-operators.spec.ts" },
      { type: "stability", path: "tests/er-epr-majorana-operators.spec.ts" },
      { type: "doc", path: "docs/research/er-epr-tiny-syk-exact-diag-v1.md" },
      { type: "policy", path: "docs/knowledge/math-claims/er-epr-tiny-syk.claims.json" },
    ],
    units: {
      nMajoranas: "1",
      dimension: "1",
      maxDiagonalError: "1",
      maxOffDiagonalError: "1",
    },
  },
  {
    tag: "ER_EPR_TINY_SYK_EXACT_DIAG_V1",
    module: "shared/er-epr-tiny-syk-hamiltonian.ts",
    stage: "diagnostic",
    notes: "Seeded q=4 tiny SYK-like Hamiltonian and double-trace-like two-sided coupling builder.",
    checks: [
      { type: "test", path: "tests/er-epr-tiny-syk-hamiltonian.spec.ts" },
      { type: "stability", path: "tests/er-epr-tiny-syk-hamiltonian.spec.ts" },
      { type: "fixture", path: "tests/fixtures/er-epr-tiny-syk/tiny-syk-plan.fixture.json" },
    ],
    units: {
      seed: "1",
      mu: "1",
      hamiltonianHash: "1",
      nonCommutativityIndex: "1",
    },
  },
  {
    tag: "ER_EPR_TINY_SYK_EXACT_DIAG_V1",
    module: "shared/er-epr-tiny-syk.ts",
    stage: "diagnostic",
    notes: "Tiny two-sided SYK-like solver backend that emits raw telemetry through the existing solver adapter.",
    motivation:
      "Move ER_EPR_STAGE1 from fixture-only raw scores toward repo-local toy-solver telemetry while preserving model-internal and proxy-only boundaries.",
    conceptualWaypoints: [
      "Generate seeded Hamiltonian and raw telemetry.",
      "Normalize telemetry through ER_EPR_STAGE1_SOLVER_ADAPTER_V1.",
      "Record hashes, controls, citations, uncertainty notes, and non-promotion caveats.",
    ],
    checks: [
      { type: "test", path: "tests/er-epr-tiny-syk-telemetry.spec.ts" },
      { type: "test", path: "tests/er-epr-tiny-syk-evolution.spec.ts" },
      { type: "stability", path: "tests/er-epr-tiny-syk-telemetry.spec.ts" },
      { type: "doc", path: "docs/research/er-epr-tiny-syk-exact-diag-v1.md" },
      { type: "policy", path: "docs/knowledge/math-claims/er-epr-tiny-syk.claims.json" },
    ],
    units: {
      teleportationFidelityRaw: "1",
      entanglementEntropy_nats: "1",
      leftRightMutualInformation: "1",
      timeDelayEstimate: "T",
      operatorSize: "1",
    },
  },
  {
    tag: "ER_EPR_TINY_SYK_EXACT_DIAG_V1",
    module: "shared/er-epr-tiny-syk-safe-language.ts",
    stage: "diagnostic",
    notes: "Safe-language renderer for tiny SYK reports, blocking real-universe, NHM2, stress-energy, and CL4 overclaims.",
    checks: [
      { type: "test", path: "tests/er-epr-tiny-syk-safe-language.spec.ts" },
      { type: "test", path: "tests/er-epr-tiny-syk-artifact.spec.ts" },
      { type: "stability", path: "tests/er-epr-tiny-syk-safe-language.spec.ts" },
    ],
    units: {
      forbiddenPhraseCount: "1",
      claimIdCount: "1",
      citationCount: "1",
      uncertaintyNoteCount: "1",
    },
  },
  {
    tag: "ER_EPR_TINY_SYK_VALIDATION_SWEEP_V1",
    module: "shared/er-epr-tiny-syk-validation-sweep.ts",
    stage: "diagnostic",
    notes: "Validation sweep aggregating seeded tiny SYK-like runs, required controls, numerical honesty, and entropy washout.",
    motivation:
      "Require repeatability across a declared ensemble before any model-internal ER=EPR-like support language is allowed.",
    conceptualWaypoints: [
      "Expand seeds and toy-model parameters into candidate runs.",
      "Aggregate required control leakage and diagnostic blockers.",
      "Require monotonic QST entropy-stretch demotion.",
    ],
    checks: [
      { type: "test", path: "tests/er-epr-tiny-syk-validation-sweep.spec.ts" },
      { type: "stability", path: "tests/er-epr-tiny-syk-validation-sweep.spec.ts" },
      { type: "fixture", path: "tests/fixtures/er-epr-tiny-syk-validation/sweep-plan.fixture.json" },
      { type: "doc", path: "docs/research/er-epr-tiny-syk-validation-sweep-v1.md" },
      { type: "policy", path: "docs/knowledge/math-claims/er-epr-tiny-syk-validation.claims.json" },
    ],
    units: {
      totalCandidateRuns: "1",
      candidatePassRate: "1",
      controlLeakageCount: "1",
      entropyWashoutPassCount: "1",
    },
  },
  {
    tag: "ER_EPR_TINY_SYK_VALIDATION_SWEEP_V1",
    module: "shared/er-epr-tiny-syk-convergence.ts",
    stage: "diagnostic",
    notes: "Numerical-method honesty checks for tiny SYK validation sweeps.",
    checks: [
      { type: "test", path: "tests/er-epr-tiny-syk-convergence.spec.ts" },
      { type: "stability", path: "tests/er-epr-tiny-syk-convergence.spec.ts" },
    ],
    units: {
      numericalTolerance: "1",
      maxObservedDelta: "1",
      methodCount: "1",
    },
  },
  {
    tag: "ER_EPR_TINY_SYK_VALIDATION_SWEEP_V1",
    module: "shared/er-epr-tiny-syk-control-aggregate.ts",
    stage: "diagnostic",
    notes: "Required-control aggregation for wrong-sign, no-coupling, disentangled, shuffled, random-matrix, and spin-chain controls.",
    checks: [
      { type: "test", path: "tests/er-epr-tiny-syk-control-aggregate.spec.ts" },
      { type: "stability", path: "tests/er-epr-tiny-syk-control-aggregate.spec.ts" },
    ],
    units: {
      controlLeakageMax: "1",
      leakageCount: "1",
      missingRequiredControlCount: "1",
    },
  },
  {
    tag: "ER_EPR_TINY_SYK_VALIDATION_SWEEP_V1",
    module: "shared/er-epr-tiny-syk-validation-safe-language.ts",
    stage: "diagnostic",
    notes: "Safe-language renderer for tiny SYK validation reports, blocking real-universe, NHM2, stress-energy, exact-label, and CL4 overclaims.",
    checks: [
      { type: "test", path: "tests/er-epr-tiny-syk-validation-safe-language.spec.ts" },
      { type: "test", path: "tests/er-epr-tiny-syk-validation-artifact.spec.ts" },
      { type: "stability", path: "tests/er-epr-tiny-syk-validation-safe-language.spec.ts" },
    ],
    units: {
      forbiddenPhraseCount: "1",
      claimIdCount: "1",
      citationCount: "1",
      uncertaintyNoteCount: "1",
    },
  },
  {
    tag: "DP_COLLAPSE",
    module: "shared/dp-collapse.ts",
    stage: "exploratory",
    notes: "Diosi-Penrose collapse estimator (DeltaE from mass-density difference).",
    checks: [{ type: "test", path: "tests/dp-collapse.spec.ts" }],
    units: {
      ell_m: "L",
      r_c_m: "L",
      deltaE_J: "M L^2 T^-2",
      tau_s: "T",
      tau_ms: "T",
      mass_a_kg: "M",
      mass_b_kg: "M",
      overlap_mass_kg: "M",
    },
  },
  {
    tag: "DP_COLLAPSE",
    module: "server/services/dp-adapters.ts",
    stage: "exploratory",
    notes: "Adapters from stress-energy fields to DP mass-density grids.",
    checks: [{ type: "test", path: "tests/dp-adapters.spec.ts" }],
    units: {
      rho_kg_m3: "M L^-3",
      energy_density: "M L^-1 T^-2",
    },
  },
  {
    tag: "DP_COLLAPSE",
    module: "server/services/dp-adapter-build.ts",
    stage: "exploratory",
    notes: "Build DP adapter inputs from stress-energy and GR evolve bricks.",
    checks: [{ type: "test", path: "tests/collapse-benchmark.phase2.routes.spec.ts" }],
    units: {
      ell_m: "L",
      rho_kg_m3: "M L^-3",
      energy_density: "M L^-1 T^-2",
    },
  },
  {
    tag: "DP_COLLAPSE",
    module: "shared/dp-planner.ts",
    stage: "exploratory",
    notes: "DP planning calculator schema (visibility, detectability, tau).",
    checks: [{ type: "test", path: "tests/dp-planner.spec.ts" }],
    units: {
      gamma_dp_s: "T^-1",
      tau_s: "T",
      tau_ms: "T",
      deltaE_J: "M L^2 T^-2",
    },
  },
  {
    tag: "DP_COLLAPSE",
    module: "server/services/dp-planner.ts",
    stage: "exploratory",
    notes: "DP planning calculator (visibility decay, detectability ratio).",
    checks: [{ type: "test", path: "tests/dp-planner.spec.ts" }],
    units: {
      gamma_dp_s: "T^-1",
      tau_s: "T",
      tau_ms: "T",
      deltaE_J: "M L^2 T^-2",
    },
  },
  {
    tag: "PROOF_MATH",
    module: "shared/curvature-proxy.ts",
    stage: "reduced-order",
    notes: "Curvature proxy helpers shared by proof pack and UI.",
    checks: [{ type: "test", path: "tests/proof-pack.spec.ts" }],
    units: {
      kappa_drive: "L^-2",
      kappa_body: "L^-2",
      kappa_u: "L^-2",
    },
  },
  {
    tag: "PROOF_MATH",
    module: "client/src/physics/curvature.ts",
    stage: "reduced-order",
    notes: "Client curvature proxy helpers for proof displays.",
    checks: [{ type: "test", path: "tests/proof-pack.spec.ts" }],
    units: {
      kappaDrive: "L^-2",
      kappaDriveFromPower: "L^-2",
      kappaBody: "L^-2",
      potatoEfficiency: "1",
    },
  },
  {
    tag: "PROOF_MATH",
    module: "client/src/lib/warp-proof-math.ts",
    stage: "reduced-order",
    notes: "Warp proof helper math (guards + proxy conversions).",
    checks: [{ type: "test", path: "tests/proof-pack.spec.ts" }],
    units: {
      casimirPressure_Pa: "M L^-1 T^-2",
      electrostaticPressure_Pa: "M L^-1 T^-2",
      restoringPressure_Pa: "M L^-1 T^-2",
      margin_Pa: "M L^-1 T^-2",
      maxStroke_pm: "L",
      kappaDriveProxy: "L^-2",
    },
  },
  {
    tag: "PROOF_MATH",
    module: "server/helix-proof-pack.ts",
    stage: "reduced-order",
    notes: "Proof pack builder for pipeline-derived proof metrics.",
    checks: [{ type: "test", path: "tests/proof-pack.spec.ts" }],
    units: {
      power_avg_W: "M L^2 T^-3",
      power_avg_MW: "M L^2 T^-3",
      duty_effective: "1",
      hull_area_m2: "L^2",
      tile_area_m2: "L^2",
      tile_count: "1",
      kappa_drive: "L^-2",
      M_exotic_kg: "M",
      U_static_J: "M L^2 T^-2",
      TS_ratio: "1",
      zeta: "1",
    },
  },
  {
    tag: "HALOBANK_SOLAR",
    module: "server/modules/halobank-solar/time-core.ts",
    stage: "reduced-order",
    notes: "Deterministic UTC/TAI/TT/TCG/TDB/TCB conversion core for HaloBank solar proofs.",
    checks: [{ type: "test", path: "tests/halobank-solar-routes.spec.ts" }],
    units: {
      tai_minus_utc_s: "T",
      tt_minus_utc_s: "T",
      tdb_minus_tt_s: "T",
      tcb_minus_tdb_s: "T",
      tcg_minus_tt_s: "T",
    },
  },
  {
    tag: "HALOBANK_SOLAR",
    module: "server/modules/halobank-solar/ephemeris-core.ts",
    stage: "diagnostic",
    notes: "Deterministic vector state core with BCRS/GCRS framing, observer handling, and compatibility exports.",
    checks: [
      { type: "test", path: "tests/halobank-solar-routes.spec.ts" },
      { type: "snapshot", path: "tests/halobank-solar-routes.spec.ts" },
    ],
    units: {
      pos_AU: "L",
      vel_AU_per_day: "L T^-1",
      light_time_s: "T",
      ra_deg: "1",
      dec_deg: "1",
    },
  },
  {
    tag: "HALOBANK_SOLAR",
    module: "server/modules/halobank-solar/derived.ts",
    stage: "diagnostic",
    notes: "Derived proof modules for Mercury precession, eclipse timing, and resonance-libration gates.",
    checks: [
      { type: "test", path: "tests/halobank-solar-derived.spec.ts" },
      { type: "snapshot", path: "tests/halobank-solar-derived.spec.ts" },
    ],
    units: {
      mercury_arcsec_per_century: "1",
      eclipse_contact_gap_deg: "1",
      resonance_theta_span_deg: "1",
      resonance_ratio_error: "1",
    },
  },
  {
    tag: "HALOBANK_SOLAR",
    module: "server/routes/halobank-solar.ts",
    stage: "diagnostic",
    notes: "API contracts for vectors and derived proof modules with deterministic provenance/fail-id gate semantics.",
    checks: [
      { type: "test", path: "tests/halobank-solar-routes.spec.ts" },
      { type: "test", path: "tests/halobank-solar-derived.spec.ts" },
      { type: "snapshot", path: "tests/halobank-solar-routes.spec.ts" },
    ],
    units: {
      gate_delta_value: "varies",
      gate_delta_limit: "varies",
    },
  },
];
