import fs from "node:fs";
import path from "node:path";

import { buildHelixPublicUiControlInventory } from "./lib/helix-public-ui-control-inventory";

const repoRoot = path.resolve(process.cwd());
const outputPath = path.join(repoRoot, "shared/helix-public-ui-control-catalog.generated.ts");
const inventory = buildHelixPublicUiControlInventory(repoRoot);
const rows = inventory.map((entry) => ({
  control_id: entry.locator,
  surface_id: entry.surface_id,
  account_scope: entry.account_scope,
  interaction_kind: entry.interaction_kind,
  authority_state: entry.authority_state,
  ...(entry.capability_id ? { capability_id: entry.capability_id } : {}),
  ...(entry.route_contract_id ? { route_contract_id: entry.route_contract_id } : {}),
}));

const generated = [
  "// Generated by scripts/generate-helix-public-ui-control-catalog.ts. Do not edit manually.",
  "import type { HelixPublicUiControlCatalogEntry } from \"./helix-public-ui-affordance\";",
  "",
  "export const HELIX_PUBLIC_UI_CONTROL_CATALOG = ",
  `${JSON.stringify(rows, null, 2)} as const satisfies readonly HelixPublicUiControlCatalogEntry[];`,
  "",
].join("\n");

const write = process.argv.includes("--write");
const current = fs.existsSync(outputPath) ? fs.readFileSync(outputPath, "utf8") : null;
const matches = current === generated;

if (write && !matches) fs.writeFileSync(outputPath, generated, "utf8");

process.stdout.write(`${JSON.stringify({
  schema: "helix.public_ui_control_catalog_generation.v1",
  mode: write ? "write" : "check",
  control_count: rows.length,
  output_path: path.relative(repoRoot, outputPath).split(path.sep).join("/"),
  changed: !matches,
  safe_field_names: [
    "control_id",
    "surface_id",
    "account_scope",
    "interaction_kind",
    "authority_state",
    "capability_id",
    "route_contract_id",
  ],
}, null, 2)}\n`);

if (!write && !matches) process.exitCode = 1;
