import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

type AnchorPair = {
  machine: string;
  human: string;
};

type DefaultAnchors = {
  integrity_parity: AnchorPair;
  reference_capsule: AnchorPair;
  promotion_readiness: AnchorPair;
  external_comparison_matrix: AnchorPair;
};

type GeometryProofPaths = {
  scripts: string[];
  snapshots: string[];
};

type Posture = {
  reference_only: boolean;
  canonical_blocking: boolean;
};

type UsageRule = {
  top_level_anchor_required: boolean;
  top_level_anchor_path_md: string;
  top_level_anchor_path_json: string;
  claim_specific_paths_required: boolean;
  missing_artifact_behavior: string;
};

type ProofAnchorIndex = {
  artifact_type: string;
  generator_version: string;
  alias: string;
  posture: Posture;
  boundary_statement: string;
  canonical_authority_chain: string[];
  default_state_of_record_anchors: DefaultAnchors;
  needle_hull_mark2_paper_inputs: string[];
  geometry_gr_observable_proof_paths: GeometryProofPaths;
  warp_family_method_track_proof_paths: string[];
  evidence_lane_proof_paths: string[];
  metrology_equation_provenance_paths: string[];
  sem_ellipsometry_specific_closure_paths: string[];
  deterministic_regeneration_commands: string[];
  paper_generation_usage_rule: UsageRule;
};

const DEFAULT_SOURCE = path.join('configs', 'warp-needle-hull-mark2-proof-anchor-index.v1.json');
const DEFAULT_OUT_JSON = path.join('docs', 'audits', 'research', 'warp-needle-hull-mark2-proof-anchor-index-latest.json');
const DEFAULT_OUT_MD = path.join('docs', 'audits', 'research', 'warp-needle-hull-mark2-proof-anchor-index-latest.md');

const readArgValue = (name: string, argv = process.argv.slice(2)): string | undefined => {
  const idx = argv.findIndex((item) => item === name || item.startsWith(`${name}=`));
  if (idx < 0) return undefined;
  if (argv[idx].includes('=')) return argv[idx].split('=', 2)[1];
  return argv[idx + 1];
};

const normalizePath = (filePath: string): string => filePath.replace(/\\/g, '/');

const ensureDirForFile = (filePath: string): void => {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
};

const readJson = <T>(filePath: string): T =>
  JSON.parse(fs.readFileSync(filePath, 'utf8')) as T;

const assert = (condition: unknown, message: string): void => {
  if (!condition) {
    throw new Error(message);
  }
};

const validateSource = (source: ProofAnchorIndex): void => {
  assert(source.artifact_type === 'needle_hull_mark2_proof_anchor_index/v1', 'artifact_type must be needle_hull_mark2_proof_anchor_index/v1');
  assert(typeof source.boundary_statement === 'string' && source.boundary_statement.length > 0, 'boundary_statement is required');
  assert(Array.isArray(source.canonical_authority_chain) && source.canonical_authority_chain.length > 0, 'canonical_authority_chain is required');
  assert(Array.isArray(source.needle_hull_mark2_paper_inputs) && source.needle_hull_mark2_paper_inputs.length > 0, 'needle_hull_mark2_paper_inputs is required');
  assert(Array.isArray(source.deterministic_regeneration_commands) && source.deterministic_regeneration_commands.length > 0, 'deterministic_regeneration_commands is required');
  assert(typeof source.paper_generation_usage_rule?.top_level_anchor_path_md === 'string', 'paper_generation_usage_rule.top_level_anchor_path_md is required');
  assert(typeof source.paper_generation_usage_rule?.top_level_anchor_path_json === 'string', 'paper_generation_usage_rule.top_level_anchor_path_json is required');
};

const renderBulletPaths = (paths: string[]): string =>
  paths.map((item) => `- \`${normalizePath(item)}\``).join('\n');

const renderNumberedPaths = (paths: string[]): string =>
  paths.map((item, index) => `${index + 1}. \`${normalizePath(item)}\``).join('\n');

const renderDefaultAnchors = (anchors: DefaultAnchors): string => {
  const lines: string[] = [];
  for (const [key, value] of Object.entries(anchors)) {
    lines.push(`- ${key} (machine): \`${normalizePath(value.machine)}\``);
    lines.push(`- ${key} (human): \`${normalizePath(value.human)}\``);
  }
  return lines.join('\n');
};

const renderMarkdown = (payload: ProofAnchorIndex, sourcePath: string): string => {
  const usage = payload.paper_generation_usage_rule;
  return `# Needle Hull Mark 2 Proof Anchor Index (${payload.alias === 'latest' ? 'Latest' : payload.alias})

"${payload.boundary_statement}"

Generated by:
- \`npm run warp:proof-index:sync\`
- source-of-truth: \`${normalizePath(sourcePath)}\`

## Purpose
Use this index as the default citation map for Needle Hull Mark 2 paper generation. It centralizes commit-tracked paths for end-to-end proof traceability.

Machine-readable companion:
- \`${normalizePath(usage.top_level_anchor_path_json)}\`

## Canonical Authority Chain
${renderNumberedPaths(payload.canonical_authority_chain)}

## Default State-of-Record Anchors
${renderDefaultAnchors(payload.default_state_of_record_anchors)}

## Needle Hull Mark 2 Paper Inputs
${renderBulletPaths(payload.needle_hull_mark2_paper_inputs)}

## Geometry + GR Observable Proof Paths
- Geometry/observable scripts:
${renderBulletPaths(payload.geometry_gr_observable_proof_paths.scripts)}
- GR snapshots:
${renderBulletPaths(payload.geometry_gr_observable_proof_paths.snapshots)}

## Warp-Family Method-Track Proof Paths
${renderBulletPaths(payload.warp_family_method_track_proof_paths)}

## Evidence-Lane Proof Paths
${renderBulletPaths(payload.evidence_lane_proof_paths)}

## Metrology + Equation Provenance Paths
${renderBulletPaths(payload.metrology_equation_provenance_paths)}

## SEM+Ellipsometry Specific Closure Paths
${renderBulletPaths(payload.sem_ellipsometry_specific_closure_paths)}

## Deterministic Regeneration Commands
${renderNumberedPaths(payload.deterministic_regeneration_commands)}

## Usage Rule for Paper Generation
- top_level_anchor_required: \`${String(usage.top_level_anchor_required)}\`
- top_level_anchor_path_md: \`${normalizePath(usage.top_level_anchor_path_md)}\`
- top_level_anchor_path_json: \`${normalizePath(usage.top_level_anchor_path_json)}\`
- claim_specific_paths_required: \`${String(usage.claim_specific_paths_required)}\`
- missing_artifact_behavior: \`${usage.missing_artifact_behavior}\`
`;
};

export const syncNeedleHullProofAnchorIndex = (options: {
  sourcePath?: string;
  outJsonPath?: string;
  outMdPath?: string;
}) => {
  const sourcePath = options.sourcePath ?? DEFAULT_SOURCE;
  const outJsonPath = options.outJsonPath ?? DEFAULT_OUT_JSON;
  const outMdPath = options.outMdPath ?? DEFAULT_OUT_MD;

  const source = readJson<ProofAnchorIndex>(sourcePath);
  validateSource(source);

  const jsonOut: ProofAnchorIndex = JSON.parse(JSON.stringify(source)) as ProofAnchorIndex;

  ensureDirForFile(outJsonPath);
  ensureDirForFile(outMdPath);
  fs.writeFileSync(outJsonPath, `${JSON.stringify(jsonOut, null, 2)}\n`, 'utf8');
  fs.writeFileSync(outMdPath, renderMarkdown(jsonOut, sourcePath), 'utf8');

  return {
    sourcePath: normalizePath(sourcePath),
    outJsonPath: normalizePath(outJsonPath),
    outMdPath: normalizePath(outMdPath),
  };
};

if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href) {
  const sourcePath = readArgValue('--source');
  const outJsonPath = readArgValue('--out-json');
  const outMdPath = readArgValue('--out-md');
  const result = syncNeedleHullProofAnchorIndex({ sourcePath, outJsonPath, outMdPath });
  console.log(JSON.stringify(result, null, 2));
}
