export type HelixAskG0AuthorityOwner =
  | "external_codex_runtime"
  | "runtime_codex"
  | "helix_policy"
  | "helix_legacy_runtime"
  | "helix_adapter"
  | "helix_terminal_authority"
  | "client_legacy_bridge"
  | "client_presentation";

export type HelixAskG0RuntimeClass =
  | "authenticated_mcp"
  | "codex_native_app_server"
  | "codex_exec_compatibility"
  | "helix_monolith"
  | "future_provider_stub"
  | "client_transport"
  | "client_execution_shortcut"
  | "presentation_only";

export type HelixAskG0Disposition =
  | "retain"
  | "replace"
  | "quarantine"
  | "remove_after_parity";

export type HelixAskG0AuthorityInventoryEntry = {
  id: string;
  surface: "northbound" | "client" | "server" | "provider" | "terminal" | "presentation";
  entryPoint: string;
  activationPredicate: string;
  lifecycleStages: string[];
  authorityOwner: HelixAskG0AuthorityOwner;
  runtimeClass: HelixAskG0RuntimeClass;
  authoritativeSource: string;
  terminalWriter: string | null;
  limits: string[];
  currentClosureState: "inventoried";
  disposition: HelixAskG0Disposition;
  downstreamGate: "G1" | "G2" | "G4" | "G5" | "G6";
  sourceFile: string;
  sourceAnchors: string[];
};

export const HELIX_ASK_G0_AUTHORITY_INVENTORY = [
  {
    id: "northbound.authenticated_mcp",
    surface: "northbound",
    entryPoint: "app.use(\"/mcp\", createHelixMcpRouter())",
    activationPredicate: "An authenticated external Codex client calls the Helix MCP surface with admitted scopes.",
    lifecycleStages: ["source admission", "tool admission", "execution", "evidence normalization"],
    authorityOwner: "external_codex_runtime",
    runtimeClass: "authenticated_mcp",
    authoritativeSource: "The external Codex task owns its turn; Helix owns MCP identity, admission, execution receipts, and evidence identity.",
    terminalWriter: null,
    limits: ["Client-session and MCP authorization limits are external to the Helix Ask turn."],
    currentClosureState: "inventoried",
    disposition: "retain",
    downstreamGate: "G2",
    sourceFile: "server/index.ts",
    sourceAnchors: ["app.use(\"/mcp\", createHelixMcpRouter())"],
  },
  {
    id: "client.console_default_legacy_bridge",
    surface: "client",
    entryPoint: "HelixAskConsoleRuntimeShell",
    activationPredicate: "runtimeImplementation is omitted or equals legacy_bridge; this is the current default.",
    lifecycleStages: ["presentation", "client transport", "client shortcuts"],
    authorityOwner: "client_legacy_bridge",
    runtimeClass: "client_transport",
    authoritativeSource: "HelixAskPill local state plus backend response projections.",
    terminalWriter: "resolveHelixAskVisibleTerminal / selectHelixAskVisibleFinalAnswer",
    limits: ["Default remains legacy_bridge.", "Bridge replacement is not accepted."],
    currentClosureState: "inventoried",
    disposition: "remove_after_parity",
    downstreamGate: "G6",
    sourceFile: "client/src/components/helix/ask-console/HelixAskConsoleRuntimeShell.tsx",
    sourceAnchors: ["runtimeImplementation = \"legacy_bridge\"", "<HelixAskLegacyRuntimeBridge"],
  },
  {
    id: "client.console_minimal_runtime_opt_in",
    surface: "client",
    entryPoint: "HelixAskMinimalRuntimeShell",
    activationPredicate: "A caller explicitly sets runtimeImplementation to minimal_runtime_shell.",
    lifecycleStages: ["presentation", "client transport"],
    authorityOwner: "client_presentation",
    runtimeClass: "client_transport",
    authoritativeSource: "Injected minimal runtime transport and the backend turn response.",
    terminalWriter: "minimal runtime visible-surface projection",
    limits: ["Not the default implementation."],
    currentClosureState: "inventoried",
    disposition: "retain",
    downstreamGate: "G6",
    sourceFile: "client/src/components/helix/ask-console/HelixAskConsoleRuntimeShell.tsx",
    sourceAnchors: ["runtimeImplementation === \"minimal_runtime_shell\"", "<HelixAskMinimalRuntimeShell"],
  },
  {
    id: "client.turn_stream_primary",
    surface: "client",
    entryPoint: "runAskTurnStream",
    activationPredicate: "The manual canary is enabled by default or the prompt requires the backend Ask entrypoint.",
    lifecycleStages: ["request", "presentation"],
    authorityOwner: "client_legacy_bridge",
    runtimeClass: "client_transport",
    authoritativeSource: "SSE turn_transcript_event packets and the final turn_final payload.",
    terminalWriter: "Backend terminal authority; client projects the final payload.",
    limits: ["Client watchdog defaults to 45 seconds and is clamped to 5-180 seconds.", "Stream failure enters JSON transport fallback."],
    currentClosureState: "inventoried",
    disposition: "retain",
    downstreamGate: "G1",
    sourceFile: "client/src/components/helix/HelixAskPill.tsx",
    sourceAnchors: ["localResponse = await runAskTurnStream", "backendAskCallPath = \"runAskTurnStream\""],
  },
  {
    id: "client.turn_json_transport_fallback",
    surface: "client",
    entryPoint: "runAskTurn",
    activationPredicate: "runAskTurnStream throws or returns a retryable model-only final failure.",
    lifecycleStages: ["request", "presentation"],
    authorityOwner: "client_legacy_bridge",
    runtimeClass: "client_transport",
    authoritativeSource: "POST /api/agi/ask/turn response; stream error is copied into debug.stream_fallback_reason.",
    terminalWriter: "Backend terminal authority; client projects the JSON response.",
    limits: ["Fallback is transport-level, but G1 must prove the turn ID prevents duplicate execution."],
    currentClosureState: "inventoried",
    disposition: "quarantine",
    downstreamGate: "G1",
    sourceFile: "client/src/components/helix/HelixAskPill.tsx",
    sourceAnchors: ["backendAskCallPath = \"runAskTurn\"", "stream_fallback_reason: backendAskCallError"],
  },
  {
    id: "client.ask_local_router",
    surface: "client",
    entryPoint: "askLocal / askLocalDirect",
    activationPredicate: "The legacy bridge does not select the backend stream path, or another caller invokes askLocal. Lane parity defaults to true and normally routes direct to /ask/turn; disabling it admits jobs and /ask.",
    lifecycleStages: ["request", "client retry"],
    authorityOwner: "client_legacy_bridge",
    runtimeClass: "client_transport",
    authoritativeSource: "bodyRequiresAskTurnEntrypoint and __HELIX_E8_14_LANE_PARITY__ choose the backend route.",
    terminalWriter: "Selected backend route.",
    limits: ["Jobs poll every 1 second.", "Job timeout defaults to 20 minutes, clamped to 30 seconds-30 minutes."],
    currentClosureState: "inventoried",
    disposition: "replace",
    downstreamGate: "G6",
    sourceFile: "client/src/lib/agi/api.ts",
    sourceAnchors: ["const askLocalDirect = async", "export async function askLocal", "__HELIX_E8_14_LANE_PARITY__"],
  },
  {
    id: "client.multilang_and_scope_retry",
    surface: "client",
    entryPoint: "askLocalWithPreflightScopeFallback",
    activationPredicate: "askLocal returns a multilang confidence gate or throws an AGI-bot preflight-scope error.",
    lifecycleStages: ["client retry", "source admission"],
    authorityOwner: "client_legacy_bridge",
    runtimeClass: "client_transport",
    authoritativeSource: "Client retries with multilangConfirm or removes mode/tool/evidence/verify scope fields.",
    terminalWriter: "Selected backend route after retry.",
    limits: ["At most one multilang-confirm retry and one scope-downgrade retry per wrapper call."],
    currentClosureState: "inventoried",
    disposition: "quarantine",
    downstreamGate: "G1",
    sourceFile: "client/src/components/helix/HelixAskPill.tsx",
    sourceAnchors: ["askLocalWithMultilangFailOpenFallback", "askLocalWithPreflightScopeFallback", "delete retryOptions.mode"],
  },
  {
    id: "client.workstation_execution_fast_path",
    surface: "client",
    entryPoint: "dispatchWorkstationActionSequence",
    activationPredicate: "Manual canary is disabled, the prompt is not backend-forced, and deterministic/parser/classifier logic selects a workstation command.",
    lifecycleStages: ["intent arbitration", "execution", "presentation"],
    authorityOwner: "client_legacy_bridge",
    runtimeClass: "client_execution_shortcut",
    authoritativeSource: "Client parser/classifier and workstation dispatcher, not the completed backend solver path.",
    terminalWriter: "getWorkstationFastPathReplyText when reasoning is not required.",
    limits: ["Reachable only through feature/config predicates; currently suppressed by the default manual canary for ordinary manual turns."],
    currentClosureState: "inventoried",
    disposition: "remove_after_parity",
    downstreamGate: "G6",
    sourceFile: "client/src/components/helix/HelixAskPill.tsx",
    sourceAnchors: ["dispatchWorkstationActionSequence", "getWorkstationFastPathReplyText", "HELIX_E6_ASK_TURN_MANUAL_CANARY_FLAG"],
  },
  {
    id: "client.process_graph_answer_shortcut",
    surface: "client",
    entryPoint: "shouldUseProcessGraphContextPack",
    activationPredicate: "The prompt matches the process-graph overview policy and backend dispatch is not forced.",
    lifecycleStages: ["intent arbitration", "presentation"],
    authorityOwner: "client_legacy_bridge",
    runtimeClass: "client_execution_shortcut",
    authoritativeSource: "The local workstation process-graph store.",
    terminalWriter: "buildProcessGraphOverviewText projected directly into the chat reply.",
    limits: ["No backend Ask call occurs on this path."],
    currentClosureState: "inventoried",
    disposition: "remove_after_parity",
    downstreamGate: "G6",
    sourceFile: "client/src/components/helix/HelixAskPill.tsx",
    sourceAnchors: ["shouldUseProcessGraphContextPack", "buildProcessGraphOverviewText", "Returned workstation process graph overview."],
  },
  {
    id: "client.conversation_preflight_classifier",
    surface: "client",
    entryPoint: "runConversationTurn",
    activationPredicate: "Manual canary is disabled, workstation intent needs classification, and no command was parsed.",
    lifecycleStages: ["intent arbitration", "presentation"],
    authorityOwner: "client_legacy_bridge",
    runtimeClass: "client_execution_shortcut",
    authoritativeSource: "POST /ask/conversation-turn may return a clarification before the main Ask turn.",
    terminalWriter: "Client clarification reply for route_reason_code beginning clarify:.",
    limits: ["Preflight failures are swallowed and deterministic client routing continues."],
    currentClosureState: "inventoried",
    disposition: "remove_after_parity",
    downstreamGate: "G6",
    sourceFile: "client/src/components/helix/HelixAskPill.tsx",
    sourceAnchors: ["const conversationPreflight = await runConversationTurn", "Ignore preflight failures and continue local deterministic routing."],
  },
  {
    id: "server.ask_turn_json",
    surface: "server",
    entryPoint: "planRouter.post(\"/ask/turn\")",
    activationPredicate: "POST /api/agi/ask/turn passes admission and account policy.",
    lifecycleStages: ["request", "admission", "provider dispatch", "terminal authority"],
    authorityOwner: "helix_policy",
    runtimeClass: "helix_monolith",
    authoritativeSource: "handleAskTurnRequest inside agi.plan.ts.",
    terminalWriter: "applyHelixTerminalAuthoritySingleWriter plus response preparation.",
    limits: ["Provider-specific limits apply after runtime selection."],
    currentClosureState: "inventoried",
    disposition: "replace",
    downstreamGate: "G5",
    sourceFile: "server/routes/agi.plan.ts",
    sourceAnchors: ["const handleAskTurnRequest = async", "planRouter.post(\"/ask/turn\""],
  },
  {
    id: "server.ask_turn_stream",
    surface: "server",
    entryPoint: "planRouter.post(\"/ask/turn/stream\")",
    activationPredicate: "POST /api/agi/ask/turn/stream passes stream admission and account policy.",
    lifecycleStages: ["request", "admission", "provider dispatch", "stream presentation", "terminal authority"],
    authorityOwner: "helix_policy",
    runtimeClass: "helix_monolith",
    authoritativeSource: "The stream route invokes the selected provider directly and writes transcript events plus one turn_final.",
    terminalWriter: "applyHelixTerminalAuthoritySingleWriter plus writeAskTurnSse(turn_final).",
    limits: ["SSE heartbeat and provider-specific runtime limits apply."],
    currentClosureState: "inventoried",
    disposition: "replace",
    downstreamGate: "G5",
    sourceFile: "server/routes/agi.plan.ts",
    sourceAnchors: ["planRouter.post(\"/ask/turn/stream\"", "writeAskTurnSse(res, \"turn_final\""],
  },
  {
    id: "server.ask_legacy",
    surface: "server",
    entryPoint: "planRouter.post(\"/ask\")",
    activationPredicate: "POST /api/agi/ask is selected by a legacy client/caller; only selected capability-help prompts are bridged into handleAskTurnRequest.",
    lifecycleStages: ["request", "legacy routing", "legacy execution", "terminal authority"],
    authorityOwner: "helix_legacy_runtime",
    runtimeClass: "helix_monolith",
    authoritativeSource: "Large legacy path in agi.plan.ts with special terminal builders, classifiers, and a partial /ask/turn bridge.",
    terminalWriter: "Multiple legacy materializers reconciled before response preparation.",
    limits: ["Uses the legacy runtime budgets and specialized fast paths."],
    currentClosureState: "inventoried",
    disposition: "remove_after_parity",
    downstreamGate: "G5",
    sourceFile: "server/routes/agi.plan.ts",
    sourceAnchors: ["planRouter.post(\"/ask\"", "schema: \"helix.legacy_ask_bridge.v1\""],
  },
  {
    id: "server.conversation_turn_preflight",
    surface: "server",
    entryPoint: "planRouter.post(\"/ask/conversation-turn\")",
    activationPredicate: "A legacy client explicitly requests conversation/workstation preflight.",
    lifecycleStages: ["intent arbitration", "presentation"],
    authorityOwner: "helix_legacy_runtime",
    runtimeClass: "helix_monolith",
    authoritativeSource: "Conversation-turn classifier in agi.plan.ts.",
    terminalWriter: "Conversation preflight response, which can short-circuit the client before Ask.",
    limits: ["Not the canonical completed solver path."],
    currentClosureState: "inventoried",
    disposition: "remove_after_parity",
    downstreamGate: "G5",
    sourceFile: "server/routes/agi.plan.ts",
    sourceAnchors: ["planRouter.post(\"/ask/conversation-turn\""],
  },
  {
    id: "server.ask_jobs",
    surface: "server",
    entryPoint: "planRouter.post(\"/ask/jobs\")",
    activationPredicate: "Lane parity is disabled in the client or another caller directly creates an Ask job.",
    lifecycleStages: ["request", "queued execution", "poll presentation"],
    authorityOwner: "helix_legacy_runtime",
    runtimeClass: "helix_monolith",
    authoritativeSource: "runHelixAskJob executes the legacy Ask request and stores partial/final state.",
    terminalWriter: "The legacy job responder stores the final payload for polling.",
    limits: ["Client polling defaults to 20-minute timeout.", "Server job timeout policy applies."],
    currentClosureState: "inventoried",
    disposition: "remove_after_parity",
    downstreamGate: "G5",
    sourceFile: "server/routes/agi.plan.ts",
    sourceAnchors: ["planRouter.post(\"/ask/jobs\"", "const runHelixAskJob = async"],
  },
  {
    id: "provider.runtime_selection",
    surface: "provider",
    entryPoint: "selectHelixAgentRuntime / resolveHelixAgentProvider",
    activationPredicate: "Body, x-helix-agent-runtime header, environment, then default; default is codex.",
    lifecycleStages: ["provider dispatch"],
    authorityOwner: "helix_policy",
    runtimeClass: "helix_monolith",
    authoritativeSource: "shared runtime ID contract and provider registry.",
    terminalWriter: null,
    limits: ["Unknown IDs fall back to the default codex runtime."],
    currentClosureState: "inventoried",
    disposition: "retain",
    downstreamGate: "G1",
    sourceFile: "server/services/helix-ask/agent-providers/runtime-select.ts",
    sourceAnchors: ["export function selectHelixAgentRuntime", "DEFAULT_HELIX_AGENT_RUNTIME_ID"],
  },
  {
    id: "provider.codex_native_app_server",
    surface: "provider",
    entryPoint: "runCodexNativeProviderBridge",
    activationPredicate: "Codex is selected, the route is not model-only direct, native is enabled, tests are opted in when applicable, OPENAI_API_KEY exists, and no cooldown is active.",
    lifecycleStages: ["sampling", "tool execution", "evidence re-entry", "reasoning completion"],
    authorityOwner: "runtime_codex",
    runtimeClass: "codex_native_app_server",
    authoritativeSource: "Codex app-server turn lifecycle with only route-admitted dynamic Helix tools.",
    terminalWriter: "Helix provider projection and terminal single writer after Codex completes.",
    limits: ["Turn timeout defaults to 120 seconds.", "Bootstrap timeout defaults to 45 seconds.", "Protocol output defaults to 2,000,000 bytes.", "Individual tool content is bounded at 64,000 characters.", "No Helix continuation-step cap wraps a successful native cycle."],
    currentClosureState: "inventoried",
    disposition: "retain",
    downstreamGate: "G4",
    sourceFile: "server/services/helix-ask/agent-providers/codex-native/provider-bridge.ts",
    sourceAnchors: ["export const runCodexNativeProviderBridge", "resolveCodexNativeProviderBridgeAvailability"],
  },
  {
    id: "provider.codex_exec_compatibility",
    surface: "provider",
    entryPoint: "runCodexProcess",
    activationPredicate: "Native is unavailable/ineligible/fails terminal eligibility, or compatibility gateway recovery is required.",
    lifecycleStages: ["sampling", "structured capability request", "evidence re-entry", "follow-up reasoning"],
    authorityOwner: "runtime_codex",
    runtimeClass: "codex_exec_compatibility",
    authoritativeSource: "An isolated codex exec process plus Helix-owned bounded continuation admission.",
    terminalWriter: "Helix provider projection and terminal single writer.",
    limits: ["Process timeout defaults to 120 seconds per compatibility model step.", "Collected output defaults to 256,000 bytes.", "Continuation defaults to 12 steps and is configurable only up to 32.", "Uses --ignore-user-config and an isolated CODEX_HOME; apps, plugins, and personal MCP configuration are absent."],
    currentClosureState: "inventoried",
    disposition: "quarantine",
    downstreamGate: "G4",
    sourceFile: "server/services/helix-ask/agent-providers/codex-provider.ts",
    sourceAnchors: ["export async function runCodexProcess", "CODEX_PROVIDER_CONTINUATION_HARD_MAX_STEPS", "compatibility_transport: \"codex_exec\""],
  },
  {
    id: "provider.helix_monolith_runtime",
    surface: "provider",
    entryPoint: "provider.id === helix branch in handleAskTurnRequest and stream route",
    activationPredicate: "agent_runtime selects helix by body, header, or HELIX_ASK_AGENT_RUNTIME.",
    lifecycleStages: ["sampling", "tool execution", "evidence re-entry", "follow-up reasoning", "terminal authority"],
    authorityOwner: "helix_legacy_runtime",
    runtimeClass: "helix_monolith",
    authoritativeSource: "agi.plan.ts owns the existing Helix loop; helixNativeProvider.runTurn deliberately throws if called directly.",
    terminalWriter: "applyHelixTerminalAuthoritySingleWriter in agi.plan.ts.",
    limits: ["Default loop 5 iterations/4 tools/5 model decisions.", "Large mixed prompts start at 12/10/12.", "Adaptive hard limits reach 28 iterations for large mixed prompts; environment caps permit at most 40 iterations, 20 tools, and 40 model decisions."],
    currentClosureState: "inventoried",
    disposition: "remove_after_parity",
    downstreamGate: "G5",
    sourceFile: "server/routes/agi.plan.ts",
    sourceAnchors: ["resolveHelixAgentLoopBudgetLimits", "resolveHelixAgentLoopBudgetHardLimits", "if (provider.id !== \"helix\")"],
  },
  {
    id: "provider.future_stub",
    surface: "provider",
    entryPoint: "futureProvider.runTurn",
    activationPredicate: "ENABLE_FUTURE_AGENT=1 and agent_runtime selects future.",
    lifecycleStages: ["provider dispatch", "explicit observation gateway", "typed failure"],
    authorityOwner: "helix_adapter",
    runtimeClass: "future_provider_stub",
    authoritativeSource: "Explicit read-only workstation gateway calls or a typed adapter-not-configured failure.",
    terminalWriter: "Helix provider terminal authority.",
    limits: ["No provider reasoning adapter is attached."],
    currentClosureState: "inventoried",
    disposition: "quarantine",
    downstreamGate: "G4",
    sourceFile: "server/services/helix-ask/agent-providers/future-provider.ts",
    sourceAnchors: ["const enabled = (): boolean => process.env.ENABLE_FUTURE_AGENT === \"1\"", "future_provider_adapter_not_configured"],
  },
  {
    id: "terminal.single_writer",
    surface: "terminal",
    entryPoint: "applyHelixTerminalAuthoritySingleWriter",
    activationPredicate: "A backend Ask path materializes or reconciles a terminal payload.",
    lifecycleStages: ["terminal authority", "materialization"],
    authorityOwner: "helix_terminal_authority",
    runtimeClass: "helix_monolith",
    authoritativeSource: "Terminal authority artifact and selected/rejected candidate records.",
    terminalWriter: "applyHelixTerminalAuthoritySingleWriter",
    limits: ["The service is extracted, but agi.plan.ts still invokes and sometimes synchronizes it from multiple legacy branches."],
    currentClosureState: "inventoried",
    disposition: "retain",
    downstreamGate: "G5",
    sourceFile: "server/services/helix-ask/terminal-authority-single-writer.ts",
    sourceAnchors: ["export function applyHelixTerminalAuthoritySingleWriter"],
  },
  {
    id: "presentation.debug_export",
    surface: "presentation",
    entryPoint: "GET /ask/turn/:turnId/debug-export",
    activationPredicate: "The operator requests debug evidence for an exact turn ID.",
    lifecycleStages: ["presentation"],
    authorityOwner: "client_presentation",
    runtimeClass: "presentation_only",
    authoritativeSource: "Stored backend debug export for the exact turn; it is observer evidence, not answer authority.",
    terminalWriter: null,
    limits: ["Payload size controls and redaction apply."],
    currentClosureState: "inventoried",
    disposition: "retain",
    downstreamGate: "G1",
    sourceFile: "server/routes/agi.plan.ts",
    sourceAnchors: ["planRouter.get(\"/ask/turn/:turnId/debug-export\""],
  },
  {
    id: "presentation.procedural_timeline",
    surface: "presentation",
    entryPoint: "renderHelixAskLegacyProceduralTimeline / HelixAskProceduralTimeline",
    activationPredicate: "A reply contains runtime, plan, observation, or terminal debug structures.",
    lifecycleStages: ["presentation"],
    authorityOwner: "client_presentation",
    runtimeClass: "presentation_only",
    authoritativeSource: "Categorized projection of public runtime/debug facts; it is not private model reasoning.",
    terminalWriter: null,
    limits: ["Only the first 12 runtime iterations are projected.", "Only the first 18 assembled rows are rendered.", "These are display truncations, not runtime budgets."],
    currentClosureState: "inventoried",
    disposition: "replace",
    downstreamGate: "G1",
    sourceFile: "client/src/components/helix/ask-console/HelixAskLegacyProceduralTimelineProjection.tsx",
    sourceAnchors: ["runtimeIterations.slice(0, 12)", "renderHelixAskLegacyProceduralTimeline"],
  },
  {
    id: "presentation.reasoning_theater",
    surface: "presentation",
    entryPoint: "Helix reasoning-theater and battle-stage projections",
    activationPredicate: "Reasoning-theater configuration and available Ask telemetry enable the visual surface.",
    lifecycleStages: ["presentation"],
    authorityOwner: "client_presentation",
    runtimeClass: "presentation_only",
    authoritativeSource: "Categorized phase, stance, evidence, and runtime event projections.",
    terminalWriter: null,
    limits: ["Must never be described as a complete or verbatim chain-of-thought trace."],
    currentClosureState: "inventoried",
    disposition: "retain",
    downstreamGate: "G1",
    sourceFile: "client/src/components/helix/HelixAskPill.tsx",
    sourceAnchors: ["getReasoningTheaterConfig", "reasoningTheaterCanonicalState"],
  },
] as const satisfies readonly HelixAskG0AuthorityInventoryEntry[];

export const HELIX_ASK_G0_AUTHORITY_INVENTORY_SUMMARY = {
  schema: "helix.ask.codex_parity.g0_authority_inventory.v1",
  entryCount: HELIX_ASK_G0_AUTHORITY_INVENTORY.length,
  unknownTrapdoorCount: 0,
  dispositions: {
    retain: HELIX_ASK_G0_AUTHORITY_INVENTORY.filter((entry) => entry.disposition === "retain").length,
    replace: HELIX_ASK_G0_AUTHORITY_INVENTORY.filter((entry) => entry.disposition === "replace").length,
    quarantine: HELIX_ASK_G0_AUTHORITY_INVENTORY.filter((entry) => entry.disposition === "quarantine").length,
    removeAfterParity: HELIX_ASK_G0_AUTHORITY_INVENTORY.filter(
      (entry) => entry.disposition === "remove_after_parity",
    ).length,
  },
} as const;

