import type { FruitionProceduralOperatorV1, FruitionProceduralRoleV1 } from "../fruition-procedure-expression";

export type MoralWisdomPrinciple = {
  id: string;
  sourceIdeologyNodeId: string;
  label: string;
  glyph: string;
  summary: string;
  proceduralRole: FruitionProceduralRoleV1;
  procedureOperator: FruitionProceduralOperatorV1;
  proceduralRule: string;
  traceBehavior: string;
  actionEffect: string;
  evidenceNeeds: string[];
  refusesAuthority: string[];
  tags: string[];
};

export const MORAL_WISDOM_ROOT_ID = "wisdom-first-principles";

export const MORAL_WISDOM_PRINCIPLES: readonly MoralWisdomPrinciple[] = [
  {
    id: "direct-observation-before-claim",
    sourceIdeologyNodeId: "direct-observation-before-claim",
    label: "Direct Observation Before Claim",
    glyph: "O",
    summary: "Separate observation from interpretation before forming a view.",
    proceduralRole: "first_principle",
    procedureOperator: "supports",
    proceduralRule: "Bind claims only after direct observation refs are present.",
    traceBehavior: "Trace observation refs before claim formulation.",
    actionEffect: "Start the procedure from observed evidence before naming a claim.",
    evidenceNeeds: ["observation_refs"],
    refusesAuthority: ["claim_without_observation"],
    tags: ["first_principle", "observation", "evidence"],
  },
  {
    id: "impermanence-entropy-and-revision",
    sourceIdeologyNodeId: "impermanence-entropy-and-revision",
    label: "Impermanence, Entropy, and Revision",
    glyph: "R",
    summary: "Treat evidence and claims as reviewable under drift and changing context.",
    proceduralRole: "first_principle",
    procedureOperator: "requires",
    proceduralRule: "Require a revision trigger when context or evidence changes.",
    traceBehavior: "Trace drift and revision triggers before increasing confidence.",
    actionEffect: "Require revision triggers when context, evidence, or risk changes.",
    evidenceNeeds: ["revision_trigger"],
    refusesAuthority: ["permanent_certainty"],
    tags: ["first_principle", "revision", "entropy"],
  },
  {
    id: "interdependence-yin-yang-balance",
    sourceIdeologyNodeId: "interdependence-yin-yang-balance",
    label: "Interdependence and Yin-Yang Balance",
    glyph: "Y",
    summary: "Track coupled forces and reciprocal effects before choosing a side.",
    proceduralRole: "balancer",
    procedureOperator: "balances",
    proceduralRule: "Represent coupled effects before selecting a side.",
    traceBehavior: "Trace reciprocal costs and countervailing values.",
    actionEffect: "Balance restraint and action by making reciprocal costs visible.",
    evidenceNeeds: ["coupled_tradeoffs"],
    refusesAuthority: ["one_sided_view"],
    tags: ["first_principle", "balance", "interdependence"],
  },
  {
    id: "falsifiability-and-truth-convergence",
    sourceIdeologyNodeId: "falsifiability-and-truth-convergence",
    label: "Falsifiability and Truth Convergence",
    glyph: "F",
    summary: "Make claims testable against shared observation and reproducible checks.",
    proceduralRole: "first_principle",
    procedureOperator: "requires",
    proceduralRule: "Require a testable claim boundary before convergence claims.",
    traceBehavior: "Trace the test, replication context, and unresolved uncertainty.",
    actionEffect: "Require a testable claim boundary before confidence increases.",
    evidenceNeeds: ["testable_claim", "replication_context"],
    refusesAuthority: ["untestable_claim"],
    tags: ["first_principle", "falsifiability", "validation"],
  },
  {
    id: "right-speech-and-accurate-formulation",
    sourceIdeologyNodeId: "right-speech-and-accurate-formulation",
    label: "Right Speech and Accurate Formulation",
    glyph: "S",
    summary: "Calibrate wording to evidence strength, uncertainty, and boundaries.",
    proceduralRole: "constraint",
    procedureOperator: "constrains",
    proceduralRule: "Constrain wording to the observed evidence and uncertainty level.",
    traceBehavior: "Trace claim boundaries and downgraded wording.",
    actionEffect: "Constrain the action wording so it preserves uncertainty and missing checks.",
    evidenceNeeds: ["claim_boundary"],
    refusesAuthority: ["false_certainty"],
    tags: ["first_principle", "right_speech", "formulation"],
  },
  {
    id: "non-harm-and-compassionate-constraint",
    sourceIdeologyNodeId: "non-harm-and-compassionate-constraint",
    label: "Non-Harm and Compassionate Constraint",
    glyph: "H",
    summary: "Constrain capability by harm reduction, repair, consent, and dignity.",
    proceduralRole: "constraint",
    procedureOperator: "constrains",
    proceduralRule: "Block or downgrade action when harm, consent, or repair paths are unknown.",
    traceBehavior: "Trace harm context, repair path, and consent gaps.",
    actionEffect: "Constrain capability until harm, consent, and repair paths are visible.",
    evidenceNeeds: ["harm_context", "repair_path"],
    refusesAuthority: ["harm_blind_action"],
    tags: ["first_principle", "non-harm", "repair"],
  },
  {
    id: "fairness-due-process-and-justification",
    sourceIdeologyNodeId: "fairness-due-process-and-justification",
    label: "Fairness, Due Process, and Justification",
    glyph: "J",
    summary: "Require reasons, jurisdiction, contestability, and review for legitimate action.",
    proceduralRole: "action_gate",
    procedureOperator: "requires",
    proceduralRule: "Require reasons, contestability, and jurisdiction before action readiness.",
    traceBehavior: "Trace due-process checks before any actionable posture.",
    actionEffect: "Require due process checks before a procedure becomes actionable.",
    evidenceNeeds: ["jurisdiction_context", "contestability_path"],
    refusesAuthority: ["unjustified_power"],
    tags: ["first_principle", "fairness", "due-process"],
  },
  {
    id: "skillful-action-under-uncertainty",
    sourceIdeologyNodeId: "skillful-action-under-uncertainty",
    label: "Skillful Action Under Uncertainty",
    glyph: "A",
    summary: "Scale action to evidence, risk, reversibility, and missing checks.",
    proceduralRole: "objective_view",
    procedureOperator: "routes_to",
    proceduralRule: "Route uncertain situations to ask, review, block, or user decision.",
    traceBehavior: "Trace risk and reversibility before selecting the posture.",
    actionEffect: "Route the assembled state toward ask, review, block, or user decision.",
    evidenceNeeds: ["risk_context", "reversibility_context"],
    refusesAuthority: ["unchecked_action"],
    tags: ["first_principle", "skillful_action", "uncertainty"],
  },
  {
    id: "mission-ethos",
    sourceIdeologyNodeId: "mission-ethos",
    label: "Mission Ethos",
    glyph: "M",
    summary: "Bind procedures to the root mission before local optimization.",
    proceduralRole: "objective_view",
    procedureOperator: "routes_to",
    proceduralRule: "Route local recommendations through the root mission before presenting them.",
    traceBehavior: "Trace activated nodes back to mission-ethos and then wisdom-first-principles.",
    actionEffect: "Use mission alignment as the objective frame for downstream badge combinations.",
    evidenceNeeds: ["mission_relevance", "root_path"],
    refusesAuthority: ["local_optimization_without_ethos"],
    tags: ["mission", "root_path", "objective_view"],
  },
  {
    id: "integrity-protocols",
    sourceIdeologyNodeId: "integrity-protocols",
    label: "Integrity Protocols",
    glyph: "I",
    summary: "Start claims and actions from provenance, auditability, and proof gates.",
    proceduralRole: "constraint",
    procedureOperator: "requires",
    proceduralRule: "Require provenance and audit hooks before treating an output as reliable evidence.",
    traceBehavior: "Trace source identity, proof gate status, and audit refs.",
    actionEffect: "Constrain recommendations until provenance and proof gates are named.",
    evidenceNeeds: ["source_provenance", "audit_ref", "proof_gate_status"],
    refusesAuthority: ["unprovenance_claim", "unaudited_evidence"],
    tags: ["integrity", "provenance", "audit", "constraint"],
  },
  {
    id: "provenance-protocol",
    sourceIdeologyNodeId: "provenance-protocol",
    label: "Provenance Protocol",
    glyph: "P",
    summary: "Require live or retrievable source lineage before increasing confidence.",
    proceduralRole: "evidence_requirement",
    procedureOperator: "requires",
    proceduralRule: "Require source lineage before a reflection can confirm a factual premise.",
    traceBehavior: "Trace source kind, refs, freshness, and whether the evidence is primary or derived.",
    actionEffect: "Ask for provenance when source lineage is missing or assistant-derived.",
    evidenceNeeds: ["source_lineage", "freshness_context"],
    refusesAuthority: ["source_laundering", "assistant_summary_as_fact"],
    tags: ["provenance", "evidence", "anti_poison"],
  },
  {
    id: "liveness-or-it-didnt-happen",
    sourceIdeologyNodeId: "liveness-or-it-didnt-happen",
    label: "Liveness or It Didn't Happen",
    glyph: "L",
    summary: "Treat unobserved or stale state as missing evidence.",
    proceduralRole: "evidence_requirement",
    procedureOperator: "requires",
    proceduralRule: "Require current observation for claims about live state.",
    traceBehavior: "Trace observation freshness and reject stale-state confirmation.",
    actionEffect: "Downgrade live-state claims to missing evidence when liveness is absent.",
    evidenceNeeds: ["live_observation_ref", "freshness_timestamp"],
    refusesAuthority: ["stale_state_claim", "screenless_deictic_claim"],
    tags: ["liveness", "freshness", "evidence"],
  },
  {
    id: "voice-integrity",
    sourceIdeologyNodeId: "voice-integrity",
    label: "Voice Integrity",
    glyph: "V",
    summary: "Keep spoken certainty no stronger than the evidence channel allows.",
    proceduralRole: "constraint",
    procedureOperator: "constrains",
    proceduralRule: "Constrain voice wording and callouts to evidence certainty and channel provenance.",
    traceBehavior: "Trace speaker/source confidence and wording downgrade decisions.",
    actionEffect: "Require clarification or quieter wording for uncertain voice events.",
    evidenceNeeds: ["speaker_context", "channel_integrity", "certainty_level"],
    refusesAuthority: ["voice_overclaim", "unverified_speaker_claim"],
    tags: ["voice", "right_speech", "channel_integrity"],
  },
  {
    id: "feedback-loop-hygiene",
    sourceIdeologyNodeId: "feedback-loop-hygiene",
    label: "Feedback Loop Hygiene",
    glyph: "G",
    summary: "Prevent outputs from becoming self-confirming evidence.",
    proceduralRole: "constraint",
    procedureOperator: "blocks",
    proceduralRule: "Block recursive confirmation from prior reflections or assistant summaries.",
    traceBehavior: "Trace parent reflection id, loop depth, source trust, and confidence cap.",
    actionEffect: "Cap confidence and mark continuity-only evidence in recursive reflection loops.",
    evidenceNeeds: ["primary_evidence_ref", "loop_depth"],
    refusesAuthority: ["self_confirmation", "recursive_confidence_inflation"],
    tags: ["anti_poison", "feedback_loop", "confidence_cap"],
  },
  {
    id: "verification-checklist",
    sourceIdeologyNodeId: "verification-checklist",
    label: "Verification Checklist",
    glyph: "K",
    summary: "Gate action readiness on explicit checks rather than narrative confidence.",
    proceduralRole: "action_gate",
    procedureOperator: "requires",
    proceduralRule: "Require checklist evidence before moving from reflection to action recommendation.",
    traceBehavior: "Trace required, satisfied, and missing checklist items.",
    actionEffect: "Route unchecked situations to ask_user or blocked admission.",
    evidenceNeeds: ["required_checks", "satisfied_checks", "missing_checks"],
    refusesAuthority: ["unchecked_action_readiness"],
    tags: ["verification", "checklist", "action_gate"],
  },
  {
    id: "two-key-approval",
    sourceIdeologyNodeId: "two-key-approval",
    label: "Two-Key Approval",
    glyph: "2",
    summary: "Require independent approval keys for covered or sensitive actions.",
    proceduralRole: "action_gate",
    procedureOperator: "requires",
    proceduralRule: "Require both legal/authority and ethos/user confirmation keys before covered action.",
    traceBehavior: "Trace required keys, present keys, and missing approval reason.",
    actionEffect: "Block covered actions until both approval keys are present.",
    evidenceNeeds: ["authority_key", "ethos_key"],
    refusesAuthority: ["single_key_sensitive_action", "approval_bypass"],
    tags: ["approval", "consent", "action_gate", "covered_action"],
  },
  {
    id: "training-certification-gate",
    sourceIdeologyNodeId: "training-certification-gate",
    label: "Training and Certification Gate",
    glyph: "T",
    summary: "Require role competence and recent certification for safety-critical actions.",
    proceduralRole: "action_gate",
    procedureOperator: "requires",
    proceduralRule: "Require current training and incident review before safety-critical action.",
    traceBehavior: "Trace certification status, renewal cadence, and incident review hooks.",
    actionEffect: "Block or require review for stale certification or missing competence evidence.",
    evidenceNeeds: ["certification_status", "renewal_cadence", "incident_review_ref"],
    refusesAuthority: ["stale_certification", "untrained_critical_action"],
    tags: ["training", "certification", "action_gate"],
  },
  {
    id: "no-bypass-guardrail",
    sourceIdeologyNodeId: "no-bypass-guardrail",
    label: "No Bypass Guardrail",
    glyph: "B",
    summary: "Do not let reflection justify bypassing admission, consent, or review.",
    proceduralRole: "authority_boundary",
    procedureOperator: "blocks",
    proceduralRule: "Block requests to use MoralGraph output as permission to bypass action admission.",
    traceBehavior: "Trace bypass cues to blocked admission with agent_executable false.",
    actionEffect: "Convert bypass pressure into a blocked recommended-action admission.",
    evidenceNeeds: ["admission_artifact", "user_consent_state"],
    refusesAuthority: ["action_bypass", "consent_override"],
    tags: ["guardrail", "admission", "authority_boundary"],
  },
  {
    id: "lawful-interface-protocol",
    sourceIdeologyNodeId: "lawful-interface-protocol",
    label: "Lawful Interface Protocol",
    glyph: "U",
    summary: "Keep legal and authority boundaries explicit before any external-facing action.",
    proceduralRole: "constraint",
    procedureOperator: "constrains",
    proceduralRule: "Constrain reflections from becoming legal authority or external action.",
    traceBehavior: "Trace legal/authority boundary and route to evidence-only output.",
    actionEffect: "Mark legal-sensitive actions as claim-sensitive or blocked.",
    evidenceNeeds: ["jurisdiction_context", "authority_boundary"],
    refusesAuthority: ["legal_authority_claim", "external_action_without_authority"],
    tags: ["lawful_interface", "legal_boundary", "constraint"],
  },
  {
    id: "harm-weighted-priority-standard",
    sourceIdeologyNodeId: "harm-weighted-priority-standard",
    label: "Harm-Weighted Priority Standard",
    glyph: "W",
    summary: "Prioritize unresolved high-harm possibilities before optimization.",
    proceduralRole: "balancer",
    procedureOperator: "balances",
    proceduralRule: "Rank next questions and safeguards by possible harm severity under uncertainty.",
    traceBehavior: "Trace harm severity, uncertainty, and selected safeguard priority.",
    actionEffect: "Route high-harm uncertainty to missing evidence or review gates.",
    evidenceNeeds: ["harm_severity", "affected_parties", "uncertainty_level"],
    refusesAuthority: ["harm_blind_priority"],
    tags: ["harm", "priority", "balancer"],
  },
  {
    id: "access-to-counsel-pathway",
    sourceIdeologyNodeId: "access-to-counsel-pathway",
    label: "Access-to-Counsel Pathway",
    glyph: "C",
    summary: "Escalate legal-risk situations toward qualified counsel rather than tool authority.",
    proceduralRole: "action_gate",
    procedureOperator: "requires",
    proceduralRule: "Require qualified counsel or user-directed professional review for legal-risk advice.",
    traceBehavior: "Trace legal-risk cues and recommended professional review boundary.",
    actionEffect: "Block legal authority claims and suggest evidence gathering or counsel review.",
    evidenceNeeds: ["legal_risk_context", "qualified_review_path"],
    refusesAuthority: ["legal_advice_as_authority"],
    tags: ["legal_boundary", "review", "action_gate"],
  },
  {
    id: "financial-fog-warning",
    sourceIdeologyNodeId: "financial-fog-warning",
    label: "Financial Fog Warning",
    glyph: "$",
    summary: "Treat financial recommendations as claim-sensitive and evidence-limited.",
    proceduralRole: "authority_boundary",
    procedureOperator: "blocks",
    proceduralRule: "Block MoralGraph from making financial authority claims or investment directives.",
    traceBehavior: "Trace financial-risk cue to evidence-only boundary and missing professional context.",
    actionEffect: "Downgrade financial prompts to diagnostic reflection or blocked authority claim.",
    evidenceNeeds: ["financial_context", "professional_review_boundary"],
    refusesAuthority: ["financial_advice_as_authority"],
    tags: ["financial_boundary", "claim_sensitive", "authority_boundary"],
  },
  {
    id: "flattery-laundering-detection",
    sourceIdeologyNodeId: "flattery-laundering-detection",
    label: "Flattery Laundering Detection",
    glyph: "D",
    summary: "Detect praise or identity framing that tries to launder weak evidence into confidence.",
    proceduralRole: "constraint",
    procedureOperator: "blocks",
    proceduralRule: "Block flattery from increasing confidence or bypassing evidence requirements.",
    traceBehavior: "Trace identity/praise cues separately from evidence-bearing claims.",
    actionEffect: "Preserve missing evidence and confidence caps despite flattering context.",
    evidenceNeeds: ["evidence_bearing_claim", "flattery_context"],
    refusesAuthority: ["flattery_as_evidence", "identity_laundered_confidence"],
    tags: ["anti_poison", "confidence", "constraint"],
  },
  {
    id: "values-over-images",
    sourceIdeologyNodeId: "values-over-images",
    label: "Values Over Images",
    glyph: "Q",
    summary: "Prefer operational values over status, optics, or self-image.",
    proceduralRole: "constraint",
    procedureOperator: "constrains",
    proceduralRule: "Constrain recommendations to stated values rather than image-preserving narratives.",
    traceBehavior: "Trace value conflict and optics pressure separately.",
    actionEffect: "Route image-driven pressure toward clarification of actual values and harms.",
    evidenceNeeds: ["stated_values", "image_pressure_context"],
    refusesAuthority: ["optics_as_justification"],
    tags: ["values", "integrity", "constraint"],
  },
  {
    id: "worldview-integrity",
    sourceIdeologyNodeId: "worldview-integrity",
    label: "Worldview Integrity",
    glyph: "Z",
    summary: "Check whether local conclusions cohere with the declared worldview and constraints.",
    proceduralRole: "balancer",
    procedureOperator: "balances",
    proceduralRule: "Balance local action pressure against declared worldview constraints.",
    traceBehavior: "Trace worldview refs, conflicting values, and unresolved tensions.",
    actionEffect: "Ask for clarification when a recommendation conflicts with declared values.",
    evidenceNeeds: ["declared_worldview_ref", "conflicting_value_context"],
    refusesAuthority: ["unexamined_worldview_conflict"],
    tags: ["worldview", "values", "balancer"],
  },
  {
    id: "capability-ambition-gradient",
    sourceIdeologyNodeId: "capability-ambition-gradient",
    label: "Capability and Ambition Gradient",
    glyph: "N",
    summary: "Scale ambition to verified capability and guardrail maturity.",
    proceduralRole: "balancer",
    procedureOperator: "balances",
    proceduralRule: "Balance desired action against capability evidence and guardrail readiness.",
    traceBehavior: "Trace capability evidence, ambition pressure, and missing guardrails.",
    actionEffect: "Route over-ambitious action to review or missing evidence.",
    evidenceNeeds: ["capability_evidence", "guardrail_readiness", "ambition_pressure"],
    refusesAuthority: ["capability_overclaim", "ambition_without_guardrails"],
    tags: ["capability", "ambition", "balancer"],
  },
  {
    id: "inherited-conditioning-check",
    sourceIdeologyNodeId: "inherited-conditioning-check",
    label: "Inherited Conditioning Check",
    glyph: "E",
    summary: "Separate chosen belief from inherited norm, cliche, role-pressure, or stale self-story.",
    proceduralRole: "constraint",
    procedureOperator: "constrains",
    proceduralRule: "Require belief-origin separation before treating a self-story as chosen commitment.",
    traceBehavior: "Trace observation, inherited story, chosen value, and current practice separately.",
    actionEffect: "Constrain identity claims until inherited pressure and present commitment are separated.",
    evidenceNeeds: ["belief_origin_context", "current_observation", "chosen_commitment"],
    refusesAuthority: ["conditioned_belief_as_final", "conditioning_as_disproof"],
    tags: ["inner_practice", "conditioning", "identity", "belief_origin"],
  },
  {
    id: "purpose-as-inquiry",
    sourceIdeologyNodeId: "purpose-as-inquiry",
    label: "Purpose as Inquiry",
    glyph: "?",
    summary: "A dream becomes responsible when it can be researched, tested, revised, and carried into practice.",
    proceduralRole: "objective_view",
    procedureOperator: "routes_to",
    proceduralRule: "Route purpose claims through research, small tests, evidence collection, and revision.",
    traceBehavior: "Trace source inquiry, small experiment, review trigger, and dream-preserving revision.",
    actionEffect: "Turn inspiration into a bounded inquiry path without treating uncertainty as failure.",
    evidenceNeeds: ["purpose_sources", "small_test", "revision_condition"],
    refusesAuthority: ["inspiration_as_proof", "uncertainty_as_abandonment"],
    tags: ["inner_practice", "purpose", "dreams", "evidence", "agency"],
  },
  {
    id: "inspiration-without-imitation",
    sourceIdeologyNodeId: "inspiration-without-imitation",
    label: "Inspiration Without Imitation",
    glyph: "X",
    summary: "Let models awaken values without becoming identity mirrors or outsourced authority.",
    proceduralRole: "constraint",
    procedureOperator: "constrains",
    proceduralRule: "Require admired models to be translated into values and chosen practices.",
    traceBehavior: "Trace admired value, imitated surface, approval pressure, and chosen practice.",
    actionEffect: "Constrain imitation pressure by extracting the value before adopting the image.",
    evidenceNeeds: ["admired_value", "imitation_pressure", "chosen_practice"],
    refusesAuthority: ["admiration_as_authority", "identity_surrender"],
    tags: ["inner_practice", "inspiration", "imitation", "values", "agency"],
  },
  {
    id: "goalpost-integrity",
    sourceIdeologyNodeId: "goalpost-integrity",
    label: "Goalpost Integrity",
    glyph: "=",
    summary: "Revise criteria openly; do not move standards to protect a preferred conclusion.",
    proceduralRole: "evidence_requirement",
    procedureOperator: "requires",
    proceduralRule: "Require old criterion, new criterion, and evidence for the revision before confidence increases.",
    traceBehavior: "Trace criteria changes, justification evidence, and unresolved uncertainty.",
    actionEffect: "Hold revised standards as conditional until the revision reason is visible.",
    evidenceNeeds: ["old_criterion", "new_criterion", "revision_evidence"],
    refusesAuthority: ["criteria_drift_as_proof", "conclusion_protection"],
    tags: ["revision", "falsifiability", "criteria", "integrity"],
  },
  {
    id: "recognition-before-transcendence",
    sourceIdeologyNodeId: "recognition-before-transcendence",
    label: "Recognition Before Transcendence",
    glyph: "*",
    summary: "Do not claim to transcend difference before recognizing affected agency and missing understanding.",
    proceduralRole: "constraint",
    procedureOperator: "constrains",
    proceduralRule: "Require affected agency, translation gaps, and non-domination checks before transcendence claims.",
    traceBehavior: "Trace who is outside the frame, what translation is missing, and where coercion could enter.",
    actionEffect: "Constrain inclusion or transcendence language until recognition and agency are mapped.",
    evidenceNeeds: ["affected_agency_map", "translation_gap", "non_domination_check"],
    refusesAuthority: ["assimilation_as_transcendence", "abandonment_as_transcendence"],
    tags: ["consideration", "culture", "recognition", "affected_parties", "non_domination"],
  },
  {
    id: "dependency-transparency-gate",
    sourceIdeologyNodeId: "dependency-transparency-gate",
    label: "Dependency Transparency Gate",
    glyph: "D",
    summary: "When others materially depend on a commitment, disclose risk early enough for them to adapt.",
    proceduralRole: "action_gate",
    procedureOperator: "requires",
    proceduralRule: "Require timely disclosure when hidden shared risk would remove another person's ability to adapt.",
    traceBehavior: "Trace shared dependency, known risk, disclosure deadline, and contingency or repair path.",
    actionEffect: "Route hidden dependency risk toward disclosure and contingency planning before damage compounds.",
    evidenceNeeds: ["shared_dependency_context", "risk_disclosure_deadline", "contingency_or_repair_path"],
    refusesAuthority: ["hidden_dependency_risk", "late_disclosure_as_private_matter"],
    tags: ["transparency", "dependency", "shared_obligation", "right_speech", "due_process", "repair_readiness"],
  },
  {
    id: "agency-preserving-disclosure",
    sourceIdeologyNodeId: "agency-preserving-disclosure",
    label: "Agency-Preserving Disclosure",
    glyph: "A",
    summary: "Disclosure is required when silence would remove another person's ability to choose, prepare, or protect themselves.",
    proceduralRole: "constraint",
    procedureOperator: "constrains",
    proceduralRule: "Constrain silence when undisclosed risk controls another person's choices, preparation, or protection.",
    traceBehavior: "Trace affected choices, response time, disclosure scope, and options lost through delay.",
    actionEffect: "Preserve agency by naming what must be disclosed before choices become unavailable.",
    evidenceNeeds: ["affected_choices", "response_time_window", "disclosure_scope"],
    refusesAuthority: ["silence_as_private_when_options_are_controlled", "agency_stripping_by_delay"],
    tags: ["agency", "disclosure", "non-harm", "affected_parties", "consent", "planning"],
  },
  {
    id: "shame-avoidance-loop",
    sourceIdeologyNodeId: "shame-avoidance-loop",
    label: "Shame-Avoidance Loop",
    glyph: "!",
    summary: "Shame becomes destructive when it delays truth, blocks repair, and lets damage compound.",
    proceduralRole: "constraint",
    procedureOperator: "constrains",
    proceduralRule: "Separate shame from repair before allowing self-image pain to delay actionable truth.",
    traceBehavior: "Trace shame context, avoided disclosure, repair delay cost, and the next actionable truth.",
    actionEffect: "Route shame pressure toward disclosure and repair without turning it into a character verdict.",
    evidenceNeeds: ["shame_context", "repair_delay_cost", "actionable_truth"],
    refusesAuthority: ["shame_as_reason_to_hide", "self_image_protection_as_repair"],
    tags: ["shame", "avoidance", "repair_readiness", "guilt_signal", "feedback_loop", "responsibility"],
  },
  {
    id: "fallout-transfer-check",
    sourceIdeologyNodeId: "fallout-transfer-check",
    label: "Fallout Transfer Check",
    glyph: ">",
    summary: "Detect when avoided responsibility shifts cost, uncertainty, or urgency onto affected people.",
    proceduralRole: "constraint",
    procedureOperator: "constrains",
    proceduralRule: "Constrain avoided responsibility when it transfers cost, uncertainty, or urgency to affected people.",
    traceBehavior: "Trace the transferred burden, affected-party consent, urgency shift, and repair or boundary reset.",
    actionEffect: "Route externalized fallout toward burden mapping, disclosure, repair, or boundary reset.",
    evidenceNeeds: ["transferred_burden_map", "affected_party_consent", "urgency_or_cost_shift"],
    refusesAuthority: ["delayed_conflict_as_reduced_harm", "externalized_fallout_without_consent"],
    tags: ["consideration_debt", "externalized_cost", "affected_parties", "dependency", "non-harm", "fairness"],
  },
  {
    id: "familiarity-anonymity-balance",
    sourceIdeologyNodeId: "familiarity-anonymity-balance",
    label: "Familiarity-Anonymity Balance",
    glyph: "~",
    summary: "Repeated familiarity may support patience while anonymity may protect privacy and fresh starts; neither establishes moral superiority.",
    proceduralRole: "balancer",
    procedureOperator: "balances",
    proceduralRule: "Separate settlement density from repeated contact, network overlap, newcomer access, privacy, and institutional reach.",
    traceBehavior: "Trace the mechanisms carrying familiarity or anonymity instead of treating density as a virtue signal.",
    actionEffect: "Balance relational patience, privacy, alternatives, and institutional permeability before drawing a social conclusion.",
    evidenceNeeds: ["repeated_contact_context", "network_overlap", "newcomer_access", "privacy_and_exit_options", "service_alternatives"],
    refusesAuthority: ["rural_density_as_virtue", "urban_density_as_distrust", "familiarity_as_proof", "anonymity_as_disposability"],
    tags: ["trust", "familiarity", "anonymity", "density", "privacy", "balance"],
  },
  {
    id: "trust-medium-translation",
    sourceIdeologyNodeId: "trust-medium-translation",
    label: "Trust-Medium Translation",
    glyph: "T",
    summary: "Identify how trust moves among familiarity, reputation, contracts, records, law, and public institutions.",
    proceduralRole: "balancer",
    procedureOperator: "balances",
    proceduralRule: "Name what each trust medium preserves, what it loses, and which contestability or repair path replaces missing context.",
    traceBehavior: "Trace source channel, destination channel, dependency scope, translation loss, and fallback path.",
    actionEffect: "Keep formal evidence domain-bounded while preserving context, correction, and appeal.",
    evidenceNeeds: ["source_trust_channel", "destination_trust_channel", "dependency_scope", "translation_loss", "fallback_and_appeal_path"],
    refusesAuthority: ["contract_as_moral_character", "institution_as_trustless", "personal_familiarity_as_high_stakes_proof", "financial_record_as_total_reputation"],
    tags: ["trust", "translation", "institution", "contract", "reputation", "balance"],
  },
  {
    id: "domain-bounded-accountability",
    sourceIdeologyNodeId: "domain-bounded-accountability",
    label: "Domain-Bounded Accountability",
    glyph: "[",
    summary: "Accountability evidence applies only to the observed domain, exposure, parties, and time period.",
    proceduralRole: "evidence_requirement",
    procedureOperator: "requires",
    proceduralRule: "Require domain, observer exposure, dates, provenance, dispute state, and repair history before increasing confidence.",
    traceBehavior: "Trace which narrow claim the evidence supports and block cross-domain totalization.",
    actionEffect: "Constrain trust claims to the observed domain and retain correction, expiry, and dispute paths.",
    evidenceNeeds: ["accountability_domain", "observer_exposure", "time_window", "source_provenance", "dispute_or_correction_state", "repair_history"],
    refusesAuthority: ["credit_as_moral_worth", "prestige_as_truth", "reference_as_global_character", "cross_domain_trust_totalization"],
    tags: ["trust", "accountability", "evidence", "provenance", "time_window", "anti_totalization"],
  },
  {
    id: "contestable-reentry-threshold",
    sourceIdeologyNodeId: "contestable-reentry-threshold",
    label: "Contestable Re-entry Threshold",
    glyph: "]",
    summary: "Consequential exclusion requires visible criteria, reasons, appeal, repair, review, and a possible re-entry state.",
    proceduralRole: "action_gate",
    procedureOperator: "requires",
    proceduralRule: "Convert a rejected-person label into a bounded access decision with a stated threshold and review lifecycle.",
    traceBehavior: "Trace threshold purpose, evidence, decision reason, appeal, repair, retention, and review date.",
    actionEffect: "Block permanent or opaque exclusion until contestation and re-entry conditions are visible.",
    evidenceNeeds: ["published_threshold", "decision_reason", "supporting_evidence", "appeal_path", "repair_or_reentry_path", "review_or_sunset_date"],
    refusesAuthority: ["permanent_reject_identity", "opaque_denial", "unappealable_score", "stale_record_exclusion"],
    tags: ["trust", "threshold", "appeal", "repair", "reentry", "due_process", "action_gate"],
  },
] as const;

export function getMoralWisdomPrinciple(id: string): MoralWisdomPrinciple | undefined {
  return MORAL_WISDOM_PRINCIPLES.find((principle) => principle.id === id);
}
