export {
  RoomEnvironmentSubjectError,
  assertPendingFabricWorkstationSource,
  assignRoomEnvironmentSubject,
  bindOwnRoomEnvironmentSubject,
  isRoomEnvironmentSubjectError,
  listRoomEnvironmentProjections,
  listRoomEnvironmentParticipantSubjectContexts,
  resolveRoomEnvironmentSubjectForProbe,
  resolveActiveRoomEnvironmentSubjectByRef,
  revokeOwnRoomEnvironmentSubject,
  type ResolvedRoomEnvironmentSubject,
  type RoomEnvironmentParticipantSubjectContext,
  type RoomEnvironmentSubjectErrorCode,
} from "./subject-binding-store";
