import { describe, expect, it } from "vitest";
import { buildHelixDebugExportEnvelopeFromMasterPayload } from "@/lib/agi/debugExport";

describe("Helix Ask debug export capability lanes", () => {
  it("preserves capability lane session, mail-loop, and goal-binding evidence in the client export", () => {
    const text = buildHelixDebugExportEnvelopeFromMasterPayload(
      {
        id: "turn-debug-lanes",
        question: "keep translating the document",
        content: "Translation lane is active.",
      },
      {
        selected_final_answer: "Translation lane is active.",
        agent_runtime: "codex",
        selected_agent_provider: {
          id: "codex",
          label: "Codex Workstation Mode",
        },
        capability_lane_ids: ["speech_to_text", "live_translation", "text_to_speech"],
        capability_lane_statuses: {
          speech_to_text: "available",
          live_translation: "available",
          text_to_speech: "available",
        },
        capability_lane_call_results: [
          {
            capability: "speech_to_text.transcribe_audio",
            ok: true,
            terminal_eligible: false,
            assistant_answer: false,
            raw_content_included: false,
          },
          {
            capability: "live_translation.translate_text",
            ok: true,
          },
          {
            capability: "text_to_speech.speak_text",
            ok: true,
            receipt: {
              playback_status: "started",
              assistant_answer: false,
              terminal_eligible: false,
            },
            terminal_eligible: false,
            assistant_answer: false,
            raw_content_included: false,
          },
        ],
        capability_lane_turn_timeline: [
          {
            schema: "helix.capability_lane.provider_timeline_event.v1",
            seq: 0,
            stage: "lane_visible",
            selected_runtime_agent_provider: "codex",
            lane_id: "live_translation",
            capability_id: "live_translation.translate_text",
            status: "available",
            lane_visible: true,
            lane_requested: false,
            lane_executed: false,
            observation_reentered: false,
            selected_backend_provider: "live_translation.local_runtime",
            observation_ref: null,
            receipt_ref: null,
            terminal_authority_status: "not_terminal_authority",
            reentry_required: true,
            terminal_eligible: false,
            assistant_answer: false,
            raw_content_included: false,
          },
          {
            schema: "helix.capability_lane.provider_timeline_event.v1",
            seq: 1,
            stage: "lane_observation",
            selected_runtime_agent_provider: "codex",
            lane_id: "live_translation",
            capability_id: "live_translation.translate_text",
            status: "completed",
            lane_visible: false,
            lane_requested: true,
            lane_executed: true,
            observation_reentered: false,
            selected_backend_provider: "live_translation.local_runtime",
            observation_ref: "obs:translation",
            receipt_ref: "receipt:projection",
            terminal_authority_status: "pending_helix_terminal_authority",
            reentry_required: true,
            terminal_eligible: false,
            assistant_answer: false,
            raw_content_included: false,
          },
          {
            schema: "helix.capability_lane.provider_timeline_event.v1",
            seq: 2,
            stage: "goal_binding",
            selected_runtime_agent_provider: "codex",
            lane_id: "speech_to_text",
            capability_id: null,
            status: "bound",
            lane_visible: false,
            lane_requested: true,
            lane_executed: true,
            observation_reentered: false,
            selected_backend_provider: "speech_to_text.openai_compatible",
            observation_ref: "obs:stt",
            receipt_ref: "stage_play_live_source_mail:stt-debug",
            terminal_authority_status: "pending_helix_terminal_authority",
            reentry_required: true,
            terminal_eligible: false,
            assistant_answer: false,
            raw_content_included: false,
          },
          {
            schema: "helix.capability_lane.provider_timeline_event.v1",
            seq: 3,
            stage: "goal_binding",
            selected_runtime_agent_provider: "codex",
            lane_id: "live_translation",
            capability_id: "live_translation.translate_text",
            goal_id: "goal:audio-translation-playback",
            goal_binding_id: "goal-binding-docs",
            lane_session_id: "lane-session-docs",
            status: "bound",
            lane_visible: false,
            lane_requested: true,
            lane_executed: true,
            observation_reentered: false,
            selected_backend_provider: "live_translation.local_runtime",
            observation_ref: "obs:translation-goal-binding",
            receipt_ref: "receipt:translation-goal-binding",
            mail_loop_ref: "stage_play_live_source_mail:translation-debug",
            materialized_mail_loop_evidence: true,
            dispatch_target: "ask_wake",
            dispatch_admission_status: "eligible_waiting_for_mail_loop",
            dispatch_blocked_reason: null,
            wake_dispatch_allowed: false,
            side_effects_allowed: false,
            source_id: "document_markdown:docs/research/nhm2.md",
            source_hash: "fnv1a32:goal-docs",
            source_kind: "docs",
            source_text_hash: "fnv1a32:goal-source-text",
            source_text_char_count: 2048,
            projection_target: "docs_chunk",
            account_locale: "es-US",
            target_language: "es",
            chunk_id: "u0001",
            chunk_index: 0,
            dedupe_key: "document_markdown:docs/research/nhm2.md:u0001:es",
            session_control_key:
              "lane-session-docs::document_markdown:docs/research/nhm2.md::fnv1a32:goal-docs::docs_chunk::es-US::es",
            source_binding_key:
              "document_markdown:docs/research/nhm2.md::fnv1a32:goal-docs::docs_chunk::es-US::es",
            session_lifecycle_action: "record_observation",
            latest_observation_key:
              "document_markdown:docs/research/nhm2.md::fnv1a32:goal-docs::docs_chunk::es::u0001::receipt:translation-goal-binding",
            observation_lane_session_id: "lane-session-docs-observation",
            report_action: "wake_on_salience",
            report_reason: "goal_binding_policy_requests_wake_on_salience",
            report_summary_text:
              "goal lane wake on salience | reason goal_binding_policy_requests_wake_on_salience | evidence obs:translation-goal-binding | mail stage_play_live_source_mail:translation-debug | receipt receipt:translation-goal-binding | terminal authority pending_helix_terminal_authority",
            terminal_authority_status: "pending_helix_terminal_authority",
            reentry_required: true,
            terminal_eligible: false,
            assistant_answer: false,
            raw_content_included: false,
          },
          {
            schema: "helix.capability_lane.provider_timeline_event.v1",
            seq: 4,
            stage: "goal_binding",
            selected_runtime_agent_provider: "codex",
            lane_id: "text_to_speech",
            capability_id: null,
            status: "bound",
            lane_visible: false,
            lane_requested: true,
            lane_executed: true,
            observation_reentered: false,
            selected_backend_provider: "text_to_speech.existing_voice_service",
            observation_ref: "obs:voice",
            receipt_ref: "receipt:voice-playback",
            terminal_authority_status: "pending_helix_terminal_authority",
            reentry_required: true,
            terminal_eligible: false,
            assistant_answer: false,
            raw_content_included: false,
          },
          {
            schema: "helix.capability_lane.provider_timeline_event.v1",
            seq: 5,
            stage: "lane_session",
            selected_runtime_agent_provider: "codex",
            lane_id: "live_translation",
            capability_id: null,
            status: "paused",
            lane_visible: false,
            lane_requested: true,
            lane_executed: false,
            observation_reentered: false,
            selected_backend_provider: "live_translation.local_runtime",
            observation_ref: null,
            receipt_ref: null,
            session_status: "paused",
            session_health: "degraded",
            lifecycle_action: "pause",
            session_lifecycle_action: "pause",
            session_action: "pause",
            latest_event_id: "lane-session-docs:pause:320",
            terminal_authority_status: "not_terminal_authority",
            reentry_required: true,
            terminal_eligible: false,
            assistant_answer: false,
            raw_content_included: false,
          },
          {
            schema: "helix.capability_lane.provider_timeline_event.v1",
            seq: 6,
            stage: "terminal_selected",
            selected_runtime_agent_provider: "codex",
            lane_id: "helix_terminal_authority",
            capability_id: null,
            status: "completed",
            lane_visible: false,
            lane_requested: true,
            lane_executed: true,
            observation_reentered: true,
            selected_backend_provider: null,
            observation_ref: "obs:translation",
            receipt_ref: "receipt:projection",
            terminal_authority_status: "authorized_by_helix_provider_candidate_bridge",
            reentry_required: true,
            terminal_eligible: false,
            assistant_answer: false,
            raw_content_included: false,
          },
        ],
        capability_lane_observation_packets: [
          {
            schema: "helix.agent_step_observation_packet.v1",
            capability_key: "speech_to_text.transcribe_audio",
            status: "succeeded",
            state_delta: {
              speech_to_text_observation: {
                schema: "helix.speech_to_text.observation.v1",
                source_kind: "audio_transcript",
                stage_play_mail_id: "stage_play_live_source_mail:stt-debug",
                terminal_eligible: false,
                assistant_answer: false,
                raw_audio_included: false,
              },
              speech_to_text_live_source_mail_item: {
                mailId: "stage_play_live_source_mail:stt-debug",
                sourceKind: "audio_transcript",
                context_role: "tool_evidence",
                terminal_eligible: false,
                assistant_answer: false,
                raw_content_included: false,
              },
            },
            terminal_eligible: false,
            assistant_answer: false,
            raw_content_included: false,
          },
        ],
        capability_lane_projection_receipts: [
          {
            receipt_ref: "receipt:projection",
            observation_ref: "obs:translation",
            projection_key:
              "document_markdown:docs/research/nhm2.md::fnv1a32:source-text::docs_chunk::es-US::u0001::receipt:projection",
            lane_session_id: "lane-session-docs",
            observation_lane_session_id: "lane-session-docs-observation",
            goal_binding_id: "goal-binding-docs",
            latest_event_id: "lane-session-docs:observation_recorded:300",
            has_observation: true,
            selected_backend_provider: "live_translation.local_runtime",
            projection_target: "docs_chunk",
            source_id: "document_markdown:docs/research/nhm2.md",
            source_hash: "fnv1a32:projection",
            source_kind: "docs",
            source_text_hash: "fnv1a32:source-text",
            source_text_char_count: 2048,
            account_locale: "es-US",
            target_language: "es",
            chunk_id: "u0001",
            chunk_index: 0,
            dedupe_key: "document_markdown:docs/research/nhm2.md:u0001:es",
            source_event_id: "docs:event:1",
            source_event_ms: 250,
            observed_at_ms: 300,
            freshness_status: "fresh",
            terminal_authority_status: "pending_helix_terminal_authority",
            terminal_eligible: false,
            assistant_answer: false,
            raw_content_included: false,
          },
        ],
        capability_lane_session_debug_summaries: [
          {
            lane_session_id: "lane-session-stt",
            lane_id: "speech_to_text",
            session_status: "running",
            session_health: "healthy",
            latest_event_id: "lane-session-stt:record_observation:200",
            has_observation: true,
            last_observation_ref: "obs:stt",
            last_receipt_ref: "stage_play_live_source_mail:stt-debug",
            terminal_eligible: false,
            assistant_answer: false,
            raw_content_included: false,
          },
          {
            lane_session_id: "lane-session-docs",
            lane_id: "live_translation",
            session_status: "running",
            session_health: "healthy",
            latest_event_id: "lane-session-docs:start:150",
            has_observation: false,
            terminal_eligible: false,
            assistant_answer: false,
            raw_content_included: false,
          },
          {
            lane_session_id: "lane-session-tts",
            lane_id: "text_to_speech",
            session_status: "running",
            session_health: "healthy",
            latest_event_id: "lane-session-tts:record_observation:240",
            has_observation: true,
            last_observation_ref: "obs:voice",
            last_receipt_ref: "receipt:voice-playback",
            terminal_eligible: false,
            assistant_answer: false,
            raw_content_included: false,
          },
        ],
        capability_lane_mail_loop_debug_summaries: [
          {
            lane_session_id: "lane-session-docs",
            observation_lane_session_id: "lane-session-docs",
            stage_play_mail_id: "stage-play-mail-docs",
            materialized_mail_loop_evidence: true,
            stage_play_wake_expected: true,
            stage_play_wake_kind: "mailbox_wake",
            terminal_eligible: false,
            assistant_answer: false,
            raw_content_included: false,
          },
        ],
        capability_lane_goal_binding_results: [
          {
            ok: true,
            goal_binding: {
              goal_binding_id: "goal-binding-stt",
              goal_id: "goal:audio-translation-playback",
              lane_session_id: "lane-session-stt",
              lane_id: "speech_to_text",
              terminal_eligible: false,
              assistant_answer: false,
              raw_content_included: false,
            },
            blocked_reason: null,
            terminal_eligible: false,
            assistant_answer: false,
            raw_content_included: false,
          },
          {
            ok: true,
            goal_binding: {
              goal_binding_id: "goal-binding-docs",
              goal_id: "goal:audio-translation-playback",
              lane_session_id: "lane-session-docs",
              lane_id: "live_translation",
              source_id: "document_markdown:docs/research/nhm2.md",
              source_hash: "fnv1a32:goal-docs",
              source_kind: "docs",
              source_text_hash: "fnv1a32:goal-source-text",
              source_text_char_count: 2048,
              projection_target: "docs_chunk",
              account_locale: "es-US",
              target_language: "es",
              latest_chunk_id: "u0001",
              latest_chunk_index: 0,
              latest_dedupe_key: "document_markdown:docs/research/nhm2.md:u0001:es",
              observation_ref: "obs:translation-goal-binding",
              receipt_ref: "receipt:translation-goal-binding",
              terminal_authority_status: "pending_helix_terminal_authority",
              terminal_eligible: false,
              assistant_answer: false,
              raw_content_included: false,
            },
            blocked_reason: null,
            terminal_eligible: false,
            assistant_answer: false,
            raw_content_included: false,
          },
          {
            ok: true,
            goal_binding: {
              goal_binding_id: "goal-binding-tts",
              goal_id: "goal:audio-translation-playback",
              lane_session_id: "lane-session-tts",
              lane_id: "text_to_speech",
              terminal_eligible: false,
              assistant_answer: false,
              raw_content_included: false,
            },
            blocked_reason: null,
            terminal_eligible: false,
            assistant_answer: false,
            raw_content_included: false,
          },
        ],
        capability_lane_goal_binding_debug_summaries: [
          {
            goal_binding_id: "goal-binding-stt",
            goal_id: "goal:audio-translation-playback",
            lane_session_id: "lane-session-stt",
            lane_id: "speech_to_text",
            binding_status: "bound",
            final_reports_require_terminal_authority: true,
            terminal_eligible: false,
            assistant_answer: false,
            raw_content_included: false,
          },
          {
            goal_binding_id: "goal-binding-docs",
            goal_id: "goal:audio-translation-playback",
            lane_session_id: "lane-session-docs",
            lane_id: "live_translation",
            binding_status: "bound",
            source_id: "document_markdown:docs/research/nhm2.md",
            source_hash: "fnv1a32:goal-docs",
            source_kind: "docs",
            source_text_hash: "fnv1a32:goal-source-text",
            source_text_char_count: 2048,
            projection_target: "docs_chunk",
            account_locale: "es-US",
            target_language: "es",
            latest_chunk_id: "u0001",
            latest_chunk_index: 0,
            latest_dedupe_key: "document_markdown:docs/research/nhm2.md:u0001:es",
            observation_ref: "obs:translation-goal-binding",
            receipt_ref: "receipt:translation-goal-binding",
            terminal_authority_status: "pending_helix_terminal_authority",
            final_reports_require_terminal_authority: true,
            terminal_eligible: false,
            assistant_answer: false,
            raw_content_included: false,
          },
          {
            goal_binding_id: "goal-binding-tts",
            goal_id: "goal:audio-translation-playback",
            lane_session_id: "lane-session-tts",
            lane_id: "text_to_speech",
            binding_status: "bound",
            final_reports_require_terminal_authority: true,
            terminal_eligible: false,
            assistant_answer: false,
            raw_content_included: false,
          },
        ],
        capability_lane_goal_dispatch_readiness: {
          next_lane_ids: ["speech_to_text", "live_translation", "text_to_speech"],
          next_lane_session_ids: ["lane-session-stt", "lane-session-docs", "lane-session-tts"],
          next_goal_binding_ids: ["goal-binding-stt", "goal-binding-docs", "goal-binding-tts"],
          terminal_eligible: false,
          assistant_answer: false,
          raw_content_included: false,
        },
        capability_lane_reentry_status: "observation_packet_required_for_provider_reentry",
        runtime_lane_request_loop: {
          status: "lane_observation_reentered",
        },
        debug: {
          turn_id: "turn-debug-lanes",
        },
      },
    );

    const exportPayload = JSON.parse(text) as Record<string, unknown>;
    expect(exportPayload.agent_runtime).toBe("codex");
    expect(exportPayload.selected_agent_provider).toMatchObject({
      id: "codex",
    });
    expect(exportPayload.capability_lane_ids).toEqual(["speech_to_text", "live_translation", "text_to_speech"]);
    expect(exportPayload.capability_lane_call_results).toEqual([
      expect.objectContaining({
        capability: "speech_to_text.transcribe_audio",
        ok: true,
        terminal_eligible: false,
        assistant_answer: false,
      }),
      expect.objectContaining({
        capability: "live_translation.translate_text",
        ok: true,
      }),
      expect.objectContaining({
        capability: "text_to_speech.speak_text",
        ok: true,
        terminal_eligible: false,
        assistant_answer: false,
        receipt: expect.objectContaining({
          playback_status: "started",
        }),
      }),
    ]);
    expect(exportPayload.capability_lane_turn_timeline).toEqual([
      expect.objectContaining({
        stage: "lane_visible",
        lane_id: "live_translation",
        capability_id: "live_translation.translate_text",
        lane_visible: true,
        lane_requested: false,
        terminal_eligible: false,
        assistant_answer: false,
      }),
      expect.objectContaining({
        stage: "lane_observation",
        observation_ref: "obs:translation",
        receipt_ref: "receipt:projection",
        lane_executed: true,
        terminal_authority_status: "pending_helix_terminal_authority",
      }),
      expect.objectContaining({
        stage: "goal_binding",
        lane_id: "speech_to_text",
        observation_ref: "obs:stt",
        receipt_ref: "stage_play_live_source_mail:stt-debug",
        terminal_eligible: false,
        assistant_answer: false,
      }),
      expect.objectContaining({
        stage: "goal_binding",
        lane_id: "live_translation",
        selected_backend_provider: "live_translation.local_runtime",
        goal_id: "goal:audio-translation-playback",
        goal_binding_id: "goal-binding-docs",
        lane_session_id: "lane-session-docs",
        observation_ref: "obs:translation-goal-binding",
        receipt_ref: "receipt:translation-goal-binding",
        mail_loop_ref: "stage_play_live_source_mail:translation-debug",
        materialized_mail_loop_evidence: true,
        dispatch_target: "ask_wake",
        dispatch_admission_status: "eligible_waiting_for_mail_loop",
        dispatch_blocked_reason: null,
        wake_dispatch_allowed: false,
        side_effects_allowed: false,
        source_id: "document_markdown:docs/research/nhm2.md",
        source_hash: "fnv1a32:goal-docs",
        source_kind: "docs",
        source_text_hash: "fnv1a32:goal-source-text",
        source_text_char_count: 2048,
        projection_target: "docs_chunk",
        account_locale: "es-US",
        target_language: "es",
        chunk_id: "u0001",
        chunk_index: 0,
        dedupe_key: "document_markdown:docs/research/nhm2.md:u0001:es",
        session_control_key:
          "lane-session-docs::document_markdown:docs/research/nhm2.md::fnv1a32:goal-docs::docs_chunk::es-US::es",
        source_binding_key:
          "document_markdown:docs/research/nhm2.md::fnv1a32:goal-docs::docs_chunk::es-US::es",
        report_action: "wake_on_salience",
        report_reason: "goal_binding_policy_requests_wake_on_salience",
        report_summary_text:
          "goal lane wake on salience | reason goal_binding_policy_requests_wake_on_salience | evidence obs:translation-goal-binding | mail stage_play_live_source_mail:translation-debug | receipt receipt:translation-goal-binding | terminal authority pending_helix_terminal_authority",
        terminal_authority_status: "pending_helix_terminal_authority",
        terminal_eligible: false,
        assistant_answer: false,
      }),
      expect.objectContaining({
        stage: "goal_binding",
        lane_id: "text_to_speech",
        observation_ref: "obs:voice",
        receipt_ref: "receipt:voice-playback",
        terminal_eligible: false,
        assistant_answer: false,
      }),
      expect.objectContaining({
        stage: "lane_session",
        lane_id: "live_translation",
        status: "paused",
        session_status: "paused",
        session_health: "degraded",
        session_lifecycle_action: "pause",
        latest_event_id: "lane-session-docs:pause:320",
        terminal_authority_status: "not_terminal_authority",
        terminal_eligible: false,
        assistant_answer: false,
      }),
      expect.objectContaining({
        stage: "terminal_selected",
        lane_id: "helix_terminal_authority",
        observation_ref: "obs:translation",
        receipt_ref: "receipt:projection",
        terminal_authority_status: "authorized_by_helix_provider_candidate_bridge",
        observation_reentered: true,
        terminal_eligible: false,
        assistant_answer: false,
      }),
    ]);
    expect(exportPayload.capability_lane_timeline_summary).toMatchObject({
      schema: "helix.capability_lane.timeline_summary.v1",
      event_count: 7,
      stage_sequence: [
        "visible",
        "observed",
        "goal",
        "goal",
        "goal",
        "session",
        "terminal_selected",
      ],
      stage_sequence_text: "visible > observed > goal > goal > goal > session > terminal_selected",
      visible_count: 1,
      requested_count: 0,
      backend_selected_count: 0,
      observed_count: 1,
      receipt_count: 0,
      reentered_count: 0,
      session_count: 1,
      mail_loop_count: 0,
      goal_binding_count: 3,
      goal_dispatch_plan_count: 0,
      goal_dispatch_admission_count: 0,
      goal_dispatch_readiness_count: 0,
      lane_executed_count: 5,
      visible_only_count: 1,
      observation_ref_count: 5,
      receipt_ref_count: 5,
      session_lifecycle_action_count: 2,
      session_control_key_count: 1,
      source_binding_key_count: 1,
      latest_observation_key_count: 1,
      observation_lane_session_id_count: 1,
      observation_reentered_count: 1,
      terminal_selected_count: 1,
      terminal_rejected_count: 0,
      visible_lane_does_not_mean_executed: true,
    });
    expect(exportPayload.capability_lane_timeline_summary.console_state_rows).toHaveLength(7);
    expect(exportPayload.capability_lane_timeline_summary.console_state_rows).toEqual(expect.arrayContaining([
      expect.objectContaining({
        schema: "helix.capability_lane.console_state_row.v1",
        seq: 0,
        stage: "lane_visible",
        normalized_stage: "visible",
        state_label: "visible_only",
        lane_id: "live_translation",
        capability_id: "live_translation.translate_text",
        selected_runtime_agent_provider: "codex",
        selected_backend_provider: "live_translation.local_runtime",
        lane_visible: true,
        lane_requested: false,
        lane_executed: false,
        observation_reentered: false,
        terminal_authority_status: "not_terminal_authority",
        terminal_eligible: false,
        assistant_answer: false,
        raw_content_included: false,
      }),
      expect.objectContaining({
        seq: 1,
        stage: "lane_observation",
        normalized_stage: "observed",
        state_label: "observed_pending_reentry",
        lane_id: "live_translation",
        observation_ref: "obs:translation",
        receipt_ref: "receipt:projection",
        lane_requested: true,
        lane_executed: true,
        observation_reentered: false,
        terminal_authority_status: "pending_helix_terminal_authority",
      }),
      expect.objectContaining({
        seq: 3,
        stage: "goal_binding",
        normalized_stage: "goal",
        state_label: "goal_bound_waiting_for_evidence",
        lane_id: "live_translation",
        goal_id: "goal:audio-translation-playback",
        goal_binding_id: "goal-binding-docs",
        lane_session_id: "lane-session-docs",
        observation_ref: "obs:translation-goal-binding",
        receipt_ref: "receipt:translation-goal-binding",
        mail_loop_ref: "stage_play_live_source_mail:translation-debug",
        materialized_mail_loop_evidence: true,
        dispatch_target: "ask_wake",
        dispatch_admission_status: "eligible_waiting_for_mail_loop",
        dispatch_blocked_reason: null,
        wake_dispatch_allowed: false,
        side_effects_allowed: false,
        report_action: "wake_on_salience",
        report_reason: "goal_binding_policy_requests_wake_on_salience",
        terminal_authority_status: "pending_helix_terminal_authority",
      }),
      expect.objectContaining({
        seq: 5,
        stage: "lane_session",
        normalized_stage: "session",
        state_label: "session_pause",
        lane_id: "live_translation",
        session_status: "paused",
        session_health: "degraded",
        latest_event_id: "lane-session-docs:pause:320",
        terminal_authority_status: "not_terminal_authority",
      }),
      expect.objectContaining({
        seq: 6,
        stage: "terminal_selected",
        normalized_stage: "terminal_selected",
        state_label: "terminal_selected",
        lane_id: "helix_terminal_authority",
        observation_ref: "obs:translation",
        receipt_ref: "receipt:projection",
        observation_reentered: true,
        terminal_authority_status: "authorized_by_helix_provider_candidate_bridge",
      }),
    ]));
    expect(exportPayload.capability_lane_observation_packets).toEqual([
      expect.objectContaining({
        capability_key: "speech_to_text.transcribe_audio",
        status: "succeeded",
        terminal_eligible: false,
        assistant_answer: false,
        state_delta: expect.objectContaining({
          speech_to_text_observation: expect.objectContaining({
            schema: "helix.speech_to_text.observation.v1",
            stage_play_mail_id: "stage_play_live_source_mail:stt-debug",
            terminal_eligible: false,
            assistant_answer: false,
            raw_audio_included: false,
          }),
          speech_to_text_live_source_mail_item: expect.objectContaining({
            sourceKind: "audio_transcript",
            context_role: "tool_evidence",
            terminal_eligible: false,
            assistant_answer: false,
          }),
        }),
      }),
    ]);
    expect(exportPayload.capability_lane_projection_receipts).toEqual([
      expect.objectContaining({
        receipt_ref: "receipt:projection",
        observation_ref: "obs:translation",
        projection_key:
          "document_markdown:docs/research/nhm2.md::fnv1a32:source-text::docs_chunk::es-US::u0001::receipt:projection",
        lane_session_id: "lane-session-docs",
        observation_lane_session_id: "lane-session-docs-observation",
        goal_binding_id: "goal-binding-docs",
        latest_event_id: "lane-session-docs:observation_recorded:300",
        has_observation: true,
        selected_backend_provider: "live_translation.local_runtime",
        projection_target: "docs_chunk",
        source_id: "document_markdown:docs/research/nhm2.md",
        source_hash: "fnv1a32:projection",
        source_kind: "docs",
        source_text_hash: "fnv1a32:source-text",
        source_text_char_count: 2048,
        account_locale: "es-US",
        target_language: "es",
        chunk_id: "u0001",
        chunk_index: 0,
        dedupe_key: "document_markdown:docs/research/nhm2.md:u0001:es",
        source_event_id: "docs:event:1",
        source_event_ms: 250,
        observed_at_ms: 300,
        freshness_status: "fresh",
        terminal_authority_status: "pending_helix_terminal_authority",
        terminal_eligible: false,
        assistant_answer: false,
      }),
    ]);
    expect(exportPayload.capability_lane_session_debug_summaries).toEqual([
      expect.objectContaining({
        lane_session_id: "lane-session-stt",
        lane_id: "speech_to_text",
        session_status: "running",
        latest_event_id: "lane-session-stt:record_observation:200",
        has_observation: true,
        terminal_eligible: false,
        assistant_answer: false,
      }),
      expect.objectContaining({
        lane_session_id: "lane-session-docs",
        lane_id: "live_translation",
        session_status: "running",
        latest_event_id: "lane-session-docs:start:150",
        has_observation: false,
        terminal_eligible: false,
        assistant_answer: false,
      }),
      expect.objectContaining({
        lane_session_id: "lane-session-tts",
        lane_id: "text_to_speech",
        session_status: "running",
        latest_event_id: "lane-session-tts:record_observation:240",
        has_observation: true,
        terminal_eligible: false,
        assistant_answer: false,
      }),
    ]);
    expect(exportPayload.capability_lane_mail_loop_debug_summaries).toEqual([
      expect.objectContaining({
        stage_play_mail_id: "stage-play-mail-docs",
        observation_lane_session_id: "lane-session-docs",
        materialized_mail_loop_evidence: true,
        stage_play_wake_expected: true,
        stage_play_wake_kind: "mailbox_wake",
        terminal_eligible: false,
        assistant_answer: false,
      }),
    ]);
    expect(exportPayload.capability_lane_goal_binding_results).toEqual([
      expect.objectContaining({
        ok: true,
        goal_binding: expect.objectContaining({
          goal_binding_id: "goal-binding-stt",
          goal_id: "goal:audio-translation-playback",
          lane_session_id: "lane-session-stt",
          lane_id: "speech_to_text",
        }),
        terminal_eligible: false,
        assistant_answer: false,
      }),
      expect.objectContaining({
        ok: true,
        goal_binding: expect.objectContaining({
          goal_binding_id: "goal-binding-docs",
          goal_id: "goal:audio-translation-playback",
          lane_session_id: "lane-session-docs",
          lane_id: "live_translation",
          source_id: "document_markdown:docs/research/nhm2.md",
          source_hash: "fnv1a32:goal-docs",
          source_kind: "docs",
          source_text_hash: "fnv1a32:goal-source-text",
          source_text_char_count: 2048,
          projection_target: "docs_chunk",
          account_locale: "es-US",
          target_language: "es",
          latest_chunk_id: "u0001",
          latest_chunk_index: 0,
          latest_dedupe_key: "document_markdown:docs/research/nhm2.md:u0001:es",
          observation_ref: "obs:translation-goal-binding",
          receipt_ref: "receipt:translation-goal-binding",
          terminal_authority_status: "pending_helix_terminal_authority",
        }),
        terminal_eligible: false,
        assistant_answer: false,
      }),
      expect.objectContaining({
        ok: true,
        goal_binding: expect.objectContaining({
          goal_binding_id: "goal-binding-tts",
          goal_id: "goal:audio-translation-playback",
          lane_session_id: "lane-session-tts",
          lane_id: "text_to_speech",
        }),
        terminal_eligible: false,
        assistant_answer: false,
      }),
    ]);
    expect(exportPayload.capability_lane_goal_binding_debug_summaries).toEqual([
      expect.objectContaining({
        goal_binding_id: "goal-binding-stt",
        lane_id: "speech_to_text",
        binding_status: "bound",
        final_reports_require_terminal_authority: true,
        terminal_eligible: false,
        assistant_answer: false,
      }),
      expect.objectContaining({
        goal_binding_id: "goal-binding-docs",
        lane_id: "live_translation",
        binding_status: "bound",
        source_id: "document_markdown:docs/research/nhm2.md",
        source_hash: "fnv1a32:goal-docs",
        source_kind: "docs",
        source_text_hash: "fnv1a32:goal-source-text",
        source_text_char_count: 2048,
        projection_target: "docs_chunk",
        account_locale: "es-US",
        target_language: "es",
        latest_chunk_id: "u0001",
        latest_chunk_index: 0,
        latest_dedupe_key: "document_markdown:docs/research/nhm2.md:u0001:es",
        observation_ref: "obs:translation-goal-binding",
        receipt_ref: "receipt:translation-goal-binding",
        terminal_authority_status: "pending_helix_terminal_authority",
        final_reports_require_terminal_authority: true,
        terminal_eligible: false,
        assistant_answer: false,
      }),
      expect.objectContaining({
        goal_binding_id: "goal-binding-tts",
        lane_id: "text_to_speech",
        binding_status: "bound",
        final_reports_require_terminal_authority: true,
        terminal_eligible: false,
        assistant_answer: false,
      }),
    ]);
    expect(exportPayload.capability_lane_goal_dispatch_readiness).toMatchObject({
      next_lane_ids: ["speech_to_text", "live_translation", "text_to_speech"],
      next_lane_session_ids: ["lane-session-stt", "lane-session-docs", "lane-session-tts"],
      next_goal_binding_ids: ["goal-binding-stt", "goal-binding-docs", "goal-binding-tts"],
    });
    expect(exportPayload.runtime_lane_request_loop).toMatchObject({
      status: "lane_observation_reentered",
    });
  });

  it("derives mail-loop evidence from goal-binding summaries when explicit mail-loop summaries are absent", () => {
    const text = buildHelixDebugExportEnvelopeFromMasterPayload(
      {
        id: "turn-debug-derived-mail",
        question: "keep translating the document",
        content: "Translation lane is active.",
      },
      {
        selected_final_answer: "Translation lane is active.",
        agent_runtime: "codex",
        capability_lane_goal_binding_debug_summaries: [
          {
            goal_binding_id: "goal-binding-docs",
            goal_id: "goal:account-language",
            lane_session_id: "lane-session-docs",
            lane_id: "live_translation",
            binding_status: "bound",
            latest_mail_loop_summary: {
              schema: "helix.capability_lane.mail_loop_debug_summary.v1",
              lane_session_id: "lane-session-docs",
              lane_id: "live_translation",
              capability: "live_translation.translate_text",
              stage_play_mail_id: "stage-play-mail-derived",
              stage_play_wake_expected: true,
              observation_ref: "ask:lane:translation:derived-obs",
              terminal_eligible: false,
              assistant_answer: false,
              raw_content_included: false,
            },
            terminal_eligible: false,
            assistant_answer: false,
            raw_content_included: false,
          },
        ],
        debug: {
          turn_id: "turn-debug-derived-mail",
        },
      },
    );

    const exportPayload = JSON.parse(text) as Record<string, unknown>;
    expect(exportPayload.capability_lane_mail_loop_debug_summaries).toEqual([
      expect.objectContaining({
        schema: "helix.capability_lane.mail_loop_debug_summary.v1",
        lane_session_id: "lane-session-docs",
        stage_play_mail_id: "stage-play-mail-derived",
        stage_play_wake_expected: true,
        stage_play_wake_kind: "mailbox_wake",
        observation_ref: "ask:lane:translation:derived-obs",
        terminal_eligible: false,
        assistant_answer: false,
        raw_content_included: false,
      }),
    ]);
  });
});
