import { describe, expect, it } from "vitest";
import { buildCapabilityLaneDebugExportFields } from "../capability-lane-debug-export";

describe("capability lane debug export fields", () => {
  it("projects lane lifecycle and runtime request fields from payload", () => {
    const fields = buildCapabilityLaneDebugExportFields({
      capability_lane_manifest: {
        schema: "helix.capability_lane_manifest.v1",
        lane_ids: ["live_translation"],
      },
      model_visible_capability_lane_manifest: {
        schema: "helix.agent_model_visible_capability_lane_manifest.v1",
        lanes: [
          {
            lane_id: "live_translation",
            status: "dry_run",
          },
        ],
      },
      capability_lane_call_results: [
        {
          capability: "live_translation.translate_text",
          ok: true,
        },
      ],
      capability_lane_backend_selections: [
        {
          selected_backend_provider: "live_translation.local_runtime",
        },
      ],
      capability_lane_turn_timeline: [
        {
          schema: "helix.capability_lane.provider_timeline_event.v1",
          stage: "lane_visible",
          lane_id: "live_translation",
          capability_id: "live_translation.translate_text",
          lane_visible: true,
          lane_requested: false,
          lane_executed: false,
          observation_reentered: false,
          terminal_authority_status: "not_terminal_authority",
          terminal_eligible: false,
          assistant_answer: false,
          raw_content_included: false,
        },
        {
          schema: "helix.capability_lane.provider_timeline_event.v1",
          stage: "lane_observation",
          lane_id: "live_translation",
          capability_id: "live_translation.translate_text",
          lane_visible: false,
          lane_requested: true,
          lane_executed: true,
          observation_reentered: false,
          observation_ref: "obs:translation",
          receipt_ref: "receipt:translation",
          observation_lane_session_id: "lane-session-docs-observation",
          terminal_authority_status: "pending_helix_terminal_authority",
          terminal_eligible: false,
          assistant_answer: false,
          raw_content_included: false,
        },
        {
          schema: "helix.capability_lane.provider_timeline_event.v1",
          stage: "lane_session",
          lane_id: "live_translation",
          capability_id: null,
          status: "paused",
          lane_visible: false,
          lane_requested: true,
          lane_executed: false,
          observation_reentered: false,
          selected_backend_provider: "live_translation.local_runtime",
          observation_ref: null,
          receipt_ref: null,
          session_status: "paused",
          session_health: "degraded",
          lifecycle_action: "pause",
          session_lifecycle_action: "pause",
          session_action: "pause",
          latest_event_id: "lane-session-docs:pause:320",
          terminal_authority_status: "not_terminal_authority",
          terminal_eligible: false,
          assistant_answer: false,
          raw_content_included: false,
        },
        {
          schema: "helix.capability_lane.provider_timeline_event.v1",
          stage: "goal_binding",
          lane_id: "live_translation",
          capability_id: "live_translation.translate_text",
          goal_id: "goal:account-language",
          goal_binding_id: "goal-binding-debug",
          lane_session_id: "lane-session-docs",
          lane_visible: false,
          lane_requested: true,
          lane_executed: true,
          observation_reentered: true,
          observation_ref: "obs:translation-goal-binding",
          receipt_ref: "receipt:translation-goal-binding",
          mail_loop_ref: "stage_play_live_source_mail:translation-debug",
          materialized_mail_loop_evidence: true,
          dispatch_target: "ask_wake",
          dispatch_admission_status: "eligible_waiting_for_mail_loop",
          dispatch_blocked_reason: null,
          wake_dispatch_allowed: false,
          side_effects_allowed: false,
          report_action: "wake_on_salience",
          report_reason: "goal_binding_policy_requests_wake_on_salience",
          report_summary_text:
            "goal lane wake on salience | reason goal_binding_policy_requests_wake_on_salience | evidence obs:translation-goal-binding | mail stage_play_live_source_mail:translation-debug | receipt receipt:translation-goal-binding | terminal authority pending_helix_terminal_authority",
          session_lifecycle_action: "record_observation",
          session_control_key:
            "lane-session-docs::document_markdown:docs/research/nhm2.md::fnv1a32:goal-docs::docs_chunk::es-US::es",
          source_binding_key:
            "document_markdown:docs/research/nhm2.md::fnv1a32:goal-docs::docs_chunk::es-US::es",
          latest_observation_key:
            "document_markdown:docs/research/nhm2.md::fnv1a32:goal-docs::docs_chunk::es::u0001::receipt:translation",
          terminal_authority_status: "pending_helix_terminal_authority",
          terminal_eligible: false,
          assistant_answer: false,
          raw_content_included: false,
        },
      ],
      capability_lane_projection_receipts: [
        {
          receipt_ref: "receipt:translation",
          observation_ref: "obs:translation",
          projection_key:
            "document_markdown:docs/research/nhm2.md::fnv1a32:source-text::docs_chunk::es-US::u0001::receipt:translation",
          lane_session_id: "lane-session-docs",
          observation_lane_session_id: "lane-session-docs-observation",
          goal_binding_id: "goal-binding-docs",
          latest_event_id: "lane-session-docs:observation_recorded:300",
          has_observation: true,
          selected_backend_provider: "live_translation.local_runtime",
          projection_target: "docs_chunk",
          source_id: "document_markdown:docs/research/nhm2.md",
          source_hash: "fnv1a32:projection",
          source_kind: "docs",
          source_text_hash: "fnv1a32:source-text",
          source_text_char_count: 2048,
          account_locale: "es-US",
          target_language: "es",
          chunk_id: "u0001",
          chunk_index: 0,
          dedupe_key: "document_markdown:docs/research/nhm2.md:u0001:es",
          source_event_id: "docs:event:1",
          source_event_ms: 250,
          observed_at_ms: 300,
          freshness_status: "fresh",
          terminal_authority_status: "pending_helix_terminal_authority",
          terminal_eligible: false,
          assistant_answer: false,
          raw_content_included: false,
        },
      ],
      capability_lane_goal_binding_results: [
        {
          ok: true,
          goal_binding: {
            goal_binding_id: "goal-binding-debug",
          },
          terminal_eligible: false,
          assistant_answer: false,
          raw_content_included: false,
        },
      ],
      runtime_lane_request_contract: {
        schema: "helix.runtime_agent_lane_request_contract.v1",
        legacy_schema: "helix.codex_runtime_lane_request_contract.v1",
        runtime_provider_adapter: "codex",
        execution_status: "lane_observation_reentered",
      },
      runtime_lane_request_loop: {
        schema: "helix.runtime_agent_lane_request_loop.v1",
        legacy_schema: "helix.codex_runtime_lane_request_loop.v1",
        runtime_provider_adapter: "codex",
        status: "lane_observation_reentered",
      },
    });

    expect(fields).toMatchObject({
      capability_lane_manifest: {
        schema: "helix.capability_lane_manifest.v1",
        lane_ids: ["live_translation"],
      },
      model_visible_capability_lane_manifest: {
        schema: "helix.agent_model_visible_capability_lane_manifest.v1",
        lanes: [
          {
            lane_id: "live_translation",
            status: "dry_run",
          },
        ],
      },
      capability_lane_call_results: [
        {
          capability: "live_translation.translate_text",
          ok: true,
        },
      ],
      capability_lane_backend_selections: [
        {
          selected_backend_provider: "live_translation.local_runtime",
        },
      ],
      capability_lane_turn_timeline: [
        expect.objectContaining({
          stage: "lane_visible",
          lane_id: "live_translation",
          lane_visible: true,
          lane_requested: false,
          lane_executed: false,
          observation_reentered: false,
          terminal_authority_status: "not_terminal_authority",
          terminal_eligible: false,
          assistant_answer: false,
        }),
        expect.objectContaining({
          stage: "lane_observation",
          lane_id: "live_translation",
          lane_requested: true,
          lane_executed: true,
          observation_ref: "obs:translation",
          receipt_ref: "receipt:translation",
          terminal_authority_status: "pending_helix_terminal_authority",
          terminal_eligible: false,
          assistant_answer: false,
        }),
        expect.objectContaining({
          stage: "lane_session",
          lane_id: "live_translation",
          status: "paused",
          session_status: "paused",
          session_health: "degraded",
          session_lifecycle_action: "pause",
          latest_event_id: "lane-session-docs:pause:320",
          terminal_authority_status: "not_terminal_authority",
          terminal_eligible: false,
          assistant_answer: false,
        }),
        expect.objectContaining({
          stage: "goal_binding",
          lane_id: "live_translation",
          goal_id: "goal:account-language",
          goal_binding_id: "goal-binding-debug",
          lane_session_id: "lane-session-docs",
          observation_ref: "obs:translation-goal-binding",
          receipt_ref: "receipt:translation-goal-binding",
          mail_loop_ref: "stage_play_live_source_mail:translation-debug",
          materialized_mail_loop_evidence: true,
          dispatch_target: "ask_wake",
          dispatch_admission_status: "eligible_waiting_for_mail_loop",
          wake_dispatch_allowed: false,
          side_effects_allowed: false,
          report_action: "wake_on_salience",
          report_reason: "goal_binding_policy_requests_wake_on_salience",
          report_summary_text:
            "goal lane wake on salience | reason goal_binding_policy_requests_wake_on_salience | evidence obs:translation-goal-binding | mail stage_play_live_source_mail:translation-debug | receipt receipt:translation-goal-binding | terminal authority pending_helix_terminal_authority",
          terminal_authority_status: "pending_helix_terminal_authority",
          terminal_eligible: false,
          assistant_answer: false,
        }),
      ],
      capability_lane_timeline_summary: {
        schema: "helix.capability_lane.timeline_summary.v1",
        event_count: 4,
        stage_sequence: ["visible", "observed", "session", "goal"],
        stage_sequence_text: "visible > observed > session > goal",
        visible_count: 1,
        requested_count: 0,
        backend_selected_count: 0,
        observed_count: 1,
        receipt_count: 0,
        reentered_count: 0,
        session_count: 1,
        mail_loop_count: 0,
        goal_binding_count: 1,
        goal_dispatch_plan_count: 0,
        goal_dispatch_admission_count: 0,
        goal_dispatch_readiness_count: 0,
        lane_executed_count: 2,
        visible_only_count: 1,
        observation_ref_count: 2,
        receipt_ref_count: 2,
        session_lifecycle_action_count: 2,
        session_control_key_count: 1,
        source_binding_key_count: 1,
        latest_observation_key_count: 1,
        observation_lane_session_id_count: 1,
        observation_reentered_count: 1,
        terminal_selected_count: 0,
        terminal_rejected_count: 0,
        visible_lane_does_not_mean_executed: true,
      },
      capability_lane_projection_receipts: [
        {
          receipt_ref: "receipt:translation",
          observation_ref: "obs:translation",
          projection_key:
            "document_markdown:docs/research/nhm2.md::fnv1a32:source-text::docs_chunk::es-US::u0001::receipt:translation",
          lane_session_id: "lane-session-docs",
          observation_lane_session_id: "lane-session-docs-observation",
          goal_binding_id: "goal-binding-docs",
          latest_event_id: "lane-session-docs:observation_recorded:300",
          has_observation: true,
          selected_backend_provider: "live_translation.local_runtime",
          projection_target: "docs_chunk",
          source_id: "document_markdown:docs/research/nhm2.md",
          source_hash: "fnv1a32:projection",
          source_kind: "docs",
          source_text_hash: "fnv1a32:source-text",
          source_text_char_count: 2048,
          account_locale: "es-US",
          target_language: "es",
          chunk_id: "u0001",
          chunk_index: 0,
          dedupe_key: "document_markdown:docs/research/nhm2.md:u0001:es",
          source_event_id: "docs:event:1",
          source_event_ms: 250,
          observed_at_ms: 300,
          freshness_status: "fresh",
          terminal_authority_status: "pending_helix_terminal_authority",
          terminal_eligible: false,
          assistant_answer: false,
          raw_content_included: false,
        },
      ],
      capability_lane_goal_binding_results: [
        {
          ok: true,
          goal_binding: {
            goal_binding_id: "goal-binding-debug",
          },
          terminal_eligible: false,
          assistant_answer: false,
          raw_content_included: false,
        },
      ],
      runtime_lane_request_contract: {
        execution_status: "lane_observation_reentered",
      },
      runtime_lane_request_loop: {
        status: "lane_observation_reentered",
      },
    });
    expect(fields.capability_lane_timeline_summary.console_state_rows).toEqual(expect.arrayContaining([
      expect.objectContaining({
        schema: "helix.capability_lane.console_state_row.v1",
        seq: 0,
        stage: "lane_visible",
        normalized_stage: "visible",
        state_label: "visible_only",
        lane_id: "live_translation",
        capability_id: "live_translation.translate_text",
        lane_visible: true,
        lane_requested: false,
        lane_executed: false,
        observation_reentered: false,
        terminal_authority_status: "not_terminal_authority",
        terminal_eligible: false,
        assistant_answer: false,
        raw_content_included: false,
      }),
      expect.objectContaining({
        seq: 1,
        stage: "lane_observation",
        normalized_stage: "observed",
        state_label: "observed_pending_reentry",
        lane_id: "live_translation",
        observation_ref: "obs:translation",
        receipt_ref: "receipt:translation",
        lane_requested: true,
        lane_executed: true,
        observation_reentered: false,
        terminal_authority_status: "pending_helix_terminal_authority",
        terminal_eligible: false,
        assistant_answer: false,
        raw_content_included: false,
      }),
      expect.objectContaining({
        seq: 2,
        stage: "lane_session",
        normalized_stage: "session",
        state_label: "session_pause",
        lane_id: "live_translation",
        session_status: "paused",
        session_health: "degraded",
        latest_event_id: "lane-session-docs:pause:320",
        terminal_authority_status: "not_terminal_authority",
        terminal_eligible: false,
        assistant_answer: false,
        raw_content_included: false,
      }),
      expect.objectContaining({
        seq: 3,
        stage: "goal_binding",
        normalized_stage: "goal",
        state_label: "goal_bound_with_evidence",
        lane_id: "live_translation",
        goal_id: "goal:account-language",
        goal_binding_id: "goal-binding-debug",
        lane_session_id: "lane-session-docs",
        observation_ref: "obs:translation-goal-binding",
        receipt_ref: "receipt:translation-goal-binding",
        mail_loop_ref: "stage_play_live_source_mail:translation-debug",
        materialized_mail_loop_evidence: true,
        dispatch_target: "ask_wake",
        dispatch_admission_status: "eligible_waiting_for_mail_loop",
        dispatch_blocked_reason: null,
        wake_dispatch_allowed: false,
        side_effects_allowed: false,
        report_action: "wake_on_salience",
        report_reason: "goal_binding_policy_requests_wake_on_salience",
        terminal_authority_status: "pending_helix_terminal_authority",
        terminal_eligible: false,
        assistant_answer: false,
        raw_content_included: false,
      }),
    ]));
  });

  it("falls back to nested debug fields when payload-level fields are absent", () => {
    const fields = buildCapabilityLaneDebugExportFields({
      debug: {
        model_visible_capability_lane_manifest: {
          schema: "helix.agent_model_visible_capability_lane_manifest.v1",
          lanes: [
            {
              lane_id: "utility_text",
              status: "available",
            },
          ],
        },
        capability_lane_observation_packets: [
          {
            capability_key: "live_translation.translate_text",
          },
        ],
        capability_lane_goal_binding_results: [
          {
            ok: false,
            blocked_reason: "unknown_lane_session",
          },
        ],
        capability_lane_reentry_status: "observation_packet_required_for_provider_reentry",
        runtime_lane_request_retry: {
          status: "runtime_provider_emitted_lane_request",
        },
      },
    });

    expect(fields).toMatchObject({
      model_visible_capability_lane_manifest: {
        schema: "helix.agent_model_visible_capability_lane_manifest.v1",
        lanes: [
          {
            lane_id: "utility_text",
            status: "available",
          },
        ],
      },
      capability_lane_observation_packets: [
        {
          capability_key: "live_translation.translate_text",
        },
      ],
      capability_lane_goal_binding_results: [
        {
          ok: false,
          blocked_reason: "unknown_lane_session",
        },
      ],
      capability_lane_reentry_status: "observation_packet_required_for_provider_reentry",
      runtime_lane_request_retry: {
        status: "runtime_provider_emitted_lane_request",
      },
    });
  });

  it("derives mail-loop debug summaries from goal-binding summaries when explicit summaries are absent", () => {
    const fields = buildCapabilityLaneDebugExportFields({
      debug: {
        capability_lane_goal_binding_debug_summaries: [
          {
            schema: "helix.capability_lane.goal_binding_debug_summary.v1",
            goal_binding_id: "goal-binding-debug",
            latest_mail_loop_summary: {
              schema: "helix.capability_lane.mail_loop_debug_summary.v1",
              lane_session_id: "lane-session-debug",
              packet_count: 2,
              stage_play_wake_expected: true,
              terminal_eligible: false,
              assistant_answer: false,
            },
          },
        ],
      },
    });

    expect(fields.capability_lane_mail_loop_debug_summaries).toEqual([
      {
        schema: "helix.capability_lane.mail_loop_debug_summary.v1",
        lane_session_id: "lane-session-debug",
        packet_count: 2,
        stage_play_wake_expected: true,
        stage_play_wake_kind: "mailbox_wake",
        terminal_eligible: false,
        assistant_answer: false,
      },
    ]);
  });

  it("preserves speech-to-text packets, text-to-speech receipts, and goal-bound audio lane sessions", () => {
    const fields = buildCapabilityLaneDebugExportFields({
      debug: {
        capability_lane_call_results: [
          {
            capability: "speech_to_text.transcribe_audio",
            ok: true,
            terminal_eligible: false,
            assistant_answer: false,
            raw_audio_included: false,
          },
          {
            capability: "text_to_speech.speak_text",
            ok: true,
            receipt: {
              playback_status: "started",
              assistant_answer: false,
              terminal_eligible: false,
            },
            terminal_eligible: false,
            assistant_answer: false,
          },
        ],
        capability_lane_observation_packets: [
          {
            schema: "helix.agent_step_observation_packet.v1",
            capability_key: "speech_to_text.transcribe_audio",
            status: "succeeded",
            state_delta: {
              speech_to_text_observation: {
                schema: "helix.speech_to_text.observation.v1",
                observation_ref: "obs:stt",
                stage_play_mail_id: "stage_play_live_source_mail:stt-debug",
                transcript_hash: "hash:stt",
                raw_audio_included: false,
                terminal_eligible: false,
                assistant_answer: false,
              },
              speech_to_text_live_source_mail_item: {
                mailId: "stage_play_live_source_mail:stt-debug",
                sourceKind: "audio_transcript",
                context_role: "tool_evidence",
                terminal_eligible: false,
                assistant_answer: false,
                raw_content_included: false,
              },
            },
            terminal_eligible: false,
            assistant_answer: false,
            raw_content_included: false,
          },
          {
            schema: "helix.agent_step_observation_packet.v1",
            capability_key: "text_to_speech.speak_text",
            status: "succeeded",
            state_delta: {
              text_to_speech_receipt: {
                schema: "helix.text_to_speech.receipt.v1",
                receipt_ref: "receipt:voice",
                playback_status: "started",
                assistant_answer: false,
                terminal_eligible: false,
              },
            },
            terminal_eligible: false,
            assistant_answer: false,
            raw_content_included: false,
          },
        ],
        capability_lane_session_debug_summaries: [
          {
            lane_session_id: "lane-session-stt",
            lane_id: "speech_to_text",
            session_status: "running",
            latest_event_id: "lane-session-stt:record_observation:200",
            has_observation: true,
            last_observation_ref: "obs:stt",
            last_receipt_ref: "stage_play_live_source_mail:stt-debug",
            terminal_eligible: false,
            assistant_answer: false,
          },
          {
            lane_session_id: "lane-session-tts",
            lane_id: "text_to_speech",
            session_status: "running",
            latest_event_id: "lane-session-tts:record_observation:240",
            has_observation: true,
            last_observation_ref: "obs:voice",
            last_receipt_ref: "receipt:voice",
            terminal_eligible: false,
            assistant_answer: false,
          },
          {
            lane_session_id: "lane-session-docs",
            lane_id: "live_translation",
            session_status: "running",
            latest_event_id: "lane-session-docs:record_observation:220",
            has_observation: true,
            last_observation_ref: "obs:translation-goal-binding",
            last_receipt_ref: "receipt:translation-goal-binding",
            source_id: "document_markdown:docs/research/nhm2.md",
            source_hash: "fnv1a32:goal-docs",
            source_kind: "docs",
            projection_target: "docs_chunk",
            account_locale: "es-US",
            target_language: "es",
            latest_chunk_id: "u0001",
            latest_chunk_index: 0,
            latest_dedupe_key: "document_markdown:docs/research/nhm2.md:u0001:es",
            terminal_authority_status: "pending_helix_terminal_authority",
            terminal_eligible: false,
            assistant_answer: false,
          },
        ],
        capability_lane_goal_binding_debug_summaries: [
          {
            goal_binding_id: "goal-binding-stt",
            goal_id: "goal:audio-translation-playback",
            lane_session_id: "lane-session-stt",
            lane_id: "speech_to_text",
            binding_status: "bound",
            latest_event_id: "lane-session-stt:record_observation:200",
            session_event_count: 2,
            has_observation: true,
            final_reports_require_terminal_authority: true,
            terminal_eligible: false,
            assistant_answer: false,
          },
          {
            goal_binding_id: "goal-binding-tts",
            goal_id: "goal:audio-translation-playback",
            lane_session_id: "lane-session-tts",
            lane_id: "text_to_speech",
            binding_status: "bound",
            latest_event_id: "lane-session-tts:record_observation:240",
            session_event_count: 2,
            has_observation: true,
            final_reports_require_terminal_authority: true,
            terminal_eligible: false,
            assistant_answer: false,
          },
          {
            goal_binding_id: "goal-binding-docs",
            goal_id: "goal:audio-translation-playback",
            lane_session_id: "lane-session-docs",
            lane_id: "live_translation",
            binding_status: "bound",
            latest_event_id: "lane-session-docs:record_observation:220",
            session_event_count: 2,
            has_observation: true,
            source_id: "document_markdown:docs/research/nhm2.md",
            source_hash: "fnv1a32:goal-docs",
            source_kind: "docs",
            projection_target: "docs_chunk",
            account_locale: "es-US",
            target_language: "es",
            latest_chunk_id: "u0001",
            latest_chunk_index: 0,
            latest_dedupe_key: "document_markdown:docs/research/nhm2.md:u0001:es",
            observation_ref: "obs:translation-goal-binding",
            receipt_ref: "receipt:translation-goal-binding",
            terminal_authority_status: "pending_helix_terminal_authority",
            final_reports_require_terminal_authority: true,
            terminal_eligible: false,
            assistant_answer: false,
          },
        ],
        capability_lane_goal_dispatch_readiness: {
          next_lane_ids: ["speech_to_text", "text_to_speech", "live_translation"],
          next_lane_session_ids: ["lane-session-stt", "lane-session-tts", "lane-session-docs"],
          next_goal_binding_ids: ["goal-binding-stt", "goal-binding-tts", "goal-binding-docs"],
          next_latest_event_ids: [
            "lane-session-stt:record_observation:200",
            "lane-session-tts:record_observation:240",
            "lane-session-docs:record_observation:220",
          ],
          next_session_event_counts: [2],
          next_has_observation: true,
          all_next_have_observation: true,
          terminal_eligible: false,
          assistant_answer: false,
        },
      },
    });

    expect(fields.capability_lane_call_results).toEqual([
      expect.objectContaining({
        capability: "speech_to_text.transcribe_audio",
        ok: true,
        terminal_eligible: false,
        assistant_answer: false,
        raw_audio_included: false,
      }),
      expect.objectContaining({
        capability: "text_to_speech.speak_text",
        ok: true,
        receipt: expect.objectContaining({
          playback_status: "started",
          terminal_eligible: false,
          assistant_answer: false,
        }),
        terminal_eligible: false,
        assistant_answer: false,
      }),
    ]);
    expect(fields.capability_lane_observation_packets).toEqual([
      expect.objectContaining({
        capability_key: "speech_to_text.transcribe_audio",
        state_delta: expect.objectContaining({
          speech_to_text_observation: expect.objectContaining({
            observation_ref: "obs:stt",
            stage_play_mail_id: "stage_play_live_source_mail:stt-debug",
            raw_audio_included: false,
            terminal_eligible: false,
            assistant_answer: false,
          }),
          speech_to_text_live_source_mail_item: expect.objectContaining({
            mailId: "stage_play_live_source_mail:stt-debug",
            sourceKind: "audio_transcript",
            context_role: "tool_evidence",
            terminal_eligible: false,
            assistant_answer: false,
          }),
        }),
      }),
      expect.objectContaining({
        capability_key: "text_to_speech.speak_text",
        state_delta: expect.objectContaining({
          text_to_speech_receipt: expect.objectContaining({
            receipt_ref: "receipt:voice",
            playback_status: "started",
            terminal_eligible: false,
            assistant_answer: false,
          }),
        }),
      }),
    ]);
    expect(fields.capability_lane_session_debug_summaries).toEqual([
      expect.objectContaining({
        lane_session_id: "lane-session-stt",
        lane_id: "speech_to_text",
        latest_event_id: "lane-session-stt:record_observation:200",
        has_observation: true,
        last_observation_ref: "obs:stt",
        last_receipt_ref: "stage_play_live_source_mail:stt-debug",
        terminal_eligible: false,
        assistant_answer: false,
      }),
      expect.objectContaining({
        lane_session_id: "lane-session-tts",
        lane_id: "text_to_speech",
        latest_event_id: "lane-session-tts:record_observation:240",
        has_observation: true,
        last_observation_ref: "obs:voice",
        last_receipt_ref: "receipt:voice",
        terminal_eligible: false,
        assistant_answer: false,
      }),
      expect.objectContaining({
        lane_session_id: "lane-session-docs",
        lane_id: "live_translation",
        latest_event_id: "lane-session-docs:record_observation:220",
        has_observation: true,
        last_observation_ref: "obs:translation-goal-binding",
        last_receipt_ref: "receipt:translation-goal-binding",
        source_id: "document_markdown:docs/research/nhm2.md",
        source_hash: "fnv1a32:goal-docs",
        source_kind: "docs",
        projection_target: "docs_chunk",
        account_locale: "es-US",
        target_language: "es",
        latest_chunk_id: "u0001",
        latest_chunk_index: 0,
        latest_dedupe_key: "document_markdown:docs/research/nhm2.md:u0001:es",
        terminal_authority_status: "pending_helix_terminal_authority",
        terminal_eligible: false,
        assistant_answer: false,
      }),
    ]);
    expect(fields.capability_lane_goal_binding_debug_summaries).toEqual([
      expect.objectContaining({
        goal_binding_id: "goal-binding-stt",
        goal_id: "goal:audio-translation-playback",
        lane_id: "speech_to_text",
        latest_event_id: "lane-session-stt:record_observation:200",
        session_event_count: 2,
        has_observation: true,
        final_reports_require_terminal_authority: true,
      }),
      expect.objectContaining({
        goal_binding_id: "goal-binding-tts",
        goal_id: "goal:audio-translation-playback",
        lane_id: "text_to_speech",
        latest_event_id: "lane-session-tts:record_observation:240",
        session_event_count: 2,
        has_observation: true,
        final_reports_require_terminal_authority: true,
      }),
      expect.objectContaining({
        goal_binding_id: "goal-binding-docs",
        goal_id: "goal:audio-translation-playback",
        lane_id: "live_translation",
        latest_event_id: "lane-session-docs:record_observation:220",
        session_event_count: 2,
        has_observation: true,
        source_id: "document_markdown:docs/research/nhm2.md",
        source_hash: "fnv1a32:goal-docs",
        source_kind: "docs",
        projection_target: "docs_chunk",
        account_locale: "es-US",
        target_language: "es",
        latest_chunk_id: "u0001",
        latest_chunk_index: 0,
        latest_dedupe_key: "document_markdown:docs/research/nhm2.md:u0001:es",
        observation_ref: "obs:translation-goal-binding",
        receipt_ref: "receipt:translation-goal-binding",
        terminal_authority_status: "pending_helix_terminal_authority",
        final_reports_require_terminal_authority: true,
      }),
    ]);
    expect(fields.capability_lane_goal_dispatch_readiness).toMatchObject({
      next_lane_ids: ["speech_to_text", "text_to_speech", "live_translation"],
      next_lane_session_ids: ["lane-session-stt", "lane-session-tts", "lane-session-docs"],
      next_goal_binding_ids: ["goal-binding-stt", "goal-binding-tts", "goal-binding-docs"],
      next_latest_event_ids: [
        "lane-session-stt:record_observation:200",
        "lane-session-tts:record_observation:240",
        "lane-session-docs:record_observation:220",
      ],
      next_session_event_counts: [2],
      next_has_observation: true,
      all_next_have_observation: true,
      terminal_eligible: false,
      assistant_answer: false,
    });
  });
});
