import { describe, expect, it } from "vitest";
import { createHelixAskLiveDebugSlimBuilder } from "../live-debug-slim";

const buildSlimDebug = createHelixAskLiveDebugSlimBuilder({
  asDebugExportRecord: (value) =>
    value && typeof value === "object" && !Array.isArray(value)
      ? (value as Record<string, unknown>)
      : null,
  buildDebugExportMandatoryNextTool: () => null,
  buildDebugExportPhaseControllerTrajectory: () => ({
    schema: "helix.phase_controller_trajectory.v1",
  }),
  buildDebugExportEvidenceReentryProof: () => ({
    schema: "helix.evidence_reentry_proof.v1",
  }),
});

describe("Helix Ask live debug slim", () => {
  it("preserves runtime-provider adapter and capability lane projection fields", () => {
    const slim = buildSlimDebug({
      agent_runtime: "codex",
      agent_runtime_adapter_contract: {
        schema: "helix.agent_runtime_adapter_contract.v1",
      },
      capability_lane_manifest: {
        schema: "helix.capability_lane_manifest.v1",
      },
      model_visible_capability_lane_manifest: {
        schema: "helix.agent_model_visible_capability_lane_manifest.v1",
        lanes: [
          {
            lane_id: "live_translation",
            status: "dry_run",
          },
        ],
      },
      capability_lane_ids: ["utility_text", "workstation_tool_reference"],
      capability_lane_statuses: {
        utility_text: "available",
        workstation_tool_reference: "available",
      },
      capability_lane_resolve_trace_shape: {
        schema: "helix.capability_lane_resolve_trace.v1",
      },
      capability_lane_backend_selections: [
        {
          schema: "helix.capability_lane.backend_selection_summary.v1",
          requested_lane: "live_translation",
          requested_backend_provider: "live_translation.google_gemini",
          selected_backend_provider: "live_translation.local_runtime",
          selection_reason: "requested_backend_unconfigured_default_backend_selected_by_helix_policy",
          receipt_ref: "ask:lane:translation:obs:projection:receipt",
        },
      ],
      capability_lane_debug_events: [
        {
          schema: "helix.capability_lane.debug_event.v1",
          stage: "lane_observation",
          capability: "live_translation.translate_text",
          selected_backend_provider: "live_translation.local_runtime",
          observation_ref: "ask:lane:translation:obs",
          receipt_ref: "ask:lane:translation:obs:projection:receipt",
          context_role: "tool_evidence",
          terminal_eligible: false,
          assistant_answer: false,
        },
      ],
      capability_lane_turn_timeline: [
        {
          stage: "lane_visible",
          adapter_boundary: "helix_agent_provider_edge",
          selected_runtime_agent_provider: "codex",
          lane_id: "live_translation",
          capability_id: "live_translation.translate_text",
          lane_visible: true,
          lane_executed: false,
          requested_backend_provider: "google_gemini",
          requested_backend_provider_known: true,
          selected_backend_provider: "live_translation.local_runtime",
          fallback_backend_provider: "live_translation.local_runtime",
          selection_reason: "requested_backend_recorded_but_default_backend_selected_by_helix_shadow_policy",
          terminal_eligible: false,
          assistant_answer: false,
        },
        {
          stage: "lane_observation",
          lane_id: "live_translation",
          lane_executed: true,
          observation_ref: "ask:lane:translation:obs",
          receipt_ref: "ask:lane:translation:obs:projection:receipt",
          answer_authority: true,
          terminal_eligible: true,
          assistant_answer: true,
          raw_content_included: true,
        },
        {
          stage: "lane_goal_binding",
          lane_id: "live_translation",
          lane_executed: true,
          session_control_key:
            "lane-session-debug::docs:debug::sha256:debug::docs_chunk::es-US::es",
          source_binding_key: "docs:debug::sha256:debug::docs_chunk::es-US::es",
          source_identity_key: "docs:debug::sha256:debug::sha256:debug-text::128::docs::docs_chunk::es-US::es",
          lane_session_source_binding_key: "docs:debug::sha256:debug-session::docs_chunk::es-US::es",
          lane_session_source_identity_key:
            "docs:debug::sha256:debug-session::sha256:debug-text::128::docs::docs_chunk::es-US::es",
          latest_source_identity_key:
            "docs:debug::sha256:debug::sha256:latest-debug-text::64::docs::docs_chunk::es-US::es",
          source_id: "docs:debug",
          source_hash: "sha256:debug",
          source_kind: "docs",
          source_text_hash: "sha256:debug-text",
          source_text_char_count: 128,
          projection_target: "docs_chunk",
          account_locale: "es-US",
          target_language: "es",
          latest_observation_key:
            "docs:debug::sha256:debug::docs::docs_chunk::es::chunk-debug::ask:lane:translation:obs:projection:receipt",
          latest_mail_loop_observation_key:
            "docs:debug::sha256:debug::document_markdown::docs_chunk::es-US::es::chunk-debug::ask:lane:translation:obs:projection:receipt",
          observation_lane_session_id: "lane-session-debug",
          observation_ref: "ask:lane:translation:obs",
          receipt_ref: "ask:lane:translation:obs:projection:receipt",
          quiet_behavior_applied: true,
          wake_expected: true,
          surface_badge_expected: true,
          terminal_report_requested: true,
          terminal_report_authorized: false,
          context_role: "tool_evidence",
          answer_authority: true,
          terminal_eligible: true,
          assistant_answer: true,
          raw_content_included: true,
        },
        {
          stage: "lane_goal_dispatch_readiness",
          lane_id: "live_translation",
          lane_executed: false,
          session_control_key:
            "lane-session-debug::docs:debug::sha256:debug::docs_chunk::es-US::es",
          latest_source_binding_key: "docs:debug::sha256:debug::docs_chunk::es-US::es",
          answer_authority: true,
          terminal_eligible: true,
          assistant_answer: true,
          raw_content_included: true,
        },
      ],
      capability_lane_projection_receipts: [
        {
          schema: "helix.capability_lane.provider_adapter_receipt.v1",
          receipt_ref: "ask:lane:translation:obs:projection:receipt",
          observation_ref: "ask:lane:translation:obs",
          terminal_eligible: false,
          assistant_answer: false,
        },
      ],
      capability_lane_session_results: [
        {
          ok: true,
          action: "list",
          lane_session_id: "lane-session-debug",
          selected_runtime_agent_provider: "codex",
          session_supported: true,
          lane_session: null,
          blocked_reason: null,
          answer_authority: true,
          terminal_eligible: true,
          assistant_answer: true,
          raw_content_included: true,
        },
      ],
      capability_lane_session_debug_summaries: [
        {
          schema: "helix.capability_lane.session_debug_summary.v1",
          lane_session_id: "lane-session-debug",
          lane_id: "live_translation",
          session_status: "running",
          latest_event_id: "lane-session-debug:record_observation:200",
          has_observation: true,
          last_observation_ref: "ask:lane:translation:obs",
          receipt_ref: "ask:lane:translation:obs:projection:receipt",
          latest_observation_key:
            "docs:debug::sha256:debug::docs::docs_chunk::es::chunk-debug::ask:lane:translation:obs:projection:receipt",
          evidence_refs: ["legacy:session-replay"],
          terminal_eligible: false,
          assistant_answer: false,
        },
      ],
      capability_lane_goal_binding_results: [
        {
          ok: true,
          goal_binding: {
            schema: "helix.capability_lane.goal_binding.v1",
            goal_binding_id: "goal-binding-debug",
            goal_id: "goal:translate-docs",
            lane_session_id: "lane-session-debug",
            lane_id: "live_translation",
            terminal_eligible: false,
            assistant_answer: false,
            raw_content_included: false,
          },
          blocked_reason: null,
          terminal_eligible: false,
          assistant_answer: false,
          raw_content_included: false,
        },
      ],
      capability_lane_goal_binding_debug_summaries: [
        {
          schema: "helix.capability_lane.goal_binding_debug_summary.v1",
          goal_binding_id: "goal-binding-debug",
          goal_id: "goal:translate-docs",
          lane_session_id: "lane-session-debug",
          lane_id: "live_translation",
          latest_event_id: "lane-session-debug:record_observation:200",
          session_event_count: 2,
          has_observation: true,
          terminal_eligible: false,
          assistant_answer: false,
          raw_content_included: false,
          latest_mail_loop_summary: {
            schema: "helix.capability_lane.mail_loop_debug_summary.v1",
            lane_session_id: "lane-session-debug",
            observation_lane_session_id: "lane-session-debug",
            packet_count: 2,
            stage_play_wake_expected: true,
            context_role: "tool_evidence",
            answer_authority: true,
            terminal_eligible: true,
            assistant_answer: true,
            raw_content_included: true,
          },
        },
      ],
      capability_lane_goal_dispatch_readiness: {
        schema: "helix.capability_lane.goal_dispatch_readiness.v1",
        status: "ready",
        next_lane_ids: ["live_translation"],
        next_lane_session_ids: ["lane-session-debug"],
        next_latest_event_ids: ["lane-session-debug:record_observation:200"],
        next_session_event_counts: [2],
        next_has_observation: true,
        all_next_have_observation: true,
        next_evidence_refs: ["ask:lane:translation:obs"],
        next_receipt_refs: ["ask:lane:translation:obs:projection:receipt"],
      },
      runtime_lane_request_contract: {
        schema: "helix.runtime_agent_lane_request_contract.v1",
        legacy_schema: "helix.codex_runtime_lane_request_contract.v1",
        runtime_provider_adapter: "codex",
        execution_status: "lane_observation_reentered",
        observation_packet_count: 1,
      },
      runtime_lane_request_loop: {
        schema: "helix.runtime_agent_lane_request_loop.v1",
        legacy_schema: "helix.codex_runtime_lane_request_loop.v1",
        runtime_provider_adapter: "codex",
        status: "lane_observation_reentered",
        candidate: {
          capability: "live_translation.translate_text",
        },
      },
      debug: {
        turn_id: "turn-provider-projection",
      },
    });

    expect(slim).toMatchObject({
      schema: "helix.ask.live_debug_slim.v1",
      agent_runtime: "codex",
      agent_runtime_adapter_contract: {
        schema: "helix.agent_runtime_adapter_contract.v1",
      },
      capability_lane_manifest: {
        schema: "helix.capability_lane_manifest.v1",
      },
      model_visible_capability_lane_manifest: {
        schema: "helix.agent_model_visible_capability_lane_manifest.v1",
        lanes: [
          {
            lane_id: "live_translation",
            status: "dry_run",
          },
        ],
      },
      capability_lane_ids: ["utility_text", "workstation_tool_reference"],
      capability_lane_statuses: {
        utility_text: "available",
        workstation_tool_reference: "available",
      },
      capability_lane_resolve_trace_shape: {
        schema: "helix.capability_lane_resolve_trace.v1",
      },
      capability_lane_backend_selections: {
        count: 1,
        sample: [
          expect.objectContaining({
            requested_lane: "live_translation",
            requested_backend_provider: "live_translation.google_gemini",
            selected_backend_provider: "live_translation.local_runtime",
            receipt_ref: "ask:lane:translation:obs:projection:receipt",
          }),
        ],
        truncated: false,
      },
      capability_lane_debug_events: {
        count: 1,
        sample: [
          expect.objectContaining({
            stage: "lane_observation",
            capability: "live_translation.translate_text",
            receipt_ref: "ask:lane:translation:obs:projection:receipt",
            terminal_eligible: false,
            assistant_answer: false,
          }),
        ],
        truncated: false,
      },
      capability_lane_timeline_summary: {
        schema: "helix.capability_lane.timeline_summary.v1",
        event_count: 4,
        stage_sequence: ["visible", "observed", "goal", "goal_readiness"],
        stage_sequence_text: "visible > observed > goal > goal_readiness",
        visible_count: 1,
        requested_count: 0,
        backend_selected_count: 0,
        observed_count: 1,
        receipt_count: 0,
        reentered_count: 0,
        session_count: 0,
        mail_loop_count: 0,
        goal_binding_count: 1,
        observed_session_count: 0,
        observed_mail_loop_count: 0,
        observed_goal_binding_count: 1,
        observed_lane_activity_count: 2,
        goal_dispatch_plan_count: 0,
        goal_dispatch_admission_count: 0,
        goal_dispatch_readiness_count: 1,
        lane_executed_count: 2,
        visible_only_count: 1,
        observation_ref_count: 2,
        receipt_ref_count: 2,
        session_control_key_count: 2,
        source_binding_key_count: 2,
        latest_source_binding_key_count: 1,
        source_identity_key_count: 1,
        latest_source_identity_key_count: 1,
        lane_session_source_binding_key_count: 1,
        lane_session_source_identity_key_count: 1,
        latest_mail_loop_observation_key_count: 1,
        latest_observation_key_count: 1,
        observation_lane_session_id_count: 1,
        observation_reentered_count: 0,
        quiet_behavior_applied_count: 1,
        wake_expected_count: 1,
        surface_badge_expected_count: 1,
        terminal_report_requested_count: 1,
        terminal_report_authorized_count: 0,
        terminal_selected_count: 0,
        terminal_rejected_count: 0,
        console_state_rows: expect.arrayContaining([
          expect.objectContaining({
            schema: "helix.capability_lane.console_state_row.v1",
            normalized_stage: "visible",
            state_label: "visible_only",
            lane_id: "live_translation",
            capability_id: "live_translation.translate_text",
            adapter_boundary: "helix_agent_provider_edge",
            selected_runtime_agent_provider: "codex",
            requested_backend_provider: "google_gemini",
            requested_backend_provider_known: true,
            selected_backend_provider: "live_translation.local_runtime",
            fallback_backend_provider: "live_translation.local_runtime",
            backend_selection_reason: "requested_backend_recorded_but_default_backend_selected_by_helix_shadow_policy",
            lane_visible: true,
            lane_executed: false,
            terminal_eligible: false,
            assistant_answer: false,
            terminal_authority_status: "not_terminal_authority",
          }),
          expect.objectContaining({
            normalized_stage: "observed",
            selected_runtime_agent_provider: "codex",
            observation_ref: "ask:lane:translation:obs",
            receipt_ref: "ask:lane:translation:obs:projection:receipt",
            context_role: "tool_evidence",
            answer_authority: false,
            terminal_eligible: false,
            assistant_answer: false,
            raw_content_included: false,
          }),
          expect.objectContaining({
            normalized_stage: "goal_readiness",
            state_label: "goal_readiness",
            lane_id: "live_translation",
            selected_runtime_agent_provider: "codex",
            source_binding_key: "docs:debug::sha256:debug::docs_chunk::es-US::es",
            latest_source_binding_key: "docs:debug::sha256:debug::docs_chunk::es-US::es",
            evidence_refs: expect.arrayContaining([
              "lane-session-debug::docs:debug::sha256:debug::docs_chunk::es-US::es",
              "docs:debug::sha256:debug::docs_chunk::es-US::es",
            ]),
            answer_authority: false,
            terminal_eligible: false,
            assistant_answer: false,
            raw_content_included: false,
          }),
          expect.objectContaining({
            normalized_stage: "goal",
            state_label: "goal_bound_waiting_for_evidence",
            lane_id: "live_translation",
            selected_runtime_agent_provider: "codex",
            source_binding_key: "docs:debug::sha256:debug::docs_chunk::es-US::es",
            source_id: "docs:debug",
            source_hash: "sha256:debug",
            source_kind: "docs",
            source_text_hash: "sha256:debug-text",
            source_text_char_count: "128",
            source_identity_key: "docs:debug::sha256:debug::sha256:debug-text::128::docs::docs_chunk::es-US::es",
            lane_session_source_binding_key: "docs:debug::sha256:debug-session::docs_chunk::es-US::es",
            lane_session_source_identity_key:
              "docs:debug::sha256:debug-session::sha256:debug-text::128::docs::docs_chunk::es-US::es",
            evidence_refs: expect.arrayContaining([
              "lane-session-debug",
              "ask:lane:translation:obs",
              "ask:lane:translation:obs:projection:receipt",
              "docs:debug",
              "sha256:debug",
              "docs:debug::sha256:debug::docs_chunk::es-US::es",
              "docs:debug::sha256:debug::sha256:debug-text::128::docs::docs_chunk::es-US::es",
              "docs:debug::sha256:debug-session::docs_chunk::es-US::es",
              "docs:debug::sha256:debug-session::sha256:debug-text::128::docs::docs_chunk::es-US::es",
            ]),
            projection_target: "docs_chunk",
            account_locale: "es-US",
            target_language: "es",
            quiet_behavior_applied: true,
            wake_expected: true,
            surface_badge_expected: true,
            terminal_report_requested: true,
            terminal_report_authorized: false,
            context_role: "tool_evidence",
            answer_authority: false,
            terminal_eligible: false,
            assistant_answer: false,
            raw_content_included: false,
            terminal_authority_status: "not_terminal_authority",
          }),
        ]),
        console_state_rows_truncated: false,
        visible_lane_does_not_mean_executed: true,
      },
      capability_lane_projection_receipts: {
        count: 1,
        sample: [
          expect.objectContaining({
            receipt_ref: "ask:lane:translation:obs:projection:receipt",
            observation_ref: "ask:lane:translation:obs",
            terminal_eligible: false,
            assistant_answer: false,
          }),
        ],
        truncated: false,
      },
      capability_lane_goal_binding_results: {
        count: 1,
        sample: [
          expect.objectContaining({
            ok: true,
            selected_runtime_agent_provider: "codex",
            goal_binding: expect.objectContaining({
              goal_binding_id: "goal-binding-debug",
              lane_session_id: "lane-session-debug",
              lane_id: "live_translation",
            }),
            terminal_eligible: false,
            assistant_answer: false,
          }),
        ],
        truncated: false,
      },
      capability_lane_session_results: {
        count: 1,
        sample: [
          expect.objectContaining({
            ok: true,
            action: "list",
            lane_session_id: "lane-session-debug",
            selected_runtime_agent_provider: "codex",
            session_supported: true,
            lane_session: null,
            blocked_reason: null,
            evidence_refs: ["lane-session-debug"],
            context_role: "tool_evidence",
            answer_authority: false,
            terminal_eligible: false,
            assistant_answer: false,
            raw_content_included: false,
          }),
        ],
        truncated: false,
      },
      capability_lane_session_debug_summaries: {
        count: 1,
        sample: [
          expect.objectContaining({
            lane_session_id: "lane-session-debug",
            lane_id: "live_translation",
            selected_runtime_agent_provider: "codex",
            latest_event_id: "lane-session-debug:record_observation:200",
            has_observation: true,
            evidence_refs: [
            "legacy:session-replay",
            "lane-session-debug",
            "lane-session-debug:record_observation:200",
            "ask:lane:translation:obs",
            "ask:lane:translation:obs:projection:receipt",
              "docs:debug::sha256:debug::docs::docs_chunk::es::chunk-debug::ask:lane:translation:obs:projection:receipt",
            ],
            context_role: "tool_evidence",
            terminal_eligible: false,
            assistant_answer: false,
          }),
        ],
        truncated: false,
      },
      capability_lane_goal_binding_debug_summaries: {
        count: 1,
        sample: [
          expect.objectContaining({
            goal_binding_id: "goal-binding-debug",
            lane_session_id: "lane-session-debug",
            lane_id: "live_translation",
            selected_runtime_agent_provider: "codex",
            latest_event_id: "lane-session-debug:record_observation:200",
            session_event_count: 2,
            has_observation: true,
            terminal_eligible: false,
            assistant_answer: false,
          }),
        ],
        truncated: false,
      },
      capability_lane_mail_loop_debug_summaries: {
        count: 1,
        sample: [
          expect.objectContaining({
            schema: "helix.capability_lane.mail_loop_debug_summary.v1",
            lane_session_id: "lane-session-debug",
            selected_runtime_agent_provider: "codex",
            observation_lane_session_id: "lane-session-debug",
            packet_count: 2,
            stage_play_wake_kind: "mailbox_wake",
            mailbox_wake_expected: true,
            decision_wake_expected: false,
            context_role: "tool_evidence",
            answer_authority: false,
            terminal_eligible: false,
            assistant_answer: false,
            raw_content_included: false,
          }),
        ],
        truncated: false,
      },
      capability_lane_goal_dispatch_readiness: {
        schema: "helix.capability_lane.goal_dispatch_readiness.v1",
        selected_runtime_agent_provider: "codex",
        status: "ready",
        next_lane_ids: ["live_translation"],
        next_lane_session_ids: ["lane-session-debug"],
        next_latest_event_ids: ["lane-session-debug:record_observation:200"],
        next_session_event_counts: [2],
        next_has_observation: true,
        all_next_have_observation: true,
        next_evidence_refs: ["ask:lane:translation:obs"],
        next_receipt_refs: ["ask:lane:translation:obs:projection:receipt"],
      },
      runtime_lane_request_contract: {
        schema: "helix.runtime_agent_lane_request_contract.v1",
        legacy_schema: "helix.codex_runtime_lane_request_contract.v1",
        runtime_provider_adapter: "codex",
        execution_status: "lane_observation_reentered",
        observation_packet_count: 1,
      },
      runtime_lane_request_loop: {
        schema: "helix.runtime_agent_lane_request_loop.v1",
        legacy_schema: "helix.codex_runtime_lane_request_loop.v1",
        runtime_provider_adapter: "codex",
        status: "lane_observation_reentered",
        candidate: {
          capability: "live_translation.translate_text",
        },
      },
    });
  });
});
